### ISSUE TITLE
[v5.4.6.8723] System.ArgumentNullException: Value cannot be null. (Parameter 'path2')

### ISSUE THREAD

**Issue by tomerh2001** [Radarr/Radarr#10018]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Automatic import is always failing, and now manual importing is failing as well.

### Expected Behavior

for the manual import to work

### Environment

```markdown
Version: 5.4.6.8723
Package Version: 5.4.6.8723-ls217 by linuxserver.io
.NET: Yes (6.0.25)
Docker: Yes
Database :Sqlite 3.44.2
Database Migration: 236
AppData Directory: /config
Startup Directory: /app/radarr/bin
Mode: Console
Uptime: 00:08:23
```
```


### What branch are you running?

Master

### Trace Logs? **Not Optional**

```
2024-05-12 22:55:32.8|Warn|ImportApprovedMovie|Couldn't import movie /pool/media/usenet/complete/movies/The.Avengers.2012.iNTERNAL.COMPLETE.BLURAY-BUTTLERZ/The.Avengers.2012.iNTERNAL.COMPLETE.BLURAY-BUTTLERZ.iso

[v5.4.6.8723] System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at NzbDrone.Core.MediaFiles.MediaInfo.UpdateMediaInfoService.UpdateMediaInfo(MovieFile movieFile, Movie movie) in ./Radarr.Core/MediaFiles/MediaInfo/UpdateMediaInfoService.cs:line 71
   at NzbDrone.Core.Organizer.FileNameBuilder.UpdateMediaInfoIfNeeded(String pattern, MovieFile movieFile, Movie movie) in ./Radarr.Core/Organizer/FileNameBuilder.cs:line 531
   at NzbDrone.Core.Organizer.FileNameBuilder.BuildFileName(Movie movie, MovieFile movieFile, NamingConfig namingConfig, List`1 customFormats) in ./Radarr.Core/Organizer/FileNameBuilder.cs:line 114
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in ./Radarr.Core/MediaFiles/MovieFileMovingService.cs:line 75
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in ./Radarr.Core/MediaFiles/UpgradeMediaFileService.cs:line 41
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in ./Radarr.Core/MediaFiles/MovieImport/ImportApprovedMovie.cs:line 136

2024-05-12 22:55:32.9|Error|VideoFileInfoReader|Unable to parse media info from file: /pool/media/usenet/complete/movies/X-Men.Origins.Wolverine.2009.HK.BluRay.1080p.AVC.DTS-HD.MA.5.1-TAG/X-Men.Origins.Wolverine.2009.HK.BluRay.1080p.AVC.DTS-HD.MA.5.1-TAG.mkv

[v5.4.6.8723] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - [matroska,webm @ 0x35116c0] EBML header parsing failed
/pool/media/usenet/complete/movies/X-Men.Origins.Wolverine.2009.HK.BluRay.1080p.AVC.DTS-HD.MA.5.1-TAG/X-Men.Origins.Wolverine.2009.HK.BluRay.1080p.AVC.DTS-HD.MA.5.1-TAG.mkv: Invalid data found when processing input)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in ./Radarr.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs:line 140

2024-05-12 22:55:32.9|Error|DetectSample|Failed to get runtime from the file, make sure ffprobe is available
2024-05-12 22:55:32.9|Error|VideoFileInfoReader|Unable to parse media info from file: /pool/media/usenet/complete/movies/X-Men.Origins.Wolverine.2009.HK.BluRay.1080p.AVC.DTS-HD.MA.5.1-TAG/X-Men.Origins.Wolverine.2009.HK.BluRay.1080p.AVC.DTS-HD.MA.5.1-TAG.mkv

[v5.4.6.8723] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - [matroska,webm @ 0x1cf66c0] EBML header parsing failed
/pool/media/usenet/complete/movies/X-Men.Origins.Wolverine.2009.HK.BluRay.1080p.AVC.DTS-HD.MA.5.1-TAG/X-Men.Origins.Wolverine.2009.HK.BluRay.1080p.AVC.DTS-HD.MA.5.1-TAG.mkv: Invalid data found when processing input)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in ./Radarr.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs:line 140

2024-05-12 22:55:32.9|Error|VideoFileInfoReader|Unable to parse media info from file: /pool/media/usenet/complete/movies/X-Men.Origins.Wolverine.2009.HK.BluRay.1080p.AVC.DTS-HD.MA.5.1-TAG/X-Men.Origins.Wolverine.2009.HK.BluRay.1080p.AVC.DTS-HD.MA.5.1-TAG.mkv

[v5.4.6.8723] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - [matroska,webm @ 0x1a536c0] EBML header parsing failed
/pool/media/usenet/complete/movies/X-Men.Origins.Wolverine.2009.HK.BluRay.1080p.AVC.DTS-HD.MA.5.1-TAG/X-Men.Origins.Wolverine.2009.HK.BluRay.1080p.AVC.DTS-HD.MA.5.1-TAG.mkv: Invalid data found when processing input)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in ./Radarr.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs:line 140

2024-05-12 22:55:32.9|Error|DetectSample|Failed to get runtime from the file, make sure ffprobe is available
2024-05-12 22:55:32.9|Warn|ImportApprovedMovie|Couldn't import movie /pool/media/usenet/complete/movies/Justice.League.Crisis.on.Infinite.Earths.Part.Two.2024.COMPLETE.BLURAY-iNTEGRUM/Justice.League.Crisis.on.Infinite.Earths.Part.Two.2024.COMPLETE.BLURAY-iNTEGRUM.iso

[v5.4.6.8723] System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at NzbDrone.Core.MediaFiles.MediaInfo.UpdateMediaInfoService.UpdateMediaInfo(MovieFile movieFile, Movie movie) in ./Radarr.Core/MediaFiles/MediaInfo/UpdateMediaInfoService.cs:line 71
   at NzbDrone.Core.Organizer.FileNameBuilder.UpdateMediaInfoIfNeeded(String pattern, MovieFile movieFile, Movie movie) in ./Radarr.Core/Organizer/FileNameBuilder.cs:line 531
   at NzbDrone.Core.Organizer.FileNameBuilder.BuildFileName(Movie movie, MovieFile movieFile, NamingConfig namingConfig, List`1 customFormats) in ./Radarr.Core/Organizer/FileNameBuilder.cs:line 114
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in ./Radarr.Core/MediaFiles/MovieFileMovingService.cs:line 75
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in ./Radarr.Core/MediaFiles/UpgradeMediaFileService.cs:line 41
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in ./Radarr.Core/MediaFiles/MovieImport/ImportApprovedMovie.cs:line 136
```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by tomerh2001** [comment]
> Looks like you're importing unsupported media like ISO and the mkv files are actually corrupted.

Shouldn't there be anything prompted to the use in this case? after pressing import, I am just navigated back to the history with nothing changed, only to to try again and .... the loop continues

**Comment by tomerh2001** [comment]
> Post some trace logs with a failed attempt of a manual import, because sadly what you posted isn't that helpful.

Here's the fully downloaded log: [radarr.txt](https://github.com/Radarr/Radarr/files/15287623/radarr.txt)

Does that help?

**Comment by tomerh2001** [comment]
> Are those trace logs?

I'm not that frequently here. What does that mean? Just tell me what to do, and I'll send
