### ISSUE TITLE
add tv from IMDb Lists fail

### ISSUE THREAD

**Issue by tcdj2014** [Radarr/Radarr#10012]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

# Description:

When trying to add tv from IMDb Lists on windows it doesn't find any movies but gives a page of warnings in log.

### Expected Behavior

 IMDb Lists add

### Environment

```markdown
- List/User ID: ls545123647
- Radarr Version: 5.4.6.8723
- OS: Windows 10 22H2
- Browser: EDGE
- Database: Sqlite 3.36.0
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

# ERROR:
```
Couldn't map movie  to a movie on The Movie DB. It will not be added :(: Movie with IMDBId tt0279600 was not found, it may have been removed from TMDb.

NzbDrone.Core.Exceptions.MovieNotFoundException: Movie with IMDBId tt0279600 was not found, it may have been removed from TMDb.
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieByImdbId(String imdbId) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 212
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie(MovieMetadata movie) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 367
```
# /radarr.trace log:
```
2024-05-10 23:56:02.3|Trace|HttpClient|Req: [GET] https://api.radarr.video/v1/movie/imdb/tt0279600
2024-05-10 23:56:02.3|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2024-05-10 23:56:02.3|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2024-05-10 23:56:02.3|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2024-05-10 23:56:02.3|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2024-05-10 23:56:02.8|Trace|HttpClient|Res: HTTP/2.0 [GET] https://api.radarr.video/v1/movie/imdb/tt0279600: 404.NotFound (2 bytes)
[] (480 ms)
2024-05-10 23:56:02.8|Warn|SkyHookProxy|Couldn't map movie  to a movie on The Movie DB. It will not be added :(

[v5.4.6.8723] NzbDrone.Core.Exceptions.MovieNotFoundException: Movie with IMDBId tt0279600 was not found, it may have been removed from TMDb.
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieByImdbId(String imdbId) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 212
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie(MovieMetadata movie) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 367
```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Radarr does not and will never support tv. That is what Sonarr is for.

tmdb must have the movie's imdbid associated with it for movies to be added via imdbid

**Comment by imTHAI** [comment]
@mynameisbogdan  Hello,

I don't know if @tcdj2014 tries to add a show into Radarr but I have a similar problem with a movie.
I can find it in Radarr
<img width="740" alt="image" src="https://github.com/Radarr/Radarr/assets/36070606/dc9ca4ba-09ff-4692-a096-754b1ccd40ee">
But I can't add it:
```
[Error] AddMovieService: TmdbId 1291491 was not found, it may have been removed from TMDb. Path:  
[Warn] RadarrErrorPipeline: Invalid request Validation failed: 
 -- TmdbId: A movie with this ID was not found. Path:  
```

So it means we can search for a movie into imdb and TMdb but if it does not exist (yet) in TMdb, we can't add it ?

**Comment by bakerboy448** [comment]
Please use [Discord](https://radarr.video/discord) for support/questions.

**Comment by imTHAI** [comment]
@bakerboy448  ok thks. I don't understand why we have the possibility to make search based on imdb references (imdb:tt32094375) if only tmdb is actually used by the app. I'll check on discord in the futur.

**Comment by bakerboy448** [comment]
IMDb id is supported if and only if the tmdb entry has the imdbid added

**Comment by imTHAI** [comment]
@mynameisbogdan Hello,
It's now available on themoviedb.org but with another number https://www.themoviedb.org/movie/1296838-die-hart-2-die-harter 
Does it happen often ? First time I personally encounter this problem
