### ISSUE TITLE
mdblists stopped working - Unable to connect to import list: Error converting value {null} 

### ISSUE THREAD

**Issue by subexx** [Radarr/Radarr#10028]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Getting error Unable to connect to import list: Error converting value {null} to type 'System.Int32'. Path '[49].id', line 1, position 7115.. Check the log surrounding this error for details for multiple lists. 

### Expected Behavior

Used to work before.

### Steps To Reproduce

Add custom list. Example list. https://mdblist.com/lists/subinjosepht/malayalam-from-2023

### Environment

```markdown
OS: Ubuntu 22.04
Radarr: Radarr 5.6.0.8846
Docker Install: Yes
Using Reverse Proxy: No
Browser: 
Database: Sqlite 3.44.2
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[Warn] RadarrListImport: Unable to connect to import list 
[v5.6.0.8846] Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Int32'. Path '[156].id', line 1, position 23073.
 ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at NzbDrone.Core.ImportLists.RadarrList.RadarrListParser.ParseResponse(ImportListResponse importListResponse) in ./Radarr.Core/ImportLists/RadarrList/RadarrListParser.cs:line 23
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchPage(ImportListRequest request, IParseImportListResponse parser) in ./Radarr.Core/ImportLists/HttpImportListBase.cs:line 185
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.TestConnection() in ./Radarr.Core/ImportLists/HttpImportListBase.cs:line 213
[Warn] RadarrErrorPipeline: Invalid request Validation failed: 
 -- : Unable to connect to import list: Error converting value {null} to type 'System.Int32'. Path '[156].id', line 1, position 23073.. Check the log surrounding this error for details. 

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by subexx** [comment]
Nevermind. It started working this morning.
