### ISSUE TITLE
Not able to update Radarr

### ISSUE THREAD

**Issue by recoi1er** [Radarr/Radarr#10047]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Trying to update Radarr from v4.2.4.6635 to v5.6.0.8846 and the process shows as working, no errors, but it just doesn't complete

### Expected Behavior

I click update (or let the auto update feature work) and it should update

### Steps To Reproduce

Click update in Radarr Settings, it processes but nothing happens.

I saw a post on here or Reddit that said to shutdown Sonarr during the update which I tried as well and no change

### Environment

```markdown
- OS: MacOS 14.5
- Radarr: 4.2.4.6635
- Docker Install: n/a
- Using Reverse Proxy: n/a
- Browser: Firefox v126.0
- Database: Sqlite 3.36.0
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

```
2024-05-24 15:08:50.1|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.2.4.6635] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Radarr.Api.V3.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 205
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 191
   at Radarr.Api.V3.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 68
   at lambda_method197(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

The log above contains "trace" but the issue at hand is noted below of the update processing without any errors:

```
2024-05-24 16:02:02.5|Info|LifecycleService|Restart requested.
2024-05-24 16:02:02.8|Info|Bootstrap|Starting Radarr - /Applications/Radarr.app/Contents/MacOS/Radarr - Version 4.2.4.6635
2024-05-24 16:02:03.1|Info|MigrationController|*** Migrating data source=/Users/komedia/.config/Radarr/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Truncate;pooling=True;version=3;Full FSync=True ***
2024-05-24 16:02:03.2|Info|MigrationController|*** Migrating data source=/Users/komedia/.config/Radarr/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Truncate;pooling=True;version=3;Full FSync=True ***
2024-05-24 16:02:03.6|Info|CommandExecutor|Starting 2 threads for tasks.
2024-05-24 16:02:07.7|Info|InstallUpdateService|Deleting old update files
2024-05-24 16:02:07.8|Info|InstallUpdateService|Downloading update 5.6.0.8846
2024-05-24 16:02:15.2|Info|InstallUpdateService|Verifying update package
2024-05-24 16:02:15.3|Info|InstallUpdateService|Update package verified successfully
2024-05-24 16:02:15.3|Info|InstallUpdateService|Extracting Update package
2024-05-24 16:02:17.2|Info|InstallUpdateService|Update package extracted successfully
2024-05-24 16:02:17.2|Info|BackupService|Starting Backup
2024-05-24 16:02:22.4|Info|InstallUpdateService|Preparing client
2024-05-24 16:02:22.5|Info|InstallUpdateService|Starting update client /var/folders/0d/n0x9mw8n7gb4sn5f35v6rjcw0000gn/T/radarr_update/Radarr.Update
2024-05-24 16:02:22.5|Info|InstallUpdateService|Radarr will restart shortly.
2024-05-24 16:02:46.2|Info|DiskScanService|Scanning disk for The Hunt for Red October
2024-05-24 16:02:46.3|Info|DiskScanService|Completed scanning disk for The Hunt for Red October
2024-05-24 16:02:46.3|Info|ExistingMetadataImporter|Found 0 existing metadata files
2024-05-24 16:02:46.3|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
2024-05-24 16:02:46.3|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
2024-05-24 16:02:46.3|Info|ExistingExtraFileService|Found 2 possible extra files, imported 2 files.
2024-05-24 16:05:57.7|Info|InstallUpdateService|Deleting old update files
2024-05-24 16:05:57.7|Info|InstallUpdateService|Downloading update 5.6.0.8846
2024-05-24 16:06:04.4|Info|InstallUpdateService|Verifying update package
2024-05-24 16:06:04.4|Info|InstallUpdateService|Update package verified successfully
2024-05-24 16:06:04.4|Info|InstallUpdateService|Extracting Update package
2024-05-24 16:06:06.3|Info|InstallUpdateService|Update package extracted successfully
2024-05-24 16:06:06.3|Info|BackupService|Starting Backup
2024-05-24 16:06:11.4|Info|InstallUpdateService|Preparing client
2024-05-24 16:06:11.5|Info|InstallUpdateService|Starting update client /var/folders/0d/n0x9mw8n7gb4sn5f35v6rjcw0000gn/T/radarr_update/Radarr.Update
2024-05-24 16:06:11.5|Info|InstallUpdateService|Radarr will restart shortly.
```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Just reinstall in place over existing to upgrade.

If you have the updater logs those would be helpful, most likely some security app is killing the updater

**Comment by recoi1er** [comment]
> Just reinstall in place over existing to upgrade.
> 
> If you have the updater logs those would be helpful, most likely some security app is killing the updater

The updater log section is blank. I don't have any security app other than whatever MacOS ships with but I would be happy to inspect further if you have any known things to check?


Reinstall seems to have worked. Now onto fix Bazarr which I will open a ticket for on its page!
