### ISSUE TITLE
[Error] EventAggregator: NotificationService failed while processing [ManualInteractionRequiredEvent] 

### ISSUE THREAD

**Issue by ngosang** [Radarr/Radarr#10053]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I see an error in the logs after updating to version 5.6.0.8846.
It looks like the app is working fine.

### Expected Behavior

.

### Environment

```markdown
- OS: 
- Radarr: 
- Docker Install: 
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[Info] Bootstrap: Starting Radarr - /app/radarr/bin/Radarr - Version 5.6.0.8846 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] MigrationController: *** Migrating data source=/config/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 *** 
[Info] FluentMigrator.Runner.MigrationRunner: DatabaseEngineVersionCheck migrating 
[Info] FluentMigrator.Runner.MigrationRunner: PerformDBOperation  
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Performing DB Operation 
[Info] DatabaseEngineVersionCheck: SQLite 3.44.2 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.2774084s 
[Info] FluentMigrator.Runner.MigrationRunner: DatabaseEngineVersionCheck migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.2883395s 
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 *** 
[Info] FluentMigrator.Runner.MigrationRunner: DatabaseEngineVersionCheck migrating 
[Info] FluentMigrator.Runner.MigrationRunner: PerformDBOperation  
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Performing DB Operation 
[Info] DatabaseEngineVersionCheck: SQLite 3.44.2 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0209416s 
[Info] FluentMigrator.Runner.MigrationRunner: DatabaseEngineVersionCheck migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0220201s 
[Info] Microsoft.Hosting.Lifetime: Now listening on: http://[::]:7878 
[ls.io-init] done.
[Info] CommandExecutor: Starting 2 threads for tasks. 
[Info] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down. 
[Info] Microsoft.Hosting.Lifetime: Hosting environment: Production 
[Info] Microsoft.Hosting.Lifetime: Content root path: /app/radarr/bin 
[Info] ManagedHttpDispatcher: IPv4 is available: True, IPv6 will be disabled 
[Error] EventAggregator: NotificationService failed while processing [ManualInteractionRequiredEvent] 
[v5.6.0.8846] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Notifications.NotificationService.Handle(ManualInteractionRequiredEvent message) in ./Radarr.Core/Notifications/NotificationService.cs:line 257
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by ngosang** [comment]
```
2024-05-31 10:55:29.4|Debug|Parser|Edition parsed: 
2024-05-31 10:55:29.4|Debug|AggregateLanguages|Language couldn't be parsed from release, fallback to movie original language: English
2024-05-31 10:55:29.4|Debug|AggregateLanguages|Selected languages: English
2024-05-31 10:55:29.4|Debug|TrackedDownloadService|Tracking 'qBittorrent:wonka.2023.web dl.1080p.x265.10bit.esp.ing.eac3.subs.mkv': ClientState=Completed (readonly) RadarrStage=Imported Movie='wonka - 2023 WEBDL-1080p v1' OutputPath=/media/hdd_raid/DOWNLOADS/_MOVIES/wonka.2023.web dl.1080p.x265.10bit.esp.ing.eac3.subs.mkv.
2024-05-31 10:55:29.4|Debug|Parser|Parsing string 'Las Virgenes Suicidas [DVDRIP][Spanish]'
2024-05-31 10:55:29.6|Debug|Parser|Unable to parse Las Virgenes Suicidas [DVDRIP][Spanish]
2024-05-31 10:55:29.6|Debug|Parser|Parsing string 'Las Virgenes Suicidas [DVDRIP][Spanish][www.pctestrenos.com]'
2024-05-31 10:55:29.6|Debug|Parser|Unable to parse Las Virgenes Suicidas [DVDRIP][Spanish][www.pctestrenos.com]
2024-05-31 10:55:29.6|Trace|TrackedDownloadService|No Movie found for download 'Las Virgenes Suicidas [DVDRIP][Spanish]'
2024-05-31 10:55:29.6|Debug|TrackedDownloadService|Tracking 'qBittorrent:Las Virgenes Suicidas [DVDRIP][Spanish]': ClientState=Completed (readonly) RadarrStage=Imported Movie='' OutputPath=/media/hdd_raid/DOWNLOADS/_MOVIES/Las Virgenes Suicidas [DVDRIP][Spanish]/Las Virgenes Suicidas [DVDRIP][Spanish][www.pctestrenos.com].avi.
2024-05-31 10:55:29.6|Debug|Parser|Parsing string 'Fallen Leaves (2023) WEB-DL 1080p AAC 2.0 H.264-LMain .mkv'
2024-05-31 10:55:29.6|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2024-05-31 10:55:29.6|Debug|Parser|Movie Parsed. Fallen Leaves - 2023 
2024-05-31 10:55:29.6|Debug|Parser|Release Group parsed: LMain
2024-05-31 10:55:29.6|Debug|Parser|Languages parsed: Unknown
2024-05-31 10:55:29.6|Debug|QualityParser|Trying to parse quality for 'Fallen Leaves (2023) WEB-DL 1080p AAC 2.0 H.264-LMain .mkv'
2024-05-31 10:55:29.6|Debug|Parser|Quality parsed: WEBDL-1080p v1
2024-05-31 10:55:29.6|Debug|Parser|Edition parsed: 
2024-05-31 10:55:29.6|Debug|AggregateLanguages|Language couldn't be parsed from release, fallback to movie original language: Finnish
2024-05-31 10:55:29.6|Debug|AggregateLanguages|Selected languages: Finnish
2024-05-31 10:55:29.6|Debug|TrackedDownloadService|Tracking 'qBittorrent:Fallen Leaves (2023) WEB-DL 1080p AAC 2.0 H.264-LMain .mkv': ClientState=Completed (readonly) RadarrStage=Imported Movie='Fallen Leaves - 2023 WEBDL-1080p v1' OutputPath=/media/hdd_raid/DOWNLOADS/_MOVIES/Fallen Leaves (2023) WEB-DL 1080p AAC 2.0 H.264-LMain .mkv.
2024-05-31 10:55:29.6|Debug|Parser|Parsing string 'Pobres Criaturas (2023) BDRip 1080p.mkv'
2024-05-31 10:55:29.6|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2024-05-31 10:55:29.6|Debug|Parser|Movie Parsed. Pobres Criaturas - 2023 
2024-05-31 10:55:29.6|Debug|Parser|Release Group parsed: 
2024-05-31 10:55:29.6|Debug|Parser|Languages parsed: Unknown
2024-05-31 10:55:29.6|Debug|QualityParser|Trying to parse quality for 'Pobres Criaturas (2023) BDRip 1080p.mkv'
2024-05-31 10:55:29.6|Debug|Parser|Quality parsed: Bluray-1080p v1
2024-05-31 10:55:29.6|Debug|Parser|Edition parsed: 
2024-05-31 10:55:29.6|Debug|AggregateLanguages|Language couldn't be parsed from release, fallback to movie original language: English
2024-05-31 10:55:29.6|Debug|AggregateLanguages|Selected languages: English
2024-05-31 10:55:29.6|Debug|TrackedDownloadService|Tracking 'qBittorrent:Pobres Criaturas (2023) BDRip 1080p.mkv': ClientState=Completed (readonly) RadarrStage=Imported Movie='Pobres Criaturas - 2023 Bluray-1080p v1' OutputPath=/media/hdd_raid/DOWNLOADS/_MOVIES/Pobres Criaturas (2023) BDRip 1080p.mkv.
2024-05-31 10:55:29.6|Debug|Parser|Parsing string 'Vesper.mkv'
2024-05-31 10:55:29.6|Debug|Parser|Unable to parse Vesper.mkv
2024-05-31 10:55:29.6|Trace|TrackedDownloadService|No Movie found for download 'Vesper.mkv'
2024-05-31 10:55:29.6|Debug|TrackedDownloadService|Tracking 'qBittorrent:Vesper.mkv': ClientState=Completed (readonly) RadarrStage=Downloading Movie='' OutputPath=/media/hdd_raid/DOWNLOADS/_MOVIES/Vesper.mkv.
2024-05-31 10:55:29.7|Debug|Parser|Parsing string 'Vesper.mkv'
2024-05-31 10:55:29.7|Debug|Parser|Unable to parse Vesper.mkv
2024-05-31 10:55:29.7|Trace|EventAggregator|Publishing ManualInteractionRequiredEvent
2024-05-31 10:55:29.7|Trace|EventAggregator|ManualInteractionRequiredEvent -> NotificationService
2024-05-31 10:55:29.7|Error|EventAggregator|NotificationService failed while processing [ManualInteractionRequiredEvent]

[v5.6.0.8846] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Notifications.NotificationService.Handle(ManualInteractionRequiredEvent message) in ./Radarr.Core/Notifications/NotificationService.cs:line 257
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


2024-05-31 10:55:29.8|Trace|EventAggregator|ManualInteractionRequiredEvent -> DownloadMonitoringService
2024-05-31 10:55:29.8|Trace|EventAggregator|ManualInteractionRequiredEvent <- DownloadMonitoringService
2024-05-31 10:55:29.8|Debug|Parser|Parsing string 'Mi Crimen (2023) BDRip 1080p x265.mkv'
2024-05-31 10:55:29.8|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2024-05-31 10:55:29.8|Debug|Parser|Movie Parsed. Mi Crimen - 2023 
2024-05-31 10:55:29.8|Debug|Parser|Release Group parsed: 
2024-05-31 10:55:29.8|Debug|Parser|Languages parsed: Unknown
2024-05-31 10:55:29.8|Debug|QualityParser|Trying to parse quality for 'Mi Crimen (2023) BDRip 1080p x265.mkv'
2024-05-31 10:55:29.8|Debug|Parser|Quality parsed: Bluray-1080p v1
2024-05-31 10:55:29.8|Debug|Parser|Edition parsed: 
2024-05-31 10:55:29.9|Debug|AggregateLanguages|Language couldn't be parsed from release, fallback to movie original language: French
2024-05-31 10:55:29.9|Debug|AggregateLanguages|Selected languages: French
2024-05-31 10:55:29.9|Debug|TrackedDownloadService|Tracking 'qBittorrent:Mi Crimen (2023) BDRip 1080p x265.mkv': ClientState=Completed (readonly) RadarrStage=Imported Movie='Mi Crimen - 2023 Bluray-1080p v1' OutputPath=/media/hdd_raid/DOWNLOADS/_MOVIES/Mi Crimen (2023) BDRip 1080p x265.mkv.
2024-05-31 10:55:29.9|Debug|Parser|Parsing string 'Una.joven.prometedora.2020.mHD.10Bits.1080p.BluRay.DD5.1.x265-TMd.mkv'
2024-05-31 10:55:29.9|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2024-05-31 10:55:29.9|Debug|Parser|Movie Parsed. Una joven prometedora - 2020 
2024-05-31 10:55:29.9|Debug|Parser|Release Group parsed: TMd
2024-05-31 10:55:29.9|Debug|Parser|Languages parsed: Unknown
```
