### ISSUE TITLE
Jackett Indexer Tests ok, but errors on Save

### ISSUE THREAD

**Issue by henryschade** [Radarr/Radarr#10061]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Just upgraded Synology NAS to DSM 7.2 tonight.
All installed software upgraded/repaired fine.
Radarr is now version 5.6.0.8846 (required clicking the Synology Repair button), and at a quick look has all the movies it had before.

Jackett was also a repair update, but functions fine, via it's interface (and via Sonarr 2.0.0.5344 on the windows desktop).
In Radarr I opened the "Jackett" indexer and clicked the "Test" button and get a green check mark. I then click the Save button and get a red exclamation mark and the Indexer settings window stays open.

### Expected Behavior

Clicking the Test button gets a green check mark, and clicking the Save button closes the Indexer settings window.

### Steps To Reproduce

Synology NAS to DSM 7.2
Radarr version 5.6.0.8846
Jackett version 0.22.43

### Environment

```markdown
- OS: Linux (Synology NAS, DSM 7.2)
- Radarr: yes
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Default
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[v5.6.0.8846] NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [GET] at [http://10.1.1.4:9117/api/v2.0/indexers/iptorrents/results/torznab/api?t=movie&cat=2000,100006,100007,100020,100048,100062,100077,100089,100090,100100&extended=1&apikey=(removed)&offset=0&limit=100]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Radarr.Common/Http/HttpClient.cs:line 119
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Radarr.Core/Indexers/HttpIndexerBase.cs:line 335
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Radarr.Core/Indexers/HttpIndexerBase.cs:line 317
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Radarr.Core/Indexers/HttpIndexerBase.cs:line 458
<?xml version="1.0" encoding="UTF-8"?>
<error code="900" description="System.NullReferenceException: Object reference not set to an instance of an object.&#xA;   at Jackett.Server.Controllers.ResultsController.&lt;&gt;c__DisplayClass18_0.&lt;Torznab&gt;b__3(ReleaseInfo r) in ./Jackett.Server/Controllers/ResultsController.cs:line 449&#xA;   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)&#xA;   at System.Linq.Enumerable.SelectListIterator`2.ToList()&#xA;   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 454" />

2024-06-03 21:32:37.8|Warn|HttpClient|HTTP Error - Res: HTTP/1.1 [GET] http://10.1.1.5:60936/gui/?token=(removed)&list=1&cid=1582896849: 400.BadRequest (17 bytes)
2024-06-03 21:33:48.8|Warn|HttpClient|HTTP Error - Res: HTTP/1.1 [GET] http://10.1.1.4:9117/api/v2.0/indexers/iptorrents/results/torznab/api?t=movie&cat=2030,2040,2045,2050,2070,2080,100006,100007,100008,100020,100048,100054,100062,100077,100081,100088,100089,100090,100100,100101&extended=1&apikey=(removed)&offset=0&limit=100: 400.BadRequest (665 bytes)
<?xml version="1.0" encoding="UTF-8"?>
<error code="900" description="System.NullReferenceException: Object reference not set to an instance of an object.&#xA;   at Jackett.Server.Controllers.ResultsController.&lt;&gt;c__DisplayClass18_0.&lt;Torznab&gt;b__3(ReleaseInfo r) in ./Jackett.Server/Controllers/ResultsController.cs:line 449&#xA;   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)&#xA;   at System.Linq.Enumerable.SelectListIterator`2.ToList()&#xA;   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 454" />
2024-06-03 21:33:48.8|Warn|Torznab|Unable to connect to indexer

[v5.6.0.8846] NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [GET] at [http://10.1.1.4:9117/api/v2.0/indexers/iptorrents/results/torznab/api?t=movie&cat=2030,2040,2045,2050,2070,2080,100006,100007,100008,100020,100048,100054,100062,100077,100081,100088,100089,100090,100100,100101&extended=1&apikey=(removed)&offset=0&limit=100]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Radarr.Common/Http/HttpClient.cs:line 119
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Radarr.Core/Indexers/HttpIndexerBase.cs:line 335
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Radarr.Core/Indexers/HttpIndexerBase.cs:line 317
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Radarr.Core/Indexers/HttpIndexerBase.cs:line 458
<?xml version="1.0" encoding="UTF-8"?>
<error code="900" description="System.NullReferenceException: Object reference not set to an instance of an object.&#xA;   at Jackett.Server.Controllers.ResultsController.&lt;&gt;c__DisplayClass18_0.&lt;Torznab&gt;b__3(ReleaseInfo r) in ./Jackett.Server/Controllers/ResultsController.cs:line 449&#xA;   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)&#xA;   at System.Linq.Enumerable.SelectListIterator`2.ToList()&#xA;   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 454" />

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by henryschade** [comment]
Screen cap of the error that appears at the top of the Indexer screen when clicking the save button.

![image](https://github.com/Radarr/Radarr/assets/15196226/aea63d3c-1244-4a83-96dd-b4822a6332d5)

**Comment by henryschade** [comment]
The whole log file
[radarr.txt](https://github.com/user-attachments/files/15542380/radarr.txt)
