### ISSUE TITLE
File Move Fails - extra parenthesis after date

### ISSUE THREAD

**Issue by GenerateUN** [Radarr/Radarr#10063]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Completed downloads of files fail to import with [System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/Backing Up Media Name (1996))/Backing Up Media Name (1996) Bluray-1080p.mp4'.] The folder is created correctly, but it appears the DiskTransferService|Copy command fails due to an extra parenthesis after the date in the destination folder name. The folder on disk does not have the extra parenthesis but the log shows that the transfer command is expecting it as above.

### Expected Behavior

Files are moved to media folder after download.

### Steps To Reproduce

add any movie. after download completes, every movie downloaded since about 2 weeks ago fails with this issue and similar log entries. Sonarr is not affected. Radarr application is aware of the failure and repeats move attempts.

### Environment

```markdown
- OS: UNRAID 6.12.10
- Radarr: v5.6.0.8846
- Docker Install: yes (binhex-radarr)
- Using Reverse Proxy: yes
- Browser: na
- Database: Sqlite 3.45.3
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

Note: The Issue is visible at 2024-06-05 21:06:26.8|Debug|DiskTransferService|Copy [/data/The Name of the Movie (1967) [1080p]/The.Name.of.the.Movie.1967.1080p.BluRay.x264.YIFY.mp4] > [/media/The Name of the Movie (1967))/The Name of the Movie (1967) Bluray-1080p.mp4] . Note extra parenthesis in destination side > [/media/The Name of the Movie (1967)) <-- extra parenthesis

Trace Log for one movie:
2024-06-05 21:06:25.8|Debug|DownloadedMovieImportService|Processing path: /data/The Name of the Movie (1967) [1080p]
2024-06-05 21:06:25.8|Debug|Parser|Parsing string 'The Name of the Movie (1967) [1080p]'
2024-06-05 21:06:25.8|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2024-06-05 21:06:25.8|Debug|Parser|Movie Parsed. The Name of the Movie - 1967 
2024-06-05 21:06:25.9|Debug|Parser|Release Group parsed: 1080p
2024-06-05 21:06:25.9|Debug|Parser|Languages parsed: Unknown
2024-06-05 21:06:25.9|Debug|QualityParser|Trying to parse quality for 'The Name of the Movie (1967) [1080p]'
2024-06-05 21:06:25.9|Debug|Parser|Quality parsed: HDTV-1080p v1
2024-06-05 21:06:25.9|Debug|Parser|Edition parsed: 
2024-06-05 21:06:25.9|Debug|DownloadedMovieImportService|The Name of the Movie (1967) [1080p] folder quality: HDTV-1080p v1
2024-06-05 21:06:26.0|Debug|DiskScanService|Scanning '/data/The Name of the Movie (1967) [1080p]' for video files
2024-06-05 21:06:26.0|Trace|DiskScanService|2 files were found in /data/The Name of the Movie (1967) [1080p]
2024-06-05 21:06:26.0|Debug|DiskScanService|1 video files were found in /data/The Name of the Movie (1967) [1080p]
2024-06-05 21:06:26.0|Debug|ImportDecisionMaker|Analyzing 1/1 files.
2024-06-05 21:06:26.0|Debug|Parser|Parsing string 'The Name of the Movie (1967) [1080p]'
2024-06-05 21:06:26.0|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2024-06-05 21:06:26.0|Debug|Parser|Movie Parsed. The Name of the Movie - 1967 
2024-06-05 21:06:26.1|Debug|Parser|Release Group parsed: 1080p
2024-06-05 21:06:26.1|Debug|Parser|Languages parsed: Unknown
2024-06-05 21:06:26.1|Debug|QualityParser|Trying to parse quality for 'The Name of the Movie (1967) [1080p]'
2024-06-05 21:06:26.1|Debug|Parser|Quality parsed: HDTV-1080p v1
2024-06-05 21:06:26.1|Debug|Parser|Edition parsed: 
2024-06-05 21:06:26.1|Debug|VideoFileInfoReader|Getting media info from /data/The Name of the Movie (1967) [1080p]/The.Name.of.the.Movie.1967.1080p.BluRay.x264.YIFY.mp4
2024-06-05 21:06:26.2|Debug|DetectSample|[/data/The Name of the Movie (1967) [1080p]/The.Name.of.the.Movie.1967.1080p.BluRay.x264.YIFY.mp4] does not appear to be a sample. Runtime 02:25:23.1720000 seconds is more than minimum of 600 seconds
2024-06-05 21:06:26.2|Debug|Parser|Parsing string 'The.Name.of.the.Movie.1967.1080p.BluRay.x264.YIFY.mp4'
2024-06-05 21:06:26.2|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2024-06-05 21:06:26.3|Debug|Parser|Movie Parsed. The Name of the Movie - 1967 
2024-06-05 21:06:26.3|Debug|Parser|Release Group parsed: YIFY
2024-06-05 21:06:26.3|Debug|Parser|Languages parsed: Unknown
2024-06-05 21:06:26.3|Debug|QualityParser|Trying to parse quality for 'The.Name.of.the.Movie.1967.1080p.BluRay.x264.YIFY.mp4'
2024-06-05 21:06:26.3|Debug|Parser|Quality parsed: Bluray-1080p v1
2024-06-05 21:06:26.3|Debug|Parser|Edition parsed: 
2024-06-05 21:06:26.4|Debug|VideoFileInfoReader|Getting media info from /data/The Name of the Movie (1967) [1080p]/The.Name.of.the.Movie.1967.1080p.BluRay.x264.YIFY.mp4
2024-06-05 21:06:26.4|Trace|AggregateLanguage|Considering Languages Unknown (Filename) from FileName
2024-06-05 21:06:26.4|Trace|AggregateLanguage|Considering Languages Unknown (Foldername) from FolderName
2024-06-05 21:06:26.4|Trace|AggregateLanguage|Considering Languages Unknown (DownloadClientItem) from DownloadClientItem
2024-06-05 21:06:26.5|Trace|AggregateLanguage|Considering Languages English (MediaInfo) from MediaInfo
2024-06-05 21:06:26.5|Debug|AggregateLanguage|Selected languages: English
2024-06-05 21:06:26.5|Trace|AggregateQuality|Considering Source BLURAY (Tag) Resolution 1080 (Tag) Revision v1 from FileName
2024-06-05 21:06:26.5|Trace|AggregateQuality|Considering Source TV (Fallback) Resolution 1080 (Tag) Revision v1 from FolderName
2024-06-05 21:06:26.5|Trace|AggregateQuality|Considering Source TV (Fallback) Resolution 1080 (Tag) Revision v1 from DownloadClientItem
2024-06-05 21:06:26.5|Trace|AugmentQualityFromMediaInfo|Resolution 1920x816 considered 1080p
2024-06-05 21:06:26.5|Trace|AggregateQuality|Considering Source UNKNOWN (Default) Resolution 1080 (MediaInfo) Revision  from MediaInfo
2024-06-05 21:06:26.5|Trace|AggregateQuality|Selected Source BLURAY (Tag) Resolution 1080 (MediaInfo) Revision v1
2024-06-05 21:06:26.5|Debug|AggregateQuality|Using quality: Bluray-1080p v1
2024-06-05 21:06:26.5|Debug|AlreadyImportedSpecification|Skipping already imported check for movie without file
2024-06-05 21:06:26.6|Trace|ConfigService|Using default config value for 'skipfreespacecheckwhenimporting' defaultValue:'False'
2024-06-05 21:06:26.6|Trace|ConfigService|Using default config value for 'minimumfreespacewhenimporting' defaultValue:'100'
2024-06-05 21:06:26.6|Debug|GrabbedReleaseQualitySpecification|No grabbed history for this download client item
2024-06-05 21:06:26.6|Debug|VideoFileInfoReader|Getting media info from /data/The Name of the Movie (1967) [1080p]/The.Name.of.the.Movie.1967.1080p.BluRay.x264.YIFY.mp4
2024-06-05 21:06:26.7|Debug|DetectSample|[/data/The Name of the Movie (1967) [1080p]/The.Name.of.the.Movie.1967.1080p.BluRay.x264.YIFY.mp4] does not appear to be a sample. Runtime 02:25:23.1720000 seconds is more than minimum of 600 seconds
2024-06-05 21:06:26.7|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
2024-06-05 21:06:26.7|Trace|ConfigService|Using default config value for 'downloadpropersandrepacks' defaultValue:'PreferAndUpgrade'
2024-06-05 21:06:26.7|Debug|ImportDecisionMaker|File accepted
2024-06-05 21:06:26.7|Debug|ImportApprovedMovie|Decisions: 1
2024-06-05 21:06:26.7|Trace|UpgradeMediaFileService|Upgrading existing movie file.
2024-06-05 21:06:26.8|Debug|MovieFileMovingService|Copying movie file: /data/The Name of the Movie (1967) [1080p]/The.Name.of.the.Movie.1967.1080p.BluRay.x264.YIFY.mp4 to //media/The Name of the Movie (1967)/The Name of the Movie (1967) Bluray-1080p.mp4
2024-06-05 21:06:26.8|Trace|ConfigService|Using default config value for 'usescriptimport' defaultValue:'False'
2024-06-05 21:06:26.8|Debug|DiskTransferService|Copy [/data/The Name of the Movie (1967) [1080p]/The.Name.of.the.Movie.1967.1080p.BluRay.x264.YIFY.mp4] > [/media/The Name of the Movie (1967))/The Name of the Movie (1967) Bluray-1080p.mp4]
2024-06-05 21:06:26.8|Debug|DiskTransferService|Rolling back file copy [/data/The Name of the Movie (1967) [1080p]/The.Name.of.the.Movie.1967.1080p.BluRay.x264.YIFY.mp4] to [/media/The Name of the Movie (1967))/The Name of the Movie (1967) Bluray-1080p.mp4].
2024-06-05 21:06:29.9|Warn|ImportApprovedMovie|Couldn't import movie /data/The Name of the Movie (1967) [1080p]/The.Name.of.the.Movie.1967.1080p.BluRay.x264.YIFY.mp4

[v5.6.0.8846] System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/The Name of the Movie (1967))/The Name of the Movie (1967) Bluray-1080p.mp4'.
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at NzbDrone.Mono.Disk.DiskProvider.TransferFilePatched(String source, String destination, Boolean overwrite, Boolean move) in ./Radarr.Mono/Disk/DiskProvider.cs:line 356
   at NzbDrone.Common.Disk.DiskProviderBase.CopyFile(String source, String destination, Boolean overwrite) in ./Radarr.Common/Disk/DiskProviderBase.cs:line 232
   at NzbDrone.Common.Disk.DiskTransferService.TryCopyFileVerified(String sourcePath, String targetPath, Int64 originalSize) in ./Radarr.Common/Disk/DiskTransferService.cs:line 487
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in ./Radarr.Common/Disk/DiskTransferService.cs:line 296
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode, LocalMovie localMovie) in ./Radarr.Core/MediaFiles/MovieFileMovingService.cs:line 155
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in ./Radarr.Core/MediaFiles/UpgradeMediaFileService.cs:line 41
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in ./Radarr.Core/MediaFiles/MovieImport/ImportApprovedMovie.cs:line 136

2024-06-05 21:06:29.9|Trace|TrackedDownloadAlreadyImported|Checking if all movies for 'The Name of the Movie (1967) [1080p]' have been imported
2024-06-05 21:06:29.9|Trace|TrackedDownloadAlreadyImported|No history for The Name of the Movie (1967) [1080p]
2024-06-05 21:06:29.9|Debug|CompletedDownloadService|Not all movies have been imported for The Name of the Movie (1967) [1080p]

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Screenshot the top portion of the movie details with the path

**Comment by GenerateUN** [comment]
No, correct path is /media/Backing Up Media Name (1996). (one parenthesis). Folder is created correctly. Trace only shows the second parenthesis on the quoted transfer line.

**Comment by GenerateUN** [comment]
I see that movies that were previously successfully transferred do not have the double leading slash in the movie details page, only the failing movies. Strange.  Thanks for looking into this and finding that. Any thoughts if this is my issue, docker compose issue from the maintainer or Radarr bug? Since no one else is reporting this, maybe it's on my end...

**Comment by GenerateUN** [comment]
I don't believe the double leading slash is configured. Looking through config settings it looks ok. Searching through the trace, 'media' is referenced as both single and double leading slashes. Here is a sequential example of both being listed (shown in **bold**):

2024-06-05 21:06:26.8|Debug|MovieFileMovingService|Copying movie file: /data/The Name of the Movie (1967) [1080p]/The.Name.of.the.Movie.1967.1080p.BluRay.x264.YIFY.mp4 to **//media/**The Name of the Movie (1967)/The Name of the Movie (1967) Bluray-1080p.mp4

2024-06-05 21:06:26.8|Trace|ConfigService|Using default config value for 'usescriptimport' defaultValue:'False'

2024-06-05 21:06:26.8|Debug|DiskTransferService|Copy [/data/The Name of the Movie (1967) [1080p]/The.Name.of.the.Movie.1967.1080p.BluRay.x264.YIFY.mp4] > [**/media**/The Name of the Movie (1967))/The Name of the Movie (1967) Bluray-1080p.mp4]

**Comment by GenerateUN** [comment]
Unalted trace logs:
2024-06-05 20:58:38.4|Debug|DiskScanService|Scanning '/data/What Dreams May Come (1998) [1080p]' for video files
2024-06-05 20:58:38.4|Trace|DiskScanService|3 files were found in /data/What Dreams May Come (1998) [1080p]
2024-06-05 20:58:38.4|Debug|DiskScanService|1 video files were found in /data/What Dreams May Come (1998) [1080p]
2024-06-05 20:58:38.5|Debug|ImportDecisionMaker|Analyzing 1/1 files.
2024-06-05 20:58:38.5|Debug|Parser|Parsing string 'What Dreams May Come (1998) [1080p]'
2024-06-05 20:58:38.5|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2024-06-05 20:58:38.5|Debug|Parser|Movie Parsed. What Dreams May Come - 1998 
2024-06-05 20:58:38.5|Debug|Parser|Release Group parsed: 1080p
2024-06-05 20:58:38.5|Debug|Parser|Languages parsed: Unknown
2024-06-05 20:58:38.6|Debug|QualityParser|Trying to parse quality for 'What Dreams May Come (1998) [1080p]'
2024-06-05 20:58:38.6|Debug|Parser|Quality parsed: HDTV-1080p v1
2024-06-05 20:58:38.6|Debug|Parser|Edition parsed: 
2024-06-05 20:58:38.6|Debug|VideoFileInfoReader|Getting media info from /data/What Dreams May Come (1998) [1080p]/What.Dreams.May.Come.1998.1080p.BluRay.x264.YIFY.mp4
2024-06-05 20:58:38.7|Debug|DetectSample|[/data/What Dreams May Come (1998) [1080p]/What.Dreams.May.Come.1998.1080p.BluRay.x264.YIFY.mp4] does not appear to be a sample. Runtime 01:53:43.8170000 seconds is more than minimum of 600 seconds
2024-06-05 20:58:38.7|Debug|Parser|Parsing string 'What.Dreams.May.Come.1998.1080p.BluRay.x264.YIFY.mp4'
2024-06-05 20:58:38.7|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2024-06-05 20:58:38.7|Debug|Parser|Movie Parsed. What Dreams May Come - 1998 
2024-06-05 20:58:38.7|Debug|Parser|Release Group parsed: YIFY
2024-06-05 20:58:38.7|Debug|Parser|Languages parsed: Unknown
2024-06-05 20:58:38.8|Debug|QualityParser|Trying to parse quality for 'What.Dreams.May.Come.1998.1080p.BluRay.x264.YIFY.mp4'
2024-06-05 20:58:38.8|Debug|Parser|Quality parsed: Bluray-1080p v1
2024-06-05 20:58:38.8|Debug|Parser|Edition parsed: 
2024-06-05 20:58:38.8|Debug|VideoFileInfoReader|Getting media info from /data/What Dreams May Come (1998) [1080p]/What.Dreams.May.Come.1998.1080p.BluRay.x264.YIFY.mp4
2024-06-05 20:58:38.9|Trace|AggregateLanguage|Considering Languages Unknown (Filename) from FileName
2024-06-05 20:58:38.9|Trace|AggregateLanguage|Considering Languages Unknown (Foldername) from FolderName
2024-06-05 20:58:38.9|Trace|AggregateLanguage|Considering Languages Unknown (DownloadClientItem) from DownloadClientItem
2024-06-05 20:58:38.9|Trace|AggregateLanguage|Considering Languages English (MediaInfo) from MediaInfo
2024-06-05 20:58:38.9|Debug|AggregateLanguage|Selected languages: English
2024-06-05 20:58:38.9|Trace|AggregateQuality|Considering Source BLURAY (Tag) Resolution 1080 (Tag) Revision v1 from FileName
2024-06-05 20:58:38.9|Trace|AggregateQuality|Considering Source TV (Fallback) Resolution 1080 (Tag) Revision v1 from FolderName
2024-06-05 20:58:38.9|Trace|AggregateQuality|Considering Source TV (Fallback) Resolution 1080 (Tag) Revision v1 from DownloadClientItem
2024-06-05 20:58:38.9|Trace|AugmentQualityFromMediaInfo|Resolution 1920x816 considered 1080p
2024-06-05 20:58:39.0|Trace|AggregateQuality|Considering Source UNKNOWN (Default) Resolution 1080 (MediaInfo) Revision  from MediaInfo
2024-06-05 20:58:39.0|Debug|QualityParser|Trying to parse quality for 'What Dreams May Come (1998) 1080p BRRip x264 -YTS'
2024-06-05 20:58:39.0|Trace|AggregateQuality|Considering Source BLURAY (Tag) Resolution 1080 (Tag) Revision v1 from ReleaseName
2024-06-05 20:58:39.0|Trace|AggregateQuality|Selected Source BLURAY (Tag) Resolution 1080 (MediaInfo) Revision v1
2024-06-05 20:58:39.0|Debug|AggregateQuality|Using quality: Bluray-1080p v1
2024-06-05 20:58:39.0|Debug|AlreadyImportedSpecification|Skipping already imported check for movie without file
2024-06-05 20:58:39.0|Trace|ConfigService|Using default config value for 'skipfreespacecheckwhenimporting' defaultValue:'False'
2024-06-05 20:58:39.1|Trace|ConfigService|Using default config value for 'minimumfreespacewhenimporting' defaultValue:'100'
2024-06-05 20:58:39.1|Debug|VideoFileInfoReader|Getting media info from /data/What Dreams May Come (1998) [1080p]/What.Dreams.May.Come.1998.1080p.BluRay.x264.YIFY.mp4
2024-06-05 20:58:39.1|Debug|DetectSample|[/data/What Dreams May Come (1998) [1080p]/What.Dreams.May.Come.1998.1080p.BluRay.x264.YIFY.mp4] does not appear to be a sample. Runtime 01:53:43.8170000 seconds is more than minimum of 600 seconds
2024-06-05 20:58:39.1|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
2024-06-05 20:58:39.1|Trace|ConfigService|Using default config value for 'downloadpropersandrepacks' defaultValue:'PreferAndUpgrade'
2024-06-05 20:58:39.1|Debug|ImportDecisionMaker|File accepted
2024-06-05 20:58:39.2|Debug|ImportApprovedMovie|Decisions: 1
2024-06-05 20:58:39.2|Trace|UpgradeMediaFileService|Upgrading existing movie file.
2024-06-05 20:58:39.2|Debug|MovieFileMovingService|Copying movie file: /data/What Dreams May Come (1998) [1080p]/What.Dreams.May.Come.1998.1080p.BluRay.x264.YIFY.mp4 to //media/What Dreams May Come (1998)/What Dreams May Come (1998) Bluray-1080p.mp4
2024-06-05 20:58:39.2|Trace|ConfigService|Using default config value for 'usescriptimport' defaultValue:'False'
2024-06-05 20:58:39.2|Debug|DiskTransferService|Copy [/data/What Dreams May Come (1998) [1080p]/What.Dreams.May.Come.1998.1080p.BluRay.x264.YIFY.mp4] > [/media/What Dreams May Come (1998))/What Dreams May Come (1998) Bluray-1080p.mp4]
2024-06-05 20:58:39.2|Debug|DiskTransferService|Rolling back file copy [/data/What Dreams May Come (1998) [1080p]/What.Dreams.May.Come.1998.1080p.BluRay.x264.YIFY.mp4] to [/media/What Dreams May Come (1998))/What Dreams May Come (1998) Bluray-1080p.mp4].
2024-06-05 20:58:42.3|Warn|ImportApprovedMovie|Couldn't import movie /data/What Dreams May Come (1998) [1080p]/What.Dreams.May.Come.1998.1080p.BluRay.x264.YIFY.mp4

[v5.6.0.8846] System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/What Dreams May Come (1998))/What Dreams May Come (1998) Bluray-1080p.mp4'.
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at NzbDrone.Mono.Disk.DiskProvider.TransferFilePatched(String source, String destination, Boolean overwrite, Boolean move) in ./Radarr.Mono/Disk/DiskProvider.cs:line 356
   at NzbDrone.Common.Disk.DiskProviderBase.CopyFile(String source, String destination, Boolean overwrite) in ./Radarr.Common/Disk/DiskProviderBase.cs:line 232
   at NzbDrone.Common.Disk.DiskTransferService.TryCopyFileVerified(String sourcePath, String targetPath, Int64 originalSize) in ./Radarr.Common/Disk/DiskTransferService.cs:line 487
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in ./Radarr.Common/Disk/DiskTransferService.cs:line 296
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode, LocalMovie localMovie) in ./Radarr.Core/MediaFiles/MovieFileMovingService.cs:line 155
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in ./Radarr.Core/MediaFiles/UpgradeMediaFileService.cs:line 41
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in ./Radarr.Core/MediaFiles/MovieImport/ImportApprovedMovie.cs:line 136


2024-06-05 20:58:42.3|Trace|TrackedDownloadAlreadyImported|Checking if all movies for 'What Dreams May Come (1998) [1080p]' have been imported
2024-06-05 20:58:42.3|Trace|TrackedDownloadAlreadyImported|Last event for movie: [What Dreams May Come (1998)][tt0120889, 12159] is: Grabbed
2024-06-05 20:58:42.3|Trace|TrackedDownloadAlreadyImported|All movies for 'What Dreams May Come (1998) [1080p]' have been imported: False
2024-06-05 20:58:42.3|Debug|CompletedDownloadService|Not all movies have been imported for What Dreams May Come (1998) [1080p]

**Comment by GenerateUN** [comment]
When you asked for the media management settings I could see that media was configured with double slash. I removed and re-added it and it is now single. I am assuming that is the issue, and of course, user error. I assume it will now run correctly but watching it to see.

**Comment by GenerateUN** [comment]
Thanks for your help. I hope I didn't burn to much of your time.
