### ISSUE TITLE
Adding movies from Discover + using a CustomScript notification throws ArgumentNullException in Datastore.WhereBuilderSqlite => some TagRepository.GetTags codepaths pass a null tagIds set

### ISSUE THREAD

**Issue by tsuereth** [Radarr/Radarr#10067]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When a movie is added from Radarr's Discover view, a Custom Script notification with the "On Movie Added" trigger will fail to notify, and log an exception like the following:

```
2024-06-07 05:00:43.4|Warn|NotificationService|Unable to send OnMovieAdded notification to: NameOfMyCustomScript

[v5.6.0.8846] System.ArgumentNullException: Value cannot be null. (Parameter 'values')
   at System.String.JoinCore[T](ReadOnlySpan`1 separator, IEnumerable`1 values)
   at NzbDrone.Core.Datastore.WhereBuilderSqlite.ParseEnumerableContains(MethodCallExpression body) in ./Radarr.Core/Datastore/WhereBuilderSqlite.cs:line 303
   at NzbDrone.Core.Datastore.WhereBuilderSqlite.VisitMethodCall(MethodCallExpression expression) in ./Radarr.Core/Datastore/WhereBuilderSqlite.cs:line 80
   at NzbDrone.Core.Datastore.ExpressionVisitor.Visit(Expression expression) in ./Radarr.Core/Datastore/ExpressionVisitor.cs:line 76
   at NzbDrone.Core.Datastore.ExpressionVisitor.VisitLamda(LambdaExpression lambdaExpression) in ./Radarr.Core/Datastore/ExpressionVisitor.cs:line 140
   at NzbDrone.Core.Datastore.ExpressionVisitor.Visit(Expression expression) in ./Radarr.Core/Datastore/ExpressionVisitor.cs:line 76
   at NzbDrone.Core.Datastore.SqlBuilderExtensions.Where[TModel](SqlBuilder builder, Expression`1 filter) in ./Radarr.Core/Datastore/Extensions/BuilderExtensions.cs:line 47
   at NzbDrone.Core.Datastore.BasicRepository`1.Query(Expression`1 where) in ./Radarr.Core/Datastore/BasicRepository.cs:line 74
   at NzbDrone.Core.Tags.TagRepository.GetTags(HashSet`1 tagIds) in ./Radarr.Core/Tags/TagRepository.cs:line 42
   at NzbDrone.Core.Notifications.CustomScript.CustomScript.GetTagLabels(Movie movie) in ./Radarr.Core/Notifications/CustomScript/CustomScript.cs:line 391
   at NzbDrone.Core.Notifications.CustomScript.CustomScript.OnMovieAdded(Movie movie) in ./Radarr.Core/Notifications/CustomScript/CustomScript.cs:line 194
   at NzbDrone.Core.Notifications.NotificationService.Handle(MoviesImportedEvent message) in ./Radarr.Core/Notifications/NotificationService.cs:line 200
```

The content of the custom script is irrelevant; this occurs before the script is invoked.

But this exception does not occur when adding movies through the Add New view (here, the Custom Script notification proceeds as expected).

Debugging Radarr highlights the difference between these "OnMovieAdded" paths in `NzbDrone.Core.Tags.TagRepository.GetTags()`:
* When adding through the Add New view, the movie's set of Tags is an empty HashSet (zero items).
* However, adding through the Discover view, the movie's set of Tags is `null`.

Inspecting the web requests which feed into these code paths does indeed show, that while Add New sends a payload describing a Movie which includes `"tags":[]`, Discover sends a payload describing a list of Movies which do not include a "tags" key.

... but since I don't know what other add/import web requests may exhibit this same behavior, i.e. maybe the "tags" key is also missing elsewhere, it seems more poignant to call the `TagRepostitory.GetTags()` misbehavior with `null` sets the real root-cause.

### Expected Behavior

Radarr should be able to invoke the Custom Script notification equally well however "OnMovieAdded" might occur.

### Steps To Reproduce

1. Assumes a functional Radarr instance (when building and running from source, at least one Root Folder must be added).
2. From Settings -> Connect, create a new Custom Script connection...
3. Enable at least the On Movie Added notification trigger...
4. And select any "valid for your OS" Path for the script.  (This could even be a zero-byte file ending with ".sh" or ".ps1" depending on the host OS.)
5. Navigate to the Movies -> Discover page, select any movie, and click Add Movies.
6. The exception will not be displayed to you directly, but will appear in System -> Log Files -> the current log.

### Environment

```markdown
- OS: multiple (tested Docker, Windows)
- Radarr: tested 5.6.0.8846 + `develop` branch
- Docker Install: both/either
- Using Reverse Proxy: No
- Browser: unrelated (but, Chrome)
- Database: unrelated (but, built-in)
```

### What branch are you running?

Develop

### Trace Logs? **Not Optional**

```
2024-06-08 14:02:30.5|Trace|Http|Req: 150 [POST] /api/v3/importlist/movie (from ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36)
2024-06-08 14:02:30.5|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-06-08 14:02:30.6|Info|AddMovieService|Adding Movie [Batman (1966)][tt0060153, 2661] Path: []
2024-06-08 14:02:30.6|Trace|HttpClient|Req: [GET] https://api.radarr.video/v1/movie/2661
2024-06-08 14:02:30.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-06-08 14:02:30.6|Trace|HttpClient|Res: HTTP/2.0 [GET] https://api.radarr.video/v1/movie/2661: 200.OK (36629 bytes) (34 ms)
2024-06-08 14:02:30.6|Trace|ConfigService|Using default config value for 'certificationcountry' defaultValue:'US'
2024-06-08 14:02:30.6|Trace|ConfigService|Using default config value for 'recyclebin' defaultValue:''
2024-06-08 14:02:30.6|Debug|MovieMetadataRepository|0 movie metadata up to date; Updating 0, Adding 1 movie metadata entries.
2024-06-08 14:02:30.6|Trace|EventAggregator|Publishing MoviesImportedEvent
2024-06-08 14:02:30.6|Trace|EventAggregator|MoviesImportedEvent -> NotificationService
2024-06-08 14:02:30.6|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2024-06-08 14:02:30.6|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2024-06-08 14:02:30.6|Debug|NotificationService|No tags set for this notification.
2024-06-08 14:02:30.6|Trace|ConfigService|Using default config value for 'applicationurl' defaultValue:''
2024-06-08 14:02:30.7|Trace|EventAggregator|Publishing ProviderStatusChangedEvent<INotification>
2024-06-08 14:02:30.7|Warn|NotificationService|Unable to send OnMovieAdded notification to: Custom Script

[v10.0.0.25253] System.ArgumentNullException: Value cannot be null. (Parameter 'values')
   at System.String.JoinCore[T](ReadOnlySpan`1 separator, IEnumerable`1 values)
   at System.String.Join[T](String separator, IEnumerable`1 values)
   at NzbDrone.Core.Datastore.WhereBuilderSqlite.ParseEnumerableContains(MethodCallExpression body) in ./Radarr.Core/Datastore/WhereBuilderSqlite.cs:line 321
   at NzbDrone.Core.Datastore.WhereBuilderSqlite.ParseContainsExpression(MethodCallExpression expression) in ./Radarr.Core/Datastore/WhereBuilderSqlite.cs:line 282
   at NzbDrone.Core.Datastore.WhereBuilderSqlite.VisitMethodCall(MethodCallExpression expression) in ./Radarr.Core/Datastore/WhereBuilderSqlite.cs:line 67
   at NzbDrone.Core.Datastore.ExpressionVisitor.Visit(Expression expression) in ./Radarr.Core/Datastore/ExpressionVisitor.cs:line 67
   at NzbDrone.Core.Datastore.ExpressionVisitor.VisitLamda(LambdaExpression lambdaExpression) in ./Radarr.Core/Datastore/ExpressionVisitor.cs:line 139
   at NzbDrone.Core.Datastore.ExpressionVisitor.Visit(Expression expression) in ./Radarr.Core/Datastore/ExpressionVisitor.cs:line 30
   at NzbDrone.Core.Datastore.WhereBuilderSqlite..ctor(Expression filter, Boolean requireConcreteValue, Int32 seq) in ./Radarr.Core/Datastore/WhereBuilderSqlite.cs:line 32
   at NzbDrone.Core.Datastore.SqlBuilderExtensions.GetWhereBuilder(DatabaseType databaseType, Expression filter, Boolean requireConcrete, Int32 seq) in ./Radarr.Core/Datastore/Extensions/BuilderExtensions.cs:line 149
   at NzbDrone.Core.Datastore.SqlBuilderExtensions.Where[TModel](SqlBuilder builder, Expression`1 filter) in ./Radarr.Core/Datastore/Extensions/BuilderExtensions.cs:line 45
   at NzbDrone.Core.Datastore.BasicRepository`1.Query(Expression`1 where) in ./Radarr.Core/Datastore/BasicRepository.cs:line 74
   at NzbDrone.Core.Tags.TagRepository.GetTags(HashSet`1 tagIds) in ./Radarr.Core/Tags/TagRepository.cs:line 47
   at NzbDrone.Core.Notifications.CustomScript.CustomScript.GetTagLabels(Movie movie) in ./Radarr.Core/Notifications/CustomScript/CustomScript.cs:line 391
   at NzbDrone.Core.Notifications.CustomScript.CustomScript.OnMovieAdded(Movie movie) in ./Radarr.Core/Notifications/CustomScript/CustomScript.cs:line 194
   at NzbDrone.Core.Notifications.NotificationService.Handle(MoviesImportedEvent message) in ./Radarr.Core/Notifications/NotificationService.cs:line 200


2024-06-08 14:02:30.8|Trace|EventAggregator|MoviesImportedEvent <- NotificationService
2024-06-08 14:02:30.8|Trace|EventAggregator|MoviesImportedEvent -> MovieAddedHandler
2024-06-08 14:02:30.8|Trace|CommandQueueManager|Publishing 1 commands
2024-06-08 14:02:30.8|Trace|EventAggregator|MoviesImportedEvent <- MovieAddedHandler
2024-06-08 14:02:30.8|Trace|CommandExecutor|RefreshMovieCommand -> RefreshMovieService

... (following logs appear normal)
```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
A proper bug report brings a tear to one's eye - let alone the additional RCAing and debugging :)

**Comment by tsuereth** [comment]
Proposed fix in #10068 

Ran this locally, and confirmed following the issue's repro steps, the logged exception no longer occurs. 😎

**Comment by tsuereth** [comment]
Alternative proposed fix in #10069 

Also confirmed locally that this - independent of the TagRepository patch - addresses the original exception.  Either change, or even both, will work.

(For my own education, I'm curious if there's a preference against modifying the `NzbDrone.Core` code, or against a wider-reaching change, or ... `¯\_(ツ)_/¯`)
