### ISSUE TITLE
Movie import fails if download dir contains a single unreadable dir

### ISSUE THREAD

**Issue by beirut-boop** [Radarr/Radarr#10085]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Downloaded movies are no longer automatically or manually imported if the download directory also contains an unreadable directory.

There is no error message logged, but if you do a manual import, you will see the message (for example): `Access to the path '/downloads/Blender' is denied.`. Once you add permissions or remove the dir, movies will get imported again.

### Expected Behavior

Not being able to read a single directory should not stop the process from traversing the other directories.

- `/downloads/Blender` `700` Not readable, import failed
- `/downloads/Movie1` `775` Never parsed
- `/downloads/Movie2` `775` Never parsed

### Steps To Reproduce

1. Create an unreadable directory (change permissions) in your download dir.
2. Possibly rename it so it sorts before the movie containing dir
3. Do manual import or new download with automatic import

### Environment

```markdown
- OS: Ubuntu 22.04
- Radarr: 5.6.0.8846
- Docker Install: Yes
- Using Reverse Proxy: Yes 
- Database: Sqlite 3.45.3
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

```
2024-06-14 02:22:29.0|Trace|CommandExecutor|ImportListSyncCommand <- ImportListSyncService [00:00:00.0080173]
(...)
2024-06-14 02:22:34.4|Debug|DiskScanService|Scanning '/downloads/' for video files
2024-06-14 02:22:34.4|Debug|Parser|Parsing string 'Movie 1'
2024-06-14 02:22:34.4|Debug|Parser|Movie Parsed. Movie 1
2024-06-14 02:22:34.4|Debug|Parser|Release Group parsed: 
2024-06-14 02:22:34.4|Debug|Parser|Languages parsed: Unknown
2024-06-14 02:22:34.5|Debug|Parser|Quality parsed: Unknown v1
2024-06-14 02:22:34.5|Debug|Parser|Edition parsed: 
2024-06-14 02:22:34.6|Debug|AlreadyImportedSpecification|No download client information is available, skipping
2024-06-14 02:22:34.6|Debug|DiskScanService|0 video files were found in /downloads/Robert P. Murphy - Contra Krugman
2024-06-14 02:22:34.6|Debug|Parser|Parsing string 'Blender'
2024-06-14 02:22:34.6|Debug|Parser|Unable to parse Blender
2024-06-14 02:22:34.6|Debug|DiskScanService|Scanning '/downloads/Blender' for video files
2024-06-14 02:22:34.6|Trace|DiskScanService|0 files were found in /downloads/Blender
2024-06-14 02:22:34.6|Debug|DiskScanService|0 video files were found in /downloads/Blender
2024-06-14 02:22:34.6|Trace|RadarrErrorPipeline|Handling Exception
2024-06-14 02:22:34.6|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/manualimport

[v5.6.0.8846] System.UnauthorizedAccessException: Access to the path '/downloads/Blender' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at NzbDrone.Core.MediaFiles.MovieImport.Manual.ManualImportService.ProcessFolder(String rootFolder, String baseFolder, String downloadId, Nullable`1 movieId, Boolean filterExistingFiles) in ./Radarr.Core/MediaFiles/MovieImport/Manual/ManualImportService.cs:line 195
   at NzbDrone.Core.MediaFiles.MovieImport.Manual.ManualImportService.<>c__DisplayClass15_0.<ProcessFolder>b__2(String subfolder) in ./Radarr.Core/MediaFiles/MovieImport/Manual/ManualImportService.cs:line 186
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at NzbDrone.Core.MediaFiles.MovieImport.Manual.ManualImportService.ProcessFolder(String rootFolder, String baseFolder, String downloadId, Nullable`1 movieId, Boolean filterExistingFiles) in ./Radarr.Core/MediaFiles/MovieImport/Manual/ManualImportService.cs:line 195
   at NzbDrone.Core.MediaFiles.MovieImport.Manual.ManualImportService.GetMediaFiles(String path, String downloadId, Nullable`1 movieId, Boolean filterExistingFiles) in ./Radarr.Core/MediaFiles/MovieImport/Manual/ManualImportService.cs:line 97
   at lambda_method809(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2024-06-14 02:22:34.6|Trace|Http|Res: 2114 [GET] /api/v3/manualimport?folder=%2Fdownloads%2F&filterExistingFiles=false: 500.InternalServerError (3776 ms)
2024-06-14 02:22:34.6|Debug|Api|[GET] /api/v3/manualimport?folder=%2Fdownloads%2F&filterExistingFiles=false: 500.InternalServerError (3776 ms)
```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by beirut-boop** [comment]
Actually, this appears to be a bug. I will be downgrading Radarr to work around the bug. I don't need support with that.

**Comment by beirut-boop** [comment]
> What's the latest version that works for you?

Since I removed the (manually downloaded) Blender directory that had no _read_ permission for the Radarr user from the downloads directory, everything works as expected again. So I'll just use a different directory for manual downloads that end up having different permissions, then I don't have to downgrade. You can see in the trace log it would throw an exception when indexing the download directory to import movies, and just stops the entire thing rather than silently ignoring the unreadable directory and continuing the import process.

This started happening a few months ago, but to be honest, I don't know if it started because of an automated Radarr update, or because I manually downloaded Blender. I don't know which happened first, but I think it is a regression because I downloaded Blender probably a year ago.

Knowing this, my issue is solved with this workaround but I think it's a matter of time before someone else has the same problem. Just do the steps to recreate, and I bet you'll agree it's a bug.

**Comment by beirut-boop** [comment]
Thanks for this. :pray: I think this fixes the problem. I will test.

> the stacktrace you provided doesn't make any sense to me regarding the source of the issue. Radarr already has the `IgnoreInaccessible` flag when listing files.

FWIW, unreadable files are fine. The problem was with unreadable directories. It triggered a full stop.
