### ISSUE TITLE
IMDB List import NotFound

### ISSUE THREAD

**Issue by bonswouar** [Radarr/Radarr#10121]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When trying to add an IMDB List (ie [ls540367013](https://www.imdb.com/list/ls540367013/), but I tested a couple more with same result) I get:
> Unable to connect to import list: Radarr API call resulted in an unexpected StatusCode [NotFound]. Check the log surrounding this error for details.

### Expected Behavior

List is valid and should be imported

### Steps To Reproduce

1. Settings > Import List > + > Other List > IMDB Lists
2. Fill the required field, with for example `ls540367013` in List/User ID
3. Click Test or Save

### Environment

```markdown
- OS: Debian 12
- Radarr: 5.7.0.8882
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Database: Sqlite 3.45.3
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

radarr  | [Warn] IMDbListImport: Unable to connect to list
radarr  |
radarr  | [v5.7.0.8882] NzbDrone.Core.ImportLists.Exceptions.ImportListException: Radarr API call resulted in an unexpected StatusCode [NotFound]
radarr  |    at NzbDrone.Core.ImportLists.RadarrList2.RadarrList2Parser.PreProcess(ImportListResponse listResponse) in ./Radarr.Core/ImportLists/RadarrList2/RadarrList2Parser.cs:line 39
radarr  |    at NzbDrone.Core.ImportLists.RadarrList2.IMDbList.IMDbListParser.ParseResponse(ImportListResponse importListResponse) in ./Radarr.Core/ImportLists/RadarrList2/IMDb/IMDbListParser.cs:line 26
radarr  |    at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchPage(ImportListRequest request, IParseImportListResponse parser) in ./Radarr.Core/ImportLists/HttpImportListBase.cs:line 185
radarr  |    at NzbDrone.Core.ImportLists.HttpImportListBase`1.TestConnection() in ./Radarr.Core/ImportLists/HttpImportListBase.cs:line 213
radarr  |
radarr  |
radarr  | [Warn] RadarrErrorPipeline: Invalid request Validation failed:
radarr  |  -- : Unable to connect to import list: Radarr API call resulted in an unexpected StatusCode [NotFound]. Check the log surrounding this error for details.

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by iamse7en** [comment]
Also having this issue, thanks for looking into it!

**Comment by Sokpan** [comment]
Same issue here.  Glad someone is looking into it.
If you need more logs, let me know.

**Comment by bokkoman** [comment]
Switch to ur##### to get it to work again.

**Comment by jleonard711** [comment]
> Switch to ur##### to get it to work again.

What do you mean by "switch to ur######" - that would be a used ID number, not a list number. Wouldn't putting the user ID of the list owner import ALL lists from that user?

**Comment by bokkoman** [comment]
> > Switch to ur##### to get it to work again.
> 
> What do you mean by "switch to ur######" - that would be a user ID number, not a list number. Wouldn't putting the user ID of the list owner import ALL lists from that user?

I don't know, i only have 1 list XD

**Comment by Sokpan** [comment]
> Switch to ur##### to get it to work again.

It is a workaround but have multiple lists so won't work with just User ID.

**Comment by pepeilegal** [comment]
> > Switch to ur##### to get it to work again.
> 
> It is a workaround but have multiple lists so won't work with just User ID.

If you need to import only one list, you can create a new user and add one public list of your user to a watch list of new user. After, you can import a list of new user on radarr.

**Comment by jleonard711** [comment]
> > > Switch to ur##### to get it to work again.
> > 
> > 
> > What do you mean by "switch to ur######" - that would be a user ID number, not a list number. Wouldn't putting the user ID of the list owner import ALL lists from that user?
> 
> I don't know, i only have 1 list XD

Why I try a user ID (ur######) I get the same error as when I try a list ID

**Comment by PiefkePaul** [comment]
On my new Radarr instance I build yesterday using "ur111684XXX" is giving me this Error:
"No results were returned from your import list, please check your settings and the log for details."

using "ls541313XXX" is giving me also:
"Unable to connect to import list: Radarr API call resulted in an unexpected StatusCode [NotFound]. Check the log surrounding this error for details."

On an older Radarr instance (from about 2 weeks ago) with the same List in it its working...

**Comment by PiefkePaul** [comment]
> @PiefkePaul if you use the real list id in `https://www.imdb.com/list/ls541313XXX/export`, it works for you?

nope, brings me to 404 Error page

https://www.imdb.com/exports/?ref_=lsedt

Maybe imdm is changing some things in the background?

**Comment by jimmyre420** [comment]
I have the same issue; my https://www.imdb.com/list/**ls05601XXXX**/export URL is returning a 404:

![image](https://github.com/Radarr/Radarr/assets/143096392/3bf1dc05-b7d3-4957-a8d3-c49ff092fd39)

As I am using my IMDb account's **Watchlist only** (not a custom list), I have gone to "My Watchlist" in IMDb, grabbed the URL which has my User ID in it, https://www.imdb.com/user/**ur4522XXXXX**/watchlist/, yields **ur4522XXXXX**.
I have edited my IMDb Watchlist in Radarr to have my User ID as per below:

![image](https://github.com/Radarr/Radarr/assets/143096392/8e8a30bb-8e38-4acf-bb34-98857f97bb99)

This workaround will only work for your IMDb account's "My Watchlist" list and it will only work in Radarr; Sonarr does not support User ID lists unfortunately.

**Comment by JEDIIy2k** [comment]
The urXXX work around wasn't working for me either, but I didn't have a watchlist. After adding the last two weeks of movies to it and making it public, it still doesn't work.
```2024-07-06 08:15:11.3|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-07-06 08:15:11.3|Debug|IMDbListImport|Downloading List https://api.radarr.video/v1/list/imdb/ur17617XXXX
2024-07-06 08:15:11.3|Trace|HttpClient|Req: [GET] https://api.radarr.video/v1/list/imdb/ur17617XXXX
2024-07-06 08:15:11.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-07-06 08:15:11.4|Trace|HttpClient|Res: HTTP/2.0 [GET] https://api.radarr.video/v1/list/imdb/ur17617XXXX: 404.NotFound (0 bytes) (137 ms)
2024-07-06 08:15:11.4|Warn|IMDbListImport|Unable to connect to list
```

**Comment by Sokpan** [comment]
Seems they change their Export feature, user has to be online on his account to export from lists.  Might also changed for Watchlist.
Sonarr having same issue, they are waiting to see if IMDb changes it back to allow export without having to do it manually from your account, else we might have to find alternate solution.

**Comment by petefinch** [comment]
I would like to add I'm also experiencing this issue.
not sure what I can do to assist the devs but I get the same error as OP

2024-07-08 09:59:22.8|Warn|RadarrErrorPipeline|Invalid request Validation failed:
-- : Unable to connect to import list: Radarr API call resulted in an unexpected StatusCode [NotFound]. Check the log surrounding this error for details.
2024-07-08 09:59:29.7|Warn|IMDbListImport|Unable to connect to list

If you need logs or another beta tester, let me know
cheers for your efforts :)
Pete

**Comment by kosymodo** [comment]
Mine is also not working, whether I use ls56677xxxx or ur2810xxxx in the **List/User ID** field

**Comment by bokkoman** [comment]
My ur#### works. It tests successfully and i don't get errors on import. 
I double checked if my watchlist is public, and it is. 
Wonder why it fails for others.

**Comment by DaveAlton** [comment]
Mine too. No issues if I use the "ur" list. Public here too.

**Comment by bokkoman** [comment]
Maybe it depends on your age on IMDb? I'm a member since 2011.

**Comment by DaveAlton** [comment]
Could be? I'm 2007, but that seems like a strange API condition.

**Comment by richardbulman** [comment]
One strange thing I found:
- Removed custom watchlist and made my default (ur) watchlist public -> Changed the connection to the ur ## and still failed
- 24 hours later recreated the connection entirely -> Worked (can't remember if I retested the old)
I can't recreate now, so could either have been the removal of the custom watchlist and / or the public setting lagging in updating in the background with IMDB - Or could have been the fact I re-created the connection.

**Comment by petefinch** [comment]
> One strange thing I found:
> 
> * Removed custom watchlist and made my default (ur) watchlist public -> Changed the connection to the ur ## and still failed
> * 24 hours later recreated the connection entirely -> Worked (can't remember if I retested the old)
>   I can't recreate now, so could either have been the removal of the custom watchlist and / or the public setting lagging in updating in the background with IMDB - Or could have been the fact I re-created the connection.

Crazy! I did what you said and now the ur# works but the ls# does not. 
connects and started searching for stuff.
I'll monitor it and post back here if it fails again

**Comment by jby** [comment]
@mynameisbogdan - it would seem that the current download link from the export page is something like:
https://userdataexport-dataexportsbucket-prod.s3.amazonaws.com/LIST/ac1afd53-216a-45b6-a059-0174d1d0a352.csv
With a security token appended.
That is, if you go to manually export your list...

**Comment by jimmyre420** [comment]
FWIW: if you have a lifetime Plex Pass subscription, which you damn well
should have, because *Plex is pretty much free, support** the devs (!)*,
you can replace your IMDb list in *Sonarr and Radarr* with your Plex RSS
Watchlist.

I did this and it immediately solved the issue. These RSS watchlists will
continue to "just work" as they're a Plex Pass feature and the only thing
you need to do differently is add movies/TV shows to your Plex Watchlist
instead of IMDb Watchlist.

I don't see IMDb "fixing" this issue anytime soon to be honest; they
probably caught on that a metric shitload of users are scraping their IMDb
watchlists from Sonarr & Radarr, generating heaps of traffic that IMDb has
to pay for.

To fix IMDb 'Import Lists' in Radarr, the devs would have to implement
usage of *User Lists (URxxxxxxx)* instead of *Lists (LSxxxxxxxx)*, just
like they have done in Sonarr, so you can scrape your IMDb main account's
Watchlist (and that's it, not a custom list).

Another added benefit of Plex Pass: add your friends as "Friends" on the
Plex platform, that way you'll be able to pull "Your Friends' Watchlist"
and yours, see screenshot:

[image: image.png]

**Comment by jimmyre420** [comment]
![image](https://github.com/user-attachments/assets/1d89367a-fe54-4669-adc2-c503ee2ed13c)

**Comment by jimmyre420** [comment]
> Another added benefit of Plex Pass: add your friends as "Friends" on the Plex platform, that way you'll be able to pull "Your Friends' Watchlist" and yours, see screenshot: ![image](https://github.com/user-attachments/assets/aefc1e41-2a12-44f8-b02f-ed083cf34298)

![image](https://github.com/user-attachments/assets/9602e2cc-b3ce-4ff7-bf3d-f4f32c11fd88)

**Comment by Sokpan** [comment]
I agree, Plex Watchlist, and other list sources for Radarr, are a great solution and alternate options, however for me IMDb provide more with ability to have multiple lists.  I could have a list for 4K content, a list for B movies, a list of immediate wants vs will grab later, and I could control the quality or when I wanted Radarr to grab each.

However, since I don't expect IMDb to enable this feature again, to avoid traffic on their servers, definately will need to find another way for lists.

For now Plex Watchlist is an option, till I find alternate multi list option.

**Comment by ollie2a** [comment]
Same I use TMDB now ... there seems to be 2 workarounds available to implement the IMDB list scraping described here (obviously a lot of projects were impacted by this change) ; unfortunately the IMDB API does not seem to provide this feature. 

These workarounds have limitations though. 
1) scrape the html and retrieve the embedded json, limited to 100 entries
2) use selenium or similar to retrieve and scrape the data from the list

source: https://www.reddit.com/r/imdb/comments/1dqi940/bulk_downloading_lists_via_the_export_endpoint_no/

**Comment by dkrahmer** [comment]
I encountered the IMDB list imports issue today and created a fix for it. With my fix, each list is limited to the last 100 movies added. The limit exists because the data is extracted from JSON content embedded in the list HTML page - that is all the data that is provided without making follow-up requests. It is likely possible to get the full list but would require more work and reverse engineering IMDB's GraphQL API. The 100 limit is sufficient for my current needs for now.

Anyone interested in the fix can find it here: https://github.com/dkrahmer/Radarr/tree/DK_FixImdbListImport
Commit: https://github.com/dkrahmer/Radarr/commit/0d89061b4cda49525dbf48d98da9f8cbc71fce1a

Does this fix adhere to IMDB's TOS? Meh, I don't know and don't care. Considering what Radarr is used for, I am surprised anyone cares about violating TOS at all.

**Comment by ZackEndboss** [comment]
Is it a Fix? No one reply
@dkrahmer maybe Merge-Request?

**Comment by MaddionMax** [comment]
> I encountered the IMDB list imports issue today and created a fix for it. With my fix, each list is limited to the last 100 movies added. The limit exists because the data is extracted from JSON content embedded in the list HTML page - that is all the data that is provided without making follow-up requests. It is likely possible to get the full list but would require more work and reverse engineering IMDB's GraphQL API. The 100 limit is sufficient for my needs for now.
> 
> Anyone interested in the fix can find it here: https://github.com/dkrahmer/Radarr/tree/DK_FixImdbListImport Commit: [dkrahmer@0d89061](https://github.com/dkrahmer/Radarr/commit/0d89061b4cda49525dbf48d98da9f8cbc71fce1a)
> 
> Does this fix adhere to IMDB's TOS? Meh, I don't know and don't care. Considering what Radarr is used for, I am surprised anyone cares about violating TOS at all.

How can I use this fix? Can you please explain?

**Comment by bakerboy448** [comment]
Please do not discuss IMDb TOS violating fixes on this github issue.
Support for third party forks is not provided by Radarr
Radarr's Github is not for any support
