### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: The given key '4' was not present in the dictionary

### ISSUE THREAD

**Issue by ishioni** [Radarr/Radarr#10143]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Prowlarr does not start with a concise "Failed to load Radarr"

### Expected Behavior

Should work

### Environment

```markdown
- OS: Talos v1.7.5
- Radarr: 5.7.0.8882
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: ALL
- Database: Postgres 16.3
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

```
[Info] Bootstrap: Starting Radarr - /app/bin/Radarr - Version 5.7.0.8882 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] MigrationController: *** Migrating Database=radarr_main;Host=postgres-rw.database.svc.cluster.local;Username=radarr;Password=a2Y3XvrXLZiiKWBiQr*w;Port=5432;Enlist=False *** 
[Info] FluentMigrator.Runner.MigrationRunner: DatabaseEngineVersionCheck migrating 
[Info] FluentMigrator.Runner.MigrationRunner: PerformDBOperation  
[Info] FluentMigrator.Runner.Processors.Postgres.PostgresProcessor: Performing DB Operation 
[Info] DatabaseEngineVersionCheck: Postgres 16.3  
[Info] FluentMigrator.Runner.MigrationRunner: => 0.2721705s 
[Info] FluentMigrator.Runner.MigrationRunner: DatabaseEngineVersionCheck migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.2740736s 
[Info] Microsoft.Hosting.Lifetime: Now listening on: http://[::]:80 
[Info] CommandExecutor: Starting 2 threads for tasks. 
[Info] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down. 
[Info] Microsoft.Hosting.Lifetime: Hosting environment: Production 
[Info] Microsoft.Hosting.Lifetime: Content root path: /config 
[Info] ManagedHttpDispatcher: IPv4 is available: True, IPv6 will be disabled 
[Error] TaskExtensions: Task Error 

[v5.7.0.8882] System.Collections.Generic.KeyNotFoundException: The given key '4' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NzbDrone.Core.Movies.MovieRepository.<>c__DisplayClass7_0.<All>b__6(Movie movie, MovieFile file, MovieMetadata metadata) in ./Radarr.Core/Movies/MovieRepository.cs:line 117
   at NzbDrone.Core.Datastore.SqlMapperExtensions.<>c__DisplayClass2_0`4.<Query>g__MapWithLazy|0(TFirst first, TSecond second, TThird third) in ./Radarr.Core/Datastore/Extensions/SqlMapperExtensions.cs:line 67
   at Dapper.SqlMapper.<>c__DisplayClass167_0`8.<GenerateMapper>b__1(DbDataReader r) in /_/Dapper/SqlMapper.cs:line 1657
   at Dapper.SqlMapper.MultiMapImpl[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn, DbDataReader reader, Identity identity, Boolean finalize)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1558
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.MultiMap[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, String sql, Delegate map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1518
   at Dapper.SqlMapper.Query[TFirst,TSecond,TThird,TReturn](IDbConnection cnn, String sql, Func`4 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1394
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[TFirst,TSecond,TThird,TReturn](IDatabase db, String sql, Func`4 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in ./Radarr.Core/Datastore/Extensions/SqlMapperExtensions.cs:line 74
   at NzbDrone.Core.Datastore.SqlMapperExtensions.QueryJoined[T,T2,T3](IDatabase db, SqlBuilder builder, Func`4 mapper) in ./Radarr.Core/Datastore/Extensions/SqlMapperExtensions.cs:line 164
   at NzbDrone.Core.Movies.MovieRepository.All() in ./Radarr.Core/Movies/MovieRepository.cs:line 111
   at NzbDrone.Core.Movies.MovieService.GetAllMovies() in ./Radarr.Core/Movies/MovieService.cs:line 233
   at NzbDrone.Core.HealthCheck.Checks.RemovedMovieCheck.Check() in ./Radarr.Core/HealthCheck/Checks/RemovedMovieCheck.cs:line 25
   at NzbDrone.Core.HealthCheck.HealthCheckService.<ProcessHealthChecks>b__15_0(IProvideHealthCheck c) in ./Radarr.Core/HealthCheck/HealthCheckService.cs:line 98
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.HealthCheck.HealthCheckService.ProcessHealthChecks() in ./Radarr.Core/HealthCheck/HealthCheckService.cs:line 85
   at NzbDrone.Core.HealthCheck.HealthCheckService.HandleAsync(ApplicationStartedEvent message) in ./Radarr.Core/HealthCheck/HealthCheckService.cs:line 162
   at NzbDrone.Core.Messaging.Events.EventAggregator.<>c__DisplayClass6_2`1.<PublishEvent>b__2() in ./Radarr.Core/Messaging/Events/EventAggregator.cs:line 120
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
SQL: 
==== Begin Query Trace ====

QUERY TEXT:
SELECT "Movies".*, "MovieFiles".*, "MovieMetadata".*
 FROM "Movies"   
LEFT JOIN "MovieFiles" ON ("Movies"."MovieFileId" = "MovieFiles"."Id")
LEFT JOIN "MovieMetadata" ON ("Movies"."MovieMetadataId" = "MovieMetadata"."Id")
    

PARAMETERS:

==== End Query Trace ====
```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by ishioni** [comment]
I'm sorry but I don't see anything specific pertaining to upgrading postgres versions under that link. The instance was created using this postgres version from the very beginning (no SQLite migration whatsoever) and the failure isn't even tied to a version upgrade. The only thing that may have happened in-between was maybe something coming from recyclaar?
