### ISSUE TITLE
Radarr crashes on startup

### ISSUE THREAD

**Issue by DaveAlton** [Radarr/Radarr#10187]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Radarr crashes on startup on the newest version

### Expected Behavior

It doesn't crash on v5.8.1.8906

### Environment

```markdown
- OS: MacOS 14.4.1
- Radarr: v5.8.2.8915
- Docker Install: NO, but it crashes there too
- Using Reverse Proxy: Yes, but it crashes without using that
- Browser: NA
- Database:
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[v5.7.0.8882] NzbDrone.Common.Exceptions.RadarrStartupException: Radarr failed to start: Error creating main database
 ---> System.Exception: SQL logic error
no such index: IX_History_DownloadId
While Processing:
"DROP INDEX "IX_History_DownloadId""
 ---> code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
no such index: IX_History_DownloadId
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by DaveAlton** [comment]
The issue was that it was trying to remove an index that wasn't there. When making migrations in the future, can a check please be made to see if the index is there before deleting?
