### ISSUE TITLE
Fail To Add Torrent If It Already Exists In qBittorrent

### ISSUE THREAD

**Issue by ataaki** [Radarr/Radarr#10200]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Let's take a movie "My Movie" which is not part of my Radarr list yet.
If I download manually "My Movie" torrent in qBittorrent, and after some time I add "My Movie" to my Radarr list, when Radarr will fetch the release, it will fail to add it to qBittorrent because the torrent already exists. 
It will result in an error, and won't be processed.

### Expected Behavior

If the torrent already exists, Radarr should be able to detect it and only import the already downloaded torrent or keep track of the torrent.
And not end in an error.

### Steps To Reproduce

Download File With qBittorrent manually
Add the corresponding movie to Radarr
Pick the corresponding release of the previously file downloaded from Radarr

### Environment

```markdown
- OS: TrueNAS Jail (Debian)
- Radarr: 5.8.3.8933
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome
- Database:
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

2024-07-24 12:10:46.6|Debug|QBittorrent|Downloading torrent for movie 'La Personne aux deux personnes 2008 FRENCH 1080p WEB H264-FW' finished (15554 bytes from http://prowlarr.home.server/3/download?apikey=(removed)&link=WmlHY2hDOUNPcHFmeDU2NWNwYldBWUtsUjR4VW5wbXduK2x2Z1lCL1JadVdkL1lKbVc2OEZqWExrOVVwaUJVS2U4YkJlQ1NBNVN0dXVxaTdDRjAvNlNwa09MSzNHak9jaGNLVk42K1I4NDNpcW40dWRYWjhKY1BRNTRhR0ovS3dDOEU0SjYxK3FMV1JjMzlFYThPcTRZdzg4QnZvR3cyTTBwenYraXFMMGRjPQ&file=La+Personne+aux+deux+personnes+2008+FRENCH+1080p+WEB+H264-FW)
2024-07-24 12:10:46.6|Fatal|RadarrErrorPipeline|Request Failed. POST /api/v3/release

[v5.8.3.8933] NzbDrone.Core.Download.Clients.DownloadClientException: Download client failed to add torrent
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.AddTorrentFromFile(String fileName, Byte[] fileContent, TorrentSeedConfiguration seedConfiguration, QBittorrentSettings settings) in ./Radarr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 185
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.AddFromTorrentFile(RemoteMovie remoteMovie, String hash, String filename, Byte[] fileContent) in ./Radarr.Core/Download/Clients/QBittorrent/QBittorrent.cs:line 141
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteMovie remoteMovie, IIndexer indexer, String torrentUrl) in ./Radarr.Core/Download/TorrentClientBase.cs:line 204
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteMovie remoteMovie, IIndexer indexer) in ./Radarr.Core/Download/TorrentClientBase.cs:line 124
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie, IDownloadClient downloadClient) in ./Radarr.Core/Download/DownloadService.cs:line 97
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie, Nullable`1 downloadClientId) in ./Radarr.Core/Download/DownloadService.cs:line 63
   at Radarr.Api.V3.Indexers.ReleaseController.DownloadRelease(ReleaseResource release) in ./Radarr.Api.V3/Indexers/ReleaseController.cs:line 115
   at lambda_method449(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2024-07-24 12:10:46.6|Debug|Api|[POST] /api/v3/release: 500.InternalServerError (210 ms)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Not a bug.

Qbittorrent responds with a generic error when trying to add a duplicate. Qbit needs to correct the response to be more verbose rather than a generic fail

Ref  
- https://github.com/Sonarr/Sonarr/issues/5336
- https://github.com/qbittorrent/qBittorrent/issues/18361

**Comment by bakerboy448** [comment]
Qbit returns a successful response (200 OK) and the content of `Fails.` for duplicate torrents. If they can provide a meaningful message in response to adding a duplicate torrent then we could work with that, but as it stands right now with Sonarr having no way to differentiate between a failure and a "failure" it's going to fail and try another release.

We're not going to add an option to ignore errors.

Sonarr should be aware of the download in the queue already and reject it for already being there, unless for some reason it can't parse/match it to the series and episode.
[...]

_Originally posted by markus101 in https://github.com/Sonarr/Sonarr/issues/5336#issuecomment-1370257928_

Radarr operates the same as sonarr here
