### ISSUE TITLE
Download Queue Display Error

### ISSUE THREAD

**Issue by Alamei** [Radarr/Radarr#1023]
I'm currently running Radarr v0.2.0.375, and it no longer seems to be able to display download queue status. When anything should be showing in the download queue (i.e., there's an active download), I simply get these errors in the log, twice a minute, until the queue is cleared:

```
17-3-5 09:08:45.3|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.375] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Download.Pending.PendingReleaseService.GetPendingQueue() in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Pending\PendingReleaseService.cs:line 133
   at NzbDrone.Api.Queue.QueueModule.GetQueueItems() in C:\projects\radarr-usby1\src\NzbDrone.Api\Queue\QueueModule.cs:line 32
   at NzbDrone.Api.Queue.QueueModule.GetQueue() in C:\projects\radarr-usby1\src\NzbDrone.Api\Queue\QueueModule.cs:line 27
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourceAll>b__32_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 111
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

The download functionality itself still seems to be working fine; it's only the status monitoring that's failing. Restarting Radarr (or even restarting the entire machine it's running on) has no impact, so the issue definitely persistent between instances. 

Are there any additional tests I could run to help troubleshoot the issue?

**Comment by onedr0p** [comment]
What release name is that and what was the download client? I'll take a peek.

**Comment by Alamei** [comment]
The bug is happening on all releases, and the client is NZBGet 18.0 stable. If you think the bug is client related, I can spool up the latest version of SABnzbd and have Radarr run through that to see if it makes any difference.

**Comment by onedr0p** [comment]
Sure, let me know how it goes, I don't see that on my Radarr and NZBGet set up

**Comment by Alamei** [comment]
This issue appears to be resolved with 0.2.0.453. Still unclear what the underlying cause was, but I don't think it's worth chasing unless it crops back up in a future release.

**Comment by seanvree** [comment]
Hey guys, I'm seeing this problem a lot lately.   it's happening with both Deluge and Sabnzbd. As @Alamei stated, it downloads and imports fine, but then my logs are filled up with these errors like every 5 minutes. 

Windows 10E
Radarr:  0.2.0.535 develop

System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Download.Pending.PendingReleaseService.GetPendingQueue() in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Pending\PendingReleaseService.cs:line 133
   at NzbDrone.Api.Queue.QueueModule.GetQueueItems() in C:\projects\radarr-usby1\src\NzbDrone.Api\Queue\QueueModule.cs:line 32
   at NzbDrone.Api.Queue.QueueModule.GetQueue() in C:\projects\radarr-usby1\src\NzbDrone.Api\Queue\QueueModule.cs:line 27
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourceAll>b__32_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 111
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by galli-leo** [comment]
I know what the issue is.

**Comment by seanvree** [comment]
@galli-leo - lol, do tell!

**Comment by galli-leo** [comment]
The parsedMovieInfo (what we parse from the Release name) can be null for some reason in the db. And that causes the error.

**Comment by galli-leo** [comment]
It's an error on our side.

**Comment by seanvree** [comment]
Gotcha. It's not a huge deal as it IS working in the background.  It just doesn't show you what it's doing.  


Fix coming soon?

**Comment by galli-leo** [comment]
@onedr0p could you implement this? Shouldn't be too much of an issue. Just check ParsedMovieInfo. (Also maybe log it)

**Comment by onedr0p** [comment]
Think I have a fix incoming

**Comment by seanvree** [comment]
Any update to this gents?

**Comment by onedr0p** [comment]
I pushed a commit last week, can you see if you get the error on the latest nightly?

**Comment by seanvree** [comment]
@onedr0p  - yes.

**Comment by mattispantone81** [comment]
any update on this gents?
