### ISSUE TITLE
Cannot change "Root Folder" after migrating to Linux. "NotParentException"

### ISSUE THREAD

**Issue by dom6770** [Radarr/Radarr#10303]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I migrated from Windows to Linux and copied the configuration directory from the old to the new host. Start up was no issue, everything works perfectly.

Now, because I used a Samba Share (as UNC paths) as root folders and those are not available anymore, I need to change the "Root Folder" from over a thousand movies to my new unix path. 

When I try to change it, nothing happens, the old path is still there. 

### Expected Behavior

Radarr should change the root directory from the old UNC path to the new UNIX path.

### Steps To Reproduce

1. Go to Movies
2. Select "Edit Movies" in the upper toolbar
3. Select desired movies
4. Go to "Edit" on the lower toolbar
5. Change the root folder to the new available path.
6. Apply Changes
7. Select "No, I'll Move the Files Myself" at the prompt

### Environment

```markdown
- OS: Debian 12
- Radarr: 5.8.3.8933
- Docker Install: No
- Using Reverse Proxy: Yes (Caddy) 
- Browser: Firefox
- Database: Sqlite 3.40.1
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

```
2024-08-16 18:07:36.2|Trace|Http|Req: 1500 [GET] /api/v3/rootFolder (from REDACTED Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0)
2024-08-16 18:07:36.2|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-08-16 18:07:36.3|Debug|RootFolderService|Generating list of unmapped folders
2024-08-16 18:07:36.3|Trace|ConfigService|Using default config value for 'recyclebin' defaultValue:''
2024-08-16 18:07:36.3|Debug|RootFolderService|0 unmapped folders detected.
2024-08-16 18:07:36.3|Debug|RootFolderService|Generating list of unmapped folders
2024-08-16 18:07:36.3|Trace|ConfigService|Using default config value for 'recyclebin' defaultValue:''
2024-08-16 18:07:36.3|Debug|RootFolderService|0 unmapped folders detected.
2024-08-16 18:07:36.3|Debug|RootFolderService|Generating list of unmapped folders
2024-08-16 18:07:36.3|Trace|ConfigService|Using default config value for 'recyclebin' defaultValue:''
2024-08-16 18:07:36.3|Debug|RootFolderService|1172 unmapped folders detected.
2024-08-16 18:07:36.3|Trace|Http|Res: 1500 [GET] /api/v3/rootFolder: 200.OK (40 ms)
2024-08-16 18:07:36.3|Debug|Api|[GET] /api/v3/rootFolder: 200.OK (40 ms)
2024-08-16 18:07:50.4|Trace|Http|Req: 1501 [PUT] /api/v3/movie/editor (from REDACTED Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0)
2024-08-16 18:07:50.4|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-08-16 18:07:50.4|Trace|ConfigService|Using default config value for 'movieinfolanguage' defaultValue:'1'
2024-08-16 18:07:50.4|Trace|ConfigService|Using default config value for 'availabilitydelay' defaultValue:'0'
2024-08-16 18:07:50.6|Debug|MovieService|Updating 1 movies
2024-08-16 18:07:50.6|Trace|MovieService|Updating: 21 Jump Street
2024-08-16 18:07:50.6|Trace|RadarrErrorPipeline|Handling Exception
2024-08-16 18:07:50.6|Fatal|RadarrErrorPipeline|Request Failed. PUT /api/v3/movie/editor

[v5.8.3.8933] NzbDrone.Common.Disk.NotParentException: \\Valhalla\Storage\MOVIES\21.Jump.Street.2012.German.DL.1080p.BluRay.x264-SONS is not a child of \\Valhalla\Storage\MOVIES
   at NzbDrone.Common.Extensions.PathExtensions.GetRelativePath(String parentPath, String childPath) in ./Radarr.Common/Extensions/PathExtensions.cs:line 82
   at NzbDrone.Core.Movies.MoviePathBuilder.GetExistingRelativePath(Movie movie) in ./Radarr.Core/Movies/MoviePathBuilder.cs:line 45
   at NzbDrone.Core.Movies.MoviePathBuilder.BuildPath(Movie movie, Boolean useExistingRelativeFolder) in ./Radarr.Core/Movies/MoviePathBuilder.cs:line 29
   at NzbDrone.Core.Movies.MovieService.UpdateMovie(List`1 movies, Boolean useExistingRelativeFolder) in ./Radarr.Core/Movies/MovieService.cs:line 268
   at Radarr.Api.V3.Movies.MovieEditorController.SaveAll(MovieEditorResource resource) in ./Radarr.Api.V3/Movies/MovieEditorController.cs:line 110
   at lambda_method276(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2024-08-16 18:07:50.6|Trace|Http|Res: 1501 [PUT] /api/v3/movie/editor: 500.InternalServerError (193 ms)
2024-08-16 18:07:50.6|Debug|Api|[PUT] /api/v3/movie/editor: 500.InternalServerError (193 ms)
2024-08-16 18:07:51.5|Trace|Scheduler|Pending Tasks: 0
```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
already fixed in nightly
https://github.com/Radarr/Radarr/commit/322df78f5a2aaaecd77eab5f78d8777ea735b118
