### ISSUE TITLE
Couldn't import ... Value cannot be null. (Parameter 'path2')

### ISSUE THREAD

**Issue by cmer** [Radarr/Radarr#10373]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

After downloading a movie, it fails to import with this exception:

```
Couldn't import movie /downloads/foobar/foobar.iso: Value cannot be null. (Parameter 'path2')

System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at NzbDrone.Core.MediaFiles.MediaInfo.UpdateMediaInfoService.UpdateMediaInfo(MovieFile movieFile, Movie movie) in ./Radarr.Core/MediaFiles/MediaInfo/UpdateMediaInfoService.cs:line 71
   at NzbDrone.Core.MediaFiles.MediaInfo.UpdateMediaInfoService.Update(MovieFile movieFile, Movie movie) in ./Radarr.Core/MediaFiles/MediaInfo/UpdateMediaInfoService.cs:line 66
   at NzbDrone.Core.Organizer.FileNameBuilder.UpdateMediaInfoIfNeeded(String pattern, MovieFile movieFile, Movie movie) in ./Radarr.Core/Organizer/FileNameBuilder.cs:line 537
   at NzbDrone.Core.Organizer.FileNameBuilder.BuildFileName(Movie movie, MovieFile movieFile, NamingConfig namingConfig, List`1 customFormats) in ./Radarr.Core/Organizer/FileNameBuilder.cs:line 114
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in ./Radarr.Core/MediaFiles/MovieFileMovingService.cs:line 75
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in ./Radarr.Core/MediaFiles/UpgradeMediaFileService.cs:line 78
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in ./Radarr.Core/MediaFiles/MovieImport/ImportApprovedMovie.cs:line 136

```

### Expected Behavior

The file should get copied over

### Steps To Reproduce

Download a movie. It crashes at import.

![CleanShot 2024-08-30 at 19 18 07@2x](https://github.com/user-attachments/assets/cb412162-c31a-4c23-a419-06b9005d95af)

### Environment

```markdown
- OS: Debian
- Radarr: 5.9.1.9070
- Docker Install: No (bare metal)
- Using Reverse Proxy: None
- Browser: N/A
- Database: Sqlite
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

Couldn't import movie /downloads/foobar/foobar.iso: Value cannot be null. (Parameter 'path2')

System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at NzbDrone.Core.MediaFiles.MediaInfo.UpdateMediaInfoService.UpdateMediaInfo(MovieFile movieFile, Movie movie) in ./Radarr.Core/MediaFiles/MediaInfo/UpdateMediaInfoService.cs:line 71
   at NzbDrone.Core.MediaFiles.MediaInfo.UpdateMediaInfoService.Update(MovieFile movieFile, Movie movie) in ./Radarr.Core/MediaFiles/MediaInfo/UpdateMediaInfoService.cs:line 66
   at NzbDrone.Core.Organizer.FileNameBuilder.UpdateMediaInfoIfNeeded(String pattern, MovieFile movieFile, Movie movie) in ./Radarr.Core/Organizer/FileNameBuilder.cs:line 537
   at NzbDrone.Core.Organizer.FileNameBuilder.BuildFileName(Movie movie, MovieFile movieFile, NamingConfig namingConfig, List`1 customFormats) in ./Radarr.Core/Organizer/FileNameBuilder.cs:line 114
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in ./Radarr.Core/MediaFiles/MovieFileMovingService.cs:line 75
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in ./Radarr.Core/MediaFiles/UpgradeMediaFileService.cs:line 78
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in ./Radarr.Core/MediaFiles/MovieImport/ImportApprovedMovie.cs:line 136

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by cmer** [comment]
Great! I'll wait for the next release.
