### ISSUE TITLE
Radarr API Error: 500 Error from Radarr API For Specific Movie (Change pas de main)

### ISSUE THREAD

**Issue by LeeThompson** [Radarr/Radarr#10487]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When attempting to add the film _Change pas de main_ (tt0122430) (125177) ,Radarr fails with "Unable to communicate with RadarrAPI."   Other films can be added without any issue.

In the trace logs, the calls to `https://api.radarr.video/v1/movie` are failing with error 500.

**This appears to be an issue with the Radarr API, _not_ with the application itself.**

### Expected Behavior

It should add the movie.

### Steps To Reproduce

1. Attempt to add "`imdb:tt0122430`" or "`tmdb:125177`"

### Environment

```markdown
- OS: Synology DSM (Debian)
- Radarr: 5.11.0.9244
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Any
- Database: Sqlite 3.45.3
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

```
2024-09-26 19:03:53.5|Warn|SkyHookProxy|NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://api.radarr.video/v1/movie/imdb/tt0122430]

[v5.11.0.9244] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://api.radarr.video/v1/movie/imdb/tt0122430]
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieByImdbId(String imdbId) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 216
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 469



2024-09-26 19:03:57.3|Warn|SkyHookProxy|NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://api.radarr.video/v1/movie/imdb/tt0122430]

[v5.11.0.9244] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://api.radarr.video/v1/movie/imdb/tt0122430]
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieByImdbId(String imdbId) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 216
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 469



2024-09-26 19:04:06.5|Warn|SkyHookProxy|NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://api.radarr.video/v1/movie/imdb/tt0122430]

[v5.11.0.9244] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://api.radarr.video/v1/movie/imdb/tt0122430]
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieByImdbId(String imdbId) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 216
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 469



2024-09-26 19:04:09.5|Info|Radarr.Http.Authentication.BasicAuthenticationHandler|Basic was not authenticated. Failure message: Authorization header missing.
2024-09-26 19:04:14.2|Warn|SkyHookProxy|NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://api.radarr.video/v1/movie/imdb/tt0122430]

[v5.11.0.9244] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://api.radarr.video/v1/movie/imdb/tt0122430]
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieByImdbId(String imdbId) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 216
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 469



2024-09-26 19:05:27.0|Warn|SkyHookProxy|NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://api.radarr.video/v1/movie/125177]

[v5.11.0.9244] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://api.radarr.video/v1/movie/125177]
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieInfo(Int32 tmdbId) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 121
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 491



2024-09-26 19:06:24.6|Warn|SkyHookProxy|NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://api.radarr.video/v1/movie/imdb/tt0122430]

[v5.11.0.9244] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://api.radarr.video/v1/movie/imdb/tt0122430]
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieByImdbId(String imdbId) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 216
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 469



2024-09-26 19:07:43.2|Warn|SkyHookProxy|NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://api.radarr.video/v1/movie/125177]

[v5.11.0.9244] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://api.radarr.video/v1/movie/125177]
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieInfo(Int32 tmdbId) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 121
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 491
```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by LeeThompson** [comment]
It's not a porno.

**Comment by LeeThompson** [comment]
Fair enough I suppose, maybe have a more specific error message in these cases so it doesn't look like something is broken?
