### ISSUE TITLE
Client is not configured yet

### ISSUE THREAD

**Issue by alexsamson1988** [Radarr/Radarr#10515]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I try to download a movie (interactive search and I guess it does the same for automatic search) I get client is not configured yet error. The same configuration works in both sonarr and prowlarr but not in radarr for some reasons. I completely deleted my radarr installation and redid it (a couple of times using different docker images) with the same result. I also started a brand new container on my windows machine (I am using unraid) and had the exact same issue.

![image](https://github.com/user-attachments/assets/7c5f38ed-704c-4d8e-8924-49715c7e04c4)

Yes deluge is added as a torrent client.

### Expected Behavior

Download the movie as expected

### Steps To Reproduce

In docker start a docker container using either binhex/arch-radarr or linuxserver/radarr image
Add one indexer and deluge as the only download client.
Setup a remote path
try downloading a movie

### Environment

```markdown
- OS: Unraid and windows on docker
- Radarr: 5.11.0.9244
- Docker Install: linuxserver/radarr
- Using Reverse Proxy: no
- Browser: Firefox and chrome
- Database: Sqlite 3.46.0
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

NzbDrone.Core.Download.Clients.DownloadClientUnavailableException: Torrent Download client isn't configured yet
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie, IDownloadClient downloadClient) in ./Radarr.Core/Download/DownloadService.cs:line 74
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie, Nullable`1 downloadClientId) in ./Radarr.Core/Download/DownloadService.cs:line 63
   at Radarr.Api.V3.Indexers.ReleaseController.DownloadRelease(ReleaseResource release) in ./Radarr.Api.V3/Indexers/ReleaseController.cs:line 115
   at lambda_method285(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Additionally to being a support issue, invalid bug report. Trace Logs  check box checked in error and not followed.
