### ISSUE TITLE
Failed to load queue

### ISSUE THREAD

**Issue by cxtal** [Radarr/Radarr#10572]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

After adding some movies and also removing them fast enough the queue gets stuck and "Failed to load queue" shows when loading the queue.

### Expected Behavior

The message should not appear and the queue should be displayed.

### Environment

```markdown
- Radarr: 5.12.2.9335
- Database: Sqlite 3.45.3
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

```
2024-10-20 10:59:25.1|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/queue

[v5.12.2.9335] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Jobs.TaskManager.GetNextExecution(Type type) in ./Radarr.Core/Jobs/TaskManager.cs:line 59
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at NzbDrone.Core.Download.Pending.PendingReleaseService.GetQueueItem(PendingRelease pendingRelease, Lazy`1 nextRssSync, Movie movie) in ./Radarr.Core/Download/Pending/PendingReleaseService.cs:line 313
   at NzbDrone.Core.Download.Pending.PendingReleaseService.GetPendingQueue() in ./Radarr.Core/Download/Pending/PendingReleaseService.cs:line 193
   at Radarr.Api.V3.Queue.QueueController.GetQueue(PagingSpec`1 pagingSpec, HashSet`1 movieIds, Nullable`1 protocol, HashSet`1 languages, Nullable`1 quality, Boolean includeUnknownMovieItems)
   at Radarr.Api.V3.Queue.QueueController.<>c__DisplayClass13_0.<GetQueue>b__0(PagingSpec`1 spec) in ./Radarr.Api.V3/Queue/QueueController.cs:line 163
   at Radarr.Http.Extensions.RequestExtensions.ApplyToPage[TResource,TModel](PagingSpec`1 pagingSpec, Func`2 function, Converter`2 mapper) in ./Radarr.Http/Extensions/RequestExtensions.cs:line 58
   at Radarr.Api.V3.Queue.QueueController.GetQueue(PagingRequestResource paging, Boolean includeUnknownMovieItems, Boolean includeMovie, Int32[] movieIds, Nullable`1 protocol, Int32[] languages, Nullable`1 quality)
   at lambda_method43(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/UrlBaseMiddleware.cs:line 29
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by cxtal** [comment]
Hello @mynameisbogdan ! Which logs? The log lines highlighting the exception being thrown have already been provided.

**Comment by cxtal** [comment]
```
   return scheduledTask.LastExecution.AddMinutes(scheduledTask.Interva
```

It seems your ``GetNextExecution`` method at line 61 assumes that ``cache.Find()`` will always succeed, which more than likely is not the case such that it might lead to the unknown object reference exception being thrown.

To your question though:

> Do you use any arr-scripts/extended scripts?

Seems irrelevant given that the state was reached due to adding and removing movies manually.

> we need to take to reproduce the issue.

I cannot reproduce this, or rather, perhaps I might, if I mess around adding and deleting releases but it does not seem consistent. 

Unfortunately, I will not provide the full ``radar.txt`` logs because they contain too much personal data (trackers, show names, etc). Sorry, about that. Either way, I have found a workaround for it and it works well for me so this bug report is more of a courtesy.

**Comment by cxtal** [comment]
> Actually is very relevant.

Asking a question that mentions something that was never mentioned in the report itself anywhere at any point, including how the bug appeared, and then claiming it is "very relevant", without any other explanations seems like your ESL way of saying "no, u!".

Hiding your own activity, and on a public development forum, and then expecting people to be upfront with their data seems disingenuous. I get that you're annoyed that you did not get what you wanted but it just doesn't pan out as legitimate, bud. Sorry.
