### ISSUE TITLE
SABNZBD nullable error

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#10722]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I try to download manually or automatically Venom 2005 Radarr can't send it to SABNZBD

### Expected Behavior

Should work

### Environment

```markdown
- OS: Unraid in the official docker
- Radarr: 

Version
5.15.1.9463
Package Version
5.15.1.9463-ls246 by linuxserver.io
.NET
Yes (6.0.35)

- Docker Install: Yes
- Using Reverse Proxy: 
- Browser: Edge
- Database: Sqlite 3.45.3
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

Automatic:

```
2024-11-30 19:48:00.1|Info|Sabnzbd|Adding report [Venom.2005.1080p.BluRay.AVC.DTS-HD.MA.5.1.REMUX-GODDESS] to the queue.
2024-11-30 19:48:00.2|Debug|SabnzbdProxy|Url: http://172.16.33.21:8080/api?mode=addfile&cat=movies-en&priority=-1&apikey=(removed)&output=json
2024-11-30 19:48:00.8|Warn|ProcessDownloadDecisions|Couldn't add release 'Venom.2005.1080p.BluRay.AVC.DTS-HD.MA.5.1.REMUX-GODDESS' from Indexer NZBHydra2-Radarr-EN (Newznab) to download queue.

[v5.15.1.9463] NzbDrone.Core.Download.Clients.DownloadClientException: Error response received from SABnzbd: 
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.CheckForError(HttpResponse response) in ./Radarr.Core/Download/Clients/Sabnzbd/SabnzbdProxy.cs:line 244
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in ./Radarr.Core/Download/Clients/Sabnzbd/SabnzbdProxy.cs:line 214
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.DownloadNzb(Byte[] nzbData, String filename, String category, Int32 priority, SabnzbdSettings settings) in ./Radarr.Core/Download/Clients/Sabnzbd/SabnzbdProxy.cs:line 61
   at NzbDrone.Core.Download.Clients.Sabnzbd.Sabnzbd.AddFromNzbFile(RemoteMovie remoteMovie, String filename, Byte[] fileContent) in ./Radarr.Core/Download/Clients/Sabnzbd/Sabnzbd.cs:line 42
   at NzbDrone.Core.Download.UsenetClientBase`1.Download(RemoteMovie remoteMovie, IIndexer indexer) in ./Radarr.Core/Download/UsenetClientBase.cs:line 90
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie, IDownloadClient downloadClient) in ./Radarr.Core/Download/DownloadService.cs:line 142
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie, Nullable`1 downloadClientId) in ./Radarr.Core/Download/DownloadService.cs:line 64
   at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisionInternal(DownloadDecision decision, Nullable`1 downloadClientId) in ./Radarr.Core/Download/ProcessDownloadDecisions.cs:line 225
```

When I do it manual in Radarr:

```
2024-11-30 19:56:14.7|Info|Sabnzbd|Adding report [Venom.2005.1080p.BluRay.AVC.DTS-HD.MA.5.1.REMUX-GODDESS] to the queue.
2024-11-30 19:56:14.7|Debug|SabnzbdProxy|Url: http://172.16.33.21:8080/api?mode=addfile&cat=movies-en&priority=-1&apikey=(removed)&output=json
2024-11-30 19:56:15.5|Fatal|RadarrErrorPipeline|Request Failed. POST /api/v3/release

[v5.15.1.9463] NzbDrone.Core.Download.Clients.DownloadClientException: Error response received from SABnzbd: 
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.CheckForError(HttpResponse response) in ./Radarr.Core/Download/Clients/Sabnzbd/SabnzbdProxy.cs:line 244
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in ./Radarr.Core/Download/Clients/Sabnzbd/SabnzbdProxy.cs:line 217
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.DownloadNzb(Byte[] nzbData, String filename, String category, Int32 priority, SabnzbdSettings settings) in ./Radarr.Core/Download/Clients/Sabnzbd/SabnzbdProxy.cs:line 55
   at NzbDrone.Core.Download.Clients.Sabnzbd.Sabnzbd.AddFromNzbFile(RemoteMovie remoteMovie, String filename, Byte[] fileContent) in ./Radarr.Core/Download/Clients/Sabnzbd/Sabnzbd.cs:line 45
   at NzbDrone.Core.Download.UsenetClientBase`1.Download(RemoteMovie remoteMovie, IIndexer indexer) in ./Radarr.Core/Download/UsenetClientBase.cs:line 89
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie, IDownloadClient downloadClient) in ./Radarr.Core/Download/DownloadService.cs:line 97
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie, Nullable`1 downloadClientId) in ./Radarr.Core/Download/DownloadService.cs:line 63
   at Radarr.Api.V3.Indexers.ReleaseController.DownloadRelease(ReleaseResource release) in ./Radarr.Api.V3/Indexers/ReleaseController.cs:line 115
   at lambda_method236(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/UrlBaseMiddleware.cs:line 29
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2024-11-30 19:56:15.6|Debug|Api|[POST] /api/v3/release: 500.InternalServerError (1835 ms)
```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Likely should be checking sab's debug logs
