### ISSUE TITLE
Sequence contains no elements

### ISSUE THREAD

**Issue by elit3ge** [Radarr/Radarr#1077]
**Description:**

System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324

When trying to add a indexer.

**Radarr Version:**
0.2.0.453

**Comment by onedr0p** [comment]
Your indexer doesn't suppirt searching by imdbid, search closed issues to see what i mean.
