### ISSUE TITLE
Activity status does not work.

### ISSUE THREAD

**Issue by Xenocell12** [Radarr/Radarr#1090]
Problem description: It appears Radarr is unable to show activitiy of either Sabnzbd and uTorrent. I currently run the latest versions of them. It does process correctly however.

Radarr Version: 0.2.0.453

Here is the error details below.

Message: Request Failed: Object reference not set to an instance of an object.

Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Download.Pending.PendingReleaseService.GetPendingQueue() in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Pending\PendingReleaseService.cs:line 133
   at NzbDrone.Api.Queue.QueueModule.GetQueueItems() in C:\projects\radarr-usby1\src\NzbDrone.Api\Queue\QueueModule.cs:line 32
   at NzbDrone.Api.Queue.QueueModule.GetQueue() in C:\projects\radarr-usby1\src\NzbDrone.Api\Queue\QueueModule.cs:line 27
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourceAll>b__32_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 111
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by onedr0p** [comment]
Please post the release name for the movie causing this problem.

**Comment by onedr0p** [comment]
Closing.. duplicate https://github.com/Radarr/Radarr/issues/557
