### ISSUE TITLE
Trak.tv List returning an error

### ISSUE THREAD

**Issue by WallaWallaWA** [Radarr/Radarr#1103]
**Description:**

Trak.tv List returning an error (it had been working). Trak.tv username verified as correct [https://trakt.tv/users/[username]/lists/movies] as well as List name ("movies"). List is public and is configured in Radarr as a UserCustomList (although also tried it as a UserWatchList with same failure, and then as a Private List, but same error message). Not certain if the extra "/items/movies" listed in the Log entry is the problem or if it is supposed to be part of the API call

**Radarr Version:** 0.2.0.453 on Windows 10

**Logs:** NzbDrone.Common.Http.HttpException: HTTP request failed: [401:Unauthorized] [GET] at [https://api.trakt.tv/users/[username]/lists/movies/items/movies]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 99
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchNetImportResponse(NetImportRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 131
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 108
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 144

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
Try to remove the list and add a new one.

**Comment by WallaWallaWA** [comment]
Thanks. Tried that with a new public list of just 3 movies ("wanted"), but it returned the same error message, so not sure what I'm doing wrong.
NzbDrone.Common.Http.HttpException: HTTP request failed: [401:Unauthorized] [GET] at [https://api.trakt.tv/users/[username]/lists/wanted/items/movies]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 99
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchNetImportResponse(NetImportRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 131
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 108
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 144

**Comment by onedr0p** [comment]
Did you authorize trakt for radarr?

**Comment by geogolem** [comment]
yes, this looks like your trakt authorization is not set-up properly. Please let us know if you have in fact set this up -- and if still not working, try clearing the token and re-authorizing.. Let us know if this helps, otherwise we will have to investigate further.

**Comment by geogolem** [comment]
in the second error message, it looks like you have a username specified.. Are you sure you tried with a public list?

**Comment by WallaWallaWA** [comment]
Cleared the token and re-authorized, and that did it, working as it did before - sorry for the problem and thanks for the outstanding support and guidance.

**Comment by geogolem** [comment]
no problem -- glad you figured it out...

not quite sure what happened there (other than if you revoked access via the trakt account)... but if you have problems please let us know.
