### ISSUE TITLE
AppVeyor CI builds failing

### ISSUE THREAD

**Issue by mitchellcash** [Radarr/Radarr#1118]
AppVeyor CI builds are failing, here is the log of the failed test from AppVeyor:

```
NzbDrone.Windows.Test.DiskProviderTests.DiskProviderFixture.directory_exist_should_be_able_to_find_existing_folder
Expected True, but found False.
at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\Shared\Execution\LateBoundTestFramework.cs:line 31
at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
at FluentAssertions.Primitives.BooleanAssertions.BeTrue(String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\BooleanAssertions.cs:line 55
at NzbDrone.Common.Test.DiskTests.DiskProviderFixtureBase`1.directory_exist_should_be_able_to_find_existing_folder() in C:\projects\radarr-usby1\src\NzbDrone.Common.Test\DiskTests\DiskProviderFixtureBase.cs:line 15
```

**Comment by onedr0p** [comment]
Tests are being a nuance at the moment and randomly fail sometimes in appveyor. I issued a rebuild on you pr and now it passed.

**Comment by mitchellcash** [comment]
@onedr0p thanks. Should we leave this open so someone can come through and fix it? Seems like it's an ongoing issue.

**Comment by onedr0p** [comment]
We're looking into it, no reason for an issue. We're going to get team city builds going instead.

**Comment by mitchellcash** [comment]
@onedr0p sounds good!

**Comment by galli-leo** [comment]
@mitchellcash to add to that. It seems to be a windows problem, not really related to appveyor. According to markus, the same happens with their Sonarr tests on Windows :( We will have to move to a linux environment to fix them.
