### ISSUE TITLE
API calls to Radarr nightly build fail from nzbToMedia and Deluge

### ISSUE THREAD

**Issue by ghallford** [Radarr/Radarr#1129]
**Description:**

nzbToMedia error:

nzbToRadarr: [15:57:59] [ERROR]::RADARR: Server returned status 500

Radarr debug logs:

17-3-11 15:59:03.1|Debug|Nzbget|Downloaded nzb for episode 'Weiner.2016.720p.WEB-DL.DD5.1.H264-FGT' finished (607162 bytes from https://api.nzbgeek.info/api?t=get&id=afbbb5754c584b42e36e81752eb0c754&apikey=(removed)
17-3-11 15:59:03.1|Info|Nzbget|Adding report [Weiner.2016.720p.WEB-DL.DD5.1.H264-FGT] to the queue.
17-3-11 15:59:03.6|Warn|ProcessDownloadDecisions|Couldn't add report to download queue. Weiner.2016.720p.WEB-DL.DD5.1.H264-FGT

[v0.2.0.534] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to add nzb Weiner.2016.720p.WEB-DL.DD5.1.H264-FGT.nzb
   at NzbDrone.Core.Download.Clients.Nzbget.Nzbget.AddFromNzbFile(RemoteMovie remoteMovie, String filename, Byte[] fileContents) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Nzbget\Nzbget.cs:line 51
   at NzbDrone.Core.Download.UsenetClientBase`1.Download(RemoteMovie remoteEpisode) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\UsenetClientBase.cs:line 108
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\DownloadService.cs:line 119
   at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions(List`1 decisions) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:line 91

17-3-11 15:59:13.4|Debug|Nzbget|Downloaded nzb for episode 'Weiner.2016.720p.WEB-DL.DD5.1.H264-FGT' finished (606577 bytes from https://www.usenet-crawler.com/getnzb/9b14d016f878df2b3aaae7bc6316324f.nzb&i=359869&r=45bb0106e9eb47e8b38126f13befdfb9)
17-3-11 15:59:13.4|Info|Nzbget|Adding report [Weiner.2016.720p.WEB-DL.DD5.1.H264-FGT] to the queue.
17-3-11 15:59:13.8|Warn|ProcessDownloadDecisions|Couldn't add report to download queue. Weiner.2016.720p.WEB-DL.DD5.1.H264-FGT

[v0.2.0.534] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to add nzb Weiner.2016.720p.WEB-DL.DD5.1.H264-FGT.nzb
   at NzbDrone.Core.Download.Clients.Nzbget.Nzbget.AddFromNzbFile(RemoteMovie remoteMovie, String filename, Byte[] fileContents) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Nzbget\Nzbget.cs:line 51
   at NzbDrone.Core.Download.UsenetClientBase`1.Download(RemoteMovie remoteEpisode) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\UsenetClientBase.cs:line 108
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\DownloadService.cs:line 119
   at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions(List`1 decisions) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:line 91

17-3-11 15:59:14.8|Debug|Nzbget|Downloaded nzb for episode 'Weiner.2016.DOCU.720p.WEBRip.AAC.2.0.x264-SRG' finished (423733 bytes from https://api.nzbgeek.info/api?t=get&id=e8212561b795f15607a134bb042e60e6&apikey=(removed)
17-3-11 15:59:14.8|Info|Nzbget|Adding report [Weiner.2016.DOCU.720p.WEBRip.AAC.2.0.x264-SRG] to the queue.
17-3-11 15:59:15.1|Info|DownloadService|Report sent to NZBGet. Weiner.2016.DOCU.720p.WEBRip.AAC.2.0.x264-SRG

**Radarr Version:**

0.2.0.534

**Logs:**

**Comment by onedr0p** [comment]
Please search closed issues.

**Comment by ghallford** [comment]
If you're referring to https://github.com/Radarr/Radarr/issues/1123, that is not it. That resolved one issue but not the one I put above which just started happening on the latest build. If it's another I can't find it.

**Comment by ghallford** [comment]
It seems that this should be resolved by updating nzbToMedia to nightly build due to changes Radarr made. Thanks all.
