### ISSUE TITLE
System.Data.SQLite.SQLiteException (0x80004005): constraint failed

### ISSUE THREAD

**Issue by colingg** [Radarr/Radarr#1141]
**Description:**

This error shows up in my console, so decided to make an issue. (found 3 closed ones) 

**Radarr Version:**
0.2.0.453
**Logs:**
```
17-3-12 13:06:11.2|Info|OwinHostController|  http://*:7878/
17-3-12 13:06:11.5|Info|NancyBootstrapper|Starting NzbDrone API
17-3-12 13:06:13.0|Info|BrowserService|Starting default browser. http://localhost:7878
17-3-12 13:06:13.0|Info|ProcessProvider|Opening URL [http://localhost:7878]
17-3-12 13:08:46.5|Info|NetImportSearchService|Found 14 movies on your auto enabled lists not in your library
17-3-12 13:08:47.2|Warn|SkyHookProxy|Couldn't map movie xxx1 to a movie on The Movie DB. It will not be added :(
17-3-12 13:08:47.9|Info|MovieService|Adding Movie [][xxx2] Path: [F:\MOVIES\xxx2]
17-3-12 13:08:48.1|Error|CommandExecutor|Error occurred while executing task NetImportSync

[v0.2.0.453] System.Data.SQLite.SQLiteException (0x80004005): constraint failed
UNIQUE constraint failed: Movies.TitleSlug
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteScalar(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteScalar()
   at Marr.Data.QGen.InsertQueryBuilder`1.Execute() in C:\projects\radarr-usby1\src\Marr.Data\QGen\InsertQueryBuilder.cs:line 138
   at Marr.Data.DataMapper.Insert[T](T entity) in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:line 728
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 106
   at NzbDrone.Core.Tv.MovieService.AddMovie(Movie newMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:line 141
   at NzbDrone.Core.NetImport.NetImportSearchService.Execute(NetImportSyncCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\NetImportSearchService.cs:line 166
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41

17-3-12 13:09:12.5|Info|RssSyncService|Starting RSS Sync
17-3-12 13:09:34.0|Info|DownloadDecisionMaker|Processing 200 releases
17-3-12 13:09:51.6|Info|RssSyncService|RSS Sync Completed. Reports found: 200, Reports grabbed: 0
```
replaced 2 movies with xxx1 & xxx2.

I don't know if the contraint is related to the above movie.

Could this have anything to do with the fact that Radarr doesn't auto import? I have to manually import every movie. (by clicking manual import, selecting the movie & clicking OK)

**Comment by galli-leo** [comment]
What is the xxx2 movie named?

**Comment by geogolem** [comment]
This should be fixed in a newer version.

**Comment by adamgot** [comment]
I'm running into this error in the latest nightly (0.2.0.571) with the Net Import Sync task :

```
17-3-29 19:07:44.0|Info|MovieService|Adding Movie [][House Swap] Path: [/mnt/plex/sorted2/Movies/House Swap (1985)]
17-3-29 19:07:45.6|Error|CommandExecutor|Error occurred while executing task NetImportSync

[v0.2.0.571] System.Data.SQLite.SQLiteException (0x80004005): constraint failed
UNIQUE constraint failed: Movies.TitleSlug
  at System.Data.SQLite.SQLite3.Reset (System.Data.SQLite.SQLiteStatement stmt) [0x00083] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLite3.Step (System.Data.SQLite.SQLiteStatement stmt) [0x0003c] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteDataReader.NextResult () [0x0016b] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteDataReader..ctor (System.Data.SQLite.SQLiteCommand cmd, System.Data.CommandBehavior behave) [0x00090] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteDataReader:.ctor (System.Data.SQLite.SQLiteCommand,System.Data.CommandBehavior)
  at System.Data.SQLite.SQLiteCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x0000c] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteCommand.ExecuteScalar (System.Data.CommandBehavior behavior) [0x00006] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteCommand.ExecuteScalar () [0x00006] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at Marr.Data.QGen.InsertQueryBuilder`1[T].Execute () [0x00051] in <1d842096f3d145bdb7cda3ecbc98889f>:0
  at Marr.Data.DataMapper.Insert[T] (T entity) [0x0005d] in <1d842096f3d145bdb7cda3ecbc98889f>:0
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Insert (TModel model) [0x00033] in <80be7e6734944d0299b0223e33344a45>:0
  at NzbDrone.Core.Tv.MovieService.AddMovie (NzbDrone.Core.Tv.Movie newMovie) [0x000fb] in <80be7e6734944d0299b0223e33344a45>:0
  at NzbDrone.Core.NetImport.NetImportSearchService.Execute (NzbDrone.Core.NetImport.NetImportSyncCommand message) [0x0013b] in <80be7e6734944d0299b0223e33344a45>:0
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x00081] in <80be7e6734944d0299b0223e33344a45>:0
```

**Comment by naq90** [comment]
I too am having the same exact problem. Has there been a fix?
