### ISSUE TITLE
API broke after last nights update

### ISSUE THREAD

**Issue by glennols** [Radarr/Radarr#1160]
During the nightly Radarr update the API Broke, my mp4autoconverter now reports this when trying to tell Radarr to scan a catalog:

2017-03-13 17:16:57 - autoprocess.radarr - INFO - Radarr notifier started.
2017-03-13 17:16:57 - autoprocess.radarr - INFO - Requesting Radarr to scan directory 'd:\Download\complete\movies\randommoviecatalog'.
2017-03-13 17:16:57 - autoprocess.radarr - ERROR - Update to Radarr failed, check if Radarr is running, autoProcess.ini settings and make sure your Radarr settings are correct (apikey?), or check install of python modules requests.
Traceback (most recent call last):
  File "C:\mkvmp4\autoprocess\radarr.py", line 64, in processMovie
    log.info("%sRadarr response: %s." % (infoprefix, rstate['state']))
KeyError: 'state'

Errorlog provided in Radarr log that i can find that might relate:
Request Failed: Sequence contains no matching element
ystem.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Api.Commands.CommandModule.StartCommand(CommandResource commandResource) in C:\projects\radarr-usby1\src\NzbDrone.Api\Commands\CommandModule.cs:line 43
   at NzbDrone.Api.REST.RestModule`1.<set_CreateResource>b__41_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 161
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**
0.2.0.535

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
We renamed the DownloadedMovieScan Command to DownloadedMoviesScan.
