### ISSUE TITLE
Post processing error with radarr and nzbget

### ISSUE THREAD

**Issue by Rhainland** [Radarr/Radarr#1176]
**Description:**

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:** 0.2.0.545

**Logs:**
Error presented in nzbget;
NZBGetPostProcess: 2017-03-15 00:04:16 - autoprocess.radarr - ERROR - [ERROR] Update to Radarr failed, check if Radarr is running, autoProcess.ini settings and make sure your Radarr settings are correct (apikey?), or check install of python modules requests.

Error shown in radarr;
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable1 source, Func2 predicate)
   at NzbDrone.Api.Commands.CommandModule.StartCommand(CommandResource commandResource) in C:\projects\radarr-usby1\src\NzbDrone.Api\Commands\CommandModule.cs:line 43
   at NzbDrone.Api.REST.RestModule1.<set_CreateResource>b__41_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 161
   at CallSite.Target(Closure , CallSite , Func2 , Object )
   at Nancy.Routing.Route.<>cDisplayClass4.<Wrap>b3(Object parameters, CancellationToken context)

This issue appeared by itself, i have no touched sickbeard mp4 converter, or any nzbget or radarr settings for weeks, maybe radarr broke something?

Regards

**Comment by onedr0p** [comment]
I believe you need the latest version if nzbToMedia.

**Comment by izeen** [comment]
Works fine for me now since updating sickbeard,

**Comment by Rhainland** [comment]
Grabbing the latest autoprocess that was updated 2 days ago did indeed solve this issue

Thanks!
