### ISSUE TITLE
HDbits indexer broken?

### ISSUE THREAD

**Issue by zarnexx** [Radarr/Radarr#1209]
Version
0.2.0.554

Details
Message
Unable to connect to indexer: Object reference not set to an instance of an object.

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Indexers.HDBits.HDBitsParser.ParseResponse(IndexerResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HDBits\HDBitsParser.cs:line 56
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 297
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324

Component	Message	Time
NzbDroneErrorPipeline	Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details	21:49
HDBits	Unable to connect to indexer: Object reference not set to an instance of an object.	21:49
DownloadDecisionMaker	No results found	21:49
Friday, 17 March 2017 21:49:45
NzbSearchService	Searching 0 indexers for [Assassin's Creed]	21:49
DownloadDecisionMaker	No results found	21:49

**Comment by onedr0p** [comment]
I have a fix incoming this weekend.
