### ISSUE TITLE
nothing downloading

### ISSUE THREAD

**Issue by dodgydaveuk** [Radarr/Radarr#1223]
Since the last update, i have added films & the come up with errors in the logs

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.DecisionEngine.Specifications.RssSync.DelaySpecification.IsSatisfiedBy(RemoteMovie subject, SearchCriteriaBase searchCriteria) in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\Specifications\RssSync\DelaySpecification.cs:line 0
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteMovie remoteMovie, SearchCriteriaBase searchCriteriaBase) in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 248
```

Radarr Version 0.2.0.535

**Comment by dodgydaveuk** [comment]
seem to have sorted it, when it added a movie it didnt give it a profile, had to add manually. going to test another
