### ISSUE TITLE
Unable to search movies

### ISSUE THREAD

**Issue by Rhainland** [Radarr/Radarr#1267]
Seems out of nowhere, i am unable to search for movies

Latest nightly

Couldn't process release.: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Parser.ParsingService.GetMovie(ParsedMovieInfo parsedMovieInfo, String imdbId, SearchCriteriaBase searchCriteria) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 426
   at NzbDrone.Core.Parser.ParsingService.Map(ParsedMovieInfo parsedMovieInfo, String imdbId, SearchCriteriaBase searchCriteria) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 229
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.<GetMovieDecisions>d__6.MoveNext() in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 73

And
Movie search failed: Object reference not set to an instance of an object.: Object reference not set to an instance of an object.

System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Api.Indexers.ReleaseResourceMapper.ToResource(DownloadDecision model) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseResource.cs:line 96
   at NzbDrone.Api.Indexers.ReleaseModuleBase.MapDecision(DownloadDecision decision, Int32 initialWeight) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModuleBase.cs:line 24
   at NzbDrone.Api.Indexers.ReleaseModule.MapDecision(DownloadDecision decision, Int32 initialWeight) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 172
   at NzbDrone.Api.Indexers.ReleaseModuleBase.MapDecisions(IEnumerable`1 decisions) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModuleBase.cs:line 12
   at NzbDrone.Api.Indexers.ReleaseModule.GetMovieReleases(Int32 movieId) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 138

Did anything break in the latest nightly? Or did something break my end?

**Comment by tooviral** [comment]
Getting the same here as well

**Comment by testarea1** [comment]
Same here, log full of this error:
```
[v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) [0x001db] in <1d9eda3b021e4e638006da4e84d154aa>:0 
  at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) [0x0000d] in <1d9eda3b021e4e638006da4e84d154aa>:0 
  at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () [0x00128] in <1d9eda3b021e4e638006da4e84d154aa>:0 
```

**Comment by tooviral** [comment]
looks like automated search works, just manual search errors out

**Comment by foux** [comment]
Same for me an manual search

**Comment by galli-leo** [comment]
Fixed in latest nightly (should be up in a few minutes).
