### ISSUE TITLE
Can't  add my personal localhost indexer

### ISSUE THREAD

**Issue by xCerNx** [Radarr/Radarr#1342]
Hi.

I run my own NewzNab indexer, but I am not allowed to add it.
If I try to save, I get "Unable to connect to the indexer"

I've tried both Http://localhost/ and http://192.168.0.101/

System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324

It works perfectly in Sonarr.

**Comment by galli-leo** [comment]
You have to enable movie search on your indexer.
