### ISSUE TITLE
Movies download but will not move to selected folder

### ISSUE THREAD

**Issue by Teke14** [Radarr/Radarr#1404]
Here is the log I am getting. Hopefully someone can help.

Request Failed: Sequence contains no matching element

Exception

System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Api.Commands.CommandModule.StartCommand(CommandResource commandResource) in C:\projects\radarr-usby1\src\NzbDrone.Api\Commands\CommandModule.cs:line 43
   at NzbDrone.Api.REST.RestModule`1.<set_CreateResource>b__41_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 161
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by galli-leo** [comment]
Do you see anything else in the logs? Also Request Failed usually means that you made a request. Are you trying to manually import something? Can you verify that that error corresponds with not importing the movie?

**Comment by Teke14** [comment]
I have this installed on a 2012 R2 box with Sonarr working great. I have the nightly build running. I can add movies and it passes it off to Sab with no issues. I have given System full rights to the download folder. This is a different folder than sonarr. When the movie downloads it just sits there. When I try a manual import this is when I get the error and nothing happens. Someone said I needed to create a group and then assign rights of the group to the folder. I didn't do that.
I will look at home when I get there for any other logs.

**Comment by galli-leo** [comment]
This should now be fixed on the latest nightly (live in a few minutes) Can you verify that?

**Comment by Teke14** [comment]
No go. Same error and won't post process.

Message

Request Failed: Sequence contains no matching element


Exception

System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source,
Func`2 predicate)
   at NzbDrone.Api.Commands.CommandModule.StartCommand(CommandResource
commandResource) in
C:\projects\radarr-usby1\src\NzbDrone.Api\Commands\CommandModule.cs:line
43
   at NzbDrone.Api.REST.RestModule`1.<set_CreateResource>b__41_0(Object
options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line
161
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object
parameters, CancellationToken context)

**Comment by Teke14** [comment]
It is working now. I had to set the drone factory interval from 0 to 1. Sonarr is not set like that. Thank you for all your help.
