### ISSUE TITLE
DownloadMonitoringService errors

### ISSUE THREAD

**Issue by Davst** [Radarr/Radarr#1411]
version: 0.2.0.596

Error:
Couldn't process tracked download En.man.som.heter.Ove.2015.1080p.BluRay.DTS.x264-VietHD: Object reference not set to an instance of an object.

------------------
System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Download.CompletedDownloadService.<>c.<Import>b__9_3(ImportResult v) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\CompletedDownloadService.cs:line 132
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Download.CompletedDownloadService.Import(TrackedDownload trackedDownload) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\CompletedDownloadService.cs:line 130
   at NzbDrone.Core.Download.CompletedDownloadService.Process(TrackedDownload trackedDownload, Boolean ignoreWarnings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\CompletedDownloadService.cs:line 107
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientItems(IDownloadClient downloadClient, DownloadClientItem downloadItem) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 128
Close

------------------

Getting about 1 error per minute like this in my logs at the moment.

Have looked at the previous errors like this. not running a delay on torrents and it has quality set.

**Comment by danseitz** [comment]
I think I'm having the same issue on my end. Here's what my log is showing:

```
17-4-18 14:49:12.2|Error|DownloadMonitoringService|Couldn't process tracked download Rogue.One.2016.720p.BluRay.DTS.x264-HiDt

[v0.2.0.596] NzbDrone.Core.Datastore.ModelNotFoundException: Movie with ID 28 does not exist
   at NzbDrone.Core.Datastore.BasicRepository`1.Get(Int32 id) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 74
   at NzbDrone.Core.Tv.MovieService.GetMovie(Int32 movieId) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:line 135
   at NzbDrone.Core.Download.CompletedDownloadService.Process(TrackedDownload trackedDownload, Boolean ignoreWarnings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\CompletedDownloadService.cs:line 96
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientItems(IDownloadClient downloadClient, DownloadClientItem downloadItem) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 128

```

**Comment by danseitz** [comment]
On looking further, I don't have a folder C:\projects\radarr-usby1\ etc. Is this a code error referencing a non-existent folder?

**Comment by galli-leo** [comment]
@Davst Your error is probably fixed in the latest release. Can you please double check?

@danseitz Your error is something different. It seems like you deleted a movie you added to your queue? Try either readding the movie to your queue or deleting the download from your download client. A restart of Radarr might also fix this.
