### ISSUE TITLE
Downloader doesn't automatically get the best quality available

### ISSUE THREAD

**Issue by dawtmaytrikx** [Radarr/Radarr#147]
I've set up a profile including 720p and 1080p BluRay, with 1080p being the cutoff. Even though both qualities are available for the movies I'm looking for, on several occasions the downloader grabbed the 720p file first and only grabbed the 1080p version after I removed the one it chose from nzbget.

**Comment by kniffs** [comment]
I got the same behaviour and from the Discord chat it seems they are working on it at the moment.

My general feeling is that Radarr knows what different qualities are, it just doesn't know how to prioritize which one you want. It just took the first search result that matched my profile.

**Comment by julestop** [comment]
Same behavior on my end. Does it still go and re-download to the highest quality and then stop? If it does do that, it wouldn't be a deal breaker for me.

**Comment by julestop** [comment]
This seams to still be happening to me...

[v0.2.0.99] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Api.Series.SeriesModule.Handle(MediaCoversUpdatedEvent message) in C:\projects\radarr-usby1\src\NzbDrone.Api\Series\SeriesModule.cs:line 239
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

17-1-12 18:59:29.6|Info|RssSyncService|Starting RSS Sync
17-1-12 18:59:36.3|Info|DownloadDecisionMaker|Processing 299 releases
17-1-12 18:59:37.2|Info|RssSyncService|RSS Sync Completed. Reports found: 299, Reports grabbed: 0
17-1-12 18:59:59.3|Info|NzbSearchService|Searching 3 indexers for [Anchorman: The Legend of Ron Burgundy]
17-1-12 19:00:14.3|Info|DownloadDecisionMaker|Processing 56 releases
17-1-12 19:00:15.2|Info|Nzbget|Adding report [Anchorman.The.Legend.Of.Ron.Burgundy.2004.UNRATED.720p.HDDVD.x264-SiNNERS ] to the queue.
17-1-12 19:00:15.8|Info|DownloadService|Report sent to Nzbget. Anchorman.The.Legend.Of.Ron.Burgundy.2004.UNRATED.720p.HDDVD.x264-SiNNERS 
17-1-12 19:00:15.8|Info|MovieSearchService|Movie search completed. 1 reports downloaded.

![screen shot 2017-01-12 at 7 05 51 pm](https://cloud.githubusercontent.com/assets/1585230/21913402/42dbcbfa-d8fa-11e6-9048-23b749246c97.png)
![screen shot 2017-01-12 at 7 06 18 pm](https://cloud.githubusercontent.com/assets/1585230/21913404/45a4d872-d8fa-11e6-8ddf-8360f6a9a42c.png)

**Comment by julestop** [comment]
Is it possible to re-open issues, or should I create a new one?

**Comment by galli-leo** [comment]
@julestop Can you do a manual search and post an image of how the releases are ordered? It could be that the next best 1080p release has too little seeders.

**Comment by julestop** [comment]
![image](https://cloud.githubusercontent.com/assets/1585230/21931060/580bd7f0-d967-11e6-81a1-0e6ab9cb831b.png)

![image](https://cloud.githubusercontent.com/assets/1585230/21931029/341b519a-d967-11e6-83ed-50a1f7d1d718.png)

**Comment by julestop** [comment]
@galli-leo Sorry, forgot to tag you.. not sure if you get automatically notified.

**Comment by galli-leo** [comment]
Yeah it seems that the 720p gets preferred. If the reported size is wrong that's because your indexer reports that. Can't do much about that. I took the auto prioritization from Sonarr.

**Comment by julestop** [comment]
Yeah... seems like the auto-prioritization has something going on... the one right below seems better in every way except for age... Bluray>HDDVD Unrated=Unrated 1080P>720P DTS>?
Maybe it prefers SiNNERS as a scene release?

**Comment by galli-leo** [comment]
Ah thats the problem. With usenet, age is to Sonarr important.

**Comment by julestop** [comment]
RIghton... I think you're right... is there a way to either toggle that off as an option or not sort by age at all... for me, quality is far more important, and I don't have bandwidth limits, so I don't mind if it fails a bunch as long as it goes from the best quality to worst...
Also, it isn't automatically going and getting the 1080P version even though it idenitifies that it hasn't met the cutoff. Having said that, I may not be giving it the chance as I'm watching it very closely and intervening.
