### ISSUE TITLE
Can't launch radarr.console: " The data field contains the error number." [windows]

### ISSUE THREAD

**Issue by seanvree** [Radarr/Radarr#1504]
OS:  Windows 10

**Description:**

Cannot launch radarr.console.exe

Not sure why this started, but randomly I saw the service was stopped, so I tried to restart and it fails. I didn't change any settings.

**Radarr Version:**

Version 0.2.0.691 - Nightly

**Logs:**

From Windows Events:

```
Unable to bind to the underlying transport for 127.0.0.1:7879. The IP Listen-Only list may contain a reference to an interface which may not exist on this machine.  The data field contains the error number.
```

```
17-5-10 00:32:54.0|Info|Bootstrap|Starting Radarr - C:\ProgramData\Radarr\bin\radarr.console.exe - Version 0.2.0.691
17-5-10 00:32:54.5|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Radarr\nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-5-10 00:32:54.7|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Radarr\logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-5-10 00:32:54.9|Info|Router|Application mode: Service
17-5-10 00:32:55.7|Info|OwinHostController|Listening on the following URLs:
17-5-10 00:32:55.7|Info|OwinHostController|  http://127.0.0.1:7878/radarr/
17-5-10 00:32:55.7|Info|OwinHostController|  http://127.0.0.1:7878/
17-5-10 00:32:55.7|Info|OwinHostController|  https://127.0.0.1:7879/radarr/
17-5-10 00:32:55.7|Info|OwinHostController|  https://127.0.0.1:7879/
17-5-10 00:32:55.7|Info|OwinHostController|  http://localhost:7878/radarr/
17-5-10 00:32:55.7|Info|OwinHostController|  http://localhost:7878/
17-5-10 00:32:55.7|Info|OwinHostController|  https://localhost:7879/radarr/
17-5-10 00:32:55.7|Info|OwinHostController|  https://localhost:7879/
17-5-10 00:32:55.8|Info|NancyBootstrapper|Starting NzbDrone API
17-5-10 00:35:27.4|Info|Bootstrap|Starting Radarr - C:\ProgramData\Radarr\bin\radarr.console.exe - Version 0.2.0.691
17-5-10 00:35:27.9|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Radarr\nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-5-10 00:35:28.1|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Radarr\logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-5-10 00:35:28.2|Info|Router|Application mode: Service
17-5-10 00:35:29.1|Info|OwinHostController|Listening on the following URLs:
17-5-10 00:35:29.1|Info|OwinHostController|  http://192.168.1.20:7878/radarr/
17-5-10 00:35:29.1|Info|OwinHostController|  http://192.168.1.20:7878/
17-5-10 00:35:29.1|Info|OwinHostController|  https://192.168.1.20:7879/radarr/
17-5-10 00:35:29.1|Info|OwinHostController|  https://192.168.1.20:7879/
17-5-10 00:35:29.1|Info|OwinHostController|  http://localhost:7878/radarr/
17-5-10 00:35:29.1|Info|OwinHostController|  http://localhost:7878/
17-5-10 00:35:29.1|Info|OwinHostController|  https://localhost:7879/radarr/
17-5-10 00:35:29.1|Info|OwinHostController|  https://localhost:7879/
17-5-10 00:35:29.3|Info|NancyBootstrapper|Starting NzbDrone API
```

**Comment by galli-leo** [comment]
Can you try and launch the Radarr.Console.exe with admin rights (So right click, launch as admin).
https://technet.microsoft.com/en-us/library/cc727839(v=ws.10).aspx According to this it fails to bind to the ip you set.

**Comment by seanvree** [comment]
@galli-leo  - it's always been running as admin.  Also, it doesn't matter what I put as the IP, it always errors:

```
[Info] Bootstrap: Starting Radarr - C:\ProgramData\Radarr\bin\Radarr.Console.exe - Version 0.2.0.691
[Info] MigrationLogger: *** Migrating data source=C:\ProgramData\Radarr\nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] MigrationLogger: *** Migrating data source=C:\ProgramData\Radarr\logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] Router: Application mode: Interactive
[Info] OwinHostController: Listening on the following URLs:
[Info] OwinHostController:   http://192.168.1.20:7878/radarr/
[Info] OwinHostController:   http://192.168.1.20:7878/
[Info] OwinHostController:   https://192.168.1.20:7879/radarr/
[Info] OwinHostController:   https://192.168.1.20:7879/
[Info] OwinHostController:   http://localhost:7878/radarr/
[Info] OwinHostController:   http://localhost:7878/
[Info] OwinHostController:   https://localhost:7879/radarr/
[Info] OwinHostController:   https://localhost:7879/
[Info] NancyBootstrapper: Starting NzbDrone API


[Fatal] ConsoleApp: EPIC FAIL!

[v0.2.0.691] Radarr.Host.Owin.PortInUseException: Port 7878 is already in use, please ensure NzbDrone is not already running. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: The process cannot access the file because it is being used by another process
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Radarr.Host.Owin.OwinAppFactory.CreateApp(List`1 urls) in C:\projects\radarr-usby1\src\NzbDrone.Host\Owin\OwinServiceProvider.cs:line 52
   --- End of inner exception stack trace ---
   at Radarr.Host.Owin.OwinAppFactory.CreateApp(List`1 urls) in C:\projects\radarr-usby1\src\NzbDrone.Host\Owin\OwinServiceProvider.cs:line 63
   at Radarr.Host.Owin.OwinHostController.StartServer() in C:\projects\radarr-usby1\src\NzbDrone.Host\Owin\OwinHostController.cs:line 53
   at Radarr.Host.NzbDroneServiceFactory.Start() in C:\projects\radarr-usby1\src\NzbDrone.Host\ApplicationServer.cs:line 55
   at Radarr.Host.Router.Route(ApplicationModes applicationModes) in C:\projects\radarr-usby1\src\NzbDrone.Host\Router.cs:line 38
   at Radarr.Host.Bootstrap.Start(ApplicationModes applicationModes, StartupContext startupContext) in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:line 74
   at Radarr.Host.Bootstrap.Start(StartupContext startupContext, IUserAlert userAlert, Action`1 startCallback) in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:line 40
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in C:\projects\radarr-usby1\src\NzbDrone.Console\ConsoleApp.cs:line 20

Press enter to exit...
```

**Comment by seanvree** [comment]
also, what's weird, is that in the console window - it still running?  But I don't know how to access the GUI?

```
[Fatal] ConsoleApp: EPIC FAIL!

[v0.2.0.691] Radarr.Host.Owin.PortInUseException: Port 7878 is already in use, please ensure NzbDrone is not already running. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: The process cannot access the file because it is being used by another process
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Radarr.Host.Owin.OwinAppFactory.CreateApp(List`1 urls) in C:\projects\radarr-usby1\src\NzbDrone.Host\Owin\OwinServiceProvider.cs:line 52
   --- End of inner exception stack trace ---
   at Radarr.Host.Owin.OwinAppFactory.CreateApp(List`1 urls) in C:\projects\radarr-usby1\src\NzbDrone.Host\Owin\OwinServiceProvider.cs:line 63
   at Radarr.Host.Owin.OwinHostController.StartServer() in C:\projects\radarr-usby1\src\NzbDrone.Host\Owin\OwinHostController.cs:line 53
   at Radarr.Host.NzbDroneServiceFactory.Start() in C:\projects\radarr-usby1\src\NzbDrone.Host\ApplicationServer.cs:line 55
   at Radarr.Host.Router.Route(ApplicationModes applicationModes) in C:\projects\radarr-usby1\src\NzbDrone.Host\Router.cs:line 38
   at Radarr.Host.Bootstrap.Start(ApplicationModes applicationModes, StartupContext startupContext) in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:line 74
   at Radarr.Host.Bootstrap.Start(StartupContext startupContext, IUserAlert userAlert, Action`1 startCallback) in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:line 40
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in C:\projects\radarr-usby1\src\NzbDrone.Console\ConsoleApp.cs:line 20

Press enter to exit...
[Info] RssSyncService: Starting RSS Sync
[Info] DownloadDecisionMaker: Processing 1935 releases
```

**Comment by galli-leo** [comment]
@seanvree Seems like the port is already in use? Maybe Radarr is already running or it does not have access to to use that port?

**Comment by seanvree** [comment]
@galli-leo  - I thought that too, but it doen'st matter what port I change it to, same error. I can ping that port, and nothing is using it.  It's not running and  there's nothing even close to that .exe running, and nothing around that port range running. 


```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>tcping 127.0.0.1 7878

Probing 127.0.0.1:7878/tcp - No response - time=2000.890ms
Probing 127.0.0.1:7878/tcp - No response - time=2001.753ms
Probing 127.0.0.1:7878/tcp - No response - time=2001.734ms
Probing 127.0.0.1:7878/tcp - No response - time=2001.865ms

Ping statistics for 127.0.0.1:7878
     4 probes sent.
     0 successful, 4 failed.
Was unable to connect, cannot provide trip statistics.

```

**Comment by galli-leo** [comment]
@seanvree Can you try and restart your pc?

**Comment by seanvree** [comment]
will do.

**Comment by seanvree** [comment]
@galli-leo  - wow, that was weird.  Always a REBOOT!

THANKS

**Comment by galli-leo** [comment]
Then it was probably a rogue process, still occupying the port, but not actually doing anything.

**Comment by seanvree** [comment]
Yeah, strange, never seen that before.
