### ISSUE TITLE
Updater uses Sonarr logentries token

### ISSUE THREAD

**Issue by Taloth** [Radarr/Radarr#1517]
**Description:**

The Sonarr updater pipes the update logs to LogEntries. I noticed Radarr log events, while I was monitoring the recent Sonarr deployment. This is because the [token](
https://github.com/Radarr/Radarr/blob/520836f475cd5ed79e72b663c8b3cceb820a5f4f/src/NzbDrone.Common/Instrumentation/NzbDroneLogger.cs#L66) is still the same. I've created a token for Radarr (2b9dd69e-1b30-411c-9ce7-f20149c3fd17) which you can use, or you could use your own logentries instance, or just tear it out completely.

**Radarr Version:** All

**Logs:** N/A

**Comment by galli-leo** [comment]
Thanks a lot, didn't even know we / Sonarr does this :) I used the token you created for us. How would I be able to look at the logs in that case?

**Comment by Taloth** [comment]
It's tied to our free account on logentries. I'll ask @markus101 when he gets online to see if we can add an login, coz I just noticed that the free tier doesn't have the ability to restrict logins to specific logs.
Advantage is that I can see which Update problems affect Radarr and Sonarr separately. Most of it is just crappy permissions. But some of it can be fixed or at least detected.

**Comment by galli-leo** [comment]
Ok, that sounds like something very useful. You could probably also make an issue on the Lidarr GH. Additionally, if you were seeing permission issues yesterday for Radarr logs on OSX, it was most certainly related to us changing the OSX binary name from Sonarr to Radarr, resulting in OSX not being able to find the executable anymore :/

**Comment by Taloth** [comment]
I asked markus, he thinks that it might be better if you guys have your own logentries account, meaning you'll have to change the token again. Sorry, I should've checked that first.
Here's a [referral link](https://logentries.com/learnmore?code=22477985) (The free plan has 7 days retention, 5 GB max per month, we average below 700 MB and that's including the skyhook error log).

**Comment by galli-leo** [comment]
@Taloth No problem :). I am guessing those unsuccessful attempts are all on osx?

**Comment by Taloth** [comment]
Most of em are on OSX yes, and could be multiple attempts on the same system. But not due to Radarr.exe rename:

Most seem related to it being unable to set the [permissions](https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Update/UpdateEngine/InstallUpdateService.cs#L119) on the folder after having copied in the files.
My guess is that it doesn't have ownership of the folder.

190 failures:
```
NzbDrone.Mono.Disk.LinuxPermissionsException: Error setting file permissions: ENOENT
 at NzbDrone.Mono.Disk.DiskProvider.SetPermissions (System.String path, System.String mask) [0x0003e] in C:\projects\radarr-usby1\src\NzbDrone.Mono\Disk\DiskProvider.cs:182
 at NzbDrone.Mono.Disk.DiskProvider.SetPermissions (System.String path, System.String mask, System.String user, System.String group) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Mono\Disk\DiskProvider.cs:113 
 at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start (System.String installationFolder, System.Int32 processId) [0x0011f] in C:\projects\radarr-usby1\src\NzbDrone.Update\UpdateEngine\InstallUpdateService.cs:122
```
 
 86 failures:
``` 
 NzbDrone.Mono.Disk.LinuxPermissionsException: Error setting file permissions: ENOENT
 at NzbDrone.Mono.Disk.DiskProvider.SetPermissions (System.String path, System.String mask) [0x0003e] in C:\projects\radarr-usby1\src\NzbDrone.Mono\Disk\DiskProvider.cs:182 
 at NzbDrone.Mono.Disk.DiskProvider.SetPermissions (System.String path, System.String mask, System.String user, System.String group) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Mono\Disk\DiskProvider.cs:113 
 at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start (System.String installationFolder, Int32 processId) [0x0011f] in C:\projects\radarr-usby1\src\NzbDrone.Update\UpdateEngine\InstallUpdateService.cs:122
```
 
  1 failure:
```
System.InvalidOperationException: Cannot open Radarr service on computer '.'. ---> System.ComponentModel.Win32Exception: Access is denied
 --- End of inner exception stack trace ---
 at System.ServiceProcess.ServiceController.GetServiceHandle(Int32 desiredAccess)
 at System.ServiceProcess.ServiceController.Stop()rn at NzbDrone.Common.ServiceProvider.Stop(String serviceName) in C:\projects\radarr-usby1\src\NzbDrone.Common\ServiceProvider.cs:line 132
 at NzbDrone.Update.UpdateEngine.TerminateNzbDrone.Terminate(Int32 processId) in C:\projects\radarr-usby1\src\NzbDrone.Update\UpdateEngine\TerminateNzbDrone.cs:line 40
```

  1 failure:
```
System.IO.IOException: Disk full. Path /share/CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr/nzbdrone.db" or "/tmp/radarr_update/radarr_appdata_backup/nzbdrone.db.partial~
 at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x001bd] in /SRC/mono-4.8.0/mcs/class/corlib/System.IO/File.cs:109 
 at NzbDrone.Common.Disk.DiskProviderBase.CopyFile (System.String source, System.String destination, System.Boolean overwrite) [0x000bc] in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs:226 
 at NzbDrone.Common.Disk.DiskTransferService.TryCopyFileTransactional (System.String sourcePath, System.String targetPath, System.Int64 originalSize) [0x0003e] in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:414
```

  1 failure:
```
System.ComponentModel.Win32Exception (0x80004005): No such interface supportedrn at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)rn at System.Diagnostics.Process.Start()
 at NzbDrone.Common.Processes.ProcessProvider.SpawnNewProcess(String path, String args, StringDictionary environmentVariables) in C:\projects\radarr-usby1\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 191
 at NzbDrone.Update.UpdateEngine.StartNzbDrone.Start(String installationFolder, String fileName) in C:\projects\radarr-usby1\src\NzbDrone.Update\UpdateEngine\StartNzbDrone.cs:line 83
 at NzbDrone.Update.UpdateEngine.StartNzbDrone.Start(AppType appType, String installationFolder) in C:\projects\radarr-usby1\src\NzbDrone.Update\UpdateEngine\StartNzbDrone.cs:line 44
 at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start(String installationFolder, Int32 processId) in C:\projects\radarr-usby1\src\NzbDrone.Update\UpdateEngine\InstallUpdateService.cs:line 136
 at NzbDrone.Update.UpdateApp.Start(String[] args) in C:\projects\radarr-usby1\src\NzbDrone.Update\UpdateApp.cs:line 58rn at NzbDrone.Update.UpdateApp.Main(String[] args) in C:\projects\radarr-usby1\src\NzbDrone.Update\UpdateApp.cs:line 43
```

  1 failure:
```
System.ComponentModel.Win32Exception (0x80004005): Access is deniedrn at System.Diagnostics.Process.Kill()
 at NzbDrone.Common.Processes.ProcessProvider.Kill(Int32 processId) in C:\projects\radarr-usby1\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 246
 at NzbDrone.Common.Processes.ProcessProvider.KillAll(String processName) in C:\projects\radarr-usby1\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 267
 at NzbDrone.Update.UpdateEngine.TerminateNzbDrone.Terminate(Int32 processId) in C:\projects\radarr-usby1\src\NzbDrone.Update\UpdateEngine\TerminateNzbDrone.cs:line 51
 at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start(String installationFolder, Int32 processId) in C:\projects\radarr-usby1\src\NzbDrone.Update\UpdateEngine\InstallUpdateService.cs:line 94
 at NzbDrone.Update.UpdateApp.Start(String[] args) in C:\projects\radarr-usby1\src\NzbDrone.Update\UpdateApp.cs:line 58
 at NzbDrone.Update.UpdateApp.Main(String[] args) in C:\projects\radarr-usby1\src\NzbDrone.Update\UpdateApp.cs:line 43
```
 
  1 failure:
```
System.ArgumentOutOfRangeException: Invalid process IDnParameter name: argn at NzbDrone.Update.UpdateApp.ParseProcessId (System.String arg) [0x0000e] in <2d58ca516aa444bc9ecdb517fc3dcb70>:0 
 at NzbDrone.Update.UpdateApp.ParseArgs (System.String[] args) [0x00020] in <2d58ca516aa444bc9ecdb517fc3dcb70>:0 
 at NzbDrone.Update.UpdateApp.Start (System.String[] args) [0x00000] in <2d58ca516aa444bc9ecdb517fc3dcb70>:0 
 at NzbDrone.Update.UpdateApp.Main (System.String[] args) [0x0003b] in <2d58ca516aa444bc9ecdb517fc3dcb70>:0
```

**Comment by galli-leo** [comment]
Thank you for the detailed response! Pretty sure the first two are related to the name change though :/ The permissions issue only seems to be happening when trying to start the Radarr client (Which seems kinda weird, as permissions have worked during the update or else it would have failed earlier). I am just assuming OSX gives back a permission error when it cannot find the binary, which is why the error is so weird.

**Comment by galli-leo** [comment]
Yeah Just looked and I forgot to change the binary name when the updater tries to set the executable flag.

**Comment by Taloth** [comment]
Awesome, another problem fixed.

Btw. In our log entries I had these configured tags, you might find them useful:
![image](https://cloud.githubusercontent.com/assets/6383890/26032720/78ff4360-389a-11e7-8241-c8b4d8b8b272.png)

**Comment by galli-leo** [comment]
@Taloth Thank you very much, those are very helpful :)
