### ISSUE TITLE
An error occurred while processing feed.

### ISSUE THREAD

**Issue by colfin22** [Radarr/Radarr#1537]
Radarr 0.2.0.696 on windows server 2012

I'm having trouble with my indexer disappearing. If i go to add the index it sometimes takes a few seconds to appear in the tab and when i do a test it works for the next search but stops working after about 2 searches. This is the error:

An error occurred while processing feed. https://nzbs.in/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=0317219: An error occurred while parsing EntityName. Line 448, position 43.

>System.Xml.XmlException: An error occurred while parsing EntityName. Line 448, position 43.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.FinishPartialValue()
   at System.Xml.XmlTextReaderImpl.get_Value()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NzbDrone.Core.Indexers.RssParser.LoadXmlDocument(IndexerResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\RssParser.cs:line 96
   at NzbDrone.Core.Indexers.Newznab.NewznabRssParser.PreProcess(IndexerResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Newznab\NewznabRssParser.cs:line 28
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\RssParser.cs:line 50
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 297
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(IndexerPageableRequestChain pageableRequestChain, Boolean isRecent) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 154

**Comment by galli-leo** [comment]
Seams like a malformed xml by your indexer. Nothing we can do.
