### ISSUE TITLE
PassThePopcorn - Unable to Connect to Indexer

### ISSUE THREAD

**Issue by Quiksmage** [Radarr/Radarr#1584]
Version: 0.2.0.696 

Hi, I'm currently receiving the following error when testing PTP.

It was working earlier today. I just noticed the "Indexers unavailable due to failures: PassThePopcorn" recently.

For comparison sake, my Jackett PTP is returning its 1 release per our other issue, so I believe it should be working on PTP's side.

```
17-5-27 22:23:44.5|Trace|Http|Req: 5754 [POST] /api/indexer/test
17-5-27 22:23:44.6|Debug|PassThePopcorn|Downloading Feed https://passthepopcorn.me/torrents.php?action=advanced&json=noredirect&searchstr=
17-5-27 22:23:44.6|Trace|HttpClient|Req: [GET] https://passthepopcorn.me/torrents.php?action=advanced&json=noredirect&searchstr=
17-5-27 22:23:44.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-5-27 22:23:45.3|Trace|HttpClient|Res: [GET] https://passthepopcorn.me/torrents.php?action=advanced&json=noredirect&searchstr=: 200.OK (766 ms)
17-5-27 22:23:45.3|Warn|PassThePopcorn|Unable to connect to indexer

[v0.2.0.696] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornParser.ParseResponse(IndexerResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornParser.cs:line 32
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 297
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324

17-5-27 22:23:45.4|Trace|NzbDroneErrorPipeline|Handling Exception
17-5-27 22:23:45.4|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
17-5-27 22:23:45.4|Trace|Http|Res: 5754 [POST] /api/indexer/test: 400.BadRequest (834 ms)
17-5-27 22:23:45.4|Debug|Api|[POST] /api/indexer/test: 400.BadRequest (834 ms)
17-5-27 22:23:47.2|Trace|Http|Req: 5755 [GET] /api/health
17-5-27 22:23:47.2|Trace|Http|Req: 5756 [GET] /api/diskspace
17-5-27 22:23:47.2|Trace|Http|Res: 5755 [GET] /api/health: 200.OK (8 ms)
17-5-27 22:23:47.2|Debug|Api|[GET] /api/health: 200.OK (8 ms)
17-5-27 22:23:47.2|Trace|Http|Req: 5757 [GET] /api/health
17-5-27 22:23:47.3|Trace|Http|Res: 5757 [GET] /api/health: 200.OK (17 ms)
17-5-27 22:23:47.3|Trace|ConfigService|Using default config value for 'downloadedmoviesfolder' defaultValue:''
17-5-27 22:23:47.3|Debug|Api|[GET] /api/health: 200.OK (17 ms)
17-5-27 22:23:47.3|Trace|Http|Req: 5758 [GET] /Content/Images/favicon/apple-touch-icon.png?h=UBN3ftVMb44yAaIXbvl3XA
17-5-27 22:23:47.4|Trace|Http|Res: 5758 [GET] /Content/Images/favicon/apple-touch-icon.png?h=UBN3ftVMb44yAaIXbvl3XA: 200.OK (51 ms)
17-5-27 22:23:48.5|Trace|Http|Req: 5759 [GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal
17-5-27 22:23:48.5|Trace|Http|Res: 5759 [GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (20 ms)
17-5-27 22:23:48.5|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (20 ms)
17-5-27 22:23:48.6|Trace|Http|Res: 5756 [GET] /api/diskspace: 200.OK (1322 ms)
17-5-27 22:23:48.6|Debug|Api|[GET] /api/diskspace: 200.OK (1322 ms)
17-5-27 22:23:48.6|Trace|Http|Req: 5760 [GET] /api/diskspace
17-5-27 22:23:48.6|Trace|ConfigService|Using default config value for 'downloadedmoviesfolder' defaultValue:''
17-5-27 22:23:48.7|Trace|Http|Res: 5760 [GET] /api/diskspace: 200.OK (119 ms)
17-5-27 22:23:48.7|Debug|Api|[GET] /api/diskspace: 200.OK (119 ms)
17-5-27 22:23:51.5|Trace|Http|Req: 5761 [GET] /api/log/file
17-5-27 22:23:51.5|Trace|Http|Res: 5761 [GET] /api/log/file: 200.OK (54 ms)
17-5-27 22:23:51.5|Debug|Api|[GET] /api/log/file: 200.OK (54 ms)
17-5-27 22:23:51.6|Trace|Http|Req: 5762 [GET] /api/log/file/radarr.trace.txt
```

**Comment by silvether** [comment]
Can confirm similar behaviour.

`
17-6-2 10:55:16.6|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
17-6-2 10:55:18.6|Warn|PassThePopcorn|Unable to connect to indexer

[v0.2.0.696] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) <0x40851870 + 0x017b4> in <filename unknown>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, IParseIndexerResponse parser) <0x40849880 + 0x0003a> in <filename unknown>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () <0x40981ff0 + 0x000e8> in <filename unknown>:0 

17-6-2 10:55:18.6|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details`

Let me know if I can provide any additional information to get us further.

**Comment by onedr0p** [comment]
Do you guys have 2FA turned on?

PTP is working for me w/o 2FA. Maybe try resetting your passkey and password...

**Comment by Quiksmage** [comment]
I do not use 2FA with PTP. I tried re-entering my passkey and password, but no success.

**Comment by Quiksmage** [comment]
I updated to latest nightly, and have no problems testing.
I then reverted back using the installer and continue to not have issues.
*scratches head*
any idea why that is?

**Comment by onedr0p** [comment]
Might just needed a restart, I do cache the auth response stuff in memory so you don't log in on every request.

**Comment by silvether** [comment]
Now working after restarting Radarr twice. This seems to happen intermittently and without consistency. This indexer error has been happening for some time, I will be sure to grab logs again when it reoccurs.

**Comment by onedr0p** [comment]
Solution for now, restart Radarr. I ma not sure why it doesn't re-auth.

**Comment by Quiksmage** [comment]
Just had it happen again. I'm not sure what day it happened as I haven't logged into my webui in a few days.

Radarr was last restarted ~10 days ago for update 0.2.0.778

Is there anything I should search for in the logs to help you figure this out?

Thanks!

**Comment by onedr0p** [comment]
Can you try to restart it again?

**Comment by Quiksmage** [comment]
Restarting definitely fixes it. I just wanted to update the issue on it
occuring again. If there's anything I can provide to help find a fix,
please let me know.

**Comment by onedr0p** [comment]
What system are you on and mono version? I have not experienced this on Linux with mono 4.8.0

**Comment by Quiksmage** [comment]
I'm on windows

**Comment by pairughdocks** [comment]
Likewise, completely fresh install on a Ubuntu 16.04 VM specifically for Radarr

System.Net.WebException: Error: SendFailure (Error writing headers) ---> System.Net.WebException: Error writing headers ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.
  at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (IAsyncResult asyncResult) <0x41fcba50 + 0x00103> in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (IAsyncResult ar, Boolean ignoreEmpty) <0x41fcb990 + 0x0002b> in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (IAsyncResult result) <0x41fae000 + 0x0021b> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Net.WebConnection.EndWrite (System.Net.HttpWebRequest request, Boolean throwOnError, IAsyncResult result) <0x420161e0 + 0x00207> in <filename unknown>:0 
  at System.Net.WebConnectionStream+<SetHeadersAsync>c__AnonStorey1.<>m__0 (IAsyncResult r) <0x42015ae0 + 0x00143> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetRequestStream (IAsyncResult asyncResult) <0x41f8fcb0 + 0x00137> in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetRequestStream () <0x41f4fd60 + 0x000ed> in <filename unknown>:0 
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x000d1] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:51 
  at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x000cc] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:58 
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x0007e] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:63 
  at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.Authenticate () [0x0013c] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:90 
  at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator+<GetRequest>d__18.MoveNext () [0x0001a] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:38 
  at System.Linq.Enumerable.First[TSource] (IEnumerable`1 source) <0x41e02a20 + 0x000be> in <filename unknown>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:325

**Comment by Jnakos** [comment]
I want to confirm this issue as well.
OS: Arch
Radarr version: 0.2.0.778

```
System.Exception: Failed to authenticate with PassThePopcorn.
  at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.Authenticate () [0x001d4] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:109 
  at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator+<GetRequest>d__18.MoveNext () [0x0001a] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:38 
  at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Boolean& found) [0x00045] in /build/mono/src/mono-5.0.0/external/corefx/src/System.Linq/src/System/Linq/First.cs:75 
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00000] in /build/mono/src/mono-5.0.0/external/corefx/src/System.Linq/src/System/Linq/First.cs:14 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:325
```

**Comment by galli-leo** [comment]
@pairughdocks What version of mono?

**Comment by gabo77** [comment]
Similar issue here, mono version 4.2.1

**Comment by PnoT** [comment]
This happened to me today, for the first time, and a restart resolved the issue.

Radarr:  Latest
Mono: 4.8.1
FreeNAS Jail

**Comment by PlaidFlannel43** [comment]
I'm having the same experiences on a fresh install via Quickbox on Ubuntu 16.04 x64 with Mono version 5.2.0.215.

Restarts have done nothing so far.

**Comment by demonotaku** [comment]
I have the same issue with Swizzin too.

**Comment by romtools** [comment]
Same problem for many months (maybe always?)

Sometimes the problem recurs immediately after restarting. Weird stuff happens too, like the failing indexer begins returning all possible movies instead of a search term's proper results.

**Comment by galli-leo** [comment]
@romtools This should be fixed on the latest release. Please post debug logs & exception info. I can’t help you otherwise

**Comment by darknessgp** [comment]
This is the error I get with ptp currently. Even double checked my user information to make sure it was correct and it is.

```
Details
Message
Unable to connect to indexer: Object reference not set to an instance of an object

Exception
System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000ab] in <3d347cb66de84f7da5adfb7fe6732772>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00008] in <3d347cb66de84f7da5adfb7fe6732772>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x00024] in <3d347cb66de84f7da5adfb7fe6732772>:0 
```

**Comment by Quiksmage** [comment]
if you restart radarr, does the error go away?

**Comment by galli-leo** [comment]
@darknessgp Tell us the version of Radarr you are on regardless if a restart fixes it. This should be fixed on the latest version of Radarr

**Comment by darknessgp** [comment]
That could be it. I was still on 0.2.0.910, updated to latest and it appears to connect just fine to PTP.

**Comment by darknessgp** [comment]
Can we get this re-opened? I've started experiencing this periodically with PTP. It seems a full restart corrects it, which leads me to believe Radarr is caching something (maybe session token?) that is going stale PTP side and then it's returning a error message that Radarr doesn't know how to handle.

I'm on version 0.2.0.995
 
>Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details

Exception:
> Unable to connect to indexer: Object reference not set to an instance of an object
> System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000ab] in <d8aa28644e714db4911f8ceaa451a1ed>:0 
>   at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00008] in <d8aa28644e714db4911f8ceaa451a1ed>:0 
>   at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x00024] in <d8aa28644e714db4911f8ceaa451a1ed>:0

**Comment by iandeath** [comment]
This seems to be happening to me now. Radarr on a seedbox, unable to add PtP:
I have restarted it, reinstalled it, changed my passkey, tried it through jackett - all failing. Other indexers are fine though.


Message
Unable to connect to indexer: Failed to authenticate with PassThePopcorn.

Exception
System.Exception: Failed to authenticate with PassThePopcorn.
  at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.Authenticate () [0x0019f] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:103 
  at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator+<GetRequest>d__26.MoveNext () [0x00035] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:44 
  at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Boolean& found) [0x00045] in <c0502b9f220448589f6c0bfcd98a6c9b>:0 
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00000] in <c0502b9f220448589f6c0bfcd98a6c9b>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x00019] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:297

**Comment by Quiksmage** [comment]
If it's not working in jackett as well, there's likely something wrong with your account info. I can confirm that PTP works in Jackett Version 0.8.1039.0 and in Radarr Ver. 0.2.0.1067

When you test in jackett, is it successful?
![image](https://user-images.githubusercontent.com/12449533/41004646-71191354-68cf-11e8-9f31-f4754a3ec563.png)

**Comment by Quiksmage** [comment]
I'm pretty sure this can be closed @galli-leo 

@iandeath 
if you can't figure out you're issue, you'll likely want to open a new issue on github as what you posted isn't directly related to this one.
In this one, the cookie expired after ~7 days and wouldn't re-auth without rebooting PTP. 
Your issue seems to be entirely at the auth level.

**Comment by iandeath** [comment]
@Quiksmage - i only used jackett as a test to see if that worked when radarr wouldn't, i got this error from there so maybe it is something more general than radarr.
<img width="391" alt="screenshot 2018-06-05 23 03 44" src="https://user-images.githubusercontent.com/39970443/41005468-72543d48-6915-11e8-87e1-06bdbc582892.png">
