### ISSUE TITLE
qBitTorrent 3.3.13 broken due to new CSRF implementation in qbit

### ISSUE THREAD

**Issue by OneBigGuy** [Radarr/Radarr#1608]
This is an issue copied from Sonarr, which occurs in Radarr as well:  [Sonarr/Sonarr#1956](https://github.com/Sonarr/Sonarr/issues/1956).

Looks like qbit added Origin: or Referer: header requirements on the api for 3.3.13: qbittorrent/qBittorrent@087856d

Needs to be verified first, and then we should probably just send out the Origin header as appropriate.

**Comment by sfnetwork** [comment]
I confirm, I have this issue since 3.3.13

**Comment by gvtters** [comment]
Same here.

`7-6-2 17:37:35.6|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unknown exception: Failed to connect to qBitTorrent, please check your settings.
17-6-2 17:39:08.9|Warn|HttpClient|HTTP Error - Res: [POST] http://localhost:8888/login: 401.Unauthorized
17-6-2 17:39:08.9|Error|QBittorrent|Failed to connect to qBitTorrent, please check your settings.

[v0.2.0.696] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBitTorrent, please check your settings. ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [401:Unauthorized] [POST] at [http://localhost:8888/login]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 99
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, QBittorrentSettings settings, Boolean reauthenticate) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 214
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, QBittorrentSettings settings, Boolean reauthenticate) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 224
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest[TResult](HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 156
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.GetVersion(QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 45
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 181
``

**Comment by galli-leo** [comment]
Seems like qbittorrent may remove that requirement (since it seems a bit silly). I will wait for their answer.

**Comment by MithrilTuxedo** [comment]
For the lazy: localhost calls will work again unauthenticated after adding `http://localhost:8090` as the `Origin` or `Referer` header to whatever you've got going on.

**Comment by galli-leo** [comment]
Or we wait for https://github.com/qbittorrent/qBittorrent/pull/6887 to be merged :)

**Comment by brandonb927** [comment]
Just ran into this issue and noticed https://github.com/qbittorrent/qBittorrent/pull/6887 was merged! This issue is keeping me from getting Radarr setup with qbit, so happy to see progress here.

**Comment by brandonb927** [comment]
@galli-leo any movement here?

**Comment by galli-leo** [comment]
@brandonb927 No, just waiting for qBittorrent 3.3.14 to be released.

**Comment by brandonb927** [comment]
Yay, looks like 3.3.14 was released this afternoon and closes https://github.com/qbittorrent/qBittorrent/issues/6882 💃

**Comment by jsimonetti** [comment]
Sonarr has added a fix for the 3.3.14 API in their download client handling with commit https://github.com/Sonarr/Sonarr/commit/126b849c270391f912d7ce3d125fd7fbdc82268c

**Comment by Qstick** [comment]
Same as #1889?
