### ISSUE TITLE
Nightly update shows corrupt database after update but database looks fine

### ISSUE THREAD

**Issue by ghallford** [Radarr/Radarr#1678]
**Description:**

Nightly update shows corrupt database but database looks fine. Followed the link it shows and did the move to a new db file as well but still says it's corrupted. Also restored from nightly db backups from days ago and still says corrupted but was working fine. 

sqlite> PRAGMA integrity_check;
ok

**Radarr Version:**

Tried even going back to 0.2.0.692 and gives same error

**Logs:**

17-6-13 07:43:10.1|Info|InstallUpdateService|Deleting old update files
17-6-13 07:43:10.3|Info|InstallUpdateService|Downloading update 0.2.0.760
17-6-13 07:43:23.7|Info|InstallUpdateService|Verifying update package
17-6-13 07:43:23.9|Info|InstallUpdateService|Update package verified successfully
17-6-13 07:43:23.9|Info|InstallUpdateService|Extracting Update package
17-6-13 07:43:25.2|Info|InstallUpdateService|Update package extracted successfully
17-6-13 07:43:25.2|Info|BackupService|Starting Backup
17-6-13 07:43:25.5|Info|InstallUpdateService|Preparing client
17-6-13 07:43:25.5|Info|InstallUpdateService|Starting update client C:\Users\htpcuser\AppData\Local\Temp\radarr_update\Radarr.Update.exe
17-6-13 07:43:25.5|Info|InstallUpdateService|Radarr will restart shortly.
17-6-13 07:43:25.6|Info|InstallUpdateService|Updater Arguments: 9984 C:\Users\htpcuser\AppData\Local\Temp\radarr_update "C:\Program Files\Radarr\Radarr.exe" /nobrowser
17-6-13 07:43:27.4|Info|Bootstrap|Starting Radarr - C:\Program Files\Radarr\Radarr.exe - Version 0.2.0.760
17-6-13 07:43:28.1|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Radarr\nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-13 07:43:28.3|Info|MigrationLogger|*** 139: consolidate_indexer_baseurl migrating ***
17-6-13 07:43:28.3|Info|consolidate_indexer_baseurl|Starting migration to 139
17-6-13 07:43:28.3|Error|MigrationLogger|SQL logic error or missing database
near ")": syntax error

[v0.2.0.760] System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
near ")": syntax error
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at NzbDrone.Core.Datastore.Migration.consolidate_indexer_baseurl.RenameUrlToBaseUrl(IDbConnection conn, IDbTransaction tran) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Migration\139_fix_indexer_baseurl.cs:line 26
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(PerformDBOperationExpression expression) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\Processors\SQLite\SQLiteProcessor.cs:line 113
   at FluentMigrator.Builders.Execute.PerformDBOperationExpression.ExecuteWith(IMigrationProcessor processor) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator\Builders\Execute\ExecuteExpressionRoot.cs:line 67
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass72_0.<ExecuteExpressions>b__1() in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 489
   at FluentMigrator.Runner.StopWatch.Time(Action action) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\StopWatch.cs:line 57
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 489

17-6-13 07:43:28.4|Fatal|WindowsApp|EPIC FAIL: Database file: C:\ProgramData\Radarr\nzbdrone.db is corrupt, restore from backup if available. See: https://github.com/Sonarr/Sonarr/wiki/FAQ#i-am-getting-an-error-database-disk-image-is-malformed

[v0.2.0.760] NzbDrone.Core.Datastore.CorruptDatabaseException: Database file: C:\ProgramData\Radarr\nzbdrone.db is corrupt, restore from backup if available. See: https://github.com/Sonarr/Sonarr/wiki/FAQ#i-am-getting-an-error-database-disk-image-is-malformed ---> System.Data.SQLite.SQLiteException: SQL logic error or missing database
near ")": syntax error
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at NzbDrone.Core.Datastore.Migration.consolidate_indexer_baseurl.RenameUrlToBaseUrl(IDbConnection conn, IDbTransaction tran) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Migration\139_fix_indexer_baseurl.cs:line 26
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(PerformDBOperationExpression expression) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\Processors\SQLite\SQLiteProcessor.cs:line 113
   at FluentMigrator.Builders.Execute.PerformDBOperationExpression.ExecuteWith(IMigrationProcessor processor) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator\Builders\Execute\ExecuteExpressionRoot.cs:line 67
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass72_0.<ExecuteExpressions>b__1() in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 489
   at FluentMigrator.Runner.StopWatch.Time(Action action) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\StopWatch.cs:line 57
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 502
   at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 458
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 308
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 157
   at NzbDrone.Core.Datastore.Migration.Framework.MigrationController.Migrate(String connectionString, MigrationContext migrationContext) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Migration\Framework\MigrationController.cs:line 58
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationContext migrationContext) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\DbFactory.cs:line 84
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationContext migrationContext) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\DbFactory.cs:line 116
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationType migrationType) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\DbFactory.cs:line 56
   at NzbDrone.Core.Datastore.DbFactory.RegisterDatabase(IContainer container) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\DbFactory.cs:line 36
   at Radarr.Host.Bootstrap.Start(ApplicationModes applicationModes, StartupContext startupContext) in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:line 73
   at Radarr.Host.Bootstrap.Start(StartupContext startupContext, IUserAlert userAlert, Action`1 startCallback) in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:line 40
   at NzbDrone.WindowsApp.Main(String[] args) in C:\projects\radarr-usby1\src\NzbDrone\WindowsApp.cs:line 23

**Comment by dazedcrazy** [comment]
![dgtssze](https://user-images.githubusercontent.com/9027988/27085961-abf2bf8e-5048-11e7-9c71-55f30c7b60d3.png)
Same issue

**Comment by nate1280** [comment]
The database is actually fine, there's an extra comma in one of the migration SQL commands from the last update, causing the crash.

**Comment by galli-leo** [comment]
@nate1280 Yeah, whoops :(
@dazedcrazy @ghallford Really sorry about that, I must have added an extra comma after copying the migration from sonarr.
