### ISSUE TITLE
Radarr not starting

### ISSUE THREAD

**Issue by astlaurent** [Radarr/Radarr#1680]
**Description:**

Recently my computer restarted and since then Radarr will not startup. It is complaining about a corrupt DB. i attempted to restore it from a backup as well as just starting it without a DB. No matter what it spits out the same error. 

**Radarr Version:**
not sure but I believe i am on the dev version Windows build

**Logs:**
[Info] Bootstrap: Starting Radarr - C:\Radarr\Radarr.Console.exe - Version 0.2.0.759
[Info] MigrationLogger: *** Migrating data source=C:\ProgramData\Radarr\nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] MigrationLogger: *** 139: consolidate_indexer_baseurl migrating ***
[Info] consolidate_indexer_baseurl: Starting migration to 139
[Error] MigrationLogger: SQL logic error or missing database
near ")": syntax error

[v0.2.0.759] System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
near ")": syntax error
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at NzbDrone.Core.Datastore.Migration.consolidate_indexer_baseurl.RenameUrlToBaseUrl(IDbConnection conn, IDbTransaction tran) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Migration\139_fix_indexer_baseurl.cs:line 26
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(PerformDBOperationExpression expression) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\Processors\SQLite\SQLiteProcessor.cs:line 113
   at FluentMigrator.Builders.Execute.PerformDBOperationExpression.ExecuteWith(IMigrationProcessor processor) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator\Builders\Execute\ExecuteExpressionRoot.cs:line 67
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass72_0.<ExecuteExpressions>b__1() in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 489
   at FluentMigrator.Runner.StopWatch.Time(Action action) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\StopWatch.cs:line 57
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 489

[Fatal] ConsoleApp: EPIC FAIL!

[v0.2.0.759] NzbDrone.Core.Datastore.CorruptDatabaseException: Database file: C:\ProgramData\Radarr\nzbdrone.db is corrupt, restore from backup if available. See: https://github.com/Sonarr/Sonarr/wiki/FAQ#i-am-getting-an-error-database-disk-image-is-malformed ---> System.Data.SQLite.SQLiteException: SQL logic error or missing database
near ")": syntax error
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at NzbDrone.Core.Datastore.Migration.consolidate_indexer_baseurl.RenameUrlToBaseUrl(IDbConnection conn, IDbTransaction tran) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Migration\139_fix_indexer_baseurl.cs:line 26
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(PerformDBOperationExpression expression) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\Processors\SQLite\SQLiteProcessor.cs:line 113
   at FluentMigrator.Builders.Execute.PerformDBOperationExpression.ExecuteWith(IMigrationProcessor processor) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator\Builders\Execute\ExecuteExpressionRoot.cs:line 67
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass72_0.<ExecuteExpressions>b__1() in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 489
   at FluentMigrator.Runner.StopWatch.Time(Action action) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\StopWatch.cs:line 57
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 502
   at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 458
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 308
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 157
   at NzbDrone.Core.Datastore.Migration.Framework.MigrationController.Migrate(String connectionString, MigrationContext migrationContext) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Migration\Framework\MigrationController.cs:line 58
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationContext migrationContext) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\DbFactory.cs:line 84
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationContext migrationContext) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\DbFactory.cs:line 116
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationType migrationType) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\DbFactory.cs:line 56
   at NzbDrone.Core.Datastore.DbFactory.RegisterDatabase(IContainer container) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\DbFactory.cs:line 36
   at Radarr.Host.Bootstrap.Start(ApplicationModes applicationModes, StartupContext startupContext) in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:line 73
   at Radarr.Host.Bootstrap.Start(StartupContext startupContext, IUserAlert userAlert, Action`1 startCallback) in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:line 40
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in C:\projects\radarr-usby1\src\NzbDrone.Console\ConsoleApp.cs:line 20

Press enter to exit...

**Comment by woble** [comment]
Have you tried the latest build?

https://ci.appveyor.com/project/galli-leo/radarr-usby1/build/artifacts

**Comment by tiphae** [comment]
I'm getting the same thing, but on QNAP NAS. Radarr GUI won't load at all, even after restore/reinstall. Log states nzbdrone.db is corrupt or malformed.

Version 0.2.0.759 (QNAP) 
Logs:
17-6-13 06:18:50.5|Info|Bootstrap|Starting Radarr - /share/CACHEDEV1_DATA/.qpkg/Radarr/Radarr/Radarr.exe - Version 0.2.0.759
17-6-13 06:18:53.3|Info|MigrationLogger|*** Migrating data source=/share/CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-13 06:18:53.6|Info|MigrationLogger|*** 139: consolidate_indexer_baseurl migrating ***
17-6-13 06:18:53.6|Info|consolidate_indexer_baseurl|Starting migration to 139
17-6-13 06:18:53.6|Error|MigrationLogger|SQL logic error or missing database
near ")": syntax error

[v0.2.0.759] System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
near ")": syntax error
  at System.Data.SQLite.SQLite3.Prepare (System.Data.SQLite.SQLiteConnection cnn, System.String strSql, System.Data.SQLite.SQLiteStatement previous, System.UInt32 timeoutMS, System.String& strRemain) [0x0033c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteCommand.BuildNextCommand () [0x00068] in <61a20cde294d4a3eb43b9d9f6284613b>:0 

17-6-13 06:18:53.8|Fatal|ConsoleApp|EPIC FAIL!

[v0.2.0.759] NzbDrone.Core.Datastore.CorruptDatabaseException: Database file: /share/CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr/nzbdrone.db is corrupt, restore from backup if available. See: https://github.com/Sonarr/Sonarr/wiki/FAQ#i-am-getting-an-error-database-disk-image-is-malformed ---> System.Data.SQLite.SQLiteException: SQL logic error or missing database
near ")": syntax error
  at System.Data.SQLite.SQLite3.Prepare (System.Data.SQLite.SQLiteConnection cnn, System.String strSql, System.Data.SQLite.SQLiteStatement previous, System.UInt32 timeoutMS, System.String& strRemain) [0x0033c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteCommand.BuildNextCommand () [0x00068] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
   --- End of inner exception stack trace ---
  at NzbDrone.Core.Datastore.DbFactory.Create (NzbDrone.Core.Datastore.Migration.Framework.MigrationContext migrationContext) [0x00121] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\DbFactory.cs:116 
  at NzbDrone.Core.Datastore.DbFactory.Create (NzbDrone.Core.Datastore.Migration.Framework.MigrationType migrationType) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\DbFactory.cs:56 
  at NzbDrone.Core.Datastore.DbFactory.RegisterDatabase (NzbDrone.Common.Composition.IContainer container) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\DbFactory.cs:36 
  at Radarr.Host.Bootstrap.Start (Radarr.Host.ApplicationModes applicationModes, NzbDrone.Common.EnvironmentInfo.StartupContext startupContext) [0x0003d] in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:73 
  at Radarr.Host.Bootstrap.Start (NzbDrone.Common.EnvironmentInfo.StartupContext startupContext, Radarr.Host.IUserAlert userAlert, System.Action`1[T] startCallback) [0x00075] in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:40 
  at NzbDrone.Console.ConsoleApp.Main (System.String[] args) [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Console\ConsoleApp.cs:20 

17-6-13 21:06:29.3|Info|Bootstrap|Starting Radarr - /share/CACHEDEV1_DATA/.qpkg/Radarr/Radarr/Radarr.exe - Version 0.2.0.759
17-6-13 21:06:32.8|Info|MigrationLogger|*** Migrating data source=/share/CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-13 21:06:33.3|Info|MigrationLogger|*** 139: consolidate_indexer_baseurl migrating ***
17-6-13 21:06:33.3|Info|consolidate_indexer_baseurl|Starting migration to 139
17-6-13 21:06:33.4|Error|MigrationLogger|SQL logic error or missing database
near ")": syntax error

[v0.2.0.759] System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
near ")": syntax error
  at System.Data.SQLite.SQLite3.Prepare (System.Data.SQLite.SQLiteConnection cnn, System.String strSql, System.Data.SQLite.SQLiteStatement previous, System.UInt32 timeoutMS, System.String& strRemain) [0x0033c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteCommand.BuildNextCommand () [0x00068] in <61a20cde294d4a3eb43b9d9f6284613b>:0 

17-6-13 21:06:33.4|Fatal|ConsoleApp|EPIC FAIL!

[v0.2.0.759] NzbDrone.Core.Datastore.CorruptDatabaseException: Database file: /share/CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr/nzbdrone.db is corrupt, restore from backup if available. See: https://github.com/Sonarr/Sonarr/wiki/FAQ#i-am-getting-an-error-database-disk-image-is-malformed ---> System.Data.SQLite.SQLiteException: SQL logic error or missing database
near ")": syntax error
  at System.Data.SQLite.SQLite3.Prepare (System.Data.SQLite.SQLiteConnection cnn, System.String strSql, System.Data.SQLite.SQLiteStatement previous, System.UInt32 timeoutMS, System.String& strRemain) [0x0033c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteCommand.BuildNextCommand () [0x00068] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
   --- End of inner exception stack trace ---
  at NzbDrone.Core.Datastore.DbFactory.Create (NzbDrone.Core.Datastore.Migration.Framework.MigrationContext migrationContext) [0x00136] in <45d573de548b4d628a5af50aa0ce4599>:0 
  at NzbDrone.Core.Datastore.DbFactory.Create (NzbDrone.Core.Datastore.Migration.Framework.MigrationType migrationType) [0x00010] in <45d573de548b4d628a5af50aa0ce4599>:0 
  at NzbDrone.Core.Datastore.DbFactory.RegisterDatabase (NzbDrone.Common.Composition.IContainer container) [0x00006] in <45d573de548b4d628a5af50aa0ce4599>:0 
  at Radarr.Host.Bootstrap.Start (Radarr.Host.ApplicationModes applicationModes, NzbDrone.Common.EnvironmentInfo.StartupContext startupContext) [0x0003d] in <e756ef1bcd3d4e6695d0e1b1a27a4688>:0 
  at Radarr.Host.Bootstrap.Start (NzbDrone.Common.EnvironmentInfo.StartupContext startupContext, Radarr.Host.IUserAlert userAlert, System.Action`1[T] startCallback) [0x00075] in <e756ef1bcd3d4e6695d0e1b1a27a4688>:0 
  at NzbDrone.Console.ConsoleApp.Main (System.String[] args) [0x00013] in <ce8814e5a034441dbfda5ef7ff0ed46b>:0

**Comment by tiphae** [comment]
I reinstalled 0.2.0.226 I had laying around, and switched it from nightly to develop. It's running on 0.2.0.696 alright - seems like a problem with 0.2.0.759.

**Comment by galli-leo** [comment]
@tiphae There should be a new nightly available to fix this (At least it did for others).

**Comment by floristenhove** [comment]
Hey guys, having the same issue. How can I update to the latest nightly from the cli? Since the GUI is unavailable.
