### ISSUE TITLE
Manual Import of Film : Error occurred while executing task ManualImport: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Systemshark** [Radarr/Radarr#1701]
Attemtping to import a film from a source folder into the 'film directory'

Select file and matched using the film type.  Icon said match failed.  Pressing ok failed to import.

**Radarr Version:0.2.0.696

**Logs:**
System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Qualities.QualityModelComparer.Compare(QualityModel left, QualityModel right) in C:\projects\radarr-usby1\src\NzbDrone.Core\Qualities\QualityModelComparer.cs:line 29
   at System.Linq.EnumerableSorter`2.CompareKeys(Int32 index1, Int32 index2)
   at System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:line 52
   at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.Execute(ManualImportCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\Manual\ManualImportService.cs:line 296
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41

**Comment by galli-leo** [comment]
What is the file named like?
