### ISSUE TITLE
File path issues with Completed Download Handling

### ISSUE THREAD

**Issue by evakq8r** [Radarr/Radarr#1702]
Hi,

In the last week or so, Radarr (as well as Sonarr) have both been adding an additional folder to the file path that I have not input.

In short, my remote file mapping file path is: C:\Syncthing\Sync\Sync - SB_2\radarr, however when CDH tries to process the file, it errors out for: 

>No files found are eligible for import in C:\Syncthing\Sync\Sync - SB_2\radarr\radarr\<insert random file here>

I do not have Drone Factory running (it was temporarily enabled to import files that were being stubborn, but this has been disabled). The remote file mapping does not have any duplicates listed, and when I try to add the second /radarr file path, Radarr indicates: 

>Request Failed: RemotePath already mounted.

>System.InvalidOperationException: RemotePath already mounted.
   at NzbDrone.Core.RemotePathMappings.RemotePathMappingService.ValidateMapping(List`1 existing, RemotePathMapping mapping) in C:\projects\radarr-usby1\src\NzbDrone.Core\RemotePathMappings\RemotePathMappingService.cs:line 119
   at NzbDrone.Core.RemotePathMappings.RemotePathMappingService.Add(RemotePathMapping mapping) in C:\projects\radarr-usby1\src\NzbDrone.Core\RemotePathMappings\RemotePathMappingService.cs:line 58
   at NzbDrone.Api.RemotePathMappings.RemotePathMappingModule.CreateMapping(RemotePathMappingResource resource) in C:\projects\radarr-usby1\src\NzbDrone.Api\RemotePathMappings\RemotePathMappingModule.cs:line 47
   at NzbDrone.Api.REST.RestModule`1.<set_CreateResource>b__41_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 161
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Radarr Version:** Radarr Ver. 0.2.0.696

I'm not sure whether this is a bug or I'm just doing something daft (again), but given it seems to be happening on both Sonarr and Radarr and started around the same time..... I'm at a loss.

Any ideas?

**Comment by galli-leo** [comment]
What download client are you using? (Pretty sure it's due to the dl client) Did you report the issue over on Sonarr as well?

**Comment by evakq8r** [comment]
SABnzbd for .nzbs, rtorrent via seedbox for torrents.

**Comment by galli-leo** [comment]
Ah, are you using remote path mappings?

**Comment by evakq8r** [comment]
Yes; both SABnzbd and rtorrent are based on my seedbox (this setup has been working fine for several months, only just started acting up).

**Comment by galli-leo** [comment]
IIRC we (and Sonarr) started adding the label (in this case radarr) to download paths ourselves. So to resolve this, remove the \radarr from the path mapping.

**Comment by evakq8r** [comment]
Can confirm, this appears to be doing the trick. Thanks again @galli-leo 

As a side note, was this change recent and noted in the change logs at all? Or was I just oblivious?

**Comment by galli-leo** [comment]
I don't recall. Maybe I forgot it in the changelog.
