### ISSUE TITLE
Jackett torrent result found and accepted, but search display fails "No results found"

### ISSUE THREAD

**Issue by lolmancgn** [Radarr/Radarr#1752]
**Description:**

While using Jackett to search a private indexer for torrent releases, the search fails and displays `No results found` in the UI, even though the trace says a release was found and accepted. This search and others work fine from the Jackett interface. I have other usenet and torrent resources configured and those spout out results amazingly well, but if I enable this particular torznab resource, every search fails. I'm having a hard time reading the log and understanding the `System.ArgumentException: The string can't be left empty, null or consist of only whitespaces.
Parameter name: key` line and the ones that follow.

**Radarr Version:**

Radarr Ver. 0.2.0.778, branch `develop`

**Logs:**

```
Info|NzbSearchService|Searching 1 indexers for [Blade Runner]
Debug|Torznab|Downloading Feed http://redacted/torznab/redacted/api?t=movie&cat=2000&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=0083658
Debug|NzbSearchService|Total of 1 reports were found for [Blade Runner] from 1 indexers
Info|DownloadDecisionMaker|Processing 1 releases
Debug|Parser|Parsing string 'Blade.Runner.Final.Cut.1982.German.DL.AC3.1080p.BluRay.VC-1.Remux-redacted'
Debug|Parser|Movie Parsed. Blade Runner - 1982 
Debug|Parser|Language parsed: German
Debug|QualityParser|Trying to parse quality for Blade.Runner.Final.Cut.1982.German.DL.AC3.1080p.BluRay.VC-1.Remux-redacted
Debug|Parser|Quality parsed: Remux-1080p v1
Debug|Parser|Release Group parsed: redacted
Debug|AcceptableSizeSpecification|Beginning size check for: Blade.Runner.Final.Cut.1982.German.DL.AC3.1080p.BluRay.VC-1.Remux-redacted
Debug|AcceptableSizeSpecification|Max size is unlimited - skipping check.
Debug|AcceptableSizeSpecification|Item: Blade.Runner.Final.Cut.1982.German.DL.AC3.1080p.BluRay.VC-1.Remux-redacted, meets size constraints.
Debug|LanguageSpecification|Checking if report meets language requirements. German
Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: Blade.Runner.Final.Cut.1982.German.DL.AC3.1080p.BluRay.VC-1.Remux-redacted
Debug|ReleaseRestrictionsSpecification|[Blade.Runner.Final.Cut.1982.German.DL.AC3.1080p.BluRay.VC-1.Remux-redacted] No restrictions apply, allowing
Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. Remux-1080p v1
Debug|MinimumAgeSpecification|Not checking minimum age requirement for non-usenet report
Debug|RetentionSpecification|Not checking retention requirement for non-usenet report
Debug|SeriesSpecification|Checking if movie matches searched movie
Debug|DelaySpecification|Ignoring delay for user invoked search
Debug|HistorySpecification|Skipping history check during search
Debug|MonitoredEpisodeSpecification|Skipping monitored check during search
Debug|AvailabilitySpecification|Skipping availability check during search
Debug|DownloadDecisionMaker|Release accepted
Warn|ArgumentValidator|The string can't be left empty, null or consist of only whitespaces.
Error|ReleaseModule|Movie search failed: The string can't be left empty, null or consist of only whitespaces.
Parameter name: key

[v0.2.0.778] System.ArgumentException: The string can't be left empty, null or consist of only whitespaces.
Parameter name: key
  at NzbDrone.Common.EnsureThat.EnsureStringExtensions.IsNotNullOrWhiteSpace (NzbDrone.Common.EnsureThat.Param`1[T] param) [0x0001e] in C:\projects\radarr-usby1\src\NzbDrone.Common\EnsureThat\EnsureStringExtensions.cs:18 
  at NzbDrone.Common.Cache.Cached`1[T].Set (System.String key, T value, System.Nullable`1[T] lifetime) [0x0000d] in C:\projects\radarr-usby1\src\NzbDrone.Common\Cache\Cached.cs:41 
  at NzbDrone.Api.Indexers.ReleaseModule.MapDecision (NzbDrone.Core.DecisionEngine.DownloadDecision decision, System.Int32 initialWeight) [0x00008] in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:165 
  at NzbDrone.Api.Indexers.ReleaseModuleBase.MapDecisions (System.Collections.Generic.IEnumerable`1[T] decisions) [0x00016] in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModuleBase.cs:14 
  at NzbDrone.Api.Indexers.ReleaseModule.GetMovieReleases (System.Int32 movieId) [0x0001b] in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:138 

Debug|Api|[GET] /api/release?movieId=25&sort_by=releaseWeight&order=asc: 200.OK (231 ms)
Debug|Api|[GET] /api/log/file: 200.OK (4 ms)
Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (2 ms)
```

Would be great to get some help on this :) Much appreciated.

Also referenced this here with a bit more info on how the Jackett definition is written: 
https://github.com/Jackett/Jackett/issues/1513

**Comment by lolmancgn** [comment]
Closing this. The YML definition was missing a key part, the details field:

```
details:
        selector: td.title_col .torrent_title_div a.torrent_link_title
        attribute: href
```

without this, Jackett was unable to provide a GUID to Sonarr/Jackett

**Comment by seanvree** [comment]
I've been seeing a lot of these errors recently as well.  Using jackett and Nzbhydra. 

OS:  Windows 10E 1709 x64

Radarr Ver. 0.2.0.900 nightly

```
Movie search failed: The string can't be left empty, null or consist of only whitespaces.
Parameter name: key: The string can't be left empty, null or consist of only whitespaces.
Parameter name: key

System.ArgumentException: The string can't be left empty, null or consist of only whitespaces.
Parameter name: key
   at NzbDrone.Common.EnsureThat.EnsureStringExtensions.IsNotNullOrWhiteSpace(Param`1 param) in C:\projects\radarr-usby1\src\NzbDrone.Common\EnsureThat\EnsureStringExtensions.cs:line 16
   at NzbDrone.Common.Cache.Cached`1.Set(String key, T value, Nullable`1 lifetime) in C:\projects\radarr-usby1\src\NzbDrone.Common\Cache\Cached.cs:line 41
   at NzbDrone.Api.Indexers.ReleaseModule.MapDecision(DownloadDecision decision, Int32 initialWeight) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 165
   at NzbDrone.Api.Indexers.ReleaseModuleBase.MapDecisions(IEnumerable`1 decisions) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModuleBase.cs:line 12
   at NzbDrone.Api.Indexers.ReleaseModule.GetMovieReleases(Int32 movieId) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 138
```
