### ISSUE TITLE
Refreshing movie failed

### ISSUE THREAD

**Issue by XmemphistoX** [Radarr/Radarr#176]
I was in process of adding my library in when maybe I noticed half of them had the status of missing.  If I refreshed a few, it updated with downloaded.

A bunch are failing the refresh and checking the logs I am getting the following.

```
Error occurred while executing task RefreshMovie: constraint failed
UNIQUE constraint failed: Movies.ImdbId


System.Data.SQLite.SQLiteException (0x80004005): constraint failed
UNIQUE constraint failed: Movies.ImdbId
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at Marr.Data.QGen.UpdateQueryBuilder`1.Execute() in C:\projects\radarr-usby1\src\Marr.Data\QGen\UpdateQueryBuilder.cs:line 156
   at Marr.Data.DataMapper.Update[T](T entity, Expression`1 filter) in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:line 674
   at NzbDrone.Core.Datastore.BasicRepository`1.Update(TModel model) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 120
   at NzbDrone.Core.Tv.MovieService.UpdateMovie(Movie movie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:line 163
   at NzbDrone.Core.Tv.RefreshMovieService.RefreshMovieInfo(Movie movie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\RefreshMovieService.cs:line 98
   at NzbDrone.Core.Tv.RefreshMovieService.Execute(RefreshMovieCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\RefreshMovieService.cs:line 111
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41
```

**Comment by onedr0p** [comment]
looks like your maybe trying to add the same movie twice?

**Comment by evilspectre** [comment]
Getting the same issue. I believe it is because TMDB has the imdb_id field, but that field is blank. Example Movie is https://www.themoviedb.org/movie/428460-alan-davies-little-victories

**Comment by galli-leo** [comment]
@evilspectre This movie works fine for me. Try the latest release?

**Comment by evilspectre** [comment]
Running on latest. Add 2 movies without IMDb id to get the issue on the second one. Here is another without IMDb id.
https://www.themoviedb.org/movie/408629-branching-paths

**Comment by galli-leo** [comment]
@evilspectre Also works fine for me. Since when are you using Radarr?

**Comment by evilspectre** [comment]
Just started this week. Do both show downloaded as status? Only one with blank IMDb id seems to be allowed. One says downloaded, Other says missing, when refreshing movie error above happens.

**Comment by XmemphistoX** [comment]
Mine specifically is this one as well as a bunch of other UFC titles.
https://www.themoviedb.org/movie/375876-ufc-1-the-beginning

**Comment by galli-leo** [comment]
@evilspectre @XmemphistoX Can you back up your database, delete it and try again?

**Comment by evilspectre** [comment]
Removed DB, same issue. 
Imported just the 2 following movies. 
https://www.themoviedb.org/movie/428460-alan-davies-little-victories and https://www.themoviedb.org/movie/408629-branching-paths 
First one I added shows status of Downloaded, second shows missing, try to scan disk and get error above.
If you set IX_Movies_ImdbId Index in the Movie table in the DB to not require unique fields, it works fine.
Not sure what that would do to rest of application, but it is a way to fix it.

**Comment by galli-leo** [comment]
@evilspectre Seems like I messed up the DB migration. Will have to take a look at that.

**Comment by XmemphistoX** [comment]
Wanted to say this is now fixed I believe.  TY!

**Comment by galli-leo** [comment]
Fixed on latest nightly.
