### ISSUE TITLE
UNC paths not working

### ISSUE THREAD

**Issue by mattg1000** [Radarr/Radarr#179]
When I try to add a UNC path to import existing movies on disk, I get an error that says Path does not exist.

![image](https://cloud.githubusercontent.com/assets/1860530/21872059/d8498756-d82b-11e6-9e54-cba8331888f9.png)

The same path works on Sonarr on the same box.

![image](https://cloud.githubusercontent.com/assets/1860530/21872180/b2746cde-d82c-11e6-8e4d-fda3760ae204.png)

This is the text in the log:
```
17-1-11 18:14:53.4|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.1.0.34618] System.ArgumentException: The UNC path should be of the form \\server\share.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at System.IO.FileInfo..ctor(String fileName)
   at NzbDrone.Common.Extensions.PathExtensions.CleanFilePath(String path)
   at NzbDrone.Common.Extensions.PathExtensions.PathEquals(String firstPath, String secondPath, Nullable`1 comparison)
   at NzbDrone.Core.Validation.Paths.DroneFactoryValidator.IsValid(PropertyValidatorContext context)
   at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context)
   at FluentValidation.Internal.PropertyRule.InvokePropertyValidator(ValidationContext context, IPropertyValidator validator, String propertyName)
   at FluentValidation.Internal.PropertyRule.<Validate>d__60.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context)
   at FluentValidation.AbstractValidator`1.Validate(T instance)
   at NzbDrone.Api.REST.RestModule`1.ReadResourceFromRequest(Boolean skipValidate)
   at NzbDrone.Api.REST.RestModule`1.<set_CreateResource>m__5(Object options)
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

17-1-11 18:15:08.9|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Path does not exist
```

**Comment by mattg1000** [comment]
I figured it out.  Had to run the Radarr service as the account that has login creds to the UNC path.  Carry on...
