### ISSUE TITLE
Had an issue with NZB.IS for last couple days...

### ISSUE THREAD

**Issue by gregcbrown** [Radarr/Radarr#1813]
17-7-18 09:37:17.0|Warn|HttpClient|HTTP Error - Res: [GET] https://nzb.is/getnzb/3a50960b3777ff8b3f950d1545ff80c5ba385958.nzb&i=2069&r=90dc52824d4d4d84a461ee433b463c2e: 404.NotFound
17-7-18 09:37:17.0|Error|Sabnzbd|Downloading nzb for episode 'Spiderman.Homecoming.2017.720p.HD.Rip.XViD-LMO' failed (https://nzb.is/getnzb/3a50960b3777ff8b3f950d1545ff80c5ba385958.nzb&i=2069&r=90dc52824d4d4d84a461ee433b463c2e)

[v0.2.0.778] NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [https://nzb.is/getnzb/3a50960b3777ff8b3f950d1545ff80c5ba385958.nzb&i=2069&r=90dc52824d4d4d84a461ee433b463c2e]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 99
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 186
   at NzbDrone.Core.Download.UsenetClientBase`1.Download(RemoteMovie remoteEpisode) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\UsenetClientBase.cs:line 83

				<html>
					<head>
						<title>404 - File not found.</title>
					</head>
					<body>
						<h1>404 - File not found.</h1>
						<p>https://nzb.is/getnzb</p>
						<p>We could not find the above page on our servers.</p>
					</body>
				</html>

17-7-18 09:37:17.0|Warn|ProcessDownloadDecisions|Couldn't add report to download queue. Spiderman.Homecoming.2017.720p.HD.Rip.XViD-LMO

[v0.2.0.778] NzbDrone.Core.Exceptions.ReleaseDownloadException: Downloading nzb failed ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [https://nzb.is/getnzb/3a50960b3777ff8b3f950d1545ff80c5ba385958.nzb&i=2069&r=90dc52824d4d4d84a461ee433b463c2e]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 99
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 186
   at NzbDrone.Core.Download.UsenetClientBase`1.Download(RemoteMovie remoteEpisode) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\UsenetClientBase.cs:line 83
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.UsenetClientBase`1.Download(RemoteMovie remoteEpisode) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\UsenetClientBase.cs:line 98
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\DownloadService.cs:line 137
   at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions(List`1 decisions) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:line 91

**Comment by gregcbrown** [comment]
BTW I tested the indexer and it passed...

**Comment by hotio** [comment]
I created an account just to test, added the info to Radarr, did a manual search and a RSS sync...In both instances I received no errors and manual search showed results as expected.
Grabbing an nzb works OK too.

Are you sure you are not over your API limits?

**Comment by gregcbrown** [comment]
It appears to have resolved itself...
