### ISSUE TITLE
Unexpected character encountered while parsing value: O. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by MrMcGyver** [Radarr/Radarr#1842]
After upgrading to the latest qBitorrent (3.3.14), Radarr (0.2.0.778) no longer assigns request to a category within qBitorrent. Had a very similar issue with Sonarr which was resolved by updating to the latest developer version. Issue is noted here:

https://forums.sonarr.tv/t/qbittorrent-nzbdroneerrorpipeline/15402

17-7-28 14:19:27.2|Info|NzbSearchService|Searching 5 indexers for [Drone]
17-7-28 14:19:33.8|Info|DownloadDecisionMaker|Processing 76 releases
17-7-28 14:19:54.0|Info|NetImportSearchService|No lists are enabled for auto-import.
17-7-28 14:19:58.0|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.778] Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: O. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in C:\projects\radarr-usby1\src\NzbDrone.Common\Serializer\Json.cs:line 37
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest[TResult](HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 184
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.AddTorrentFromUrl(String torrentUrl, QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 75
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.AddFromMagnetLink(RemoteMovie remoteMovie, String hash, String magnetLink) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 46
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromMagnetUrl(RemoteMovie remoteEpisode, String magnetUrl) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 301
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteMovie remoteMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 110
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\DownloadService.cs:line 119
   at NzbDrone.Api.Indexers.ReleaseModule.DownloadRelease(ReleaseResource release) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 73
   at NzbDrone.Api.Indexers.ReleaseModule.<.ctor>b__8_0(Object x) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 47
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by Stolla** [comment]
Sonarr had the same issue but it's now resolved.

**Comment by jamesmacwhite** [comment]
Upstream change:

https://github.com/qbittorrent/qBittorrent/commit/7cf1d844b05a275a51472fc93de3ce33aa750f0b

Fix in Sonarr:

https://github.com/Sonarr/Sonarr/commit/126b849c270391f912d7ce3d125fd7fbdc82268c

**Comment by galli-leo** [comment]
Fixed in latest nightly.
