### ISSUE TITLE
Odd error message when pressing download after searching

### ISSUE THREAD

**Issue by mrangryoven** [Radarr/Radarr#1883]
**Description:**
I am getting this error message 
```
[v0.2.0.778] Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: O. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in C:\projects\radarr-usby1\src\NzbDrone.Common\Serializer\Json.cs:line 37
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest[TResult](HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 184
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.AddTorrentFromUrl(String torrentUrl, QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 75
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.AddFromMagnetLink(RemoteMovie remoteMovie, String hash, String magnetLink) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 46
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromMagnetUrl(RemoteMovie remoteEpisode, String magnetUrl) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 301
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteMovie remoteMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 110
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\DownloadService.cs:line 119
   at NzbDrone.Api.Indexers.ReleaseModule.DownloadRelease(ReleaseResource release) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 73
   at NzbDrone.Api.Indexers.ReleaseModule.<.ctor>b__8_0(Object x) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 47
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

The cloud icon goes red and shows this in a pop up bubble.

HOWEVER: It does add it to the download client, but as radarr belives it fails its adding multiple different releases into my download queue. Just had to remove over 40 downloads of the same film?

**Radarr Version:** 0.2.0.778

**Logs:**
https://drive.google.com/open?id=0BzQu-a3rNxZDUlJQdmx6RnlreGc

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
This is fixed on the latest nightly.
