### ISSUE TITLE
SQL Logic Error with nightly build 0.2.0.812

### ISSUE THREAD

**Issue by ChrisDurham** [Radarr/Radarr#1900]
When trying to Organize files I get the following error after updating to latest nightly build

[v0.2.0.812] System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
ambiguous column name: Id
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Marr.Data.DataMapper.QueryToGraph[T](String sql, EntityGraph graph, List`1 childrenToLoad) in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:line 624
   at Marr.Data.QGen.QueryBuilder`1.ToList() in C:\projects\radarr-usby1\src\Marr.Data\QGen\QueryBuilder.cs:line 275
   at Marr.Data.QGen.SortBuilder`1.ToList() in C:\projects\radarr-usby1\src\Marr.Data\QGen\SortBuilder.cs:line 176
   at NzbDrone.Core.Datastore.BasicRepository`1.Get(IEnumerable`1 ids) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 85
   at NzbDrone.Core.Tv.MovieService.GetMovies(IEnumerable`1 movieIds) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:line 147
   at NzbDrone.Core.MediaFiles.RenameMovieFileService.Execute(RenameMovieCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\RenameMovieFileService.cs:line 187
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41

**Comment by galli-leo** [comment]
Fixed in latest nightly.

**Comment by ChrisDurham** [comment]
Still not working in nightly build 814

**Comment by galli-leo** [comment]
Exact same log?

**Comment by ChrisDurham** [comment]
Yes. Same error as soon as i click to organise the movies. I updated to latest nightly version. 


Sent from Samsung Mobile on O2
-------- Original message --------From: Leonardo Galli <notifications@github.com> Date: 11/08/2017  17:40  (GMT+00:00) To: Radarr/Radarr <Radarr@noreply.github.com> Cc: ChrisDurham <chris.durham@latticeconcepts.co.uk>, Author <author@noreply.github.com> Subject: Re: [Radarr/Radarr] SQL Logic Error with nightly build 0.2.0.812 (#1900) 
Exact same log?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Radarr/Radarr","title":"Radarr/Radarr","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Radarr/Radarr"}},"updates":{"snippets":[{"icon":"PERSON","message":"@galli-leo in #1900: Exact same log?"}],"action":{"name":"View Issue","url":"https://github.com/Radarr/Radarr/issues/1900#issuecomment-321861340"}}}
