### ISSUE TITLE
Unable to add Newznab provider

### ISSUE THREAD

**Issue by smidley** [Radarr/Radarr#196]
I'm unable to add PFM as a newznab provider.  Testing connectivity fails as well as saving the indexer.  I think a baked in path is referenced since I don't have a C:\projects path.

Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details

Unable to connect to indexer: Sequence contains no elements
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 322

**Comment by onedr0p** [comment]
Duplicate, Please read #4
