### ISSUE TITLE
Unexpected character encountered while parsing value: O. Path '', line 0, position 0

### ISSUE THREAD

**Issue by thisgeekza** [Radarr/Radarr#1964]
**Description:**
This error occurs when selecting a torrent for download. This happens even when a torrent is selected with automatic search. The torrent still goes through to the qbittorrent download client despite the error, but Radarr does not track it and will select an alternate download (if done automatically).

I am using Jackett public for the torrent indexers. Same indexers are being used for Sonarr with no issues.

**Radarr Version:**
v0.2.0.778

**Logs:**
```
17-8-19 12:55:34.0|Info|NzbSearchService|Searching 9 indexers for [-REDACTED-]
17-8-19 12:56:07.6|Info|DownloadDecisionMaker|Processing 220 releases
17-8-19 12:58:11.3|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.778] Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: O. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in C:\projects\radarr-usby1\src\NzbDrone.Common\Serializer\Json.cs:line 37
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest[TResult](HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 184
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.AddTorrentFromUrl(String torrentUrl, QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 75
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.AddFromMagnetLink(RemoteMovie remoteMovie, String hash, String magnetLink) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 46
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromMagnetUrl(RemoteMovie remoteEpisode, String magnetUrl) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 301
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteMovie remoteMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 110
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\DownloadService.cs:line 119
   at NzbDrone.Api.Indexers.ReleaseModule.DownloadRelease(ReleaseResource release) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 73
   at NzbDrone.Api.Indexers.ReleaseModule.<.ctor>b__8_0(Object x) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 47
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

**Comment by galli-leo** [comment]
This is fixed on the latest nightly.
