### ISSUE TITLE
Can't search for new movies to add (Request limit exceeded)

### ISSUE THREAD

**Issue by Quiksmage** [Radarr/Radarr#2017]
Whenever, I attempt to add a movie by searching, I'm getting the error 

"There Was An Error Searching For 'Frozen'.
If the movie title contains non-alphanumeric characters try removing them, otherwise try your search again later."

Looking in the logs, I get the following.
```
17-8-29 16:23:57.5|Debug|Api|[GET] /api/rootfolder: 200.OK (984 ms)
17-8-29 16:24:04.4|Trace|Http|Req: 228 [GET] /api/movies/lookup?term=frozen
17-8-29 16:24:04.4|Debug|Parser|Parsing string 'frozen'
17-8-29 16:24:04.4|Debug|Parser|Unable to parse frozen
17-8-29 16:24:04.4|Trace|HttpClient|Req: [GET] https://api.themoviedb.org/3/search/movie?api_key=1a7373301961d03f97f853a876dd1212&query=frozen&year=&include_adult=False
17-8-29 16:24:04.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-8-29 16:24:04.8|Trace|HttpClient|Res: [GET] https://api.themoviedb.org/3/search/movie?api_key=1a7373301961d03f97f853a876dd1212&query=frozen&year=&include_adult=False: 429.429
{"status_code":25,"status_message":"Your request count (1559) is over the allowed limit of 40."}
 (342 ms)
17-8-29 16:24:04.8|Trace|NzbDroneErrorPipeline|Handling Exception
17-8-29 16:24:04.8|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.846] System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 504
   at NzbDrone.Api.Movie.MovieLookupModule.Search() in C:\projects\radarr-usby1\src\NzbDrone.Api\Series\MovieLookupModule.cs:line 48
   at NzbDrone.Api.Movie.MovieLookupModule.<.ctor>b__2_0(Object x) in C:\projects\radarr-usby1\src\NzbDrone.Api\Series\MovieLookupModule.cs:line 22
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

17-8-29 16:24:04.8|Trace|Http|Res: 228 [GET] /api/movies/lookup?term=frozen: 500.InternalServerError (353 ms)
17-8-29 16:24:04.8|Debug|Api|[GET] /api/movies/lookup?term=frozen: 500.InternalServerError (353 ms)
```

"{"status_code":25,"status_message":"Your request count (1559) is over the allowed limit of 40."}"

What's causing all these api requests? I did add a movie successfully earlier today.

**Comment by Quiksmage** [comment]
http://i.imgur.com/YDIpLIP.jpg

It looks like everything refreshed? What could have triggered this?

**Comment by Logvin** [comment]
I'm having this exact same issue.

**Comment by Quiksmage** [comment]
I left it alone for a while and did periodic checks to see where my api limit was at. About 3 hours ago I was 100 over the api limit (~140)

now, I'm back to 700, so something is still hammering it.
Are these apikeys unique to each installation?

```
17-8-29 21:40:18.7|Trace|Http|Req: 1188 [GET] /api/movies/lookup?term=frozen
17-8-29 21:40:18.7|Debug|Parser|Parsing string 'frozen'
17-8-29 21:40:18.7|Debug|Parser|Unable to parse frozen
17-8-29 21:40:18.7|Trace|HttpClient|Req: [GET] https://api.themoviedb.org/3/search/movie?api_key=1a7373301961d03f97f853a876dd1212&query=frozen&year=&include_adult=False
17-8-29 21:40:18.7|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-8-29 21:40:19.1|Trace|HttpClient|Res: [GET] https://api.themoviedb.org/3/search/movie?api_key=1a7373301961d03f97f853a876dd1212&query=frozen&year=&include_adult=False: 429.429
{"status_code":25,"status_message":"Your request count (770) is over the allowed limit of 40."}
 (421 ms)
17-8-29 21:40:19.1|Trace|NzbDroneErrorPipeline|Handling Exception
17-8-29 21:40:19.1|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.846] System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 504
   at NzbDrone.Api.Movie.MovieLookupModule.Search() in C:\projects\radarr-usby1\src\NzbDrone.Api\Series\MovieLookupModule.cs:line 48
   at NzbDrone.Api.Movie.MovieLookupModule.<.ctor>b__2_0(Object x) in C:\projects\radarr-usby1\src\NzbDrone.Api\Series\MovieLookupModule.cs:line 22
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

17-8-29 21:40:19.2|Trace|Http|Res: 1188 [GET] /api/movies/lookup?term=frozen: 500.InternalServerError (453 ms)
17-8-29 21:40:19.2|Debug|Api|[GET] /api/movies/lookup?term=frozen: 500.InternalServerError (453 ms)
```

**Comment by galli-leo** [comment]
Seems like it's an error on TMDB's side: https://www.themoviedb.org/talk/59a5de3ac3a3684005013b59

**Comment by Quiksmage** [comment]
I can confirm that everything is working for me now. Looking at that
thread, they made some ipv6 changes causing people to share the api hits.
They reverted this change and all appears to be well. Sorry for the
confusion and thanks for finding that source on this!
