### ISSUE TITLE
Unable to set date of file [\\path\movie.mkv]: Access to the path '\\path\movie.mkv' is denied.

### ISSUE THREAD

**Issue by ounrequitedo** [Radarr/Radarr#2038]
The movie renamed properly, but the date can't be set. Why is this?

**Radarr Version:** 0.2.0.846

**Logs:**
17-9-5 01:35:03.3|Info|MovieService|Linking [movie.mkv] > [[tt0000000][Redated Movie (2017)]]
17-9-5 01:35:03.3|Info|DiskScanService|Completed scanning disk for Redated Movie
17-9-5 01:35:03.3|Warn|UpdateMovieFileService|Unable to set date of file [\\path\movie.mkv]

[v0.2.0.846] System.UnauthorizedAccessException: Access to the path '\\path\movie.mkv' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at NzbDrone.Common.Disk.DiskProviderBase.FileSetLastWriteTime(String path, DateTime dateTime) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 285
   at NzbDrone.Core.MediaFiles.UpdateMovieFileService.ChangeFileDate(String filePath, DateTime date) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\UpdateMovieFileService.cs:line 88

17-9-5 01:35:13.7|Info|RenameMovieFileService|Renaming 1 files for Redated Movie
17-9-5 01:35:13.7|Warn|UpdateMovieFileService|Unable to set date of file [\\path\movie.mkv]

[v0.2.0.846] System.UnauthorizedAccessException: Access to the path '\\path\movie.mkv' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at NzbDrone.Common.Disk.DiskProviderBase.FileSetLastWriteTime(String path, DateTime dateTime) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 285
   at NzbDrone.Core.MediaFiles.UpdateMovieFileService.ChangeFileDate(String filePath, DateTime date) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\UpdateMovieFileService.cs:line 88

17-9-5 01:35:13.7|Warn|MovieFileMovingService|Unable to set last write time

[v0.2.0.846] System.IO.IOException: The process cannot access the file '\\path' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.OpenHandle(String path)
   at System.IO.Directory.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at NzbDrone.Common.Disk.DiskProviderBase.FolderSetLastWriteTime(String path, DateTime dateTime) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 278
   at NzbDrone.Core.MediaFiles.MediaFileAttributeService.SetFolderLastWriteTime(String path, DateTime time) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MediaFileAttributeService.cs:line 75
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 137

17-9-5 01:35:13.7|Info|RenameMovieFileService|Selected movie files renamed for Redated Movie

**Comment by ounrequitedo** [comment]
Note, this is only with existing files being imported. I just tried redownloading the entire movie passed through sabnzbd, and the date was set correctly.
