### ISSUE TITLE
Update tab doesn't load since last version

### ISSUE THREAD

**Issue by jsebtessier** [Radarr/Radarr#2157]
**Description:**
Update tab doesn't load since last version

**Radarr Version:** 0.2.0.870

**OS:** Windows 10 Pro v1703

```
Request Failed: Sequence contains more than one matching element

System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Api.Update.UpdateModule.GetRecentUpdates() in C:\projects\radarr-usby1\src\NzbDrone.Api\Update\UpdateModule.cs:line 34
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourceAll>b__32_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 111
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

**Comment by webbson** [comment]
+1 on Windows Server 2012 R2

**Comment by jasonla** [comment]
I'm getting the same error.

**Comment by gpvelzen** [comment]
+1 on Qnap QTS 4.3

**Comment by Groofster** [comment]
+1 on Linuxserver.io docker installation

**Comment by develguebil** [comment]
+1 on Ubuntu 16.04 running on Dell Server

**Comment by BernCarney** [comment]
+1 on FreeNAS/BSD 11.0

**Comment by jermo5** [comment]
+1 on Mac mini (Mid-2011) running macOs Sierra 10.12.6

**Comment by galli-leo** [comment]
This is a server side issue, so closing this. If you want, you can open one over at the RadarrAPI.Update page, but this should be fixed soon anyways.

**Comment by nemchik** [comment]
@galli-leo does the automatic updating still work? Ex: When this issue is fixed, will Radarr still update on its own? (Sorry for my lack of understanding on this issue)

**Comment by jamesmacwhite** [comment]
@nemchik At the moment the update tab won't load properly due to the return by the update API.

It looks like the API is returning more than one result when queried and this is causing the page to 500 error. Its server side, so nothing can be done on the user side at this point. Once its resolved, the updater should be fine.

**Comment by silentmiles** [comment]
I found this response a bit confusing, as I assumed you were referring to the Radarr server running locally, instead of the Update API referenced here: https://status.radarr.video/

**Comment by galli-leo** [comment]
Yeah sorry I responded on a phone and just closed a lot of similar issues 😬

**Comment by Darkknight33** [comment]
After updating to the latest 0.2.0.935 build using Linuxserver.io's docker, I am experiencing this issue.

System.InvalidOperationException: Sequence contains more than one matching element
at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable1[T] source, System.Func2[T,TResult] predicate) [0x0004a] in :0
at NzbDrone.Api.Update.UpdateModule.GetRecentUpdates () [0x00064] in C:\projects\radarr-usby1\src\NzbDrone.Api\Update\UpdateModule.cs:34
at NzbDrone.Api.REST.RestModule1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:111 at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func2<object, object>,object)
at Nancy.Routing.Route+<>c__DisplayClass4.b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0

**Comment by galli-leo** [comment]
Yeah I know update server is being wonky again
