### ISSUE TITLE
Request Failed: Sequence contains more than one matching element

### ISSUE THREAD

**Issue by gregcbrown** [Radarr/Radarr#2159]
Receiving the following error when clicking on "Updates" Tab. 
Radarr Ver. 0.2.0.870

Request Failed: Sequence contains more than one matching element

System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Api.Update.UpdateModule.GetRecentUpdates() in C:\projects\radarr-usby1\src\NzbDrone.Api\Update\UpdateModule.cs:line 34
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourceAll>b__32_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 111
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by jamesmacwhite** [comment]
Thanks, being tracked here

https://github.com/Radarr/Radarr/issues/2157

**Comment by Darkknight33** [comment]
After updating to the latest 0.2.0.935 build using Linuxserver.io's docker, I am experiencing this issue.


System.InvalidOperationException: Sequence contains more than one matching element
  at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0004a] in <b0fca80f08474611b248e2d30bb75230>:0 
  at NzbDrone.Api.Update.UpdateModule.GetRecentUpdates () [0x00064] in C:\projects\radarr-usby1\src\NzbDrone.Api\Update\UpdateModule.cs:34 
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:111 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0
