### ISSUE TITLE
After update to 0.2.0.870 update page unavailable

### ISSUE THREAD

**Issue by kretipleti** [Radarr/Radarr#2168]
After I updated Radarr to 0.2.0.870, going to System->Updates results in an endless loop of the dots going left to right without any result presented.
![dots](https://user-images.githubusercontent.com/32747770/31512685-243c534a-af8c-11e7-8cd9-3299a25a3721.jpeg)

**Comment by pellz0r** [comment]
I just noticed this as well.

**Comment by pellz0r** [comment]
And this is what I can find in the logs:

17-10-12 21:35:28.2|Trace|Http|Req: 1412 [GET] /api/update
17-10-12 21:35:28.2|Trace|HttpClient|Req: [GET] http://radarr.aeonlucid.com/v1/update/develop/changes?version=0.2.0.870&os=windows
17-10-12 21:35:28.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-10-12 21:35:28.3|Trace|HttpClient|Res: [GET] http://radarr.aeonlucid.com/v1/update/develop/changes?version=0.2.0.870&os=windows: 200.OK (97 ms)
17-10-12 21:35:28.3|Trace|NzbDroneErrorPipeline|Handling Exception
17-10-12 21:35:28.3|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.870] System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Api.Update.UpdateModule.GetRecentUpdates() in C:\projects\radarr-usby1\src\NzbDrone.Api\Update\UpdateModule.cs:line 34
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourceAll>b__32_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 111
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

17-10-12 21:35:28.4|Trace|Http|Res: 1412 [GET] /api/update: 500.InternalServerError (125 ms)
17-10-12 21:35:28.4|Debug|Api|[GET] /api/update: 500.InternalServerError (125 ms)
17-10-12 21:35:28.4|Trace|Http|Req: 1413 [GET] /api/update
17-10-12 21:35:28.4|Trace|Owin|SQLite error (5): database is locked

17-10-12 21:35:28.5|Trace|HttpClient|Req: [GET] http://radarr.aeonlucid.com/v1/update/develop/changes?version=0.2.0.870&os=windows
17-10-12 21:35:28.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-10-12 21:35:28.6|Trace|HttpClient|Res: [GET] http://radarr.aeonlucid.com/v1/update/develop/changes?version=0.2.0.870&os=windows: 200.OK (104 ms)
17-10-12 21:35:28.6|Trace|NzbDroneErrorPipeline|Handling Exception
17-10-12 21:35:28.6|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.870] System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Api.Update.UpdateModule.GetRecentUpdates() in C:\projects\radarr-usby1\src\NzbDrone.Api\Update\UpdateModule.cs:line 34
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourceAll>b__32_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 111
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

17-10-12 21:35:28.6|Trace|Http|Res: 1413 [GET] /api/update: 500.InternalServerError (214 ms)
17-10-12 21:35:28.6|Debug|Api|[GET] /api/update: 500.InternalServerError (214 ms)

**Comment by luxferro** [comment]
It's broken for me too.

**Comment by galli-leo** [comment]
Duplicate issue, it's server side and will be fixed shortly.

**Comment by seanvree** [comment]
fixed in Ver. 0.2.0.877

**Comment by galli-leo** [comment]
@seanvree Probably only fixed because you are on nightly and the nightly endpoint does not have multiple versions for the same release.
