### ISSUE TITLE
error Import downloaded movie

### ISSUE THREAD

**Issue by breadcan** [Radarr/Radarr#224]
Automatic import from downloaded folder did not work. Manual import is the same.

Message: Couldn't import episode G:\sab\movies\The.Girl.on.the.Train.2016.BluRay.Remux.1080p.AVC.DTS.X.7.1-HiFi\The.Girl.on.the.Train.2016.BluRay.Remux.1080p.AVC.DTS.X.7.1-HiFi.mkv: Input string was not in a correct format.

Exception:

System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   at NzbDrone.Core.MediaFiles.MediaInfo.MediaInfoModel.<>c.<get_FormattedAudioChannels>b__73_0(String s) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MediaInfo\MediaInfoModel.cs:line 51
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
   at NzbDrone.Core.MediaFiles.MediaInfo.MediaInfoModel.get_FormattedAudioChannels() in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MediaInfo\MediaInfoModel.cs:line 51
   at NzbDrone.Core.Organizer.FileNameBuilder.AddMediaInfoTokens(Dictionary`2 tokenHandlers, MovieFile movieFile) in C:\projects\radarr-usby1\src\NzbDrone.Core\Organizer\FileNameBuilder.cs:line 717
   at NzbDrone.Core.Organizer.FileNameBuilder.BuildFileName(Movie movie, MovieFile movieFile, NamingConfig namingConfig) in C:\projects\radarr-usby1\src\NzbDrone.Core\Organizer\FileNameBuilder.cs:line 165
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 72
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile episodeFile, LocalMovie localEpisode, Boolean copyOnly) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 67
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:line 102

Version is 0.2.0.99

![image](https://cloud.githubusercontent.com/assets/416166/21937355/6fdc71e6-d9b7-11e6-88e8-d060115e5bc4.png)

**Comment by breadcan** [comment]
The mediainfo xml of the file:
[media.txt](https://github.com/Radarr/Radarr/files/706023/media.txt)

**Comment by breadcan** [comment]
Looks like it is fixed. Could manually import the file now.
