### ISSUE TITLE
Duplicate files on rename and move

### ISSUE THREAD

**Issue by OliverRC** [Radarr/Radarr#2255]
**Description:**

So after the movie was downloaded it seems that in the renaming and moving duplicates were created.

It almost looks like it renamed and moved it twice. Once with my configured settings and then again with the defaults.

![screenshot_14](https://user-images.githubusercontent.com/1888486/32572895-d306f31e-c4d4-11e7-81ec-35a44ab8c684.png)

What is weird is I have metadata enabled which seems to have picked up the "default" filename and not the naming I have configured:

![screenshot_15](https://user-images.githubusercontent.com/1888486/32572976-13b0221e-c4d5-11e7-9776-d86ed141eefa.png) 

Looking into the logs. I see that something happened with removing the file:

```
17-11-8 01:17:18.7|Info|MovieService|Linking [That Sugar Film [2014].mkv] > [[tt3892434][That Sugar Film (2014)]]
17-11-8 01:17:28.7|Error|VideoFileInfoReader|Unable to parse media info from file: F:\Downloads\Complete\Movies\That.Sugar.Film.2014.1080p.BluRay.x264-PHOBOS.1\That.Sugar.Film.2014.1080p.BluRay.x264-PHOBOS.mkv

[v0.2.0.870] System.UnauthorizedAccessException: Access to the path 'F:\Downloads\Complete\Movies\That.Sugar.Film.2014.1080p.BluRay.x264-PHOBOS.1\That.Sugar.Film.2014.1080p.BluRay.x264-PHOBOS.mkv' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at NzbDrone.Common.Disk.DiskProviderBase.OpenReadStream(String path) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 418
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MediaInfo\VideoFileInfoReader.cs:line 53

17-11-8 01:17:57.7|Error|DetectSample|[F:\Downloads\Complete\Movies\That.Sugar.Film.2014.1080p.BluRay.x264-PHOBOS.1\That.Sugar.Film.2014.1080p.BluRay.x264-PHOBOS.mkv] has a runtime of 0, is it a valid video file?
17-11-8 01:18:00.8|Error|DownloadMonitoringService|Couldn't process tracked download That.Sugar.Film.2014.1080p.BluRay.x264-PHOBOS

[v0.2.0.870] System.UnauthorizedAccessException: Access to the path 'That.Sugar.Film.2014.1080p.BluRay.x264-PHOBOS.mkv' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at NzbDrone.Common.Disk.DiskProviderBase.DeleteFolder(String path, Boolean recursive) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 257
   at NzbDrone.Core.MediaFiles.DownloadedMovieImportService.ProcessFolder(DirectoryInfo directoryInfo, ImportMode importMode, Movie movie, DownloadClientItem downloadClientItem) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\DownloadedMovieImportService.cs:line 198
   at NzbDrone.Core.MediaFiles.DownloadedMovieImportService.ProcessPath(String path, ImportMode importMode, Movie movie, DownloadClientItem downloadClientItem) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\DownloadedMovieImportService.cs:line 87
   at NzbDrone.Core.Download.CompletedDownloadService.Import(TrackedDownload trackedDownload) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\CompletedDownloadService.cs:line 113
   at NzbDrone.Core.Download.CompletedDownloadService.Process(TrackedDownload trackedDownload, Boolean ignoreWarnings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\CompletedDownloadService.cs:line 107
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientItems(IDownloadClient downloadClient, DownloadClientItem downloadItem) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 128
```

**Radarr Version:**
0.2.0.870

**Comment by OliverRC** [comment]
Another example, seems to happen every time now :(

![screenshot_16](https://user-images.githubusercontent.com/1888486/32573249-03cbc1fe-c4d6-11e7-8848-b22b6cd217a2.png)

**Comment by OliverRC** [comment]
I was an idiot. After a reboot CouchPotato and Radarr running and pointing to the same folder. They both seemed to "move" the movie although one would fail to delete as the file was locked.
