### ISSUE TITLE
Drone factory interval input not saving

### ISSUE THREAD

**Issue by XmemphistoX** [Radarr/Radarr#228]
Whenever I stick a value for the drone factory interval and hit save, if I refresh or return to the page from another the value does not stick and is blank again.

**Comment by d2dyno** [comment]
I have this issue as well.

**Comment by blackley** [comment]
Still and issue in the latest build - 0.2.0.196

**Comment by WallaWallaWA** [comment]
Interval is saved now, but still must use the Rescan Drone Factory Folder under the Wanted tab to actually get the Folder to scan and pick up the movie.

**Comment by fedoranimus** [comment]
I just tested this and it's rescanning the drone factory folder on the interval.

**Comment by WallaWallaWA** [comment]
Thanks for checking this out. Not certain why it's not working for me. From today, logs read:

17-1-23 13:33:22.1|Error|EventAggregator|MovieMissingModule failed while processing [MovieDownloadedEvent]

[v0.2.0.210] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Api.NzbDroneRestModuleWithSignalR`2.BroadcastResourceChange(ModelAction action, Int32 id) in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModuleWithSignalR.cs:line 38
   at NzbDrone.Api.Wanted.MovieMissingModule.Handle(MovieDownloadedEvent message) in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieMissingModule.cs:line 74
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

Maybe I have some settings incorrect, but it only works when I use the manual rescan.

**Comment by XmemphistoX** [comment]
I am getting the same as WallaWallaWA.  The Drone Factory interval is set however doesn't work.  I have to go to Wanted/Rescan Drone Factory Folder for it to sort.

**Comment by crafty35a** [comment]
I ran into this today as well. I had to manually Rescan Drone Factory Folder to get it to pick up some files, even with the interval set to 1 minute.
