### ISSUE TITLE
Can't add IMDB watchlist

### ISSUE THREAD

**Issue by aporzio1** [Radarr/Radarr#2330]
Description: When trying to add my IMDB watchlist I get the following error when I hit test. 

"Unable to connect to indexer. Indexer responded with html content. Site is likely blocked or unavailable"

I am using http://rss.imdb.com/user/ur50198383/watchlist as my RSS link. I get the same error if I try to use a IMDB list also

Radarr Version: 0.2.0.870

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Did you try using the Radarr lists? Also an exact log would be helpful here.

**Comment by aporzio1** [comment]
The log entry is just the same error and it does work if I do it as a Radarr List

<img width="1122" alt="screen shot 2017-12-10 at 8 33 00 am" src="https://user-images.githubusercontent.com/7033289/33805316-d0abab14-dd84-11e7-9893-dbfe1af41023.png">

**Comment by galli-leo** [comment]
Are you sure you are using the Radarr List correctly? This works for me: /imdb/list?listId=ur50198383

**Comment by roma0803** [comment]
Same issue here. Noticed some movies I added to my 'want to see' list weren't added to Radarr. "Unable to connect to indexer. Indexer responded with html content. Site is likely blocked or unavailable."
Changed the URL to different formats, without resolve. Might this be due to a change at IMDB side?
Log entry: 

```
RSSImport | An error occurred while processing feed. http://rss.imdb.com/list/ls003457489: Indexer responded with html content. Site is likely blocked or unavailable. | 07:48
-- | -- | --
  | NzbDroneErrorPipeline | Invalid request Validation failed:   -- Unable to connect to indexer. Indexer responded with html content. Site is likely blocked or unavailable. | 07:26
  | RSSImport | Unable to connect to list: Indexer responded with html content. Site is likely blocked or unavailable.

```

**Comment by galli-leo** [comment]
Can you post the logs for the radarr list? I tried the radarr list and it worked.

**Comment by roma0803** [comment]
How do I create that specific log? Just for the Radarr list?

**Comment by RickDB** [comment]
RSS domain now redirects to the normal watch list overview, so it's no longer returning the usual rss / xml contents which results in this error.

If this is an intended change by IMDB might need to switch to their .csv export file url which can be found at the bottom of your watch list ("Export this list"), of course that also requires code changes.

**Comment by aporzio1** [comment]
The Radarr list works, but the RSS option does not. What @RickDB  said makes sense, if you put the RSS url in a browser it takes you to the webpage

**Comment by galli-leo** [comment]
Just add the Radarr list, search it and the post the log here.

**Comment by galli-leo** [comment]
Well radarr lists replace the rss list, so parsing the csv won’t be necessary.

**Comment by uncleiven** [comment]
I've also noticed this issue recently. Tried to add the Radarr list (assuming I choose the preset IMDb list option?) but it still won't connect to my watch list. When I test it states failed.

Any ideas?

**Comment by galli-leo** [comment]
Can you post your settings as well as logs?

**Comment by RickDB** [comment]
Removing the IMDB Watchlist and switching to Radarr custom list solved it here.
Thanks @galli-leo 👍

**Comment by uncleiven** [comment]
@galli-leo  - my settings are as follows;

![screen shot 2017-12-13 at 14 26 29](https://user-images.githubusercontent.com/34493348/33943687-b510a014-e011-11e7-8e48-f175975b5bc1.png)

Will attach logs shortly

**Comment by CurtisFeatures** [comment]
Iv got the same issue. It just sits there testing and will not let me save. I must have tried about 30 times and i got it to add a list once. I then tried to add another and got the same issue. I removed the list that did add eventually and I'm now back to square one. Here are my settings and logs

![screen shot 2017-12-14 at 08 18 51](https://user-images.githubusercontent.com/34516049/33982204-9a9b62a0-e0a7-11e7-8145-c931c46a129d.png)

17-12-14 08:16:07.8|Warn|RadarrLists|Unable to connect to list

[v0.2.0.870] System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 74
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 58
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 63
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchNetImportResponse(NetImportRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 131
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 108
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 144

17-12-14 08:16:07.8|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details
17-12-14 08:18:21.3|Warn|RadarrLists|Unable to connect to list

[v0.2.0.870] System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 74
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 58
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 63
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchNetImportResponse(NetImportRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 131
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 108
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 144

17-12-14 08:18:21.3|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details

**Comment by bwareca** [comment]
I've looked into this issue, and apparently IMDB has officially discontinued RSS feed support. You can read an official statement [here](https://getsatisfaction.com/imdb/topics/upcoming-changes-to-several-imdb-features-du6man1opd5q0).

Hopefully Radarr can incorporate an HTML parser for these lists, but until then, we're all out of luck.

**Comment by galli-leo** [comment]
@bwareca We don’t need an html crawler. Just use the Radarr lists, they use an unofficial API.

**Comment by fafoulon** [comment]
I also cannot get it to work, even when using Radarr lists

**Comment by galli-leo** [comment]
@fafoulon Please post the exact error, else we cannot help you.

**Comment by galli-leo** [comment]
@CurtisFeatures Your list works fine for me. Please double check your internet connection / ability to ping api.radarr.video.

**Comment by lemohol** [comment]
Is someone able to share settings that do work? I've followed the multiple ideas on here and cannot get it back working. Thanks all

**Comment by galli-leo** [comment]
Settings seen above work for me. Maybe you can post your settings as well as some logs of the failure?

**Comment by lemohol** [comment]
Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details

v0.2.0.910] NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Unprocessable Entity! Parameter listId has one or more errors.
Full error(s): Unprocessable Entity! Parameter listId has one or more errors. (422), Details: The following errors happened while processing the request parameter listId: The format of the listId given is invalid!
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess(NetImportResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 60
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse(NetImportResponse importResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 34
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 110
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 144

This is the log file details when using the Radarr IMDB list

**Comment by fafoulon** [comment]
Hi, I'm trying with the path to list /imdb/list?listId=ur5726204 I get this error "Unable to connect to list, check the log for more details"

> Unable to connect to list: Error while calling api: Unprocessable Entity! Parameter listId has one or more errors.
Full error(s): Unprocessable Entity! Parameter listId has one or more errors. (422, RayId: 29713327-dabf-4718-9865-bdcaf51bea88), Details: The following errors happened while processing the request parameter listId: The format of the listId given is invalid!

**Comment by galli-leo** [comment]
@fafoulon and @lemohol See #2338

**Comment by CurtisFeatures** [comment]
So i retried this morning and i think i have found my issue. My using IP vanish on the system its installed on and when that is active it doesn't work. Looks like i will have to split my setup into multiple VMs unless anyone else has any other ideas?

**Comment by uncleiven** [comment]
Ok so I can't ping https://api.radarr.video/v2 from my machine, guessing that has something to do with it. Unlike @CurtisFeatures I don't have a VPN running, and I have checked my OpenDNS logs and that domain isn't being blocked

**Comment by uncleiven** [comment]
Ok, so managed to get mine working by adding a / to the end of the API URL...

![screen shot 2017-12-21 at 17 59 30](https://user-images.githubusercontent.com/34493348/34268504-dc0afada-e678-11e7-90e7-85a95b18890b.png)

**Comment by Elfman72** [comment]
I tried everything in this thread and still could not get my Watchlist to work using these settings.  What seems to have worked is not using the urNUMBER format.  What I did to get it to save was to click 'Edit' on my watch list on IMDB.  In the URL, you'll see it gives an actual list id of lsNUMBER.

Using this number instead of UR seemed to work.

Now I need to test if Radarr will actually bring in a new item when I add it to my watch list.

**Comment by SFolkmann** [comment]
Done what Elfman72 did, and that actually works, must be because the "hidden" ls ID is more than 8 characters as commented in issue #2338 by galli-leo

**Comment by ddysart** [comment]
Not to be all "me too" but what Elfman72 suggests is what fixed things for me. Since I'd had automatic sync enabled, using the ur ID resulted in over 50k movies being added to my list (similar to what is mentioned in this [Reddit thread](https://www.reddit.com/r/radarr/comments/6lhiaw/something_is_adding_a_lot_of_crap_movies_to_radarr/).

**Comment by galli-leo** [comment]
Can you share your ur id?

**Comment by ddysart** [comment]
The URL to the watchlist is http://www.imdb.com/user/ur46022785/watchlist?ref_=wt_nv_wl_all_0 but when I click edit it is http://www.imdb.com/list/ls074073377/edit?ref_=wl_edt_pwr.

Using the `ls074073377` works fine, but `ur46022785` resulted in about 50k movies getting added (since I had auto import enabled).

**Comment by lemohol** [comment]
I got this working using the ls tag - it worked perfectly until a few days ago. Nothing changed on the server; Radarr didnt update, no changes what so ever, but now the lists down work again. I can only assume it's at the IDMB end. Does anyone still have theirs working?

**Comment by galli-leo** [comment]
@lemohol Actually, seems like my api is kinda borked atm :(

**Comment by rickyagrawal** [comment]
Has API been fixed?

**Comment by galli-leo** [comment]
@rickyagrawal Yeah should be fine now. (Still unstable a few times a month, but that's kinda impossible to fix, without redoing the whole architecture. We are currently being hit by about 2 million requests a day).

**Comment by DutchmanSA** [comment]
Changing my watchlist to public on IMDB fixed the issue for me. Its on private by default

**Comment by jandreaucodes** [comment]
I'm just trying Radarr for the first time and am struggling to add my list here, too.

Message from logs:
`Unable to connect to list: Error while calling api: Not Found
Full error(s): Not Found (404, RayId: 87c961bd-26ab-4ed1-b084-e4045af6c0ae), Details: not found`

Error:
`NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Not Found
Full error(s): Not Found (404, RayId: 87c961bd-26ab-4ed1-b084-e4045af6c0ae), Details: not found
  at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess (NzbDrone.Core.NetImport.NetImportResponse indexerResponse) [0x00029] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:60 
  at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse (NzbDrone.Core.NetImport.NetImportResponse importResponse) [0x0000d] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:34 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].FetchPage (NzbDrone.Core.NetImport.NetImportRequest request, NzbDrone.Core.NetImport.IParseNetImportResponse parser) [0x00008] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:115 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].TestConnection () [0x00`

Not sure how to proceed here, given the Not Found error.
