### ISSUE TITLE
Parsing error when trying to import from Couchpotato

### ISSUE THREAD

**Issue by nikotime** [Radarr/Radarr#2400]
Hi there

I'm running version 0.2.0.910 and am having problems with importing the wanted films from Couchpotato, getting the error below.

Do you have any advice on how I can get it working? Thanks

Log:
[v0.2.0.910] Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 2, position 1.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Core.NetImport.CouchPotato.CouchPotatoParser.ParseResponse(NetImportResponse importResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\CouchPotato\CouchPotatoParser.cs:line 34
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 110
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 144

18-1-7 22:52:21.2|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details

**Comment by galli-leo** [comment]
Enable trace logging, post them here.

**Comment by nikotime** [comment]
Thanks, please see trace logs here:
https://pastebin.com/BqBG4brq

May have included some stuff too early, sorry!

**Comment by galli-leo** [comment]
Can you go to this url http://localhost:5050/api/HIDDEN/movie.list/?status=active in your browser replacing HIDDEN with your cp api key? And post the results here.

**Comment by nikotime** [comment]
![image](https://user-images.githubusercontent.com/4553820/34713613-bedeabbe-f51e-11e7-89ad-d644f17e1b2a.png)

I just get the attached blank screen, so guess there is a problem with my CP install!

**Comment by galli-leo** [comment]
Yeah try enabling developer mode.

**Comment by nikotime** [comment]
Alas it is enabled - oh well I'll just go about manually adding them! Cheers for your help

**Comment by jaxjexjox** [comment]
I am also having the same issue, latest build of both apps as of today.

**Comment by aphex3k** [comment]
+1

**Comment by aphex3k** [comment]
Having the same issue...
> [Log] Arguments ["TypeError: undefined is not an object (evaluating 'movies.length')", "https://192.168.1.245:8086/static/scripts/combined.plugins.min.js?1512995708", 870] (3) (combined.base.min.js, line 551)
