### ISSUE TITLE
Can't start Radarr with SSL enabled. Port is already in use. (It's not, I scanned with nmap)

### ISSUE THREAD

**Issue by BetaLeaf** [Radarr/Radarr#2451]
```
18-1-27 00:33:03.0|Info|Bootstrap|Starting Radarr - C:\ProgramData\Radarr\bin\Radarr.exe - Version 0.2.0.910
18-1-27 00:33:03.9|Info|Router|Application mode: Interactive
18-1-27 00:33:04.1|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Radarr\nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
18-1-27 00:33:04.4|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Radarr\logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
18-1-27 00:33:04.7|Info|OwinHostController|Listening on the following URLs:
18-1-27 00:33:04.7|Info|OwinHostController|  http://*:5060/
18-1-27 00:33:04.7|Info|OwinHostController|  https://*:5050/
18-1-27 00:33:05.0|Info|NancyBootstrapper|Starting NzbDrone API
18-1-27 00:33:06.5|Fatal|WindowsApp|EPIC FAIL: Port 5060 is already in use, please ensure NzbDrone is not already running.

[v0.2.0.910] Radarr.Host.Owin.PortInUseException: Port 5060 is already in use, please ensure NzbDrone is not already running. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Failed to listen on prefix 'https://*:5050/' because it conflicts with an existing registration on the machine.
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Radarr.Host.Owin.OwinAppFactory.CreateApp(List`1 urls) in C:\projects\radarr-usby1\src\NzbDrone.Host\Owin\OwinServiceProvider.cs:line 52
   --- End of inner exception stack trace ---
   at Radarr.Host.Owin.OwinAppFactory.CreateApp(List`1 urls) in C:\projects\radarr-usby1\src\NzbDrone.Host\Owin\OwinServiceProvider.cs:line 63
   at Radarr.Host.Owin.OwinHostController.StartServer() in C:\projects\radarr-usby1\src\NzbDrone.Host\Owin\OwinHostController.cs:line 53
   at Radarr.Host.NzbDroneServiceFactory.Start() in C:\projects\radarr-usby1\src\NzbDrone.Host\ApplicationServer.cs:line 61
   at Radarr.Host.Router.Route(ApplicationModes applicationModes) in C:\projects\radarr-usby1\src\NzbDrone.Host\Router.cs:line 38
   at Radarr.Host.Bootstrap.Start(ApplicationModes applicationModes, StartupContext startupContext) in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:line 71
   at Radarr.Host.Bootstrap.Start(StartupContext startupContext, IUserAlert userAlert, Action`1 startCallback) in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:line 39
   at NzbDrone.WindowsApp.Main(String[] args) in C:\projects\radarr-usby1\src\NzbDrone\WindowsApp.cs:line 23
```

**Comment by BetaLeaf** [comment]
Sonarr is also having the same problem. https://github.com/Sonarr/Sonarr/issues/2385

**Comment by BetaLeaf** [comment]
I figured it out.
```
netsh http delete urlacl http://*:5050/
netsh http delete urlacl http://*:5060/
netsh http delete urlacl https://*:5050/
netsh http delete urlacl https://*:5060/
```
