### ISSUE TITLE
semicolon messing things up?

### ISSUE THREAD

**Issue by mirthenemrys** [Radarr/Radarr#2454]
**Description:**
Have a bunch of movies that all contain a semicolon ":" in the title, all throwing errors when attempting to search for them on multiple indexers. Both using automatic searching and manual searches. When these movies are searched via the respective websites they all come back with plenty of matches for my profile.

All other info on these movies match the search results, such as release year and full name... except the semicolon since that is not included in scene names. It has not had this issue for all movies with a semicolon, just these. so either a combination with something else... or just a coincidence perhaps.

examples;
Kill Bill: Vol. 1
Kill Bill: Vol. 2
Lara Croft: Tomb Raider
Halloween 4: The Return Of Michael Myers

below a some snippets of what its spitting out, for each release it finds for the movie...

**Radarr Version:**
0.2.0.910 running on Windows 10 x64

**Logs:**

> [v0.2.0.910] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.DecisionEngine.Specifications.QualityAllowedByProfileSpecification.IsSatisfiedBy(RemoteMovie subject, SearchCriteriaBase searchCriteria) in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\Specifications\QualityAllowedByProfileSpecification.cs:line 33
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteMovie remoteMovie, SearchCriteriaBase searchCriteriaBase) in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 307

> 18-1-27 21:23:34.8|Error|DownloadDecisionMaker|Couldn't evaluate decision on Kill Bill Vol 1 2003 BluRay 1080p DTS-HD MA 5.1 x264 dxva-FraMeSToR, with spec: LanguageSpecification

> [v0.2.0.910] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.DecisionEngine.Specifications.LanguageSpecification.IsSatisfiedBy(RemoteMovie subject, SearchCriteriaBase searchCriteria) in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\Specifications\LanguageSpecification.cs:line 35
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteMovie remoteMovie, SearchCriteriaBase searchCriteriaBase) in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 307

> 18-1-27 21:23:34.8|Error|DownloadDecisionMaker|Couldn't evaluate decision on Kill Bill Vol 1 2003 BluRay 1080p DTS-HD MA 5.1 x264 dxva-FraMeSToR, with spec: QualityAllowedByProfileSpecification

> [v0.2.0.910] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.DecisionEngine.Specifications.QualityAllowedByProfileSpecification.IsSatisfiedBy(RemoteMovie subject, SearchCriteriaBase searchCriteria) in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\Specifications\QualityAllowedByProfileSpecification.cs:line 33
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteMovie remoteMovie, SearchCriteriaBase searchCriteriaBase) in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 307

**Comment by mirthenemrys** [comment]
Just did a test with another movie containing a : in it, and it was able to be searched fine. Not sure what makes these ones so special.

**Comment by galli-leo** [comment]
This happens when you delete a movie profile that’s still in use. Try changing the profile on the movies in question.
