### ISSUE TITLE
Manual Import - Unable to parse file

### ISSUE THREAD

**Issue by dedo1911** [Radarr/Radarr#2464]
**Radarr Version:** 0.2.0.910

It's happening like 3 times out of 5 randomly: movies don't get auto imported because "Unable to parse file". Than manual import fails too with the following error.

Message
`Error occurred while executing task ManualImport: Object reference not set to an instance of an object.`

Exception
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Qualities.QualityModelComparer.Compare(QualityModel left, QualityModel right) in C:\projects\radarr-usby1\src\NzbDrone.Core\Qualities\QualityModelComparer.cs:line 29
   at System.Linq.EnumerableSorter`2.CompareKeys(Int32 index1, Int32 index2)
   at System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:line 52
   at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.Execute(ManualImportCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\Manual\ManualImportService.cs:line 316
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41
```

**Comment by galli-leo** [comment]
Please provide more logs than that. E.g. where it says unable to parse and lines before that.

**Comment by dedo1911** [comment]
Unable to parse is in the Activity tab, where I see that it's basically blocked.

![activity](https://user-images.githubusercontent.com/1364496/35708486-b87c3a96-07ae-11e8-9a5e-658eae4b2ab5.png)
The provided stacktracke is the only error I got in the logs, after trying a manual import on that file.

**Comment by galli-leo** [comment]
Can you post the full Log (System -> Logs -> Files)? Also no need to hide release names as in this case it makes it actually harder to see what's going on.

**Comment by krin-san** [comment]
Duplicates #896

**Comment by dedo1911** [comment]
After reading #896 I noticed I wasn't setting the proper quality during manual import. It worked.

Still auto import has failed (quality was set automatically correct actually)

**Comment by krin-san** [comment]
Thanks, @dedo1911 Only now I notice that you could set quality in manual import form 😄 
Any test like "Auto" will be helpful to see it's a selectable field.

**Comment by galli-leo** [comment]
@krin-san Oh wow, even I didn't notice that 😬

**Comment by halsafar** [comment]
Just got bit by this.  For the file selection you get a helpful "Select a file" message.  For the quality selection you get nothing (blank) which if clicked brings up the quality selection.  Perhaps worth reopening this just to add some text to the quality selection input.
