### ISSUE TITLE
radarr randomly stopped working

### ISSUE THREAD

**Issue by phairplay** [Radarr/Radarr#2492]
**Description:**
for some unknown reason radarr has stopped working below is the error when trying to boot it back up. how do i fix this

**Radarr Version:**
v0.2.0.910
**Mono Version:**

**Logs:**
[Info] Bootstrap: Starting Radarr - C:\Radarr\Radarr.Console.exe - Version 0.2.0.910

[Fatal] ConsoleApp: EPIC FAIL!

[v0.2.0.910] System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNet.SignalR.Core, Version=0.1.0.18212, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.AspNet.SignalR.Core, Version=0.1.0.18212, Culture=neutral, PublicKeyToken=null'
   at Radarr.Host.MainAppContainerBuilder..ctor(StartupContext args, String[] assemblies)
   at Radarr.Host.MainAppContainerBuilder.BuildContainer(StartupContext args) in C:\projects\radarr-usby1\src\NzbDrone.Host\MainAppContainerBuilder.cs:line 31
   at Radarr.Host.Bootstrap.Start(StartupContext startupContext, IUserAlert userAlert, Action`1 startCallback) in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:line 33
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in C:\projects\radarr-usby1\src\NzbDrone.Console\ConsoleApp.cs:line 27

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Please use the search bar and make sure you are not submitting an already submitted issue.

**Comment by galli-leo** [comment]
Seems like some dlls are missing. Try reinstalling, using the installer on the releases page.
