### ISSUE TITLE
Discover new movies stopped working

### ISSUE THREAD

**Issue by Wolivere** [Radarr/Radarr#2617]
Failed to discover movies for action recommendations!: Error while calling api: Internal Server Error
Full error(s): Internal Server Error (500, RayId: 271c93d5-db3d-456c-a0bb-0592e20e700e), Details: An error has occurred and this resource cannot be displayed.

NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Internal Server Error
Full error(s): Internal Server Error (500, RayId: 271c93d5-db3d-456c-a0bb-0592e20e700e), Details: An error has occurred and this resource cannot be displayed.
   at NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIClient.Execute[T](HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\RadarrAPI\RadarrAPIClient.cs:line 77
   at NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIClient.DiscoverMovies(String action, Func`2 enhanceRequest) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\RadarrAPI\RadarrAPIClient.cs:line 103
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.DiscoverNewMovies(String action) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 389

**Comment by galli-leo** [comment]
Staging api isn't back up yet.

Also for future reference: API errors go into the correct Github page: Radarr/RadarrAPI.TMDB
