### ISSUE TITLE
Error downloading artwork (when renaming folders)

### ISSUE THREAD

**Issue by Artwebb1986** [Radarr/Radarr#2738]
My issue is that I have it keep the movie folder/file name as {Original Title}

So when I added Fifty Shades Freed to the watch list. It had the path set as X:\Movies\Fifty.Shades.Freed.2018-Radarr

And it renamed the directory to the original title and its named Fifty.Shades.Freed.2018.UNRATED.720p.BluRay.x264-DRONES

I get this error I was told by fryfrog on the discord to send to the github

Couldn't download image C:\ProgramData\Radarr\MediaCover\602\fanart.jpg for [tt4477536][Fifty Shades Freed (2018)]. Could not find a part of the path 'X:\Movies\Fifty.Shades.Freed.2018.-Radarr\fanart.jpg'.: Could not find a part of the path 'X:\Movies\Fifty.Shades.Freed.2018.-Radarr\fanart.jpg'.

System.IO.DirectoryNotFoundException: Could not find a part of the path 'X:\Movies\Fifty.Shades.Freed.2018.-Radarr\fanart.jpg'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskProviderBase.CopyFile(String source, String destination, Boolean overwrite) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 226
   at NzbDrone.Core.Extras.Metadata.MetadataService.DownloadImage(Movie movie, ImageFileResult image) in C:\projects\radarr-usby1\src\NzbDrone.Core\Extras\Metadata\MetadataService.cs:line 279

The exact same error for the poster.jpg as well so I wont post that as well.
 
If I got to my movie list and press the refresh button it will put the poster.jpg and fanart.jpg into the movie directory just fine. Just figured this was something that should of gotten done automatically.

Windows 10
Radarr Ver. 0.2.0.1067
develop

**Comment by Artwebb1986** [comment]
Yes this is still an issue

**Comment by Artwebb1986** [comment]
Still an issue

**Comment by Artwebb1986** [comment]
Still an issue

**Comment by huuub** [comment]
When is this planned?

**Comment by galli-leo** [comment]
http://blog.radarr.video/development/update/2018/11/11/roadmap-update.html

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.

dynamic movie folder names are not supported
