### ISSUE TITLE
Windows 7 Dependencies Error

### ISSUE THREAD

**Issue by DanielHHowell** [Radarr/Radarr#2741]
Tried all of the past five most recent versions, all running under admin. No antivirus software running concurrently, and cleaning system cache and deleting the local folder it created each time. Here is the log I get (from the most recent version):

18-4-23 22:37:58.9|Info|Bootstrap|Starting Radarr - C:\ProgramData\Radarr\bin\Radarr.exe - Version 0.2.0.1067

18-4-23 22:37:59.9|Info|Router|Application mode: Interactive

18-4-23 22:38:00.1|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Radarr\nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***

18-4-23 22:38:00.3|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Radarr\logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***

18-4-23 22:38:00.3|Info|OwinHostController|Listening on the following URLs:

18-4-23 22:38:00.3|Info|OwinHostController| http://*:7878/

18-4-23 22:38:00.5|Info|NancyBootstrapper|Starting NzbDrone API

18-4-23 22:38:00.6|Fatal|WindowsApp|EPIC FAIL: Something went wrong when trying to satisfy one of the dependencies during composition, make sure that you've registered all new dependencies in the container and inspect the innerexception for more details.

[v0.2.0.1067] System.InvalidOperationException: Something went wrong when trying to satisfy one of the dependencies during composition, make sure that you've registered all new dependencies in the container and inspect the innerexception for more details. ---> TinyIoC.TinyIoCResolutionException: Unable to resolve type: Nancy.NancyEngine ---> TinyIoC.TinyIoCResolutionException: Unable to resolve type: Nancy.Routing.DefaultRequestDispatcher ---> TinyIoC.TinyIoCResolutionException: Unable to resolve type: Nancy.Routing.DefaultRouteResolver ---> TinyIoC.TinyIoCResolutionException: Unable to resolve type: Nancy.Routing.RouteCache ---> TinyIoC.TinyIoCResolutionException: Unable to resolve type: NzbDrone.Api.Wanted.MovieCutoffModule ---> System.IO.FileLoadException: Could not load file or assembly 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)

at NzbDrone.Api.NzbDroneRestModule`1..ctor(String resource)

at NzbDrone.Api.Wanted.MovieCutoffModule..ctor(IMovieCutoffService movieCutoffService, IMovieService movieService, IQualityUpgradableSpecification

qualityUpgradableSpecification, IBroadcastSignalRMessage signalRBroadcaster) in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieCutoffModule.cs:line 17 at lambda_method(Closure , Object[] )

at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 3560

--- End of inner exception stack trace ---

at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 3568

at TinyIoC.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 2738

at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 3230

at TinyIoC.TinyIoCContainer.<ResolveAllInternal>b__134_2(TypeRegistration registration) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 3650

at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()

at System.Linq.Enumerable.<CastIterator>d__b1`1.MoveNext()

at Nancy.Routing.RouteCache.BuildCache(IEnumerable`1 modules)

at Nancy.Routing.RouteCache..ctor(INancyModuleCatalog moduleCatalog, INancyContextFactory contextFactory, IRouteSegmentExtractor routeSegmentExtractor, IRouteDescriptionProvider routeDescriptionProvider, ICultureService cultureService, IEnumerable`1 routeMetadataProviders)

at lambda_method(Closure , Object[] )

at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 3560

--- End of inner exception stack trace ---

at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 3568

at TinyIoC.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 2738

at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 3230

at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 3536

--- End of inner exception stack trace ---

at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 3549

at TinyIoC.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 2738

at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 3230

at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 3536

--- End of inner exception stack trace ---

at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 3549

at TinyIoC.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 2738

at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 3230

at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 3536

--- End of inner exception stack trace ---

at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 3549

at TinyIoC.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 2738

at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 3230

at TinyIoC.TinyIoCContainer.Resolve(Type resolveType) in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 1429

at TinyIoC.TinyIoCContainer.Resolve[ResolveType]() in C:\projects\radarr-usby1\src\NzbDrone.Common\TinyIoC.cs:line 1548

at NzbDrone.Api.TinyIoCNancyBootstrapper.GetEngineInternal() in C:\projects\radarr-usby1\src\NzbDrone.Api\TinyIoCNancyBootstrapper.cs:line 52

at Nancy.Bootstrapper.NancyBootstrapperBase`1.SafeGetNancyEngineInstance()

--- End of inner exception stack trace ---

at Nancy.Bootstrapper.NancyBootstrapperBase`1.SafeGetNancyEngineInstance()

at Nancy.Bootstrapper.NancyBootstrapperBase`1.GetEngine()

at Nancy.Owin.NancyMiddleware.UseNancy(NancyOptions options)

at Owin.AppBuilderExtensions.UseNancy(IAppBuilder builder, NancyOptions options)

at Radarr.Host.Owin.MiddleWare.NancyMiddleWare.Attach(IAppBuilder appBuilder) in C:\projects\radarr-usby1\src\NzbDrone.Host\Owin\MiddleWare\NancyMiddleWare.cs:line 20

at Radarr.Host.Owin.OwinAppFactory.BuildApp(IAppBuilder appBuilder) in C:\projects\radarr-usby1\src\NzbDrone.Host\Owin\OwinServiceProvider.cs:line 78

at Microsoft.Owin.Hosting.Engine.HostingEngine.ResolveApp(StartContext context)

at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)

at Radarr.Host.Owin.OwinAppFactory.CreateApp(List`1 urls) in C:\projects\radarr-usby1\src\NzbDrone.Host\Owin\OwinServiceProvider.cs:line 52

at Radarr.Host.Owin.OwinHostController.StartServer() in C:\projects\radarr-usby1\src\NzbDrone.Host\Owin\OwinHostController.cs:line 53

at Radarr.Host.NzbDroneServiceFactory.Start() in C:\projects\radarr-usby1\src\NzbDrone.Host\ApplicationServer.cs:line 63

at Radarr.Host.Router.Route(ApplicationModes applicationModes) in C:\projects\radarr-usby1\src\NzbDrone.Host\Router.cs:line 38

at Radarr.Host.Bootstrap.Start(ApplicationModes applicationModes, StartupContext startupContext) in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:line 73

at Radarr.Host.Bootstrap.Start(StartupContext startupContext, IUserAlert userAlert, Action`1 startCallback) in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:line 39

at NzbDrone.WindowsApp.Main(String[] args) in C:\projects\radarr-usby1\src\NzbDrone\WindowsApp.cs:line 23

**Comment by galli-leo** [comment]
You need to install the .net framework (4.5 IIRC)
