### ISSUE TITLE
Add and Search for Movie Not Working

### ISSUE THREAD

**Issue by speedyflipper** [Radarr/Radarr#2756]
When I add a movie using the add and search function the movie is added but never searched. I must go and manually tell Radarr to search. I am running the latest nightly update.

```
18-5-4 15:41:15.1|Debug|Parser|Parsing string 'The Brothers Grimm'
18-5-4 15:41:15.1|Debug|Parser|Unable to parse The Brothers Grimm
18-5-4 15:41:15.3|Debug|Api|[GET] /api/movie/lookup?term=The+Brothers+Grimm: 200.OK (226 ms)
18-5-4 15:41:17.7|Info|MovieService|Adding Movie [][The Brothers Grimm (2005)] Path: [\\fileserver.phonebook.com\Media\Movies\The Brothers Grimm (2005) -]
18-5-4 15:41:18.9|Info|MediaCoverService|Downloading Poster for [][The Brothers Grimm (2005)] http://image.tmdb.org/t/p/original/g6EgJUwwQre5RsvFj2hDsLzXUsH.jpg
18-5-4 15:41:18.9|Debug|HttpClient|Downloading [http://image.tmdb.org/t/p/original/g6EgJUwwQre5RsvFj2hDsLzXUsH.jpg] to [C:\ProgramData\Radarr\MediaCover\1684\poster.jpg]
18-5-4 15:41:19.2|Debug|Api|[POST] /api/movie: 201.Created (2201 ms)
18-5-4 15:41:19.3|Info|RefreshMovieService|Updating Info for The Brothers Grimm
18-5-4 15:41:19.3|Debug|HttpClient|Downloading Completed. took 0s
18-5-4 15:41:19.4|Debug|MediaCoverService|Resizing Poster-500 for [][The Brothers Grimm (2005)]
18-5-4 15:41:19.9|Debug|RefreshMovieService|Finished movie refresh for The Brothers Grimm
18-5-4 15:41:20.1|Info|RenameMovieFileService|[tt0355295][The Brothers Grimm (2005)]'s movie folder changed to: \\fileserver.phonebook.com\Media\Movies\The Brothers Grimm (2005) - tt0355295
18-5-4 15:41:20.1|Debug|MediaCoverService|Resizing Poster-250 for [][The Brothers Grimm (2005)]
18-5-4 15:41:20.7|Debug|CleanExtraFileService|Cleaning missing metadata files for movie: The Brothers Grimm
18-5-4 15:41:20.1|Error|EventAggregator|DiskScanService failed while processing [MovieUpdatedEvent]

[v0.2.0.1067] System.IO.DirectoryNotFoundException: Could not find a part of the path '\\fileserver.phonebook.com\Media\Movies\The Brothers Grimm (2005) -'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFolder(String source, String destination, Boolean overwrite) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 264
   at NzbDrone.Core.MediaFiles.RenameMovieFileService.RenameMoviePath(Movie movie, Boolean shouldRenameFiles) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\RenameMovieFileService.cs:line 155
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(Movie movie) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 75
   at NzbDrone.Core.MediaFiles.DiskScanService.Handle(MovieUpdatedEvent message) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 198
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

18-5-4 15:41:20.7|Info|MetadataService|Movie folder does not exist, skipping metadata creation
18-5-4 15:41:21.0|Info|MediaCoverService|Downloading Fanart for [tt0355295][The Brothers Grimm (2005)] http://image.tmdb.org/t/p/original/tn7EGGDPYqDn6T1boyfwhizyHkZ.jpg
18-5-4 15:41:21.2|Debug|HttpClient|Downloading [http://image.tmdb.org/t/p/original/tn7EGGDPYqDn6T1boyfwhizyHkZ.jpg] to [C:\ProgramData\Radarr\MediaCover\1684\fanart.jpg]
18-5-4 15:41:21.4|Debug|HttpClient|Downloading Completed. took 0s
18-5-4 15:41:21.4|Debug|MediaCoverService|Resizing Fanart-360 for [tt0355295][The Brothers Grimm (2005)]
18-5-4 15:41:22.0|Debug|MediaCoverService|Resizing Fanart-180 for [tt0355295][The Brothers Grimm (2005)]
```

```
18-5-4 15:33:30.3|Info|MovieService|Adding Movie [][Rounders (1998)] Path: [\\fileserver.phonebook.com\Media\Movies\Rounders (1998) -]
18-5-4 15:33:30.9|Debug|Api|[POST] /api/movie: 201.Created (1405 ms)
18-5-4 15:33:30.8|Info|MediaCoverService|Downloading Poster for [][Rounders (1998)] http://image.tmdb.org/t/p/original/j5IzmdWdO5CqgeoyJLZ1dO7w375.jpg
18-5-4 15:33:31.1|Debug|HttpClient|Downloading [http://image.tmdb.org/t/p/original/j5IzmdWdO5CqgeoyJLZ1dO7w375.jpg] to [C:\ProgramData\Radarr\MediaCover\1683\poster.jpg]
18-5-4 15:33:31.3|Info|RefreshMovieService|Updating Info for Rounders
18-5-4 15:33:31.4|Debug|HttpClient|Downloading Completed. took 0s
18-5-4 15:33:31.4|Debug|MediaCoverService|Resizing Poster-500 for [][Rounders (1998)]
18-5-4 15:33:31.8|Debug|MediaCoverService|Resizing Poster-250 for [][Rounders (1998)]
18-5-4 15:33:32.2|Debug|RefreshMovieService|Finished movie refresh for Rounders
18-5-4 15:33:32.2|Info|RenameMovieFileService|[tt0128442][Rounders (1998)]'s movie folder changed to: \\fileserver.phonebook.com\Media\Movies\Rounders (1998) - tt0128442
18-5-4 15:33:32.3|Debug|CleanExtraFileService|Cleaning missing metadata files for movie: Rounders
18-5-4 15:33:32.3|Error|EventAggregator|DiskScanService failed while processing [MovieUpdatedEvent]

[v0.2.0.1067] System.IO.DirectoryNotFoundException: Could not find a part of the path '\\fileserver.phonebook.com\Media\Movies\Rounders (1998) -'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFolder(String source, String destination, Boolean overwrite) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 264
   at NzbDrone.Core.MediaFiles.RenameMovieFileService.RenameMoviePath(Movie movie, Boolean shouldRenameFiles) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\RenameMovieFileService.cs:line 155
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(Movie movie) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 75
   at NzbDrone.Core.MediaFiles.DiskScanService.Handle(MovieUpdatedEvent message) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 198
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

18-5-4 15:33:32.3|Info|MetadataService|Movie folder does not exist, skipping metadata creation
18-5-4 15:33:32.6|Info|MediaCoverService|Downloading Fanart for [tt0128442][Rounders (1998)] http://image.tmdb.org/t/p/original/IbRtRvkIFwZ6D3F2BliburxWgt.jpg
18-5-4 15:33:32.6|Debug|HttpClient|Downloading [http://image.tmdb.org/t/p/original/IbRtRvkIFwZ6D3F2BliburxWgt.jpg] to [C:\ProgramData\Radarr\MediaCover\1683\fanart.jpg]
18-5-4 15:33:32.8|Debug|HttpClient|Downloading Completed. took 0s
18-5-4 15:33:32.8|Debug|MediaCoverService|Resizing Fanart-360 for [tt0128442][Rounders (1998)]
18-5-4 15:33:33.0|Debug|MediaCoverService|Resizing Fanart-180 for [tt0128442][Rounders (1998)]
18-5-4 15:33:33.2|Debug|CleanExtraFileService|Cleaning missing metadata files for movie: Rounders
18-5-4 15:33:33.2|Info|MetadataService|Movie folder does not exist, skipping metadata creation
```

**Comment by speedyflipper** [comment]
Not sure why this isn't considered a bug but I posted to reddit

**Comment by galli-leo** [comment]
@speedyflipper It isn't considered a bug since a lot of people can search fine. Also you cutoff any logs that could have helped in diagnosing the issue (and deciding whether it's a bug or not)

**Comment by speedyflipper** [comment]
I could have provided more logs if asked to do so but anyway it seems to be related to the "Movie Paths Default to Static" option. When I enable it, the search works fine but the imdb id is not added to the end of the folder. When its disabled, the search doesn't work and the folder is originally created without the the imdb id but it is added later when a movie is post-processed
