### ISSUE TITLE
Can't access settings

### ISSUE THREAD

**Issue by thinkfastsolu1** [Radarr/Radarr#2773]
So this issue is identical to #2039 , only the solutions there have not worked for me.
I am on Pre-Release v0.2.0.1067. I am a first time user of radarr, but have used/am using sonarr.
I am on windows 7, and i have imported my movie library, but when i went to setup the settings for my indexer and media management settings, the 4 dots move back and forth endlessly.

I get this error 18-5-12 11:34:05.1|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.1067] System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Datastore.BasicRepository`1.SingleOrDefault() in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 99
   at NzbDrone.Core.Organizer.NamingConfigService.GetConfig() in C:\projects\radarr-usby1\src\NzbDrone.Core\Organizer\NamingConfigService.cs:line 20
   at NzbDrone.Api.Config.NamingConfigModule.GetNamingConfig() in C:\projects\radarr-usby1\src\NzbDrone.Api\Config\NamingConfigModule.cs:line 51
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourceSingle>b__38_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 147
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
Any Ideas?

**Comment by galli-leo** [comment]
To try and fix this, you can either manually remove the second namingconfig or try waiting for the automatic housekeeper to fix this (Radarr needs to be running).
