### ISSUE TITLE
"Too Many Requests" Error after trying to import a 4-movie watchlist from imdb using Radarr lists.

### ISSUE THREAD

**Issue by georgios89** [Radarr/Radarr#2791]
Full error: 

```
An error occurred while processing feed. http://api.radarr.video/v2/imdb/list?listId=ls003937840: Error while calling api: Too Many Requests
Full error(s): Too Many Requests (429, RayId: 6511e65b-c250-40e7-ae0f-3c48f78f3ea3), Details: You have sent too many requests. Please retry after -1526834166 seconds.
```
Exception: 
```
NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Too Many Requests
Full error(s): Too Many Requests (429, RayId: 6511e65b-c250-40e7-ae0f-3c48f78f3ea3), Details: You have sent too many requests. Please retry after -1526834166 seconds.
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess(NetImportResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 60
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse(NetImportResponse importResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 34
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 115
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchMovies(NetImportPageableRequestChain pageableRequestChain, Boolean isRecent) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 63
```
My settings:
[https://i.imgur.com/E0Unlqq.png](https://i.imgur.com/E0Unlqq.png)

Needless to say, the movies are not getting monitored nor downloaded

**Comment by galli-leo** [comment]
Try using https instead. Could also be that you are on a shared connection that executes too many requests against the api.

**Comment by georgios89** [comment]
I used to have it on https but was not working either.
At the moment, there are no other computers in my network.
Do you think i should change my ip/use proxy? What are the next steps I should take?

**Comment by galli-leo** [comment]
Idk, if you are using a proxy / vpn, I would try disabling that. But in the server logs I see a lot of successful calls to the endpoint. Are you sure that it wasn't just an isolated case?
