### ISSUE TITLE
Crash "out of memory"

### ISSUE THREAD

**Issue by scottrobertson** [Radarr/Radarr#2962]
**Describe the bug**
Whole app is crashing

**To Reproduce**

Unsure

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Tried every nightly and stable. On the lates nightly now

**Debug Logs**

```
18-8-15 21:46:51.4|Error|HousekeepingService|Error running housekeeping task: TrimLogDatabase

[v0.2.0.1158] System.Data.SQLite.SQLiteException (0x80004005): out of memory
out of memory
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at Marr.Data.DataMapper.Delete[T](String tableName, Expression`1 filter)
   at Marr.Data.DataMapper.Delete[T](Expression`1 filter)
   at NzbDrone.Core.Datastore.BasicRepository`1.Delete(Expression`1 filter)
   at NzbDrone.Core.Instrumentation.LogRepository.Trim()
   at NzbDrone.Core.Housekeeping.Housekeepers.TrimLogDatabase.Clean()
   at NzbDrone.Core.Housekeeping.HousekeepingService.Clean()

18-8-15 21:47:11.3|Info|Bootstrap|Starting Radarr - C:\Users\Scott\Desktop\Radarr\Radarr.exe - Version 0.2.0.1158
18-8-15 21:47:11.7|Info|Router|Application mode: Interactive
18-8-15 21:47:11.8|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Radarr\nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
18-8-15 21:47:11.9|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Radarr\logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
18-8-15 21:47:11.9|Info|OwinHostController|Listening on the following URLs:
18-8-15 21:47:11.9|Info|OwinHostController|  http://*:7878/
18-8-15 21:47:12.0|Info|NancyBootstrapper|Starting NzbDrone API
18-8-15 21:47:12.4|Info|BrowserService|Starting default browser. http://localhost:7878
18-8-15 21:47:12.4|Info|ProcessProvider|Opening URL [http://localhost:7878]
18-8-15 21:47:12.6|Info|CommandExecutor|Starting 2 threads for tasks.
```

**Comment by scottrobertson** [comment]
Another one:

```
18-8-15 21:59:24.4|Error|CommandExecutor|Error occurred while executing task ClearLog

[v0.2.0.1158] System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at System.Data.SQLite.SQLiteException.GetErrorString(SQLiteErrorCode errorCode)
   at System.Data.SQLite.SQLiteException.GetStockErrorMessage(SQLiteErrorCode errorCode, String message)
   at System.Data.SQLite.SQLiteException..ctor(SQLiteErrorCode errorCode, String message)
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at Marr.Data.DataMapper.Delete[T](String tableName, Expression`1 filter) in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:line 802
   at Marr.Data.DataMapper.Delete[T](Expression`1 filter) in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:line 777
   at NzbDrone.Core.Datastore.BasicRepository`1.Purge(Boolean vacuum) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 217
   at NzbDrone.Core.Instrumentation.LogService.Execute(ClearLogCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\Instrumentation\LogService.cs:line 28
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 93
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 43
```

**Comment by scottrobertson** [comment]
Plenty of RAM available on the machine too

**Comment by scottrobertson** [comment]
When i run the Housekeeping task, the memory jumps from about 45mb to 1.8gb

**Comment by galli-leo** [comment]
Please provide your full debug log files. Also try removing the log db and see if that helps. Also is this a common occurence (Radarr crashing)?
AFAIK that‘s a sqlite error, so not much we can do about it, if you have enough RAM that shouldn‘t happen.

**Comment by galli-leo** [comment]
Unfortunately I won't be able to be of any help then. Also TV shows? Did Sonarr or Radarr crash?

**Comment by scottrobertson** [comment]
In my head they did :p I meant movies.

No worries. I switched to Couchpotato for now. Will post logs if I switch
back and it happens again. Feel free to close this.

**Comment by galli-leo** [comment]
I think I found the issue.

**Comment by galli-leo** [comment]
So from the limited amount of info you gave me, I couldn't reproduce such a huge jump in memory usage. Nevertheless, I found a few things in the Housekeeping tasks that could potentially lead to something like that and are unnecessary. So I removed them.

I would also recommend checking your AV, according to the Sonarr devs, AVs can potentially limit memory usage of applications.

How many movies do you have added to Radarr?

**Comment by scottrobertson** [comment]
About 150ish. I did start clearing them out and got down to about 100 to
try and see if it helps.

I am away for a while, but I will give this a test once I get back home.

Thank you very much.

Will give full logs if it happens again too.
