### ISSUE TITLE
Folder path not saved on lists and wrong path on imported movies

### ISSUE THREAD

**Issue by Rouzax** [Radarr/Radarr#3015]
**Describe the bug**
In some lists no folder path is saved and as a result when a movie is imported it tries to save it in the ProgamData. When I set it to the second movie folder path it seems to save but I don't want it in that location
Seems to be same as: https://github.com/Radarr/Radarr/issues/1711

**Screenshots**
![image](https://user-images.githubusercontent.com/4103090/45264571-1e5ab300-b43f-11e8-949e-5c9a73911a3f.png)
![image](https://user-images.githubusercontent.com/4103090/45264638-f586ed80-b43f-11e8-8764-8fd2a1c24064.png)

**Desktop (please complete the following information):**
 - OS: Windows 2016
 - Browser and Version: Firefox 62 64Bit
 - Version: 0.2.0.1120

**Debug Logs**
```
18-9-9 14:38:06.2|Info|MediaCoverService|Downloading Poster for [tt5208252][Operation Finale (2018)] http://image.tmdb.org/t/p/original/uitoc4tDFFotLSs1vJBon52IZIx.jpg
18-9-9 14:38:06.2|Info|RefreshMovieService|Updating Info for Operation Finale
18-9-9 14:38:06.2|Debug|HttpClient|Downloading [http://image.tmdb.org/t/p/original/uitoc4tDFFotLSs1vJBon52IZIx.jpg] to [C:\ProgramData\Radarr\MediaCover\1994\poster.jpg]
18-9-9 14:38:06.4|Debug|HttpClient|Downloading Completed. took 0s
18-9-9 14:38:06.4|Debug|MediaCoverService|Resizing Poster-500 for [tt5208252][Operation Finale (2018)]
18-9-9 14:38:06.6|Debug|MediaCoverService|Resizing Poster-250 for [tt5208252][Operation Finale (2018)]
18-9-9 14:38:06.8|Info|MediaCoverService|Downloading Fanart for [tt5208252][Operation Finale (2018)] http://image.tmdb.org/t/p/original/7diKA3XyLUB9pV6oI9FznQ5lv66.jpg
18-9-9 14:38:06.8|Debug|HttpClient|Downloading [http://image.tmdb.org/t/p/original/7diKA3XyLUB9pV6oI9FznQ5lv66.jpg] to [C:\ProgramData\Radarr\MediaCover\1994\fanart.jpg]
18-9-9 14:38:06.8|Debug|HttpClient|Downloading Completed. took 0s
18-9-9 14:38:06.8|Debug|MediaCoverService|Resizing Fanart-360 for [tt5208252][Operation Finale (2018)]
18-9-9 14:38:06.9|Debug|MediaCoverService|Resizing Fanart-180 for [tt5208252][Operation Finale (2018)]
18-9-9 14:38:06.9|Debug|CleanExtraFileService|Cleaning missing metadata files for movie: Operation Finale
18-9-9 14:38:06.9|Warn|ArgumentValidator|value [Operation Finale (2018)]  is not a valid Windows path. paths must be a full path eg. C:\Windows
18-9-9 14:38:07.0|Debug|RefreshMovieService|Finished movie refresh for Operation Finale
18-9-9 14:38:07.0|Error|EventAggregator|ExtraService failed while processing [MediaCoversUpdatedEvent]

[v0.2.0.1120] System.ArgumentException: value [Operation Finale (2018)]  is not a valid Windows path. paths must be a full path eg. C:\Windows
Parameter name: path
   at NzbDrone.Common.EnsureThat.EnsureStringExtensions.IsValidPath(Param`1 param) in C:\projects\radarr-usby1\src\NzbDrone.Common\EnsureThat\EnsureStringExtensions.cs:line 109
   at NzbDrone.Common.Disk.DiskProviderBase.FolderExists(String path) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 83
   at NzbDrone.Core.Extras.Metadata.MetadataService.CreateAfterMovieScan(Movie movie, List`1 movieFiles) in C:\projects\radarr-usby1\src\NzbDrone.Core\Extras\Metadata\MetadataService.cs:line 64
   at NzbDrone.Core.Extras.ExtraService.Handle(MediaCoversUpdatedEvent message) in C:\projects\radarr-usby1\src\NzbDrone.Core\Extras\ExtraService.cs:line 119
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

18-9-9 14:38:07.9|Info|DiskScanService|Scanning disk for Operation Finale
18-9-9 14:38:07.9|Debug|DiskScanService|Movies folder doesn't exist: C:\ProgramData\Radarr\bin\Operation Finale (2018)
18-9-9 14:38:08.1|Debug|CleanExtraFileService|Cleaning missing metadata files for movie: Operation Finale
18-9-9 14:38:08.1|Info|MetadataService|Movie folder does not exist, skipping metadata creation
18-9-9 14:38:14.1|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (15 ms)
18-9-9 14:38:19.0|Debug|Api|[GET] /api/history?page=1&pageSize=15&sortKey=date&sortDir=desc&movieId=1994: 200.OK (15 ms)
18-9-9 14:38:24.6|Debug|Api|[GET] /api/filesystem?includeFiles=false&path=C%3A%5CProgramData%5CRadarr%5Cbin%5COperation+Finale+(2018): 200.OK (62 ms)
18-9-9 14:38:42.3|Debug|Api|[GET] /api/filesystem?includeFiles=false&path=C%3A%5CProgramData%5CRadarr%5Cbin%5COperation+Finale+(2018): 200.OK (0 ms)
18-9-9 14:38:43.0|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (0 ms)
18-9-9 14:38:44.0|Debug|Api|[GET] /api/filesystem?includeFiles=false&path=C%3A%5CProgramData%5CRadarr%5C: 200.OK (0 ms)
18-9-9 14:38:44.3|Debug|Api|[GET] /api/filesystem?includeFiles=false&path=C%3A%5CProgramData%5C: 200.OK (46 ms)
18-9-9 14:38:44.4|Debug|Api|[GET] /api/filesystem?includeFiles=false&path=C%3A%5C: 200.OK (15 ms)
18-9-9 14:38:45.7|Debug|Api|[GET] /api/filesystem?includeFiles=false&path=C%3A%5CDATA%5C: 200.OK (31 ms)
18-9-9 14:38:47.7|Debug|Api|[GET] /api/filesystem?includeFiles=false&path=C%3A%5CDATA%5CMovies%5C: 200.OK (15 ms)
18-9-9 14:38:49.4|Debug|Api|[GET] /api/filesystem?includeFiles=false&path=C%3A%5CDATA%5CMovies%5COperation+Finale+(2018): 200.OK (31 ms)
18-9-9 14:38:56.5|Debug|Api|[PUT] /api/movie/1994: 202.Accepted (312 ms)
18-9-9 14:38:59.7|Debug|Api|[GET] /api/config/mediamanagement: 200.OK (15 ms)
18-9-9 14:38:59.7|Debug|Api|[GET] /api/config/downloadclient: 200.OK (15 ms)
18-9-9 14:38:59.7|Debug|Api|[GET] /api/config/indexer: 200.OK (15 ms)
18-9-9 14:38:59.7|Debug|Api|[GET] /api/config/naming: 200.OK (31 ms)
18-9-9 14:38:59.7|Debug|Api|[GET] /api/config/netimport: 200.OK (0 ms)
18-9-9 14:38:59.7|Debug|Api|[GET] /api/config/ui: 200.OK (0 ms)
18-9-9 14:38:59.7|Debug|Api|[GET] /api/notification: 200.OK (15 ms)
18-9-9 14:38:59.7|Debug|Api|[GET] /api/config/host: 200.OK (15 ms)
18-9-9 14:38:59.8|Debug|Api|[GET] /api/config/naming/samples?renameEpisodes=true&replaceIllegalCharacters=true&colonReplacementFormat=delete&standardMovieFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)+-+%7B%5BEdition+Tags%5D%7D%7B%5BQuality+Full%5D%7D%7B%5BMEDIAINFO+AUDIOCODEC%7D%7B+MEDIAINFO+AUDIOCHANNELS%5D%7D%7B%5BMEDIAINFO+VIDEOCODEC%5D%7D%7B-Release+Group%7D&movieFolderFormat=%7BMovie+TitleThe%7D+(%7BRelease+Year%7D)&multiEpisodeStyle=0&includeSeriesTitle=false&includeEpisodeTitle=false&includeQuality=false&replaceSpaces=false&id=1: 200.OK (15 ms)
18-9-9 14:38:59.8|Debug|Api|[GET] /api/profile: 200.OK (0 ms)
18-9-9 14:38:59.8|Debug|Api|[GET] /api/delayprofile: 200.OK (15 ms)
18-9-9 14:38:59.8|Debug|Api|[GET] /api/qualitydefinition: 200.OK (15 ms)
18-9-9 14:38:59.8|Debug|Api|[GET] /api/Restriction: 200.OK (15 ms)
18-9-9 14:38:59.8|Debug|Api|[GET] /api/remotePathMapping: 200.OK (15 ms)
18-9-9 14:38:59.8|Debug|Api|[GET] /api/downloadclient: 200.OK (15 ms)
18-9-9 14:38:59.8|Debug|Api|[GET] /api/indexer: 200.OK (15 ms)
18-9-9 14:38:59.9|Debug|Api|[GET] /api/netimport: 200.OK (15 ms)
18-9-9 14:38:59.9|Debug|RootFolderService|Generating list of unmapped folders
18-9-9 14:38:59.9|Debug|Api|[GET] /api/metadata: 200.OK (15 ms)
18-9-9 14:38:59.9|Debug|Api|[GET] /api/exclusions: 200.OK (31 ms)
18-9-9 14:39:00.0|Debug|RootFolderService|0 unmapped folders detected.
18-9-9 14:39:00.0|Debug|RootFolderService|Generating list of unmapped folders
18-9-9 14:39:00.1|Debug|RootFolderService|1 unmapped folders detected.
18-9-9 14:39:00.1|Debug|Api|[GET] /api/rootfolder: 200.OK (312 ms)
18-9-9 14:39:09.1|Debug|Api|[PUT] /api/netimport/11: 202.Accepted (31 ms)
18-9-9 14:39:12.6|Debug|Api|[PUT] /api/netimport/10: 202.Accepted (15 ms)
18-9-9 14:39:13.0|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (15 ms)
18-9-9 14:39:18.6|Debug|Api|[DELETE] /api/netimport/1: 200.OK (15 ms)
18-9-9 14:39:21.9|Debug|Api|[PUT] /api/netimport/8: 202.Accepted (15 ms)
18-9-9 14:39:27.9|Debug|Api|[PUT] /api/netimport/11: 202.Accepted (15 ms)
18-9-9 14:39:32.8|Debug|Api|[PUT] /api/netimport/10: 202.Accepted (15 ms)
18-9-9 14:39:37.1|Debug|Api|[PUT] /api/netimport/4: 202.Accepted (15 ms)
18-9-9 14:39:40.8|Debug|Api|[PUT] /api/netimport/7: 202.Accepted (15 ms)
18-9-9 14:39:43.0|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (0 ms)
18-9-9 14:40:13.0|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (0 ms)
18-9-9 14:40:44.0|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (0 ms)
18-9-9 14:41:13.0|Info|PreDBService|Starting PreDB Sync
18-9-9 14:41:13.1|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (15 ms)
18-9-9 14:41:43.0|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (15 ms)
18-9-9 14:41:43.0|Info|NetImportSearchService|No lists are enabled for auto-import.
18-9-9 14:42:13.1|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (0 ms)
```

**Comment by galli-leo** [comment]
This is a known issue with firefox. Either try a different browser, or use different path, save list, open back up, use the first path and save list. (While it will show back again as an empty path, the path should be correct).
