### ISSUE TITLE
Couldn't process release.: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Grohnheit** [Radarr/Radarr#3022]
Hey.
After the latest updates, when I search for a movie it dont return anything.
I am running 0.2.0.1191

I have tried a profile without Custom Formats, and it´s the same.

From the log:
```
18-9-12 18:00:59.1|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unexpected error processing release
18-9-12 18:00:59.1|Debug|Parser|Parsing string 'Oceans.Eight.2018.BDRip.x264-SPARKS'
18-9-12 18:00:59.1|Debug|Parser|Movie Parsed. Oceans Eight - 2018 
18-9-12 18:00:59.1|Debug|ParsingService|Language(s) parsed: 
18-9-12 18:00:59.1|Debug|QualityParser|Trying to parse quality for Oceans.Eight.2018.BDRip.x264-SPARKS
18-9-12 18:00:59.1|Error|DownloadDecisionMaker|Couldn't process release.

[v0.2.0.1191] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.CustomFormats.FormatTag.DoesItMatchWithoutMods(ParsedMovieInfo movieInfo) in C:\projects\radarr-usby1\src\NzbDrone.Core\CustomFormats\FormatTag.cs:line 74
   at NzbDrone.Core.CustomFormats.FormatTag.DoesItMatch(ParsedMovieInfo movieInfo) in C:\projects\radarr-usby1\src\NzbDrone.Core\CustomFormats\FormatTag.cs:line 43
   at NzbDrone.Core.Parser.ParsingService.<>c__DisplayClass13_0.<MatchFormatTags>b__3(FormatTag t) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 166
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at NzbDrone.Core.Parser.ParsingService.<>c__DisplayClass13_0.<MatchFormatTags>b__1(IGrouping`2 g) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 166
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Parser.ParsingService.MatchFormatTags(ParsedMovieInfo movieInfo) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 165
   at NzbDrone.Core.Parser.ParsingService.ParseCustomFormat(ParsedMovieInfo movieInfo) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 147
   at NzbDrone.Core.Parser.ParsingService.EnhanceMinimalInfo(ParsedMovieInfo minimalInfo, List`1 helpers) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 95
   at NzbDrone.Core.Parser.ParsingService.ParseMovieInfo(String title, List`1 helpers) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 74
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.<GetMovieDecisions>d__8.MoveNext() in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 73

18-9-12 18:00:59.1|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unexpected error processing release
18-9-12 18:00:59.2|Debug|Parser|Parsing string 'Oceans.Eight.2018.720p.BluRay.x264-SPARKS'
18-9-12 18:00:59.2|Debug|Parser|Movie Parsed. Oceans Eight - 2018 
18-9-12 18:00:59.2|Debug|ParsingService|Language(s) parsed: 
18-9-12 18:00:59.2|Debug|QualityParser|Trying to parse quality for Oceans.Eight.2018.720p.BluRay.x264-SPARKS
18-9-12 18:00:59.2|Error|DownloadDecisionMaker|Couldn't process release.

[v0.2.0.1191] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.CustomFormats.FormatTag.DoesItMatchWithoutMods(ParsedMovieInfo movieInfo) in C:\projects\radarr-usby1\src\NzbDrone.Core\CustomFormats\FormatTag.cs:line 74
   at NzbDrone.Core.CustomFormats.FormatTag.DoesItMatch(ParsedMovieInfo movieInfo) in C:\projects\radarr-usby1\src\NzbDrone.Core\CustomFormats\FormatTag.cs:line 43
   at NzbDrone.Core.Parser.ParsingService.<>c__DisplayClass13_0.<MatchFormatTags>b__3(FormatTag t) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 166
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at NzbDrone.Core.Parser.ParsingService.<>c__DisplayClass13_0.<MatchFormatTags>b__1(IGrouping`2 g) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 166
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Parser.ParsingService.MatchFormatTags(ParsedMovieInfo movieInfo) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 165
   at NzbDrone.Core.Parser.ParsingService.ParseCustomFormat(ParsedMovieInfo movieInfo) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 147
   at NzbDrone.Core.Parser.ParsingService.EnhanceMinimalInfo(ParsedMovieInfo minimalInfo, List`1 helpers) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 95
   at NzbDrone.Core.Parser.ParsingService.ParseMovieInfo(String title, List`1 helpers) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 74
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.<GetMovieDecisions>d__8.MoveNext() in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 73
```

**Comment by Grohnheit** [comment]
And I dont have this folder on the server: C:\projects

**Comment by Grohnheit** [comment]
If I try to "Test" a custom format, I get the same error.
From the log:

18-9-12 18:45:06.8|Debug|Api|[GET] /api/customformat/test?title=A.Movie.2018.Directors.Cut.2160p.UHD.BluRay.REMUX.HDR.HEVC.Atmos-EPSiLOn&sort_by=matches&order=desc: 500.InternalServerError (31 ms)
18-9-12 18:45:11.9|Debug|Parser|Parsing string 'A.Movie.2018.Directors.Cut.2160p.UHD.BluRay.REMUX.HDR.HEVC.Atmos-EPSiLON'
18-9-12 18:45:11.9|Debug|Parser|Movie Parsed. A Movie - 2018 
18-9-12 18:45:11.9|Debug|ParsingService|Language(s) parsed: 
18-9-12 18:45:11.9|Debug|QualityParser|Trying to parse quality for A.Movie.2018.Directors.Cut.2160p.UHD.BluRay.REMUX.HDR.HEVC.Atmos-EPSiLON
18-9-12 18:45:11.9|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.1191] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.CustomFormats.FormatTag.DoesItMatchWithoutMods(ParsedMovieInfo movieInfo) in C:\projects\radarr-usby1\src\NzbDrone.Core\CustomFormats\FormatTag.cs:line 74
   at NzbDrone.Core.CustomFormats.FormatTag.DoesItMatch(ParsedMovieInfo movieInfo) in C:\projects\radarr-usby1\src\NzbDrone.Core\CustomFormats\FormatTag.cs:line 43
   at NzbDrone.Core.Parser.ParsingService.<>c__DisplayClass13_0.<MatchFormatTags>b__3(FormatTag t) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 166
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at NzbDrone.Core.Parser.ParsingService.<>c__DisplayClass13_0.<MatchFormatTags>b__1(IGrouping`2 g) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 166
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Parser.ParsingService.MatchFormatTags(ParsedMovieInfo movieInfo) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 165
   at NzbDrone.Core.Parser.ParsingService.ParseCustomFormat(ParsedMovieInfo movieInfo) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 147
   at NzbDrone.Core.Parser.ParsingService.EnhanceMinimalInfo(ParsedMovieInfo minimalInfo, List`1 helpers) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 95
   at NzbDrone.Core.Parser.ParsingService.ParseMovieInfo(String title, List`1 helpers) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 74
   at NzbDrone.Api.Qualities.CustomFormatModule.TestWithNewModel() in C:\projects\radarr-usby1\src\NzbDrone.Api\Qualities\CustomFormatModule.cs:line 120
   at NzbDrone.Api.Qualities.CustomFormatModule.<.ctor>b__2_7(Object x) in C:\projects\radarr-usby1\src\NzbDrone.Api\Qualities\CustomFormatModule.cs:line 52
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by fryfrog** [comment]
Can you hop on to the [Radarr Discord] (https://discord.gg/AD3UP37) for some real time trouble shooting? I'm not sure what this is and I think we'll need to work through it to figure out.

**Comment by Grohnheit** [comment]
Deleting all custom formats and recreating them, fixed the problem.
