### ISSUE TITLE
Testing Slack Webhook Connection Fails Due To Empty Test Message

### ISSUE THREAD

**Issue by ThePieMonster** [Radarr/Radarr#3073]
**Describe the bug**
I am trying to save a new slack connection in which I provided the name, webhook url, and username but I can't get it to save the connection. When I reload the page there are no connections. Tried restarting also.

Looked in the logs and it seems when you go to save or test a connection there is no text value being populated with a test message so it fails.

**To Reproduce**
1. Go to Settings
2. Click on Connections
3. Add new connection and select Slack
4. Enter a name, webhook url, and username
5. See error

**Expected behavior**
The test is successful and the connection is added

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome 69
 - Version 0.2.0.1120

**Debug Logs**
HttpClient
`HTTP Error - Res: [POST] https://discordapp.com/api/webhooks/#############/###########################: 400.BadRequest {"code": 50006, "message": "Cannot send an empty message"}`

NzbDroneErrorPipeline
```
NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [POST] at [https://discordapp.com/api/webhooks/#############/###########################]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 89
   at NzbDrone.Core.Notifications.Slack.SlackProxy.SendPayload(SlackPayload payload, SlackSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Slack\SlackProxy.cs:line 37
   at NzbDrone.Core.Notifications.Slack.Slack.TestMessage() in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Slack\Slack.cs:line 98
   at NzbDrone.Core.Notifications.Slack.Slack.Test() in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Slack\Slack.cs:line 85
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.Test(TProviderDefinition definition) in C:\projects\radarr-usby1\src\NzbDrone.Core\ThingiProvider\ProviderFactory.cs:line 81
   at NzbDrone.Api.ProviderModuleBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in C:\projects\radarr-usby1\src\NzbDrone.Api\ProviderModuleBase.cs:line 206
   at NzbDrone.Api.ProviderModuleBase`3.Test(TProviderResource providerResource) in C:\projects\radarr-usby1\src\NzbDrone.Api\ProviderModuleBase.cs:line 179
   at NzbDrone.Api.ProviderModuleBase`3.<.ctor>b__1_1(Object x) in C:\projects\radarr-usby1\src\NzbDrone.Api\ProviderModuleBase.cs:line 28
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
{"code": 50006, "message": "Cannot send an empty message"}
```

**Comment by galli-leo** [comment]
https://discordapp.com/developers/docs/resources/webhook#execute-slackcompatible-webhook You need to use this url, else it’s not a slack webhook
