### ISSUE TITLE
Corrupt history?

### ISSUE THREAD

**Issue by woble** [Radarr/Radarr#309]
Opening history tab shows loading indefinitely.

```
Request Failed: Instance property 'movies' is not defined for type 'NzbDrone.Core.History.History'
```
```
System.ArgumentException: Instance property 'movies' is not defined for type 'NzbDrone.Core.History.History'
   at System.Linq.Expressions.Expression.Property(Expression expression, String propertyName)
   at NzbDrone.Core.Datastore.Extensions.PagingSpecExtensions.CreateExpression[TModel](String propertyName) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Extensions\PagingSpecExtensions.cs:line 36
   at NzbDrone.Core.Datastore.Extensions.PagingSpecExtensions.OrderByClause[TModel](PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Extensions\PagingSpecExtensions.cs:line 11
   at NzbDrone.Core.Datastore.BasicRepository`1.GetPagedQuery(QueryBuilder`1 query, PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 257
   at NzbDrone.Core.History.HistoryRepository.GetPagedQuery(QueryBuilder`1 query, PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\History\HistoryRepository.cs:line 76
   at NzbDrone.Core.Datastore.BasicRepository`1.GetPaged(PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 249
   at NzbDrone.Core.History.HistoryService.Paged(PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\History\HistoryService.cs:line 51
   at NzbDrone.Api.NzbDroneRestModule`1.ApplyToPage[TModel](Func`2 function, PagingSpec`1 pagingSpec, Converter`2 mapper) in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModule.cs:line 27
   at NzbDrone.Api.History.HistoryModule.GetHistory(PagingResource`1 pagingResource) in C:\projects\radarr-usby1\src\NzbDrone.Api\History\HistoryModule.cs:line 79
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourcePaged>b__35_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 126
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

**Comment by galli-leo** [comment]
Do you by any chance now since when this is happening?

**Comment by woble** [comment]
It was a few days ago, but I believe it happened after Radarr wasn't communicating correctly with nzbget about a failed download. I recall marking a download as failed in Radarr and removing a few incorrect entries from history. It might broke at that point or after I restarted or maybe even updated Radarr. 😕

**Comment by woble** [comment]
"Solved" by changing port number. Still no idea why or how it's even related.
