### ISSUE TITLE
Error while adding Torznab/Torrentpotato

### ISSUE THREAD

**Issue by Binkie88** [Radarr/Radarr#311]
While adding a cardigann Torznab or Torrentpotato feed i get this error.

```
Unable to connect to indexer: Sequence contains no elements
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 322

**Comment by morpheus65535** [comment]
Got the same problem here when I try to add a Torznab that work fine with Sonarr.

**Comment by phendryx** [comment]
+1

**Comment by Dgameman1** [comment]
+1. Added things in the username field didn't fix anything.

**Comment by onedr0p** [comment]
I'll have to get cardigann up and running and see what all the fuss is about :)

**Comment by Dnkhatri** [comment]
works for me at least for kickass and piratebay copied the torrent potato field and the api leaving username blank

**Comment by Binkie88** [comment]
When adding torrentpotato feeds on the latest version it works. Torznab is still not working for me

**Comment by roboticsound** [comment]
I am running on Ubuntu 14.01 and am getting the below error. It looks like it is looking for a windows path.

```17-1-24 12:04:30.1|Warn|NzbDroneErrorPipeline|Invalid request Validation failed:
 -- Unable to connect to indexer, check the log for more details
17-1-24 12:04:37.2|Warn|TorrentPotato|Unable to connect to indexer

[v0.2.0.210] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Common.Http.HttpRequestBuilder.AddQueryParam (System.String key, System.Object value, Boolean replace) [0x00040] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpRequestBuild$
  at NzbDrone.Core.Indexers.TorrentPotato.TorrentPotatoRequestGenerator+<GetPagedRequests>d__11.MoveNext () [0x0003a] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\TorrentPotato\TorrentPo$
  at System.Linq.Enumerable.First[TSource] (IEnumerable`1 source) <0x4083d3f0 + 0x000be> in <filename unknown>:0
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:323
```

**Comment by onedr0p** [comment]
I have created an issue on cardiganns GH issue page:

https://github.com/cardigann/cardigann/issues/327

Anyone with GoLang knowledge feel free to send them a PR.

Closing this, as it's not in our hands to make cardigann work.
