### ISSUE TITLE
Can no longer add movies to Radarr

### ISSUE THREAD

**Issue by tusharbhutt** [Radarr/Radarr#3143]
I cannot add movies via the "Add Movies" page... every title I enter comes up with no results.

**To Reproduce**
1. Go to "Add Movies" from the top menu
2. Click on "Add New Movie" and enter a name
3. There are no results when entering a name, or the IMDB id number
4. The error is:

 There was an error searching for 'imdb:tt0098439'. (<-- a random example, don't hate me)
If the movie title contains non-alphanumeric characters try removing them, otherwise try your search again later. 

**Expected behavior**
Some results should have been displayed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version: Problem exists on all browsers
 - Version 0.2.0.1202, problem started after October 29 update

The log shows an error as per below and I will try to attach the file.  
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/2536714/radarr.debug.txt)

> 18-10-31 17:31:44.2|Debug|Api|[GET] /api/movie/lookup?term=Christ: 500.InternalServerError (156 ms)
> 18-10-31 17:31:46.6|Debug|Parser|Parsing string 'Christopher Robin'
> 18-10-31 17:31:46.7|Debug|Parser|Unable to parse Christopher Robin
> 18-10-31 17:31:46.7|Fatal|NzbDroneErrorPipeline|Request Failed
> 
> [v0.2.0.1202] System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 23.21.221.50:443
>    at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
>    at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
>    --- End of inner exception stack trace ---
>    at System.Net.HttpWebRequest.GetResponse()
>    at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 74
>    at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 58
>    at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 114
>    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 50
>    at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 255
>    at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 507
>    at NzbDrone.Api.Movies.MovieLookupModule.Search() in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\MovieLookupModule.cs:line 48
>    at NzbDrone.Api.Movies.MovieLookupModule.<.ctor>b__2_0(Object x) in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\MovieLookupModule.cs:line 22
>    at CallSite.Target(Closure , CallSite , Func`2 , Object )
>    at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

Rebooting the machine and restarting the applications did not help.

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by tusharbhutt** [comment]
Seems to be a firewall issue that just occurred...
