### ISSUE TITLE
Problem with bitdefender

### ISSUE THREAD

**Issue by pikachukaki** [Radarr/Radarr#3159]
Im getting this error while installing. Bitdefender stop it once i put it in exceptions but still after 5-6 installs im getting this

[Fatal] ConsoleApp: EPIC FAIL!

[v0.2.0.1120] System.InvalidOperationException: Cannot start service Radarr on computer '.'. ---> System.ComponentModel.Win32Exception: The dependency service does not exist or has been marked for deletion
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at System.ServiceProcess.ServiceController.Start()
   at NzbDrone.Common.ServiceProvider.Start(String serviceName) in C:\projects\radarr-usby1\src\NzbDrone.Common\ServiceProvider.cs:line 171
   at Radarr.Host.Router.Route(ApplicationModes applicationModes) in C:\projects\radarr-usby1\src\NzbDrone.Host\Router.cs:line 51
   at Radarr.Host.Bootstrap.Start(ApplicationModes applicationModes, StartupContext startupContext) in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:line 73
   at Radarr.Host.Bootstrap.Start(StartupContext startupContext, IUserAlert userAlert, Action`1 startCallback) in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:line 39
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in C:\projects\radarr-usby1\src\NzbDrone.Console\ConsoleApp.cs:line 35

**Comment by galli-leo** [comment]
Not much we can do here. You could write bitdefender and point them to this page and tell them to whitelist it.
