### ISSUE TITLE
The SceneMappingservice task fails - can the task be removed

### ISSUE THREAD

**Issue by CBers** [Radarr/Radarr#329]
The SceneMappingservice task fails - can the task be removed please.

**Message**:

Failed to Update Scene Mappings:: HTTP request failed: [404:NotFound] [GET] at [http://radarr.aeonlucid.com/v1/scenemapping]

**Exception**:

NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [http://radarr.aeonlucid.com/v1/scenemapping]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 99
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 191
   at NzbDrone.Core.DataAugmentation.Scene.SceneMappingProxy.Fetch() in C:\projects\radarr-usby1\src\NzbDrone.Core\DataAugmentation\Scene\SceneMappingProxy.cs:line 29
   at NzbDrone.Core.DataAugmentation.Scene.ServicesProvider.GetSceneMappings() in C:\projects\radarr-usby1\src\NzbDrone.Core\DataAugmentation\Scene\ServicesProvider.cs:line 16
   at NzbDrone.Core.DataAugmentation.Scene.SceneMappingService.UpdateMappings() in C:\projects\radarr-usby1\src\NzbDrone.Core\DataAugmentation\Scene\SceneMappingService.cs:line 151

**Comment by onedr0p** [comment]
We will remove it.

**Comment by CBers** [comment]
Thanks.
