### ISSUE TITLE
Raddar crashes windows 10 event logs 

### ISSUE THREAD

**Issue by Bastien42** [Radarr/Radarr#3306]
hi so i'm running radarr v0.2.0.1217 on windows 10 pro as a service on startup and the app run good until it crashes i then go in windows event viewer and got these 3: 

```
Application: radarr.console.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.SEHException
   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_step(IntPtr)
   at System.Data.SQLite.SQLite3.Step(System.Data.SQLite.SQLiteStatement)
   at System.Data.SQLite.SQLiteDataReader.Read()
   at Marr.Data.DataMapper.QueryToGraph[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, Marr.Data.EntityGraph, System.Collections.Generic.List`1<System.Reflection.MemberInfo>)
   at Marr.Data.QGen.QueryBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ToList()
   at Marr.Data.QGen.SortBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ToList()
   at Marr.Data.QGen.SortBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at NzbDrone.Core.Movies.MovieRepository.FindByTmdbId(Int32)
   at NzbDrone.Core.Movies.MovieService.MovieExists(NzbDrone.Core.Movies.Movie)
   at NzbDrone.Core.NetImport.NetImportSearchService.<Execute>b__13_1(NzbDrone.Core.Movies.Movie)
   at System.Linq.Enumerable+WhereListIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Linq.Enumerable.ToList[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at NzbDrone.Core.NetImport.NetImportSearchService.Execute(NzbDrone.Core.NetImport.NetImportSyncCommand)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon, NzbDrone.Core.Messaging.Commands.CommandModel)
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, NzbDrone.Core.Messaging.Commands.CommandExecutor, System.Object, NzbDrone.Core.Messaging.Commands.CommandModel)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Runtime.CompilerServices.CallSite, System.__Canon, System.__Canon, System.__Canon)
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, NzbDrone.Core.Messaging.Commands.CommandExecutor, System.Object, NzbDrone.Core.Messaging.Commands.CommandModel)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Faulting application name: radarr.console.exe, version: 0.2.0.1217, time stamp: 0x5be82d90
Faulting module name: sqlite3.DLL, version: 3.8.7.2, time stamp: 0x546c4371
Exception code: 0xc000001d
Fault offset: 0x0004454f
Faulting process ID: 0x29c0
Faulting application start time: 0x01d4aab2b991a3dd
Faulting application path: C:\ProgramData\Radarr\bin\radarr.console.exe
Faulting module path: C:\ProgramData\Radarr\bin\sqlite3.DLL
Report ID: 74dbc74f-a81e-44ac-b338-deeee0ea81ad
Faulting package full name: 
Faulting package-relative application ID: `

Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program NzbDrone.Host because of this error.

Program: NzbDrone.Host
File: 

The error value is listed in the Additional Data section.
User Action
1. Open the file again. This situation might be a temporary problem that corrects itself when the program runs again.
2. If the file still cannot be accessed and
	- It is on the network, your network administrator should verify that there is not a problem with the network and that the server can be contacted.
	- It is on a removable disk, for example, a floppy disk or CD-ROM, verify that the disk is fully inserted into the computer.
3. Check and repair the file system by running CHKDSK. To run CHKDSK, click Start, click Run, type CMD, and then click OK. At the command prompt, type CHKDSK /F, and then press ENTER.
4. If the problem persists, restore the file from a backup copy.
5. Determine whether other files on the same disk can be opened. If not, the disk might be damaged. If it is a hard disk, contact your administrator or computer hardware vendor for further assistance.

Additional Data
Error value: 00000000
Disk type: 0
```
so about reproducibility i'm not sure since it's just random and without any action from my side so yeah hope can get some answers thanks guys great work anyway :)

**Comment by fryfrog** [comment]
Check the Radarr logs. Is the disk Radarr is on okay?
