### ISSUE TITLE
[MediaCoverService][Poster] corrupted download

### ISSUE THREAD

**Issue by djoole** [Radarr/Radarr#3347]
I often have these errors when fetching the movie poster 👍 

```
19-2-2 15:12:10.4|Info|MediaCoverService|Downloading Poster for [Incredibles 2 (2018)][tt3606756, 260513] http://image.tmdb.org/t/p/original/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg
19-2-2 15:12:10.4|Warn|HttpClient|Failed to get response from: http://image.tmdb.org/t/p/original/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg An exception occurred during a WebClient request.
19-2-2 15:12:10.4|Warn|MediaCoverService|Couldn't download media cover for [Incredibles 2 (2018)][tt3606756, 260513]. An exception occurred during a WebClient request.

[v0.2.0.1217] System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.IOException: Sharing violation on path /usr/local/radarr_config/MediaCover/5/poster.jpg
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <0e06830de9a44394a7e366951eabca52>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean isAsync, System.Boolean anonymous) [0x00000] in <0e06830de9a44394a7e366951eabca52>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access) [0x00000] in <0e06830de9a44394a7e366951eabca52>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess)
  at System.Net.WebClient.DownloadFile (System.Uri address, System.String fileName) [0x00034] in <b3922b7d60404fa9ae645f1fb97f5b6b>:0 
   --- End of inner exception stack trace ---
  at System.Net.WebClient.DownloadFile (System.Uri address, System.String fileName) [0x000ad] in <b3922b7d60404fa9ae645f1fb97f5b6b>:0 
  at System.Net.WebClient.DownloadFile (System.String address, System.String fileName) [0x00016] in <b3922b7d60404fa9ae645f1fb97f5b6b>:0 
  at (wrapper remoting-invoke-with-check) System.Net.WebClient.DownloadFile(string,string)
  at NzbDrone.Common.Http.HttpClient.DownloadFile (System.String url, System.String fileName) [0x0009b] in <b0dfb1df5d9940fab2d0472f71ba7ae7>:0 
  at NzbDrone.Core.MediaCover.MediaCoverService.DownloadCover (NzbDrone.Core.Movies.Movie movie, NzbDrone.Core.MediaCover.MediaCover cover) [0x00045] in <eb6d7ee69d274d0eb2c19e6d87dabfdc>:0 
  at NzbDrone.Core.MediaCover.MediaCoverService.EnsureCovers (NzbDrone.Core.Movies.Movie movie, System.Int32 retried) [0x0004e] in <eb6d7ee69d274d0eb2c19e6d87dabfdc>:0 
```

I end up with a /usr/local/radarr_config/MediaCover/5/poster.jpg file, same size than the one I'd download manually, but it's corrupted.

Using V0.2.0.1217 with Mono 5.10.1.57 on FreeBSD

**Comment by danz1995** [comment]
I am having a similar problem with the cover downloads failing. The "mediacovermap" and other cover related actions are not allowing Radarr to grab from indexer nor confirm downloads. 

In less than 2 days my table log has 9,000+ entries regarding trying to download posters than failing.

I have the most update version of Mono for Windows (OS Win7) with Radarr Ver. 0.2.0.1358.

19-7-9 19:48:26.7|Warn|HttpClient|Failed to get response from: http://image.tmdb.org/t/p/original/KTirnfG6FZLKWbm8Am3EEKmZDx.jpg The operation has timed out
19-7-9 19:48:26.7|Warn|MediaCoverService|Couldn't download media cover for [The Last Emperor (1987)][tt0093389, 746]. The operation has timed out

[v0.2.0.1358] System.Net.WebException: The operation has timed out
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at NzbDrone.Common.Http.HttpClient.DownloadFile(String url, String fileName) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 240
   at NzbDrone.Core.MediaCover.MediaCoverService.DownloadCover(Movie movie, MediaCover cover) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 145
   at NzbDrone.Core.MediaCover.MediaCoverService.EnsureCovers(Movie movie, Int32 retried) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 106

There is no need for me to download metadata like posters, a solution suggest would be to disable getting posters from tmdb.
