### ISSUE TITLE
Error on adding iMDB watchlist (using the preset)

### ISSUE THREAD

**Issue by chris-64** [Radarr/Radarr#3404]
When I go to Settings » Lists » Add list » Radarr Lists » Presets » IMDB List and then add a new list (filling in all necessary fields) I get the error "_Unable to connect to list, check the log for more details_"

I read various bug reports about this, but neither solved my issue. I am using the correct watchlist ID (ls023846868) and have set my list to 'public'.

I should mention: whenever I press the 'Test' or 'Save' button, I get the error and the Folder field, where I specified my movies folder, goes empty.

**Log:** 
19-3-3 17:30:41.2|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details
19-3-3 17:31:29.0|Warn|RadarrLists|Unable to connect to list

[v0.2.0.1293] Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess(NetImportResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 56
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse(NetImportResponse importResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 34
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 115
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 149

**Comment by chris-64** [comment]
Anyone?

**Comment by FabianNL** [comment]
Did you installed the latest update of Radarr? This fixed it for me (just installed it today, still trying to figure it all out...)

**Comment by chris-64** [comment]
hm, I see that I forgot about this one... The issue has been solved, but unfortunately, I can't remember how I solved it eventually. I do remember I had to change something, it was not by updating to a new version.

**Comment by hymerman** [comment]
I'm having this same issue - same error in the log. Can you remember if it was something on the IMDB side or radarr side that you changed? I'm wondering if there's something on my watchlist that radarr is having trouble parsing? It was working up until a few weeks ago and I'm at the latest version (0.2.0.1293)

**Comment by chris-64** [comment]
It was on the Radarr side and had nothing to do with something on the watchlist. It more likely had something to do with the folder(s).

**Comment by hymerman** [comment]
Mine seems to be working now, after fiddling with the URL from some advice from sometime in 2018. Looks like watch list user IDs are fiddly - need to hit 'edit' on the list to get the actual ID to put in the URL.

Strangely though it was definitely working about a month ago, so I don't know if this actually fixed it, or if it was just randomly failing while I was looking at the setting.

**Comment by Krandor1** [comment]
In the last 2-3 days IMDB blocked radarr.  They have implemented a workaround so anything in the past few days is likely related to that.
