### ISSUE TITLE
Error when attempting to add an IMDB watchlist (via Radarr Lists)

### ISSUE THREAD

**Issue by malventano** [Radarr/Radarr#3475]
**Describe the bug**
Error when attempting to add an IMDB watchlist.

**To Reproduce**
- Clean install of Radarr Ver. 0.2.0.1293 develop on Windows 10.
- Settings > Lists > add list > Radarr Lists - Presets - IMDB List > select a folder and replace LISTID with an IMDB watchlist (e.g. /imdb/list?listId=ur101382163 ). The example list contains one title.
- Confirm API URL set to default of https://api.radarr.video/v2
- Hit test or save and see error thrown.
- *note* A TMDB list can be added without issue on this same installation.

**Expected behavior**
IMDB list should be added without error.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 0.2.0.1293 develop

**Debug Logs**
```
Unable to connect to list: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess(NetImportResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 56
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse(NetImportResponse importResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 34
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 115
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 149
```

**Comment by malventano** [comment]
Note: issue also exists with Ver. 0.2.0.1331 (nightly) and while using the nightly API link (staging.api.radarr.video)

**Comment by galli-leo** [comment]
You need to set your list to public.

**Comment by WilliamStam** [comment]
i get the same issue. im sure its a bug

https://www.imdb.com/list/ls042946306/ <-- shows so it is public

https://api.radarr.video/v2/imdb/list?listId=ls042946306 <-- shows 404 not found


>Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details


>Unable to connect to list: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

>Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
  at Newtonsoft.Json.JsonTextReader.ParseValue () [0x002c2] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.JsonTextReader.ReadInternal () [0x00043] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.JsonTextReader.Read () [0x00007] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x0003d] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000dd] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00057] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value) [0x00000] in <5e099fb6434a463a960f4009caf8abae>:0 
  at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess (NzbDrone.Core.NetImport.NetImportResponse indexerResponse) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:56 
  at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse (NzbDrone.Core.NetImport.NetImportResponse importResponse) [0x0000d] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:34 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].FetchPage (NzbDrone.Core.NetImport.NetImportRequest request, NzbDrone.Core.NetImport.IParseNetImportResponse parser) [0x00008] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:115 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:150 


docker container via docker compose:
>  radarr:
      image: linuxserver/radarr
      container_name: radarr
      volumes:
         - /storage.config/radarr:/config
         - /storage/movies:/movies
         - /storage/downloads:/downloads
      ports:
         - 8092:7878
      environment:
         - PUID=${PUID}
         - PGID=${PGID}
         - TZ=${TZ}
