### ISSUE TITLE
Radarr API down 

### ISSUE THREAD

**Issue by MadDemonoide** [Radarr/Radarr#3504]
**Describe the bug**
Internal server error 500 on the web page of the API request, and no response at all at http://api.radarr.video/v2/

An error occurred while processing feed. https://api.radarr.video/v2/imdb/list?listId=XXXXXXXXX: Error while calling api: Internal Server Error
Full error(s): Internal Server Error (500, RayId: ad69fe14-99a5-484c-88f1-b0f736b0bde5), Details: An error has occurred and this resource cannot be displayed.

NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Internal Server Error
Full error(s): Internal Server Error (500, RayId: ad69fe14-99a5-484c-88f1-b0f736b0bde5), Details: An error has occurred and this resource cannot be displayed.
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess(NetImportResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 60
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse(NetImportResponse importResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 34
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 115
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchMovies(NetImportPageableRequestChain pageableRequestChain, Boolean isRecent) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 63

**Comment by galli-leo** [comment]
Yes, IMDB blocked our API server, I am currently looking into other options.

**Comment by cephalopodsquid** [comment]
Would it be possible to offer people instructions to package/run the API themselves perhaps?

**Comment by galli-leo** [comment]
@cephalopodsquid https://github.com/Radarr/RadarrAPI.TMDB

**Comment by cephalopodsquid** [comment]
> @cephalopodsquid https://github.com/Radarr/RadarrAPI.TMDB

Thanks but I can't see instructions there... and without them I'm guessing its (Laravel Homestead and pre-reqs) from this:  https://github.com/cloudcreativity/demo-laravel-json-api

**Comment by galli-leo** [comment]
It's back up again.

**Comment by galli-leo** [comment]
@cephalopodsquid Well we are currently in the process of rewriting it anyways. But yeah it's laravel based atm.
