### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Buri** [Radarr/Radarr#3527]
**Describe the bug**
Adding torznab indexer from jackett fails on indexer test

**To Reproduce**
1. Go to Add indexer
2. Fill in form
3. Initial test fails

**Expected behavior**
Indexer is added

**Desktop (please complete the following information):**
 - OS: linux (docker container)
Version
    0.2.0.1349
Mono Version
    5.20.1.19
AppData directory
    /config
Startup directory
    /opt/radarr
Mode
    Console

**Debug Logs**
[Trace] Http: Req: 99 [POST] /api/v2/indexer/test
[Trace] RadarrErrorPipeline: Handling Exception
[Fatal] RadarrErrorPipeline: Request Failed. POST /api/v2/indexer/test

[v0.2.0.1349] System.NullReferenceException: Object reference not set to an instance of an object
  at Radarr.Http.ClientSchema.SchemaBuilder+<>c.<GetValueConverter>b__8_6 (System.Object fieldValue) [0x00000] in C:\projects\radarr-usby1\src\Radarr.Http\ClientSchema\SchemaBuilder.cs:184
  at Radarr.Http.ClientSchema.SchemaBuilder+<>c__DisplayClass5_2.<GetFieldMapping>b__2 (System.Object t, System.Object v) [0x00000] in C:\projects\radarr-usby1\src\Radarr.Http\ClientSchema\SchemaBuilder.cs:119
  at Radarr.Http.ClientSchema.SchemaBuilder.ReadFromSchema (System.Collections.Generic.List`1[T] fields, System.Type targetType) [0x00096] in C:\projects\radarr-usby1\src\Radarr.Http\ClientSchema\SchemaBuilder.cs:49
  at Radarr.Api.V2.ProviderResourceMapper`2[TProviderResource,TProviderDefinition].ToModel (TProviderResource resource) [0x000c8] in C:\projects\radarr-usby1\src\Radarr.Api.V2\ProviderResource.cs:65
  at Radarr.Api.V2.Indexers.IndexerResourceMapper.ToModel (Radarr.Api.V2.Indexers.IndexerResource resource) [0x00005] in C:\projects\radarr-usby1\src\Radarr.Api.V2\Indexers\IndexerResource.cs:35
  at Radarr.Api.V2.ProviderModuleBase`3[TProviderResource,TProvider,TProviderDefinition].GetDefinition (TProviderResource providerResource, System.Boolean includeWarnings, System.Boolean validate) [0x00000] in C:\projects\radarr-usby1\src\Radarr.Api.V2\ProviderModuleBase.cs:100
  at Radarr.Api.V2.ProviderModuleBase`3[TProviderResource,TProvider,TProviderDefinition].Test (TProviderResource providerResource) [0x00000] in C:\projects\radarr-usby1\src\Radarr.Api.V2\ProviderModuleBase.cs:141
  at Radarr.Api.V2.ProviderModuleBase`3[TProviderResource,TProvider,TProviderDefinition].<.ctor>b__2_1 (System.Object x) [0x00000] in C:\projects\radarr-usby1\src\Radarr.Api.V2\ProviderModuleBase.cs:30
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <bb3027f50b35411088f45475912cc2ff>:0

[Trace] Http: Res: 99 [POST] /api/v2/indexer/test: 500.InternalServerError (39 ms)
[Debug] Api: [POST] /api/v2/indexer/test: 500.InternalServerError (39 ms)

**Comment by guim31** [comment]
I'm facing the same issue since few days.
Search in the Jackett interface works great, but won't work when I add it to radarr (the test is looping forever)

**Comment by Buri** [comment]
Also, Jackett version is  0.11.348.0

**Comment by rkmfl** [comment]
Yes, I get the same thing, ever since the 0.2.0.1344 update on 2019-05-05
```
Couldn't process release.: Object reference not set to an instance of an object.

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.CustomFormats.FormatTag.DoesItMatchWithoutMods(ParsedMovieInfo movieInfo) in C:\projects\radarr-usby1\src\NzbDrone.Core\CustomFormats\FormatTag.cs:line 74
   at NzbDrone.Core.CustomFormats.FormatTag.DoesItMatch(ParsedMovieInfo movieInfo) in C:\projects\radarr-usby1\src\NzbDrone.Core\CustomFormats\FormatTag.cs:line 43
   at NzbDrone.Core.Parser.ParsingService.<>c__DisplayClass13_0.<MatchFormatTags>b__3(FormatTag t) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 166
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at NzbDrone.Core.Parser.ParsingService.<>c__DisplayClass13_0.<MatchFormatTags>b__1(IGrouping`2 g) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 166
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Parser.ParsingService.MatchFormatTags(ParsedMovieInfo movieInfo) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 165
   at NzbDrone.Core.Parser.ParsingService.ParseCustomFormat(ParsedMovieInfo movieInfo) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 147
   at NzbDrone.Core.Parser.ParsingService.EnhanceMinimalInfo(ParsedMovieInfo minimalInfo, List`1 helpers) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 95
   at NzbDrone.Core.Parser.ParsingService.ParseMovieInfo(String title, List`1 helpers) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 74
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.<GetMovieDecisions>d__8.MoveNext() in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 73
```

I have also uninstalled and re-installed as a fresh copy of Radarr, with same issues.

Since then I've moved to another system and installed Radarr, then copied over my settings, same issues.

https://github.com/Radarr/Radarr/issues/3525

**Comment by 1990clb** [comment]
Has anyone found a workaround for this issue? Got everything set up but can't add any indexers.

**Comment by rkmfl** [comment]
@1990clb - Are you saying that you receive the "**Couldn't process release.: Object reference not set to an instance of an object**." error, or something else?  Or can you paste your specific error?

**Comment by 1990clb** [comment]
Sorry, I should have been more descriptive. I'm having the same issue as reported by Buri, when adding torznab as an indexer I receive the error:

```
[v0.2.0.1349] System.NullReferenceException: Object reference not set to an instance of an object
  at Radarr.Http.ClientSchema.SchemaBuilder+<>c.<GetValueConverter>b__8_6 (System.Object fieldValue) [0x00000] in C:\projects\radarr-usby1\src\Radarr.Http\ClientSchema\SchemaBuilder.cs:184 
  at Radarr.Http.ClientSchema.SchemaBuilder+<>c__DisplayClass5_2.<GetFieldMapping>b__2 (System.Object t, System.Object v) [0x00000] in C:\projects\radarr-usby1\src\Radarr.Http\ClientSchema\SchemaBuilder.cs:119 
  at Radarr.Http.ClientSchema.SchemaBuilder.ReadFromSchema (System.Collections.Generic.List`1[T] fields, System.Type targetType) [0x00096] in C:\projects\radarr-usby1\src\Radarr.Http\ClientSchema\SchemaBuilder.cs:49 
  at Radarr.Api.V2.ProviderResourceMapper`2[TProviderResource,TProviderDefinition].ToModel (TProviderResource resource) [0x000c8] in C:\projects\radarr-usby1\src\Radarr.Api.V2\ProviderResource.cs:65 
  at Radarr.Api.V2.Indexers.IndexerResourceMapper.ToModel (Radarr.Api.V2.Indexers.IndexerResource resource) [0x00005] in C:\projects\radarr-usby1\src\Radarr.Api.V2\Indexers\IndexerResource.cs:35 
  at Radarr.Api.V2.ProviderModuleBase`3[TProviderResource,TProvider,TProviderDefinition].GetDefinition (TProviderResource providerResource, System.Boolean includeWarnings, System.Boolean validate) [0x00000] in C:\projects\radarr-usby1\src\Radarr.Api.V2\ProviderModuleBase.cs:100 
  at Radarr.Api.V2.ProviderModuleBase`3[TProviderResource,TProvider,TProviderDefinition].Test (TProviderResource providerResource) [0x00000] in C:\projects\radarr-usby1\src\Radarr.Api.V2\ProviderModuleBase.cs:141 
  at Radarr.Api.V2.ProviderModuleBase`3[TProviderResource,TProvider,TProviderDefinition].<.ctor>b__2_1 (System.Object x) [0x00000] in C:\projects\radarr-usby1\src\Radarr.Api.V2\ProviderModuleBase.cs:30 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <bb3027f50b35411088f45475912cc2ff>:0 
```

**Comment by galli-leo** [comment]
Where did you guys get this version from? Did Radarr auto update to this version itself? The version you are running on is a non supported experimental branch.

**Comment by 1990clb** [comment]
Not sure about others but I installed it from here using the "preview" tag.
https://hub.docker.com/r/linuxserver/radarr

**Comment by Buri** [comment]
Yeah, the same

**Comment by galli-leo** [comment]
Well then that’s expected

**Comment by 1990clb** [comment]
Where can we report issues with the "preview" version?

**Comment by rkmfl** [comment]
@1990clb - 
To clarify, @galli-leo (the primary dev) is saying that your fix will be switching to a supported version.

To do this, go to:
**Settings > General > Updates : Branch**

You've got a few options you can enter here, any of them will work as long as you remove "preview".

The popular choice is "**develop**" (for more frequent release but possibly less stable).  I believe the other options are likely "**master**" (more stable/less frequent) or "**prod**" (production - likely same as master for Radarr).

Once you change that, make sure to update and confirm you are on the May 5th release (Click "System > About" see "Version" which should be **0.2.0.1344** for the "develop" track.

**Comment by Buri** [comment]
Well, this is all nice, but this bug still needs to be solved in the future if this version is ever to be going live. Dont get me wrong, this is not a support request ticket, this is a bug report and I don't believe that "switch to stable version" is correct resolution.
