### ISSUE TITLE
Radarr crashing on startup. NLog related?  

### ISSUE THREAD

**Issue by cmosek** [Radarr/Radarr#3553]
**Describe the bug**
Radarr is not able to start successfully. 
Basic stuff already checked on Discord with @fryfrog 

**To Reproduce**
```
sudo -u radarr /usr/bin/mono  /opt/Radarr/Radarr.exe -nobrowser -data=/var/lib/radarr/ 


Press enter to exit...
```

**Expected behavior**
Radarr starts

**Desktop:**
 - OS: CentOS 7 as a LXC container on Proxmox 
 - Mono Version: 5.20.1, tried also 6.0.0
 - Version: 0.2.0.1344

```$ mono --version
Mono JIT compiler version 6.0.0.274 (tarball Sat Jun  1 08:49:56 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```
Sonarr is being run in the same container, without the issues.

**Debug Logs**
Full logs, mono run with `--trace` (gziped) https://we.tl/t-xK5Y0NizWn
Mono run with strace https://pastebin.com/dzEV7iJG
Install directory dump https://pastebin.com/VSDYUz97

**Some snippets**

```
=================================================================
        Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
/proc/self/maps:
00400000-00878000 r-xp 00000000 fd:14 7912                               /usr/bin/mono-sgen
00a77000-00a7f000 r--p 00477000 fd:14 7912                               /usr/bin/mono-sgen
00a7f000-00a83000 rw-p 0047f000 fd:14 7912                               /usr/bin/mono-sgen
00a83000-00a9b000 rw-p 00000000 00:00 0 
02629000-02f7a000 rw-p 00000000 00:00 0                                  [heap]
413aa000-413ba000 rwxp 00000000 00:00 0 
41879000-41959000 rwxp 00000000 00:00 0 
7fbdd8000000-7fbdd8021000 rw-p 00000000 00:00 0 
7fbdd8021000-7fbddc000000 ---p 00000000 00:00 0 
7fbddd8a3000-7fbddda00000 r--p 00000000 fd:14 131282                     /usr/lib/mono/gac/System.ServiceModel/4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
7fbddda00000-7fbdddb00000 rw-p 00000000 00:00 0 
7fbdddb14000-7fbdddbf8000 r--p 00000000 fd:14 7769                       /usr/lib/mono/gac/System.Runtime.Serialization/4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
7fbdddbf8000-7fbdddc45000 r--p 00000000 fd:14 131499                     /usr/lib/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed756/Mono.Security.dll
7fbdddc45000-7fbdddc52000 r-xp 00000000 fd:14 8022                       /usr/lib64/libmono-native.so.0.0.0
7fbdddc52000-7fbddde51000 ---p 0000d000 fd:14 8022                       /usr/lib64/libmono-native.so.0.0.0
7fbddde51000-7fbddde52000 r--p 0000c000 fd:14 8022                       /usr/lib64/libmono-native.so.0.0.0
7fbddde52000-7fbddde53000 rw-p 0000d000 fd:14 8022                       /usr/lib64/libmono-native.so.0.0.0
7fbddde53000-7fbdde15a000 r--p 00000000 fd:14 131609                     /usr/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll
7fbdde15a000-7fbdde25f000 r--p 00000000 fd:14 133070                     /usr/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll
7fbdde25f000-7fbdde4db000 r--p 00000000 fd:14 133082                     /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
7fbdde4db000-7fbdded79000 r-xp 00000000 fd:14 8008                       /usr/lib/mono/4.5/mscorlib.dll.so
7fbdded79000-7fbddef79000 ---p 0089e000 fd:14 8008                       /usr/lib/mono/4.5/mscorlib.dll.so
7fbddef79000-7fbddef7a000 r--p 0089e000 fd:14 8008                       /usr/lib/mono/4.5/mscorlib.dll.so
7fbddef7a000-7fbddef7b000 rw-p 0089f000 fd:14 8008                       /usr/lib/mono/4.5/mscorlib.dll.so
7fbddef7b000-7fbddefa2000 rw-p 00000000 00:00 0 

=================================================================
        Native stacktrace:
=================================================================
        0x523d16 - /usr/bin/mono : (null)
        0x4afb11 - /usr/bin/mono : (null)
        0x51cc90 - /usr/bin/mono : (null)
        0x471bdb - /usr/bin/mono : (null)
        0x26378b0 - Unknown

=================================================================
        Telemetry Dumper:
=================================================================
Pkilling 0x7fbde12cc700 from 0x7fbde2909780
Entering thread summarizer pause from 0x7fbde2909780
Finished thread summarizer pause from 0x7fbde2909780.

Waiting for dumping threads to resume

=================================================================
        External Debugger Dump:
=================================================================
warning: File "/usr/bin/mono-sgen-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".
To enable execution of this file add
        add-auto-load-safe-path /usr/bin/mono-sgen-gdb.py
line to your configuration file "/home/radarr/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/radarr/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
[New LWP 2242]
[New LWP 2241]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007fbde1ec8179 in waitpid () from /lib64/libpthread.so.0
  Id   Target Id         Frame 
  3    Thread 0x7fbde0bff700 (LWP 2241) "SGen worker" 0x00007fbde1ec4965 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  2    Thread 0x7fbde12cc700 (LWP 2242) "Finalizer" 0x00007fbde1ec6adb in do_futex_wait.constprop.1 () from /lib64/libpthread.so.0
* 1    Thread 0x7fbde2909780 (LWP 2240) "mono" 0x00007fbde1ec8179 in waitpid () from /lib64/libpthread.so.0

Thread 3 (Thread 0x7fbde0bff700 (LWP 2241)):
#0  0x00007fbde1ec4965 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000000708363 in thread_func ()
#2  0x00007fbde1ec0dd5 in start_thread () from /lib64/libpthread.so.0
#3  0x00007fbde13caead in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7fbde12cc700 (LWP 2242)):
#0  0x00007fbde1ec6adb in do_futex_wait.constprop.1 () from /lib64/libpthread.so.0
#1  0x00007fbde1ec6b6f in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
#2  0x00007fbde1ec6c0b in sem_wait@@GLIBC_2.2.5 () from /lib64/libpthread.so.0
#3  0x00000000006ab434 in finalizer_thread ()
#4  0x000000000065f14e in start_wrapper ()
#5  0x00007fbde1ec0dd5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fbde13caead in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7fbde2909780 (LWP 2240)):
#0  0x00007fbde1ec8179 in waitpid () from /lib64/libpthread.so.0
#1  0x0000000000523e74 in dump_native_stacktrace.isra.3 ()
#2  0x00000000004afb11 in mono_handle_native_crash ()
#3  0x000000000051cc90 in altstack_handle_and_restore ()
#4  0x0000000000471bdb in mono_trace_enter_method ()
#5  0x00000000026378b0 in ?? ()
#6  0x0000000000000000 in ?? ()
[0x7fbde2909780: 13.83683 18] ENTER: NLog.Internal.Fakeables.AppDomainWrapper:OnProcessExit (object,System.EventArgs)(this:0x7fbde0c0a020[NLog.Internal.Fakeables.AppDomainWrapper Radarr.exe], Aborted
```

```
EXCEPTION handling: System.BadImageFormatException: Cannot box IsByRefLike type 'System.ReadOnlySpan`1'
EXCEPTION: catch found at clause 2 of System.Reflection.RuntimeMethodInfo:Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo)
EXCEPTION handling: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
EXCEPTION: catch found at clause 0 of NLog.Internal.PropertyHelper:SetPropertyFromString (object,string,string,NLog.Config.ConfigurationItemFactory)
EXCEPTION handling: NLog.NLogConfigurationException: Error when setting property 'Format' on Layout Renderer: ${exception}
EXCEPTION: catch found at clause 1 of NzbDrone.Console.ConsoleApp:Main (string[])
```

Tried to set `/home/radarr/.gdbinit`, but it seems it is not picked up. 

Let me know if you need anything else.

**Comment by galli-leo** [comment]
Make sure you downloaded the linux version. Also this is not something we can fix, since mono is crashing. That looks like a mono bug

**Comment by cmosek** [comment]
Looks like it is crashing when executing Radarr code...
