### ISSUE TITLE
Manual Import not Overwriting

### ISSUE THREAD

**Issue by rterblanche** [Radarr/Radarr#360]
When I manually import a movie that's shown in my Queue as downloaded , it doesn't want to overwrite the current file. I downloaded a better quality.

System.IO.IOException: Destination already exists [D:\Movies\Coin Heist (2017)\Coin Heist (2017) HDTV-720p.mkv]
   at NzbDrone.Common.Disk.DiskTransferService.ClearTargetPath(String targetPath, Boolean overwrite) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 331
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 244
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 183
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 117
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 77
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile episodeFile, LocalMovie localEpisode, Boolean copyOnly) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 67
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:line 103

**Comment by Rusk85** [comment]
Just tested this on Version `Radarr Ver. 0.1.0.35340/develop` (that version can't be right, no? I am running from my fork locally of off develop which I just updated today with the latest commits)
Either way I downloaded `Sing (2016)` with `SD` profile, then set to `Any` profile and added `Sing (2016) Bluray-1080p` to my drone factory. Old movie was immediately deleted and the new one with the better version imported.
Guess nothing to fix here or am I missing something?

**Comment by galli-leo** [comment]
@Rusk85 That's just the version when you manually compile it on your machine. We patch the assembly info to say the correct version on appveyor.

**Comment by galli-leo** [comment]
There seem to be moments where movie files don't want to be deleted, but I don't exactly know why or where yet.

**Comment by galli-leo** [comment]
This is probably related to #657. If you experience this issue please check if Radarr know about the file you already have. If not, please post to #657.
