### ISSUE TITLE
Media Cover Mapper and Media Cover Service repeating non-stop

### ISSUE THREAD

**Issue by danz1995** [Radarr/Radarr#3618]
I am having a problem with the media cover downloads failing and don't quitting, that is preventing Radarr from running.

 The "Media Cover Mapper" and "Media Cover Service" won't allow Radarr to grab from indexer nor confirm/rename downloads after I tried to bulk add some movies (less than 50 movies). 

In less than one week my table log has 25,000+ entries, most of them like the ones below, showing Radarr trying to download posters then failling.

At first, it began with repetitive messages like these ones:

```
19-7-9 19:48:26.7|Warn|MediaCoverService|Couldn't download media cover for [The Last Emperor (1987)][tt0093389, 746]. The operation has timed out

[v0.2.0.1358] System.Net.WebException: The operation has timed out
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at NzbDrone.Common.Http.HttpClient.DownloadFile(String url, String fileName) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 240
   at NzbDrone.Core.MediaCover.MediaCoverService.DownloadCover(Movie movie, MediaCover cover) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 145
   at NzbDrone.Core.MediaCover.MediaCoverService.EnsureCovers(Movie movie, Int32 retried) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 145
```

Then just tons of these:

```
19-7-11 22:31:16.8|Warn|MediaCoverService|Couldn't download media cover even after retrying five times :(.

[v0.2.0.1358] System.Net.WebException: The operation has timed out
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at NzbDrone.Common.Http.HttpClient.DownloadFile(String url, String fileName) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 240
   at NzbDrone.Core.MediaCover.MediaCoverService.DownloadCover(Movie movie, MediaCover cover) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 145
   at NzbDrone.Core.MediaCover.MediaCoverService.EnsureCovers(Movie movie, Int32 retried) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 106

19-7-11 22:31:16.8|Info|MediaCoverService|Downloading Fanart for [Midsommar (2019)][tt8772262, 530385] http://image.tmdb.org/t/p/original/reU8qaO848nkCay7WPtJcdi61p5.jpg
19-7-11 22:32:56.1|Warn|HttpClient|Failed to get response from: http://image.tmdb.org/t/p/original/tmM78qRhpg0i2Cky8Q8hXKASOXY.jpg The operation has timed out
19-7-11 22:32:56.1|Warn|MediaCoverService|Couldn't download media cover for [Little (2019)][tt8085790, 526050]. The operation has timed out

[v0.2.0.1358] System.Net.WebException: The operation has timed out
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at NzbDrone.Common.Http.HttpClient.DownloadFile(String url, String fileName) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 240
   at NzbDrone.Core.MediaCover.MediaCoverService.DownloadCover(Movie movie, MediaCover cover) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 145
   at NzbDrone.Core.MediaCover.MediaCoverService.EnsureCovers(Movie movie, Int32 retried) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 106

19-7-11 22:32:56.1|Warn|MediaCoverService|Couldn't download media cover even after retrying five times :(.

[v0.2.0.1358] System.Net.WebException: The operation has timed out
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at NzbDrone.Common.Http.HttpClient.DownloadFile(String url, String fileName) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 240
   at NzbDrone.Core.MediaCover.MediaCoverService.DownloadCover(Movie movie, MediaCover cover) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 145
   at NzbDrone.Core.MediaCover.MediaCoverService.EnsureCovers(Movie movie, Int32 retried) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 106

19-7-11 22:32:56.1|Info|MediaCoverService|Downloading Fanart for [Little (2019)][tt8085790, 526050] http://image.tmdb.org/t/p/original/tmM78qRhpg0i2Cky8Q8hXKASOXY.jpg
19-7-11 22:32:56.6|Warn|HttpClient|Failed to get response from: http://image.tmdb.org/t/p/original/2FYzxgLNuNVwncilzUeCGbOQzP7.jpg The operation has timed out
19-7-11 22:32:56.6|Warn|MediaCoverService|Couldn't download media cover for [Men in Black: International (2019)][tt2283336, 479455]. The operation has timed out

[v0.2.0.1358] System.Net.WebException: The operation has timed out
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at NzbDrone.Common.Http.HttpClient.DownloadFile(String url, String fileName) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 240
   at NzbDrone.Core.MediaCover.MediaCoverService.DownloadCover(Movie movie, MediaCover cover) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 145
   at NzbDrone.Core.MediaCover.MediaCoverService.EnsureCovers(Movie movie, Int32 retried) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 106

19-7-11 22:32:56.6|Warn|MediaCoverService|Couldn't download media cover even after retrying five times :(.

[v0.2.0.1358] System.Net.WebException: The operation has timed out
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at NzbDrone.Common.Http.HttpClient.DownloadFile(String url, String fileName) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 240
   at NzbDrone.Core.MediaCover.MediaCoverService.DownloadCover(Movie movie, MediaCover cover) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 145
   at NzbDrone.Core.MediaCover.MediaCoverService.EnsureCovers(Movie movie, Int32 retried) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 106

19-7-11 22:32:56.6|Info|MediaCoverService|Downloading Fanart for [Men in Black: International (2019)][tt2283336, 479455] http://image.tmdb.org/t/p/original/2FYzxgLNuNVwncilzUeCGbOQzP7.jpg
19-7-11 22:32:56.8|Warn|HttpClient|Failed to get response from: http://image.tmdb.org/t/p/original/reU8qaO848nkCay7WPtJcdi61p5.jpg The operation has timed out
19-7-11 22:32:56.8|Warn|MediaCoverService|Couldn't download media cover for [Midsommar (2019)][tt8772262, 530385]. The operation has timed out

[v0.2.0.1358] System.Net.WebException: The operation has timed out
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at NzbDrone.Common.Http.HttpClient.DownloadFile(String url, String fileName) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 240
   at NzbDrone.Core.MediaCover.MediaCoverService.DownloadCover(Movie movie, MediaCover cover) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 145
   at NzbDrone.Core.MediaCover.MediaCoverService.EnsureCovers(Movie movie, Int32 retried) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 106

19-7-11 22:32:56.8|Warn|MediaCoverService|Couldn't download media cover even after retrying five times :(.

[v0.2.0.1358] System.Net.WebException: The operation has timed out
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at NzbDrone.Common.Http.HttpClient.DownloadFile(String url, String fileName) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 240
   at NzbDrone.Core.MediaCover.MediaCoverService.DownloadCover(Movie movie, MediaCover cover) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 145
   at NzbDrone.Core.MediaCover.MediaCoverService.EnsureCovers(Movie movie, Int32 retried) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 106
```

It just won't stop, even when it fails it tries again eventually and then fails again and again...

Since I use Plex, there is no need for me to download posters as metadata through Radarr, a suggested solution would be to disable getting posters from tmdb. 

I have the most updated version of Mono for Windows (OS Win7), Mono version is 5.20.1.19 and Radarr Ver. 0.2.0.1358.

**Comment by fryfrog** [comment]
An example URL from your error log `http://image.tmdb.org/t/p/original/2FYzxgLNuNVwncilzUeCGbOQzP7.jpg` works fine for me. I think you need to figure out why it isn't working on your system. They're for Radarr, not the metadata. Also, Windows doesn't use Mono. What are you doing?

**Comment by danz1995** [comment]
The URL is working, though the program will not complete poster downloads and just keep on searching. I downloaded a Mono version for Windows (that currently exists on their website) thinking it could provide a solution.

**Comment by fryfrog** [comment]
So why can't *Radarr* download that file?

Have you installed the normal .NET Windows version? That is what you should run on Windows. I didn't even realize you could install Mono on Windows.

I think you need support, hop on Discord some time.

**Comment by danz1995** [comment]
Sorry for not following this up earlier, I just downgraded to another version of .NET and everything is working fine. Thanks!
