### ISSUE TITLE
[Error] CommandExecutor: Error occurred while executing task RefreshMovie

### ISSUE THREAD

**Issue by tatsumasagc** [Radarr/Radarr#3682]
**Describe the bug**
When Trying to add a new movie or update an existing movie is get the error below

Message: 
`Error occurred while executing task RefreshMovie: Unexpected character encountered while parsing value: b. Path '', line 0, position 0.`

Exception:
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: b. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in C:\projects\radarr-usby1\src\NzbDrone.Common\Serializer\Json.cs:line 37
   at NzbDrone.Common.Http.HttpResponse`1..ctor(HttpResponse response) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpResponse.cs:line 97
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 257
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieInfo(Int32 TmdbId, Profile profile, Boolean hasPreDBEntry) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 71
   at NzbDrone.Core.Movies.RefreshMovieService.RefreshMovieInfo(Movie movie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Movies\RefreshMovieService.cs:line 64
   at NzbDrone.Core.Movies.RefreshMovieService.Execute(RefreshMovieCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\Movies\RefreshMovieService.cs:line 177
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 93
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 43
```

**To Reproduce**
1. Go to an Existing Movie
2. Click on 'Update Movie Info and Scan Disk' button
3. Failed Message pops up at the bottom
4. See error in Logs

**Expected behavior**
Update the movie info and scan the disk for files

**Desktop:**
 - OS: Windows 10.0.17763.475
 - Radarr Version: 0.2.0.1358

**Comment by tatsumasagc** [comment]
hmmm, seems to have fixed itself

**Comment by TheFiZi** [comment]
I had the exact same error:

```Error occurred while executing task RefreshMovie: Unexpected character encountered while parsing value: b. Path '', line 0, position 0.```

```Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: b. Path '', line 0, position 0.
  at Newtonsoft.Json.JsonTextReader.ParseValue () [0x002c2] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.JsonTextReader.ReadInternal () [0x00043] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.JsonTextReader.Read () [0x00007] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x0003d] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x00029] in <5e099fb6434a463a960f4009caf8abae>:0 ```

Since you said "it fixed itself" on a hunch I reloaded Radarr and the issue did correct itself.

Leaving this here for the next person.
