### ISSUE TITLE
Unable to search new movies

### ISSUE THREAD

**Issue by waynemillskidals** [Radarr/Radarr#3689]
Radarr has been operating perfectly fine for a year on windows machine without issues but recently it has stopped being able to search with following error

**If the movie title contains non-alphanumeric characters try removing them, otherwise try your search again later.**

Radarr log details

```
Log file says this

Request Failed: Unexpected character encountered while parsing value: b. Path '', line 0, position 0.


Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: b. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in C:\projects\radarr-usby1\src\NzbDrone.Common\Serializer\Json.cs:line 37
   at NzbDrone.Common.Http.HttpResponse`1..ctor(HttpResponse response) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpResponse.cs:line 97
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 257
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 503
   at NzbDrone.Api.Movies.MovieLookupModule.Search() in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\MovieLookupModule.cs:line 48
   at NzbDrone.Api.Movies.MovieLookupModule.<.ctor>b__2_0(Object x) in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\MovieLookupModule.cs:line 22
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

**Comment by drashna** [comment]
Experiencing this exact same issue, too.  But I suspect that this is related to #3504.

**Comment by dkobelak** [comment]
I have the same problem as of today.. 

Version 0.2.0.1358
Mono Version 5.18.1.0

**Comment by waynemillskidals** [comment]
ok at least its not just me then ...

**Comment by delize** [comment]
Also experiencing this:

```
Version
0.2.0.1358
Mono Version
6.0.0.319 (tarball Mon Aug 12 23:46:26 UTC 2019)
AppData directory
/var/lib/radarr/.config/Radarr
Startup directory
/opt/Radarr
```


```
19-8-14 13:25:26.3|Info|Bootstrap|Starting Radarr - /opt/Radarr/Radarr.exe - Version 0.2.0.1358
19-8-14 13:25:26.8|Info|Router|Application mode: Interactive
19-8-14 13:25:27.0|Info|MigrationLogger|*** Migrating data source=/var/lib/radarr/.config/Radarr/nzbdrone.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
19-8-14 13:25:27.2|Info|MigrationLogger|*** Migrating data source=/var/lib/radarr/.config/Radarr/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
19-8-14 13:25:27.2|Info|OwinHostController|Listening on the following URLs:
19-8-14 13:25:27.2|Info|OwinHostController|  http://*:7878/radarr/
19-8-14 13:25:27.2|Info|OwinHostController|  http://*:7878/
19-8-14 13:25:27.3|Info|NancyBootstrapper|Starting NzbDrone API
19-8-14 13:25:28.1|Info|CommandExecutor|Starting 2 threads for tasks.
19-8-14 13:25:40.6|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.1358] Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: b. Path '', line 0, position 0.
  at Newtonsoft.Json.JsonTextReader.ParseValue () [0x002c2] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.JsonTextReader.ReadInternal () [0x00043] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.JsonTextReader.Read () [0x00007] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x0003d] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000dd] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00057] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <5e099fb6434a463a960f4009caf8abae>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <5e099fb6434a463a960f4009caf8abae>:0 
  at NzbDrone.Common.Serializer.Json.Deserialize[T] (System.String json) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Common\Serializer\Json.cs:37 
  at NzbDrone.Common.Http.HttpResponse`1[T]..ctor (NzbDrone.Common.Http.HttpResponse response) [0x0001e] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpResponse.cs:99 
  at NzbDrone.Common.Http.HttpClient.Get[T] (NzbDrone.Common.Http.HttpRequest request) [0x00007] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:258 
  at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie (System.String title) [0x00275] in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:503 
  at NzbDrone.Api.Movies.MovieLookupModule.Search () [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\MovieLookupModule.cs:48 
  at NzbDrone.Api.Movies.MovieLookupModule.<.ctor>b__2_0 (System.Object x) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\MovieLookupModule.cs:22 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 

```

**Comment by drashna** [comment]
For the record,  I'm using:
 
Version
0.2.0.1391
On Windows Server 2012R2 Essentials.

**Comment by AntaeusNar** [comment]
Same issue here, I'm using

`Version    0.2.0.1358`
`Mono Version
    6.0.0.313 (tarball Sun Jul 14 09:57:59 UTC 2019)`
 `Ubuntu 18.04.3 LTS (GNU/Linux 4.15.18-14-pve x86_64)`

**Comment by bigjohns97** [comment]
Same here

Version
0.2.0.1358

Windows 10

**Comment by nomad007-2019** [comment]
I also have the same issue.  Was working fine a couple of days ago.

Version 0.2.0.1358
Windows 10

**Comment by s0mm3rb** [comment]
same here
started today
only imdb:ttxxxx is possible
any other search results in the same error
nothing changed since yesterday

**Comment by systemmonkey42** [comment]
Radarr (like Sonarr and others) uses something called SkyHookProxy for offloading movie and tv searching.   This issue occurs when the skyhook proxy is down.

This happens occasionally, and its usually back in a few hours.

**Comment by hooah212002** [comment]
I am having the same issue and confirm that searching via imdb:ttxxxx works.

OS: CentOS 7
radarr version: 0.2.0.1358
Mono Version: 6.0.0.319

**Comment by s0mm3rb** [comment]
maybe something at tmdb's api?

**Comment by kennyparsons** [comment]
Same here, except I'm running on docker. 
Radarr Ver. 0.2.0.1358
I posted the full error details here on [gist](https://gist.github.com/kennyparsons/bc05579206cae71621dce1758bb7aad9)

**Comment by Heufneutje** [comment]
I am also getting this exact same exception message in my logs.

**Comment by waynemillskidals** [comment]
This now works so I expect it was an API issue for a brief period?
