### ISSUE TITLE
Issue with Radarr Windows 10 Not searching movies

### ISSUE THREAD

**Issue by itguy1984** [Radarr/Radarr#3691]
When i try to search for a new movie i get this error:

There Was An Error Searching For 'Movie'.
If the movie title contains non-alphanumeric characters try removing them, otherwise try your search again later.

Below is the Error Log:

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: b. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in C:\projects\radarr-usby1\src\NzbDrone.Common\Serializer\Json.cs:line 37
   at NzbDrone.Common.Http.HttpResponse`1..ctor(HttpResponse response) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpResponse.cs:line 97
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 257
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 503
   at NzbDrone.Api.Movies.MovieLookupModule.Search() in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\MovieLookupModule.cs:line 48
   at NzbDrone.Api.Movies.MovieLookupModule.<.ctor>b__2_0(Object x) in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\MovieLookupModule.cs:line 22
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by imzenreally** [comment]
i'm running my radarr on a ubuntu 18.04 box and am having the same issue

**Comment by azza10** [comment]
I too am having this issue. Was working fine approximately 7 hours ago.
Win 10 Ver 1903 Build 18362.295
log:
[v0.2.0.1358] Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: b. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in C:\projects\radarr-usby1\src\NzbDrone.Common\Serializer\Json.cs:line 37
   at NzbDrone.Common.Http.HttpResponse`1..ctor(HttpResponse response) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpResponse.cs:line 97
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 257
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 503
   at NzbDrone.Api.Movies.MovieLookupModule.Search() in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\MovieLookupModule.cs:line 48
   at NzbDrone.Api.Movies.MovieLookupModule.<.ctor>b__2_0(Object x) in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\MovieLookupModule.cs:line 22
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by imzenreally** [comment]
beat me to the punch - was just aboutt o post - thanks

**Comment by ryancrawcour** [comment]
how do you search with IMDb id?

**Comment by imzenreally** [comment]
IMDb:[insert IMDb # - ttXXXXXX]

**Comment by designgears** [comment]
> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: b. Path '', line 0, position 0. (Json snippet **'<--error-->be right back**') --->

**Comment by itguy1984** [comment]
It is back up and working today!  Must of just been the IMDB issue you were talking about.

**Comment by designgears** [comment]
@itguy1984 maybe reopen this or create a new feature request to fall back if one service or the other is down.
