### ISSUE TITLE
Unable to Add Radarr List for IMDB

### ISSUE THREAD

**Issue by EmeraldFlame** [Radarr/Radarr#3804]
**Describe the bug**
When adding a Radarr List to pull in an IMDB list, I just get failures to connect. Have tried multiple lists on IMDB with various settings attach to them

**To Reproduce**
1. Go to Settings->Lists->Add
2. Choose Radarr Lists->Presets->IMDB List
3. Select desired availability, the proper folder, and copy and paste list ID from IMDB so the path to list looks like "/imdb/list?listId=ls#########"
4. Hit test
5. Get error: Unable to connect to list, check the log for more details
6. Logs show the following:
`Unable to connect to list: Error while calling api: Not Found
Full error(s): Not Found (404, RayId: 323021bb-745d-4201-8000-d764bc822c4f), Details: not found
NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Not Found
Full error(s): Not Found (404, RayId: 323021bb-745d-4201-8000-d764bc822c4f), Details: not found
  at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess (NzbDrone.Core.NetImport.NetImportResponse indexerResponse) [0x00029] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:60 
  at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse (NzbDrone.Core.NetImport.NetImportResponse importResponse) [0x0000d] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:34 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].FetchPage (NzbDrone.Core.NetImport.NetImportRequest request, NzbDrone.Core.NetImport.IParseNetImportResponse parser) [0x00008] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:115 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:151 
`

**Expected behavior**
The list gets added instead of failing

**Desktop (please complete the following information):**
 - OS: Linux (Docker)
 - Docker Image: https://hub.docker.com/r/linuxserver/radarr
 - Mono Version 5.20.1.34
 - Radarr Version 0.2.0.1358 

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3694532/radarr.debug.txt)

**Comment by Rouzax** [comment]
I have the same issue.
Tried with different ways as described in: https://github.com/Radarr/Radarr/issues/2330 but can't get it to work.
```
19-10-17 13:54:59.2|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (0 ms)
19-10-17 13:55:06.2|Debug|RadarrLists|Downloading List https://api.radarr.video/v2/imdb/list?listId=ur18921019
19-10-17 13:55:06.6|Warn|RadarrLists|Unable to connect to list

[v0.2.0.1358] NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Not Found
Full error(s): Not Found (404, RayId: 42393d43-0fcc-4e86-8f63-f48d8ff6fa95), Details: not found
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess(NetImportResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 60
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse(NetImportResponse importResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 34
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 113
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 150

19-10-17 13:55:06.7|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details
19-10-17 13:55:06.7|Debug|Api|[POST] /api/netimport/test: 400.BadRequest (468 ms)
19-10-17 13:55:08.6|Debug|RadarrLists|Downloading List https://api.radarr.video/v2/imdb/list?listId=ur18921019
19-10-17 13:55:09.0|Warn|RadarrLists|Unable to connect to list

[v0.2.0.1358] NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Not Found
Full error(s): Not Found (404, RayId: 42393d43-0fcc-4e86-8f63-f48d8ff6fa95), Details: not found
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess(NetImportResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 60
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse(NetImportResponse importResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 34
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 113
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 150

19-10-17 13:55:09.0|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details
19-10-17 13:55:09.0|Debug|Api|[POST] /api/netimport: 400.BadRequest (437 ms)
19-10-17 13:55:14.0|Debug|RadarrLists|Downloading List https://api.radarr.video/v2/imdb/list?listId=ur18921019
19-10-17 13:55:14.4|Warn|RadarrLists|Unable to connect to list

[v0.2.0.1358] NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Not Found
Full error(s): Not Found (404, RayId: 42393d43-0fcc-4e86-8f63-f48d8ff6fa95), Details: not found
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess(NetImportResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 60
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse(NetImportResponse importResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 34
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 113
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 150

19-10-17 13:55:14.4|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details
19-10-17 13:55:14.4|Debug|Api|[POST] /api/netimport: 400.BadRequest (453 ms)
19-10-17 13:55:22.3|Debug|RadarrLists|Downloading List https://api.radarr.video/v2/imdb/list?listId=ur18921019
19-10-17 13:55:22.7|Warn|RadarrLists|Unable to connect to list

[v0.2.0.1358] NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Not Found
Full error(s): Not Found (404, RayId: 42393d43-0fcc-4e86-8f63-f48d8ff6fa95), Details: not found
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess(NetImportResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 60
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse(NetImportResponse importResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 34
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 113
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 150

19-10-17 13:55:22.7|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details
19-10-17 13:55:22.7|Debug|Api|[POST] /api/netimport: 400.BadRequest (468 ms)
19-10-17 13:56:08.0|Debug|RadarrLists|Downloading List https://api.radarr.video/v2/imdb/list?listId=ls074400660
19-10-17 13:56:08.6|Warn|RadarrLists|Unable to connect to list

[v0.2.0.1358] NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Not Found
Full error(s): Not Found (404, RayId: 45c92264-0c7f-4033-ad46-57205c53ff02), Details: not found
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess(NetImportResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 60
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse(NetImportResponse importResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 34
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 113
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 150

19-10-17 13:56:08.6|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details
19-10-17 13:56:08.6|Debug|Api|[POST] /api/netimport/test: 400.BadRequest (562 ms)
19-10-17 13:56:10.3|Debug|RadarrLists|Downloading List https://api.radarr.video/v2/imdb/list?listId=ls074400660
19-10-17 13:56:10.7|Warn|RadarrLists|Unable to connect to list

[v0.2.0.1358] NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Not Found
Full error(s): Not Found (404, RayId: 45c92264-0c7f-4033-ad46-57205c53ff02), Details: not found
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess(NetImportResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 60
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse(NetImportResponse importResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 34
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 113
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 150

19-10-17 13:56:10.7|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details
19-10-17 13:56:10.7|Debug|Api|[POST] /api/netimport: 400.BadRequest (468 ms)
19-10-17 13:56:14.5|Debug|RadarrLists|Downloading List https://api.radarr.video/v2/imdb/list?listId=ls074400660
19-10-17 13:56:14.9|Warn|RadarrLists|Unable to connect to list

[v0.2.0.1358] NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Not Found
Full error(s): Not Found (404, RayId: 45c92264-0c7f-4033-ad46-57205c53ff02), Details: not found
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess(NetImportResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 60
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse(NetImportResponse importResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 34
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 113
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 150

19-10-17 13:56:14.9|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details
19-10-17 13:56:14.9|Debug|Api|[POST] /api/netimport/test: 400.BadRequest (454 ms)
```

**Comment by vertan** [comment]
Just making sure; have you tested making the IMDb lists public? I tried both of your lists for myself, and it did indeed not work, but then again your lists are seemingly non-public when viewing on IMDb as well.

I tried fetching one of my own lists which is public, and it worked like a charm. I would expect the lists have to be public since there's no login method specified in the Add List flow.

**Comment by Rouzax** [comment]
My list was public (deleted it in the meantime), will try it again to be sure and post back when I'm have the chance.

**Comment by EmeraldFlame** [comment]
I tried mine as both public and private, failed either way.

**Comment by vertan** [comment]
Ok! Emerald, could you make the list from your original debug logs public (`ls048084909`)? I need to make certain it's public to continue with debugging.

**Comment by Rouzax** [comment]
This is my test list
https://www.imdb.com/list/ls097585964/

**Comment by EmeraldFlame** [comment]
> Ok! Emerald, could you make the list from your original debug logs public (`ls048084909`)? I need to make certain it's public to continue with debugging.

I've switched it to public, still not working on my end, exact same error and log messages.

**Comment by mikelagase** [comment]
Same error here as well.

**Comment by jandreaucodes** [comment]
I'm just trying Radarr for the first time and am struggling to add my list here, too.

Message from logs:
Unable to connect to list: Error while calling api: Not Found Full error(s): Not Found (404, RayId: 87c961bd-26ab-4ed1-b084-e4045af6c0ae), Details: not found

Error:

```
NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Not Found
Full error(s): Not Found (404, RayId: 87c961bd-26ab-4ed1-b084-e4045af6c0ae), Details: not found
  at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess (NzbDrone.Core.NetImport.NetImportResponse indexerResponse) [0x00029] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:60 
  at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse (NzbDrone.Core.NetImport.NetImportResponse importResponse) [0x0000d] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:34 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].FetchPage (NzbDrone.Core.NetImport.NetImportRequest request, NzbDrone.Core.NetImport.IParseNetImportResponse parser) [0x00008] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:115 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].TestConnection () [0x00
```

**Comment by telans** [comment]
Same here, this should probably be reopened @Qstick

**Comment by EmeraldFlame** [comment]
For those still having issues, I'm OP that opened the ticket. What I found worked for me is I needed to wait some more time physically before attempting to add to Radarr. If I made a new list, or edited the name/settings on an existing list, it'd take 10-15 minutes after each change before Radarr could see the list and work with it.

**Comment by telans** [comment]
I'm trying the IMDb popular list unfortunately.

**Comment by profucius** [comment]
I am having an issue accessing IMDb Watchlist. The list is certainly Public, I can access it via the web browser fine. But Radarr is giving me this error when I try to "Test" on the List add page:

> Unable to connect to indexer. Indexer responded with html content. Site is likely blocked or unavailable.
