### ISSUE TITLE
Failure to connect radarr with qBittorrent because /login page doesn't exist

### ISSUE THREAD

**Issue by dmxt** [Radarr/Radarr#3806]
**Describe the bug**
`127.0.0.1:8089` exists and opens qbittorrent webui just fine. 
But radarr refuses to connect to qbittorrent because it insisted on using `127.0.0.1:8089/login` to connect and I had no way of controlling that. It failed because adding /login to qbittorrent url won't load and return 404 instead.

**To Reproduce w/ Screenshots**
qBittorrent webui settings
![qbittorrent_bcSlqwkDmG](https://user-images.githubusercontent.com/3248782/66271495-8f2ff280-e82c-11e9-9b55-d7f9670750d9.png)
Confirmation that `127.0.0.1:8089` works fine
![qbittorrent_ethYeBnmFN](https://user-images.githubusercontent.com/3248782/66271496-922ae300-e82c-11e9-95c8-306b06817abb.png)
![chrome_D68nX6YL7A](https://user-images.githubusercontent.com/3248782/66271502-9e16a500-e82c-11e9-9a39-b7ac81242f11.png)

radarr error window
![chrome_0NdSBZ1uwX](https://user-images.githubusercontent.com/3248782/66271603-f39f8180-e82d-11e9-8ecc-cbf254b0489e.png)

I got this address off radarr's debug log and of course it returned 404 
![chrome_RC71gukL8W](https://user-images.githubusercontent.com/3248782/66271607-06b25180-e82e-11e9-8e91-f5f257c76bfd.png)

**Required behavior**
1. Make radarr connect qbittorrent via `127.0.0.1:8089`, NOT `127.0.0.1:8089/login`!
2. OR make qbittorrent load `127.0.0.1:8089/login` and not return 404!

**Versions:**
 - OS: Windows 10 64-bit
 - radarr Version 0.2.0.1358
 - qbittorrent v4.2.0alpha2

**Debug Logs**
```
19-10-6 09:59:43.4|Error|QBittorrent|Failed to connect to qBittorrent, please check your settings.

[v0.2.0.1358] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, please check your settings. ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [POST] at [http://localhost:8089/login]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 89
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, QBittorrentSettings settings, Boolean reauthenticate) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 276
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, QBittorrentSettings settings, Boolean reauthenticate) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 286
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 217
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.GetConfig(QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 56
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.GetItems() in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 103

19-10-6 10:01:15.4|Warn|HttpClient|HTTP Error - Res: [POST] http://localhost:8089/login: 404.NotFound
```

**Comment by Qstick** [comment]
Use nightly or downgrade qbit
