### ISSUE TITLE
Radarr fails to start after recent APHRODITE release

### ISSUE THREAD

**Issue by CBers** [Radarr/Radarr#3922]
**Describe the bug**
Radarr running as a Windows service will not start.

**To Reproduce**
1. Go to 'Service'
2. Click on 'Start'
3. See error

**Expected behavior**
From Eventvwr:
```Description: A .NET Core application failed.
Application: Radarr.Console.exe
Path: C:\ProgramData\Radarr\bin\Radarr.Console.exe
Message: Error:
  An assembly specified in the application dependencies manifest (Radarr.Console.deps.json) was not found:
    package: 'runtimepack.Microsoft.AspNetCore.App.Runtime.win-x64', version: '3.0.0'
    path: 'System.Windows.Extensions.dll'
```
From UpdateLog:
```[v2.0.0.2221] System.IO.FileNotFoundException: Could not find file 'C:\WINDOWS\TEMP\radarr_update\Radarr\System.Threading.dll'.
File name: 'C:\WINDOWS\TEMP\radarr_update\Radarr\System.Threading.dll'
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskProviderBase.CopyFile(String source, String destination, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskTransferService.TryCopyFileVerified(String sourcePath, String targetPath, Int64 originalSize)
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode)
   at NzbDrone.Common.Disk.DiskTransferService.MirrorFolder(String sourcePath, String targetPath)
   at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start(String installationFolder, Int32 processId)
```

**Seems to have started happening since the release of 4th Dec 2019.**

**Desktop (please complete the following information):**
 - OS: Windosws 10
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Version [e.g. 22]: "Updating Radarr from version 2.0.0.2200 to version 2.0.0.2221" - from log file.

**Debug Logs**
[2019.12.04-04.21.txt](https://github.com/Radarr/Radarr/files/3927519/2019.12.04-04.21.txt)

I have tried restoring the radarr.db and config.xml files from the backup, but it still fails to start.

**Comment by CBers** [comment]
I have regressed back to NIGHTLY (v0.2.0.1450) for now, but can test with APRODITE if/when needed.

**Comment by fryfrog** [comment]
You can't use the built in updater to go from v0.2 to v2 (well, v3 now). Is that what you tried to do?
