### ISSUE TITLE
Issues when adding new movie - Aphrodite

### ISSUE THREAD

**Issue by mstrdraco** [Radarr/Radarr#4114]
When I add a new Movie to Monitor I get the following error -

CommandExecutor | Error occurred while executing task RefreshMovie: SQL logic error  table Credits has no column named Department | 12:38pm |  
code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error

table Credits has no column named Department

   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)

   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()

   at System.Data.SQLite.SQLiteDataReader.NextResult()

   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)

   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)

   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1060

   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1043

   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 996

   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in d:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 204

   at NzbDrone.Core.Datastore.BasicRepository`1.InsertMany(IList`1 models) in d:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 218

   at NzbDrone.Core.Movies.Credits.CreditService.UpdateCredits(List`1 credits, Movie movie) in d:\a\1\s\src\NzbDrone.Core\Movies\Credits\CreditService.cs:line 82

   at NzbDrone.Core.Movies.RefreshMovieService.RefreshMovieInfo(Movie movie) in d:\a\1\s\src\NzbDrone.Core\Movies\RefreshMovieService.cs:line 142

   at NzbDrone.Core.Movies.RefreshMovieService.Execute(RefreshMovieCommand message) in d:\a\1\s\src\NzbDrone.Core\Movies\RefreshMovieService.cs:line 209

   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 114

   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)

   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44

**To Reproduce**
1. Add a new Movie - It doesn't pull in poster to Movie
2. Try to refresh the Movie by hitting the Refresh Movie button

**Expected behavior**
Should pull in the poster to the new movie and movie details

![RadarrMovie-error](https://user-images.githubusercontent.com/37802459/73562102-67dae200-4428-11ea-9d21-885ee7cbf7c4.jpg)
![RadarrMovieView](https://user-images.githubusercontent.com/37802459/73562103-67dae200-4428-11ea-9c60-7df82e0ca3d4.jpg)
![radarrerrorview](https://user-images.githubusercontent.com/37802459/73562104-67dae200-4428-11ea-8733-a5e2974204f3.jpg)

**Desktop (please complete the following information):**
 - OS: Windows Server 2016
 - Version - 3.0.0.2608

**Comment by ta264** [comment]
Your database is corrupt or you've been playing with test versions and got your database in a broken state. Jump on the discord for support, but you probably need to restore a backup or reimport into a fresh database
