### ISSUE TITLE
ERROR: ExtraService failed while processing [MediaCoversUpdatedEvent]: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by seanvree** [Radarr/Radarr#412]
Running Radarr Ver. 0.2.0.210 (feature/net-import) on Windows. 

Keep getting this error:

Error:  ExtraService failed while processing [MediaCoversUpdatedEvent]: Object reference not set to an instance of an object

System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Extras.ExtraService.Handle(MediaCoversUpdatedEvent message) in C:\projects\radarr-usby1\src\NzbDrone.Core\Extras\ExtraService.cs:line 105
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 5

**Comment by galli-leo** [comment]
That error is harmless and only an artifact of Sonarr :)
