### ISSUE TITLE
[Bug v3] Missing posters?

### ISSUE THREAD

**Issue by casperse** [Radarr/Radarr#4156]
**Describe the bug**
After adding some new movies I see a poster but after adding the movie its blank?
I tried deleting the media covers and refresh but didn't work

Also refresh movie button gives a Failed?

Some covers work others don't?
I am trying to find a pattern? - Could it be movies which is translated in native language?
But to my knowledge you don't set a language in Radarr? I have danish movies that are now named in english only? where Radarr v2 would take the danish title?

```
Refreshing the movie I get af error:
[v3.0.0.2619] code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
UNIQUE constraint failed: AlternativeTitles.CleanTitle
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1060
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1043
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 996
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in d:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 204
   at NzbDrone.Core.Datastore.BasicRepository`1.InsertMany(IList`1 models) in d:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 218
   at NzbDrone.Core.Movies.AlternativeTitles.AlternativeTitleService.UpdateTitles(List`1 titles, Movie movie) in d:\a\1\s\src\NzbDrone.Core\Movies\AlternativeTitles\AlternativeTitleService.cs:line 96
   at NzbDrone.Core.Movies.RefreshMovieService.RefreshMovieInfo(Movie movie) in d:\a\1\s\src\NzbDrone.Core\Movies\RefreshMovieService.cs:line 119

2020-2-15 23:57:20.7|Error|RefreshMovieService|Couldn't refresh info for [Frozen II (2019)][tt4520988, 330457]
```

**To Reproduce**

**Expected behavior**
Download poster after search...

**Screenshots**
[https://ibb.co/0Qg51df.](url)

Version
3.0.0.2619
.NET Core
Yes
Docker
Yes
DB Migration
167
AppData directory
/config
Startup directory
/opt/radarr
Mode
Console

**Comment by Qstick** [comment]
Same root cause as #3965

**Comment by casperse** [comment]
So I have found that all the movies are there?
[https://pasteboard.co/IUVskSo.jpg](url)
And looking into the DB file it looks like the other movies?
But for some reason it will not get posters for these movies?
