### ISSUE TITLE
Couldn't Import Movie because destination already exists

### ISSUE THREAD

**Issue by ArGaMer** [Radarr/Radarr#4164]
**Describe the bug**
radarr trying over and over and over to import a movie that is already imported 

**To Reproduce**
1. Download Movie through radarr
2. let radarr try to import the movie
3. radarr then gets on import

**Expected behavior**
radarr import doesn't get stuck in a loop and don't have 2 copies of the movie

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Version 0.2.0.1450

**Debug Logs**
```
20-2-18 11:53:21.8|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
20-2-18 11:53:21.8|Debug|Parser|Parsing string 'The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT'
20-2-18 11:53:21.8|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
20-2-18 11:53:21.8|Debug|Parser|Movie Parsed. The Greatest Showman - 2017 
20-2-18 11:53:21.8|Debug|ParsingService|Language(s) parsed: 
20-2-18 11:53:21.8|Debug|QualityParser|Trying to parse quality for The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT
20-2-18 11:53:21.8|Debug|ParsingService|Quality parsed: Remux-2160p v1 (Surround)
20-2-18 11:53:21.8|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId)

20-2-18 11:53:21.8|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId)

20-2-18 11:53:21.8|Trace|ConfigService|Using default config value for 'downloadedmoviesfolder' defaultValue:''
20-2-18 11:53:21.8|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
20-2-18 11:53:21.8|Debug|Parser|Parsing string 'The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT'
20-2-18 11:53:21.8|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
20-2-18 11:53:21.8|Debug|Parser|Movie Parsed. The Greatest Showman - 2017 
20-2-18 11:53:21.8|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId)

20-2-18 11:53:21.8|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId)

20-2-18 11:53:21.9|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId)

20-2-18 11:53:21.9|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId)

20-2-18 11:53:21.9|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
20-2-18 11:53:21.9|Debug|Parser|Parsing string 'The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT'
20-2-18 11:53:21.9|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
20-2-18 11:53:21.9|Debug|Parser|Movie Parsed. The Greatest Showman - 2017 
20-2-18 11:53:21.9|Debug|ParsingService|Language(s) parsed: 
20-2-18 11:53:21.9|Debug|QualityParser|Trying to parse quality for The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT
20-2-18 11:53:21.9|Debug|ParsingService|Quality parsed: Remux-2160p v1 (Surround)
20-2-18 11:53:21.9|Debug|DownloadedMovieImportService|The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT folder quality: Remux-2160p v1 (Surround)
20-2-18 11:53:21.9|Debug|DiskScanService|Scanning 'M:\M&T\#PP\Movies4K\The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT' for video files
20-2-18 11:53:21.9|Debug|DiskScanService|1 video files were found in M:\M&T\#PP\Movies4K\The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT
20-2-18 11:53:21.9|Debug|ImportDecisionMaker|Analyzing 1/1 files.
20-2-18 11:53:21.9|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
20-2-18 11:53:21.9|Debug|Parser|Parsing string 'The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv'
20-2-18 11:53:21.9|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
20-2-18 11:53:21.9|Debug|Parser|Movie Parsed. The Greatest Showman - 2017 
20-2-18 11:53:21.9|Debug|VideoFileInfoReader|Getting media info from M:\M&T\#PP\Movies4K\The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT\The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv
20-2-18 11:53:21.9|Trace|MediaInfo|Read file offset 0-262144 (262144 bytes)
20-2-18 11:53:21.9|Trace|MediaInfo|Read file offset 60078891748-60078908132 (16384 bytes)
20-2-18 11:53:21.9|Trace|MediaInfo|Read file offset 60081071405-60081090114 (18709 bytes)
20-2-18 11:53:21.9|Trace|MediaInfo|Read a total of 297237 bytes (0.0%)
20-2-18 11:53:21.9|Debug|ParsingService|Language(s) parsed: 
20-2-18 11:53:21.9|Debug|QualityParser|Trying to parse quality for The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT
20-2-18 11:53:21.9|Debug|ParsingService|Quality parsed: Remux-2160p v1 (Surround)
20-2-18 11:53:21.9|Debug|ImportDecisionMaker|Size: 60081090114
20-2-18 11:53:21.9|Debug|SameFileSpecification|No existing movie file, skipping
20-2-18 11:53:21.9|Trace|ConfigService|Using default config value for 'skipfreespacecheckwhenimporting' defaultValue:'False'
20-2-18 11:53:21.9|Debug|VideoFileInfoReader|Getting media info from M:\M&T\#PP\Movies4K\The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT\The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv
20-2-18 11:53:21.9|Trace|MediaInfo|Read file offset 0-262144 (262144 bytes)
20-2-18 11:53:21.9|Trace|MediaInfo|Read file offset 60078891748-60078908132 (16384 bytes)
20-2-18 11:53:21.9|Trace|MediaInfo|Read file offset 60081071405-60081090114 (18709 bytes)
20-2-18 11:53:22.0|Trace|MediaInfo|Read a total of 297237 bytes (0.0%)
20-2-18 11:53:22.0|Debug|DetectSample|Runtime is over 90 seconds
20-2-18 11:53:22.0|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
20-2-18 11:53:22.0|Debug|ImportApprovedMovie|Decisions: 1
20-2-18 11:53:22.0|Debug|Parser|Parsing string 'The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT'
20-2-18 11:53:22.0|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
20-2-18 11:53:22.0|Debug|Parser|Movie Parsed. The Greatest Showman - 2017 
20-2-18 11:53:22.0|Trace|UpgradeMediaFileService|Upgrading existing movie file.
20-2-18 11:53:22.0|Debug|MovieFileMovingService|Copying movie file: M:\M&T\#PP\Movies4K\The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT\The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv to M:\M&T\UHD Movies\The Greatest Showman (2017)\The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv
20-2-18 11:53:22.0|Debug|DiskTransferService|Copy [M:\M&T\#PP\Movies4K\The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT\The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv] > [M:\M&T\UHD Movies\The Greatest Showman (2017)\The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv]
20-2-18 11:53:22.0|Warn|ImportApprovedMovie|Couldn't import movie M:\M&T\#PP\Movies4K\The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT\The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv

[v0.2.0.1450] System.IO.IOException: Destination already exists [M:\M&T\UHD Movies\The Greatest Showman (2017)\The.Greatest.Showman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv]
   at NzbDrone.Common.Disk.DiskTransferService.ClearTargetPath(String targetPath, Boolean overwrite) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 331
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 244
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 183
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 120
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.CopyMovieFile(MovieFile movieFile, LocalMovie localMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 98
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 65
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:line 105 
```

**Comment by beyondmeat** [comment]
Here's what's going on, you have an existing file that is not mapped in radarr.

It's already in that location but it's not "known" to radarr.

1. Go to the The Greatest Showman (2017) Movie page
2. Click the Manual Import icon in the toolbar.
3. See a file with the same name as "Unmapped"
4. Import it.
5. Go back to Activity Queue, Import the download (if you want), it will now import and replace the old file.
