### ISSUE TITLE
Moving fails when using separate users for radarr and download client

### ISSUE THREAD

**Issue by D34DC3N73R** [Radarr/Radarr#4194]
Radarr (aphrodite - docker - linuxserver/radarr:preview) can not move files when running as a different user than the download client.

1. Create user for radarr
2. Create user for nzbget
3. Add both to common group 'media'
4. Give download directory and media library 775 dir permissions
5. Run radarr as the radarr PUID and nzbget as the nzbget PUID, use the 'media' group PGID.
6. Search for and download a movie
7. The move will fail with the following error

```
2020-2-25 18:19:08.3|Warn|ImportApprovedMovie|Couldn't import movie /mnt/downloads/.movies/The.Movie.Directory/the.movie.file.mkv

[v3.0.0.2659] System.UnauthorizedAccessException: Access to the path is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFileInternal(String source, String destination, Boolean overwrite) in d:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 262
   at NzbDrone.Mono.Disk.DiskProvider.MoveFileInternal(String source, String destination, Boolean overwrite) in d:\a\1\s\src\NzbDrone.Mono\Disk\DiskProvider.cs:line 192
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile(String source, String destination, Boolean overwrite) in d:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 234
   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified(String sourcePath, String targetPath, Int64 originalSize) in d:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 620
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) in d:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 372
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) in d:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 230
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 122
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 82
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 77
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:line 124
```

When moving, the destination file does not get a .partial~ extension. The filesize changes, until the move appears to be complete, and then the file is removed from the destination directory and begins moving again with the above error repeated. 

Permissions are correct. The file can be successfully copied inside the container. For example:
```
docker exec --user=abc radarr cp "/mnt/downloads/.movies/The.Movie.Title.1080p.BluRay.x264/the.movie.title.1080.mkv" "/mnt/media/Video/Movies/The Movie Title (2020)/The Movie Title (2020) - (BLURAY-1080P - X264 - DTS 5.1) - GROUP.mkv"
```
Note: when using mv instead of cp the move does complete, but the following warning is output
```
mv: failed to preserve ownership for '/mnt/media/Video/Movies/The Movie Title (2020)/The Movie Title (2020) - (BLURAY-1080P - X264 - DTS 5.1) - GROUP.mkv': Operation not permitted
```

The above set up (separate users, same group) works with linuxserver/sonarr:preview

OS: Ubuntu 18.04 server
System > Status
 - Version 3.0.0.2665
 - .NET Core Yes
 - Docker Yes
 - DB Migration 168
 - AppData directory /config
 - Startup directory /opt/radarr
 - Mode Console

[radarr.txt](https://github.com/Radarr/Radarr/files/4253247/radarr.txt)

**Comment by ta264** [comment]
This is a known bug in net core and mono >= 6.0.  We'll try to add a workaround until it's fixed in .NET 5

**Comment by D34DC3N73R** [comment]
That would be great. I didn't see an open issue for this so I wanted to start one for anyone else running into the same problem.

**Comment by ta264** [comment]
Sorry, that was my pre-coffee way of saying thanks for opening the issue, it's a legit bug we should try to fix

**Comment by tehniemer** [comment]
I'm having a similar issue, but seemingly only when trying to do a manual import. My radarr and nzbget PUID and PGID are the same.

```
2020-3-1 12:59:51.2|Warn|ImportApprovedMovie|Couldn't import movie /mnt/downloads/.movies/The.Movie.Directory/the.movie.file.mkv

[v3.0.0.2704] System.IO.IOException: Input/output error
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFileInternal(String source, String destination, Boolean overwrite) in d:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 262
   at NzbDrone.Mono.Disk.DiskProvider.MoveFileInternal(String source, String destination, Boolean overwrite) in d:\a\1\s\src\NzbDrone.Mono\Disk\DiskProvider.cs:line 192
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile(String source, String destination, Boolean overwrite) in d:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 234
   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileTransactional(String sourcePath, String targetPath, Int64 originalSize, DiskTransferVerificationMode verificationMode) in d:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 543
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) in d:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 363
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) in d:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 230
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 122
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 82
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 77
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:line 124
```

**Comment by D34DC3N73R** [comment]
Just wanted to report this works for me now in 3.0.0.2736
