### ISSUE TITLE
Unable to connect to plex

### ISSUE THREAD

**Issue by loeschj** [Radarr/Radarr#4226]
**Describe the bug**
When trying to save/test the connect to Plex Media Server, in the UI it is throwing an error unable to connect to plex server.

**To Reproduce**

1. login and go to settings, connect.
2. Add a plex media server to the list that is on the same network
3. Retrieve the plex token as expected
4. Click save/test.

**Expected behavior**
The validation was successful and the settings are saved.

**Screenshots**
![image](https://user-images.githubusercontent.com/16830558/76694711-a34b0c00-6676-11ea-91cd-b31990a61b04.png) asteriks are only for the screenshot, my actual token was used.

**Desktop (please complete the following information):**
Docker Container on Ubuntu 18
Version 3.0.0.2719

**Debug Logs**
2020-3-14 22:29:34.7|Error|PlexServerService|Unable to connect to Plex Server

[v3.0.0.2719] NzbDrone.Core.Notifications.Plex.PlexException: Unable to connect to Plex Media Server
 ---> System.Net.WebException: An error occurred while sending the request. The response ended prematurely.: 'http://10.61.15.200:32400/library/sections?X-Plex-Client-Identifier=05d62b31-31fe-400c-9195-d9dc1e13061e&X-Plex-Product=Radarr&X-Plex-Platform=Windows&X-Plex-Platform-Version=7&X-Plex-Device-Name=Radarr&X-Plex-Version=3.0.0.2719&X-Plex-Token=n68Hb3HzgyHXykNevh72'
 ---> System.Net.WebException: An error occurred while sending the request. The response ended prematurely.
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in d:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 145
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in d:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 145
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 127
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 61
   at NzbDrone.Core.Notifications.Plex.Server.PlexServerProxy.ProcessRequest(HttpRequestBuilder requestBuilder) in d:\a\1\s\src\NzbDrone.Core\Notifications\Plex\Server\PlexServerProxy.cs:line 184
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Notifications.Plex.Server.PlexServerProxy.ProcessRequest(HttpRequestBuilder requestBuilder) in d:\a\1\s\src\NzbDrone.Core\Notifications\Plex\Server\PlexServerProxy.cs:line 197
   at NzbDrone.Core.Notifications.Plex.Server.PlexServerProxy.GetMovieSections(PlexServerSettings settings) in d:\a\1\s\src\NzbDrone.Core\Notifications\Plex\Server\PlexServerProxy.cs:line 39
   at NzbDrone.Core.Notifications.Plex.Server.PlexServerService.GetSections(PlexServerSettings settings) in d:\a\1\s\src\NzbDrone.Core\Notifications\Plex\Server\PlexServerService.cs:line 66
   at NzbDrone.Core.Notifications.Plex.Server.PlexServerService.Test(PlexServerSettings settings) in d:\a\1\s\src\NzbDrone.Core\Notifications\Plex\Server\PlexServerService.cs:line 162

2020-3-14 22:29:34.8|Warn|RadarrErrorPipeline|Invalid request Validation failed:
 -- Host: Unable to connect to Plex Server

**Comment by D34DC3N73R** [comment]
You won't be able to connect to a local ip using https. Disable that and it should work. Or alternatively, use https with the plex.direct address. Using a standard http connection with the local ip address works fine for me.

**Comment by loeschj** [comment]
thanks, it's working now :)

**Comment by evlo** [comment]
Hmm, mine is version 0.2.0.1480 and it is latest release on github and for plex server it does have user and pwd, what am I doing wrong?
