### ISSUE TITLE
Importing library fails

### ISSUE THREAD

**Issue by shanester64** [Radarr/Radarr#4243]
Attempting to import my existing library and fails. Tried one movie at a time with same results.
Looking at an example of the log, it consistently references the path "C:\projects\.." which doesn't exist, nor do I know where this reference is coming from.
[radarr.txt](https://github.com/Radarr/Radarr/files/4364442/radarr.txt)

20-3-21 15:48:35.4|Warn|SkyHookProxy|Couldn't map movie Hoosiers to a movie on The Movie DB. It will not be added :(

[v0.2.0.870] System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieInfo(Int32 TmdbId, Profile profile, Boolean hasPreDBEntry) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 105
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie(Movie movie) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 824

**Comment by ta264** [comment]
Upgrade, that'stoo old to work
