### ISSUE TITLE
[aphrodite] Exceptions on musl libc based linux distributions when importing movies

### ISSUE THREAD

**Issue by gentoo-overlay** [Radarr/Radarr#4245]
**Describe the bug**

This sounds similar to #2305.

**To Reproduce**
1. Using a musl libc based distribution (e.g Alpine Linux, Void Linux's musl edition, Gentoo with a musl stage3, etc...)
2. Click on 'Movies' -> Import -> Choose another folder
3. Add a folder
4. Nothing will happen but if you click on 'Movies' -> 'Import' again you'll see that the path was added with no free space ("0 B"). Clicking on the path name will produce a message that "All movies in {{path}} have been imported" but no such thing was done.

NOTE: The exception does not occur on a glibc based Linux distribution, this is specific to distributions using musl. In order to build it for musl at all I had to patch some files that hardcode `linux-x64` as follows:

```bash
for f in build.sh azure-pipelines.yml src/Directory.Build.props src/FixBindingRedirects.targets
do
    sed -i "s|linux-x64|linux-musl-x64|g" "$f"
done
```

This is needed because the `./build.sh` script generates builds for `linux-x64` by default which despite its name is not portable (it assumes glibc) so I needed to add an additional build target for `linux-musl-x64`. What's weird is that even though I can find no mentions of `linux-x64` in the sources the Exception text still mentions it:

```
[v10.0.0.18637] System.IO.FileLoadException: Could not load file or assembly 'Mono.Posix.NETStandard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. An operation is not legal in the current state. (0x80131509)
File name: 'Mono.Posix.NETStandard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
 ---> System.InvalidOperationException: Dependency resolution failed for component /usr/lib/radarr/Radarr.Mono.dll with error code -2147450740. Detailed error: Error:
  An assembly specified in the application dependencies manifest (Radarr.Mono.deps.json) was not found:
    package: 'Mono.Posix.NETStandard', version: '1.0.0'
    path: 'runtimes/linux-x64/native/libMonoPosixHelper.so'

   at System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componentAssemblyPath)
   at NzbDrone.Common.Composition.ContainerBuilderBase.ContainerResolveEventHandler(Object sender, ResolveEventArgs args) in /var/tmp/portage/net-p2p/radarr-99999999/work/radarr-99999999/src/NzbDrone.Common/Composition/ContainerBuilderBase.cs:line 57
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)
   at NzbDrone.Mono.Disk.SymbolicLinkResolver.GetCompleteRealPath(String path)
   at NzbDrone.Mono.Disk.DiskProvider.GetMount(String path) in /var/tmp/portage/net-p2p/radarr-99999999/work/radarr-99999999/src/NzbDrone.Mono/Disk/DiskProvider.cs:line 34
   at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path) in /var/tmp/portage/net-p2p/radarr-99999999/work/radarr-99999999/src/NzbDrone.Mono/Disk/DiskProvider.cs:line 43
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in /var/tmp/portage/net-p2p/radarr-99999999/work/radarr-99999999/src/NzbDrone.Core/RootFolders/RootFolderService.cs:line 193
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Debug Logs**

[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4365098/radarr.debug.txt)

**Comment by ta264** [comment]
Correct, netcore builds are glibc only currently. As you've discovered, one of the dependencies doesnt support musl. You could try the mono build.

**Comment by gentoo-overlay** [comment]
How would I build it for mono? The old version (the version in the nightly branch) works fine with mono, I just thought I'd try out the new version for testing. If that's not possible though then feel free to close this issue and I can keep using the nightly branch for now.

**Comment by ta264** [comment]
It'll be produced at the same time as the regular build.  Look for the net462 folder

**Comment by ta264** [comment]
But actually you're better off downloading from here https://radarr.lidarr.audio/v1/update/Aphrodite/updatefile?os=linux&runtime=mono

The build you produce yourself will be in Dev mode and won't work properly

**Comment by gentoo-overlay** [comment]
Thanks, I didn't realise the build built for both dotnetcore and mono (I was only installing the dotnetcore files). I feel stupid now.
