### ISSUE TITLE
Task Extension Task Sequence Error

### ISSUE THREAD

**Issue by loeschj** [Radarr/Radarr#4296]
**Describe the bug**
Not entirely sure what the impact of this is, but i was noticing in my logs quite frequently after a reboot and movies were being processed, this task sequence error would be thrown.

**To Reproduce**
1) rebooted radarr
2) movie scan was in progress

**Expected behavior**
scan was happening as expected, but an error was being thrown.

**Screenshots**

**Desktop (please complete the following information):**
Version - 3.0.0.2741
.NET Core - Yes
Docker - Yes
DB Migration - 169

**Debug Logs**
2020-4-8 09:49:25.9|Error|TaskExtensions|Task Error

[v3.0.0.2741] System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push[TCommand](TCommand command, CommandPriority priority, CommandTrigger trigger) in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandQueueManager.cs:line 128
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push(String commandName, Nullable`1 lastExecutionTime, Nullable`1 lastStartTime, CommandPriority priority, CommandTrigger trigger) in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandQueueManager.cs:line 138
   at NzbDrone.Core.Jobs.Scheduler.ExecuteCommands() in d:\a\1\s\src\NzbDrone.Core\Jobs\Scheduler.cs:line 42
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

**Comment by Naushi** [comment]
Same issue on a Synology Package v0.2.0.1480
Don't see any effect other than clogging up the log file and moving pretty slow...
```[Error] TaskExtensions: Task Error

[v0.2.0.1480] System.InvalidOperationException: Sequence contains more than one matching element
  at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0004a] in <b6496d2162cd48e1bb4e6753184b3d82>:0
  at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandPriority priority, NzbDrone.Core.Messaging.Commands.CommandTrigger trigger) [0x000a3] in <fd6dc903261f46d49ff7a60364fd04b3>:0
  at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3) [0x00035] in <b6496d2162cd48e1bb4e6753184b3d82>:0
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandQueueManager,object,NzbDrone.Core.Messaging.Commands.CommandPriority,NzbDrone.Core.Messaging.Commands.CommandTrigger)
  at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push (System.String commandName, System.Nullable`1[T] lastExecutionTime, NzbDrone.Core.Messaging.Commands.CommandPriority priority, NzbDrone.Core.Messaging.Commands.CommandTrigger trigger) [0x00141] in <fd6dc903261f46d49ff7a60364fd04b3>:0
  at NzbDrone.Core.Jobs.Scheduler.ExecuteCommands () [0x0005a] in <fd6dc903261f46d49ff7a60364fd04b3>:0
  at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <4a89e81f3d9644e6a5d556824ae3eaf1>:0
  at System.Threading.Tasks.Task.Execute () [0x00000] in <4a89e81f3d9644e6a5d556824ae3eaf1>:0```

**Comment by Qstick** [comment]
Fixed
