### ISSUE TITLE
Unable to connect to indexer

### ISSUE THREAD

**Issue by bigverm23** [Radarr/Radarr#4314]
**Description:**
Indexers created using torznab url and api key from Jackett are failing with exception shown in logs. I have verified said indexers work outside of radarr/sonarr.

**Radarr Version: 3.0.0.2830

**Mono Version:**

**Debug Logs:**
`2020-4-15 11:51:45.0|Debug|NewznabCapabilitiesProvider|Failed to parse newznab api capabilities for https://jackett.mydomain.net/api/v2.0/indexers/1337x/results/torznab/

[v3.0.0.2830] System.Xml.XmlException: Data at the root level is invalid. Line 1, position 578.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.ParseCapabilities(HttpResponse response) in d:\a\1\s\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 85
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in d:\a\1\s\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 80

2020-4-15 11:51:45.0|Warn|Torznab|Unable to connect to indexer

[v3.0.0.2830] System.Xml.XmlException: Data at the root level is invalid. Line 1, position 578.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.ParseCapabilities(HttpResponse response) in d:\a\1\s\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 85
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in d:\a\1\s\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 80
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in d:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 88
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.GetCapabilities(NewznabSettings indexerSettings) in d:\a\1\s\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 36
   at NzbDrone.Core.Indexers.Torznab.Torznab.get_PageSize() in d:\a\1\s\src\NzbDrone.Core\Indexers\Torznab\Torznab.cs:line 23
   at NzbDrone.Core.Indexers.Torznab.Torznab.GetRequestGenerator() in d:\a\1\s\src\NzbDrone.Core\Indexers\Torznab\Torznab.cs:line 27
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in d:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 387

2020-4-15 11:51:45.0|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
2020-4-15 11:51:45.0|Debug|Api|[POST] /api/v3/indexer/test: 400.BadRequest (92 ms)
2020-4-15 11:51:46.8|Debug|NewznabCapabilitiesProvider|Failed to parse newznab api capabilities for https://jackett.mydomain.net/api/v2.0/indexers/1337x/results/torznab/

[v3.0.0.2830] System.Xml.XmlException: Data at the root level is invalid. Line 1, position 578.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.ParseCapabilities(HttpResponse response) in d:\a\1\s\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 85
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in d:\a\1\s\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 80

2020-4-15 11:51:46.8|Warn|Torznab|Unable to connect to indexer

[v3.0.0.2830] System.Xml.XmlException: Data at the root level is invalid. Line 1, position 578.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.ParseCapabilities(HttpResponse response) in d:\a\1\s\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 85
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in d:\a\1\s\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 80
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in d:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 88
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.GetCapabilities(NewznabSettings indexerSettings) in d:\a\1\s\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 36
   at NzbDrone.Core.Indexers.Torznab.Torznab.get_PageSize() in d:\a\1\s\src\NzbDrone.Core\Indexers\Torznab\Torznab.cs:line 23
   at NzbDrone.Core.Indexers.Torznab.Torznab.GetRequestGenerator() in d:\a\1\s\src\NzbDrone.Core\Indexers\Torznab\Torznab.cs:line 27
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in d:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 387`

**Comment by ilike2burnthing** [comment]
You're using Newznab under Usenet, rather than Torznab under Torrents

**Comment by bigverm23** [comment]
No, I'm using torzbnab for all of my torrents, all of which are failed.

**Comment by ilike2burnthing** [comment]
Sonarr/Radarr > Settings > Indexers > add symbol

You're clicking Torznab in the bottom right, rather than Newznab in top left?

And when you click on your added indexers, it says 'Edit - Torznab' at the top?

**Comment by bigverm23** [comment]
Yes thats correct
![image](https://user-images.githubusercontent.com/17554438/79452572-58dee700-7fb6-11ea-9faf-a8b6cf16a864.png)
![image](https://user-images.githubusercontent.com/17554438/79452624-6b592080-7fb6-11ea-8a19-63b05bfebd35.png)

**Comment by bigverm23** [comment]
I do have two Newsnab set up and they work perfectly, but again all Torrents are failing in both sonarr/radarr v3

**Comment by ilike2burnthing** [comment]
Apologies, that's what I get for skim reading the log. 

Have you tried using http://192.168.0.xxx:yyyy/api... instead?

**Comment by bigverm23** [comment]
yes I should have included that as well, this is the result.

<error code="100" description="Invalid API Key"/>

i have double and triple checked the API key within Jackett and it matches up.

**Comment by ta264** [comment]
Check jackett log for errors and try fetching the URL in a browser to see what's wrong with the data.

**Comment by bigverm23** [comment]
so nothing happens after I enter the URL and it gives API error, no logs show in Jackett.  Yet if I test the indexer (all indexers) within Jackett, it passes and I show search results in the logs.

Found 60 releases from 1337x

**Comment by bigverm23** [comment]
> Check jackett log for errors and try fetching the URL in a browser to see what's wrong with the data.

<error code="100" description="Invalid API Key"/>

**Comment by bigverm23** [comment]
> Apologies, that's what I get for skim reading the log.
> 
> Have you tried using http://192.168.0.xxx:yyyy/api... instead?

using the IP instead of domain name also fails

**Comment by ta264** [comment]
Looks like you have the wrong API key? I think you'd have more luck getting support on the discord server
