### ISSUE TITLE
System.InvalidOperationException: Sequence contains more than one matching element

### ISSUE THREAD

**Issue by thibautcornolti** [Radarr/Radarr#4319]
**Describe the bug**

Hello, I have this recurring trace in my Radarr v3.0.0.2830 logs.
I'm not sure if it is linked but I cannot see almost any poster as well.

Thank you!

**To Reproduce**

Steps to reproduce the behavior (not sure if anything here is linked to that):
1. Install Radarr through Docker and https://hub.docker.com/r/linuxserver/radarr
2. Import bunch of movies (let's say 4000)
3. Wait or manually re-scan a movie
4. See error happening

**Desktop (please complete the following information):**

Debian 10, Docker and https://hub.docker.com/r/linuxserver/radarr v3.0.0.2830

**Debug Logs**

No difference between Info and Debug logs (?).

```
2020-4-17 23:39:35.7|Debug|DetectSample|Runtime is over 90 seconds
2020-4-17 23:39:35.7|Debug|VideoFileInfoReader|Getting media info from /movies/Alita Battle Angel (2019)/Alita.Battle.Angel.2019.MULTI.1080p.WEB.H264-EXTREME.mkv
2020-4-17 23:39:35.7|Trace|MediaInfo|Read a total of 32768 bytes (0.0%)
2020-4-17 23:39:35.7|Debug|DetectSample|Runtime is over 90 seconds
2020-4-17 23:39:35.7|Trace|MediaInfo|Read a total of 32768 bytes (0.0%)
2020-4-17 23:39:35.7|Debug|VideoFileInfoReader|Getting media info from /movies/Alita Battle Angel (2019)/Alita.Battle.Angel.2019.MULTI.1080p.WEB.H264-EXTREME.mkv
2020-4-17 23:39:35.7|Debug|DetectSample|Runtime is over 90 seconds
2020-4-17 23:39:35.7|Debug|VideoFileInfoReader|Getting media info from /movies/Alita Battle Angel (2019)/Alita.Battle.Angel.2019.MULTI.1080p.WEB.H264-EXTREME.mkv
2020-4-17 23:39:37.0|Trace|MediaInfo|Read file offset 0-32768 (32768 bytes)
2020-4-17 23:39:37.0|Trace|MediaInfo|Read file offset 0-32768 (32768 bytes)
2020-4-17 23:39:37.0|Trace|MediaInfo|Read file offset 0-32768 (32768 bytes)
2020-4-17 23:39:37.5|Trace|Scheduler|Pending Tasks: 10
2020-4-17 23:39:37.5|Trace|CommandQueueManager|Publishing PreDBSync
2020-4-17 23:39:37.5|Trace|CommandQueueManager|Checking if command is queued or started: PreDBSync
2020-4-17 23:39:37.5|Trace|CommandQueueManager|Command is already in progress: PreDBSync
2020-4-17 23:39:37.5|Trace|CommandQueueManager|Publishing MessagingCleanup
2020-4-17 23:39:37.5|Trace|CommandQueueManager|Checking if command is queued or started: MessagingCleanup
2020-4-17 23:39:37.5|Trace|CommandQueueManager|Command is already in progress: MessagingCleanup
2020-4-17 23:39:37.5|Trace|CommandQueueManager|Publishing ApplicationUpdate
2020-4-17 23:39:37.5|Trace|CommandQueueManager|Checking if command is queued or started: ApplicationUpdate
2020-4-17 23:39:37.5|Trace|CommandQueueManager|Command is already in progress: ApplicationUpdate
2020-4-17 23:39:37.5|Trace|CommandQueueManager|Publishing CheckHealth
2020-4-17 23:39:37.5|Trace|CommandQueueManager|Checking if command is queued or started: CheckHealth
2020-4-17 23:39:37.5|Trace|CommandQueueManager|Command is already in progress: CheckHealth
2020-4-17 23:39:37.5|Trace|CommandQueueManager|Publishing RefreshMovie
2020-4-17 23:39:37.5|Trace|CommandQueueManager|Checking if command is queued or started: RefreshMovie
2020-4-17 23:39:37.5|Error|TaskExtensions|Task Error

[v3.0.0.2830] System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push[TCommand](TCommand command, CommandPriority priority, CommandTrigger trigger) in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandQueueManager.cs:line 128
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push(String commandName, Nullable`1 lastExecutionTime, Nullable`1 lastStartTime, CommandPriority priority, CommandTrigger trigger) in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandQueueManager.cs:line 138
   at NzbDrone.Core.Jobs.Scheduler.ExecuteCommands() in d:\a\1\s\src\NzbDrone.Core\Jobs\Scheduler.cs:line 42
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

2020-4-17 23:39:38.5|Trace|MediaInfo|Read file offset 4745027115-4745043499 (16384 bytes)
2020-4-17 23:39:38.5|Trace|MediaInfo|Read file offset 4745027115-4745043499 (16384 bytes)
2020-4-17 23:39:38.5|Trace|MediaInfo|Read file offset 4745027115-4745043499 (16384 bytes)
2020-4-17 23:39:38.5|Trace|MediaInfo|Read file offset 4745124134-4745126092 (1958 bytes)
2020-4-17 23:39:38.5|Trace|MediaInfo|Read file offset 4745124134-4745126092 (1958 bytes)
2020-4-17 23:39:38.5|Trace|MediaInfo|Read file offset 4745124134-4745126092 (1958 bytes)
2020-4-17 23:39:38.5|Trace|MediaInfo|Read a total of 51110 bytes (0.0%)
2020-4-17 23:39:38.5|Trace|MediaInfo|Read a total of 51110 bytes (0.0%)
2020-4-17 23:39:38.5|Trace|MediaInfo|Read a total of 51110 bytes (0.0%)
2020-4-17 23:39:38.5|Debug|DetectSample|Runtime is over 90 seconds
2020-4-17 23:39:38.5|Debug|DetectSample|Runtime is over 90 seconds
2020-4-17 23:39:38.5|Debug|DetectSample|Runtime is over 90 seconds
2020-4-17 23:39:38.5|Debug|VideoFileInfoReader|Getting media info from /movies/All Eyez on Me (2017)/All Eyez on Me 2017 1080p FR EN X264 AC3-mHDgz.mkv
2020-4-17 23:39:38.5|Debug|VideoFileInfoReader|Getting media info from /movies/All Eyez on Me (2017)/All Eyez on Me 2017 1080p FR EN X264 AC3-mHDgz.mkv
2020-4-17 23:39:38.5|Debug|VideoFileInfoReader|Getting media info from /movies/All Eyez on Me (2017)/All Eyez on Me 2017 1080p FR EN X264 AC3-mHDgz.mkv
```

And a lot of
`[Warn] MediaCoverMapper: File /config/MediaCover/xxxx/poster.jpg not found`

**Comment by FrancisHG** [comment]
Same issue here, but I cannot do any manual import. I tried renaming the import folder, same results. Here are my trace logs:

`System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Jobs.ScheduledTaskRepository.GetDefinition(Type type) in d:\a\1\s\src\NzbDrone.Core\Jobs\ScheduledTaskRepository.cs:line 23
   at NzbDrone.Core.Jobs.TaskManager.HandleAsync(ConfigSavedEvent message) in d:\a\1\s\src\NzbDrone.Core\Jobs\TaskManager.cs:line 197
   at NzbDrone.Core.Messaging.Events.EventAggregator.<>c__DisplayClass6_2`1.<PublishEvent>b__2() in d:\a\1\s\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 122
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)`

**Comment by Naushi** [comment]
Same issue on a Synology Package v0.2.0.1480
Don't see any effect other than clogging up the log file and moving pretty slow...
```[Error] TaskExtensions: Task Error

[v0.2.0.1480] System.InvalidOperationException: Sequence contains more than one matching element
  at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0004a] in <b6496d2162cd48e1bb4e6753184b3d82>:0
  at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandPriority priority, NzbDrone.Core.Messaging.Commands.CommandTrigger trigger) [0x000a3] in <fd6dc903261f46d49ff7a60364fd04b3>:0
  at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3) [0x00035] in <b6496d2162cd48e1bb4e6753184b3d82>:0
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandQueueManager,object,NzbDrone.Core.Messaging.Commands.CommandPriority,NzbDrone.Core.Messaging.Commands.CommandTrigger)
  at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push (System.String commandName, System.Nullable`1[T] lastExecutionTime, NzbDrone.Core.Messaging.Commands.CommandPriority priority, NzbDrone.Core.Messaging.Commands.CommandTrigger trigger) [0x00141] in <fd6dc903261f46d49ff7a60364fd04b3>:0
  at NzbDrone.Core.Jobs.Scheduler.ExecuteCommands () [0x0005a] in <fd6dc903261f46d49ff7a60364fd04b3>:0
  at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <4a89e81f3d9644e6a5d556824ae3eaf1>:0
  at System.Threading.Tasks.Task.Execute () [0x00000] in <4a89e81f3d9644e6a5d556824ae3eaf1>:0```

**Comment by Qstick** [comment]
Fixed
