### ISSUE TITLE
Gotify notifications broke with recent migration to HttpClient 

### ISSUE THREAD

**Issue by brandon099** [Radarr/Radarr#4321]
**Describe the bug**
Just upgraded to 3.0.0.2830 and previously configured Gotify notifications are now throwing 404's with the same settings they have always had. It also does this when trying to add new configurations. 

It looks like it could be related to the recently merged PR which migrates away from RestSharp over to HttpClient (#4303). I'm not too familiar with C#, but at least one thing that seems off is when building the request it looks like the wrong parameter type is being sent ([`4abf446`](https://github.com/Radarr/Radarr/commit/4abf44617c296d659d5289355c9ea0ed8c17bcf2#diff-b66b26dc23f045c65607ed4c5fed02d4)) for at least the token (Query Param gets changed to Form Param in that PR, which would result in a 401 I believe).

**To Reproduce**
Go to Settings -> Connect -> Gotify server settings -> Click test -> Receive error: Unable to send test message
OR
Settings -> Connect -> + (New) -> Gotify -> Enter details of server -> Receive error: Unable to send test message

**Expected behavior**
Notifications sent to Gotify's API

**Desktop (please complete the following information):**
 - OS: Linux
 - Mono Version: Dotnet Core
 - Version: 3.0.0.2830

**Debug Logs**
I've sanitized the URL in the log
```
2020-4-17 23:55:36.4|Warn|NotificationService|Unable to send OnDownload notification to: Gotify

[v3.0.0.2830] System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at NzbDrone.Common.Exceptions.NzbDroneException..ctor(String message, Exception innerException, Object[] args) in d:\a\1\s\src\NzbDrone.Common\Exceptions\NzbDroneException.cs:line 18
   at NzbDrone.Core.Notifications.Gotify.GotifyException..ctor(String message, Exception innerException, Object[] args) in d:\a\1\s\src\NzbDrone.Core\Notifications\Gotify\GotifyException.cs:line 16
   at NzbDrone.Core.Notifications.Gotify.GotifyProxy.SendNotification(String title, String message, GotifySettings settings) in d:\a\1\s\src\NzbDrone.Core\Notifications\Gotify\GotifyProxy.cs:line 40
   at NzbDrone.Core.Notifications.Gotify.Gotify.OnDownload(DownloadMessage message) in d:\a\1\s\src\NzbDrone.Core\Notifications\Gotify\Gotify.cs:line 30
   at NzbDrone.Core.Notifications.NotificationService.Handle(MovieDownloadedEvent message) in d:\a\1\s\src\NzbDrone.Core\Notifications\NotificationService.cs:line 129

2020-4-17 23:55:36.6|Warn|HttpClient|HTTP Error - Res: [POST] https://notify.example.com: 404.NotFound
{"error":"Not Found","errorCode":404,"errorDescription":"page not found"}
```

**Comment by Qstick** [comment]
Thanks for the great bug report, will get fixed up

**Comment by brandon099** [comment]
@Qstick It does look like changing it to a query parameter was only part of the fix, and is still breaking with a 404 if the previously configured Server URL is not changed. The logs below show the updated request including the query parameter, as it used to. However, it's missing the `/message` portion of the URI that was getting passed in to RestSharp that happened when building the request URI previously, thus causing the 404.

HttpRequestBuilder only takes the baseUrl as a parameter, and `settings.Server` is being passed  while not appending `/message`. I'm not sure if it was intended vs bug, but if it was intended behavior the help text should probably be updated and any existing settings will need to be updated to get it working. Or update `HttpRequestBuilder` to accept the API route as an optional parameter maybe, like was previously being done.

```
[v3.0.0.2894] NzbDrone.Core.Notifications.Gotify.GotifyException: Unable to connect to Gotify. Status Code: {0}
 ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [POST] at [https://notify.example.com?token=(removed)   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 100
   at NzbDrone.Core.Notifications.Gotify.GotifyProxy.SendNotification(String title, String message, GotifySettings settings) in d:\a\1\s\src\NzbDrone.Core\Notifications\Gotify\GotifyProxy.cs:line 31
{"error":"Not Found","errorCode":404,"errorDescription":"page not found"}
```

**Comment by Qstick** [comment]
Thanks, I'll look at this tonight again.

**Comment by Qstick** [comment]
@brandon099 Should really be fixed now. Test would be appreciated.

**Comment by brandon099** [comment]
@Qstick That did the trick -- working just as it did before the migration to HTTPClient. Sorry, if I was more familiar with these C# libraries, this would have been an easy PR to submit. Thanks again!

**Comment by Qstick** [comment]
Hehe no problem. Thanks for testing
