### ISSUE TITLE
Unknown exception: Unable to determine qBittorrent API version

### ISSUE THREAD

**Issue by azumukupoe** [Radarr/Radarr#4324]
**Describe the bug**
Can't use qBittorrent v4.2.3

**To Reproduce**
1. Test qBittorrent

**Expected behavior**
Success

**Screenshots**
![image](https://user-images.githubusercontent.com/31339007/79668720-c62a8c00-81f1-11ea-960a-c9cb312ad4e6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Version 0.2.0.1480

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by WHiZSTA** [comment]
this started happening to me too the past month.

NzbDrone.Core.Download.Clients.DownloadClientException: Unable to determine qBittorrent API version
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.FetchProxy(QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 84
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.<>c__DisplayClass6_0.<GetProxy>b__0() in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 67
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in C:\projects\radarr-usby1\src\NzbDrone.Common\Cache\Cached.cs:line 81
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxy(QBittorrentSettings settings, Boolean force) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 67
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.GetItems() in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 110

**Comment by austinwbest** [comment]
Start a new issue and provide the requested information when doing so.
