### ISSUE TITLE
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by b1zbi** [Radarr/Radarr#4337]
I cannot search by IMDB List. I have tried my List and it does not work, in the past it used to work. I have tried searching from other users imdb list id and it works. My list is set as public on IMDB (the API call retrieves data).

 On console logs I have: 
`An error occurred while processing feed. https://api.radarr.video/v2/imdb/list?listId=ls009687199: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.`

```
Exception:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess(NetImportResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 56
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse(NetImportResponse importResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 34
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 115
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchMovies(NetImportPageableRequestChain pageableRequestChain, Boolean isRecent) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 63

```

Version 0.2.0.1480 running on windows 10

**Comment by Qstick** [comment]
This list works fine for me adding it to Radarr

**Comment by b1zbi** [comment]
Hello @Qstick 
Sorry to open this again but the same list does not work for me. Could you share how you added the list? I attach a video of the same list and testing fetching data
https://imgur.com/a/Fe9k6oz

**Comment by Qstick** [comment]
Take the `/` off the end behind the list number

**Comment by b1zbi** [comment]
Same issue without / 

https://imgur.com/a/d8igSAX

**Comment by Qstick** [comment]
You have something blocking access to Radarr site or something, I have no issues with this list on 0.2 or v3
