### ISSUE TITLE
radarr v3 - new install // default branch to aphrodite ?

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#4354]
Wanted to try v3 out and followed instructions from reddit to grab 
https://radarr.lidarr.audio/v1/update/aphrodite/updatefile?version=3.0.0.2871&os=windows&runtime=netcore&arch=64x

Started with clean install. Greeted with 4 status messages, three of them make sense (no indexers for search, no indexers for rss sync / no download client) but then:
> Branch develop is for a previous version of Radarr, set branch to 'Aphrodite' for further updates

1) shouldnt that be 'aphrodite'
2) why isnt this just set by default for this branch?

as not everyone would know to go to settings > general, show hidden, then know to change it.

**Comment by thezoggy** [comment]
yeah, looks like v3 has a bit to go :/

* crashed on switching to form based login (it didnt properly restart, had to exit and restart twice to make it happy).
* when adding first indexer it errored because it didnt pre-populate the categories.. then on second save it did. but then it added 2035 which warned that the site didnt have it and i should manually remove.. 
* task errors galore on new setup
* lists seems like only partially added so far, cant do tmdb popular/upcoming/etc anymore? cant filter by ratings? cant tell it to ignore suggestions? 
* when adding root dir, it was not happy trying to add a parent folder that had a bunch of subfolders.. crashed. tried to just type it out and hit okay.
* Failed to discover movies for action recommendations!: Error while calling api: Unprocessable Entity

**Comment by thezoggy** [comment]
about the imdb watch list:
```
2020-4-25 15:31:59.2|Debug|RSSImport|Downloading List http://rss.imdb.com/user/urXXXXXXXX/watchlist
2020-4-25 15:32:01.1|Warn|RSSImport|Unable to connect to list

[v3.0.0.2871] NzbDrone.Core.NetImport.Exceptions.NetImportException: List responded with html content. Site is likely blocked or unavailable.
   at NzbDrone.Core.NetImport.RSSImport.RSSImportParser.PreProcess(NetImportResponse netImportResponse) in d:\a\1\s\src\NzbDrone.Core\NetImport\RSSImport\RSSImportParser.cs:line 121
   at NzbDrone.Core.NetImport.RSSImport.RSSImportParser.ParseResponse(NetImportResponse importResponse) in d:\a\1\s\src\NzbDrone.Core\NetImport\RSSImport\RSSImportParser.cs:line 40
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in d:\a\1\s\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 115
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in d:\a\1\s\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 151

2020-4-25 15:32:01.1|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer. List responded with html content. Site is likely blocked or unavailable.
```

**Comment by thezoggy** [comment]
about discovering throwing errors, looks like it should just abort out if there are 0 movies (new install):
```
2020-4-25 15:20:51.1|Error|SkyHookProxy|Failed to discover movies for action recommendations!

[v3.0.0.2871] NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Unprocessable Entity
Full error(s): Unprocessable Entity (422, RayId: dacb1077-9492-467b-935f-4294693943d9), Details: Please add some movies before using our recommendation engine :)
   at NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIClient.Execute[T](HttpRequest request) in d:\a\1\s\src\NzbDrone.Core\MetadataSource\RadarrAPI\RadarrAPIClient.cs:line 151
   at NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIClient.DiscoverMovies(String action, Func`2 enhanceRequest) in d:\a\1\s\src\NzbDrone.Core\MetadataSource\RadarrAPI\RadarrAPIClient.cs:line 42
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.DiscoverNewMovies(String action) in d:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 387
```

**Comment by thezoggy** [comment]
about task error, kept seeing it while in the config setting things up.
guessing its not handling dummy show when doing naming?

```
2020-4-25 13:05:47.1|Debug|Api|[PUT] /api/v3/config/mediamanagement: 202.Accepted (10 ms)
2020-4-25 13:05:47.1|Error|TaskExtensions|Task Error

[v3.0.0.2871] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Jobs.ScheduledTaskRepository.GetDefinition(Type type) in d:\a\1\s\src\NzbDrone.Core\Jobs\ScheduledTaskRepository.cs:line 23
   at NzbDrone.Core.Jobs.TaskManager.HandleAsync(ConfigSavedEvent message) in d:\a\1\s\src\NzbDrone.Core\Jobs\TaskManager.cs:line 197
   at NzbDrone.Core.Messaging.Events.EventAggregator.<>c__DisplayClass6_2`1.<PublishEvent>b__2() in d:\a\1\s\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 122
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

2020-4-25 13:05:47.1|Debug|Parser|Parsing string 'The.Movie.Title.2010.1080p.BluRay.DTS.x264-EVOLVE'
```

**Comment by Qstick** [comment]
Open different issues for each issue you find. This was closed as the original issue was fixed.
