### ISSUE TITLE
radarr v3 -- task error on new install

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#4358]
on a new install, I kept seeing these pop up when navigating throughout the config.

```
2020-4-25 13:05:47.1|Debug|Api|[PUT] /api/v3/config/mediamanagement: 202.Accepted (10 ms)
2020-4-25 13:05:47.1|Error|TaskExtensions|Task Error

[v3.0.0.2871] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Jobs.ScheduledTaskRepository.GetDefinition(Type type) in d:\a\1\s\src\NzbDrone.Core\Jobs\ScheduledTaskRepository.cs:line 23
   at NzbDrone.Core.Jobs.TaskManager.HandleAsync(ConfigSavedEvent message) in d:\a\1\s\src\NzbDrone.Core\Jobs\TaskManager.cs:line 197
   at NzbDrone.Core.Messaging.Events.EventAggregator.<>c__DisplayClass6_2`1.<PublishEvent>b__2() in d:\a\1\s\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 122
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

2020-4-25 13:05:47.1|Debug|Parser|Parsing string 'The.Movie.Title.2010.1080p.BluRay.DTS.x264-EVOLVE'
```

```
2020-4-25 12:48:51.9|Debug|Api|[PUT] /api/v3/config/indexer: 202.Accepted (220 ms)
2020-4-25 12:48:51.9|Error|TaskExtensions|Task Error

[v3.0.0.2871] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Jobs.ScheduledTaskRepository.GetDefinition(Type type) in d:\a\1\s\src\NzbDrone.Core\Jobs\ScheduledTaskRepository.cs:line 23
   at NzbDrone.Core.Jobs.TaskManager.HandleAsync(ConfigSavedEvent message) in d:\a\1\s\src\NzbDrone.Core\Jobs\TaskManager.cs:line 197
   at NzbDrone.Core.Messaging.Events.EventAggregator.<>c__DisplayClass6_2`1.<PublishEvent>b__2() in d:\a\1\s\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 122
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Comment by Qstick** [comment]
Fixed in https://github.com/Radarr/Radarr/commit/a0fe43cd6edf6784cbd4a9634f25775dfd0fb82a

**Comment by thezoggy** [comment]
Thanks!
