### ISSUE TITLE
Error occurred while executing task RenameMovie: SQL logic error too many SQL variables

### ISSUE THREAD

**Issue by mbeebe43083** [Radarr/Radarr#4359]
Renamer Fails

**To Reproduce**
Select All 
Rename Files
(3000+ movies, less than 1000 selected works fine)

**Expected behavior**
Renames Files

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - 3.0.0.2878

```
code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
too many SQL variables
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1060
   at Dapper.SqlMapper.MultiMapImpl[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn, IDataReader reader, Identity identity, Boolean finalize)+MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1421
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.MultiMap[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, String sql, Delegate map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1402
   at NzbDrone.Core.Movies.MovieRepository.GetResults(Template sql) in d:\a\1\s\src\NzbDrone.Core\Movies\MovieRepository.cs:line 80
   at NzbDrone.Core.Datastore.BasicRepository`1.Query(SqlBuilder builder, Func`2 queryFunc) in d:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 99
   at NzbDrone.Core.Datastore.BasicRepository`1.Get(IEnumerable`1 ids) in d:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 138
   at NzbDrone.Core.Movies.MovieService.GetMovies(IEnumerable`1 movieIds) in d:\a\1\s\src\NzbDrone.Core\Movies\MovieService.cs:line 87
   at NzbDrone.Core.MediaFiles.RenameMovieFileService.Execute(RenameMovieCommand message) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\RenameMovieFileService.cs:line 137
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 119
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44
Close
```

**Comment by Qstick** [comment]
There is a bug currently that limits to 999.

**Comment by Qstick** [comment]
Fixed here, need pull
https://github.com/Readarr/Readarr/commit/0e4957cca3565bb2999d9b16dacdc51db5b79db5
