### ISSUE TITLE
Cannot import movie from nzbget - null exception error.

### ISSUE THREAD

**Issue by hodor** [Radarr/Radarr#4360]
**Describe the bug**
When the nzbget downloads the file, the import task fails with a null exception from NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 50.

**To Reproduce**
1. Setup NZBGet as the download client
2. Add a new movie
3. Wait until the import fails.

**Expected behavior**
Download movie flow should finish without any errors. Completed movies should be properly imported to the correct folder.

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Mono Version: [N/A]
 - Version [3.0.0.2850-ls5 by linuxserver.io]

**Environment**
I'm using https://cloudboxes.io/, which uses Docker to run Radarr.
The target folder is a mounted drive, which is done with RClone.

**Debug Logs**
```
2020-4-26 07:22:33.3|Warn|ImportApprovedMovie|Couldn't import movie [...]

[v3.0.0.2850] System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 50
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:line 124

2020-4-26 07:22:33.4|Warn|ImportApprovedMovie|Couldn't import movie [...]

[v3.0.0.2850] System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 50
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:line 124
```

**Comment by mattmac24** [comment]
I am also seeing this error. Any workaround?

**Comment by Qstick** [comment]
Can you confirm this still happens in 3021 or above?

**Comment by Pfuenzle** [comment]
Does still happen to me on 3073

**Comment by Qstick** [comment]
Ok, need some more trace logs, an entire log if possible as the small excerpt doesn’t provide enough context

**Comment by oooseun** [comment]
I'm also seeing this on 3.0.0.3112

Here's an example log


```
2020-7-3 19:24:02.1|Warn|ImportApprovedMovie|Couldn't import movie /mnt/downloads/nzbget/movies/blablabla.-HDMaNiAcS/S7sxWQFb40jA361gNpMfc0FSWS/j27oEKOA2w2mUGeY8SYffcTwm8Y51TdJ.mkv

[v3.0.0.3112] System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 50
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:line 123

```

**Comment by Qstick** [comment]
Most examples of this I've seen on discord ended up being permissions issues. If anyone is having these, can you join discord to try and debug?

**Comment by sweeneyuk** [comment]
I get this also running Windows
System.ArgumentNullException: Value cannot be null. (Parameter 'path2') at System.IO.Path.Combine(String path1, String path2) at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 50 at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:line 123

Running 3.0.0.3164

**Comment by bakerboy448** [comment]
@sweeneyuk is this still happening on the latest builds?  did you have the mount set to no create?

and still waiting on the nice big chunk of trace logs

did you confirm permissions are good across the board?
