### ISSUE TITLE
Unable to add IMDB List

### ISSUE THREAD

**Issue by tunes0710** [Radarr/Radarr#4364]
**Describe the bug**
Trying to add an IMDB list returns an error of "Unable to connect to list, check the log for more details"

**To Reproduce**
1. Go to 'settings'
2. Click on 'Lists'
3. Add Preset Radarr List for 'IMDB Lists'
4. Set Availability/Profile and folder settings
5. Under Path to list replace LISTID with 'ur117431687'
6. Click Test

**Expected behavior**
Expect the test to complete, so I can save as IMDB List.

**Screenshots**
![image](https://user-images.githubusercontent.com/26158557/80351051-96baf580-8869-11ea-88b1-0a43a0ec76e5.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version 0.2.0.1480 (Develop branch)

**Debug Logs**
2020-4-27 09:31:46.2|Debug|RadarrLists|Downloading List https://api.radarr.video/v2/imdb/list?listId=ur117431687
2020-4-27 09:31:46.7|Warn|RadarrLists|Unable to connect to list

[v0.2.0.1480] NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Not Found
Full error(s): Not Found (404, RayId: cbb22c58-0f06-4240-96ae-195e3c6da2e6), Details: not found
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess(NetImportResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 60
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse(NetImportResponse importResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 34
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 115
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 150

***Additional Info***
In the Debug log, it shows the link as https://api.radarr.video/v2/imdb/list?listId=ur117431687
If I go to that link, I get 

{"errors":[{"id":"cbb22c58-0f06-4240-96ae-195e3c6da2e6","status":404,"title":"Not Found","detail":"not found"}]}

However under my watch list in IMDB I added
![image](https://user-images.githubusercontent.com/26158557/80351641-996a1a80-886a-11ea-9c22-624884d197e0.png)

**Comment by Qstick** [comment]
You must use the ls number for the list, and it can’t be private

**Comment by tunes0710** [comment]
Have created a public list, but it still doesn't appear to work.
List is https://www.imdb.com/list/ls099319875
API Link is https://api.radarr.video/v2/imdb/list?listId=ls099319875
and reporting
{"errors":[{"id":"f79f9ae1-3897-4d13-b163-e1a0c51a9b9d","status":404,"title":"Not Found","detail":"not found"}]}

Debug log shows
2020-4-27 10:22:13.4|Debug|RadarrLists|Downloading List https://api.radarr.video/v2/imdb/list?listId=ls099319875
2020-4-27 10:22:13.9|Warn|RadarrLists|Unable to connect to list

![image](https://user-images.githubusercontent.com/26158557/80356536-7e4ed900-8871-11ea-840e-a5125d6e2579.png)


[v0.2.0.1480] NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Not Found
Full error(s): Not Found (404, RayId: f79f9ae1-3897-4d13-b163-e1a0c51a9b9d), Details: not found
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess(NetImportResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 60
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse(NetImportResponse importResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 34
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 115
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 150

2020-4-27 10:22:13.9|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details
2020-4-27 10:22:13.9|Debug|Api|[POST] /api/netimport/test: 400.BadRequest (514 ms)
2020-4-27 10:22:16.7|Debug|RadarrLists|Downloading List https://api.radarr.video/v2/imdb/list?listId=ls099319875
2020-4-27 10:22:17.1|Warn|RadarrLists|Unable to connect to list

[v0.2.0.1480] NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Not Found
Full error(s): Not Found (404, RayId: f79f9ae1-3897-4d13-b163-e1a0c51a9b9d), Details: not found
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess(NetImportResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 60
   at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse(NetImportResponse importResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:line 34
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 115
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 150

2020-4-27 10:22:17.1|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details
2020-4-27 10:22:17.1|Debug|Api|[POST] /api/netimport/test: 400.BadRequest (577 ms)
2020-4-27 10:22:25.2|Debug|Api|[GET] /api/log/file: 200.OK (249 ms)
2020-4-27 10:22:25.4|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (78 ms)

**Comment by tunes0710** [comment]
Actually.. have made my original watchlist public and used the ls099312947 number.
On advice from @Qstick am waiting a while before trying to add.

**Comment by in2survive** [comment]
I had the exact same issue, once I removed some items from the list it worked. My list had 524 items in my watchlist. My guess is the limit is 512. In any case, I copy the entire list to a temporary list and as you sync, deleted from the watchlist and continue to add them to add from the temp list... or create multiple list.

**Comment by tunes0710** [comment]
I've only got 1 item in this list as a test.
It seems like it may be a bug with IMDB, that I'm still waiting for them to fix. As when you try to go to the link for my IMDB feed, it 404's
