### ISSUE TITLE
radarr -- error on getting VideoLibrary.GetMovies

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#4405]
Radarr 3.0.0.2913
Kodi v18.6

Radarr sends GUI notification but errors on trying to update kodi library:
```
2020-5-8 18:37:46.9|Trace|HttpClient|Req: [POST] http://192.168.111.11:9999/jsonrpc: GUI.ShowNotification("Radarr - Downloaded", "Valley Girl (2020) [WEBDL-720p] https://www.imdb.com/title/tt1266036/", "https://raw.github.com/Radarr/Radarr/develop/Logo/64.png", 2000)
2020-5-8 18:37:46.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2020-5-8 18:37:47.0|Trace|HttpClient|Res: [POST] http://192.168.111.11:9999/jsonrpc: 200.OK (22 ms)
2020-5-8 18:37:47.0|Trace|HttpClient|Response content (47 bytes): {"id":"ac7c335f","jsonrpc":"2.0","result":"OK"}
2020-5-8 18:37:47.0|Trace|XbmcJsonApiProxy|Response: {"id":"ac7c335f","jsonrpc":"2.0","result":"OK"}
2020-5-8 18:37:47.0|Trace|XbmcJsonApiProxy|Looking for error in response, {"id":"ac7c335f","jsonrpc":"2.0","result":"OK"}
2020-5-8 18:37:47.0|Trace|HttpClient|Req: [POST] http://192.168.111.11:9999/jsonrpc: VideoLibrary.GetMovies("file", "imdbnumber")
2020-5-8 18:37:47.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2020-5-8 18:37:47.0|Trace|HttpClient|Res: [POST] http://192.168.111.11:9999/jsonrpc: 200.OK (1 ms)
2020-5-8 18:37:47.0|Trace|HttpClient|Response content (214 bytes): {"error":{"code":-32602,"data":{"method":"VideoLibrary.GetMovies","stack":{"message":"Invalid type string received","name":"properties","type":"array"}},"message":"Invalid params."},"id":"a1cde968","jsonrpc":"2.0"}
2020-5-8 18:37:47.0|Trace|XbmcJsonApiProxy|Response: {"error":{"code":-32602,"data":{"method":"VideoLibrary.GetMovies","stack":{"message":"Invalid type string received","name":"properties","type":"array"}},"message":"Invalid params."},"id":"a1cde968","jsonrpc":"2.0"}
2020-5-8 18:37:47.0|Trace|XbmcJsonApiProxy|Looking for error in response, {"error":{"code":-32602,"data":{"method":"VideoLibrary.GetMovies","stack":{"message":"Invalid type string received","name":"properties","type":"array"}},"message":"Invalid params."},"id":"a1cde968","jsonrpc":"2.0"}
2020-5-8 18:37:47.0|Debug|XbmcService|Unexpected character encountered while parsing value: {. Path 'error.data', line 1, position 32. (Json snippet 'ode":-32602,"data":{<--error-->"method":"VideoLibra')

[v3.0.0.2911] Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'error.data', line 1, position 32. (Json snippet 'ode":-32602,"data":{<--error-->"method":"VideoLibra')
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'error.data', line 1, position 32.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in d:\a\1\s\src\NzbDrone.Common\Serializer\Json.cs:line 48
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in d:\a\1\s\src\NzbDrone.Common\Serializer\Json.cs:line 48
   at NzbDrone.Core.Notifications.Xbmc.XbmcJsonApiProxy.CheckForError(HttpResponse response) in d:\a\1\s\src\NzbDrone.Core\Notifications\Xbmc\XbmcJsonApiProxy.cs:line 100
   at NzbDrone.Core.Notifications.Xbmc.XbmcJsonApiProxy.ProcessRequest(XbmcSettings settings, String method, Object[] parameters) in d:\a\1\s\src\NzbDrone.Core\Notifications\Xbmc\XbmcJsonApiProxy.cs:line 86
   at NzbDrone.Core.Notifications.Xbmc.XbmcJsonApiProxy.GetMovies(XbmcSettings settings) in d:\a\1\s\src\NzbDrone.Core\Notifications\Xbmc\XbmcJsonApiProxy.cs:line 62
   at NzbDrone.Core.Notifications.Xbmc.XbmcService.GetMoviePath(XbmcSettings settings, Movie movie) in d:\a\1\s\src\NzbDrone.Core\Notifications\Xbmc\XbmcService.cs:line 60
   at NzbDrone.Core.Notifications.Xbmc.XbmcService.UpdateMovieLibrary(XbmcSettings settings, Movie movie) in d:\a\1\s\src\NzbDrone.Core\Notifications\Xbmc\XbmcService.cs:line 85
```

using ARC client and testing rpc call myself I see it responds back without any problems
```
{
  "jsonrpc": "2.0",
  "method": "VideoLibrary.GetMovies",
  "params": {
    "properties": [
      "file",
      "imdbnumber"
    ]
  },
  "id": "1"
}
```
```
{"id":"1","jsonrpc":"2.0","result":{"limits":{"end":2030,"start":0,"total":2030},"movies":[{"file":"smb://server/Movies/Movies ... 64-NTG.mkv","imdbnumber":"tt1266036","label":"Valley Girl","movieid":2152}]}}
```

**Comment by thezoggy** [comment]
looks like it may have broke during the  RestSharp to HttpClient conversion?

**Comment by Qstick** [comment]
Thanks for the report @thezoggy
