### ISSUE TITLE
Unable to send OnGrab notification to: Notify Slack: The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by jaretclifton** [Radarr/Radarr#4411]
**Describe the bug**
"Unable to send OnGrab notification to: Notify Slack: The request was aborted: Could not create SSL/TLS secure channel" displayed in the log. No message makes it to Slack. A restart of Radarr resolves the issue for a short period of time, usually less than 45 minutes.

**To Reproduce**
1. Standard install of Radarr 0.2.0.1480
2. Configure Slack endpoint for on-grab and on-import
3. Expect messages
4. Check log for errors

**Expected behavior**
Both on-grab and on-import to consistently be delivered to Slack

**Work Around**
I created a scheduled task to run every 15 minutes that restarts Radarr. This seems to work fairly well but can interfere with Radarr jobs that are running when the service is restarted.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Mono Version: N/A
 - Browser and Version: N/A
 - Version 0.2.0.1480

**Debug Logs**
Log was too large for pastebin but here is the relevant snippet:

2020-5-12 09:28:30.5|Error|NotificationService|Unable to send OnGrab notification to: Notify Slack

[v0.2.0.1480] System.Net.WebException: The request was aborted: **Could not create SSL/TLS secure channel.**
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 117
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 60
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 121
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 57
   at NzbDrone.Core.Notifications.Slack.SlackProxy.SendPayload(SlackPayload payload, SlackSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Slack\SlackProxy.cs:line 37
   at NzbDrone.Core.Notifications.Slack.Slack.OnGrab(GrabMessage message) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Slack\Slack.cs:line 46
   at NzbDrone.Core.Notifications.NotificationService.Handle(MovieGrabbedEvent message) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\NotificationService.cs:line 85

**Comment by ta264** [comment]
You neglected to fill in the template which I think would highlight that your mono is too old (4.6.2 is too old) and needs upgrading

**Comment by ta264** [comment]
Uh I apologize, you say it's windows. I neglected to read it properly :)

In any case, jump on the discord for support please
