### ISSUE TITLE
ERROR when importing: Error occurred while executing task RefreshMovie: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by seanvree** [Radarr/Radarr#443]
Windows 10E
Radarr Ver. 0.2.0.226 develop

I get a lot of these errors when trying to import a movie from disk:

System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.ToUrlSlug(String value) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 544
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieInfo(Int32 TmdbId) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 89
   at NzbDrone.Core.Tv.RefreshMovieService.RefreshMovieInfo(Movie movie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\RefreshMovieService.cs:line 54
   at NzbDrone.Core.Tv.RefreshMovieService.Execute(RefreshMovieCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\RefreshMovieService.cs:line 113
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 4

**Comment by galli-leo** [comment]
Which movie is that?

**Comment by seanvree** [comment]
I'm not sure, I just went thru and was clicking the PLUS sign and started seeing these errors.

**Comment by onedr0p** [comment]
How long have you had radarr running for? I haven't seen that error ever since I wiped radarr and reinstalled.

**Comment by seanvree** [comment]
For about 3 days.  

I just reimported all of my movies (about 1,200), it added most of them, but then it says "missing" next to about 50% of them. Not sure if it takes time update the library from disk?

**Comment by Benni-chan** [comment]
do you have folders/files without a year in the name?
that was my main reason for "missing" after I added movies from my folders.

**Comment by seanvree** [comment]
Yeah, all of my folders have the year in the name as well as the file name. Isn't that how it's supposed to be?

**Comment by seanvree** [comment]
so this is happening to all my downloaded movies via my torrent client (deluge) but not NZBs:

System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Download.CompletedDownloadService.<>c.<Import>b__11_3(ImportResult v) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\CompletedDownloadService.cs:line 138
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Download.CompletedDownloadService.Import(TrackedDownload trackedDownload) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\CompletedDownloadService.cs:line 136
   at NzbDrone.Core.Download.CompletedDownloadService.Process(TrackedDownload trackedDownload, Boolean ignoreWarnings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\CompletedDownloadService.cs:line 113
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientItems(IDownloadClient downloadClient, DownloadClientItem downloadItem) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 12

**Comment by galli-leo** [comment]
@seanvree Are you on the latest nightly?

**Comment by seanvree** [comment]
@galli-leo i'm on Radarr Ver. 0.2.0.238 develop

**Comment by onedr0p** [comment]
@seanvree do you still have this problem on the latest version?

**Comment by seanvree** [comment]
@onedr0p 

Yes, I'm on develop 0.2.0.375


System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Download.Pending.PendingReleaseService.GetPendingQueue() in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Pending\PendingReleaseService.cs:line 133
   at NzbDrone.Api.Queue.QueueModule.GetQueueItems() in C:\projects\radarr-usby1\src\NzbDrone.Api\Queue\QueueModule.cs:line 32
   at NzbDrone.Api.Queue.QueueModule.GetQueue() in C:\projects\radarr-usby1\src\NzbDrone.Api\Queue\QueueModule.cs:line 27
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourceAll>b__32_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 111
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken contex

**Comment by seanvree** [comment]
Okay, I found out what causes this, or at least what's triggering it.  

If you send a release to your downloader, (in my case SABNZBD), for some reason it can't get the queue status from Sabnzbd for like 10 minutes and then starts generating these errors. .  It looks like it's working with torrents (Deluge in my case).  

It's weird because even tho the releases are downloading in Sabnzbd, it just doesn't show up in the Radarr Queue for approx 10 minutes, As soon as they do appear in the Radarr queue, the errors stop.

**Comment by seanvree** [comment]
also related to : https://github.com/Radarr/Radarr/issues/1023#issuecomment-287501705

**Comment by galli-leo** [comment]
@seanvree Can you test and see if this works on the current version?
