### ISSUE TITLE
"Force add to download queue" fails with different release year

### ISSUE THREAD

**Issue by AnonTester** [Radarr/Radarr#4435]
**Describe the bug**
Trying to download a movie manually "force add to download queue" option with a different release year to the data in Radarr from the Radarr search results tab opens the option to force download it and add the different release year to the movie properties. Clicking on force download shows a spinner for a little while, then the spinner disappears but the option window remains open, the alternative year has not been added to the properties and the release is not being downloaded.

**Expected behavior**
Year should be added to movie details and file should be downloaded. Even when there is some Radarr error, the main use of this option is to force the download.

**Desktop (please complete the following information):**
 - OS: Linux/Synology
 - Mono Version: 5.20.1.34
 - Radarr Ver. 0.2.0.1491

**Debug Logs**

Request Failed: Error while calling api: Internal Server Error
Full error(s): Internal Server Error (500, RayId: 8092d470-594c-4a4a-9abf-88f4dd3382d0), Details: An error has occurred and this resource cannot be displayed.

NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Internal Server Error
Full error(s): Internal Server Error (500, RayId: 8092d470-594c-4a4a-9abf-88f4dd3382d0), Details: An error has occurred and this resource cannot be displayed.
  at NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIClient.Execute[T] (NzbDrone.Common.Http.HttpRequest request) [0x0004f] in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\RadarrAPI\RadarrAPIClient.cs:77 
  at NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIClient.AddNewAlternativeYear (System.Int32 year, System.Int32 tmdbId) [0x00063] in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\RadarrAPI\RadarrAPIClient.cs:174 
  at NzbDrone.Api.Movies.AlternativeYearModule.AddYear (NzbDrone.Api.Movies.AlternativeYearResource altYear) [0x00048] in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\AlternativeYearModule.cs:46 
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_CreateResource>b__41_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:161 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0

**Comment by martonbaksa** [comment]
Hi!
I seem to be getting the same issue with Alternate Name force downloads. 
Please see below:

`NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Internal Server Error
Full error(s): Internal Server Error (500, RayId: 8bd5760e-c6fb-4a90-ad27-b3847b85708a), Details: An error has occurred and this resource cannot be displayed.
   at NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIClient.Execute[T](HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\RadarrAPI\RadarrAPIClient.cs:line 77
   at NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIClient.AddNewAlternativeTitle(AlternativeTitle title, Int32 TmdbId) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\RadarrAPI\RadarrAPIClient.cs:line 159
   at NzbDrone.Api.Movies.AlternativeTitleModule.AddTitle(AlternativeTitleResource altTitle) in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\AlternativeTitleModule.cs:line 44
   at NzbDrone.Api.REST.RestModule`1.<set_CreateResource>b__41_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 161
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
`

**Comment by Qstick** [comment]
Should be fixed

**Comment by ahiguero** [comment]
as the fix been pushed to the main repository?

**Comment by Qstick** [comment]
No, we have an update bug in nightly to get sorted

**Comment by Mannekino** [comment]
I think I've encountered the same issue. I'm running Radarr in a FreeNAS jail. I'm not using the plugin from FreeNAS but a manual jail installation with the package from the FreeBSD repository. I'm trying to add a movie that is listed as 2019 but all the download results are listed as 2020. When I press "Force Download" nothing happens.

<pre>Request Failed: Error while calling api: Internal Server Error
Full error(s): Internal Server Error (500, RayId: 8167196a-fc83-4dd7-a00c-1f02bae81330), Details: An error has occurred and this resource cannot be displayed.</pre>

<pre>NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Internal Server Error
Full error(s): Internal Server Error (500, RayId: 8167196a-fc83-4dd7-a00c-1f02bae81330), Details: An error has occurred and this resource cannot be displayed.
  at NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIClient.Execute[T] (NzbDrone.Common.Http.HttpRequest request) [0x0004f] in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\RadarrAPI\RadarrAPIClient.cs:77 
  at NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIClient.AddNewAlternativeYear (System.Int32 year, System.Int32 tmdbId) [0x00063] in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\RadarrAPI\RadarrAPIClient.cs:174 
  at NzbDrone.Api.Movies.AlternativeYearModule.AddYear (NzbDrone.Api.Movies.AlternativeYearResource altYear) [0x00048] in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\AlternativeYearModule.cs:46 
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_CreateResource>b__41_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:161 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0</pre>
