### ISSUE TITLE
Trakt username with apostrophe is not found with user list

### ISSUE THREAD

**Issue by mwinandy** [Radarr/Radarr#4440]
When the username contain ' it fail to import user lists

Use Trakt User List with username that contain ' inside, it will fail to import.

```
[v3.0.0.2955] NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [https://api.trakt.tv/users/Lil'Monster/watchlist/movies?limit=100]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 100
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchNetImportResponse(NetImportRequest request) in d:\a\1\s\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 137
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in d:\a\1\s\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 113
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in d:\a\1\s\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 151

```

for account `lil-monster-e2b533cd-3afa-4bae-8896-704cb034391c` - `Lil'Monster`

May there's inside the api the right username next to the UUID.

I change my username and it works.

Version 3.0.0.2955

**Debug Logs**
```
2020-5-18 00:13:52.8|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to list, check the log for more details
2020-5-18 00:15:45.1|Warn|HttpClient|HTTP Error - Res: [GET] https://api.trakt.tv/users/Lil'Monster/watchlist/movies?limit=100: 404.NotFound
2020-5-18 00:15:45.1|Warn|TraktUserImport|Unable to connect to list

[v3.0.0.2955] NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [https://api.trakt.tv/users/Lil'Monster/watchlist/movies?limit=100]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 100
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchNetImportResponse(NetImportRequest request) in d:\a\1\s\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 137
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in d:\a\1\s\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 113
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in d:\a\1\s\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 151
```

**Comment by geogolem** [comment]
just for cross referencing purposes - this could be related to: https://github.com/Radarr/Radarr/issues/4168 but its not the same issue..
