### ISSUE TITLE
Couldn't add report to download queue. %INSERT_MOVIE_NAME [1080p / Blu-ray / H.264 / MKV / Checked / Remux / Extras]: Invalid torrent file specified

### ISSUE THREAD

**Issue by MrHollowPS** [Radarr/Radarr#4560]
**Describe the bug**
No movies are sent to the download client

Repro Steps:
1. Go to movies
2. Choose a movie
3. Press the "search movie" option if there's a release that' s supposed to be downloaded

**Expected behavior**
Torrent file is sent to the download client.

**Platform Information (please complete the following information):**
 - OS: Linux server 5.4.0-39-generic #43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Mono Version: running on docker
 - Browser and Version: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
 - Radarr Version : 3.0.0.3107
 - Package Version: 3.0.0.3107-ls12 by linuxserver.io
 - .NET Core: Yes
 - Docker: Yes
 - DB Migration: 176
 - AppData directory: /config
 - Startup directory: /app/radarr/bin
 - Mode: Console

**Debug Logs**

Message
Couldn't add report to download queue. Guns.Akimbo.2019.Extras.1080p.Remux.AVC.DD 2.0-Gyroscope [1080p / Blu-ray / H.264 / MKV / Checked / Remux / Extras]: Invalid torrent file specified
Exception
MonoTorrent.TorrentException: Invalid torrent file specified
 ---> MonoTorrent.BEncoding.BEncodingException: Could not find what value to decode
   at MonoTorrent.BEncoding.BEncodeDecoder.Decode(RawReader reader, Int32 read)
   at MonoTorrent.BEncoding.BEncodeDecoder.Decode(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedValue.Decode(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedValue.Decode(Stream stream)
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   --- End of inner exception stack trace ---
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   at MonoTorrent.Torrent.Load(Byte[] data)
   at NzbDrone.Core.MediaFiles.TorrentInfo.TorrentFileInfoReader.GetHashFromTorrentFile(Byte[] fileContents) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\TorrentInfo\TorrentFileInfoReader.cs:line 14
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteMovie remoteMovie, String torrentUrl) in d:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 189
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteMovie remoteMovie) in d:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 123
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in d:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 73
   at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions(List`1 decisions) in d:\a\1\s\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:line 76

[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4864197/radarr.debug.txt)

**Comment by MrHollowPS** [comment]
Found the problem, I was using a reverse proxy and this was causing issues... Sorry for raising this in error.
