### ISSUE TITLE
"No Results Found" but reloading page and searching again will return search results

### ISSUE THREAD

**Issue by dannyvfilms** [Radarr/Radarr#4594]
I noticed some new additions weren't downloading, so I load the movie page (Log example "The Cove") and Search returns no results. Seeing no issues reported with indexers (and I've seen this before), I reload the page and click Search again. Sidenote, the "Search movie" button doesn't seem to do anything when "No results found" is displayed in the Search tab.

Anywho, reloading the movie one or two times and searching again usually does the trick. After that, the page seems to consistently return search results.

OS: UnRAID
Chrome V88

Version
3.0.0.3112
Package Version
3.0.0.3112-ls13 by linuxserver.io

```
2020-7-15 14:25:39.1|Info|DiskScanService|Completed scanning disk for Tomorrow Never Dies
2020-7-15 14:25:39.1|Info|RefreshMovieService|Updating Info for Tomorrowland
2020-7-15 14:26:53.3|Warn|MediaCoverMapper|File /config/MediaCover/3672/poster.jpg not found
2020-7-15 14:26:53.7|Warn|MediaCoverMapper|File /config/MediaCover/1479/poster.jpg not found
2020-7-15 14:26:53.7|Warn|MediaCoverMapper|File /config/MediaCover/3672/poster.jpg not found
2020-7-15 14:27:01.7|Warn|MediaCoverMapper|File /config/MediaCover/3672/poster.jpg not found
2020-7-15 14:27:04.9|Warn|MediaCoverMapper|File /config/MediaCover/3672/fanart.jpg not found
2020-7-15 14:27:04.9|Warn|MediaCoverMapper|File /config/MediaCover/3672/poster.jpg not found
2020-7-15 14:27:09.6|Error|TaskExtensions|Task Error

[v3.0.0.3112] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1060
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1043
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 996
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in d:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 180
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in d:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 143
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push[TCommand](TCommand command, CommandPriority priority, CommandTrigger trigger) in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandQueueManager.cs:line 135
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push(String commandName, Nullable`1 lastExecutionTime, Nullable`1 lastStartTime, CommandPriority priority, CommandTrigger trigger) in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandQueueManager.cs:line 144
   at NzbDrone.Core.Jobs.Scheduler.ExecuteCommands() in d:\a\1\s\src\NzbDrone.Core\Jobs\Scheduler.cs:line 42
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

2020-7-15 14:27:17.0|Info|NzbSearchService|Searching 3 indexers for [The Cove]
2020-7-15 14:27:19.2|Info|DownloadDecisionMaker|No results found
2020-7-15 14:27:23.6|Warn|MediaCoverMapper|File /config/MediaCover/3672/fanart.jpg not found
2020-7-15 14:27:23.6|Warn|MediaCoverMapper|File /config/MediaCover/3672/poster.jpg not found
2020-7-15 14:27:24.7|Info|NzbSearchService|Searching 3 indexers for [The Cove]
2020-7-15 14:27:26.8|Info|DownloadDecisionMaker|No results found
2020-7-15 14:27:27.5|Info|DiskScanService|Scanning disk for Tomorrowland
2020-7-15 14:27:27.5|Info|DiskScanService|Completed scanning disk for Tomorrowland
2020-7-15 14:27:27.5|Info|RefreshMovieService|Skipping refresh of movie: Tootsie
2020-7-15 14:27:27.5|Info|DiskScanService|Scanning disk for Tootsie
2020-7-15 14:27:27.5|Info|DiskScanService|Completed scanning disk for Tootsie
2020-7-15 14:27:27.5|Info|RefreshMovieService|Skipping refresh of movie: Top Gun
2020-7-15 14:27:27.5|Info|DiskScanService|Scanning disk for Top Gun
2020-7-15 14:27:27.5|Info|DiskScanService|Completed scanning disk for Top Gun
2020-7-15 14:27:27.5|Info|RefreshMovieService|Skipping refresh of movie: Top Hat
2020-7-15 14:27:27.5|Info|DiskScanService|Scanning disk for Top Hat
2020-7-15 14:27:27.5|Info|DiskScanService|Completed scanning disk for Top Hat
2020-7-15 14:27:27.5|Info|RefreshMovieService|Skipping refresh of movie: Top Secret!
2020-7-15 14:27:27.5|Info|DiskScanService|Scanning disk for Top Secret!
2020-7-15 14:27:27.5|Info|DiskScanService|Completed scanning disk for Top Secret!
2020-7-15 14:27:27.5|Info|RefreshMovieService|Skipping refresh of movie: Tora! Tora! Tora!
2020-7-15 14:27:27.5|Info|DiskScanService|Scanning disk for Tora! Tora! Tora!
2020-7-15 14:27:27.5|Info|DiskScanService|Completed scanning disk for Tora! Tora! Tora!
2020-7-15 14:27:27.5|Info|RefreshMovieService|Skipping refresh of movie: Total Recall
2020-7-15 14:27:27.5|Info|DiskScanService|Scanning disk for Total Recall
2020-7-15 14:27:27.5|Info|DiskScanService|Completed scanning disk for Total Recall
2020-7-15 14:27:27.5|Info|RefreshMovieService|Skipping refresh of movie: Total Recall
2020-7-15 14:27:27.5|Info|DiskScanService|Scanning disk for Total Recall
2020-7-15 14:27:27.5|Info|DiskScanService|Completed scanning disk for Total Recall
2020-7-15 14:27:27.5|Info|RefreshMovieService|Skipping refresh of movie: Touch of Evil
2020-7-15 14:27:27.5|Info|DiskScanService|Scanning disk for Touch of Evil
2020-7-15 14:27:27.5|Info|DiskScanService|Completed scanning disk for Touch of Evil
2020-7-15 14:27:27.5|Info|RefreshMovieService|Skipping refresh of movie: The Towering Inferno
2020-7-15 14:27:27.5|Info|DiskScanService|Scanning disk for The Towering Inferno
2020-7-15 14:27:27.5|Info|DiskScanService|Completed scanning disk for The Towering Inferno
2020-7-15 14:27:27.5|Info|RefreshMovieService|Skipping refresh of movie: The Town
2020-7-15 14:27:27.6|Info|DiskScanService|Scanning disk for The Town
2020-7-15 14:27:27.6|Info|DiskScanService|Completed scanning disk for The Town
2020-7-15 14:27:27.6|Info|RefreshMovieService|Skipping refresh of movie: Toy Story
2020-7-15 14:27:27.6|Info|DiskScanService|Scanning disk for Toy Story
2020-7-15 14:27:27.6|Info|DiskScanService|Completed scanning disk for Toy Story
2020-7-15 14:27:27.6|Info|RefreshMovieService|Skipping refresh of movie: Toy Story 2
2020-7-15 14:27:27.6|Info|DiskScanService|Scanning disk for Toy Story 2
2020-7-15 14:27:27.6|Info|DiskScanService|Completed scanning disk for Toy Story 2
2020-7-15 14:27:27.6|Info|RefreshMovieService|Skipping refresh of movie: Toy Story 3
2020-7-15 14:27:27.6|Info|DiskScanService|Scanning disk for Toy Story 3
2020-7-15 14:27:27.6|Info|DiskScanService|Completed scanning disk for Toy Story 3
2020-7-15 14:27:27.6|Info|RefreshMovieService|Skipping refresh of movie: Toy Story 4
2020-7-15 14:27:27.6|Info|DiskScanService|Scanning disk for Toy Story 4
2020-7-15 14:27:27.6|Info|DiskScanService|Completed scanning disk for Toy Story 4
2020-7-15 14:27:27.6|Info|RefreshMovieService|Skipping refresh of movie: Toy Story of Terror!
2020-7-15 14:27:27.6|Info|DiskScanService|Scanning disk for Toy Story of Terror!
2020-7-15 14:27:27.6|Info|DiskScanService|Completed scanning disk for Toy Story of Terror!
2020-7-15 14:27:27.6|Info|RefreshMovieService|Skipping refresh of movie: Toy Story That Time Forgot
2020-7-15 14:27:27.6|Info|DiskScanService|Scanning disk for Toy Story That Time Forgot
2020-7-15 14:27:27.6|Info|DiskScanService|Completed scanning disk for Toy Story That Time Forgot
2020-7-15 14:27:27.6|Info|RefreshMovieService|Skipping refresh of movie: Tracy Morgan: Black & Blue
2020-7-15 14:27:27.6|Info|DiskScanService|Scanning disk for Tracy Morgan: Black & Blue
2020-7-15 14:27:27.6|Info|DiskScanService|Completed scanning disk for Tracy Morgan: Black & Blue
2020-7-15 14:27:27.6|Info|RefreshMovieService|Skipping refresh of movie: Tracy Morgan: Bona Fide
2020-7-15 14:27:27.6|Info|DiskScanService|Scanning disk for Tracy Morgan: Bona Fide
2020-7-15 14:27:27.6|Info|DiskScanService|Completed scanning disk for Tracy Morgan: Bona Fide
2020-7-15 14:27:27.6|Info|RefreshMovieService|Skipping refresh of movie: Tracy Morgan: Life, Love & Lust
2020-7-15 14:27:27.6|Info|DiskScanService|Scanning disk for Tracy Morgan: Life, Love & Lust
2020-7-15 14:27:27.6|Info|DiskScanService|Completed scanning disk for Tracy Morgan: Life, Love & Lust
2020-7-15 14:27:27.6|Info|RefreshMovieService|Skipping refresh of movie: Tracy Morgan: Staying Alive
2020-7-15 14:27:27.6|Info|DiskScanService|Scanning disk for Tracy Morgan: Staying Alive
2020-7-15 14:27:27.6|Info|DiskScanService|Completed scanning disk for Tracy Morgan: Staying Alive
2020-7-15 14:27:27.6|Info|RefreshMovieService|Skipping refresh of movie: Trading Places
2020-7-15 14:27:27.6|Info|DiskScanService|Scanning disk for Trading Places
2020-7-15 14:27:27.6|Info|DiskScanService|Completed scanning disk for Trading Places
2020-7-15 14:27:27.6|Info|RefreshMovieService|Skipping refresh of movie: Train to Busan
2020-7-15 14:27:27.6|Info|DiskScanService|Scanning disk for Train to Busan
2020-7-15 14:27:27.6|Info|DiskScanService|Completed scanning disk for Train to Busan
2020-7-15 14:27:27.6|Info|RefreshMovieService|Skipping refresh of movie: Training Day
2020-7-15 14:27:27.7|Info|DiskScanService|Scanning disk for Training Day
2020-7-15 14:27:27.7|Info|DiskScanService|Completed scanning disk for Training Day
2020-7-15 14:27:27.7|Info|RefreshMovieService|Skipping refresh of movie: Trainspotting
2020-7-15 14:27:27.7|Info|MetadataService|Movie folder does not exist, skipping metadata creation
2020-7-15 14:27:27.7|Info|DiskScanService|Scanning disk for Trainspotting
2020-7-15 14:27:27.7|Info|DiskScanService|Completed scanning disk for Trainspotting
2020-7-15 14:27:27.7|Info|RefreshMovieService|Skipping refresh of movie: Transcendence
2020-7-15 14:27:27.7|Info|DiskScanService|Scanning disk for Transcendence
2020-7-15 14:27:27.7|Info|DiskScanService|Completed scanning disk for Transcendence
2020-7-15 14:27:27.7|Info|RefreshMovieService|Skipping refresh of movie: The Transcendents
2020-7-15 14:27:27.7|Info|DiskScanService|Scanning disk for The Transcendents
2020-7-15 14:27:27.7|Info|DiskScanService|Completed scanning disk for The Transcendents
2020-7-15 14:27:27.7|Info|RefreshMovieService|Skipping refresh of movie: Transformers
2020-7-15 14:27:27.7|Info|DiskScanService|Scanning disk for Transformers
2020-7-15 14:27:27.7|Info|DiskScanService|Completed scanning disk for Transformers
2020-7-15 14:27:27.7|Info|RefreshMovieService|Skipping refresh of movie: Transformers: Age of Extinction
2020-7-15 14:27:27.7|Info|DiskScanService|Scanning disk for Transformers: Age of Extinction
2020-7-15 14:27:27.7|Info|DiskScanService|Completed scanning disk for Transformers: Age of Extinction
2020-7-15 14:27:27.7|Info|RefreshMovieService|Skipping refresh of movie: Transformers: Dark of the Moon
2020-7-15 14:27:27.7|Info|DiskScanService|Scanning disk for Transformers: Dark of the Moon
2020-7-15 14:27:27.7|Info|DiskScanService|Completed scanning disk for Transformers: Dark of the Moon
2020-7-15 14:27:27.7|Info|RefreshMovieService|Skipping refresh of movie: Transformers: The Last Knight
2020-7-15 14:27:27.7|Info|DiskScanService|Scanning disk for Transformers: The Last Knight
2020-7-15 14:27:27.7|Info|DiskScanService|Completed scanning disk for Transformers: The Last Knight
2020-7-15 14:27:27.7|Info|RefreshMovieService|Updating Info for The Transformers: The Movie
2020-7-15 14:27:28.5|Error|CommandExecutor|Error occurred while executing task RefreshMonitoredDownloads

[v3.0.0.3112] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in C:\projects\dapper\Dapper\SqlMapper.cs:line 2806
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 568
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 441
   at NzbDrone.Core.Datastore.BasicRepository`1.UpdateFields(IDbConnection connection, IDbTransaction transaction, TModel model, List`1 propertiesToUpdate) in d:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 371
   at NzbDrone.Core.Datastore.BasicRepository`1.SetFields(TModel model, Expression`1[] properties) in d:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 321
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Update(CommandModel command, CommandStatus status, String message) in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandQueueManager.cs:line 241
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 118
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44

2020-7-15 14:27:30.1|Warn|MediaCoverMapper|File /config/MediaCover/3672/fanart.jpg not found
2020-7-15 14:27:30.1|Warn|MediaCoverMapper|File /config/MediaCover/3672/poster.jpg not found
2020-7-15 14:27:36.1|Info|NzbSearchService|Searching 3 indexers for [The Cove]
2020-7-15 14:27:38.2|Info|DownloadDecisionMaker|Processing 10 releases
2020-7-15 14:27:47.6|Info|DownloadService|Report sent to Transmission. The.Cove.2009.1080p.BluRay.x264-CiNEFiLE
2020-7-15 14:28:17.8|Error|EventAggregator|HistoryService failed while processing [MovieGrabbedEvent]

[v3.0.0.3112] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1060
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1043
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 996
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in d:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 180
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in d:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 143
   at NzbDrone.Core.History.HistoryService.Handle(MovieGrabbedEvent message) in d:\a\1\s\src\NzbDrone.Core\History\HistoryService.cs:line 144
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in d:\a\1\s\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 95
```

**Comment by Qstick** [comment]
First... Upgrade to latest build
