### ISSUE TITLE
Migrating from 0.2 to 0.3 fails with "The given key '1' was not present in the dictionary."

### ISSUE THREAD

**Issue by wsw70** [Radarr/Radarr#4662]
**Describe the bug**

Upgrade from 0.2.0.1504 to 0.3 in a docker environment leads to a "The given key '1' was not present in the dictionary." error (and no movies at all).

I read the disclaimer during the startup, but I hope this maybe will be useful for debugging.

**To Reproduce**

A correctly running 0.2 version is started via docker with the following `docker-compose` configuration:

```
  radarr:
    container_name: radarr
    environment:
      - PUID=999
      - PGID=999
      - TZ=Europe/Paris
    image: linuxserver/radarr
    restart: unless-stopped
    volumes:
      - /etc/docker/data/radarr:/config
      - /data/Movies:/movies
      - /data/deluge:/downloads
```

When stopping the container, changing `image: linuxserver/radarr` to `image: linuxserver/radarr:preview` (which is as of now 3.0.0.3308-ls17` and restarting the container, radarr displays a `The given key '1' was not present in the dictionary.` error.

A similar behaviour  was mentioned in https://github.com/Radarr/Radarr/issues/4396 but I have no movies altogether (and the "Edit Movies" button disabled as there are no movies)

**Expected behavior**

A seamless migration to aphodite :)

*Note: recovering the configuration directory from backup and moving back to the stable version thankfully restores a working Radarr*

**Screenshots**

![image](https://user-images.githubusercontent.com/1345886/88943646-06d38000-d28c-11ea-98e9-33248a224c26.png)

**Platform Information (please complete the following information):**
 - OS: [e.g. Windows]
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Radarr Version [e.g. 3.0.0.2956]

**Debug Logs**

## Startup logs

```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
Radarr: https://opencollective.com/radarr
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    999
User gid:    999
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-warning: executing...
******************************************************
******************************************************
*                                                    *
*                                                    *
*         This image is for development only         *
*                                                    *
*              Use at your own peril                 *
* It will likely have bugs and not function properly *
*                                                    *
*                                                    *
******************************************************
******************************************************
[cont-init.d] 90-warning: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Bootstrap: Starting Radarr - /app/radarr/bin/Radarr.dll - Version 3.0.0.3308
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Info] Router: Application mode: Interactive
[Info] MigrationController: *** Migrating data source=/config/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] MigrationLoggerProvider: *** 130: remove_wombles_kickass migrating ***
[Info] remove_wombles_kickass: Starting migration to 130
[Info] MigrationLoggerProvider: *** 152: add_custom_filters migrating ***
[Info] add_custom_filters: Starting migration to 152
[Info] MigrationLoggerProvider: *** 153: indexer_client_status_search_changes migrating ***
[Info] indexer_client_status_search_changes: Starting migration to 153
[Info] MigrationLoggerProvider: *** 154: add_language_to_files_history_blacklist migrating ***
[Info] add_language_to_files_history_blacklist: Starting migration to 154
[Info] MigrationLoggerProvider: *** 155: add_update_allowed_quality_profile migrating ***
[Info] add_update_allowed_quality_profile: Starting migration to 155
[Info] MigrationLoggerProvider: *** 156: add_download_client_priority migrating ***
[Info] add_download_client_priority: Starting migration to 156
[Info] MigrationLoggerProvider: *** 157: remove_growl_prowl migrating ***
[Info] remove_growl_prowl: Starting migration to 157
[Info] MigrationLoggerProvider: *** 158: remove_plex_hometheatre migrating ***
[Info] remove_plex_hometheatre: Starting migration to 158
[Info] MigrationLoggerProvider: *** 159: add_webrip_qualites migrating ***
[Info] add_webrip_qualites: Starting migration to 159
[Info] MigrationLoggerProvider: *** 160: health_issue_notification migrating ***
[Info] health_issue_notification: Starting migration to 160
[Info] MigrationLoggerProvider: *** 161: speed_improvements migrating ***
[Info] speed_improvements: Starting migration to 161
[Info] MigrationLoggerProvider: *** 162: fix_profile_format_default migrating ***
[Info] fix_profile_format_default: Starting migration to 162
[Info] MigrationLoggerProvider: *** 163: task_duration migrating ***
[Info] task_duration: Starting migration to 163
[Info] MigrationLoggerProvider: *** 164: movie_collections_crew migrating ***
[Info] movie_collections_crew: Starting migration to 164
[Info] MigrationLoggerProvider: *** 165: remove_custom_formats_from_quality_model migrating ***
[Info] remove_custom_formats_from_quality_model: Starting migration to 165
[Info] MigrationLoggerProvider: *** 166: fix_tmdb_list_config migrating ***
[Info] fix_tmdb_list_config: Starting migration to 166
[Info] MigrationLoggerProvider: *** 167: remove_movie_pathstate migrating ***
[Info] remove_movie_pathstate: Starting migration to 167
[Info] MigrationLoggerProvider: *** 168: custom_format_rework migrating ***
[Info] custom_format_rework: Starting migration to 168
[Info] MigrationLoggerProvider: *** 169: custom_format_scores migrating ***
[Info] custom_format_scores: Starting migration to 169
[Info] MigrationLoggerProvider: *** 170: fix_trakt_list_config migrating ***
[Info] fix_trakt_list_config: Starting migration to 170
[Info] MigrationLoggerProvider: *** 171: quality_definition_preferred_size migrating ***
[Info] quality_definition_preferred_size: Starting migration to 171
[Info] MigrationLoggerProvider: *** 172: add_download_history migrating ***
[Info] add_download_history: Starting migration to 172
[Info] MigrationLoggerProvider: *** 173: net_import_status migrating ***
[Info] net_import_status: Starting migration to 173
[Info] MigrationLoggerProvider: *** 174: email_multiple_addresses migrating ***
[Info] email_multiple_addresses: Starting migration to 174
[Info] MigrationLoggerProvider: *** 175: remove_chown_and_folderchmod_config migrating ***
[Info] remove_chown_and_folderchmod_config: Starting migration to 175
[Info] MigrationLoggerProvider: *** 176: movie_recommendations migrating ***
[Info] movie_recommendations: Starting migration to 176
[Info] MigrationLoggerProvider: *** 177: language_improvements migrating ***
[Info] language_improvements: Starting migration to 177
[Info] MigrationLoggerProvider: *** 178: new_list_server migrating ***
[Info] new_list_server: Starting migration to 178
[Info] MigrationLoggerProvider: *** 179: movie_translation_indexes migrating ***
[Info] movie_translation_indexes: Starting migration to 179
[Info] WebHostController: Listening on the following URLs:
[Info] WebHostController:   http://*:7878
[Info] RadarrBootstrapper: Starting Web Server
[Info] UpdaterConfigProvider: Update mechanism BuiltIn not supported in the current configuration, changing to Docker.
[Info] UpdaterConfigProvider: External updater uses branch aphrodite instead of the currently selected develop, changing to aphrodite.
[Info] CommandExecutor: Starting 2 threads for tasks.
[Error] TaskExtensions: Task Error
[v3.0.0.3308] System.Collections.Generic.KeyNotFoundException: The given key '1' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NzbDrone.Core.Movies.MovieRepository.<>c__DisplayClass5_0.<All>b__3(Movie movie, AlternativeTitle altTitle, MovieFile file) in d:\a\1\s\src\NzbDrone.Core\Movies\MovieRepository.cs:line 97
   at NzbDrone.Core.Datastore.SqlMapperExtensions.<>c__DisplayClass2_0`4.<Query>g__MapWithLazy|0(TFirst first, TSecond second, TThird third) in d:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\SqlMapperExtensions.cs:line 52
   at Dapper.SqlMapper.<>c__DisplayClass158_0`8.<GenerateMapper>b__1(IDataReader r) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1542
   at Dapper.SqlMapper.MultiMapImpl[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn, IDataReader reader, Identity identity, Boolean finalize)+MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1442
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.MultiMap[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, String sql, Delegate map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1402
   at Dapper.SqlMapper.Query[TFirst,TSecond,TThird,TReturn](IDbConnection cnn, String sql, Func`4 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1278
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[TFirst,TSecond,TThird,TReturn](IDatabase db, String sql, Func`4 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in d:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\SqlMapperExtensions.cs:line 58
   at NzbDrone.Core.Datastore.SqlMapperExtensions.QueryJoined[T,T2,T3](IDatabase db, SqlBuilder builder, Func`4 mapper) in d:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\SqlMapperExtensions.cs:line 134
   at NzbDrone.Core.Movies.MovieRepository.All() in d:\a\1\s\src\NzbDrone.Core\Movies\MovieRepository.cs:line 99
   at NzbDrone.Core.Movies.MovieService.GetAllMovies() in d:\a\1\s\src\NzbDrone.Core\Movies\MovieService.cs:line 209
   at NzbDrone.Core.HealthCheck.Checks.RemovedMovieCheck.Check() in d:\a\1\s\src\NzbDrone.Core\HealthCheck\Checks\RemovedMovieCheck.cs:line 23
   at NzbDrone.Core.HealthCheck.HealthCheckService.<>c.<PerformHealthCheck>b__11_0(IProvideHealthCheck c) in d:\a\1\s\src\NzbDrone.Core\HealthCheck\HealthCheckService.cs:line 72
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.HealthCheck.HealthCheckService.PerformHealthCheck(IProvideHealthCheck[] healthChecks) in d:\a\1\s\src\NzbDrone.Core\HealthCheck\HealthCheckService.cs:line 75
   at NzbDrone.Core.HealthCheck.HealthCheckService.HandleAsync(ApplicationStartedEvent message) in d:\a\1\s\src\NzbDrone.Core\HealthCheck\HealthCheckService.cs:line 110
   at NzbDrone.Core.Messaging.Events.EventAggregator.<>c__DisplayClass6_2`1.<PublishEvent>b__2() in d:\a\1\s\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 122
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

## Debug logs

```
Component | Message | Time |  -- | -- | -- | --
  | RadarrErrorPipeline | Request Failed. GET /api/v3/movie: The given key '1' was not present in the dictionary. | 5:39pm |  
  | TaskExtensions | Task Error: The given key '1' was not present in the dictionary. | 5:39pm |  
  | CommandExecutor | Starting 2 threads for tasks. | 5:39pm |  
  | Database | Log database compressed | 5:39pm |  
  | Database | Vacuuming Log database | 5:39pm
```

**Comment by Qstick** [comment]
You have a movie tied to a bad profile most likely

**Comment by wsw70** [comment]
@Qstick : thanks for the quick follow-up, but what does this mean, exactly? (and how to fix it, if possible?)

**Comment by Qstick** [comment]
At some point in the past v 0.2 allowed deletion of profiles without checking to see if they were in use. I've seen one or two other users with the same issue when they try to migrate to V3 and the issue was present in their old DB, V3 has a different data map for movies and profiles which might cause the hang up. 

Quick fix is to look in your DB for any movies with a profile ID that is not in the profile table. from our side we should probably do a migration to fix this for users who have this problem from v0.2. Assuming that is the problem in this case

**Comment by wsw70** [comment]
@Qstick Thank you for the details.

Since the quick fix probably requires SQL wizardy - is it possible to start from scratch and simply re-import all the movies into a blank database?

**Comment by Qstick** [comment]
I'd like to avoid you having to do that. I can stick a migration up tonight if you want to test it.

**Comment by wsw70** [comment]
@Qstick certainly, especially if this can help others. Just let me know 
(I will be getting back from vacation tomorrow but I will be able to do the test over the week-end)

**Comment by Qstick** [comment]
Dupe #4396
