### ISSUE TITLE
iMDB List Import Broken

### ISSUE THREAD

**Issue by franco-101** [Radarr/Radarr#4907]
I am running the latest developer version of Radarr from inside of Windows.

The issue I am experiencing is that my iMDB list is no longer auto updating/importing into Radarr. I have tried with a fresh install  of Radarr and the same iMDB list, but still get the same error. In the logs each time I can see a stuck film that I have removed from my list but the API does not appear to pick this up.

I think the problem might be to do with https://api.radarr.video/v2/ caching my list.

`
NzbDrone.Core.Exceptions.MovieNotFoundException: Movie with imdbid Movie not found. was not found, it may have been removed from IMDb.
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieInfo(Int32 TmdbId, Profile profile, Boolean hasPreDBEntry) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 74
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie(Movie movie) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 642
`

**Comment by ta264** [comment]
We're not fixing anything but showstopper bugs on 0.2. Try V3 if it's important to you, it's been totally reworked there. But beware V3 is still alpha.
