### ISSUE TITLE
MovieMissingModule failed while processing [MovieDownloadedEvent]

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#492]
movie completed but has error:

`MovieMissingModule failed while processing [MovieDownloadedEvent]: Object reference not set to an instance of an object.`

guessing its because the movie had a sub file but radarr didnt handle thus puked on it? end result is just .mkv file

**Comment by seanvree** [comment]
I'm having the same issue:

https://github.com/Radarr/Radarr/issues/443

**Comment by galli-leo** [comment]
Is this on the latest nightly?

**Comment by thezoggy** [comment]
Using: `Radarr Ver. 0.2.0.238`

**Comment by galli-leo** [comment]
@thezoggy can you provide a more detailed log of the error?

**Comment by thezoggy** [comment]
since this was a fresh install the log level was at info, so theres not much.. ive since changed it to debug and was waiting for it to happen again...  here is all that it showed right before/during/after:
```
17-1-27 19:50:18.1|Info|Sabnzbd|Adding report [At.Cafe.6.2016.720p.BluRay.x264-ROVERS] to the queue.
17-1-27 19:50:18.5|Info|DownloadService|Report sent to Sabnzbd. At.Cafe.6.2016.720p.BluRay.x264-ROVERS
17-1-27 19:54:29.9|Info|RssSyncService|Starting RSS Sync
17-1-27 19:54:46.1|Info|DownloadDecisionMaker|Processing 299 releases
17-1-27 19:54:46.6|Info|RssSyncService|RSS Sync Completed. Reports found: 299, Reports grabbed: 0
17-1-27 19:56:00.1|Warn|UpgradeMediaFileService|The existing movie file was not lazy loaded.
17-1-27 19:56:27.1|Error|EventAggregator|MovieMissingModule failed while processing [MovieDownloadedEvent]

[v0.2.0.238] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Api.NzbDroneRestModuleWithSignalR`2.BroadcastResourceChange(ModelAction action, Int32 id) in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModuleWithSignalR.cs:line 38
   at NzbDrone.Api.Wanted.MovieMissingModule.Handle(MovieDownloadedEvent message) in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieMissingModule.cs:line 74
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

17-1-27 20:55:08.6|Info|RssSyncService|Starting RSS Sync
17-1-27 20:55:22.1|Info|DownloadDecisionMaker|Processing 200 releases
17-1-27 20:55:22.7|Info|RssSyncService|RSS Sync Completed. Reports found: 200, Reports grabbed: 0
17-1-27 21:55:48.7|Info|RssSyncService|Starting RSS Sync
17-1-27 21:56:09.5|Info|DownloadDecisionMaker|Processing 300 releases
17-1-27 21:56:10.6|Info|RssSyncService|RSS Sync Completed. Reports found: 300, Reports grabbed: 0
17-1-27 22:43:26.4|Warn|Sabnzbd|Couldn't get download queue. Unable to connect to SABnzbd, please check your settings
17-1-27 22:43:27.4|Error|Sabnzbd|Unable to connect to SABnzbd, please check your settings

[v0.2.0.238] NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to SABnzbd, please check your settings ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 192.168.0.2:8082
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 74
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 58
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 63
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 167
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 175
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.GetHistory(Int32 start, Int32 limit, String category, SabnzbdSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 109
   at NzbDrone.Core.Download.Clients.Sabnzbd.Sabnzbd.GetHistory() in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Sabnzbd\Sabnzbd.cs:line 132

17-1-27 22:56:25.8|Info|RssSyncService|Starting RSS Sync
```

**Comment by galli-leo** [comment]
Ah yeah, that's a known issue. Shouldn't affect the import much.

**Comment by thezoggy** [comment]
looks like I see this when the release has a `.sub` and `.idx` file, radarr fails to move them. 

example, we see sab extracting subs:
```
Extracting from C:\Users\<USERNAME>\DOWNLO~1\INCOMP~1\THEEDG~1.720\the.edge.of.seventeen.2016.720p.bluray.x264-drones.subs.rar

Extracting  C:\Users\<USERNAME>\DOWNLO~1\complete\RADARR\_UNPAC~1.X26/the.edge.of.seventeen.2016.720p.bluray.x264-drones.rar  OK
Extracting  C:\Users\<USERNAME>\DOWNLO~1\complete\RADARR\_UNPAC~1.X26/The.Edge.of.Seventeen.2016.720p.BluRay.x264-DRONES.idx  OK
Extracting from C:\Users\<USERNAME>\DOWNLO~1\complete\RADARR\_UNPAC~1.X26\the.edge.of.seventeen.2016.720p.bluray.x264-drones.rar

Extracting  C:\Users\<USERNAME>\DOWNLO~1\complete\RADARR\_UNPAC~1.X26/The.Edge.of.Seventeen.2016.720p.BluRay.x264-DRONES.sub  OK
```

**Comment by onedr0p** [comment]
The error you originally pointed out is fixed, subtitles are not supported as of yet. There is a feature request to get them though, closing this issue.
