### ISSUE TITLE
Unable to determine qBittorrent API version

### ISSUE THREAD

**Issue by WHiZSTA** [Radarr/Radarr#4941]
**Describe the bug**
This started happening to me about a month ago. radarr (and sonarr) are unable to  communicate with qbit randomly. It seems to work after a reboot, but not long after it will stop working. closing and restarting both apps makes no difference. i even updated qbit in case that would help, which it sadly didn't. its clearly some issue in the shared src between the two. googling it i found some other people who have had the same issue, but no solutions.

**Platform Information (please complete the following information):**
 - OS: Windows 10
 - Radarr Version 0.2.0.1504
- QBit: 4.2.5

**Debug Logs**
```
NzbDrone.Core.Download.Clients.DownloadClientException: Unable to determine qBittorrent API version
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.FetchProxy(QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 84
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.<>c__DisplayClass6_0.<GetProxy>b__0() in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 67
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in C:\projects\radarr-usby1\src\NzbDrone.Common\Cache\Cached.cs:line 81
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxy(QBittorrentSettings settings, Boolean force) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 67
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.GetItems() in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 110
```

**Comment by austinwbest** [comment]
Can you enable trace logging & rerun it. Then include more than just the error line as well :)

**Comment by WHiZSTA** [comment]
is this what you are looking for or am i in the wrong place?

```2020-9-2 19:49:11.4|Info|OwinHostController|Listening on the following URLs:
2020-9-2 19:49:11.4|Info|OwinHostController|  http://*:7878/
2020-9-2 19:49:11.5|Debug|OwinAppFactory|Attaching NzbDroneVersionMiddleWare to host
2020-9-2 19:49:11.5|Debug|OwinAppFactory|Attaching SignalRMiddleWare to host
2020-9-2 19:49:11.5|Debug|OwinAppFactory|Attaching NancyMiddleWare to host
2020-9-2 19:49:11.6|Info|NancyBootstrapper|Starting Web Server
2020-9-2 19:49:12.0|Debug|QualityDefinitionService|Setting up default quality config
2020-9-2 19:49:12.6|Debug|NotificationFactory|Initializing Providers. Count 21
2020-9-2 19:49:12.6|Info|CommandExecutor|Starting 2 threads for tasks.
2020-9-2 19:49:13.3|Debug|NetImportFactory|Initializing Providers. Count 6
2020-9-2 19:49:13.3|Debug|IndexerFactory|Initializing Providers. Count 11
2020-9-2 19:49:13.3|Debug|MetadataFactory|Initializing Providers. Count 4
2020-9-2 19:49:13.4|Debug|DownloadClientFactory|Initializing Providers. Count 15
2020-9-2 19:49:13.5|Error|QBittorrent|Unable to determine qBittorrent API version

[v0.2.0.1504] NzbDrone.Core.Download.Clients.DownloadClientException: Unable to determine qBittorrent API version
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.FetchProxy(QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 84
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.<>c__DisplayClass6_0.<GetProxy>b__0() in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 67
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in C:\projects\radarr-usby1\src\NzbDrone.Common\Cache\Cached.cs:line 81
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxy(QBittorrentSettings settings, Boolean force) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 67
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.GetItems() in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 110

2020-9-2 19:49:26.9|Debug|Api|[GET] /api/config/ui: 200.OK (40 ms)
2020-9-2 19:49:26.9|Debug|Api|[GET] /api/system/status: 200.OK (7 ms)
2020-9-2 19:49:27.0|Debug|Api|[GET] /api/profile: 200.OK (36 ms)
2020-9-2 19:49:27.0|Debug|Api|[GET] /api/health: 200.OK (22 ms)
2020-9-2 19:49:27.1|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (65 ms)
2020-9-2 19:49:27.2|Debug|Api|[GET] /api/movie?page=1&pageSize=250&sortKey=sortTitle&sortDir=asc&filterKey=downloaded&filterValue=false: 200.OK (127 ms)
2020-9-2 19:49:27.2|Debug|Api|[GET] /api/command: 200.OK (3 ms)
2020-9-2 19:49:27.3|Debug|Api|[GET] /api/movie?page=1&pageSize=-1&sortKey=sortTitle&sortDir=asc&filterKey=filterKey&filterValue=filterValue&filterType=filterType: 200.OK (49 ms)
2020-9-2 19:49:27.3|Debug|Api|[GET] /api/tag: 200.OK (49 ms)
2020-9-2 19:49:27.3|Debug|Api|[GET] /api/language: 200.OK (56 ms)
2020-9-2 19:49:27.3|Debug|Api|[GET] /api/series: 200.OK (2 ms)
2020-9-2 19:49:27.3|Debug|Api|[GET] /api/health: 200.OK (0 ms)
2020-9-2 19:49:27.3|Debug|Api|[GET] /api/movies/discover/lists: 200.OK (44 ms)
2020-9-2 19:49:27.3|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (2 ms)
2020-9-2 19:49:27.4|Debug|Api|[GET] /api/movie?page=1&pageSize=250&sortKey=sortTitle&sortDir=asc&filterKey=downloaded&filterValue=false&filterType=equal: 200.OK (15 ms)
2020-9-2 19:49:27.9|Warn|StaticResourceMapper|File C:\ProgramData\Radarr\bin\UI\Content\Images\favicon\manifest not found
2020-9-2 19:49:29.3|Debug|Api|[GET] /api/config/mediamanagement: 200.OK (9 ms)
2020-9-2 19:49:29.3|Debug|Api|[GET] /api/config/downloadclient: 200.OK (7 ms)
2020-9-2 19:49:29.3|Debug|Api|[GET] /api/config/indexer: 200.OK (6 ms)
2020-9-2 19:49:29.4|Debug|Api|[GET] /api/config/naming: 200.OK (17 ms)
2020-9-2 19:49:29.4|Debug|Api|[GET] /api/notification: 200.OK (29 ms)
2020-9-2 19:49:29.4|Debug|Api|[GET] /api/config/ui: 200.OK (0 ms)
2020-9-2 19:49:29.4|Debug|Api|[GET] /api/config/netimport: 200.OK (6 ms)
2020-9-2 19:49:29.5|Debug|Api|[GET] /api/config/host: 200.OK (111 ms)
2020-9-2 19:49:29.6|Debug|Api|[GET] /api/profile: 200.OK (6 ms)
2020-9-2 19:49:29.6|Debug|Api|[GET] /api/profile: 200.OK (5 ms)
2020-9-2 19:49:29.6|Debug|Api|[GET] /api/customformat: 200.OK (13 ms)
2020-9-2 19:49:29.6|Debug|Api|[GET] /api/qualitydefinition: 200.OK (20 ms)
2020-9-2 19:49:29.6|Debug|Api|[GET] /api/delayprofile: 200.OK (77 ms)
2020-9-2 19:49:29.6|Debug|Api|[GET] /api/Restriction: 200.OK (19 ms)
2020-9-2 19:49:29.6|Debug|Api|[GET] /api/indexer: 200.OK (41 ms)
2020-9-2 19:49:29.7|Debug|Api|[GET] /api/downloadclient: 200.OK (30 ms)
2020-9-2 19:49:29.7|Debug|Api|[GET] /api/remotePathMapping: 200.OK (33 ms)```

**Comment by WHiZSTA** [comment]
nm i think i got it for u now..

```2020-9-2 19:53:39.1|Debug|Api|[GET] /api/config/downloadclient: 200.OK (13 ms)
2020-9-2 19:53:39.2|Trace|Http|Req: 109 [GET] /api/config/host
2020-9-2 19:53:39.2|Trace|Http|Res: 107 [GET] /api/notification: 200.OK (15 ms)
2020-9-2 19:53:39.1|Trace|Http|Req: 108 [GET] /api/config/ui
2020-9-2 19:53:39.2|Debug|Api|[GET] /api/notification: 200.OK (15 ms)
2020-9-2 19:53:39.2|Trace|ConfigService|Using default config value for 'firstdayofweek' defaultValue:'0'
2020-9-2 19:53:39.2|Trace|ConfigService|Using default config value for 'calendarweekcolumnheader' defaultValue:'ddd M/D'
2020-9-2 19:53:39.2|Trace|ConfigService|Using default config value for 'shortdateformat' defaultValue:'MMM D YYYY'
2020-9-2 19:53:39.2|Trace|ConfigService|Using default config value for 'longdateformat' defaultValue:'dddd, MMMM D YYYY'
2020-9-2 19:53:39.2|Trace|Http|Req: 110 [GET] /api/config/netimport
2020-9-2 19:53:39.2|Trace|ConfigService|Using default config value for 'netimportsyncinterval' defaultValue:'60'
2020-9-2 19:53:39.2|Trace|ConfigService|Using default config value for 'listsynclevel' defaultValue:'disabled'
2020-9-2 19:53:39.2|Trace|ConfigService|Using default config value for 'importexclusions' defaultValue:''
2020-9-2 19:53:39.2|Trace|ConfigService|Using default config value for 'traktauthtoken' defaultValue:''
2020-9-2 19:53:39.2|Trace|ConfigService|Using default config value for 'traktrefreshtoken' defaultValue:''
2020-9-2 19:53:39.1|Trace|Http|Res: 104 [GET] /api/config/naming: 200.OK (18 ms)
2020-9-2 19:53:39.2|Trace|ConfigService|Using default config value for 'trakttokenexpiry' defaultValue:'0'
2020-9-2 19:53:39.2|Trace|ConfigService|Using default config value for 'timeformat' defaultValue:'h(:mm)a'
2020-9-2 19:53:39.2|Trace|ConfigService|Using default config value for 'showrelativedates' defaultValue:'True'
2020-9-2 19:53:39.2|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2020-9-2 19:53:39.2|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2020-9-2 19:53:39.2|Trace|ConfigService|Using default config value for 'enablecolorimpairedmode' defaultValue:'False'
2020-9-2 19:53:39.2|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2020-9-2 19:53:39.2|Debug|Api|[GET] /api/config/naming: 200.OK (18 ms)
2020-9-2 19:53:39.2|Trace|Http|Res: 110 [GET] /api/config/netimport: 200.OK (7 ms)
2020-9-2 19:53:39.2|Trace|Http|Res: 108 [GET] /api/config/ui: 200.OK (37 ms)
2020-9-2 19:53:39.2|Trace|Http|Res: 109 [GET] /api/config/host: 200.OK (38 ms)
2020-9-2 19:53:39.2|Debug|Api|[GET] /api/config/ui: 200.OK (37 ms)
2020-9-2 19:53:39.2|Debug|Api|[GET] /api/config/host: 200.OK (38 ms)
2020-9-2 19:53:39.2|Debug|Api|[GET] /api/config/netimport: 200.OK (7 ms)
2020-9-2 19:53:39.3|Trace|Http|Req: 111 [GET] /api/config/naming/samples?renameEpisodes=true&replaceIllegalCharacters=true&colonReplacementFormat=delete&standardMovieFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)+%7BQuality+Full%7D&movieFolderFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)&multiEpisodeStyle=0&includeSeriesTitle=false&includeEpisodeTitle=false&includeQuality=false&replaceSpaces=false&id=1
2020-9-2 19:53:39.3|Debug|MediaInfoFormatter|Formatting audio channels using 'AudioChannelPositions', with a value of: '3/2/0.1'
2020-9-2 19:53:39.3|Debug|MediaInfoFormatter|Formatting audio channels using 'AudioChannelPositions', with a value of: '3/2/0.1'
2020-9-2 19:53:39.3|Trace|Http|Res: 111 [GET] /api/config/naming/samples?renameEpisodes=true&replaceIllegalCharacters=true&colonReplacementFormat=delete&standardMovieFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)+%7BQuality+Full%7D&movieFolderFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)&multiEpisodeStyle=0&includeSeriesTitle=false&includeEpisodeTitle=false&includeQuality=false&replaceSpaces=false&id=1: 200.OK (11 ms)
2020-9-2 19:53:39.3|Debug|Api|[GET] /api/config/naming/samples?renameEpisodes=true&replaceIllegalCharacters=true&colonReplacementFormat=delete&standardMovieFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)+%7BQuality+Full%7D&movieFolderFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)&multiEpisodeStyle=0&includeSeriesTitle=false&includeEpisodeTitle=false&includeQuality=false&replaceSpaces=false&id=1: 200.OK (11 ms)
2020-9-2 19:53:39.3|Trace|Http|Req: 112 [GET] /api/profile
2020-9-2 19:53:39.3|Trace|Http|Req: 113 [GET] /api/delayprofile
2020-9-2 19:53:39.3|Trace|Http|Res: 112 [GET] /api/profile: 200.OK (10 ms)
2020-9-2 19:53:39.3|Debug|Api|[GET] /api/profile: 200.OK (10 ms)
2020-9-2 19:53:39.3|Trace|Http|Res: 113 [GET] /api/delayprofile: 200.OK (11 ms)
2020-9-2 19:53:39.3|Debug|Api|[GET] /api/delayprofile: 200.OK (11 ms)
2020-9-2 19:53:39.3|Trace|Http|Req: 114 [GET] /api/qualitydefinition
2020-9-2 19:53:39.3|Trace|Http|Req: 115 [GET] /api/profile
2020-9-2 19:53:39.3|Trace|Http|Res: 114 [GET] /api/qualitydefinition: 200.OK (1 ms)
2020-9-2 19:53:39.3|Debug|Api|[GET] /api/qualitydefinition: 200.OK (1 ms)
2020-9-2 19:53:39.3|Trace|Http|Req: 116 [GET] /api/customformat
2020-9-2 19:53:39.3|Trace|Http|Res: 116 [GET] /api/customformat: 200.OK (2 ms)
2020-9-2 19:53:39.3|Trace|Http|Res: 115 [GET] /api/profile: 200.OK (7 ms)
2020-9-2 19:53:39.3|Debug|Api|[GET] /api/customformat: 200.OK (2 ms)
2020-9-2 19:53:39.3|Debug|Api|[GET] /api/profile: 200.OK (7 ms)
2020-9-2 19:53:39.3|Trace|Http|Req: 117 [GET] /api/customformat/test?title=A.Movie.2018.Directors.Cut.2160p.UHD.BluRay.REMUX.HDR.HEVC.Atmos-EPSiLON&sort_by=matches&order=desc
2020-9-2 19:53:39.3|Trace|Http|Req: 118 [GET] /api/profile
2020-9-2 19:53:39.3|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
2020-9-2 19:53:39.3|Trace|Http|Req: 120 [GET] /api/Restriction
2020-9-2 19:53:39.3|Debug|Parser|Parsing string 'A.Movie.2018.Directors.Cut.2160p.UHD.BluRay.REMUX.HDR.HEVC.Atmos-EPSiLON'
2020-9-2 19:53:39.3|Trace|Http|Req: 119 [GET] /api/indexer
2020-9-2 19:53:39.3|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2020-9-2 19:53:39.3|Debug|Parser|Movie Parsed. A Movie - 2018 
2020-9-2 19:53:39.3|Debug|ParsingService|Language(s) parsed: 
2020-9-2 19:53:39.3|Debug|QualityParser|Trying to parse quality for A.Movie.2018.Directors.Cut.2160p.UHD.BluRay.REMUX.HDR.HEVC.Atmos-EPSiLON
2020-9-2 19:53:39.3|Debug|ParsingService|Quality parsed: Remux-2160p v1 (None)
2020-9-2 19:53:39.3|Trace|Http|Res: 118 [GET] /api/profile: 200.OK (8 ms)
2020-9-2 19:53:39.3|Trace|Http|Res: 117 [GET] /api/customformat/test?title=A.Movie.2018.Directors.Cut.2160p.UHD.BluRay.REMUX.HDR.HEVC.Atmos-EPSiLON&sort_by=matches&order=desc: 200.OK (11 ms)
2020-9-2 19:53:39.3|Debug|Api|[GET] /api/profile: 200.OK (8 ms)
2020-9-2 19:53:39.3|Debug|Api|[GET] /api/customformat/test?title=A.Movie.2018.Directors.Cut.2160p.UHD.BluRay.REMUX.HDR.HEVC.Atmos-EPSiLON&sort_by=matches&order=desc: 200.OK (11 ms)
2020-9-2 19:53:39.3|Trace|Http|Req: 121 [GET] /api/downloadclient
2020-9-2 19:53:39.3|Trace|Http|Req: 122 [GET] /api/remotePathMapping
2020-9-2 19:53:39.3|Trace|Http|Req: 123 [GET] /api/profile
2020-9-2 19:53:39.3|Trace|Http|Res: 122 [GET] /api/remotePathMapping: 200.OK (17 ms)
2020-9-2 19:53:39.3|Trace|Http|Res: 120 [GET] /api/Restriction: 200.OK (32 ms)
2020-9-2 19:53:39.3|Trace|Http|Res: 121 [GET] /api/downloadclient: 200.OK (21 ms)
2020-9-2 19:53:39.3|Debug|Api|[GET] /api/Restriction: 200.OK (32 ms)
2020-9-2 19:53:39.3|Debug|Api|[GET] /api/remotePathMapping: 200.OK (17 ms)
2020-9-2 19:53:39.3|Debug|Api|[GET] /api/downloadclient: 200.OK (21 ms)
2020-9-2 19:53:39.4|Trace|Http|Res: 119 [GET] /api/indexer: 200.OK (37 ms)
2020-9-2 19:53:39.4|Trace|Http|Req: 124 [GET] /api/netimport
2020-9-2 19:53:39.4|Debug|Api|[GET] /api/indexer: 200.OK (37 ms)
2020-9-2 19:53:39.4|Trace|Http|Res: 123 [GET] /api/profile: 200.OK (20 ms)
2020-9-2 19:53:39.4|Trace|Http|Req: 125 [GET] /api/rootfolder
2020-9-2 19:53:39.4|Trace|Http|Req: 126 [GET] /api/exclusions
2020-9-2 19:53:39.4|Debug|Api|[GET] /api/profile: 200.OK (20 ms)
2020-9-2 19:53:39.4|Trace|Http|Res: 124 [GET] /api/netimport: 200.OK (17 ms)
2020-9-2 19:53:39.4|Trace|Http|Res: 125 [GET] /api/rootfolder: 200.OK (15 ms)
2020-9-2 19:53:39.4|Debug|Api|[GET] /api/netimport: 200.OK (17 ms)
2020-9-2 19:53:39.4|Debug|Api|[GET] /api/rootfolder: 200.OK (15 ms)
2020-9-2 19:53:39.4|Trace|Http|Res: 126 [GET] /api/exclusions: 200.OK (14 ms)
2020-9-2 19:53:39.4|Debug|Api|[GET] /api/exclusions: 200.OK (14 ms)
2020-9-2 19:53:39.5|Trace|Http|Req: 127 [GET] /api/metadata
2020-9-2 19:53:39.5|Trace|Http|Res: 127 [GET] /api/metadata: 200.OK (5 ms)
2020-9-2 19:53:39.5|Debug|Api|[GET] /api/metadata: 200.OK (5 ms)
2020-9-2 19:53:44.0|Trace|Scheduler|Pending Tasks: 0
2020-9-2 19:53:46.1|Trace|Http|Req: 128 [POST] /api/downloadclient/test
2020-9-2 19:53:46.1|Trace|HttpClient|Req: [GET] http://localhost:8080/api/v2/app/webapiVersion
2020-9-2 19:53:46.2|Trace|HttpClient|Res: [GET] http://localhost:8080/api/v2/app/webapiVersion: 404.NotFound (22 ms)
2020-9-2 19:53:46.2|Trace|HttpClient|Response content (342 bytes): <?xml version="1.0" encoding="ascii" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml10/DTD/xhtml10strict.dtd">
<html lang="en">
<head>
<title>Client error</title>
</head>
<body>
<h1>404 Client error (/api/v2/app/webapiVersion)</h1>
<hr />
<a href="http://www.videolan.org">VideoLAN</a>
</body>
</html>

2020-9-2 19:53:46.2|Trace|HttpClient|Req: [GET] http://localhost:8080/version/api
2020-9-2 19:53:46.2|Trace|HttpClient|Res: [GET] http://localhost:8080/version/api: 404.NotFound (21 ms)
2020-9-2 19:53:46.2|Trace|HttpClient|Response content (329 bytes): <?xml version="1.0" encoding="ascii" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml10/DTD/xhtml10strict.dtd">
<html lang="en">
<head>
<title>Client error</title>
</head>
<body>
<h1>404 Client error (/version/api)</h1>
<hr />
<a href="http://www.videolan.org">VideoLAN</a>
</body>
</html>

2020-9-2 19:53:46.2|Error|QBittorrent|Unable to determine qBittorrent API version

[v0.2.0.1504] NzbDrone.Core.Download.Clients.DownloadClientException: Unable to determine qBittorrent API version
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.FetchProxy(QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 84
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.<>c__DisplayClass6_0.<GetProxy>b__0() in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 67
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in C:\projects\radarr-usby1\src\NzbDrone.Common\Cache\Cached.cs:line 81
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxy(QBittorrentSettings settings, Boolean force) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 67
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 234

2020-9-2 19:53:46.3|Trace|NzbDroneErrorPipeline|Handling Exception
2020-9-2 19:53:46.3|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unknown exception: Unable to determine qBittorrent API version
2020-9-2 19:53:46.3|Trace|Http|Res: 128 [POST] /api/downloadclient/test: 400.BadRequest (165 ms)
2020-9-2 19:53:46.3|Debug|Api|[POST] /api/downloadclient/test: 400.BadRequest (165 ms)
2020-9-2 19:53:49.9|Trace|Http|Req: 129 [GET] /api/health
2020-9-2 19:53:49.9|Trace|Http|Res: 129 [GET] /api/health: 200.OK (0 ms)
2020-9-2 19:53:49.9|Debug|Api|[GET] /api/health: 200.OK (0 ms)
2020-9-2 19:53:49.9|Trace|Http|Req: 130 [GET] /api/diskspace
2020-9-2 19:53:49.9|Trace|Http|Req: 131 [GET] /api/health
2020-9-2 19:53:49.9|Trace|Http|Res: 131 [GET] /api/health: 200.OK (0 ms)
2020-9-2 19:53:49.9|Debug|Api|[GET] /api/health: 200.OK (0 ms)```

**Comment by ta264** [comment]
I think that makes it pretty clear you aren't running qbit on the port you think you are.  Looks like VLC is running on 8080.

**Comment by WHiZSTA** [comment]
i was confused why  it was saying vlc. thank you so much for pointing it out, qbit was indeed running on that port as it has forever, but i recently started running vlc which i  had no idea had an http module loaded which appears to have been interfering. i closed it and it connects fine. im so sorry for the trouble, thank you for the help. in case anyone else stumbles upon this when googling like i did, check for conflicting things that may also try to run on that qbit port.
