### ISSUE TITLE
Aphrodite Radarr fails after updating  - Netstandard.dll error

### ISSUE THREAD

**Issue by ewjannece** [Radarr/Radarr#5047]
After updating to v3.0.0.3751, running Radarr fails with this error: 

```
Error:
  An assembly specified in the application dependencies manifest (Radarr.deps.json) was not found:
    package: 'Dapper', version: '2.0.30'
    path: 'lib/netstandard2.0/Dapper.dll'

```

md5sum for netstandard.dll
22d2a9d4fd219bba51e9e566275305df  netstandard.dll

Last 2 update logs:
[2020.09.22-12.37.txt](https://github.com/Radarr/Radarr/files/5264303/2020.09.22-12.37.txt)
[2020.09.22-13.59.txt](https://github.com/Radarr/Radarr/files/5264304/2020.09.22-13.59.txt)

OS: Linux 

Mono version: 
```
mono --version
Mono JIT compiler version 6.8.0.105 (tarball Tue Feb  4 21:20:35 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```
Let me know if I can add to this to help troubleshoot this.

**Comment by Qstick** [comment]
Native linux install?

**Comment by gjannece** [comment]
```
file Radarr
Radarr: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=18006ff07870ebf0e35262fabc52066177a6f9a6, stripped
```

**Comment by Qstick** [comment]
Looks like update went bad or something, have you tried to re-install with latest? @ta264 maybe of more help, nothing significant changed in latest build though

```
2020-9-22 14:00:08.6|Debug|DiskTransferService|Copy [/tmp/radarr_update/Radarr/Microsoft.Extensions.Identity.Core.dll] > [/opt/Radarr/Microsoft.Extensions.Identity.Core.dll]
2020-9-22 14:00:08.6|Debug|DiskTransferService|Rolling back file copy [/tmp/radarr_update/Radarr/Microsoft.Extensions.Identity.Core.dll] to [/opt/Radarr/Microsoft.Extensions.Identity.Core.dll].
2020-9-22 14:00:11.6|Error|InstallUpdateService|Failed to copy upgrade package to target folder.

[v3.0.0.3751] System.InvalidOperationException: Path doesn't exist!
   at Mono.Unix.UnixFileSystemInfo.AssertValid()
   at NzbDrone.Mono.Disk.DiskProvider.CopyFileInternal(String source, String destination, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskProviderBase.CopyFile(String source, String destination, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskTransferService.TryCopyFileVerified(String sourcePath, String targetPath, Int64 originalSize)
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskTransferService.MirrorFolder(String sourcePath, String targetPath)
   at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start(String installationFolder, Int32 processId)
```

**Comment by gjannece** [comment]
This error during updates have happened a few times. I use Sonarr V3 and this doesn't seem to happen. Is there any code to see if the md5sum of the file matches what is downloaded? Just trying to help.

**Comment by Qstick** [comment]
Yea we check the hash during the upgrade process and confirm its a legit file before processing. Sonarr V3 is a bit of a different animal. If you can, jump on discord for some help troubleshooting. I don't believe this is a widespread issue.
