### ISSUE TITLE
'iso-8859-2' is not a supported encoding name

### ISSUE THREAD

**Issue by kbzowski** [Radarr/Radarr#5049]
**Describe the bug**
I tried to add polishsource.org rss to Radarr 3.0.0.3751 without success. Test finishes with error: "Unable to connect to indexer: 'iso-8859-2' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')"

**Platform Information (please complete the following information):**
 - OS: Linux (Docker)
 - Radarr Version 3.0.0.3751-ls23 by linuxserver.io

**Debug Logs**

```
System.ArgumentException: 'iso-8859-2' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
   at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at NzbDrone.Common.Http.HttpHeader.GetEncodingFromContentType(String contentType) in D:\a\1\s\src\NzbDrone.Common\Http\HttpHeader.cs:line 139
   at NzbDrone.Common.Http.HttpHeader.GetEncodingFromContentType() in D:\a\1\s\src\NzbDrone.Common\Http\HttpHeader.cs:line 134
   at NzbDrone.Common.Http.HttpResponse.get_Content() in D:\a\1\s\src\NzbDrone.Common\Http\HttpResponse.cs:line 47
   at NzbDrone.Core.Indexers.IndexerResponse.get_Content() in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerResponse.cs:line 22
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.IsEZTVFeed(IndexerResponse response) in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:line 195
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.GetEzrssParserSettings(IndexerResponse response, TorrentRssIndexerSettings indexerSettings) in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:line 79
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.GetParserSettings(IndexerResponse response, TorrentRssIndexerSettings indexerSettings) in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:line 62
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.Detect(TorrentRssIndexerSettings indexerSettings) in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:line 58
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssParserFactory.DetectParserSettings(TorrentRssIndexerSettings indexerSettings) in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssParserFactory.cs:line 55
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssParserFactory.<>c__DisplayClass4_0.<GetParser>b__0() in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssParserFactory.cs:line 32
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 114
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssParserFactory.GetParser(TorrentRssIndexerSettings indexerSettings) in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssParserFactory.cs:line 32
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssIndexer.GetParser() in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssIndexer.cs:line 31
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 318

**Comment by Qstick** [comment]
Issue here is iso-8859-2 isn't supported out of box on netcore

We'd have to add Reference `System.Text.Encoding.CodePages`

Then register the encoding provider to use the new encodings

Refs:
https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.registerprovider?view=netcore-3.1
https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding?view=netcore-3.1
https://github.com/dotnet/runtime/issues/22907

**Comment by ta264** [comment]
I think this is a legitimate issue

**Comment by accountjusttobumpthisissue** [comment]
I'm also affected by this issue. For what it's worth, Sonarr doesn't throw an error using the same RSS feed.

**Comment by austinwbest** [comment]
> I'm also affected by this issue. For what it's worth, Sonarr doesn't throw an error using the same RSS feed.

Apples and oranges. Sonarr did not use the same framework.

**Comment by Qstick** [comment]
Anyone have an example feed this happens with?

**Comment by kbzowski** [comment]
In my case, the problem is caused by https://polishsource.cz. This is private tracker so I cannot post feed. I can confirm that feed returns `content-type: text/html; charset=ISO-8859-2`

**Comment by Qstick** [comment]
Nightly build is building now with a fix for this if someone can please test it

**Comment by babacs** [comment]
Waiting to be forked to arm32v7-latest, so I can test it

**Comment by kbzowski** [comment]
It works fine with polishsource.cz. Thank you!

**Comment by Qstick** [comment]
Thanks @kbzowski
