### ISSUE TITLE
Collection folder does not get create when using the "{Movie Collection}" macro

### ISSUE THREAD

**Issue by John-Gee** [Radarr/Radarr#5247]
**Describe the bug**
I use "{Movie Collection}/{Movie Title} ({Release Year})" as my Movie folder path, but Radarr does not create the Collection's folder if it does not exist and complain about it missing instead.

**To Reproduce**
1. Set the Movie Folder Format in settings to {Movie Collection}/{Movie OriginalTitle} ({Release Year})
2. Download a new movie with the Collection's folder not existing. (Importing would probably be the same)
3. See error

**Expected behavior**
Radarr should create the folder (whether it's a root folder or not, either way would be fine)

**Screenshots**
N/A

**Platform Information (please complete the following information):**
 - OS: Linux
 - Mono Version: using .NET Core
 - Radarr Version: 3.0.0.3966

**Debug Logs**
Is this really needed? This seems pretty obvious.

**Comment by ta264** [comment]
Yes please add logs so that
> and complain about it missing instead
Makes some sense to us

**Comment by John-Gee** [comment]
Alright:

2020-10-21 16:02:14.6|Warn|ImportApprovedMovie|Couldn't import movie <MOVIEPATH/MOVIE.EXT>

[v3.0.0.3966] NzbDrone.Core.MediaFiles.MovieImport.RootFolderNotFoundException: Root folder 'ROOT FOLDER/COLLECTION's FOLDER' was not found.
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.EnsureMovieFolder(MovieFile movieFile, Movie movie, String filePath) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 150
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.EnsureMovieFolder(MovieFile movieFile, LocalMovie localMovie, String filePath) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 136
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 73
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 75
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:line 123

Is this enough?

Thank you!

**Comment by ta264** [comment]
Radarr doesn't create root folders, that's for you to do.

**Comment by Qstick** [comment]
I think this might be legit actually, If there is a nested parent in the naming format (under the Root, but above the Movie folder) Radarr won't create it when making the movie folder. I think I recall running into this on the Lidarr side as well.

**Comment by John-Gee** [comment]
> Radarr doesn't create root folders, that's for you to do.

Does the collection folder need to be a root folder? If Radarr won't create root folders, then can it not just make it non-root? If not, what's the point of that variable?

> I think this might be legit actually, If there is a nested parent in the naming format (under the Root, but above the Movie folder) Radarr won't create it when making the movie folder.

That's exactly it. :)

**Comment by austinwbest** [comment]
This would be an issue when using first letter folders too then, yea?

**Comment by John-Gee** [comment]
I've never used those, but I'd guess so yes.

**Comment by bakerboy448** [comment]
@John-Gee  `{Movie TitleFirstCharacter}/` rather than collection

**Comment by John-Gee** [comment]
As requested: https://pastebin.com/RsGVuxrh

**Comment by John-Gee** [comment]
I just tested it and it works fine, thanks!
