### ISSUE TITLE
watch list -- exceeding skyhook limits

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#533]
Radarr Ver. 0.2.0.266

Added StephenLu list, let it update. Saw some movies add then a wave of errors.
Looks like watch list hammer skyhook too much and was throttled.. thus causing data not to be returned as expected..  

seeing errors like:
`Error occurred while executing task RefreshMovie: Object reference not set to an instance of an object.`

logs:
```
17-1-30 16:48:36.7|Info|MovieService|Adding Movie [][The Accountant] Path: [D:\Movies\The Accountant (2016)]
17-1-30 16:48:36.8|Info|MediaCoverService|Downloading Banner for [tt1878870][The Edge of Seventeen] http://image.tmdb.org/t/p/original/4veOp3jxmZ6kv2hf6vR8cHTMy51.jpg
17-1-30 16:48:36.8|Debug|HttpClient|Downloading [http://image.tmdb.org/t/p/original/4veOp3jxmZ6kv2hf6vR8cHTMy51.jpg] to [C:\ProgramData\Radarr\MediaCover\22\banner.jpg]
17-1-30 16:48:36.9|Debug|RefreshMovieService|Finished movie refresh for Arrival
17-1-30 16:48:36.9|Warn|DiskScanService|Series' root folder (D:\Movies) is empty.
17-1-30 16:48:36.9|Info|MovieService|Adding Movie [][Masterminds] Path: [D:\Movies\Masterminds (2016)]
17-1-30 16:48:36.9|Info|RefreshMovieService|Updating Info for Hacksaw Ridge
17-1-30 16:48:36.9|Debug|HttpClient|Downloading Completed. took 0s
17-1-30 16:48:36.9|Debug|MediaCoverService|Resizing Banner-70 for [tt1878870][The Edge of Seventeen]
17-1-30 16:48:37.0|Debug|Api|[GET] /api/system/task??sort_by=name&order=asc: 200.OK (6 ms)
17-1-30 16:48:37.0|Debug|Api|[GET] /api/system/task??sort_by=name&order=asc: 200.OK (6 ms)
17-1-30 16:48:37.0|Debug|Api|[GET] /api/system/task??sort_by=name&order=asc: 200.OK (4 ms)
17-1-30 16:48:37.0|Debug|Api|[GET] /api/system/task??sort_by=name&order=asc: 200.OK (6 ms)
17-1-30 16:48:37.0|Warn|SkyHookProxy|Your request count (41) is over the allowed limit of 40.
17-1-30 16:48:37.0|Error|CommandExecutor|Error occurred while executing task RefreshMovie

[v0.2.0.266] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Tv.RefreshMovieService.RefreshMovieInfo(Movie movie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\RefreshMovieService.cs:line 59
   at NzbDrone.Core.Tv.RefreshMovieService.Execute(RefreshMovieCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\RefreshMovieService.cs:line 113
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41

17-1-30 16:48:37.1|Info|RefreshMovieService|Updating Info for Trolls
17-1-30 16:48:37.1|Debug|MediaCoverService|Resizing Banner-35 for [tt4550098][Nocturnal Animals]
17-1-30 16:48:37.1|Debug|MediaCoverService|Resizing Banner-35 for [tt4034228][Manchester by the Sea]
17-1-30 16:48:37.1|Debug|MediaCoverService|Resizing Poster-250 for [][Max Steel]
17-1-30 16:48:37.1|Debug|MediaCoverService|Resizing Poster-250 for [][Keeping Up with the Joneses]
17-1-30 16:48:37.1|Info|MediaCoverService|Downloading Poster for [][The Accountant] http://image.tmdb.org/t/p/original/afhAUuWVB7k7PjJUd4lwO3rzhSq.jpg
17-1-30 16:48:37.1|Debug|HttpClient|Downloading [http://image.tmdb.org/t/p/original/afhAUuWVB7k7PjJUd4lwO3rzhSq.jpg] to [C:\ProgramData\Radarr\MediaCover\29\poster.jpg]
17-1-30 16:48:37.1|Info|MediaCoverService|Downloading Poster for [][Masterminds] http://image.tmdb.org/t/p/original/jqDwMxDPRuBOheKaXnT6nZQdxD.jpg
17-1-30 16:48:37.1|Debug|HttpClient|Downloading [http://image.tmdb.org/t/p/original/jqDwMxDPRuBOheKaXnT6nZQdxD.jpg] to [C:\ProgramData\Radarr\MediaCover\30\poster.jpg]
17-1-30 16:48:37.2|Debug|HttpClient|Downloading Completed. took 0s
17-1-30 16:48:37.2|Debug|MediaCoverService|Resizing Poster-500 for [][The Accountant]
17-1-30 16:48:37.2|Debug|Api|[GET] /api/system/task??sort_by=name&order=asc: 200.OK (6 ms)
17-1-30 16:48:37.2|Debug|Api|[GET] /api/system/task??sort_by=name&order=asc: 200.OK (15 ms)
17-1-30 16:48:37.2|Debug|Api|[GET] /api/system/task??sort_by=name&order=asc: 200.OK (22 ms)
17-1-30 16:48:37.2|Debug|Api|[GET] /api/system/task??sort_by=name&order=asc: 200.OK (21 ms)
17-1-30 16:48:37.2|Error|CommandExecutor|Error occurred while executing task NetImportSync

[v0.2.0.266] System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieInfo(String ImdbId) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 224
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie(Movie movie) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 600
   at NzbDrone.Core.NetImport.NetImportSearchService.Execute(NetImportSyncCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\NetImportSearchService.cs:line 83
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41

17-1-30 16:48:37.2|Warn|SkyHookProxy|Your request count (43) is over the allowed limit of 40.
17-1-30 16:48:37.2|Debug|Api|[GET] /api/system/task??sort_by=name&order=asc: 200.OK (37 ms)
17-1-30 16:48:37.2|Info|MediaCoverService|Downloading Banner for [tt2543164][Arrival] http://image.tmdb.org/t/p/original/yIZ1xendyqKvY3FGeeUYUd5X9Mm.jpg
17-1-30 16:48:37.2|Debug|HttpClient|Downloading [http://image.tmdb.org/t/p/original/yIZ1xendyqKvY3FGeeUYUd5X9Mm.jpg] to [C:\ProgramData\Radarr\MediaCover\23\banner.jpg]
17-1-30 16:48:37.2|Debug|Api|[GET] /api/system/task??sort_by=name&order=asc: 200.OK (33 ms)
17-1-30 16:48:37.2|Error|CommandExecutor|Error occurred while executing task RefreshMovie

[v0.2.0.266] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Tv.RefreshMovieService.RefreshMovieInfo(Movie movie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\RefreshMovieService.cs:line 59
   at NzbDrone.Core.Tv.RefreshMovieService.Execute(RefreshMovieCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\RefreshMovieService.cs:line 113
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41
```

needs to handle throttling and breaking up bulk requests into smaller parts/delay between..  
also rss interval of 60 mins is a bit low.. imdb and others dont update their list that often... every 12 hours is prob a more sane lower limit

**Comment by thezoggy** [comment]
also, once you use one of these watch list..  and lets say you want to remove half of the releases because you already have them / dont want them...  can see that you need the ability to bulk delete and also add a filter when adding (such as only add if over x rating)

**Comment by onedr0p** [comment]
This is already fixed.
