### ISSUE TITLE
Failure when installing updates

### ISSUE THREAD

**Issue by triantos** [Radarr/Radarr#5343]
**Describe the bug**
If downloading of the latest update of V3 takes too long, it looks like Radarr throws an exception and gives up.

**To Reproduce**
1. Choose System -> Updates -> Install Latest
2. On my system, which was busy downloading some other content, the download silently fails in the UI.
3. Note I am able to `wget https://dev.azure.com/Radarr/Radarr/...` and that works well
4. Error below, full debug logs at the bottom

```
[v3.0.0.4039] System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException: The response ended prematurely, with at least 38040352 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.Read(Span`1 buffer)
```

**Expected behavior**
The download should work. If it fails, at least some feedback in the UI would be of help.

**Platform Information (please complete the following information):**
 - OS: Linux (Ubuntu 20.04)
 - Mono Version: Mono 6.10.0.104-0xamarin16+ubuntu1804b1
 - Browser and Version Safari / MacOS
 - Radarr Version 3.0.0.4039

**Debug Logs**
```
[Info] InstallUpdateService: Deleting old update files
[Info] InstallUpdateService: Downloading update 3.0.0.4065
[Warn] ManagedHttpDispatcher: Failed to get response from: https://dev.azure.com/Radarr/Radarr/_apis/build/builds/2498/artifacts?artifactName=Packages&fileId=FD3082ED18108749CA31AAFF523FA78AE05D3CC4AFF2B90451092D5BAA4E52D102&fileName=Radarr.develop.3.0.0.4065.linux-core-x64.tar.gz&api-version=5.1 An exception occurred during a WebClient request.
[Error] CommandExecutor: Error occurred while executing task ApplicationUpdate

[v3.0.0.4039] System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException: The response ended prematurely, with at least 38101792 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.Read(Span`1 buffer)
   at System.Net.Http.HttpBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.DownloadFile(String url, String fileName) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 169
   at NzbDrone.Common.Http.HttpClient.DownloadFile(String url, String fileName) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 233
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 122
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 276
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 88
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44
```

**Comment by triantos** [comment]
Isn't it a bug that the update fails and has no way to change the timeout or better handle this failure case? I can easily solve the support need of of this by just pulling the latest code. My point in filing this was that the code isn't behaving in an expected way...
