### ISSUE TITLE
Updating and starting Radarr fails because ./Radarr.Update and ./Radarr are not executable

### ISSUE THREAD

**Issue by twdkeule** [Radarr/Radarr#5390]
**Describe the bug**
Since updating to  3.0.0.4126, both Radarr and any new Radarr update fail, because the permissions of the executables are not marked as executable.

**To Reproduce**
1. Update to 3.0.0.4126
2. Try to start Radarr.

**Expected behavior**
./Radarr and ./Radarr.Update should be marked as executable when extracted.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Linux - Ubuntu 20.04.1 LTS
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Radarr Version 3.0.0.4126

**Logs for starting Radarr**
```
Nov 22 12:13:30 acer-laptop Radarr[1055]: [Info] InstallUpdateService: Downloading update 3.0.0.4126
Nov 22 12:13:43 acer-laptop Radarr[1055]: [Info] InstallUpdateService: Verifying update package
Nov 22 12:13:44 acer-laptop Radarr[1055]: [Info] InstallUpdateService: Update package verified successfully
Nov 22 12:13:44 acer-laptop Radarr[1055]: [Info] InstallUpdateService: Extracting Update package
Nov 22 12:13:53 acer-laptop Radarr[1055]: [Info] InstallUpdateService: Update package extracted successfully
Nov 22 12:13:53 acer-laptop Radarr[1055]: [Info] BackupService: Starting Backup
Nov 22 12:13:58 acer-laptop Radarr[1055]: [Info] InstallUpdateService: Preparing client
Nov 22 12:14:01 acer-laptop Radarr[1055]: [Info] InstallUpdateService: Starting update client /tmp/radarr_update/Radarr.Update
Nov 22 12:14:01 acer-laptop Radarr[1055]: [Info] InstallUpdateService: Radarr will restart shortly.
Nov 22 12:14:03 acer-laptop Radarr[1055]: SQLite error (5): database is locked in "PRAGMA cache_size=-20000"
Nov 22 12:14:03 acer-laptop Radarr[1055]: SQLite error (5): database is locked in "PRAGMA cache_size=-20000"
Nov 22 12:14:23 acer-laptop systemd[1]: radarr.service: Main process exited, code=killed, status=9/KILL
Nov 22 12:14:23 acer-laptop systemd[1]: radarr.service: Failed with result 'signal'.
Nov 22 12:14:23 acer-laptop systemd[1]: radarr.service: Scheduled restart job, restart counter is at 1.
Nov 22 12:14:23 acer-laptop systemd[1]: Stopped Radarr Daemon.
Nov 22 12:14:23 acer-laptop systemd[1]: radarr.service: Found left-over process 276950 (Radarr.Update) in control group while starting unit. Ignoring.
Nov 22 12:14:23 acer-laptop systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Nov 22 12:14:23 acer-laptop systemd[1]: Started Radarr Daemon.
Nov 22 12:14:24 acer-laptop systemd[277047]: radarr.service: Failed to execute command: Permission denied
Nov 22 12:14:24 acer-laptop systemd[277047]: radarr.service: Failed at step EXEC spawning /opt/Radarr/Radarr: Permission denied
Nov 22 12:14:24 acer-laptop systemd[1]: radarr.service: Main process exited, code=exited, status=203/EXEC
Nov 22 12:14:24 acer-laptop systemd[1]: radarr.service: Failed with result 'exit-code'.
```
```
$ ll Radarr
-rw-r--r-- 1 sonarr sonarr 89K Nov 22 12:13 Radarr
```

**Logs for update process**
```
[Info] InstallUpdateService: Downloading update 3.0.0.4136
[Info] InstallUpdateService: Verifying update package
[Info] InstallUpdateService: Update package verified successfully
[Info] InstallUpdateService: Extracting Update package
[Info] InstallUpdateService: Update package extracted successfully
[Info] BackupService: Starting Backup
[Info] InstallUpdateService: Preparing client
[Info] InstallUpdateService: Starting update client /tmp/radarr_update/Radarr.Update
[Info] InstallUpdateService: Radarr will restart shortly.
[Error] CommandExecutor: Error occurred while executing task ApplicationUpdate

[v3.0.0.4126] System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NzbDrone.Common.Processes.ProcessProvider.Start(String path, String args, StringDictionary environmentVariables, Action`1 onOutputDataReceived, Action`1 onErrorDataReceived) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 188
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 160
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 276
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 88
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44
```
```
$ ll /tmp/radarr_update/Radarr.Update
-rw-r--r-- 1 sonarr sonarr 89K Nov 23 08:31 /tmp/radarr_update/Radarr.Update
```

**Comment by ta264** [comment]
Known issue already fixed in next update. You'll need to update manually to get off this build.
