### ISSUE TITLE
Error when updating Radarr v3

### ISSUE THREAD

**Issue by seannymurrs** [Radarr/Radarr#5415]
I'm trying to update to the latest version of Radarr v3, and I'm getting the following error in my logs.

```
2020-11-27 12:29:17.7|Info|InstallUpdateService|Downloading update 3.0.0.4194
2020-11-27 12:29:29.3|Info|InstallUpdateService|Verifying update package
2020-11-27 12:29:29.6|Info|InstallUpdateService|Update package verified successfully
2020-11-27 12:29:29.6|Info|InstallUpdateService|Extracting Update package
2020-11-27 12:29:34.1|Info|InstallUpdateService|Update package extracted successfully
2020-11-27 12:29:34.1|Info|BackupService|Starting Backup
2020-11-27 12:29:44.9|Info|InstallUpdateService|Preparing client
2020-11-27 12:29:49.1|Info|InstallUpdateService|Starting update client /tmp/radarr_update/Radarr.Update
2020-11-27 12:29:49.1|Info|InstallUpdateService|Radarr will restart shortly.
2020-11-27 12:29:49.1|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

[v3.0.0.4136] System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NzbDrone.Common.Processes.ProcessProvider.Start(String path, String args, StringDictionary environmentVariables, Action`1 onOutputDataReceived, Action`1 onErrorDataReceived) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 188
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 160
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 276
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 88
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44
```

**Comment by bakerboy448** [comment]
https://www.reddit.com/r/radarr/comments/jzp8ne/osxlinux_radarr_wont_start_or_wont_update_builds/
