### ISSUE TITLE
Unable to connect to qBittorrent after upgrade (also after manual adding)

### ISSUE THREAD

**Issue by riddertommie** [Radarr/Radarr#5443]
**Describe the bug**

Qbittorrent not working after (auto) upgrade to radar > (did remove an try to add it manual but same problem).

**To Reproduce**
1. Go to 'Download client'
2. Click on 'Add Download Client - qBittorrent'
3. fill in the appropriate info or in my case via upgrade.
4. below host > Unable to connect to qBittorrent

**Expected behavior**

Connection to qbittorrent

**Screenshots**

**Platform Information (please complete the following information):**
 - OS:  Ubuntu 20.10
 - Docker: Yes > 3.0.0.4204-ls85 by linuxserver.io
 - Mono or.NET Core Version: [e.g. Mono 5.8 or .Net Core 3.1.10] (found under System -> Status)
 - Browser and Version [e.g. chrome 86.0.4240.198] (Only needed for UI issues)
 - Radarr Version 3.0.0.4204
 - Radarr Branch [e.g. master]

**Trace Logs**

  **(FYI i'm using a self signed cert, but also before the upgrade)**

Here a snippet concerning Qbit 

at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.IsApiSupported(QBittorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxyV2.cs:line 35
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.IsApiSupported(QBittorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxyV2.cs:line 62
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.FetchProxy(QBittorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 77
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.<>c__DisplayClass6_0.<GetProxy>b__0() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 72
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 114
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxy(QBittorrentSettings settings, Boolean force) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 72
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.GetItems() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 126
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) in D:\a\1\s\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 89

2020-11-29 11:25:20.8|Error|X509CertificateValidationService|Certificate validation for https://192.168.2.200:8080/api/v2/app/webapiVersion failed. RemoteCertificateNameMismatch, RemoteCertificateChainErrors
2020-11-29 11:35:50.8|Error|X509CertificateValidationService|Certificate validation for https://192.168.2.200:8080/api/v2/app/webapiVersion failed. RemoteCertificateNameMismatch, RemoteCertificateChainErrors
2020-11-29 11:35:50.9|Warn|DownloadMonitoringService|Unable to retrieve queue and history items from QBittorrent

[v3.0.0.4204] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, check your settings.

**Comment by bakerboy448** [comment]
don't use SSL/HTTPS locally there is no need

or use a CA signed cert

**Comment by riddertommie** [comment]
Little to short thru the corner i think. ;-) 

https is needed locally for the Register protocol handler in WebUI for magnet links within qbittorrent. 
 
To make a CA for  that would be overkill
