### ISSUE TITLE
Unable to login via https

### ISSUE THREAD

**Issue by Eds1989** [Radarr/Radarr#5444]
**Describe the bug**
My Radarr instance has been updated to V3 automatically. I have corrected missing SSL information preventing HTTPS access.
Login page now loads, however, on every login attempt it just refreshes the login page.
If I open the URL using HTTP and the HTTP port, it immediately takes me to the homepage suggesting login has completed and stored auth token.
If I go back to HTTPS page, it continues to only show me the login page

**To Reproduce**
Logout.
Open HTTP URL - presented with login page
Switch to HTTPS URL and login - page refreshes and goes no further
Switch back to HTTP URL and refresh - takes me to homepage

**Expected behavior**
HTTPS URL should complete login process and take me to homepage

**Screenshots**
N/A

**Platform Information (please complete the following information):**
 - OS: Windows Server 2016
 - Docker: No
 - Mono or.NET Core Version: .NET 3.1.10
 - Browser and Version Google Chrome 87.0.4280.66
 - Radarr Version 3.0.0.4204
 - Radarr Branch develop
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/5618545/radarr.trace.txt)

[AB#757](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/757)

**Comment by jwoodhouse** [comment]
I'm also having this issue.

**Platform Information**

- OS: Windows Server 2016
- Docker: No
- Mono or.NET Core Version: .NET Core 3.1.10
- Browser and Version: Firefox 83.0 (64-bit)
- Radarr Version: 3.0.0.4204
- Radarr Branch: develop


[radarr.trace.txt](https://github.com/Radarr/Radarr/files/5619801/radarr.trace.txt)

**Comment by austinwbest** [comment]
Are these actual valid certs or no cert/self certs that "worked" in v0.2?

**Comment by jwoodhouse** [comment]
> Are these actual valid certs or no cert/self certs that "worked" in v0.2?

As far as I know, the certs I’m using should be valid. They are signed by a Certificate Authority thats part of my AD domain. The same cert worked in v0.2, and certs created via the same method seem to work for a myriad of other applications (gitea, nzbhydra, sonarr, grafana, idrac etc).

For completeness, in order to create the .pfx file requested by Radarr V3, I exported my already locally installed Radarr certificate (with private key) and set a password on it.

Is there a way I can somehow validate my certs to make sure theyre not the problem?

Thanks.

**Comment by austinwbest** [comment]
I was asking because I was waiting for the 0.2 comment.. It worked because there was no validation check in 0.2

I would head to discord for help if it is a valid cert bud

**Comment by bakerboy448** [comment]
@austinwbest  seems to be an issue isolated to using IIS ?
https://www.reddit.com/r/radarr/comments/k4qek9/http2_tls_issues_after_upgrading_to_v3_server/

**Comment by R8s6** [comment]
I have exactly the same error. Observations:

- Client: Synology Download Station. 
- https doesn't work (but http works). 
- Configs aren't changed from Radarr v2 to v3, and the same https configs still work with Sonarr.
- linuxserver/radarr docker was used.
- This in particular in the logs: "The remote certificate is invalid according to the validation procedure."
- The https cert is a self-signed one (provided by Synology as the default for its Web Station) so maybe that's why it didn't pass the validation.
- In the logs, I saw quite a few references to "D:\a\1\s\src\...", which seems to be a Windows directory, but all of my machines are Linux, so is this something buggy in the code?

Logs:
```
[v3.0.0.4204] NzbDrone.Core.Download.Clients.DownloadClientUnavailableException: Unable to connect to Diskstation, please check your settings
 ---> System.Net.WebException: The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.: 'https://192.168.0.8:50010/webapi/query.cgi?api=(removed)&version=1&method=query&query=SYNO.API.Auth%2CSYNO.DownloadStation.Task'
 ---> System.Net.WebException: The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 146
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 146
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 123
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 57
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T](HttpRequestBuilder requestBuilder, String operation, DiskStationApi api, DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 93
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T](HttpRequestBuilder requestBuilder, String operation, DiskStationApi api, DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 93
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.UpdateApiInfo(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 208
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.GetApiInfo(DiskStationApi api, DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 240
   at NzbDrone.Core.Download.Clients.DownloadStation.UsenetDownloadStation.ValidateVersion() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\UsenetDownloadStation.cs:line 300
   at NzbDrone.Core.Download.Clients.DownloadStation.UsenetDownloadStation.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\UsenetDownloadStation.cs:line 263
```

**Comment by ta264** [comment]
Self signed certificates don't work in v3 by design. The paths are nothing to worry about

**Comment by jwoodhouse** [comment]
@R8s6 I'm tempted to say your issue is unrelated to what we are experiencing with regards to the web ui login issue, since my Radarr is able to connect to download clients just fine over SSL, and my trace log doesnt mention any SSL failures.

**Comment by Eds1989** [comment]
My cert is issued by an internal AD CA. Is it a case of Radarr require the root CA cert to be added as well? The server has the root cert installed, so as far as the server and my clients are concerned, the certificate chain is valid.

**Comment by Eds1989** [comment]
> @austinwbest seems to be an issue isolated to using IIS ?
> https://www.reddit.com/r/radarr/comments/k4qek9/http2_tls_issues_after_upgrading_to_v3_server/

As the OP in that thread also says, I don't think the issues are the same, as I don't get the error they report.
I can load the page, the login just doesn't complete via HTTPS.

**Comment by boekhold** [comment]
Apologies for replying to a closed issue, but was anything actually fixed? I have the exact same issue with Radarr 3.0.0.4204, installed on Dec 8,  on Ubuntu 20.04, using a Let's Encrypt issued certificate (which I previously used for v2, and I'm using as well for Sonarr & Plex).

**Comment by bakerboy448** [comment]
@boekhold the https login loop?

Current workaround is run http behind a proper reverse proxy

**Comment by samw5** [comment]
i think what he means by the https login loop is that the main login page with the SSL cert on v3 does actually load but once you enter the creds and try to sign in, it kicks you right back to the login page w/o processing the sign in. 
Interestingly my Sonarr v3 instance that's still using the cert hash is working just fine (same cert).

**Comment by egyptianbman** [comment]
I too all of a sudden am locked out due to the recent update. The browser is able to successfully make the initial request but then isn't able to submit the authentication leading to a basic auth loop. I'm running it with ssl disabled and a proxy in front that takes care of LE and ssl.

**Comment by ta264** [comment]
@egyptianbman that's a different issue, see https://wiki.servarr.com/Radarr_FAQ#why_doesnt_radarr_work_behind_an_nginx_reverse_proxy

**Comment by egyptianbman** [comment]
Thanks for the tip, @ta264 -- unfortunately, that didn't do the trick for me. The interesting thing is I get 401 on `/` then when I authenticate, a few requests succeed until `/index.js`. When I try to authenticate for that, I don't see that the authentication is being submitted to the server.

**Comment by egyptianbman** [comment]
I take that back. It seems maybe my browser had something cached because several hours later, I am now able to access Radarr. Thank you!

**Comment by Eds1989** [comment]
Is this accepted as a bug or do I need to try anything else before it is accepted as one? Cheers

**Comment by gconcepts** [comment]
Setting URL Base to /radarr allows me to login when accessing via https

**Comment by Eds1989** [comment]
Yep same here!

**Comment by Eds1989** [comment]
Is this likely to get fixed? Since Lidarr resolved their bug with the application not starting with SSL enabled, I see the same behaviour with that too.

I am not yet in a position to run a reverse proxy in my environment due to using RD Gateway, and not being able to get that working behind a reverse proxy. I therefore need direct SSL connectivity to individual apps.

**Comment by ta264** [comment]
Unlikely unless someone steps up with a pull request.

We'll be replacing the webserver component in 4.0 which may or may not improve things. Until then I'm reluctant to waste the time on the old one.

**Comment by ta264** [comment]
I have tested this in the new setup (which we will swap to as part of radarr 4.0) and I believe login works on https with no URL base.  So this should get fixed eventually.
