### ISSUE TITLE
Failure to update to3.0.0.4204

### ISSUE THREAD

**Issue by tmathura** [Radarr/Radarr#5479]
**Describe the bug**
I have an issue where Radarr fails to update, either manually or automatically. It is trying to update from 0.2.0.1504 to 3.0.0.4204. I get the below error in the logs:

`Error occurred while executing task ApplicationUpdate: The request was aborted: Could not create SSL/TLS secure channel.

System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at NzbDrone.Common.Http.HttpClient.DownloadFile(String url, String fileName) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 255
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in C:\projects\radarr-usby1\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 102
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 221
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 93
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 43`

**To Reproduce**
1. Go to System --> Update
2. Click on "Install Latest"
4. See error in Logs

**Expected behavior**
Radarr should update to the latest version.

**Platform Information (please complete the following information):**
 - OS: Windows 10 Pro 2004
 - Docker: No
 - Mono or.NET Core Version: Don't see it
 - Radarr Version 0.2.0.1504
 - Radarr Branch develop

**Comment by austinwbest** [comment]
Disable https, there is info about it on the wiki.
