### ISSUE TITLE
Download station broken

### ISSUE THREAD

**Issue by trapie** [Radarr/Radarr#5515]
**Describe the bug**
The download station torrent client is broken.

**To Reproduce**
Updated the docker version to the new UI, since then Radarr is unable to connect to my Synology NAS.
The NAS is on a different subnet, but has full access, and with the previous version it was working perfectly.
I have tried to create a new client, but it also has the same issue it wouldn't connect.
The NAS has a high port (not default) and ssl is enabled. 2FA is not.

**Expected behavior**
Normal operation would work after update.

**Platform Information (please complete the following information):**
 - OS: Ubuntu
 - Docker: Yes
Version
3.0.0.4204
Package Version
3.0.0.4204-ls86 by linuxserver.io
.NET Core
Yes (3.1.10)
Docker
Yes
DB Migration
188
AppData directory
/config
Startup directory
/app/radarr/bin
Mode
Console
Uptime

**Trace Logs**
[v3.0.0.4204] NzbDrone.Core.Download.Clients.DownloadClientUnavailableException: Unable to connect to Diskstation, please check your settings

 ---> System.Net.WebException: The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.: 'https://192.168.123.51:61542/webapi/query.cgi?api=SYNO.API.Info&version=1&method=query&query=SYNO.API.Auth%2CSYNO.DownloadStation.Task'

 ---> System.Net.WebException: The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.

 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.

   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)

   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)

   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)

   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)

   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)

   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)

   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)

   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)

   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)

--- End of stack trace from previous location where exception was thrown ---

   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)

   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

--- End of stack trace from previous location where exception was thrown ---

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

   at System.Net.HttpWebRequest.SendRequest()

   at System.Net.HttpWebRequest.GetResponse()

   --- End of inner exception stack trace ---

   at System.Net.HttpWebRequest.GetResponse()

   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 146

   --- End of inner exception stack trace ---

   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 146

   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 123

   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 57

   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T](HttpRequestBuilder requestBuilder, String operation, DiskStationApi api, DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 93

   --- End of inner exception stack trace ---

   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T](HttpRequestBuilder requestBuilder, String operation, DiskStationApi api, DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 93

   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.UpdateApiInfo(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 208

   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.GetApiInfo(DiskStationApi api, DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 240

   at NzbDrone.Core.Download.Clients.DownloadStation.TorrentDownloadStation.ValidateVersion() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\TorrentDownloadStation.cs:line 402

   at NzbDrone.Core.Download.Clients.DownloadStation.TorrentDownloadStation.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\TorrentDownloadStation.cs:line 365

[Warn] RadarrErrorPipeline: Invalid request Validation failed: 

 -- Host: Unable to connect to Torrent Download Station 

[Error] X509CertificateValidationService: Certificate validation for https://192.168.123.51:61542/webapi/query.cgi?api=SYNO.API.Info&version=1&method=query&query=SYNO.API.Auth%2CSYNO.DownloadStation.Task failed. RemoteCertificateNameMismatch, RemoteCertificateChainErrors 

[Error] TorrentDownloadStation: Error testing Torrent Download Station 

[v3.0.0.4204] NzbDrone.Core.Download.Clients.DownloadClientUnavailableException: Unable to connect to Diskstation, please check your settings

 ---> System.Net.WebException: The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.: 'https://192.168.123.51:61542/webapi/query.cgi?api=SYNO.API.Info&version=1&method=query&query=SYNO.API.Auth%2CSYNO.DownloadStation.Task'

 ---> System.Net.WebException: The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.

 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.

   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)

   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)

   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)

   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)

   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)

   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)

   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)

   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)

   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)

--- End of stack trace from previous location where exception was thrown ---

   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)

   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

--- End of stack trace from previous location where exception was thrown ---

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

   at System.Net.HttpWebRequest.SendRequest()

   at System.Net.HttpWebRequest.GetResponse()

   --- End of inner exception stack trace ---

   at System.Net.HttpWebRequest.GetResponse()

   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 146

   --- End of inner exception stack trace ---

   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 146

   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 123

   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 57

   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T](HttpRequestBuilder requestBuilder, String operation, DiskStationApi api, DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 93

   --- End of inner exception stack trace ---

   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T](HttpRequestBuilder requestBuilder, String operation, DiskStationApi api, DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 93

   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.UpdateApiInfo(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 208

   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.GetApiInfo(DiskStationApi api, DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 240

   at NzbDrone.Core.Download.Clients.DownloadStation.TorrentDownloadStation.ValidateVersion() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\TorrentDownloadStation.cs:line 402

   at NzbDrone.Core.Download.Clients.DownloadStation.TorrentDownloadStation.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\TorrentDownloadStation.cs:line 365

[Warn] RadarrErrorPipeline: Invalid request Validation failed: 

 -- Host: Unable to connect to Torrent Download Station

**Comment by ta264** [comment]
Disable SSL if you don't have a valid ssl certificate on the NAS

**Comment by trapie** [comment]
Thanks!
