### ISSUE TITLE
radarr not connecting to xmlrpc - response does not contain valid xml

### ISSUE THREAD

**Issue by jamiew0w** [Radarr/Radarr#5516]
hi guys, i've setup sonarr/radarr many times with rtorrent but i'm running into issues now. I'm unsure if it's to do with V3 however have tested with v2 and works fine.

**To Reproduce**
1. Be using Cloudflare
2. Setup rtorrent downloader (domain, 443, /rutorrent/plugins/httprpc/action.php, username & password)
3. Click test or save, reopen and test.

**Expected behavior**
it should pass test without error

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Docker: [No]
 - .NET Core Yes (3.1.10)
 - Radarr Version [3.0.0.4204]

**Trace Logs**

Here's the response code from nginx:

```
- [08/Dec/2020:10:49:51 +0000] "POST /rutorrent/plugins/httprpc/action.php HTTP/1.1" 200 5 "-" "XML-RPC.NET"
```
(200 indicating no problem)

Radarr:

```
Failed to test rTorrent: Response from server does not contain valid XML.

CookComputing.XmlRpc.XmlRpcIllFormedXmlException: Response from server does not contain valid XML.
 ---> System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at CookComputing.XmlRpc.XmlRpcSerializer.DeserializeResponse(Stream stm, Type svcType)
   --- End of inner exception stack trace ---
   at CookComputing.XmlRpc.XmlRpcSerializer.DeserializeResponse(Stream stm, Type svcType)
   at CookComputing.XmlRpc.XmlRpcClientProtocol.ReadResponse(XmlRpcRequest req, WebResponse webResp, Stream respStm, Type returnType)
   at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke(Object clientObj, MethodInfo mi, Object[] parameters)
   at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke(MethodInfo mi, Object[] parameters)
   at XmlRpcProxy448ce507-5f17-49f8-bda3-85ec9168a69a.GetVersion()
   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.<>c__DisplayClass2_0.<GetVersion>b__0() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:line 67
   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.ExecuteRequest[T](Func`1 task) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:line 262
   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.GetVersion(RTorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:line 67
   at NzbDrone.Core.Download.Clients.RTorrent.RTorrent.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrent.cs:line 203
```

**Comment by ta264** [comment]
Pretty sure this will just be the SSL validation failing. If you need help getting it working again please join the discord channel

**Comment by jamiew0w** [comment]
> 
> 
> Pretty sure this will just be the SSL validation failing. If you need help getting it working again please join the discord channel

Thanks for the prompt reply, this is with ssl-validation disabled. I'll leave this closed for now while I look into other possibilities, can re-open it later if no luck.
