### ISSUE TITLE
Radarr v3 not deleting files and folders with Recycle Bin folder configured.

### ISSUE THREAD

**Issue by soccerdmon11** [Radarr/Radarr#5525]
**Describe the bug:** 
I added the folder location for the Recycle bin. When I delete a movie from Radarr and select to delete files and folders, an error occurs and does not delete them:

2020-12-9 14:09:41.9|Info|MovieService|Deleted movie [ABC]
2020-12-9 14:09:43.8|Info|RecycleBinProvider|Attempting to send '/mnt/plexdrive/Movies/ABC' to recycling bin
2020-12-9 14:09:43.9|Error|TaskExtensions|Task Error

[v3.0.1.4251] System.IO.IOException: Invalid cross-device link
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFolder(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 263
   at NzbDrone.Common.Disk.DiskTransferService.TransferFolder(String sourcePath, String targetPath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 89
   at NzbDrone.Core.MediaFiles.RecycleBinProvider.DeleteFolder(String path) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\RecycleBinProvider.cs:line 57
   at NzbDrone.Core.MediaFiles.MediaFileDeletionService.HandleAsync(MoviesDeletedEvent message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MediaFileDeletionService.cs:line 116
   at NzbDrone.Core.Messaging.Events.EventAggregator.<>c__DisplayClass6_2`1.<PublishEvent>b__2() in D:\a\1\s\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 122
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

Recycle bin folder configured as: /mnt/plexdrive/Recycle_bin

When updating a movie to a newer file, the old file gets moved to the Recycle bin folder with no issues. 

When I remove the folder location for the Recycle bin and delete a movie, it deletes the movie permanently. 

2020-12-9 14:15:31.4|Info|MovieService|Deleted movie [XYZ]
2020-12-9 14:15:33.3|Info|RecycleBinProvider|Attempting to send '/mnt/plexdrive/Movies/XYZ' to recycling bin
2020-12-9 14:15:33.3|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /mnt/plexdrive/Movies/XYZ

**Expected Behavior**
When deleting a movie with Recycle Bin configured, it should move the file and folder to the Recycle bin.

**Version info**
Radarr: v3.0.1.4251
OS: Linux Mint v20

**Comment by bakerboy448** [comment]
`[v3.0.1.4251] System.IO.IOException: Invalid cross-device link`  this points more to a config or mount issue rather than an actual bug
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

since OP left it out: branch is `nightly`
OP be sure you want to be running the bleeding edge :)  I don't think you can switch to the normal branches just yet as there is a DB migration out there

I'll reopen if we confirm that this is indeed a bug and not a config issue.
