### ISSUE TITLE
Changing movie's root folder is unable to move the files between drives in mergerfs pool.

### ISSUE THREAD

**Issue by SugarDroid** [Radarr/Radarr#5558]
**Describe the bug**
Changing movie's root folder is unable to move the files between drives in mergerfs pool. If hardlink enabled in media management then nothing happens, if disabled then root gets changed in the database but the files aren't moved physically.

**To Reproduce**

1. create a mergerfs pool with 2 drives
2. create 1 -differently named- folder on both drives, like "movies" on A drive and "Movies" on B drive
3. add both to Radarr as root
4. add a movie to one of them and try to move it to the other and choose "yes, move the files" option

**Expected behavior**
A move should be move, not hardlinking and then delete the original.

**Platform Information (please complete the following information):**

- Version 3.0.1.4263
- Package Version 3.0.1.4263-ls4 by linuxserver.io
- .NET Core Yes (3.1.10)
- Docker Yes

**Trace Logs**

```
[v3.0.1.4263] System.IO.IOException: Invalid cross-device link
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFolder(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 263
   at NzbDrone.Common.Disk.DiskTransferService.TransferFolder(String sourcePath, String targetPath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 89
   at NzbDrone.Core.Movies.MoveMovieService.MoveSingleMovie(Movie movie, String sourcePath, String destinationPath, Nullable`1 index, Nullable`1 total) in D:\a\1\s\src\NzbDrone.Core\Movies\MoveMovieService.cs:line 59
```

**Comment by bakerboy448** [comment]
Need to know if this is reproducible on sonarr as well

either upstream issue or something radarr (netcore?) specific

**Comment by SugarDroid** [comment]
@bakerboy448 https://github.com/Sonarr/Sonarr/issues/4185

**Comment by bakerboy448** [comment]
> ### Current Behavior
> Edit of Movie Path OR Movie Editor Change Root Path fails with:
> 
> Unable to move movie from '/mnt/share/media/Videos/movies/Knives Out (2019)' to '/mnt/datashare/media/Videos/movies/Knives Out (2019)'. Try moving files manually: Cross-device link
> 
> System.IO.IOException: Cross-device link at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath) at System.IO.Directory.Move(String sourceDirName, String destDirName) at NzbDrone.Common.Disk.DiskProviderBase.MoveFolder(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 262 at NzbDrone.Common.Disk.DiskTransferService.TransferFolder(String sourcePath, String targetPath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 88 at NzbDrone.Core.Movies.MoveMovieService.MoveSingleMovie(Movie movie, String sourcePath, String destinationPath, Nullable`1 index, Nullable`1 total) in D:\a\1\s\src\NzbDrone.Core\Movies\MoveMovieService.cs:line 57
> 
> NOTE: This was working with Mono-based v3 of Radarr.
> 
> ### Environment
> ```gfm
> - OS: TrueNAS-12.0-U8
> - Radarr: 4.0.4.5922
> - Docker Install: No
> - Using Reverse Proxy: No
> - Browser: Firefox 98.0
> ```
> 
> ### Trace Logs?
> 2022-03-10 07:54:15.0|Info|MoveMovieService|Moving 1 movies to '/mnt/datashare/media/Videos/movies' 2022-03-10 07:54:15.0|Info|MoveMovieService|Moving Knives Out from '/mnt/share/media/Videos/movies/Knives Out (2019)' to '/mnt/datashare/media/Videos/movies/Knives Out (2019)' (1/1) 2022-03-10 07:54:15.0|Error|MoveMovieService|Unable to move movie from '/mnt/share/media/Videos/movies/Knives Out (2019)' to '/mnt/datashare/media/Videos/movies/Knives Out (2019)'. Try moving files manually
> 
> [v4.0.4.5922] System.IO.IOException: Cross-device link at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath) at System.IO.Directory.Move(String sourceDirName, String destDirName) at NzbDrone.Common.Disk.DiskProviderBase.MoveFolder(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 262 at NzbDrone.Common.Disk.DiskTransferService.TransferFolder(String sourcePath, String targetPath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 88 at NzbDrone.Core.Movies.MoveMovieService.MoveSingleMovie(Movie movie, String sourcePath, String destinationPath, Nullable`1 index, Nullable`1 total) in D:\a\1\s\src\NzbDrone.Core\Movies\MoveMovieService.cs:line 57
> 
> 2022-03-10 07:54:15.0|Info|MoveMovieService|Finished moving 1 movies to '/mnt/datashare/media/Videos/movies'
> 

From @madhackbt on #7126

**Comment by madhackbt** [comment]
@bakerboy448 I am using Sonarr 3.0.7.1477 (mono 6.8.0.105 on the TrueNAS-12.0-U8) and the "Move" operation works just fine. I had seen this report, but I did not have the "mergerfs" type config, Thanks for handling this.

**Comment by christianha1111** [comment]
I can confirm the same thing happens on Sonarr 4.2.4.6635 if mergerfs is used.

**Comment by colinborins** [comment]
Any movement on this?

**Comment by 0xdevalias** [comment]
See also:

- https://github.com/Sonarr/Sonarr/issues/4185
- https://github.com/Lidarr/Lidarr/issues/1827

**Comment by Panda260** [comment]
any updates? kinda an important bug i think
