### ISSUE TITLE
Raddar Connection to Plex Server Fails

### ISSUE THREAD

**Issue by Ryonez** [Radarr/Radarr#5619]
**Describe the bug**
A connection to Plex Media Server fails.

**To Reproduce**
1. Go to 'Settings -> Connect'
2. Add a "Plex Media Server" Connection
3. After filling in the information, click "Test"
4. Test Fails

**Expected behavior**
The test to succeed, and for Radarr to be able to communicate to the Plex Server.

**Screenshots**
![image](https://user-images.githubusercontent.com/16157130/103089171-ff08e380-4651-11eb-9950-557903d3138f.png)

**Platform Information (please complete the following information):**
 - OS: unRaid 6.8.3
 - Docker: Yes
 - Mono or.NET Core Version: Yes (3.1.10
 - Radarr Version 3.0.1.4259
 - Docker Image: https://registry.hub.docker.com/u/binhex/arch-radarr/

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

Abridged Logs (Full log contains Library information):
```
2020-12-25 01:39:02.9|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Host: Unable to connect to Plex Server
2020-12-25 01:42:07.4|Warn|HttpClient|HTTP Error - Res: [GET] https://10.1.1.101:32400/library/sections?X-Plex-Client-Identifier=(removed)&X-Plex-Product=Radarr&X-Plex-Platform=Windows&X-Plex-Platform-Version=7&X-Plex-Device-Name=Radarr&X-Plex-Version=3.0.1.4259: 503.ServiceUnavailable
2020-12-25 01:42:07.5|Error|PlexServerService|Unable to connect to Plex Server

[v3.0.1.4259] NzbDrone.Core.Notifications.Plex.PlexException: Unable to connect to Plex Media Server. Status Code: ServiceUnavailable
   at NzbDrone.Core.Notifications.Plex.Server.PlexServerProxy.ProcessRequest(HttpRequestBuilder requestBuilder) in D:\a\1\s\src\NzbDrone.Core\Notifications\Plex\Server\PlexServerProxy.cs:line 193
   at NzbDrone.Core.Notifications.Plex.Server.PlexServerProxy.GetMovieSections(PlexServerSettings settings) in D:\a\1\s\src\NzbDrone.Core\Notifications\Plex\Server\PlexServerProxy.cs:line 39
   at NzbDrone.Core.Notifications.Plex.Server.PlexServerService.GetSections(PlexServerSettings settings) in D:\a\1\s\src\NzbDrone.Core\Notifications\Plex\Server\PlexServerService.cs:line 93
   at NzbDrone.Core.Notifications.Plex.Server.PlexServerService.Test(PlexServerSettings settings) in D:\a\1\s\src\NzbDrone.Core\Notifications\Plex\Server\PlexServerService.cs:line 186

```

Further Notes:

I have a Sonarr installation that's running V2. It is able to connect to the server without issue, so I don't feel it's only an issue with the server, but possibly with the way Radarr is trying to communicate, as how connections authorize has changed.

**Comment by ta264** [comment]
Don't use SSL to an IP address, you won't have a valid certificate for it

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/Radarr_FAQ#invalid_certificate_and_other_https_or_ssl_issues

**Comment by Ryonez** [comment]
I dislike how much is assumed in this little section.

> If your client and radarr are on the same local network there is absolutely 0 reason to use HTTPS. You're implying you do not trust your network. That is pointless and causes nothing but problems, stop doing that. 

A local network is not the same as a local machine, and have various trust levels I use around things. I can not guarantee that everything will always be secure, and I see zero reason why I can't take steps to limit potential damage to my setup.

I ask you to reword this, and inform users why why you recommend things a certain way instead of treating them as a child. When I sort out final configuration, it will be secured over ssl, because that is my preference for my network. There is a reverse proxy setup, but this was failing no matter the setup.

However I'm certainly not against trying things. It still fails with it disabled.
![image](https://user-images.githubusercontent.com/16157130/103090996-a2a8c280-4657-11eb-82a7-d5b4b6f47b6f.png)

```
2020-12-25 02:18:24.5|Warn|HttpClient|HTTP Error - Res: [GET] http://10.1.1.101:32400/library/sections?X-Plex-Client-Identifier=(removed)&X-Plex-Product=Radarr&X-Plex-Platform=Windows&X-Plex-Platform-Version=7&X-Plex-Device-Name=Radarr&X-Plex-Version=3.0.1.4259: 503.ServiceUnavailable
2020-12-25 02:18:24.5|Error|PlexServerService|Unable to connect to Plex Server

[v3.0.1.4259] NzbDrone.Core.Notifications.Plex.PlexException: Unable to connect to Plex Media Server. Status Code: ServiceUnavailable
   at NzbDrone.Core.Notifications.Plex.Server.PlexServerProxy.ProcessRequest(HttpRequestBuilder requestBuilder) in D:\a\1\s\src\NzbDrone.Core\Notifications\Plex\Server\PlexServerProxy.cs:line 193
   at NzbDrone.Core.Notifications.Plex.Server.PlexServerProxy.GetMovieSections(PlexServerSettings settings) in D:\a\1\s\src\NzbDrone.Core\Notifications\Plex\Server\PlexServerProxy.cs:line 39
   at NzbDrone.Core.Notifications.Plex.Server.PlexServerService.GetSections(PlexServerSettings settings) in D:\a\1\s\src\NzbDrone.Core\Notifications\Plex\Server\PlexServerService.cs:line 93
   at NzbDrone.Core.Notifications.Plex.Server.PlexServerService.Test(PlexServerSettings settings) in D:\a\1\s\src\NzbDrone.Core\Notifications\Plex\Server\PlexServerService.cs:line 186
   ```

**Comment by ta264** [comment]
I agree, that wiki article has not been worded in the professional manner I think we should be striving for and I will change it.

However from your updated log file it looks like the plex server is not available.  Please join the discord channel if you need further support.

**Comment by Ryonez** [comment]
Thank you very much, I'll will do a bit later, considering the holidays.

Have a great Christmas.
