### ISSUE TITLE
Radarr v3 Automatic Import input/output error

### ISSUE THREAD

**Issue by BigH3ater** [Radarr/Radarr#5708]
**Describe the bug**

I have a CIFS mount from a Mergerfs unionfs merged with a local and rclone google drive mount.  It writes locally first then I have a job to move the file to the cloud.  When Radarr tries to import a file from nzbget they will intermittently move.  The files have the same permission level, same directory mapping and same ownership.

**To Reproduce**

Download several movies at once and the issue will appear.

I have the the service running as user media group media.

<img width="734" alt="Service User" src="https://user-images.githubusercontent.com/65198109/104036244-c6f8b900-5198-11eb-9375-87770176987f.PNG">

**Platform Information (please complete the following information):**

    OS: Ubuntu 18.04
    Docker: No
    Mono or.NET Core Version: .Net Core 3.1.10
    Radarr Version 3.0.1.4259
    Radarr Branch master

Mono version for sonarr on the vm.

mono --version
Mono JIT compiler version 5.20.1.34 (tarball Tue Jul 16 22:52:32 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

I attached the radarr log because its to large for pastebin.  Let me know what other information would help.
[Radarr log.txt](https://github.com/Radarr/Radarr/files/5788124/Radarr.log.txt)

Example:

/Downloads# ls -l
total 0
drwxr-xr-x 2 media media 0 Jan  8 16:03 Movies

/Downloads/Movies/Defendor.2009.1080p.Blu-ray.Remux.AVC.DTS-HD.MA.5.1.KRaLiMaRKo# ls -l
total 14349312
-rwxr-xr-x 1 media media 15201952749 Jan  1 12:37 cb7d4373529477b5facfbc0bdb029ccb.mkv

Couldn't import movie /Downloads/Movies/Defendor.2009.1080p.Blu-ray.Remux.AVC.DTS-HD.MA.5.1.KRaLiMaRKo/cb7d4373529477b5facfbc0bdb029ccb.mkv: Input/output error

System.IO.IOException: Input/output error
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at NzbDrone.Mono.Disk.DiskProvider.TransferFilePatched(String source, String destination, Boolean overwrite, Boolean move) in D:\a\1\s\src\NzbDrone.Mono\Disk\DiskProvider.cs:line 337
   at NzbDrone.Mono.Disk.DiskProvider.CopyFileInternal(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Mono\Disk\DiskProvider.cs:line 260
   at NzbDrone.Common.Disk.DiskProviderBase.CopyFile(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 231
   at NzbDrone.Common.Disk.DiskTransferService.TryCopyFileVerified(String sourcePath, String targetPath, Int64 originalSize) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 478
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 381
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 119
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 79
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 75
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:line 123

[AB#669](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/669)

**Comment by bakerboy448** [comment]
Trace logs?

Also note that Qbit is not responding.

It almost look  you're possibly getting I/O errors strictly due to disk lock...?

**Comment by BigH3ater** [comment]
[radarr trace.txt](https://github.com/Radarr/Radarr/files/5789701/radarr.trace.txt)


Here is a trace log for a failed import.

Couldn't import movie /Downloads/Movies/Felony.2013.1080p.BluRay.REMUX.AVC.TrueHD.5.1-EPSiLON/9de027a793894358988c395fc0d92169.mkv: Input/output error

**Comment by bakerboy448** [comment]
@BigH3ater I think that's the wrong tracelog...? that error isn't in there

**Comment by BigH3ater** [comment]
I see the import trying at line 859 but you are right.  I don't see that actual in the logs for this import input/output error.  I will try to generate another example.

**Comment by BigH3ater** [comment]
![image](https://user-images.githubusercontent.com/65198109/104196082-ff8ed180-53e8-11eb-9e22-2feda96c24e1.png)

![image](https://user-images.githubusercontent.com/65198109/104196513-7b891980-53e9-11eb-9fd4-495058ee708e.png)

[trace 8_18 am 2.txt](https://github.com/Radarr/Radarr/files/5796396/trace.8_18.am.2.txt)
[trace 8_18 am 1.txt](https://github.com/Radarr/Radarr/files/5796397/trace.8_18.am.1.txt)


I attached the only trace files that show that movie in the logs but I still don't see that input/output error listed.  It actually imported it even though it said it failed.

**Comment by BigH3ater** [comment]
![image](https://user-images.githubusercontent.com/65198109/104199842-9198d900-53ed-11eb-807a-93a8febc374b.png)
[trace 9_09 2.txt](https://github.com/Radarr/Radarr/files/5796530/trace.9_09.2.txt)
[trace 9_09 3.txt](https://github.com/Radarr/Radarr/files/5796531/trace.9_09.3.txt)
[trace 9_09 1.txt](https://github.com/Radarr/Radarr/files/5796532/trace.9_09.1.txt)  
[debug 1_11 9_11.txt](https://github.com/Radarr/Radarr/files/5796551/debug.1_11.9_11.txt)

trace 9_09 line 1277 has the input/output error.  One thing I did notice, once this input/output error occurs it removes the movie from the import queue.  I would think it should have an error in the queue but maybe that is the issue.

I appreciate you looking at this.  Let me know if this has everything you need.

**Comment by chasx003** [comment]
I have the same issue, but with NFS, exact same setup works with v2 of Radarr (Kubernetes with media directory being a NFS mount)

[Warn] ImportApprovedMovie: Couldn't import movie /downloads/Movie.2001.720p.BluRay.x264.mkv 
[v3.0.2.4446] System.IO.IOException: Input/output error
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Int64 result, String path, Boolean isDirectory, Func`2 errorRewriter)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.FileSystem.LinkOrCopyFile(String sourceFullPath, String destFullPath)
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at NzbDrone.Mono.Disk.DiskProvider.TransferFilePatched(String source, String destination, Boolean overwrite, Boolean move) in D:\a\1\s\src\NzbDrone.Mono\Disk\DiskProvider.cs:line 333
   at NzbDrone.Mono.Disk.DiskProvider.MoveFileInternal(String source, String destination) in D:\a\1\s\src\NzbDrone.Mono\Disk\DiskProvider.cs:line 300
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 254
   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified(String sourcePath, String targetPath, Int64 originalSize) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 495
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 386
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 117
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 79
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 75
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:line 123

**Comment by jgriffiths014** [comment]
Got a very similar problem with the very same symptoms, this is running on an NFS mount mapped to the container, worked fin in V2, and all other containers can successfully rwx on the volume:


[v3.0.2.4488] System.IO.IOException: Invalid argument
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Int64 result, String path, Boolean isDirectory, Func`2 errorRewriter)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at NzbDrone.Mono.Disk.DiskProvider.TransferFilePatched(String source, String destination, Boolean overwrite, Boolean move) in D:\a\1\s\src\NzbDrone.Mono\Disk\DiskProvider.cs:line 337
   at NzbDrone.Mono.Disk.DiskProvider.CopyFileInternal(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Mono\Disk\DiskProvider.cs:line 254
   at NzbDrone.Common.Disk.DiskProviderBase.CopyFile(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 230
   at NzbDrone.Common.Disk.DiskTransferService.TryCopyFileVerified(String sourcePath, String targetPath, Int64 originalSize) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 476
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 355
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 117
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.CopyMovieFile(MovieFile movieFile, LocalMovie localMovie) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 96
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 71
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:line 123

**Comment by turygo** [comment]
> Got a very similar problem with the very same symptoms, this is running on an NFS mount mapped to the container, worked fin in V2, and all other containers can successfully rwx on the volume:
> 
> [v3.0.2.4488] System.IO.IOException: Invalid argument
> at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter) at Interop.CheckIo(Int64 result, String path, Boolean isDirectory, Func`2 errorRewriter)
> at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
> at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
> at NzbDrone.Mono.Disk.DiskProvider.TransferFilePatched(String source, String destination, Boolean overwrite, Boolean move) in D:\a\1\s\src\NzbDrone.Mono\Disk\DiskProvider.cs:line 337
> at NzbDrone.Mono.Disk.DiskProvider.CopyFileInternal(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Mono\Disk\DiskProvider.cs:line 254
> at NzbDrone.Common.Disk.DiskProviderBase.CopyFile(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 230
> at NzbDrone.Common.Disk.DiskTransferService.TryCopyFileVerified(String sourcePath, String targetPath, Int64 originalSize) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 476
> at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 355
> at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 117
> at NzbDrone.Core.MediaFiles.MovieFileMovingService.CopyMovieFile(MovieFile movieFile, LocalMovie localMovie) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 96
> at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 71
> at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:line 123

Same problem.It worked fine in v2 but breaked in v3.Radarr just import movie file and delete it once finished.Repeat it again and again.

**Comment by badangrycloud** [comment]
@turygo I have exactly the same problem, did you manage to solve it?

**Comment by bakerboy448** [comment]
For those on this issue running NFS, have you tried NFSv4 instead of v3? That occasionally does the trick.

Otherwise, for posterity noting that OP is on CIFS

**Comment by turygo** [comment]
Thank you @bakerboy448 for saving my day! @badangrycloud After spend hours change mount from NFS to CIFS,Finally Radarr v3 can import downloaded movie successfully. This weird problem seems only happened on docker container with mounted file system.

**Comment by jgriffiths014** [comment]
unfortunately not so easy for me, NFS client only supports max v3. is it confirmed that nfsV4 Server fixes the issue?

**Comment by ta264** [comment]
You could try mounting with the `nolock` option on v3

**Comment by jgriffiths014** [comment]
> You could try mounting with the `nolock` option on v3

nolock option doenst change anything for me unfortunately, still get 'invalid argumrnt' (nfsv3)
