### ISSUE TITLE
Unable to add uTorrent as a download client in Radarr 3.0.2.4369

### ISSUE THREAD

**Issue by Co0ljay** [Radarr/Radarr#5733]
Unable to add uTorrent as a download client in Radarr 3.0.2.4369

**To Reproduce**
Attempt to add uTorrent as a download client

See error log:
Message
Failed to test uTorrent: Unable to connect to uTorrent, please check your settings
Exception
NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to uTorrent, please check your settings
 ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [GET] at [http://localhost:58133/gui/token.html]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 96
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, UTorrentSettings settings, Boolean reauthenticate) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 262

invalid request
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, UTorrentSettings settings, Boolean reauthenticate) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 278
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.ProcessRequest(HttpRequestBuilder requestBuilder, UTorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 208
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.GetVersion(UTorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 51
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrent.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrent.cs:line 265

**Expected behavior**
Able to add uTorrent successfully as a download client.

**Platform Information (please complete the following information):**
 - OS: Windows 10 Edition	Windows 10 Pro
          Version	20H2
          Installed on	‎2020/‎08/‎02
           OS build	19042.746
           Experience	Windows Feature Experience Pack 120.2212.551.0

 - Docker: No
 - Mono or.NET Core Version: .Net (3.1.10)
 - Browser and Version Chrome Version 87.0.4280.141 (Official Build) (64-bit)
 - Radarr Version 3.0.2.4369
 - Radarr Branch : Develop

**Trace Logs**
2021-1-13 20:46:52.2|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- UrlBase: Must be a valid URL path (ie: '/sonarr')
2021-1-13 20:48:31.2|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- UrlBase: Must be a valid URL path (ie: '/sonarr')
2021-1-13 20:53:48.5|Warn|HttpClient|HTTP Error - Res: [GET] http://localhost:58133/gui/token.html: 400.BadRequest
2021-1-13 20:53:48.5|Error|UTorrent|Failed to test uTorrent

[v3.0.2.4369] NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to uTorrent, please check your settings
 ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [GET] at [http://localhost:58133/gui/token.html]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 96
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, UTorrentSettings settings, Boolean reauthenticate) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 262

invalid request
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, UTorrentSettings settings, Boolean reauthenticate) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 278
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.ProcessRequest(HttpRequestBuilder requestBuilder, UTorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 208
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.GetVersion(UTorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 51
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrent.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrent.cs:line 265

2021-1-13 20:53:48.5|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Host: Unable to connect to uTorrent
2021-1-13 20:55:07.4|Warn|HttpClient|HTTP Error - Res: [GET] http://localhost:58133/gui/token.html: 400.BadRequest
2021-1-13 20:55:07.4|Error|UTorrent|Failed to test uTorrent

[v3.0.2.4369] NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to uTorrent, please check your settings
 ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [GET] at [http://localhost:58133/gui/token.html]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 96
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, UTorrentSettings settings, Boolean reauthenticate) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 262

invalid request
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, UTorrentSettings settings, Boolean reauthenticate) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 278
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.ProcessRequest(HttpRequestBuilder requestBuilder, UTorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 208
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.GetVersion(UTorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 51
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrent.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrent.cs:line 265

2021-1-13 20:55:07.4|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Host: Unable to connect to uTorrent
2021-1-13 20:59:52.8|Info|LifecycleService|Restart requested.
2021-1-13 20:59:52.8|Info|CommandExecutor|Shutting down task execution
2021-1-13 20:59:52.8|Info|Scheduler|Shutting down scheduler
2021-1-13 20:59:53.9|Info|NzbDroneConsoleFactory|Attempting to stop application.
2021-1-13 20:59:53.9|Info|WebHostController|Attempting to stop OWIN host
2021-1-13 20:59:53.9|Info|NzbDroneConsoleFactory|Application has finished stop routine.
2021-1-13 20:59:53.9|Info|ConsoleApp|Exiting main.
2021-1-13 20:59:53.9|Info|WebHostController|Host has stopped
2021-1-13 20:59:57.8|Info|Bootstrap|Starting Radarr - C:\ProgramData\Radarr\bin\Radarr.Console.dll - Version 3.0.2.4369
2021-1-13 20:59:58.2|Info|Router|Application mode: Service
2021-1-13 20:59:58.4|Info|MigrationController|*** Migrating data source=C:\ProgramData\Radarr\radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2021-1-13 20:59:58.8|Info|MigrationController|*** Migrating data source=C:\ProgramData\Radarr\logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2021-1-13 21:00:00.2|Info|WebHostController|Listening on the following URLs:
2021-1-13 21:00:00.2|Info|WebHostController|  http://*:7878
2021-1-13 21:00:00.8|Info|RadarrBootstrapper|Starting Web Server
2021-1-13 21:00:02.5|Info|CommandExecutor|Starting 2 threads for tasks.
2021-1-13 21:00:39.7|Warn|HttpClient|HTTP Error - Res: [GET] http://localhost:58133/gui/token.html: 400.BadRequest
2021-1-13 21:00:39.7|Error|UTorrent|Failed to test uTorrent

[v3.0.2.4369] NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to uTorrent, please check your settings
 ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [GET] at [http://localhost:58133/gui/token.html]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 96
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, UTorrentSettings settings, Boolean reauthenticate) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 262

invalid request
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, UTorrentSettings settings, Boolean reauthenticate) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 278
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.ProcessRequest(HttpRequestBuilder requestBuilder, UTorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 208
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.GetVersion(UTorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 51
   at NzbDrone.Core.Download.Clients.UTorrent.UTorrent.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrent.cs:line 265

2021-1-13 21:00:39.9|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Host: Unable to connect to uTorrent

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

Because uTorrent is known for cryptoware, malware and ads we'd suggest switching to a better client like qBittorrent, Deluge or ruTorrent. In the mean time, you can probably fix it by making a few suggested changes in the following FAQ entry.

<https://wiki.servarr.com/Radarr_FAQ#uTorrent_is_no_longer_working>
