### ISSUE TITLE
Can't find "Once Upon a Time in America"

### ISSUE THREAD

**Issue by Zamana** [Radarr/Radarr#5774]
**Describe the bug**
When I try to add a new movie called [Once Upon a Time in America](https://www.themoviedb.org/movie/311-once-upon-a-time-in-america), I got the error:

Failed to load search results, please try again.
Search for 'once upon a time in america' failed. Invalid response received from TMDb.

**To Reproduce**
1. Go to Movies -> Add New
2. Fill the search bar with the movie's title: "Once Upon a Time in America"
3. See error

**Expected behavior**
I expected to see some suggestions related with the movie I was looking for.

At the same time I can find other movies, so this exclude the possibility of network issues, for example:

**Screenshots**
![error](https://user-images.githubusercontent.com/6900313/104856371-105fab80-58f1-11eb-9dbc-f0460c4edc62.png)

**Platform Information:**
 - OS: Debian 10 in a VM in FreeNAS
 - Docker: Yes
 - Mono or.NET Core Version: .NET Core3.1.10
 - Radarr Version: 3.0.1.4259-ls89 by linuxserver.io
 - Radarr Branch: Master

**Trace Logs**
Attached.
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/5826864/radarr.trace.txt)

**Events**
`Error parsing column 5 (Language=30 - Int64): Error parsing column 5 (Language=30 - Int64)`

`System.Data.DataException: Error parsing column 5 (Language=30 - Int64)
 ---> System.ArgumentException: ID does not match a known language (Parameter 'id')
   at NzbDrone.Core.Languages.Language.FindById(Int32 id) in D:\a\1\s\src\NzbDrone.Core\Languages\Language.cs:line 159
   at Dapper.SqlMapper.TypeHandler`1.Dapper.SqlMapper.ITypeHandler.Parse(Type destinationType, Object value) in C:\projects\dapper\Dapper\SqlMapper.TypeHandler.cs:line 42
   at Dapper.SqlMapper.TypeHandlerCache`1.Parse(Object value) in C:\projects\dapper\Dapper\SqlMapper.TypeHandlerCache.cs:line 23
   at Deserialize5188c15b-124f-48f5-8306-3a0c8e4b5757(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in C:\projects\dapper\Dapper\SqlMapper.cs:line 3633
   at Deserialize5188c15b-124f-48f5-8306-3a0c8e4b5757(IDataReader )
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[T](IDatabase db, String sql, Object param)
   at NzbDrone.Core.Datastore.BasicRepository`1.Query(SqlBuilder builder)
   at NzbDrone.Core.Datastore.BasicRepository`1.Query(Expression`1 where)
   at NzbDrone.Core.Movies.Translations.MovieTranslationRepository.FindByMovieId(Int32 movieId)
   at NzbDrone.Core.Movies.Translations.MovieTranslationService.GetAllTranslationsForMovie(Int32 movieId)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapSearchResult(MovieResource result)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at NzbDrone.Common.Extensions.EnumerableExtensions.SelectList[TSource,TResult](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title)
`

**Comment by Qstick** [comment]
You went from nightly to master, or develop to master thus you are feeling the consequences

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

[Language 30 was added after the current Latest/Stable Version](https://github.com/Radarr/Radarr/commit/3ab9af06636f7d3986c77359231643ffcdda11ab)

[Which means you did exactly what you are explicitly not supposed to do (without checking with the team first)](https://wiki.servarr.com/Radarr_FAQ#can_i_switch_between_branches)

Go back to develop for now. Switch to latest/master with the next major release.

Additionally, posting this big and bold, not specifically for you, but because this is a frequent occurrence:
### Support Requests will be closed immediately, if you are unsure go to our Reddit or Discord first. Exceptions do not mean you found a bug!
