### ISSUE TITLE
Importing Movies from library just stops and UI gets stuck

### ISSUE THREAD

**Issue by KaiAKoenig** [Radarr/Radarr#5924]
Note: I already tried to get help on Reddit: https://www.reddit.com/r/radarr/comments/l8lvqf/strange_behavior_when_importing_existing_movie/
He was not able to help me. If this is not the correct place to get further help, please direct me to the correct location.

I reinstalled my QNAP and in the process of that re-installed Radarr starting from scratch (No existing db import). I then tried to import my existing Radarr managed movie library and encountered a problem. After adding a root folder, it automatically starts trying to map folders to movies and it does for some time taking ~1-4s per movie. After some time, it just stops. At the bottom, it shows that its still processing folders and the import Movies button is still greyed out, but I can let it run for hours and nothing will change. When I looked at the logs, I did not find anything indicating a problem. However, I saw that it parsed a movie and then stopped. On the Web interface it never showed that it finished that. There, the last processed movie was the one just before.

Some additional info from experimenting (not part of the log filed):
- When I try to cancel the processing and import the detected movies, It either works some times, or it freezes as well, or I get a web error. If it works, then it only does so for 5 movies at a time. If I try to import more than 5 it usually freezes there as well.
- When I finally managed to import some movies, most of the time at least one or two movies do not have movie posters in the movie overview. When I try to refresh all using the movie mass editor, you guessed it, it usually freezes. I can try to do it one at a time, but even then after 4-5 movies it usually gets stuck updating the movie. I can then do maybe two other updates manually before the update symbols on the movies posters become unresponsive.
- Additionally, the Movie Refresh Task automatically started when starting Radarr never seems to finish at all.
- When I add indexers and a download client, the RSS parsing and the automatic download work just fine.

So, for me, it seems there is some real problem handling multiple tasks in my system setup. But I have no clue what makes my system special in that regard.

**To Reproduce**
1. Install Radarr and run it.
2. Select Movies / Library Import and select the previously Radarr managed movie library
3. Wait a minute

**Expected behavior**
Movies are processed until all folders are mapped or an error is shown (at least in the logs)

**Screenshots**
This is how it looks like when it is stuck (no change from this for hours): https://pasteboard.co/JNU3diV.png
When I hit F5 it reloads and starts again and get stuck again. The movie where it stops is always different.

**Platform Information (please complete the following information):**
 - OS: Linux (specifically QNAP QTS 4.2.1)
 - Docker: No
 - Mono or .NET Version (System -> Status): .Net Core 3.1.10
 - Browser and Version (Only needed for UI issues): Opera 73.0.3856.344
 - Radarr Version: 3.0.2.4552
 - Radarr Branch: master

The App is installed on an SSD on the NAS base drive (single disk). The movie library is on an raid 5.
Before I reinstalled my QNAP, I made sure to rename all movies in the library (using Radarr) and removed all unnecessary files from it.

**Trace Logs**
Although they show nothing, the logs can be found here:
trace: https://pastebin.com/HFENDasR
debug: https://pastebin.com/4FvWV3Hy

RETRY:I deleted all indexers and all download clients, cleared the logs, restarted radarr and then started library import. This time, it was stuck immediately. On the GUI he did not even show one completed folder processing.

trace: https://pastebin.com/pCm1NwA0
debug: https://pastebin.com/FWCBGt0a
normal: https://pastebin.com/aBztMjaZ

RETRY 2: I deleted the logs, restarted Radarr and then started library import again. After it froze I waited ~10min. until pulling the logs.
trace: https://pastebin.com/qUweDrPH

**Comment by KaiAKoenig** [comment]
Is still no one even looking at this?

**Comment by bakerboy448** [comment]
Issues are looked at when capacity allows and typically triaged. Critical breaking bugs that affect many people are handled first for example.

Bugs that impact fewer people are pushed further along the line.

If I had to take a stab in the dark, I'm guessing your issue is related somehow to Qnap either hardware or software given this is not otherwise widely reported.  

Typically issues relating to scanning movies on import or on disk are related mediainfo choking on a specific file or files if not permissions related.

The main development team is split across 3 apps: Radarr, Readarr, and Lidarr.
There are only 3 or 4 active developers who work on this, and of those 3 or 4 exactly zero work on this fulltime. Exactly zero of any members involved  (developers / support) get paid to do this. Everyone of us has fulltime real jobs. Everyone of us has kids and family. Everyone of us works on more than just this project.

**Comment by KaiAKoenig** [comment]
Thats ok. I just wanted to get some reaction. I acknowledge that this is not a critical issue and can wait, as long as it is not just ignored :)

**Comment by lrstanley** [comment]
I've got a similar issue.

   * Version: 3.0.2.4552
   * Package Version: 3.0.2.4552-ls100 by linuxserver.io
   * .NET Core: Yes (3.1.10)
   * Docker: Yes
   * OS: Ubuntu 20.04

NFS share is mounted into the container (using docker volume mount). Importing content from Sonarr, I didn't seem to have any issues. Plex, and Deluge also mount the NFS share exactly the same, and are running in the same Plex environment.

I go to import using `Movies > Library Import`. The three problems I'm facing while doing this for my 1000+ movie library:

1. Let it find all 1000 movies, only re-searched for a few movies that it didn't find the right result for, then click "Import X Movies". this seemed to run for some time, then randomly showed the error page, with no details. Unfortunately, I don't have the logs from this.
2. External http calls to 3rd party services fail with no apparent retries happening, causing the entire import to fail. Little annoying when it takes quite some time for it to scan for what each imported movie is.. It didn't save each movie as it was importing, it seems it has to complete ALL imports before it actually imports everything and things show in the library.
3. I started importing by about 30-50 at a time, then even down to about 10 at a time, as I was curious if it was related to HTTP request sizes or similar (too large of a body, etc). When doing this, sometimes the requests would just hang for really long periods of time... e.g. importing 10 movies taking over 20 minutes, before I refreshed the page. I've tried restarting the container with no success. Nothing in the logs/tasks seem to show any issues or errors, it just shows it successfully completed importing one of the movies, and doesn't show the rest of the movies that have still yet to be imported into the list.

Unfortunately, no logs at the moment, as I wiped all logs in attempting to get things imported. I've just about completed the import at this point, despite all of the issues.

**Comment by lrstanley** [comment]
Logs from situation #2:
```
Request Failed. POST /api/v3/movie/import: An error occurred while sending the request. The response ended prematurely.: 'https://radarrapi.servarr.com/v1/movie/641790'
```

```
System.Net.WebException: An error occurred while sending the request. The response ended prematurely.: 'https://radarrapi.servarr.com/v1/movie/641790'
 ---> System.Net.WebException: An error occurred while sending the request. The response ended prematurely.
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 146
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 146
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 123
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 57
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 246
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieInfo(Int32 tmdbId) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 88
   at NzbDrone.Core.Movies.AddMovieService.AddSkyhookData(Movie newMovie) in D:\a\1\s\src\NzbDrone.Core\Movies\AddMovieService.cs:line 97
   at NzbDrone.Core.Movies.AddMovieService.AddMovies(List`1 newMovies, Boolean ignoreErrors) in D:\a\1\s\src\NzbDrone.Core\Movies\AddMovieService.cs:line 67
   at Radarr.Api.V3.Movies.MovieImportModule.Import() in D:\a\1\s\src\Radarr.Api.V3\Movies\MovieImportModule.cs:line 25
   at Radarr.Api.V3.Movies.MovieImportModule.<.ctor>b__1_0(Object x) in D:\a\1\s\src\Radarr.Api.V3\Movies\MovieImportModule.cs:line 17
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
```

Could be due to my network, but intermittent failures aren't common. Guessing it has something to do with ratelimiting given I'm probably slamming the API due to the amount of movies. Regardless, I'd assume these types of requests should retry/delay, at least a few times, esp for those with large imports like I have. Seems very inefficient to make thousands of requests and fail because of 1 (and have to start over).

**Comment by KaiAKoenig** [comment]
Update to the original problem: what I assumed from the beginning turned out to be true, the origin lay somewhere in my QNAP. Because after an update of the QNAP OS the issues are gone. I do not know what was fixed and what the original problem in the OS was that caused this strange Radarr behavior. Still the issue remains, that Radarr  behaved very strange and did not give any hint of a problem in the logs, so that should still be looked at.

**Comment by planetrocky** [comment]
My Radarr has also stalled on Library Import.  The web UI does nothing, nothing logged at the Debug level at all.

Version 4.2.4.6635
Package Version 4.2.4.6635-ls153 by [linuxserver.io](https://linuxserver.io/)
.NET Yes (6.0.8)
Docker Yes
DB Migration 214
Database Sqlite 3.36.0
