### ISSUE TITLE
Movie Editor PUT Issue (Renaming Fails)

### ISSUE THREAD

**Issue by l3uddz** [Radarr/Radarr#5966]
**Describe the bug**

Using the movie editor PUT API so that radarr moves an existing movie to a new folder path (e.g. year has changed) I am seeing the following debug logs:

```
2021-2-25 09:46:43.8|Debug|DiskTransferService|Rename Directory [/mnt/unionfs/Media/Movies/The Very Excellent Mr. Dundee (2021) - [imdb:tt8560172] [tmdb:604768]] > [/mnt/unionfs/Media/Movies/The Very Excellent Mr. Dundee (2020) - [imdb:tt8560172] [tmdb:604768]]
2021-2-25 09:46:43.8|Error|MoveMovieService|Unable to move movie from '/mnt/unionfs/Media/Movies/The Very Excellent Mr. Dundee (2021) - [imdb:tt8560172] [tmdb:604768]' to '/mnt/unionfs/Media/Movies/The Very Excellent Mr. Dundee (2020) - [imdb:tt8560172] [tmdb:604768]'. Try moving files manually

[v3.1.0.4641] System.IO.IOException: The file '/mnt/unionfs/Media/Movies/The Very Excellent Mr. Dundee (2021) - [imdb:tt8560172] [tmdb:604768]' already exists.
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFolder(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 262
   at NzbDrone.Common.Disk.DiskTransferService.TransferFolder(String sourcePath, String targetPath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 88
   at NzbDrone.Core.Movies.MoveMovieService.MoveSingleMovie(Movie movie, String sourcePath, String destinationPath, Nullable`1 index, Nullable`1 total) in D:\a\1\s\src\NzbDrone.Core\Movies\MoveMovieService.cs:line 57
```

```
2021-2-25 09:38:26.1|Info|MoveMovieService|Moving Skylines from '/mnt/unionfs/Media/Movies/Skylines (2021) - [imdb:tt9387250] [tmdb:560144]' to '/mnt/unionfs/Media/Movies/Skylines (2020) - [imdb:tt9387250] [tmdb:560144]' (7/10)
2021-2-25 09:38:26.1|Debug|DiskTransferService|Move Directory [/mnt/unionfs/Media/Movies/Skylines (2021) - [imdb:tt9387250] [tmdb:560144]] > [/mnt/unionfs/Media/Movies/Skylines (2020) - [imdb:tt9387250] [tmdb:560144]]
2021-2-25 09:38:26.1|Debug|DiskTransferService|Rename Directory [/mnt/unionfs/Media/Movies/Skylines (2021) - [imdb:tt9387250] [tmdb:560144]] > [/mnt/unionfs/Media/Movies/Skylines (2020) - [imdb:tt9387250] [tmdb:560144]]
2021-2-25 09:38:26.1|Error|MoveMovieService|Unable to move movie from '/mnt/unionfs/Media/Movies/Skylines (2021) - [imdb:tt9387250] [tmdb:560144]' to '/mnt/unionfs/Media/Movies/Skylines (2020) - [imdb:tt9387250] [tmdb:560144]'. Try moving files manually

[v3.1.0.4641] System.IO.IOException: The file '/mnt/unionfs/Media/Movies/Skylines (2021) - [imdb:tt9387250] [tmdb:560144]' already exists.
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFolder(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 262
   at NzbDrone.Common.Disk.DiskTransferService.TransferFolder(String sourcePath, String targetPath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 88
   at NzbDrone.Core.Movies.MoveMovieService.MoveSingleMovie(Movie movie, String sourcePath, String destinationPath, Nullable`1 index, Nullable`1 total) in D:\a\1\s\src\NzbDrone.Core\Movies\MoveMovieService.cs:line 57
```

If I ls -lah on the disk:

```
➜  nabarr docker exec -it radarr ls /mnt/unionfs/Media/Movies | grep Dundee
'The Very Excellent Mr. Dundee (2021) - [imdb:tt8560172] [tmdb:604768]'
➜  nabarr docker exec -it radarr ls /mnt/unionfs/Media/Movies | grep Skylines
'Skylines (2021) - [imdb:tt9387250] [tmdb:560144]'
```

**To Reproduce**

I am unsure exactly how to reproduce as it seems to be inconsistent, it works for most cases, however, seems to occur for some movies.

**Expected behavior**

The movie folder should be renamed as the folder does not already exist.

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: Yes
 - Mono or .NET Version (System -> Status): NET 5.0.3
 - Radarr Version: 3.1.0.4641
 - Radarr Branch: nightly-9b56e2b

**Trace Logs**

https://pastebin.com/H6Kek79h

[AB#634](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/634)

**Comment by bakerboy448** [comment]
Is this still an issue in v4.1  or v4.2

**Comment by bakerboy448** [comment]
@l3uddz bump on this.  No other reports, and the paths all appear to align?
