### ISSUE TITLE
"The given key '1' was not present in the dictionary."

### ISSUE THREAD

**Issue by Freeben666** [Radarr/Radarr#6050]
**Describe the bug**
I created a Custom format, never used it anywhere, and just deleted it. Now I get this error everywhere : "The given key '1' was not present in the dictionary."

**To Reproduce**
1. Create a custom format
2. Delete it

**Screenshots**
Only thing the WebUI show now:
![image](https://user-images.githubusercontent.com/25664142/111033655-96403480-8412-11eb-88ad-d3a262aaa2d1.png)

**Platform Information (please complete the following information):**
 - OS: Asustor NAS (linux x86_64 4.14.0.x)
 - Docker: Yes (Docker 19.03.8)
 - Mono or .NET Version (System -> Status): Unknown
 - Browser and Version (Only needed for UI issues): Firefox 86.0
 - Radarr Version: 3.0.2.4552
 - Radarr Branch: linuxserver/radarr:latest

**Trace Logs**
Here's what I get in the logs after restarting the docker container
[radarr.log](https://github.com/Radarr/Radarr/files/6134969/radarr.log)

**Comment by Freeben666** [comment]
I restored a radarr.db and config.xml from a backup from a couple days ago, and all is fine now. I kept the corrupt DB if needed.

**Comment by Qstick** [comment]
I can't manage to reproduce this in 3.1 branch, can you hop on discord and DM me or @ta264 the DB

**Comment by dooooood** [comment]
What was the resolution to this issue? I am having the exact same problem. Created a custom format, deleted it, and then got this message. I'm on Windows 10 (no docker). I tried restoring radarr.db and config.xml from a backup, but it didn't work (got the same message again). I can provide more info, if necessary.

**Comment by biship** [comment]
Same steps, same result:

'
2021-09-07 15:26:29.6|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/movie

[v4.0.0.5241] System.Collections.Generic.KeyNotFoundException: The given key '75' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NzbDrone.Core.Profiles.ProfileRepository.Query(SqlBuilder builder) in D:\a\1\s\src\NzbDrone.Core\Profiles\ProfileRepository.cs:line 35
   at NzbDrone.Core.Movies.MovieRepository.All()
   at NzbDrone.Core.Movies.MovieService.GetAllMovies() in D:\a\1\s\src\NzbDrone.Core\Movies\MovieService.cs:line 233
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Radarr.Api.V3.Movies.MovieModule.AllMovie() in D:\a\1\s\src\Radarr.Api.V3\Movies\MovieModule.cs:line 140
   at Radarr.Http.REST.RestModule`1.<set_GetResourceAll>b__34_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 153
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)'

**Comment by bakerboy448** [comment]
@biship again this was not reproducible

> hop on discord and DM @Qstick or @ta264 the DB

**Comment by ta264** [comment]
To be honest a broken database isn't super useful, someone needs to figure out what steps cause a good database to become broken.

**Comment by casperse** [comment]
I just experienced the same issue - There where two users accessing Radarr on two different browsers
One deleted a custom formats "Stereo 1.0"  while user 2 have the Edit Quality Profile open and press save
That resulted in the below error and no UI
![image](https://user-images.githubusercontent.com/2026859/140644978-3da3c1e7-6236-4b5c-bd0a-3b31254296a8.png)

**Comment by casperse** [comment]
Restoring DB form Radarr I get  database disk image is malformed database disk image is malformed

**Comment by bakerboy448** [comment]
> Restoring DB form Radarr I get database disk image is malformed database disk image is malformed

Officially covered on the FAQ and a support issue.

So it sounds like this is reproducible if and only if a user is editing a profile and simultaneously a custom format is deleted at which point the profile is saved which then causes conflicts and the missing key error?

**Comment by casperse** [comment]
Yes that is correct! editing a profile while another have deleted a custom format (That would be in that profile) will give first the given key is not present and after a malformed database error (I had to fix the SQL backup to get it up and running again)

**Comment by mrvaghani** [comment]
> Yes that is correct! editing a profile while another have deleted a custom format (That would be in that profile) will give first the given key is not present and after a malformed database error (I had to fix the SQL backup to get it up and running again)

I seem to have a similar issue. Any chance you can give some high level steps on what you did to "fix the SQL backup" to get it up and running again?
