### ISSUE TITLE
nn caps - gracefully handle when sites dont have the info you seek

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#609]
note not that all newznab providers use caps or have everything shown.. several remove stuff from this page to leak things

```
17-2-5 10:32:12.2|Debug|NewznabCapabilitiesProvider|Failed to get capabilities from https://api.dognzb.cr: Object reference not set to an instance of an object.

[v0.2.0.285] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.ParseCapabilities(HttpResponse response) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 68
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 56
```

**Comment by galli-leo** [comment]
Maybe ask them to enable this endpoint? Sonarr also did not work without that.

**Comment by onedr0p** [comment]
Dogs API had been shit for the past year, it could also be that it cannot connect..

**Comment by thezoggy** [comment]
dognzb works fine, its just when radarr even right before/after it throws "Failed to get capabilities", so it would appear it is just those requests that radarr is doing isnt handling it well..

**Comment by galli-leo** [comment]
We get the capabilities the same way Sonarr does it. So the problem is that your indexer does not have movie search enabled.
