### ISSUE TITLE
Can't add new notification : sqlite error Notifications has no column named OnDelete

### ISSUE THREAD

**Issue by Hakujou** [Radarr/Radarr#6146]
**Describe the bug**
When trying to add a new Connection with a PMS server, the following error occurs:

```2021-4-5 14:42:19.7|Error|RadarrErrorPipeline|[POST /api/v3/notification]

[v3.0.2.4552] code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
table Notifications has no column named OnDelete
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1060
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1043
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 996
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 180
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 143
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.Create(TProviderDefinition definition) in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderFactory.cs:line 101
   at Radarr.Api.V3.ProviderModuleBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Radarr.Api.V3\ProviderModuleBase.cs:line 80
   at Radarr.Http.REST.RestModule`1.<set_CreateResource>b__43_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 206
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
```

**To Reproduce**
Settings -> Connect
Add a new PMS Server, and click "Save".
Editing an existing one causes the same issue.

**Expected behavior**
Save should work without an error.

**Platform Information (please complete the following information):**
 - OS: Debian 10
 - Docker: Yes
 - Mono or .NET Version (System -> Status): .Net Core 3.1.10
 - Radarr Version: 3.0.2.4552
 - Radarr Branch: master

**Trace Logs**
https://pastebin.com/d6Jj94p4

**Comment by ta264** [comment]
Did you downgrade from nightly to latest / master?

**Comment by Hakujou** [comment]
I switched from nightly to latest, yes. If I remember correctly there was a warning on nightly branch (I use LSIO container).

**Comment by RobinDadswell** [comment]
That's currently unsupported - please change back to nightly.
