### ISSUE TITLE
Unable to View Tags in Settings

### ISSUE THREAD

**Issue by JagandeepBrar** [Radarr/Radarr#6192]
**Describe the bug**
After adding a new tag to Radarr (by typing in the new tag name into the movie's edit dialog), I am no longer able to view all the tags by going to Settings -> Tags.

Some additional context:
- Using this new tag is possible, and can be added to movies
- When adding tags and partially typing the tag name, it will still appear
- Using HTTP DELETE on `api/v3/tag/{id}` will cause the same error 500
- Using HTTP GET on `api/v3/tag` to fetch the list of all tags returns successfully, where I can see this newly added tag's label and ID
- Updating to nightly builds (v3.1.0.x) had no effect

**To Reproduce**
1. Add a new tag to a movie
2. Save the movie
3. Go to Settings -> Tags
4. You will get an "Unable to load tags" message

**Expected behavior**
Be able to view tags and remove stale tags.

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: Yes
 - Mono or .NET Version (System -> Status): .NET Core (3.1.10)
 - Radarr Version: 3.0.2.4552
 - Radarr Branch: master

**Trace Logs**

```
2021-4-17 07:42:16.5|Trace|Http|Req: 725 [GET] /api/v3/tag/detail (from ::ffff:172.20.0.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15)
2021-4-17 07:42:16.5|Trace|RadarrErrorPipeline|Handling Exception
2021-4-17 07:42:16.5|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/tag/detail

[v3.0.2.4552] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Tags.TagService.<>c__DisplayClass12_0.<Details>b__8(KeyValuePair`2 c) in D:\a\1\s\src\NzbDrone.Core\Tags\TagService.cs:line 117
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at NzbDrone.Core.Tags.TagService.Details() in D:\a\1\s\src\NzbDrone.Core\Tags\TagService.cs:line 109
   at Radarr.Api.V3.Tags.TagDetailsModule.GetAll() in D:\a\1\s\src\Radarr.Api.V3\Tags\TagDetailsModule.cs:line 27
   at Radarr.Http.REST.RestModule`1.<set_GetResourceAll>b__34_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 153
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)


2021-4-17 07:42:16.5|Trace|Http|Res: 725 [GET] /api/v3/tag/detail: 500.InternalServerError (32 ms)
2021-4-17 07:42:16.5|Debug|Api|[GET] /api/v3/tag/detail: 500.InternalServerError (32 ms)
```

**Comment by Qstick** [comment]
What’s the name of the tag you are adding? do you currently have any other tags? I’m unable to reproduce this in nightly by simply adding a tag and going settings.

**Comment by JagandeepBrar** [comment]
> What’s the name of the tag you are adding? do you currently have any other tags? I’m unable to reproduce this in nightly by simply adding a tag and going settings.

Any text will cause this error. Some examples tested: asdf, test, lunasea, etc.

**Comment by JagandeepBrar** [comment]
After setting up a separate Docker instance, it appears this was likely caused from some kind of database corruption. After re-importing my entire library in a new instance and doing tests with tags (on both stable and nightly), the error does not occur anymore.

**Comment by Qstick** [comment]
Interesting. Thanks for the followup.
