### ISSUE TITLE
Race condition on upgrading

### ISSUE THREAD

**Issue by TheRealShiz** [Radarr/Radarr#621]
I had a movie in DVD quality.  Radarr queued up an upgrade to 1080p, then while that was still downloading, it queued up another "upgrade" to 720p.  So it replaced the DVD with the 1080p, then replaced the 1080p with the 720p.

**Comment by testarea1** [comment]
I've seen this when the 1080p was a Web-DL or Webrip and the 720p is the Bluray quality (bluray is the higher quality in this case). Was that the case in this?

**Comment by TheRealShiz** [comment]
No both the 720 and 1080 were Bluray.

**Comment by onedr0p** [comment]
Can you post a screen shot of you profile you used for that movie?

**Comment by TheRealShiz** [comment]
Here is the history.

![image](https://cloud.githubusercontent.com/assets/18042390/22715397/4a44a2f2-ed56-11e6-8a84-77828df23d84.png)

Here is the quality profile.

![image](https://cloud.githubusercontent.com/assets/18042390/22715435/88101fc6-ed56-11e6-9a6b-1122b950ae84.png)

**Comment by TheRealShiz** [comment]
To clarify, you can see that I went in later and forced it to download the 1080p again.

**Comment by onedr0p** [comment]
Hmm I have no idea, did the 1080p movie finish, and they the 720p movie started?

**Comment by onedr0p** [comment]
Try updating to the latest release and see report back if it happens again.

**Comment by TheRealShiz** [comment]
The 1080p was not finished downloading at the time.  It queued the 720p release behind it.  They both finished within minutes of each other with the 720p replacing the 1080p.

My guess is that since the 720p was technically an upgrade to the 480p that I had, it queued it up without checking to see if an even higher quality release had been previously queued.  In addition, when replacing the file it did not confirm that the file being replaced was actually lower quality.  If either of these two checks existed this would not have happened.

I am on the latest release and I have only seen this one time (but again it takes a special set of circumstances to reproduce).

**Comment by TheRealShiz** [comment]
Here is a screenshot from Sab.  You can see that the first two finished within 3 minutes of each other.  The last one is the one I forced to download the 1080p again.

![image](https://cloud.githubusercontent.com/assets/18042390/22715763/1ab8f518-ed58-11e6-8066-5525d1230864.png)

**Comment by onedr0p** [comment]
Keep up updated if you see it happen again, I have not seen anyone else report this issue.

**Comment by TheRealShiz** [comment]
Welp, that didn't take long.  Did it again early this morning.

Here is Sab screenshot

![image](https://cloud.githubusercontent.com/assets/18042390/22739523/98c20494-edd1-11e6-896a-e6d63e17f480.png)

Here is History from Radarr

![image](https://cloud.githubusercontent.com/assets/18042390/22739632/05b51d66-edd2-11e6-8c88-b6fc73f66d47.png)

Same quality profile as before.  Not sure why it replaced the 1080p from 12:48 with the 1080p at 2:45, then replaced that with a 720p 2 minutes later.  Then replaced that with the 1080p again at 3:50.

Good thing I don't have a bandwidth cap.

**Comment by onedr0p** [comment]
Can you post you full logs between the time 1230 and 4?

**Comment by onedr0p** [comment]
Maybe Sab is telling radarr to grab another release?

**Comment by TheRealShiz** [comment]
```
17-2-8 00:34:05.0|Info|RssSyncService|Starting RSS Sync
17-2-8 00:34:31.7|Info|DownloadDecisionMaker|Processing 200 releases
17-2-8 00:35:06.7|Info|Sabnzbd|Adding report [NAME-REMOVED.2016.1080p.BluRay.x264-GECKOS] to the queue.
17-2-8 00:35:07.9|Info|DownloadService|Report sent to Sabnzbd. NAME-REMOVED.2016.1080p.BluRay.x264-GECKOS
17-2-8 00:35:07.9|Info|RssSyncService|RSS Sync Completed. Reports found: 200, Reports grabbed: 1
17-2-8 00:49:06.6|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. D:\Media\Movies\NAME-REMOVED (2016)\NAME-REMOVED (2016) - WEBDL-1080p.mkv
17-2-8 00:49:06.7|Error|EventAggregator|MovieMissingModule failed while processing [MovieDownloadedEvent]

[v0.2.0.299] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Api.NzbDroneRestModuleWithSignalR`2.BroadcastResourceChange(ModelAction action, Int32 id) in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModuleWithSignalR.cs:line 38
   at NzbDrone.Api.Wanted.MovieMissingModule.Handle(MovieDownloadedEvent message) in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieMissingModule.cs:line 74
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

17-2-8 01:35:08.2|Info|RssSyncService|Starting RSS Sync
17-2-8 01:35:14.0|Warn|SecurityProtocolPolicy|Disabled Tls1.2 due to remote certificate error.
17-2-8 01:35:31.5|Info|DownloadDecisionMaker|Processing 300 releases
17-2-8 01:36:15.6|Info|RssSyncService|RSS Sync Completed. Reports found: 300, Reports grabbed: 0
17-2-8 02:36:40.7|Info|RssSyncService|Starting RSS Sync
17-2-8 02:36:42.3|Warn|Newznab|API Temporarily Disabled (daily maintenance) - https://api.dognzb.cr/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100

[v0.2.0.299] NzbDrone.Core.Indexers.Newznab.NewznabException: API Temporarily Disabled (daily maintenance)
   at NzbDrone.Core.Indexers.Newznab.NewznabRssParser.PreProcess(IndexerResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Newznab\NewznabRssParser.cs:line 45
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\RssParser.cs:line 50
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 297
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(IndexerPageableRequestChain pageableRequestChain, Boolean isRecent) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 154

17-2-8 02:36:45.1|Info|DownloadDecisionMaker|Processing 200 releases
17-2-8 02:37:12.1|Info|RssSyncService|RSS Sync Completed. Reports found: 200, Reports grabbed: 0
17-2-8 02:46:11.4|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. D:\Media\Movies\NAME-REMOVED (2016)\NAME-REMOVED (2016) - Bluray-1080p.mkv
17-2-8 02:46:11.4|Error|EventAggregator|MovieMissingModule failed while processing [MovieDownloadedEvent]

[v0.2.0.299] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Api.NzbDroneRestModuleWithSignalR`2.BroadcastResourceChange(ModelAction action, Int32 id) in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModuleWithSignalR.cs:line 38
   at NzbDrone.Api.Wanted.MovieMissingModule.Handle(MovieDownloadedEvent message) in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieMissingModule.cs:line 74
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

17-2-8 02:48:11.6|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. D:\Media\Movies\NAME-REMOVED (2016)\NAME-REMOVED (2016) - Bluray-1080p.mkv
17-2-8 02:48:11.8|Error|EventAggregator|MovieMissingModule failed while processing [MovieDownloadedEvent]

[v0.2.0.299] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Api.NzbDroneRestModuleWithSignalR`2.BroadcastResourceChange(ModelAction action, Int32 id) in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModuleWithSignalR.cs:line 38
   at NzbDrone.Api.Wanted.MovieMissingModule.Handle(MovieDownloadedEvent message) in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieMissingModule.cs:line 74
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

17-2-8 03:37:13.4|Info|RssSyncService|Starting RSS Sync
17-2-8 03:37:36.4|Info|DownloadDecisionMaker|Processing 300 releases
17-2-8 03:38:15.4|Info|Sabnzbd|Adding report [NAME-REMOVED.2016.1080p.BluRay.x264-GECKOS] to the queue.
17-2-8 03:38:16.4|Info|DownloadService|Report sent to Sabnzbd. NAME-REMOVED.2016.1080p.BluRay.x264-GECKOS
17-2-8 03:38:16.4|Info|RssSyncService|RSS Sync Completed. Reports found: 300, Reports grabbed: 1
17-2-8 03:51:15.2|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. D:\Media\Movies\NAME-REMOVED (2016)\NAME-REMOVED (2016) - Bluray-720p.mkv
17-2-8 03:51:15.3|Error|EventAggregator|MovieMissingModule failed while processing [MovieDownloadedEvent]

[v0.2.0.299] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Api.NzbDroneRestModuleWithSignalR`2.BroadcastResourceChange(ModelAction action, Int32 id) in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModuleWithSignalR.cs:line 38
   at NzbDrone.Api.Wanted.MovieMissingModule.Handle(MovieDownloadedEvent message) in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieMissingModule.cs:line 74
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56


```

**Comment by onedr0p** [comment]
Please post the trace log in that time frame so we can investigate further.

**Comment by TheRealShiz** [comment]
I don't have trace logging turned on.  I will enable it and hope it happens again.

**Comment by TheRealShiz** [comment]
I have not seen this happen again.  I suggest closing.
