### ISSUE TITLE
Unable to import movie by using api/command DownloadedMoviesScan

### ISSUE THREAD

**Issue by Rouzax** [Radarr/Radarr#6275]
**Describe the bug**

I've always imported movies by calling the Radarr API

POST `http://download.home.lan:7878/api/command`
```
{
  "name": "DownloadedMoviesScan",
  "importMode": "Move",
  "path": "C:\\TEMP\\Torrent\\PROCD\\Movie\\The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR",
  "downloadClientId": "B4E7E0F6EEBA1710857CBFF0F3F644E8472F6DE2"
}
```

The API job will post this back
```
{
  "name": "DownloadedMoviesScan",
  "message": "Failed",
  "body": {
    "sendUpdatesToClient": false,
    "sendUpdates": false,
    "path": "C:\\TEMP\\Torrent\\PROCD\\Movie\\The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR",
    "downloadClientId": "B4E7E0F6EEBA1710857CBFF0F3F644E8472F6DE2",
    "importMode": "move",
    "updateScheduledTask": true,
    "completionMessage": "Completed",
    "requiresDiskAccess": false,
    "isExclusive": false,
    "isTypeExclusive": false,
    "name": "DownloadedMoviesScan",
    "trigger": "manual",
    "suppressMessages": false
  },
  "priority": "normal",
  "status": "failed",
  "queued": "2021-05-06T17:49:38Z",
  "started": "2021-05-06T17:49:38Z",
  "ended": "2021-05-06T17:49:39Z",
  "duration": "00:00:00.4043587",
  "exception": "System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at NzbDrone.Core.Download.CompletedDownloadService.VerifyImport(TrackedDownload trackedDownload, List`1 importResults) in D:\\a\\1\\s\\src\\NzbDrone.Core\\Download\\CompletedDownloadService.cs:line 183\r\n   at NzbDrone.Core.MediaFiles.DownloadedMovieCommandService.ProcessPath(DownloadedMoviesScanCommand message) in D:\\a\\1\\s\\src\\NzbDrone.Core\\MediaFiles\\DownloadedMovieCommandService.cs:line 55\r\n   at NzbDrone.Core.MediaFiles.DownloadedMovieCommandService.Execute(DownloadedMoviesScanCommand message) in D:\\a\\1\\s\\src\\NzbDrone.Core\\MediaFiles\\DownloadedMovieCommandService.cs:line 72\r\n   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\\a\\1\\s\\src\\NzbDrone.Core\\Messaging\\Commands\\CommandExecutor.cs:line 86",
  "trigger": "manual",
  "state": "failed",
  "manual": true,
  "startedOn": "2021-05-06T17:49:38Z",
  "stateChangeTime": "2021-05-06T17:49:38Z",
  "sendUpdatesToClient": false,
  "updateScheduledTask": true,
  "id": 2662877
}

```

This always worked but with the latest update it doesn't work any more and I see errors in the log

**Platform Information (please complete the following information):**
 - OS: Windows 2019
 - Docker: No
 - Mono or .NET Version (System -> Status): 5.0.5
 - Browser and Version (Only needed for UI issues): 
 - Radarr Version: 3.1.1.4954

**Trace Logs**
```
2021-05-06 19:49:38.8|Debug|Api|[POST] /api/command: 201.Created (5 ms)
2021-05-06 19:49:38.9|Debug|DownloadedMovieCommandService|External directory scan request for known download B4E7E0F6EEBA1710857CBFF0F3F644E8472F6DE2. [C:\TEMP\Torrent\PROCD\Movie\The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR]
2021-05-06 19:49:38.9|Debug|DownloadedMovieImportService|Processing path: C:\TEMP\Torrent\PROCD\Movie\The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR
2021-05-06 19:49:38.9|Debug|Parser|Parsing string 'The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR'
2021-05-06 19:49:38.9|Debug|Parser|Movie Parsed. The Courier - 2020 
2021-05-06 19:49:38.9|Debug|Parser|Release Group parsed: RUMOUR
2021-05-06 19:49:38.9|Debug|Parser|Languages parsed: Unknown
2021-05-06 19:49:38.9|Debug|QualityParser|Trying to parse quality for The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR
2021-05-06 19:49:38.9|Debug|Parser|Quality parsed: WEBDL-2160p v1
2021-05-06 19:49:38.9|Debug|Parser|Edition parsed: 
2021-05-06 19:49:38.9|Debug|DownloadedMovieImportService|The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR folder quality: WEBDL-2160p v1
2021-05-06 19:49:38.9|Debug|DiskScanService|Scanning 'C:\TEMP\Torrent\PROCD\Movie\The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR' for video files
2021-05-06 19:49:38.9|Debug|DiskScanService|1 video files were found in C:\TEMP\Torrent\PROCD\Movie\The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR
2021-05-06 19:49:38.9|Debug|ImportDecisionMaker|Analyzing 1/1 files.
2021-05-06 19:49:38.9|Debug|Parser|Parsing string 'The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR'
2021-05-06 19:49:39.0|Debug|Parser|Movie Parsed. The Courier - 2020 
2021-05-06 19:49:39.0|Debug|Parser|Release Group parsed: RUMOUR
2021-05-06 19:49:39.0|Debug|Parser|Languages parsed: Unknown
2021-05-06 19:49:39.0|Debug|QualityParser|Trying to parse quality for The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR
2021-05-06 19:49:39.0|Debug|Parser|Quality parsed: WEBDL-2160p v1
2021-05-06 19:49:39.0|Debug|Parser|Edition parsed: 
2021-05-06 19:49:39.0|Debug|VideoFileInfoReader|Getting media info from C:\TEMP\Torrent\PROCD\Movie\The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR\The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR.mkv
2021-05-06 19:49:39.0|Debug|DetectSample|Runtime of 6720,16 is more than 600 seconds, Not Sample
2021-05-06 19:49:39.0|Debug|Parser|Parsing string 'The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR.mkv'
2021-05-06 19:49:39.1|Debug|Parser|Movie Parsed. The Courier - 2020 
2021-05-06 19:49:39.1|Debug|Parser|Release Group parsed: RUMOUR
2021-05-06 19:49:39.1|Debug|Parser|Languages parsed: Unknown
2021-05-06 19:49:39.1|Debug|QualityParser|Trying to parse quality for The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR.mkv
2021-05-06 19:49:39.1|Debug|Parser|Quality parsed: WEBDL-2160p v1
2021-05-06 19:49:39.1|Debug|Parser|Edition parsed: 
2021-05-06 19:49:39.1|Debug|VideoFileInfoReader|Getting media info from C:\TEMP\Torrent\PROCD\Movie\The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR\The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR.mkv
2021-05-06 19:49:39.1|Debug|AggregateLanguage|Selected languages: English
2021-05-06 19:49:39.1|Debug|QualityParser|Trying to parse quality for The Courier 2020 HDR 2160p WEB h265-RUMOUR
2021-05-06 19:49:39.1|Debug|AggregateQuality|Using quality: WEBDL-2160p v1
2021-05-06 19:49:39.2|Debug|AlreadyImportedSpecification|Movie file previously imported at 4-5-2021 09:04:21
2021-05-06 19:49:39.2|Debug|VideoFileInfoReader|Getting media info from C:\TEMP\Torrent\PROCD\Movie\The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR\The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR.mkv
2021-05-06 19:49:39.2|Debug|DetectSample|Runtime of 6720,16 is more than 600 seconds, Not Sample
2021-05-06 19:49:39.2|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Movie file already imported at 4-5-2021 09:04:21
2021-05-06 19:49:39.2|Debug|ImportApprovedMovie|Decisions: 1
2021-05-06 19:49:39.3|Debug|Api|[GET] /api/v3/command: 200.OK (26 ms)
2021-05-06 19:49:39.3|Error|CommandExecutor|Error occurred while executing task DownloadedMoviesScan

[v3.1.1.4954] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Download.CompletedDownloadService.VerifyImport(TrackedDownload trackedDownload, List`1 importResults) in D:\a\1\s\src\NzbDrone.Core\Download\CompletedDownloadService.cs:line 183
   at NzbDrone.Core.MediaFiles.DownloadedMovieCommandService.ProcessPath(DownloadedMoviesScanCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DownloadedMovieCommandService.cs:line 55
   at NzbDrone.Core.MediaFiles.DownloadedMovieCommandService.Execute(DownloadedMoviesScanCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DownloadedMovieCommandService.cs:line 72
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 86
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44
```

**Comment by bakerboy448** [comment]
1) Why do you always need to import via the API that should be very rarely needed as the whole point of radarr is for it to automatically occur?  If it isn't ten that is something to troubleshoot.

2) someone with a bit better API knowledge will come by, but my guess is it is related to the fact the file was already imported possibly?  `2021-05-06 19:49:39.2|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Movie file already imported at 4-5-2021 09:04:21`

3) the old API will be eventually phased out; switch to the v3 one
https://radarr.video/docs/api/

**Comment by Rouzax** [comment]
It says that because the original import also failed with the same issue
I want to import after a download because I do some stuff before the import 😄 
See: https://github.com/Rouzax/TorrentScript

I'll give the APiv3 a test.

**Comment by Rouzax** [comment]
API v3 does seem to do a bit more but has a different result
Doing a POST `http://download.home.lan:7878/api/v3/command`
```
{
  "name": "DownloadedMoviesScan",
  "importMode": "Copy",
  "path": "C:\\TEMP\\Torrent\\PROCD\\Movie\\The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR",
  "downloadClientId": "B4E7E0F6EEBA1710857CBFF0F3F644E8472F6DE2"
}
```

The job that starts is directly completed while in the backend it is still processing.
```
{
    "name": "DownloadedMoviesScan",
    "commandName": "Downloaded Movies Scan",
    "message": "Completed",
    "body": {
        "sendUpdatesToClient": false,
        "sendUpdates": false,
        "path": "C:\\TEMP\\Torrent\\PROCD\\Movie\\The.Courier.2020.HDR.2160p.WEB.h265-RUMOUR",
        "downloadClientId": "B4E7E0F6EEBA1710857CBFF0F3F644E8472F6DE2",
        "importMode": "copy",
        "updateScheduledTask": true,
        "completionMessage": "Completed",
        "requiresDiskAccess": false,
        "isExclusive": false,
        "isTypeExclusive": false,
        "name": "DownloadedMoviesScan",
        "trigger": "manual",
        "suppressMessages": true
    },
    "priority": "normal",
    "status": "completed",
    "queued": "2021-05-06T18:19:52Z",
    "started": "2021-05-06T18:19:52Z",
    "ended": "2021-05-06T18:20:21Z",
    "duration": "00:00:29.4801576",
    "trigger": "manual",
    "stateChangeTime": "2021-05-06T18:19:52Z",
    "sendUpdatesToClient": false,
    "updateScheduledTask": true,
    "id": 2662915
}
```
Inside Radarr the movie is still missing, while it did import it on the filesystem
![image](https://user-images.githubusercontent.com/4103090/117347174-087c4500-aea9-11eb-965f-6288b4377c47.png)
![image](https://user-images.githubusercontent.com/4103090/117347236-22b62300-aea9-11eb-9ad1-9be1edc9f93f.png)

**Comment by Rouzax** [comment]
Think I found the issue 😄 
`The Courier` is in the DB from the year 2019 and 2020
![image](https://user-images.githubusercontent.com/4103090/117350169-8726b180-aeac-11eb-9bd7-015353d0affa.png)

**Comment by wthueb** [comment]
Does anyone have a reference for the command endpoint on the v3 API? Can't seem to find anything about it in the docs.

**Comment by bakerboy448** [comment]
Not sure what docs you were trying....

api docs are linked in the readme, on the site call and on the wiki

**Comment by wthueb** [comment]
Scrolled right past it after looking over the docs twice to find it. Apologies, thank you.
