### ISSUE TITLE
Duplicate MovieTranslations-MovieId

### ISSUE THREAD

**Issue by IInvocation** [Radarr/Radarr#6340]
**Describe the bug**
Instead of showing the default content - i get the message "An item with the same key has already been added. Key: {somekey}"
Something (and i'm not sure when and why) is adding duplicate entries into the table "MovieTranslations", since the problem is solvable by manually issued the sql "DELETE FROM MovieTranslations WHERE MovieId = {somekey};"
(Found this checking the logs, see https://pastebin.com/vvJz0KCR / checking the sourcecode)

Sadly - i'm unable to find the place or time when this issue is actually getting caused - making things difficult to reproduce - i'm not even doing anything manually causing this - only using Ombi and automated list imports.

However - i guess someone that knows the source could easily add some kind of check to prevent entering duplicate keys.

**To Reproduce**
-> I can't actively reproduce the issue.

**Expected behavior**
Radarr should be able to not insert duplicate keys into tables.

**Screenshots**
-> not applicable

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: Yes / linuxserver.io
 - Mono or .NET Version (System -> Status): .NET 5.0.5
 - Radarr Version: 3.2.0.5048
 - Radarr Branch: master

**Trace Logs**
I beg your forgiveness - but i don't think this would help, since the time-difference between the actual problem getting caused (inserting the duplicate key) and me finally finding out there's a problem should make things more complicated. If that's not the case i'd potentially have to wait a week for this thinking about the first time this happened. (this is my second time experiencing this)

As for additional info: The related movie is "Peter Hook & The Light: So This Is Permanent" (in case the source of the translation could be the problem)

**Comment by bakerboy448** [comment]
[Xpost from Reddit](https://www.reddit.com/r/radarr/comments/ngworp/bug_i_should_to_github/?utm_source=share&utm_medium=ios_app&utm_name=iossmf)

**Comment by IInvocation** [comment]
After reviewing the standard logs i'm a little baffled as i'm seeing a couple errors for different films that look like the following:
`2021-05-17 15:18:25.5|Error|RefreshMovieService|Couldn't refresh info for [Hot Fuzz (2007)][tt0425112, 4638]`
```
[v3.1.1.4954] code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
UNIQUE constraint failed: MovieTranslations.MovieId, MovieTranslations.Language
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1064
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1047
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1000
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 180
   at NzbDrone.Core.Datastore.BasicRepository`1.InsertMany(IList`1 models) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 196
   at NzbDrone.Core.Movies.Translations.MovieTranslationService.UpdateTranslations(List`1 translations, Movie movie)
   at NzbDrone.Core.Movies.RefreshMovieService.RefreshMovieInfo(Int32 movieId) in D:\a\1\s\src\NzbDrone.Core\Movies\RefreshMovieService.cs:line 142
   at NzbDrone.Core.Movies.RefreshMovieService.Execute(RefreshMovieCommand message) in D:\a\1\s\src\NzbDrone.Core\Movies\RefreshMovieService.cs:line 224
```
Considerung the constraint of a unique(MovieTranslations.MovieId, MovieTranslations.Language) as well as the code throwing the exception:       
```
var translations = _movieTranslationService.GetAllTranslationsForLanguage(configLanguage);
var tdict = translations.ToDictionary(x => x.MovieId);
```
The exception should not even be possible :/

**Comment by abyssalsmoke** [comment]
im having a seemingly similar issue 

<img width="931" alt="image" src="https://user-images.githubusercontent.com/40474693/205736060-77b25f0e-2b05-4e4f-b46d-4f512b9d543f.png">

**Comment by bakerboy448** [comment]
@abyssalsmoke 
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.  That's not the issue noted here. a null value is not a duplicate.

**Comment by nitantsoni** [comment]
I just had this same issue occur. My DB was fine, but Radarr had this error in the trace log

```
2024-09-23 14:44:49.5|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/movie

[v5.10.4.9218] System.ArgumentException: An item with the same key has already been added. Key: 620
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](List`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at Radarr.Api.V3.Movies.MovieController.AllMovie(Nullable`1 tmdbId, Boolean excludeLocalCovers, Nullable`1 languageId) in ./Radarr.Api.V3/Movies/MovieController.cs:line 144
   at lambda_method21(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/BufferingMiddleware.cs:line 27
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/IfModifiedMiddleware.cs:line 40
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/CacheHeaderMiddleware.cs:line 32
   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/StartingUpMiddleware.cs:line 37
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/UrlBaseMiddleware.cs:line 26
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

Ran the `.recover` command on my DB, but that did not work. It would still give me this same error. 

To fix it, here is what I did 

- Backup radarr.db
- Open radarr.db using sqlite - `sqlite3 radarr.db`
- Truncate the `MovieTranslations` table, by running `DELETE from MovieTranslations`
- and that should be it!  

FWIW sqlite3 was able to open the database and when I checked the `MovieTranslations` table, there was nothing with the ID as 620. I am not sure what was going on, but truncating the table fixed it

¯\\_(ツ)_/¯

**Comment by nitantsoni** [comment]
> Hey [@nitantsoni](https://github.com/nitantsoni)! 620 is not from the `Id` column, but actually `MovieMetadataId`.
> 
> Maybe this query to see all duplicated rows for a MovieMetadataId and Language would make it easier to understand.
> 
> SELECT *
> FROM "MovieTranslations"
> GROUP BY "MovieMetadataId", "Language"
> HAVING COUNT("Id") > 1

I ran that query on my current working DB and it returns a blank result.

I didn't really look into what was going on, when troubleshooting. Have no need for translations anyway, so was more than happy to nuke that table to test if it would work. Luckily it worked in my case.

**Comment by nitantsoni** [comment]
> It returns results only when you have the `An item with the same key has already been added` issue.
> 
> The translations were repopulated on the next sync all, so that's why you don't miss them because you got them back. 👍

Lemme see, I might have a backup of the corrupt DB
