### ISSUE TITLE
NZBHydra Request Failed. POST /api/v3/release: 'doctype' is an unexpected token

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [Radarr/Radarr#6381]
**Describe the bug**

When I manually search for and add certainly newsgroup releases, I get the below error. I only have NZBHydra set up at the moment, and this doesn't happen with torrents.
**To Reproduce**

1. Run a search
2. Pick an NZB release
3. Error always happens on specific releases, sometimes it works normally/

**Expected behavior**

**Screenshots**

**Platform Information (please complete the following information):**
 - OS:  Ubuntu 20.04
 - Docker:  Yes, linuxserver/radarr
 - Mono or .NET Version (System -> Status):  .NET 5.0.5
 - Radarr Version: 3.2.2.5080
 - Radarr Branch: master

**Trace Logs**
Interesting bit, [full log attached](https://github.com/Radarr/Radarr/files/6612499/radarr.trace.txt):

```
2021-06-07 19:31:50.8|Debug|Sabnzbd|Downloaded nzb for movie 'Inglourious.Basterds.2009.4K.UHD.Remaster.2160p.HDR.By Silverok' finished (3381 bytes from https://nzbhydra.crimsonazure.com:443/getnzb/api/-6991478437195701138?apikey=(removed)
2021-06-07 19:31:50.8|Trace|RadarrErrorPipeline|Handling Exception
2021-06-07 19:31:50.8|Fatal|RadarrErrorPipeline|Request Failed. POST /api/v3/release

[v3.2.2.5080] System.Xml.XmlException: 'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 1, position 3.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(XmlReader reader)
   at NzbDrone.Core.Download.NzbValidationService.Validate(String filename, Byte[] fileContent) in D:\a\1\s\src\NzbDrone.Core\Download\NzbValidationService.cs:line 22
   at NzbDrone.Core.Download.UsenetClientBase`1.Download(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\UsenetClientBase.cs:line 79
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 73
   at Radarr.Api.V3.Indexers.ReleaseModule.DownloadRelease(ReleaseResource release) in D:\a\1\s\src\Radarr.Api.V3\Indexers\ReleaseModule.cs:line 87
   at Radarr.Api.V3.Indexers.ReleaseModule.<.ctor>b__8_2(Object x) in D:\a\1\s\src\Radarr.Api.V3\Indexers\ReleaseModule.cs:line 55
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)


2021-06-07 19:31:50.9|Trace|Http|Res: 619 [POST] /api/v3/release: 500.InternalServerError (183 ms)
2021-06-07 19:31:50.9|Debug|Api|[POST] /api/v3/release: 500.InternalServerError (183 ms)
```

[AB#560](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/560)

**Comment by bakerboy448** [comment]
I'm thinking this was more likely a bad nzb file rather than an application bug; has it occurred more or with any pattern?

**Comment by Adrian-at-CrimsonAuzre** [comment]
When I add it from NBHydra directly to SABnzbd it works fine. It seems to be pretty random when it does and doesn't work. I can attach or email an offending nzb if you'd like.

**Comment by Adrian-at-CrimsonAuzre** [comment]
Got around to doing some more tinkering, it only happens on NZBs fetched from nzbfinder.ws *through* NZBHydra. I'll be opening an issue on the NZBHydra repo as well.

**Comment by bakerboy448** [comment]
Closing for now given it seems to be a hydra caused issue; can reopen if determined it's related to Radarr.
