### ISSUE TITLE
Error processing found movie; parameter "source" cannot be null.

### ISSUE THREAD

**Issue by rschmetzer** [Radarr/Radarr#643]
Trying to download a recently created nzb.  A manual search finds the movie but the following error shows in the log when attempting a search/download:

[v0.2.0.288] System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Core.DecisionEngine.Specifications.RssSync.DelaySpecification.IsSatisfiedBy(RemoteMovie subject, SearchCriteriaBase searchCriteria) in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\Specifications\RssSync\DelaySpecification.cs:line 47
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteMovie remoteEpisode, SearchCriteriaBase searchCriteriaBase) in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 251

Selecting one of the nzb's from the manual search list will correctly send the file to SAB.

**Comment by onedr0p** [comment]
Should be fixed in next release.

**Comment by rschmetzer** [comment]
Thanks!
