### ISSUE TITLE
Radarr list sync between Radarr instances not working

### ISSUE THREAD

**Issue by BinsonBuzz** [Radarr/Radarr#6495]
Radarr List Import not working Radarr - 2 - Radarr

Importing titles from 2nd radarr docker not working
**To Reproduce**

1. Set up 2nd radarr docker settings in lists
2. Click on test or save
3. get response "unable to send test message" although intermittently it works, but then the sync task fails

**Expected behavior**
titles that match criteria added to library of 1st docker from 2nd docker

**Platform Information (please complete the following information):**
 - OS: unRAID 6.9.2
 - Docker: Yes
 - Mono or .NET Version (System -> Status): Not sure - running Linuxserver docker (linuxserver/radarr:latest)
 - Radarr Version: 3.2.2.5080
 - Radarr Branch: latest

**Trace Logs**

2021-08-01 00:16:54.4|Trace|CommandQueueManager|Getting all commands
2021-08-01 00:16:54.4|Trace|Http|Res: 309 [GET] /api/v3/command: 200.OK (3 ms)
2021-08-01 00:16:54.4|Trace|Http|Res: 308 [GET] /api/v3/queue/details: 200.OK (7 ms)
2021-08-01 00:16:54.4|Debug|Api|[GET] /api/v3/command: 200.OK (3 ms)
2021-08-01 00:16:54.4|Debug|Api|[GET] /api/v3/queue/details: 200.OK (7 ms)
2021-08-01 00:16:54.7|Trace|Scheduler|Pending Tasks: 0
2021-08-01 00:16:57.2|Error|RadarrV3Proxy|Unable to send test message

[v3.2.2.5080] System.Net.WebException: The operation has timed out.: 'http://192.168.1.1:7878/radarr/api/v3/movie'
 ---> System.Net.WebException: The operation has timed out.
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 146
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 146
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 57
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 241
   at NzbDrone.Core.ImportLists.Radarr.RadarrV3Proxy.Execute[TResource](String resource, RadarrSettings settings) in D:\a\1\s\src\NzbDrone.Core\ImportLists\Radarr\RadarrV3Proxy.cs:line 84
   at NzbDrone.Core.ImportLists.Radarr.RadarrV3Proxy.GetMovies(RadarrSettings settings) in D:\a\1\s\src\NzbDrone.Core\ImportLists\Radarr\RadarrV3Proxy.cs:line 33
   at NzbDrone.Core.ImportLists.Radarr.RadarrV3Proxy.Test(RadarrSettings settings) in D:\a\1\s\src\NzbDrone.Core\ImportLists\Radarr\RadarrV3Proxy.cs:line 50

2021-08-01 00:16:57.2|Trace|RadarrErrorPipeline|Handling Exception
2021-08-01 00:16:57.2|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to send test message
2021-08-01 00:16:57.2|Trace|Http|Res: 289 [POST] /api/v3/importlist/test: 400.BadRequest (100049 ms)
2021-08-01 00:16:57.2|Debug|Api|[POST] /api/v3/importlist/test: 400.BadRequest (100049 ms)

[AB#1306](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1306)

**Comment by austinwbest** [comment]
Pretty sure if it wasn't working, we would have a ton of complaints.

Let's start out with some basics, there is a template when making a new bug report, please fill it in and provide all the missing info.

**Comment by BinsonBuzz** [comment]
Sorry, I did filll it all in  - when I pasted the trace in I made my text hidden.

Fixed

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

> http://192.168.1.1:7878/radarr/api/v3/movie

I'm going to guess the other radarr instance is not accessible at what is a typical router IP
