### ISSUE TITLE
[BUG]: Error occurred while executing task ApplicationUpdate: Access to the path 'Radarr.Update.exe' is denied.

### ISSUE THREAD

**Issue by jaretclifton** [Radarr/Radarr#6531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempting to update from 4..0.0.5183 to 4.0.0.5206 results in an error of: Error occurred while executing task ApplicationUpdate: Access to the path 'Radarr.Update.exe' is denied.

### Expected Behavior

Update succeeds without issue

### Steps To Reproduce

1. Login
2. Click System
3. Click Updates
4. Click Install Latest
5. Check error messages

### Environment

```markdown
- OS: Windows 7
- Radarr: 4.0.0.5183
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome 92
```

### What branch are you running?

Nightly

### Anything else?

Message
Error occurred while executing task ApplicationUpdate: Access to the path 'Radarr.Update.exe' is denied.

Exception
System.UnauthorizedAccessException: Access to the path 'Radarr.Update.exe' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at NzbDrone.Common.Disk.DiskProviderBase.DeleteFolder(String path, Boolean recursive) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 289
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 115
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 283
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 86
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44

[AB#1386](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1386)

**Comment by bakerboy448** [comment]
99% sure this is a support issue and an issue on your machine

Get the updater logs and share them via gist/0bin/etc. https://wiki.servarr.com/radarr/troubleshooting#logging-and-log-files

Also Windows 7 is officially not supported as it is no longer supported by Microsoft and is EOL as of 1/2020

**Comment by austinwbest** [comment]
This won't be a Radarr bug.

**Comment by jaretclifton** [comment]
Restored a backup of the system from 3 days prior on a previous version, was able to update to the latest nightly.
