### ISSUE TITLE
Transmission  -- Username: Authentication failure Keenetic ULTRA SE

### ISSUE THREAD

**Issue by SparkYDevtk** [Radarr/Radarr#6646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Invalid request Validation failed: 
 -- Username: Authentication failure

### Expected Behavior

When trying to connect Transmission. An authorization error comes out.
Login, password, RPC, entered correctly. There are no errors in the logs from Keenetic, authorization is in progress. Transmission: 3.00 (989b6a3dc4), RPC: 16

### Environment

```markdown
- OS: Arch Linux
- Radarr:3.2.2.5080
- Kernel: Linux 5.10.70-1-lts
- Docker Install: no
- Using Reverse Proxy: no
```

### What branch are you running?

Master

### Anything else?

Invalid request Validation failed: 
 -- Username: Authentication failure
Failed to authenticate with Transmission.: Failed to authenticate with Transmission.
NzbDrone.Core.Download.Clients.DownloadClientAuthenticationException: Failed to authenticate with Transmission.
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, TransmissionSettings settings, Boolean reauthenticate) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Transmission\TransmissionProxy.cs:line 240
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.ProcessRequest(String action, Object arguments, TransmissionSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Transmission\TransmissionProxy.cs:line 316
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.GetConfig(TransmissionSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Transmission\TransmissionProxy.cs:line 120
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.GetClientVersion(TransmissionSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Transmission\TransmissionProxy.cs:line 112
   at NzbDrone.Core.Download.Clients.Transmission.Transmission.ValidateVersion() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Transmission\Transmission.cs:line 42
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionBase.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Transmission\TransmissionBase.cs:line 287

[AB#1740](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1740)

**Comment by ta264** [comment]
Please use the support channels first, if this does turn out to be a bug we can reopen

**Comment by tree-white** [comment]
It has been normal all the time, but it suddenly expired today, and the click test has been prompted to fail the verification.
![image](https://user-images.githubusercontent.com/80657359/144000176-0b69df2b-4f8f-423e-ae94-06340f84cc25.png)
