### ISSUE TITLE
Snatching same quality during API triggered `DownloadedMoviesScan` import

### ISSUE THREAD

**Issue by Rouzax** [Radarr/Radarr#6790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have created issues for this before, and I know it is an edge case, but it is really annoying that it is happing as it fills up my torrent disk with duplicated movie downloads.

I use Radarr to snatch movies, but the actually import in Radarr is done by calling the Radarr API v3. The reason for this is that I need to do post processing before Radarr can import.

During the API call I give Radarr the location where the file is residing, and the download client ID, so it knows which of it's snatches it was.

POST 
`http://RADARR:7878/api/v3/command`

**BODY**
```JSON
{
    "name": "DownloadedMoviesScan",
    "downloadClientId":"04E19AEB0287422EF693FAC8EA0553F853C5D90F"
    "importMode": "Move",
    "path": "C:\\TEMP\\Torrent\\PROCD\\Movie\\Cry.Macho.2021.2160p.UHD.Remux.HEVC.HDR.DTS-HD.MA.5.1-playBD"
}
```

About 95% of the time this works fully as intended and there are no issues, however there are times that during import Radarr will snatch the same movie in the same quality again. In the log it will say that qBittorent cannot be reached which is impossible as both are running on the same machine and both stay active.

Here is an instance of this happening.

**qBittorent**
![image](https://user-images.githubusercontent.com/4103090/144812733-73be1019-36d2-43e6-ac33-5e2a64e2225d.png)

**Radarr**
![image](https://user-images.githubusercontent.com/4103090/144812795-61efa0a0-8461-4b53-84c2-ef0d1e79e7dd.png)

**Radarr normal log**
```
2021-12-05 18:26:24.6|Info|DownloadDecisionMaker|Processing 894 releases
2021-12-05 18:26:43.0|Info|DownloadService|Report sent to qBittorent. Cry Macho 2021 2160p UHD Remux HEVC HDR DTS-HD MA 5 1-playBD
2021-12-05 18:26:43.0|Info|RssSyncService|RSS Sync Completed. Reports found: 894, Reports grabbed: 1
2021-12-05 18:41:21.2|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. C:\DATA\Movies\Cry Macho (2021)\Cry Macho (2021) - [WEBDL-2160p][X265][AC3 5.1][EN][CMRG].mkv
2021-12-05 18:41:22.1|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. C:\DATA\Movies\Cry Macho (2021)\Cry Macho (2021) - [WEBDL-2160p][X265][AC3 5.1][EN][CMRG].en.srt
2021-12-05 18:41:22.1|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. C:\DATA\Movies\Cry Macho (2021)\Cry Macho (2021) - [WEBDL-2160p][X265][AC3 5.1][EN][CMRG]-fanart.jpg
2021-12-05 18:41:22.1|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. C:\DATA\Movies\Cry Macho (2021)\Cry Macho (2021) - [WEBDL-2160p][X265][AC3 5.1][EN][CMRG]-landscape.jpg
2021-12-05 18:41:22.1|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. C:\DATA\Movies\Cry Macho (2021)\Cry Macho (2021) - [WEBDL-2160p][X265][AC3 5.1][EN][CMRG]-poster.jpg
2021-12-05 18:41:53.2|Info|RssSyncService|Starting RSS Sync
2021-12-05 18:41:55.5|Info|DownloadDecisionMaker|Processing 894 releases
2021-12-05 18:42:15.0|Warn|ProcessDownloadDecisions|Couldn't add report to download queue. Cry Macho 2021 2160p UHD Remux HEVC HDR DTS-HD MA 5 1-playBD

[v3.2.2.5080] NzbDrone.Core.Download.Clients.DownloadClientException: Download client failed to add torrent
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.AddTorrentFromFile(String fileName, Byte[] fileContent, TorrentSeedConfiguration seedConfiguration, QBittorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxyV2.cs:line 205
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.AddFromTorrentFile(RemoteMovie remoteMovie, String hash, String filename, Byte[] fileContent) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 139
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteMovie remoteMovie, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 191
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 118
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 73
   at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions(List`1 decisions) in D:\a\1\s\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:line 76


2021-12-05 18:42:17.3|Info|DownloadService|Report sent to qBittorent. Cry Macho 2021 2160p UHD Remux HEVC HDR DTS-HD MA 5 1-playBD
2021-12-05 18:42:17.3|Info|RssSyncService|RSS Sync Completed. Reports found: 894, Reports grabbed: 1
2021-12-05 18:43:20.1|Info|MovieService|Assigning file [Cry Macho (2021) - [Remux-2160p][HEVC][DTS-HD MA 5.1][EN][playBD].mkv] to movie [[Cry Macho (2021)][tt1924245, 749274]]
2021-12-05 18:57:12.2|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. C:\DATA\Movies\Cry Macho (2021)\Cry Macho (2021) - [Remux-2160p][HEVC][DTS-HD MA 5.1][EN][playBD].mkv
2021-12-05 18:57:12.6|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. C:\DATA\Movies\Cry Macho (2021)\Cry Macho (2021) - [Remux-2160p][HEVC][DTS-HD MA 5.1][EN][playBD].en.srt
2021-12-05 18:57:12.7|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. C:\DATA\Movies\Cry Macho (2021)\Cry Macho (2021) - [Remux-2160p][HEVC][DTS-HD MA 5.1][EN][playBD].nl.srt
2021-12-05 18:57:23.6|Info|RssSyncService|Starting RSS Sync
2021-12-05 18:57:25.8|Info|DownloadDecisionMaker|Processing 894 releases
2021-12-05 18:57:42.6|Warn|ProcessDownloadDecisions|Couldn't add report to download queue. Cry Macho 2021 2160p UHD Remux HEVC HDR DTS-HD MA 5 1-playBD

[v3.2.2.5080] NzbDrone.Core.Download.Clients.DownloadClientException: Download client failed to add torrent
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.AddTorrentFromFile(String fileName, Byte[] fileContent, TorrentSeedConfiguration seedConfiguration, QBittorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxyV2.cs:line 205
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.AddFromTorrentFile(RemoteMovie remoteMovie, String hash, String filename, Byte[] fileContent) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 139
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteMovie remoteMovie, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 191
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 118
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 73
   at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions(List`1 decisions) in D:\a\1\s\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:line 76


2021-12-05 18:57:45.1|Warn|ProcessDownloadDecisions|Couldn't add report to download queue. Cry Macho 2021 2160p UHD Remux HEVC HDR DTS-HD MA 5 1-playBD

[v3.2.2.5080] NzbDrone.Core.Download.Clients.DownloadClientException: Download client failed to add torrent
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.AddTorrentFromFile(String fileName, Byte[] fileContent, TorrentSeedConfiguration seedConfiguration, QBittorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxyV2.cs:line 205
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.AddFromTorrentFile(RemoteMovie remoteMovie, String hash, String filename, Byte[] fileContent) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 139
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteMovie remoteMovie, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 191
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 118
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 73
   at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions(List`1 decisions) in D:\a\1\s\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:line 76


2021-12-05 18:57:47.0|Info|DownloadService|Report sent to qBittorent. Cry Macho 2021 2160p UHD Remux HEVC HDR DTS-HD MA 5.1-playBD
2021-12-05 18:57:47.1|Info|RssSyncService|RSS Sync Completed. Reports found: 894, Reports grabbed: 1
2021-12-05 18:59:10.7|Info|MovieService|Assigning file [Cry Macho (2021) - [Remux-2160p][HEVC][DTS-HD MA 5.1][EN][playBD].mkv] to movie [[Cry Macho (2021)][tt1924245, 749274]]
2021-12-05 19:05:32.8|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. C:\DATA\Movies\Cry Macho (2021)\Cry Macho (2021) - [Remux-2160p][HEVC][DTS-HD MA 5.1][EN][playBD].mkv
2021-12-05 19:05:33.2|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. C:\DATA\Movies\Cry Macho (2021)\Cry Macho (2021) - [Remux-2160p][HEVC][DTS-HD MA 5.1][EN][playBD].en.srt
2021-12-05 19:05:33.3|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. C:\DATA\Movies\Cry Macho (2021)\Cry Macho (2021) - [Remux-2160p][HEVC][DTS-HD MA 5.1][EN][playBD].nl.srt
2021-12-05 19:07:38.5|Info|MovieService|Assigning file [Cry Macho (2021) - [Remux-2160p][HEVC][DTS-HD MA 5.1][EN][playBD].mkv] to movie [[Cry Macho (2021)][tt1924245, 749274]]
```

**qBittorent Logs**
```
(N) 2021-12-05T18:26:43 - 'Cry.Macho.2021.2160p.UHD.Remux.HEVC.HDR.DTS-HD.MA.5.1-playBD.mkv' added to download list.
(N) 2021-12-05T18:35:27 - Torrent: Cry.Macho.2021.2160p.UHD.Remux.HEVC.HDR.DTS-HD.MA.5.1-playBD.mkv, running external program, command: powershell "C:\GitHub\TorrentScript\TorrentScript.ps1" -DownloadPath 'C:\TEMP\Torrent\Downloads\Cry.Macho.2021.2160p.UHD.Remux.HEVC.HDR.DTS-HD.MA.5.1-playBD.mkv' -DownloadLabel 'Movie' -TorrentHash 'e552c71d25ffbe366c8a3f241525ba379dc789ff'
(N) 2021-12-05T18:42:17 - 'Cry.Macho.2021.2160p.UHD.Remux.HEVC.HDR.DTS-HD.MA.5.1-playBD' added to download list.
(N) 2021-12-05T18:51:31 - Torrent: Cry.Macho.2021.2160p.UHD.Remux.HEVC.HDR.DTS-HD.MA.5.1-playBD, running external program, command: powershell "C:\GitHub\TorrentScript\TorrentScript.ps1" -DownloadPath 'C:\TEMP\Torrent\Downloads\Cry.Macho.2021.2160p.UHD.Remux.HEVC.HDR.DTS-HD.MA.5.1-playBD' -DownloadLabel 'Movie' -TorrentHash '7a1685d674467b2ae44279c6cb025615c50a4844'
(N) 2021-12-05T18:57:47 - 'Cry.Macho.2021.2160p.UHD.Remux.HEVC.HDR.DTS-HD.MA.5.1-playBD' added to download list.
(N) 2021-12-05T18:58:48 - Torrent: Cry.Macho.2021.2160p.UHD.Remux.HEVC.HDR.DTS-HD.MA.5.1-playBD, running external program, command: powershell "C:\GitHub\TorrentScript\TorrentScript.ps1" -DownloadPath 'C:\TEMP\Torrent\Downloads\Cry.Macho.2021.2160p.UHD.Remux.HEVC.HDR.DTS-HD.MA.5.1-playBD' -DownloadLabel 'Movie' -TorrentHash '04e19aeb0287422ef693fac8ea0553f853c5d90f'
```

Unfortunatly the trace logs have already rolled over for Radarr so I can't retrive them for this instance but will add to this issue when it happens again.

How can I change the Debug/trace log size/rollover?

Previous issues:
https://github.com/Radarr/Radarr/issues/3907
https://github.com/Radarr/Radarr/issues/4134
https://github.com/Radarr/Radarr/issues/3778

I understand that I'm opperating as an edgecase with Radarr but I would really like to get this solved. If there is a better API command to trigger the import please also let me know.
So let me know what you need from my side to get that done.

### Expected Behavior

Not to snatch a duplicated same quality movie

### Environment

```markdown
- OS: Server 2019
- Radarr:3.2.2.5080
- Docker Install:No
- Using Reverse Proxy: Yes
- Browser: Firefox
```

### What branch are you running?

Develop

### Trace Logs?

No trace logs at the moment.
How can I extend the rollover of the log size?

[AB#2086](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2086)

**Comment by ta264** [comment]
This looks like it's unrelated to your API call and instead a failure adding the torrent.  You need to fix whatever is going wrong on qbittorrent.

I'm going to mark this as support for now, but if you come by discord hopefully we can figure out what's going on.  If it does turn out to be a radarr bug we can reopen / fix

**Comment by Rouzax** [comment]
I'll add some more context here as that allows me better formatting

Radarr Snatched to qBittorent at: 18:26:43
```
2021-12-05 18:26:43.0|Info|DownloadService|Report sent to qBittorent. Cry Macho 2021 2160p UHD Remux HEVC HDR DTS-HD MA 5 1-playBD
```

Comes in to qBittorent at the same time: 18:26:43
```
(N) 2021-12-05T18:26:43 - 'Cry.Macho.2021.2160p.UHD.Remux.HEVC.HDR.DTS-HD.MA.5.1-playBD.mkv' added to download list.
```

qBittorent finish download and starts import script at: 18:35:27
```
(N) 2021-12-05T18:35:27 - Torrent: Cry.Macho.2021.2160p.UHD.Remux.HEVC.HDR.DTS-HD.MA.5.1-playBD.mkv, running external program, command: powershell "C:\GitHub\TorrentScript\TorrentScript.ps1" -DownloadPath 'C:\TEMP\Torrent\Downloads\Cry.Macho.2021.2160p.UHD.Remux.HEVC.HDR.DTS-HD.MA.5.1-playBD.mkv' -DownloadLabel 'Movie' -TorrentHash 'e552c71d25ffbe366c8a3f241525ba379dc789ff'
```

The script runs for 7 minutes and 53 seconds
![image](https://user-images.githubusercontent.com/4103090/144828629-9d817337-9a10-4087-af0c-1469524304e7.png)


At 18:42:15 Radarr import API is called and that triggers the qBittorent `Couldn't add report to download queue` warning.
That triggers another snatch, while in the backend the first snatch is being imported.
```
2021-12-05 18:42:15.0|Warn|ProcessDownloadDecisions|Couldn't add report to download queue. Cry Macho 2021 2160p UHD Remux HEVC HDR DTS-HD MA 5 1-playBD

[v3.2.2.5080] NzbDrone.Core.Download.Clients.DownloadClientException: Download client failed to add torrent
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.AddTorrentFromFile(String fileName, Byte[] fileContent, TorrentSeedConfiguration seedConfiguration, QBittorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxyV2.cs:line 205
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.AddFromTorrentFile(RemoteMovie remoteMovie, String hash, String filename, Byte[] fileContent) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 139
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteMovie remoteMovie, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 191
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 118
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 73
   at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions(List`1 decisions) in D:\a\1\s\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:line 76


2021-12-05 18:42:17.3|Info|DownloadService|Report sent to qBittorent. Cry Macho 2021 2160p UHD Remux HEVC HDR DTS-HD MA 5 1-playBD
2021-12-05 18:42:17.3|Info|RssSyncService|RSS Sync Completed. Reports found: 894, Reports grabbed: 1
```

```
(N) 2021-12-05T18:42:17 - 'Cry.Macho.2021.2160p.UHD.Remux.HEVC.HDR.DTS-HD.MA.5.1-playBD' added to download list.
```
