### ISSUE TITLE
Importing movies fails with folders that have non-alphanumeric characters

### ISSUE THREAD

**Issue by themurderlator** [Radarr/Radarr#68]
Attempting to import any movies with parenthesis in the folder name fails:

Example: Z:\Movies\Pulp Fiction (1994) (tt0110912)

There Was An Error Searching For 'Pulp Fiction (1994) (Tt0110912)'.
If the movie title contains non-alphanumeric characters try removing them, otherwise try your search again later.

**Comment by fedoranimus** [comment]
I am able to import movies of this format on my in-progress branch. I'll update this when I merge.

**Comment by galli-leo** [comment]
Should be fixed on the latest commit.

**Comment by themurderlator** [comment]
Just checked and it's now able to import movies but it says that the movie is missing. Here's a message log.

> DiskScanService failed while processing [MovieUpdatedEvent]: Object reference not set to an instance of an object.

> System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.<>c.<Import>b__7_1(ImportDecision c) in C:\projects\radarr\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:line 51
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`4.GetEnumerator()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\radarr\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:line 50
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(Movie movie) in C:\projects\radarr\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 182
   at NzbDrone.Core.MediaFiles.DiskScanService.Handle(MovieUpdatedEvent message) in C:\projects\radarr\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 258
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

Let me know if I should create a new ticket for this issue.

**Comment by fedoranimus** [comment]
Can you retest this on the latest version?

**Comment by fedoranimus** [comment]
This works for me. Closing, since no new information has been provided.
