### ISSUE TITLE
DSM 7 Download Station Error Fixed in Sonarr but dev update not available in radarr. 

### ISSUE THREAD

**Issue by humlemand** [Radarr/Radarr#6818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am unable to add download station to my radarr config, since dsm 7. I understand, that the problem was solved in Sonarr in nov. in version 3.0.6.1386. But I still have the issue, in my latest nightly update for radar is from dec. 4.0.0.5597

Sadly, I can't run docker, on my synology, since its cpu is not supported (synology hasn't made a package for that cpu). 

So I guess, my actual question should be, why isn't it working in radarr, when 
"Download Station Error with DSM 7.0 Beta #5567" is marked as closed, with a solution referring to a sonarr update. 

I installed radarr package from https://packages.synocommunity.com/

### Expected Behavior

I expect to be able to connect to download station, but get the error "no default destination"

### Environment

```markdown
- OS: Synology DSM7
- Radarr:4.0.0.5597
- Docker Install: No
- Using Reverse Proxy:No
- Browser: Edge
```

### What branch are you running?

Nightly

### Trace Logs?

![image](https://user-images.githubusercontent.com/96182090/146184862-8465c511-0d58-45fb-8f41-af6bcea366f0.png)

2021-12-15 13:18:39.6|Debug|Api|[GET] /api/v3/command: 200.OK (3 ms)
2021-12-15 13:18:45.0|Debug|Api|[GET] /api/v3/queue/details: 200.OK (9 ms)
2021-12-15 13:18:45.0|Debug|Api|[GET] /api/v3/queue/details: 200.OK (3 ms)
2021-12-15 13:18:45.1|Debug|Api|[GET] /api/v3/command: 200.OK (3 ms)
2021-12-15 13:18:45.3|Debug|Api|[GET] /api/v3/command: 200.OK (3 ms)
2021-12-15 13:18:47.1|Debug|Api|[GET] /api/v3/config/downloadclient: 200.OK (2 ms)
2021-12-15 13:18:47.2|Debug|Api|[GET] /api/v3/downloadclient: 200.OK (8 ms)
2021-12-15 13:18:47.2|Debug|Api|[GET] /api/v3/remotepathmapping: 200.OK (23 ms)
2021-12-15 13:18:49.7|Debug|UsenetDownloadStation|Download Station api version information: Min 1 - Max 2
2021-12-15 13:18:49.9|Debug|DownloadStationInfoProxy|Trying to get config
2021-12-15 13:18:49.9|Debug|DownloadStationTaskProxyV2|Trying to get tasks with additional detail
2021-12-15 13:18:50.1|Debug|DSMInfoProxy|Trying to get serial number
2021-12-15 13:18:50.1|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.0.0.5597] FluentValidation.ValidationException: Validation failed: 
 -- TvDirectory: No default destination
   at Radarr.Api.V3.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 200
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 191
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 140
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2021-12-15 13:18:50.1|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- TvDirectory: No default destination
2021-12-15 13:18:50.1|Debug|Api|[POST] /api/v3/downloadclient/test: 400.BadRequest (463 ms)
2021-12-15 13:18:52.3|Debug|Api|[PUT] /api/v3/downloadclient/1: 202.Accepted (92 ms)
2021-12-15 13:18:52.4|Debug|Api|[GET] /api/v3/health: 200.OK (2 ms)
2021-12-15 13:18:54.3|Debug|Api|[GET] /api/v3/health: 200.OK (2 ms)
2021-12-15 13:18:54.3|Debug|Api|[GET] /api/v3/system/status: 200.OK (13 ms)
2021-12-15 13:18:54.3|Debug|Api|[GET] /api/v3/diskspace: 200.OK (42 ms)
2021-12-15 13:18:56.6|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)
2021-12-15 13:19:15.1|Debug|Api|[GET] /api/v3/command: 200.OK (4 ms)
2021-12-15 13:19:36.8|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)
2021-12-15 13:19:37.9|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)
2021-12-15 13:19:38.5|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)

[AB#2153](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2153)

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/issues/6751

**Comment by humlemand** [comment]
> #6751

Sorry, I don't think i understand the reference in #6751

**Comment by bakerboy448** [comment]
![image](https://user-images.githubusercontent.com/55419169/146206968-b60fe55f-a41e-4df9-866b-bd96f872d492.png)

That GHI is the pull for this commit from Sonarr

**Comment by Stanzilla** [comment]
Hrm the latest Radarr release on this repo is from June, did I miss something or has there really been no release since then?

**Comment by humlemand** [comment]
> Hrm the latest Radarr release on this repo is from June, did I miss something or has there really been no release since then?

I tried the latest nightly build. That's from Dec.
But dev and master are from June.
