### ISSUE TITLE
qBittorrent: Can't authenticate after qBittorrent v4.3.9

### ISSUE THREAD

**Issue by Dr0id1** [Radarr/Radarr#6836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When Testing downclien I get the auth failed error. I tried the credentials in a browser and it worked. I also have the same config running in Sonarr without any issue. Tried to delete and redo the download client profil and I got the same error.

### Expected Behavior

Radarr should be able to authenticate with qBittorrent.

### Steps To Reproduce

1. Radarr running in a docker container
2. Having qBittorrent v4.3.9 (latest)
2. Opening Radarr's settings
3. Creating a new download client profil
4. filling all the info
5. Testing connection

### Environment

```markdown
- OS: Ubuntun 20.04.2 LTS
- Radarr: 3.2.2.5080
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: N/A
```

### What branch are you running?

Master

### Trace Logs?

```
2021-12-17 23:55:15.2|Trace|DiskProviderBase|Deleting file: /config/logs/radarr.debug.txt
2021-12-17 23:55:15.2|Trace|CommandQueueManager|Updating command status
2021-12-17 23:55:15.3|Trace|EventAggregator|Publishing CommandUpdatedEvent
2021-12-17 23:55:15.3|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2021-12-17 23:55:15.3|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2021-12-17 23:55:15.3|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2021-12-17 23:55:15.3|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2021-12-17 23:55:15.3|Trace|EventAggregator|Publishing CommandExecutedEvent
2021-12-17 23:55:15.3|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2021-12-17 23:55:15.3|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2021-12-17 23:55:15.3|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
2021-12-17 23:55:15.3|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
2021-12-17 23:55:15.3|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
2021-12-17 23:55:15.3|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
2021-12-17 23:55:15.3|Trace|CommandExecutor|DeleteLogFilesCommand <- DeleteLogFilesService [00:00:00.0080701]
2021-12-17 23:55:15.4|Trace|Http|Req: 136608 [GET] /api/v3/command (from ::ffff:192.168.1.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36)
2021-12-17 23:55:15.4|Trace|CommandQueueManager|Getting all commands
2021-12-17 23:55:15.8|Trace|Http|Res: 136608 [GET] /api/v3/command: 200.OK (446 ms)
2021-12-17 23:55:15.8|Debug|Api|[GET] /api/v3/command: 200.OK (446 ms)
2021-12-17 23:55:18.3|Trace|Http|Req: 136609 [GET] /api/v3/downloadclient (from ::ffff:192.168.1.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36)
2021-12-17 23:55:18.3|Trace|Http|Req: 136610 [GET] /api/v3/config/downloadclient (from ::ffff:192.168.1.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36)
2021-12-17 23:55:18.3|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
2021-12-17 23:55:18.3|Trace|ConfigService|Using default config value for 'removecompleteddownloads' defaultValue:'False'
2021-12-17 23:55:18.3|Trace|ConfigService|Using default config value for 'checkforfinisheddownloadinterval' defaultValue:'1'
2021-12-17 23:55:18.3|Trace|ConfigService|Using default config value for 'autoredownloadfailed' defaultValue:'True'
2021-12-17 23:55:18.3|Trace|ConfigService|Using default config value for 'removefaileddownloads' defaultValue:'True'
2021-12-17 23:55:18.3|Trace|Http|Res: 136610 [GET] /api/v3/config/downloadclient: 200.OK (4 ms)
2021-12-17 23:55:18.3|Debug|Api|[GET] /api/v3/config/downloadclient: 200.OK (4 ms)
2021-12-17 23:55:18.3|Trace|Http|Res: 136609 [GET] /api/v3/downloadclient: 200.OK (10 ms)
2021-12-17 23:55:18.3|Debug|Api|[GET] /api/v3/downloadclient: 200.OK (10 ms)
2021-12-17 23:55:18.3|Trace|Http|Req: 136611 [GET] /api/v3/remotepathmapping (from ::ffff:192.168.1.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36)
2021-12-17 23:55:18.3|Trace|Http|Res: 136611 [GET] /api/v3/remotepathmapping: 200.OK (2 ms)
2021-12-17 23:55:18.3|Debug|Api|[GET] /api/v3/remotepathmapping: 200.OK (2 ms)
2021-12-17 23:55:22.1|Trace|Http|Req: 136612 [POST] /api/v3/downloadclient/test (from ::ffff:192.168.1.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36)
2021-12-17 23:55:22.2|Trace|HttpClient|Req: [GET] http://192.168.1.12:9090/api/v2/app/webapiVersion
2021-12-17 23:55:22.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-12-17 23:55:22.2|Trace|HttpClient|Res: [GET] http://192.168.1.12:9090/api/v2/app/webapiVersion: 403.Forbidden
Forbidden (1 ms)
2021-12-17 23:55:22.2|Trace|HttpClient|Response content (9 bytes): Forbidden
2021-12-17 23:55:22.2|Trace|QBittorrentProxySelector|Using qbitTorrent API v2
2021-12-17 23:55:22.2|Trace|HttpClient|Req: [POST] http://192.168.1.12:9090/api/v2/auth/login: username=admin&password=(removed)
2021-12-17 23:55:22.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-12-17 23:55:22.3|Trace|HttpClient|Res: [POST] http://192.168.1.12:9090/api/v2/auth/login: 200.OK (158 ms)
2021-12-17 23:55:22.3|Trace|HttpClient|Response content (6 bytes): Fails.
2021-12-17 23:55:22.3|Debug|QBittorrentProxyV2|qbitTorrent authentication failed.
2021-12-17 23:55:22.3|Error|QBittorrent|Failed to authenticate with qBittorrent.

[v3.2.2.5080] NzbDrone.Core.Download.Clients.DownloadClientAuthenticationException: Failed to authenticate with qBittorrent.
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.AuthenticateClient(HttpRequestBuilder requestBuilder, QBittorrentSettings settings, Boolean reauthenticate) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxyV2.cs:line 430
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxyV2.cs:line 381
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.GetApiVersion(QBittorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxyV2.cs:line 71
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.FetchProxy(QBittorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 99
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 114
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxy(QBittorrentSettings settings, Boolean force) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 65
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 412


2021-12-17 23:55:22.3|Trace|RadarrErrorPipeline|Handling Exception
2021-12-17 23:55:22.3|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Username: Authentication failure
2021-12-17 23:55:22.3|Trace|Http|Res: 136612 [POST] /api/v3/downloadclient/test: 400.BadRequest (191 ms)
2021-12-17 23:55:22.3|Debug|Api|[POST] /api/v3/downloadclient/test: 400.BadRequest (191 ms)
2021-12-17 23:55:25.3|Trace|Http|Req: 136613 [GET] /api/v3/health (from ::ffff:192.168.1.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36)
2021-12-17 23:55:25.3|Trace|Http|Res: 136613 [GET] /api/v3/health: 200.OK (1 ms)
2021-12-17 23:55:25.3|Debug|Api|[GET] /api/v3/health: 200.OK (1 ms)
2021-12-17 23:55:25.3|Trace|Http|Req: 136614 [GET] /api/v3/diskspace (from ::ffff:192.168.1.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36)
2021-12-17 23:55:25.3|Trace|Http|Req: 136615 [GET] /api/v3/system/status (from ::ffff:192.168.1.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36)
2021-12-17 23:55:25.4|Trace|Http|Res: 136615 [GET] /api/v3/system/status: 200.OK (6 ms)
2021-12-17 23:55:25.4|Debug|Api|[GET] /api/v3/system/status: 200.OK (6 ms)
2021-12-17 23:55:25.7|Trace|Http|Res: 136614 [GET] /api/v3/diskspace: 200.OK (309 ms)
2021-12-17 23:55:25.7|Debug|Api|[GET] /api/v3/diskspace: 200.OK (309 ms)
2021-12-17 23:55:26.3|Trace|Http|Req: 136616 [GET] /api/v3/log/file (from ::ffff:192.168.1.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36)
2021-12-17 23:55:26.3|Trace|Http|Res: 136616 [GET] /api/v3/log/file: 200.OK (2 ms)
2021-12-17 23:55:26.3|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)
2021-12-17 23:55:28.4|Trace|Http|Req: 136617 [GET] /logfile/radarr.trace.txt (from ::ffff:192.168.1.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36)
```

[AB#2195](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2195)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

https://gist.github.com/bakerboy448/14335936f6df6ae1bdcf05d704c356a0

Could not reproduce

qBittorrent v4.3.9 Web UI (64-bit)
Radarr 4.0.0.5620
