### ISSUE TITLE
Request Failed: Instance property 'this' is not defined for type 'NzbDrone.Core.Tv.Movie'

### ISSUE THREAD

**Issue by onedr0p** [Radarr/Radarr#684]
Shows up once in awhile, not life threatening to Radarr, but a bug none-the-less.

NzbDroneErrorPipeline
```System.ArgumentException: Instance property 'this' is not defined for type 'NzbDrone.Core.Tv.Movie'
  at System.Linq.Expressions.Expression.Property (System.Linq.Expressions.Expression expression, System.String propertyName) [0x00058] in <63992662b765477a898ef49cdcc99ee2>:0 
  at NzbDrone.Core.Datastore.Extensions.PagingSpecExtensions.CreateExpression[TModel] (System.String propertyName) [0x0003d] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Extensions\PagingSpecExtensions.cs:36 
  at NzbDrone.Core.Datastore.Extensions.PagingSpecExtensions.OrderByClause[TModel] (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Extensions\PagingSpecExtensions.cs:11 
  at NzbDrone.Core.Tv.MovieRepository.GetMoviesWithoutFilesQuery (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieRepository.cs:195 
  at NzbDrone.Core.Tv.MovieRepository.MoviesWithoutFiles (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieRepository.cs:187 
  at NzbDrone.Core.Tv.MovieService.MoviesWithoutFiles (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:277 
  at NzbDrone.Api.NzbDroneRestModule`1[TResource].ApplyToPage[TModel] (System.Func`2[T,TResult] function, NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec, System.Converter`2[TInput,TOutput] mapper) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModule.cs:27 
  at NzbDrone.Api.Wanted.MovieMissingModule.GetMissingMovies (NzbDrone.Api.PagingResource`1[TResource] pagingResource) [0x000e5] in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieMissingModule.cs:44 
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourcePaged>b__35_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:126 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 ```

**Comment by DTrace001** [comment]
I get that when I try to view the Wanted tab

**Comment by jaycedk** [comment]
I'm getting this error, when I try to view the Wanted Tab.

Message

Request Failed: Instance property 'this' is not defined for type 'NzbDrone.Core.Tv.Movie'


Exception

System.ArgumentException: Instance property 'this' is not defined for type 'NzbDrone.Core.Tv.Movie'
   at System.Linq.Expressions.Expression.Property(Expression expression, String propertyName)
   at NzbDrone.Core.Datastore.Extensions.PagingSpecExtensions.CreateExpression[TModel](String propertyName) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Extensions\PagingSpecExtensions.cs:line 36
   at NzbDrone.Core.Tv.MovieRepository.GetMoviesWithoutFilesQuery(PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieRepository.cs:line 197
   at NzbDrone.Core.Tv.MovieRepository.MoviesWithoutFiles(PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieRepository.cs:line 189
   at NzbDrone.Core.Tv.MovieService.MoviesWithoutFiles(PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:line 277
   at NzbDrone.Api.NzbDroneRestModule`1.ApplyToPage[TModel](Func`2 function, PagingSpec`1 pagingSpec, Converter`2 mapper) in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModule.cs:line 27
   at NzbDrone.Api.Wanted.MovieMissingModule.GetMissingMovies(PagingResource`1 pagingResource) in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieMissingModule.cs:line 44
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourcePaged>b__35_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 126
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by onedr0p** [comment]
Wanted tab works n the latest nightly

**Comment by jaycedk** [comment]
Hmm strange 

0.2.0.314 - 2017-02-10 nightly Installed
New Pass at seeing if this works on linux now (#692)

Stille getting the error on this tab.

![wanted tab](https://cloud.githubusercontent.com/assets/17232146/22820006/2dbdbd5a-ef75-11e6-82d4-1ca31f5986f1.PNG)

**Comment by onedr0p** [comment]
try incognito

**Comment by schumi2004** [comment]
Didn't you fixed that with commit https://github.com/Radarr/Radarr/commit/c43c9f049cb3705e6698662483a99d28fd248818 ?

**Comment by onedr0p** [comment]
I fixed it before, but that allows for sorting. It's a matter of his browser using the cache to get the sort key which is invalid.

**Comment by jaycedk** [comment]
Ok sorry about that. 
Just tried in IE and there it worked. 
Will have to clear cache in firefox.

**Comment by jaycedk** [comment]
ok after clearing cache in firefox its working again.
Thanks for you help :)
