### ISSUE TITLE
"Clean Up Recycle Bin" Task fails completely due to .nomedia file

### ISSUE THREAD

**Issue by phit42** [Radarr/Radarr#6859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Due to our media player, I have a read-only .nomedia file in the recycle bin folder. The "cleanup recycle bin task" fails on this file with obviously no access, this would not be an issue if it would delete all "normal" movie file nonetheless, however it stops immediately with the error. 

(PS It is not an issue with general access to the folder. Radarr is using the folder just fine and putting deleted items into it.)

### Expected Behavior

Request: please exclude .nomedia file from cleanup process. It is required. (I believe it is good practice in *nix to not delete any files beginning with a . in standard tasks, as they are usually for special purposes.)

### Steps To Reproduce

Create a read-only (or maybe unaccessible) file in recycle bin and try task.

### Environment

```markdown
- OS: Synology DSM
- Radarr:   3.2.2.5080-ls125 by linuxserver.io, .NET (5.0.5)
- Docker Install:   Yes
- Using Reverse Proxy:  No
- Browser:   Chrome
```

### What branch are you running?

Master

### Trace Logs?

`2021-12-22 09:24:59.1|Info|RecycleBinProvider|Removing items older than 7 days from the recycling bin
2021-12-22 09:24:59.3|Error|CommandExecutor|Error occurred while executing task CleanUpRecycleBin

[v3.2.2.5080] System.UnauthorizedAccessException: Access to the path '/movies/__Papierkorb/.nomedia' is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Int64 result, String path, Boolean isDirectory, Func`2 errorRewriter)
   at System.IO.FileStatus.SetAttributes(String path, FileAttributes attributes)
   at System.IO.File.SetAttributes(String path, FileAttributes fileAttributes)
   at NzbDrone.Common.Disk.DiskProviderBase.RemoveReadOnly(String path) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 384
   at NzbDrone.Common.Disk.DiskProviderBase.DeleteFile(String path) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 197
   at NzbDrone.Core.MediaFiles.RecycleBinProvider.Cleanup() in D:\a\1\s\src\NzbDrone.Core\MediaFiles\RecycleBinProvider.cs:line 182
   at NzbDrone.Core.MediaFiles.RecycleBinProvider.Execute(CleanUpRecycleBinCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\RecycleBinProvider.cs:line 207
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 118
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44`

[AB#2245](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2245)

**Comment by phit42** [comment]
Note: I got a strange error message from Github after opening this issue, if this is of interest to you: "[Radarr/Radarr] Run cancelled: Sync issue to Azure DevOps work item - develop (eecd4e4)"

**Comment by Qstick** [comment]
https://github.com/Radarr/Radarr/commit/50b273acaebb88e230a8ce0824dce7e7cdb23c48
