### ISSUE TITLE
Trying to setting up Download Station, failing

### ISSUE THREAD

**Issue by giospud** [Radarr/Radarr#6915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I try to set up Download Station but when I try to save it I get the following error:

Unknown exception: Failed to login. Reason: The requested method does not exist

any hint?

### Expected Behavior

Get the cofniguration for download Stationa dn work (like Sonarr is doing)

### Environment

```markdown
- OS:   Ubuntu 20.04
- Radarr:  202110708-15
- Docker Install:   not possible  (MARVELL Armada 385 88F6820)
- Using Reverse Proxy:   NO
- Browser:
```

### What branch are you running?

Master

### Trace Logs?

2022-1-8 20:59:41.3|Error|DownloadStationTaskProxy|Failed to login. Reason: The requested method does not exist
2022-1-8 20:59:41.3|Error|DownloadStationTaskProxy|NzbDrone.Core.Download.Clients.DownloadClientException: Failed to login. Reason: The requested method does not exist
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T](HttpRequestBuilder requestBuilder, String operation, DiskStationApi api, DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 121
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.AuthenticateClient(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 140
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.<>c__DisplayClass14_0.<BuildRequest>b__1() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 181
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 114
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.BuildRequest(DownloadStationSettings settings, DiskStationApiInfo apiInfo, String methodName, Int32 apiVersion, HttpMethod httpVerb) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 163
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.BuildRequest(DownloadStationSettings settings, String methodName, Int32 apiVersion, HttpMethod httpVerb) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 149
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DownloadStationTaskProxy.GetTasks(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DownloadStationTaskProxy.cs:line 56

[v3.0.2.4552] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to login. Reason: The requested method does not exist
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T](HttpRequestBuilder requestBuilder, String operation, DiskStationApi api, DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 121
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.AuthenticateClient(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 140
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.<>c__DisplayClass14_0.<BuildRequest>b__1() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 181
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 114
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.BuildRequest(DownloadStationSettings settings, DiskStationApiInfo apiInfo, String methodName, Int32 apiVersion, HttpMethod httpVerb) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 163
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.BuildRequest(DownloadStationSettings settings, String methodName, Int32 apiVersion, HttpMethod httpVerb) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 149
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DownloadStationTaskProxy.GetTasks(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DownloadStationTaskProxy.cs:line 56

2022-1-8 20:59:41.3|Error|DSMInfoProxy|Failed to login. Reason: The requested method does not exist
2022-1-8 20:59:41.3|Warn|SerialNumberProvider|Could not get the serial number from Download Station 127.0.0.1:5000

[v3.0.2.4552] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to login. Reason: The requested method does not exist
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T](HttpRequestBuilder requestBuilder, String operation, DiskStationApi api, DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 121
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.AuthenticateClient(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 140
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.<>c__DisplayClass14_0.<BuildRequest>b__1() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 181
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 114
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.BuildRequest(DownloadStationSettings settings, DiskStationApiInfo apiInfo, String methodName, Int32 apiVersion, HttpMethod httpVerb) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 163
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.BuildRequest(DownloadStationSettings settings, String methodName, Int32 apiVersion, HttpMethod httpVerb) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 149
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DSMInfoProxy.GetSerialNumber(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DSMInfoProxy.cs:line 24
   at NzbDrone.Core.Download.Clients.DownloadStation.SerialNumberProvider.GetHashedSerialNumber(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\SerialNumberProvider.cs:line 45
   at NzbDrone.Core.Download.Clients.DownloadStation.SerialNumberProvider.<>c__DisplayClass4_0.<GetSerialNumber>b__0() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\SerialNumberProvider.cs:line 34
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 114
   at NzbDrone.Core.Download.Clients.DownloadStation.SerialNumberProvider.GetSerialNumber(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\SerialNumberProvider.cs:line 34

2022-1-8 20:59:41.3|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Unknown exception: Failed to login. Reason: The requested method does not exist
 -- : Failed to get the list of torrents: Failed to login. Reason: The requested method does not exist

[AB#2328](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2328)

**Comment by Qstick** [comment]
You need to update, you are a few versions behind even for master branch
