### ISSUE TITLE
Email broken after 4.0.0.5745 update

### ISSUE THREAD

**Issue by Shnoobins** [Radarr/Radarr#6916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Email doesn't work after update on 2022/01/03. Testing email via the gui results in: Unable to send test email

Trace logs indicate an SSL failure due to self signed certificates, but there is no option to override the check or allow self-signed certs to not cause an SSL exception. Testing from CLI works fine to send an email (not through Radarr, via telnet). Works fine in Sonarr still, and worked fine prior to the 4.x update this past Monday. 

### Expected Behavior

A test email should be sent. 

### Steps To Reproduce

Setup email notifications under the 'connect' menu in settings. 

I have a local exchange server, not using SSL (port 25), though I've tried with ssl via starttls (56ma7) with the same behavior. 

### Environment

```markdown
- OS: Debian 11
- Radarr: Radarr 4.0.0.5745
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome (but does it in all)
```

### What branch are you running?

Develop

### Trace Logs?

```
2022-01-08 18:59:33.5|Trace|EventAggregator|ConfigSavedEvent ~> LocalizationService
2022-01-08 18:59:33.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-01-08 18:59:33.5|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2022-01-08 18:59:33.5|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2022-01-08 18:59:33.5|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2022-01-08 18:59:33.5|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2022-01-08 18:59:33.5|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2022-01-08 18:59:33.5|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2022-01-08 18:59:33.5|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2022-01-08 18:59:33.5|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2022-01-08 18:59:33.5|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-01-08 18:59:33.5|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2022-01-08 18:59:33.5|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2022-01-08 18:59:33.5|Trace|EventAggregator|ConfigSavedEvent <~ LocalizationService
2022-01-08 18:59:33.5|Trace|EventAggregator|ConfigSavedEvent ~> TaskManager
2022-01-08 18:59:33.5|Trace|Http|Res: 432 [PUT] /radarr/api/v3/config/host: 202.Accepted (57 ms)
2022-01-08 18:59:33.5|Trace|ConfigService|Using default config value for 'rsssyncinterval' defaultValue:'60'
2022-01-08 18:59:33.5|Trace|EventAggregator|ConfigFileSavedEvent <~ ReconfigureLogging
2022-01-08 18:59:33.5|Trace|ConfigService|Using default config value for 'importlistsyncinterval' defaultValue:'24'
2022-01-08 18:59:33.5|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2022-01-08 18:59:33.5|Trace|ConfigService|Using default config value for 'checkforfinisheddownloadinterval' defaultValue:'1'
2022-01-08 18:59:33.5|Trace|EventAggregator|ConfigSavedEvent <~ TaskManager
2022-01-08 18:59:33.7|Trace|HttpClient|Res: [GET] https://radarr.servarr.com/v1/notification?version=4.0.0.5745&os=linux&arch=X64&runtime=netcore&branch=master: 200.OK (203 ms)
2022-01-08 18:59:33.7|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2022-01-08 18:59:33.7|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2022-01-08 18:59:33.7|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2022-01-08 18:59:33.7|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2022-01-08 18:59:33.7|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2022-01-08 18:59:33.7|Trace|HttpClient|Res: [GET] https://radarr.servarr.com/v1/notification?version=4.0.0.5745&os=linux&arch=X64&runtime=netcore&branch=master: 200.OK (201 ms)
2022-01-08 18:59:33.7|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2022-01-08 18:59:33.7|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2022-01-08 18:59:33.7|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2022-01-08 18:59:33.7|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2022-01-08 18:59:33.7|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2022-01-08 18:59:33.7|Trace|Http|Req: 433 [GET] /radarr/api/v3/health (from 10.10.11.31)
2022-01-08 18:59:33.7|Trace|Http|Res: 433 [GET] /radarr/api/v3/health: 200.OK (4 ms)
2022-01-08 18:59:33.7|Trace|Http|Req: 434 [GET] /radarr/api/v3/health (from 10.10.11.31)
2022-01-08 18:59:33.7|Trace|Http|Res: 434 [GET] /radarr/api/v3/health: 200.OK (0 ms)
2022-01-08 18:59:34.9|Trace|Http|Req: 435 [GET] /radarr/api/v3/notification (from 10.10.11.31)
2022-01-08 18:59:34.9|Trace|Http|Res: 435 [GET] /radarr/api/v3/notification: 200.OK (7 ms)
2022-01-08 18:59:35.9|Trace|Http|Req: 436 [GET] /radarr/api/v3/notification/schema (from 10.10.11.31)
2022-01-08 18:59:35.9|Trace|Http|Res: 436 [GET] /radarr/api/v3/notification/schema: 200.OK (13 ms)
2022-01-08 18:59:57.1|Trace|Scheduler|Pending Tasks: 0
2022-01-08 19:00:11.7|Trace|Http|Req: 437 [POST] /radarr/api/v3/notification/test (from 10.10.11.31)
2022-01-08 19:00:11.7|Debug|Email|Sending email Subject: Radarr - Test Notification
2022-01-08 19:00:11.7|Debug|Email|Connecting to mail server
2022-01-08 19:00:11.8|Error|Email|Error sending email. Subject: Radarr - Test Notification
2022-01-08 19:00:11.8|Debug|Email|An error occurred while attempting to establish an SSL or TLS connection.

The server's SSL certificate could not be validated for the following reasons:
â€¢ The server certificate has the following errors:
  â€¢ self signed certificate


[v4.0.0.5745] MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

The server's SSL certificate could not be validated for the following reasons:
â€¢ The server certificate has the following errors:
  â€¢ self signed certificate

 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at NzbDrone.Core.Notifications.Email.Email.Send(MimeMessage email, EmailSettings settings) in D:\a\1\s\src\NzbDrone.Core\Notifications\Email\Email.cs:line 146
   at NzbDrone.Core.Notifications.Email.Email.SendEmail(EmailSettings settings, String subject, String body, Boolean htmlBody) in D:\a\1\s\src\NzbDrone.Core\Notifications\Email\Email.cs:line 111


2022-01-08 19:00:11.8|Error|Email|Unable to send test email

[v4.0.0.5745] MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

The server's SSL certificate could not be validated for the following reasons:
â€¢ The server certificate has the following errors:
  â€¢ self signed certificate

 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at NzbDrone.Core.Notifications.Email.Email.Send(MimeMessage email, EmailSettings settings) in D:\a\1\s\src\NzbDrone.Core\Notifications\Email\Email.cs:line 146
   at NzbDrone.Core.Notifications.Email.Email.SendEmail(EmailSettings settings, String subject, String body, Boolean htmlBody) in D:\a\1\s\src\NzbDrone.Core\Notifications\Email\Email.cs:line 111
   at NzbDrone.Core.Notifications.Email.Email.Test(EmailSettings settings) in D:\a\1\s\src\NzbDrone.Core\Notifications\Email\Email.cs:line 81


2022-01-08 19:00:11.8|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.0.0.5745] FluentValidation.ValidationException: Validation failed: 
 -- Server: Unable to send test email
   at Radarr.Api.V3.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 200
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 191
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 140
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-01-08 19:00:11.9|Trace|RadarrErrorPipeline|Handling Exception
2022-01-08 19:00:11.9|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Server: Unable to send test email
2022-01-08 19:00:11.9|Trace|Http|Res: 437 [POST] /radarr/api/v3/notification/test: 400.BadRequest (205 ms)
2022-01-08 19:00:16.6|Trace|Http|Req: 438 [GET] /radarr/api/v3/health (from 10.10.11.31)
2022-01-08 19:00:16.6|Trace|Http|Res: 438 [GET] /radarr/api/v3/health: 200.OK (1 ms)
2022-01-08 19:00:16.6|Trace|Http|Req: 439 [GET] /radarr/api/v3/diskspace (from 10.10.11.31)
2022-01-08 19:00:16.6|Trace|Http|Req: 440 [GET] /radarr/api/v3/system/status (from 10.10.11.31)
2022-01-08 19:00:16.7|Trace|Http|Res: 440 [GET] /radarr/api/v3/system/status: 200.OK (6 ms)
2022-01-08 19:00:16.7|Trace|Http|Res: 439 [GET] /radarr/api/v3/diskspace: 200.OK (81 ms)
2022-01-08 19:00:18.0|Trace|Http|Req: 441 [GET] /radarr/api/v3/log/file (from 10.10.11.31)
2022-01-08 19:00:18.0|Trace|Http|Res: 441 [GET] /radarr/api/v3/log/file: 200.OK (13 ms)
2022-01-08 19:00:19.8|Trace|Http|Req: 442 [GET] /radarr/logfile/radarr.trace.txt (from 10.10.11.31)
```

**Comment by bakerboy448** [comment]
Does the certificate validation setting in General not take care of this?

Disable local certification validation should do it.

Also little reason to have a self signed certificate in 2022 they're effectively security theater.

**Comment by Shnoobins** [comment]
It does not - tested with it off and the it's the same behavior.

I agree self signed isn't a worthy use case from a security standpoint. Anything internet facing gets its own cert. The mail server has no connection outside of the LAN.

**Comment by Qstick** [comment]
> Does the certificate validation setting in General not take care of this?
> 

It does not, we broke it.

**Comment by phrenesis82** [comment]
Hello. I have the same issue with the download client. Will the fix work for it too?

 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch, RemoteCertificateChainErrors

**Comment by bakerboy448** [comment]
What download client? But it would  not - and need more context not just the error as well. Note that Rtorrent has already been fixed in nightly.

But that's something for a separate GHI or better yet swing by discord and get it out.

**Comment by Qstick** [comment]
Assuming it's rtorrent or aria2, yes it's already fixed

**Comment by phrenesis82** [comment]
It's rutorrent. I'll just wait for the next update then. Thank you.
