### ISSUE TITLE
Cannot load queue

### ISSUE THREAD

**Issue by blastbeng** [Radarr/Radarr#6934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm clicking on the activity tab

### Expected Behavior

Torrents should show up

### Steps To Reproduce

I don't know... i did nothing, it just stopped working without editing any configuration

I searched on the web but i haven't found a solution after hours of googling. 

### Environment

```markdown
OS: Ubuntu
Radarr: version 3.2.2.5080
Docket Install: Yes
Using Reverse Proxy: No
Browser: Not UI related
```

### What branch are you running?

Master

### Trace Logs?

2022-01-14 21:41:59.1|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/queue/status

[v3.2.2.5080] System.ApplicationException: Expected query to return 3 rows but returned 0
   at NzbDrone.Core.Datastore.BasicRepository`1.Get(IEnumerable`1 ids) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 113
   at NzbDrone.Core.Movies.MovieService.GetMovies(IEnumerable`1 movieIds) in D:\a\1\s\src\NzbDrone.Core\Movies\MovieService.cs:line 83
   at NzbDrone.Core.Download.Pending.PendingReleaseService.IncludeRemoteMovies(List`1 releases, Dictionary`2 knownRemoteMovies) in D:\a\1\s\src\NzbDrone.Core\Download\Pending\PendingReleaseService.cs:line 271
   at NzbDrone.Core.Download.Pending.PendingReleaseService.GetPendingQueue() in D:\a\1\s\src\NzbDrone.Core\Download\Pending\PendingReleaseService.cs:line 160
   at Radarr.Api.V3.Queue.QueueStatusModule.GetQueueStatus() in D:\a\1\s\src\Radarr.Api.V3\Queue\QueueStatusModule.cs:line 42
   at Radarr.Api.V3.Queue.QueueStatusModule.GetQueueStatusResponse() in D:\a\1\s\src\Radarr.Api.V3\Queue\QueueStatusModule.cs:line 34
   at Radarr.Api.V3.Queue.QueueStatusModule.<.ctor>b__3_0(Object x) in D:\a\1\s\src\Radarr.Api.V3\Queue\QueueStatusModule.cs:line 29
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)

[AB#2366](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2366)

**Comment by bakerboy448** [comment]
Seems like more likely database corruption or a high IOWait than a bug.

also for future reference those are not trace logs; those are just the error spew.  The issue template has a link to the wiki for how to get and provide tracelogs
