### ISSUE TITLE
I can't use Radarr properly when i use Hijri date

### ISSUE THREAD

**Issue by NeverlandENR** [Radarr/Radarr#6995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to add Lists/Connections it gives me the message "Unable to add a new list, please try again.", Or "Unable to add a new notification, please try again.".
  I know its because the Hijri date, Because the Hijri date is in the year 1443 which is before 1900, I tried changing it to Gregorian date but the error is still there, And when I look it up in the events it says
"Microsoft.AspNetCore.Server.Kestrel
  Connection id "0HMF0K7954T8D", Request id "0HMF0K7954T8D:00000012": An unhandled exception was thrown by the application.: Specified time is not supported in this calendar. It should be between 04/30/1900 00:00:00 (Gregorian date) and 11/16/2077 23:59:59 (Gregorian date), inclusive. (Parameter 'time') Actual value was 0."

### Expected Behavior

I want to be able to add lists and connections for the notifications.

### Environment

```markdown
- OS: Windows 11 (22000.434)
- Radarr: 3.2.2.5080
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome Version 97.0.4692.99
```

### What branch are you running?

Master

### Trace Logs?

2022-01-26 11:00:39.0|Error|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HMF0K7954T81", Request id "0HMF0K7954T81:00000002": An unhandled exception was thrown by the application.

[v3.2.2.5080] System.ArgumentOutOfRangeException: Specified time is not supported in this calendar. It should be between 04/30/1900 00:00:00 (Gregorian date) and 11/16/2077 23:59:59 (Gregorian date), inclusive. (Parameter 'time')
Actual value was 0.
   at System.Globalization.UmAlQuraCalendar.CheckTicksRange(Int64 ticks)
   at System.Globalization.UmAlQuraCalendar.GetDatePart(DateTime time, Int32 part)
   at System.Globalization.UmAlQuraCalendar.GetYear(DateTime time)
   at System.DateTimeFormat.FormatCustomized(DateTime dateTime, ReadOnlySpan`1 format, DateTimeFormatInfo dtfi, TimeSpan offset, StringBuilder result)
   at System.DateTimeFormat.FormatStringBuilder(DateTime dateTime, ReadOnlySpan`1 format, DateTimeFormatInfo dtfi, TimeSpan offset)
   at System.DateTimeFormat.Format(DateTime dateTime, String format, IFormatProvider provider, TimeSpan offset)
   at NzbDrone.Common.Serializer.STJUtcConverter.Write(Utf8JsonWriter writer, DateTime value, JsonSerializerOptions options) in D:\a\1\s\src\NzbDrone.Common\Serializer\System.Text.Json\STJUtcConverter.cs:line 17
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.IEnumerableOfTConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, Type inputType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue value, JsonSerializerOptions options)
   at NzbDrone.Common.Serializer.STJson.Serialize[TModel](TModel model, Stream outputStream, JsonSerializerOptions options) in D:\a\1\s\src\NzbDrone.Common\Serializer\System.Text.Json\STJson.cs:line 84
   at Radarr.Http.Extensions.NancyJsonSerializer.Serialize[TModel](MediaRange contentType, TModel model, Stream outputStream) in D:\a\1\s\src\Radarr.Http\Extensions\NancyJsonSerializer.cs:line 26
   at Nancy.Responses.JsonResponse`1.<>c__DisplayClass6_0.<GetJsonContents>b__0(Stream stream)
   at Radarr.Http.Extensions.Pipelines.GzipCompressionPipeline.WriteGZipStream(Action`1 innerContent, Stream targetStream) in D:\a\1\s\src\Radarr.Http\Extensions\Pipelines\GZipPipeline.cs:line 76
   at Radarr.Http.Extensions.Pipelines.GzipCompressionPipeline.<>c__DisplayClass6_0.<CompressResponse>b__1(Stream responseStream) in D:\a\1\s\src\Radarr.Http\Extensions\Pipelines\GZipPipeline.cs:line 51
   at Nancy.Owin.NancyMiddleware.RequestComplete(NancyContext context, IDictionary`2 environment, Func`2 performPassThrough, Func`2 next)
   at Nancy.Owin.NancyMiddleware.<>c__DisplayClass2_1.<<UseNancy>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Owin.WebSocketAcceptAdapter.<>c__DisplayClass6_0.<<AdaptWebSockets>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Radarr.Host.Middleware.SignalRMiddleware.<Attach>b__7_0(HttpContext context, Func`1 next) in D:\a\1\s\src\NzbDrone.Host\WebHost\Middleware\SignalRMiddleware.cs:line 58
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

![Screenshot_26](https://user-images.githubusercontent.com/89540550/151127597-3e10fb99-bcb7-4d5e-9119-883dabe16168.png)
![Screenshot_27](https://user-images.githubusercontent.com/89540550/151127603-9426ffd0-79ef-4e0e-9c7a-acc4fdaa7a10.png)

**Comment by ta264** [comment]
I suspect some garbled data was written to the database when you had windows set to use Hijri date.

I think you'll have to delete you radarr database, and start again with everything set to Gregorian calendar.

**Comment by NeverlandENR** [comment]
> I suspect some garbled data was written to the database when you had windows set to use Hijri date.
> 
> 
> 
> I think you'll have to delete you radarr database, and start again with everything set to Gregorian calendar.

It was already Gregorian calendar i changed nothing.
 I tried to delete radarr and download it again, it worked for a little while then it gave me this exception again.

**Comment by ta264** [comment]
I don't understand.

I think your radarr database broke when you ran radarr with windows set to hijri date format. The only way to recover is to delete your radarr database and make sure radarr is never run with hijri date turned on

**Comment by Adam-Saeed** [comment]
for me it was just because my Gregorian calendar was in Arabic. I had to change it to an English Gregorian calendar and restart the app
