### ISSUE TITLE
IMDb List Failures - 'utf8' is not a supported encoding name

### ISSUE THREAD

**Issue by Eldoc62** [Radarr/Radarr#6996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,
I have a problem with the IMDB list which to date was still working fine.
My log is below.
I think there is a problem with Radarr because the .CSV downloads well and works well when I open it with Excel.
Thank you for your help

`2022-01-26 15:27:10.4|Debug|Api|[PUT] /api/v3/config/host: 202.Accepted (45 ms)
2022-01-26 15:27:10.6|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2022-01-26 15:27:10.6|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2022-01-26 15:27:26.2|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
2022-01-26 15:27:26.2|Debug|Api|[GET] /api/v3/command: 200.OK (0 ms)
2022-01-26 15:27:26.3|Debug|Api|[GET] /api/v3/queue/details: 200.OK (106 ms)
2022-01-26 15:27:37.3|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2022-01-26 15:27:37.3|Debug|Api|[GET] /api/v3/system/status: 200.OK (0 ms)
2022-01-26 15:27:37.4|Debug|Api|[GET] /api/v3/diskspace: 200.OK (19 ms)
2022-01-26 15:27:40.1|Debug|Api|[GET] /api/v3/importlist: 200.OK (3 ms)
2022-01-26 15:27:40.1|Debug|RootFolderService|Generating list of unmapped folders
2022-01-26 15:27:40.1|Debug|Api|[GET] /api/v3/config/importlist: 200.OK (0 ms)
2022-01-26 15:27:40.1|Debug|Api|[GET] /api/v3/exclusions: 200.OK (1 ms)
2022-01-26 15:27:40.1|Debug|RootFolderService|51 unmapped folders detected.
2022-01-26 15:27:40.1|Debug|Api|[GET] /api/v3/rootFolder: 200.OK (33 ms)
2022-01-26 15:27:43.0|Debug|IMDbListImport|Downloading List https://www.imdb.com/list/ls020180728/export
2022-01-26 15:27:43.5|Warn|IMDbListImport|Unable to connect to list

[v4.0.3.5879] System.ArgumentException: 'utf8' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
   at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at NzbDrone.Common.Http.HttpHeader.GetEncodingFromContentType(String contentType) in D:\a\1\s\src\NzbDrone.Common\Http\HttpHeader.cs:line 160
   at NzbDrone.Common.Http.HttpResponse.get_Content() in D:\a\1\s\src\NzbDrone.Common\Http\HttpResponse.cs:line 47
   at NzbDrone.Core.ImportLists.ImportListResponse.get_Content() in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListResponse.cs:line 22
   at NzbDrone.Core.ImportLists.RadarrList2.IMDbList.IMDbListParser.ParseResponse(ImportListResponse importListResponse) in D:\a\1\s\src\NzbDrone.Core\ImportLists\RadarrList2\IMDb\IMDbListParser.cs:line 35
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchPage(ImportListRequest request, IParseImportListResponse parser) in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 159
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 187

2022-01-26 15:27:43.5|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.0.3.5879] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to list, check the log for more details
   at Radarr.Api.V3.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 200
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 191
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 140
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2022-01-26 15:27:43.6|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to list, check the log for more details
2022-01-26 15:27:43.6|Debug|Api|[POST] /api/v3/importlist/test: 400.BadRequest (589 ms)
2022-01-26 15:27:46.3|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2022-01-26 15:27:46.3|Debug|Api|[GET] /api/v3/system/status: 200.OK (1 ms)
2022-01-26 15:27:46.3|Debug|Api|[GET] /api/v3/diskspace: 200.OK (20 ms)
2022-01-26 15:27:47.4|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)`

### Expected Behavior

Nok

### Environment

```markdown
Version
4.0.3.5879
.NET
Yes (6.0.1)
Migration de la base de données
206
Dossier AppData
/Volumes/HDD_1/.config/Radarr
Répertoire de démarrage
/Applications/Radarr.app/Contents/MacOS
Mode
Console
Durée de fonctionnent
```

### What branch are you running?

Master

### Trace Logs?

2022-01-26 15:27:10.4|Debug|Api|[PUT] /api/v3/config/host: 202.Accepted (45 ms)
2022-01-26 15:27:10.6|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2022-01-26 15:27:10.6|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2022-01-26 15:27:26.2|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
2022-01-26 15:27:26.2|Debug|Api|[GET] /api/v3/command: 200.OK (0 ms)
2022-01-26 15:27:26.3|Debug|Api|[GET] /api/v3/queue/details: 200.OK (106 ms)
2022-01-26 15:27:37.3|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2022-01-26 15:27:37.3|Debug|Api|[GET] /api/v3/system/status: 200.OK (0 ms)
2022-01-26 15:27:37.4|Debug|Api|[GET] /api/v3/diskspace: 200.OK (19 ms)
2022-01-26 15:27:40.1|Debug|Api|[GET] /api/v3/importlist: 200.OK (3 ms)
2022-01-26 15:27:40.1|Debug|RootFolderService|Generating list of unmapped folders
2022-01-26 15:27:40.1|Debug|Api|[GET] /api/v3/config/importlist: 200.OK (0 ms)
2022-01-26 15:27:40.1|Debug|Api|[GET] /api/v3/exclusions: 200.OK (1 ms)
2022-01-26 15:27:40.1|Debug|RootFolderService|51 unmapped folders detected.
2022-01-26 15:27:40.1|Debug|Api|[GET] /api/v3/rootFolder: 200.OK (33 ms)
2022-01-26 15:27:43.0|Debug|IMDbListImport|Downloading List https://www.imdb.com/list/ls020180728/export
2022-01-26 15:27:43.5|Warn|IMDbListImport|Unable to connect to list

[v4.0.3.5879] System.ArgumentException: 'utf8' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
   at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at NzbDrone.Common.Http.HttpHeader.GetEncodingFromContentType(String contentType) in D:\a\1\s\src\NzbDrone.Common\Http\HttpHeader.cs:line 160
   at NzbDrone.Common.Http.HttpResponse.get_Content() in D:\a\1\s\src\NzbDrone.Common\Http\HttpResponse.cs:line 47
   at NzbDrone.Core.ImportLists.ImportListResponse.get_Content() in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListResponse.cs:line 22
   at NzbDrone.Core.ImportLists.RadarrList2.IMDbList.IMDbListParser.ParseResponse(ImportListResponse importListResponse) in D:\a\1\s\src\NzbDrone.Core\ImportLists\RadarrList2\IMDb\IMDbListParser.cs:line 35
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchPage(ImportListRequest request, IParseImportListResponse parser) in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 159
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 187

2022-01-26 15:27:43.5|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.0.3.5879] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to list, check the log for more details
   at Radarr.Api.V3.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 200
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 191
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 140
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2022-01-26 15:27:43.6|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to list, check the log for more details
2022-01-26 15:27:43.6|Debug|Api|[POST] /api/v3/importlist/test: 400.BadRequest (589 ms)
2022-01-26 15:27:46.3|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2022-01-26 15:27:46.3|Debug|Api|[GET] /api/v3/system/status: 200.OK (1 ms)
2022-01-26 15:27:46.3|Debug|Api|[GET] /api/v3/diskspace: 200.OK (20 ms)
2022-01-26 15:27:47.4|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)

[AB#2504](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2504)

**Comment by bakerboy448** [comment]
Not a Radarr bug.

It's an IMDb bug

they're giving this header: content-type: text/csv;charset=utf8

utf8 is not a valid charset

http://www.iana.org/assignments/character-sets/character-sets.xhtml

**Comment by ta264** [comment]
IMDB changed their HTTP response to include the header 
```
content-type: text/csv;charset=utf8
```

This is not a valid charset:

<http://www.iana.org/assignments/character-sets/character-sets.xhtml>

Reported to IMDB here:
https://community-imdb.sprinklr.com/conversations/imdbcom/lists-started-returning-incorrect-encoding-today/61f155e49ae52c4a67525fee

I'll leave this open until they fix the issue so people can track it.

**Comment by Eldoc62** [comment]
as much for me :)

Thank you for your answer, I love radarr and the work you do

**Comment by bakerboy448** [comment]
- This only impacts IMDb lists using the Export list function to bypass the cache.
- IMDb lists that are added normally and do not use the Exported (CSV) list should not be impacted by this.

**Comment by ta264** [comment]
I believe IMDB have resolved this now
