### ISSUE TITLE
Update from 3.2.2.5080 to 4.0.4.5922 fails on Ubuntu server 20.04

### ISSUE THREAD

**Issue by fcmircea** [Radarr/Radarr#7026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Updating from 3.2.2.5080 to 4.0.4.5922 fails on Ubuntu server 20.04

Update is offered via interface

log:

```
2022-02-12 04:24:29.5|Info|UpdateApp|Starting Radarr Update Client
2022-02-12 04:24:29.7|Info|AppFolderInfo|Data directory is being overridden to [/media/Radarr.data]
2022-02-12 04:24:29.7|Debug|UpdateApp|NzbDrone process ID: 2900
2022-02-12 04:24:29.7|Debug|UpdateApp|Arguments:
2022-02-12 04:24:29.7|Debug|UpdateApp|  2900
2022-02-12 04:24:29.7|Debug|UpdateApp|  /tmp/radarr_update
2022-02-12 04:24:29.7|Debug|UpdateApp|  /media/Radarr/Radarr
2022-02-12 04:24:29.7|Debug|UpdateApp|  /data=/media/Radarr.data
2022-02-12 04:24:29.7|Debug|UpdateApp|  /nobrowser
2022-02-12 04:24:29.7|Debug|UpdateApp|Using executing application: /media/Radarr/Radarr
2022-02-12 04:24:29.7|Debug|UpdateApp|Executable location: /media/Radarr/Radarr
2022-02-12 04:24:29.7|Info|InstallUpdateService|Installation Folder: /media/Radarr
2022-02-12 04:24:29.7|Info|InstallUpdateService|Updating Radarr from version (unknown) to version 4.0.4.5922
2022-02-12 04:24:29.7|Info|InstallUpdateService|Verifying requirements before update...
2022-02-12 04:24:29.7|Debug|ProcessProvider|Finding process with Id:2900
2022-02-12 04:24:29.7|Fatal|UpdateApp|An error has occurred while applying update package.

[v4.0.4.5922] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Common.Processes.ProcessProvider.GetExeFileName(Process process) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 329
   at NzbDrone.Common.Processes.ProcessProvider.ConvertToProcessInfo(Process process) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 312
   at NzbDrone.Common.Processes.ProcessProvider.GetProcessById(Int32 id) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 74
   at NzbDrone.Common.Processes.ProcessProvider.Exists(Int32 processId) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 57
   at NzbDrone.Update.UpdateEngine.InstallUpdateService.Verify(String targetFolder, Int32 processId) in D:\a\1\s\src\NzbDrone.Update\UpdateEngine\InstallUpdateService.cs:line 74
   at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start(String installationFolder, Int32 processId) in D:\a\1\s\src\NzbDrone.Update\UpdateEngine\InstallUpdateService.cs:line 91
   at NzbDrone.Update.UpdateApp.Start(String[] args) in D:\a\1\s\src\NzbDrone.Update\UpdateApp.cs:line 59
   at NzbDrone.Update.UpdateApp.Main(String[] args) in D:\a\1\s\src\NzbDrone.Update\UpdateApp.cs:line 44
```

### Expected Behavior

Update should work automatically.

### Steps To Reproduce

Click "install latest"
Notice the Error Log

### Environment

```markdown
- OS: Ubuntu 20.04
- Radarr: 3.2.2.5080
- Docker Install:no
- Using Reverse Proxy:
- Browser: Firefox
```

### What branch are you running?

Master

### Trace Logs?

```
2022-02-12 04:29:20.4|Info|UpdateApp|Starting Radarr Update Client
2022-02-12 04:29:20.6|Info|AppFolderInfo|Data directory is being overridden to [/media/Radarr.data]
2022-02-12 04:29:20.6|Debug|UpdateApp|NzbDrone process ID: 4170597
2022-02-12 04:29:20.6|Debug|UpdateApp|Arguments:
2022-02-12 04:29:20.6|Debug|UpdateApp|  4170597
2022-02-12 04:29:20.6|Debug|UpdateApp|  /tmp/radarr_update
2022-02-12 04:29:20.6|Debug|UpdateApp|  /media/Radarr/Radarr
2022-02-12 04:29:20.6|Debug|UpdateApp|  /data=/media/Radarr.data
2022-02-12 04:29:20.6|Debug|UpdateApp|  /nobrowser
2022-02-12 04:29:20.6|Debug|UpdateApp|Using executing application: /media/Radarr/Radarr
2022-02-12 04:29:20.6|Debug|UpdateApp|Executable location: /media/Radarr/Radarr
2022-02-12 04:29:20.6|Info|InstallUpdateService|Installation Folder: /media/Radarr
2022-02-12 04:29:20.6|Info|InstallUpdateService|Updating Radarr from version (unknown) to version 4.0.4.5922
2022-02-12 04:29:20.6|Info|InstallUpdateService|Verifying requirements before update...
2022-02-12 04:29:20.6|Debug|ProcessProvider|Finding process with Id:4170597
2022-02-12 04:29:20.6|Fatal|UpdateApp|An error has occurred while applying update package.

[v4.0.4.5922] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Common.Processes.ProcessProvider.GetExeFileName(Process process) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 329
   at NzbDrone.Common.Processes.ProcessProvider.ConvertToProcessInfo(Process process) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 312
   at NzbDrone.Common.Processes.ProcessProvider.GetProcessById(Int32 id) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 74
   at NzbDrone.Common.Processes.ProcessProvider.Exists(Int32 processId) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 57
   at NzbDrone.Update.UpdateEngine.InstallUpdateService.Verify(String targetFolder, Int32 processId) in D:\a\1\s\src\NzbDrone.Update\UpdateEngine\InstallUpdateService.cs:line 74
   at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start(String installationFolder, Int32 processId) in D:\a\1\s\src\NzbDrone.Update\UpdateEngine\InstallUpdateService.cs:line 91
   at NzbDrone.Update.UpdateApp.Start(String[] args) in D:\a\1\s\src\NzbDrone.Update\UpdateApp.cs:line 59
   at NzbDrone.Update.UpdateApp.Main(String[] args) in D:\a\1\s\src\NzbDrone.Update\UpdateApp.cs:line 44
```

[AB#2570](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2570)

**Comment by milesizzo** [comment]
I also tried to update via the web interface (3.2.2.5080 to 4.0.4.5922) but had slightly different errors. It feels related so I'll post it here (If this needs to be a separate issue I'm happy to move it):
```
2022-02-14 05:45:52.3|Debug|DiskTransferService|Copy [/tmp/radarr_update/Radarr/Microsoft.AspNetCore.Routing.Abstractions.dll] > [/opt/Radarr/Microsoft.AspNetCore.Routing.Abstractions.dll]
2022-02-14 05:45:52.3|Debug|DiskTransferService|Copy [/tmp/radarr_update/Radarr/Microsoft.AspNetCore.Diagnostics.Abstractions.dll] > [/opt/Radarr/Microsoft.AspNetCore.Diagnostics.Abstractions.dll]
2022-02-14 05:45:52.3|Debug|DiskTransferService|Copy [/tmp/radarr_update/Radarr/Microsoft.AspNetCore.Mvc.Formatters.Xml.dll] > [/opt/Radarr/Microsoft.AspNetCore.Mvc.Formatters.Xml.dll]
2022-02-14 05:45:52.3|Debug|DiskTransferService|Rolling back file copy [/tmp/radarr_update/Radarr/Microsoft.AspNetCore.Mvc.Formatters.Xml.dll] to [/opt/Radarr/Microsoft.AspNetCore.Mvc.Formatters.Xml.dll].
2022-02-14 05:45:55.3|Error|InstallUpdateService|Failed to copy upgrade package to target folder.

[v4.0.4.5922] System.InvalidOperationException: Path doesn't exist!
   at Mono.Unix.UnixFileSystemInfo.AssertValid()
   at NzbDrone.Mono.Disk.DiskProvider.CopyFileInternal(String source, String destination, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskProviderBase.CopyFile(String source, String destination, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskTransferService.TryCopyFileVerified(String sourcePath, String targetPath, Int64 originalSize)
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskTransferService.MirrorFolder(String sourcePath, String targetPath)
   at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start(String installationFolder, Int32 processId)


2022-02-14 05:45:55.4|Info|BackupAndRestore|Attempting to rollback upgrade
2022-02-14 05:45:55.4|Debug|DiskTransferService|Mirror Folder [/tmp/radarr_update/radarr_backup/] > [/opt/Radarr]
2022-02-14 05:45:55.4|Info|TerminateNzbDrone|Killing all running processes
2022-02-14 05:45:55.4|Debug|ProcessProvider|Found 0 processes with the name: Radarr.Console
2022-02-14 05:45:55.4|Debug|ProcessProvider|Found 0 processes to kill
2022-02-14 05:45:55.4|Debug|ProcessProvider|Found 1 processes with the name: Radarr
2022-02-14 05:45:55.4|Debug|ProcessProvider| - [197176] Radarr
2022-02-14 05:45:55.4|Debug|ProcessProvider|Found 1 processes to kill
2022-02-14 05:45:55.4|Debug|ProcessProvider|Killing process: 197176 [Radarr]
2022-02-14 05:45:55.4|Info|ProcessProvider|[197176]: Killing process
2022-02-14 05:45:55.4|Info|ProcessProvider|[197176]: Waiting for exit
2022-02-14 05:45:55.4|Info|ProcessProvider|[197176]: Process terminated successfully
2022-02-14 05:45:55.4|Warn|ProcessProvider|Cannot find process with id: 197176
2022-02-14 05:45:55.4|Info|InstallUpdateService|Waiting for external auto-restart.
2022-02-14 05:45:56.4|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2022-02-14 05:45:57.4|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2022-02-14 05:45:58.4|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2022-02-14 05:45:59.5|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2022-02-14 05:46:00.5|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2022-02-14 05:46:01.5|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2022-02-14 05:46:02.5|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2022-02-14 05:46:03.5|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2022-02-14 05:46:04.5|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2022-02-14 05:46:05.5|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2022-02-14 05:46:05.5|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2022-02-14 05:46:05.5|Info|StartNzbDrone|Starting Radarr
2022-02-14 05:46:05.5|Info|StartNzbDrone|Starting Radarr
2022-02-14 05:46:05.5|Debug|ProcessProvider|Starting /opt/Radarr/Radarr /data=/var/lib/radarr /nobrowser
2022-02-14 05:46:05.5|Fatal|UpdateApp|An error has occurred while applying update package.

[v4.0.4.5922] System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmp/radarr_update/radarr_backup'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.GetDirectories()
   at NzbDrone.Common.Disk.DiskProviderBase.GetDirectoryInfos(String path)
   at NzbDrone.Common.Disk.DiskTransferService.MirrorFolder(String sourcePath, String targetPath)
   at NzbDrone.Update.UpdateEngine.BackupAndRestore.Restore(String target)
   at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start(String installationFolder, Int32 processId)
   at NzbDrone.Update.UpdateApp.Start(String[] args)
   at NzbDrone.Update.UpdateApp.Main(String[] args)
```
This has left me with a completely broken Radarr (and Prowlarr, but I'll post separately over there).

**Comment by bakerboy448** [comment]
@milesizzo That looks to be a different issue and appears to be that your tmp dir was cleaned up mid-backup

The OP has an issue around the updater and getting the process logic

**Comment by fcmircea** [comment]
I have resorted to a manual  update, overwriting the folder from the archive.

**Comment by bakerboy448** [comment]
Closing; no additional nor recent reports and the process logic has been refactored with further v4 versions 

Can reopen if additional reports occur
