### ISSUE TITLE
Can't Connect my IMDBLIST watchlist to Rdarr 

### ISSUE THREAD

**Issue by Sylrob434** [Radarr/Radarr#7028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When adding my IMDB list to radarr I received an unexpected error

### Expected Behavior

N/A

### Steps To Reproduce

Simply go to the list section in the setting of Radarr and try to add your own IMDB list

### Environment

```markdown
- OS: Running under QNAP didn't verify the linux distro
- Radarr:4.0.4.5922
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: Chrome 8.0.4758.82 (Build officiel) (64 bits)
```

### What branch are you running?

Master

### Trace Logs?

2022-02-12 13:08:11.9|Warn|IMDbListImport|Unable to connect to list

[v4.0.4.5922] NzbDrone.Core.ImportLists.Exceptions.ImportListException: Radarr API call resulted in an unexpected StatusCode [NotFound]
   at NzbDrone.Core.ImportLists.RadarrList2.RadarrList2Parser.PreProcess(ImportListResponse listResponse) in D:\a\1\s\src\NzbDrone.Core\ImportLists\RadarrList2\RadarrList2Parser.cs:line 39
   at NzbDrone.Core.ImportLists.RadarrList2.IMDbList.IMDbListParser.ParseResponse(ImportListResponse importListResponse) in D:\a\1\s\src\NzbDrone.Core\ImportLists\RadarrList2\IMDb\IMDbListParser.cs:line 27
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchPage(ImportListRequest request, IParseImportListResponse parser) in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 159
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 187

2022-02-12 13:08:11.9|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.0.4.5922] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to list. Radarr API call resulted in an unexpected StatusCode [NotFound]
   at Radarr.Api.V3.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 200
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 191
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 140
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2022-02-12 13:08:11.9|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to list. Radarr API call resulted in an unexpected StatusCode [NotFound]

**Comment by Sylrob434** [comment]
Found the problem Sorry my fault list wasn't public !
