### ISSUE TITLE
Skyhook Error Code 1020 | Server in Germany | URL Works with curl

### ISSUE THREAD

**Issue by MikeeI** [Radarr/Radarr#7133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cloudflare and Code 1020 ... i know blocking of Russian IPs, but Server is from a big hoster in germany. Curl works.
Cleared DB, Complete Wipe and new install. Same behavior. 

When searching for a movie i get this 

```
2022-03-15 04:11:07.0|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.0.5.5981] NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for 'Movies' failed. Invalid response received from TMDb.
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: e. Path '', line 0, position 0. (Json snippet '<--error-->error code: 1020')
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: e. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in D:\a\1\s\src\NzbDrone.Common\Serializer\Newtonsoft.Json\Json.cs:line 44
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in D:\a\1\s\src\NzbDrone.Common\Serializer\Newtonsoft.Json\Json.cs:line 48
   at NzbDrone.Common.Http.HttpResponse`1..ctor(HttpResponse response) in D:\a\1\s\src\NzbDrone.Common\Http\HttpResponse.cs:line 101
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 290
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 431
   --- End of inner exception stack trace ---
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 448
   at lambda_method330(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

```
curl https://radarrapi.servarr.com/v1/search?q=10%2Bminutes%2Bgone&year=2019
```
 
On the same server gives me a nice JSON 

### Expected Behavior

Output of movies

### Environment

```markdown
- OS: Ubuntu 20.04
- Radarr: 4.0.5.5981
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome 99
```

### What branch are you running?

Master

### Trace Logs?

```
2022-03-15 04:33:35.9|Trace|EventAggregator|ConfigFileSavedEvent <~ ReconfigureLogging
2022-03-15 04:33:35.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-03-15 04:33:35.9|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2022-03-15 04:33:35.9|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2022-03-15 04:33:35.9|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2022-03-15 04:33:35.9|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2022-03-15 04:33:35.9|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2022-03-15 04:33:35.9|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2022-03-15 04:33:35.9|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2022-03-15 04:33:35.9|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2022-03-15 04:33:35.9|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-03-15 04:33:35.9|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2022-03-15 04:33:35.9|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2022-03-15 04:33:35.9|Trace|EventAggregator|ConfigSavedEvent ~> LocalizationService
2022-03-15 04:33:35.9|Trace|EventAggregator|ConfigSavedEvent ~> TaskManager
2022-03-15 04:33:35.9|Trace|EventAggregator|ConfigSavedEvent <~ LocalizationService
2022-03-15 04:33:35.9|Trace|Http|Res: 457 [PUT] /api/v3/config/host: 202.Accepted (12 ms)
2022-03-15 04:33:35.9|Debug|Api|[PUT] /api/v3/config/host: 202.Accepted (12 ms)
2022-03-15 04:33:35.9|Trace|ConfigService|Using default config value for 'importlistsyncinterval' defaultValue:'24'
2022-03-15 04:33:35.9|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2022-03-15 04:33:35.9|Trace|ConfigService|Using default config value for 'checkforfinisheddownloadinterval' defaultValue:'1'
2022-03-15 04:33:35.9|Trace|EventAggregator|ConfigSavedEvent <~ TaskManager
2022-03-15 04:33:35.9|Trace|HttpClient|Res: [GET] https://radarr.servarr.com/v1/update/master?version=4.0.5.5981&os=linux&arch=X64&runtime=netcore&runtimeVer=6.0.1: 403.Forbidden
error code: 1020 (84 ms)
2022-03-15 04:33:35.9|Warn|HttpClient|HTTP Error - Res: [GET] https://radarr.servarr.com/v1/update/master?version=4.0.5.5981&os=linux&arch=X64&runtime=netcore&runtimeVer=6.0.1: 403.Forbidden
error code: 1020
2022-03-15 04:33:35.9|Error|TaskExtensions|Task Error

[v4.0.5.5981] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [GET] at [https://radarr.servarr.com/v1/update/master?version=4.0.5.5981&os=linux&arch=X64&runtime=netcore&runtimeVer=6.0.1]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 101
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 282
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 288
   at NzbDrone.Core.Update.UpdatePackageProvider.GetLatestUpdate(String branch, Version currentVersion) in D:\a\1\s\src\NzbDrone.Core\Update\UpdatePackageProvider.cs:line 49
   at NzbDrone.Core.Update.CheckUpdateService.AvailableUpdate() in D:\a\1\s\src\NzbDrone.Core\Update\UpdateCheckService.cs:line 25
   at NzbDrone.Core.HealthCheck.Checks.UpdateCheck.Check() in D:\a\1\s\src\NzbDrone.Core\HealthCheck\Checks\UpdateCheck.cs:line 71
   at NzbDrone.Core.HealthCheck.HealthCheckService.<>c.<PerformHealthCheck>b__12_0(IProvideHealthCheck c) in D:\a\1\s\src\NzbDrone.Core\HealthCheck\HealthCheckService.cs:line 75
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at NzbDrone.Core.HealthCheck.HealthCheckService.PerformHealthCheck(IProvideHealthCheck[] healthChecks) in D:\a\1\s\src\NzbDrone.Core\HealthCheck\HealthCheckService.cs:line 75
   at NzbDrone.Core.HealthCheck.HealthCheckService.HandleAsync(IEvent message) in D:\a\1\s\src\NzbDrone.Core\HealthCheck\HealthCheckService.cs:line 133
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
error code: 1020


2022-03-15 04:33:36.0|Trace|HttpClient|Res: [GET] https://radarr.servarr.com/v1/notification?version=4.0.5.5981&os=linux&arch=X64&runtime=netcore&branch=master: 403.Forbidden
error code: 1020 (141 ms)
2022-03-15 04:33:36.0|Warn|HttpClient|HTTP Error - Res: [GET] https://radarr.servarr.com/v1/notification?version=4.0.5.5981&os=linux&arch=X64&runtime=netcore&branch=master: 403.Forbidden
error code: 1020
2022-03-15 04:33:36.0|Error|ServerSideNotificationService|Failed to retrieve server notifications

[v4.0.5.5981] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [GET] at [https://radarr.servarr.com/v1/notification?version=4.0.5.5981&os=linux&arch=X64&runtime=netcore&branch=master]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 101
   at NzbDrone.Core.HealthCheck.ServerSideNotificationService.GetServerChecks() in D:\a\1\s\src\NzbDrone.Core\HealthCheck\ServerSideNotificationService.cs:line 47
error code: 1020


2022-03-15 04:33:36.0|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2022-03-15 04:33:36.0|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2022-03-15 04:33:36.0|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2022-03-15 04:33:36.0|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2022-03-15 04:33:36.0|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2022-03-15 04:33:36.0|Trace|Http|Req: 458 [GET] /api/v3/health (from 172.*.*.30)
2022-03-15 04:33:36.0|Trace|Http|Res: 458 [GET] /api/v3/health: 200.OK (2 ms)
2022-03-15 04:33:36.0|Debug|Api|[GET] /api/v3/health: 200.OK (2 ms)
2022-03-15 04:33:38.0|Trace|Http|Req: 459 [GET] /api/v3/health (from 172.*.*.30)
2022-03-15 04:33:38.0|Trace|Http|Res: 459 [GET] /api/v3/health: 200.OK (0 ms)
2022-03-15 04:33:38.0|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2022-03-15 04:33:38.0|Trace|Http|Req: 460 [GET] /api/v3/diskspace (from 172.*.*.64)
2022-03-15 04:33:38.0|Trace|Http|Req: 461 [GET] /api/v3/system/status (from 172.*.*.210)
2022-03-15 04:33:38.0|Trace|Http|Res: 461 [GET] /api/v3/system/status: 200.OK (1 ms)
2022-03-15 04:33:38.0|Debug|Api|[GET] /api/v3/system/status: 200.OK (1 ms)
2022-03-15 04:33:38.4|Trace|Http|Req: 462 [POST] /signalr/messages?access_token=(removed)&id=w18Bp9CE-x6KNObOGHy9UQ (from 172.*.*.210)
2022-03-15 04:33:38.4|Trace|Http|Res: 462 [POST] /signalr/messages?access_token=(removed)&id=w18Bp9CE-x6KNObOGHy9UQ: 200.OK (0 ms)
2022-03-15 04:33:38.6|Trace|Http|Res: 460 [GET] /api/v3/diskspace: 200.OK (596 ms)
2022-03-15 04:33:38.6|Debug|Api|[GET] /api/v3/diskspace: 200.OK (596 ms)
2022-03-15 04:33:40.1|Trace|Http|Req: 463 [GET] /api/v3/config/host (from 172.*.*.210)
2022-03-15 04:33:40.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-03-15 04:33:40.1|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2022-03-15 04:33:40.1|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2022-03-15 04:33:40.1|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2022-03-15 04:33:40.1|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2022-03-15 04:33:40.1|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2022-03-15 04:33:40.1|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2022-03-15 04:33:40.1|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2022-03-15 04:33:40.1|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2022-03-15 04:33:40.1|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-03-15 04:33:40.1|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2022-03-15 04:33:40.1|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2022-03-15 04:33:40.1|Trace|Http|Res: 463 [GET] /api/v3/config/host: 200.OK (3 ms)
2022-03-15 04:33:40.1|Debug|Api|[GET] /api/v3/config/host: 200.OK (3 ms)
2022-03-15 04:33:40.1|Trace|Http|Req: 464 [GET] /api/v3/update (from 172.*.*.64)
2022-03-15 04:33:40.1|Trace|HttpClient|Req: [GET] https://radarr.servarr.com/v1/update/master/changes?version=4.0.5.5981&os=linux&arch=X64&runtime=netcore&runtimeVer=6.0.1&prevVersion=3.2.2.5080
2022-03-15 04:33:40.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-03-15 04:33:40.1|Trace|HttpClient|Res: [GET] https://radarr.servarr.com/v1/update/master/changes?version=4.0.5.5981&os=linux&arch=X64&runtime=netcore&runtimeVer=6.0.1&prevVersion=3.2.2.5080: 403.Forbidden
error code: 1020 (22 ms)
2022-03-15 04:33:40.1|Warn|HttpClient|HTTP Error - Res: [GET] https://radarr.servarr.com/v1/update/master/changes?version=4.0.5.5981&os=linux&arch=X64&runtime=netcore&runtimeVer=6.0.1&prevVersion=3.2.2.5080: 403.Forbidden
error code: 1020
2022-03-15 04:33:40.2|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.0.5.5981] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [GET] at [https://radarr.servarr.com/v1/update/master/changes?version=4.0.5.5981&os=linux&arch=X64&runtime=netcore&runtimeVer=6.0.1&prevVersion=3.2.2.5080]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 101
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 282
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 288
   at NzbDrone.Core.Update.UpdatePackageProvider.GetRecentUpdates(String branch, Version currentVersion, Version previousVersion) in D:\a\1\s\src\NzbDrone.Core\Update\UpdatePackageProvider.cs:line 81
   at NzbDrone.Core.Update.RecentUpdateProvider.GetRecentUpdatePackages() in D:\a\1\s\src\NzbDrone.Core\Update\RecentUpdateProvider.cs:line 34
   at Radarr.Api.V3.Update.UpdateController.GetRecentUpdates() in D:\a\1\s\src\Radarr.Api.V3\Update\UpdateController.cs:line 27
   at lambda_method382(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
error code: 1020


2022-03-15 04:33:40.2|Trace|RadarrErrorPipeline|Handling Exception
2022-03-15 04:33:40.2|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/update

[v4.0.5.5981] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [GET] at [https://radarr.servarr.com/v1/update/master/changes?version=4.0.5.5981&os=linux&arch=X64&runtime=netcore&runtimeVer=6.0.1&prevVersion=3.2.2.5080]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 101
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 282
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 288
   at NzbDrone.Core.Update.UpdatePackageProvider.GetRecentUpdates(String branch, Version currentVersion, Version previousVersion) in D:\a\1\s\src\NzbDrone.Core\Update\UpdatePackageProvider.cs:line 81
   at NzbDrone.Core.Update.RecentUpdateProvider.GetRecentUpdatePackages() in D:\a\1\s\src\NzbDrone.Core\Update\RecentUpdateProvider.cs:line 34
   at Radarr.Api.V3.Update.UpdateController.GetRecentUpdates() in D:\a\1\s\src\Radarr.Api.V3\Update\UpdateController.cs:line 27
   at lambda_method382(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
error code: 1020


2022-03-15 04:33:40.2|Trace|Http|Res: 464 [GET] /api/v3/update: 500.InternalServerError (58 ms)
2022-03-15 04:33:40.2|Debug|Api|[GET] /api/v3/update: 500.InternalServerError (58 ms)
2022-03-15 04:33:41.1|Trace|Http|Req: 465 [GET] /api/v3/log?page=1&pageSize=50&sortDirection=descending&sortKey=time (from 172.*.*.64)
2022-03-15 04:33:41.1|Trace|Http|Res: 465 [GET] /api/v3/log?page=1&pageSize=50&sortDirection=descending&sortKey=time: 200.OK (4 ms)
2022-03-15 04:33:41.1|Debug|Api|[GET] /api/v3/log?page=1&pageSize=50&sortDirection=descending&sortKey=time: 200.OK (4 ms)
2022-03-15 04:33:43.1|Trace|Http|Req: 466 [POST] /api/v3/command (from 172.*.*.64)
2022-03-15 04:33:43.1|Trace|CommandQueueManager|Publishing ClearLog
2022-03-15 04:33:43.1|Trace|CommandQueueManager|Checking if command is queued or started: ClearLog
2022-03-15 04:33:43.1|Trace|CommandQueueManager|Inserting new command: ClearLog
2022-03-15 04:33:43.1|Trace|CommandExecutor|ClearLogCommand -> LogService
2022-03-15 04:33:43.1|Trace|CommandQueueManager|Marking command as started: ClearLog
2022-03-15 04:33:43.1|Trace|Http|Res: 466 [POST] /api/v3/command: 201.Created (5 ms)
2022-03-15 04:33:43.1|Debug|Api|[POST] /api/v3/command: 201.Created (5 ms)
2022-03-15 04:33:43.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-03-15 04:33:43.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2022-03-15 04:33:43.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2022-03-15 04:33:43.1|Info|Database|Vacuuming Log database
2022-03-15 04:33:43.1|Info|Database|Log database compressed
2022-03-15 04:33:43.1|Trace|CommandQueueManager|Updating command status
2022-03-15 04:33:43.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-03-15 04:33:43.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2022-03-15 04:33:43.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2022-03-15 04:33:43.1|Trace|EventAggregator|Publishing CommandExecutedEvent
2022-03-15 04:33:43.1|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2022-03-15 04:33:43.1|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2022-03-15 04:33:43.1|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2022-03-15 04:33:43.1|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2022-03-15 04:33:43.1|Trace|CommandExecutor|ClearLogCommand <- LogService [00:00:00.0068439]
2022-03-15 04:33:43.1|Trace|Http|Req: 467 [GET] /api/v3/command (from 172.*.*.64)
2022-03-15 04:33:43.1|Trace|CommandQueueManager|Getting all commands
2022-03-15 04:33:43.1|Trace|Http|Res: 467 [GET] /api/v3/command: 200.OK (1 ms)
2022-03-15 04:33:43.1|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
2022-03-15 04:33:43.5|Trace|Scheduler|Pending Tasks: 1
2022-03-15 04:33:43.5|Trace|CommandQueueManager|Publishing RefreshMonitoredDownloads
2022-03-15 04:33:43.5|Trace|CommandQueueManager|Checking if command is queued or started: RefreshMonitoredDownloads
2022-03-15 04:33:43.5|Trace|CommandQueueManager|Inserting new command: RefreshMonitoredDownloads
2022-03-15 04:33:43.5|Trace|CommandExecutor|RefreshMonitoredDownloadsCommand -> DownloadMonitoringService
2022-03-15 04:33:43.5|Trace|CommandQueueManager|Marking command as started: RefreshMonitoredDownloads
```

[AB#2793](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2793)

**Comment by bakerboy448** [comment]
https://support.cloudflare.com/hc/en-us/articles/200168236-Configuring-Cloudflare-IP-Geolocation#12345683

**Comment by MikeeI** [comment]
> https://support.cloudflare.com/hc/en-us/articles/200168236-Configuring-Cloudflare-IP-Geolocation#12345683
> 
> Seems Maxmind's database has some DE IPs as BY or RU

Thank you. Got it fixed via Maxmind and their support Page.
Strange problem that even as Radarr could not connect curl could.

By the way, thank you for working on Radarr.
