### ISSUE TITLE
Add support for 4-letter language code in Movie Folder Format

### ISSUE THREAD

**Issue by carvsal** [Radarr/Radarr#7138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am attempting to set the `Movie Folder Format` (`Media Management` > `Movie Naming`) setting to `{Movie Title:pt-BR} ({Release Year})` so that movie folders are named with their Brazilian Portuguese titles.

Unable to save my changes to that field due to an error: `Must contain movie title`

I am able to save my changes if `Movie Folder Format` is set to `{Movie Title:pt} ({Release Year})` but that ends up naming the movie folders with their European Portuguese titles (which often differ greatly from their Brazilian Portuguese counterparts).

### Expected Behavior

I would like to be able to have movie folders with their Brazilian Portuguese titles (pt-BR).

### Environment

```markdown
- OS: Debian Bullseye
- Radarr: 4.0.5.5981
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome 99
```

### What branch are you running?

Master

### Trace Logs?

```
2022-03-17 18:36:57.3|Trace|Http|Res: 717 [GET] /api/v3/config/mediamanagement: 200.OK (326 ms)
2022-03-17 18:36:57.3|Debug|Api|[GET] /api/v3/config/mediamanagement: 200.OK (326 ms)
2022-03-17 18:37:03.3|Trace|Scheduler|Pending Tasks: 0
2022-03-17 18:37:04.1|Trace|Http|Req: 719 [GET] /api/v3/config/naming/examples?renameMovies=false&replaceIllegalCharacters=true&colonReplacementFormat=delete&standardMovieFormat=%7BMovie%20Title%7D%20(%7BRelease%20Year%7D)%20%7BQuality%20Full%7D&movieFolderFormat=%7BMovie%20Title%3Apt-BR%7D%20(%7BRelease%20Year%7D)&includeQuality=false&replaceSpaces=false&id=1 (from 10.0.0.3)
2022-03-17 18:37:04.1|Debug|MediaInfoFormatter|Unknown video format: '' in 'The.Movie.Title.2010.1080p.BluRay.DTS.x264-EVOLVE'.
2022-03-17 18:37:04.1|Debug|MediaInfoFormatter|Unknown audio format: '' in 'The.Movie.Title.2010.1080p.BluRay.DTS.x264-EVOLVE'.
2022-03-17 18:37:04.1|Trace|Http|Res: 719 [GET] /api/v3/config/naming/examples?renameMovies=false&replaceIllegalCharacters=true&colonReplacementFormat=delete&standardMovieFormat=%7BMovie%20Title%7D%20(%7BRelease%20Year%7D)%20%7BQuality%20Full%7D&movieFolderFormat=%7BMovie%20Title%3Apt-BR%7D%20(%7BRelease%20Year%7D)&includeQuality=false&replaceSpaces=false&id=1: 200.OK (73 ms)
2022-03-17 18:37:04.2|Debug|Api|[GET] /api/v3/config/naming/examples?renameMovies=false&replaceIllegalCharacters=true&colonReplacementFormat=delete&standardMovieFormat=%7BMovie%20Title%7D%20(%7BRelease%20Year%7D)%20%7BQuality%20Full%7D&movieFolderFormat=%7BMovie%20Title%3Apt-BR%7D%20(%7BRelease%20Year%7D)&includeQuality=false&replaceSpaces=false&id=1: 200.OK (73 ms)
2022-03-17 18:37:05.3|Trace|Http|Req: 720 [PUT] /api/v3/config/mediamanagement (from 10.0.0.3)
2022-03-17 18:37:05.3|Trace|Http|Req: 721 [PUT] /api/v3/config/naming (from 10.0.0.3)
2022-03-17 18:37:05.3|Trace|ConfigService|Using default config value for 'autounmonitorpreviouslydownloadedmovies' defaultValue:'False'
2022-03-17 18:37:05.3|Trace|ConfigService|Using default config value for 'retention' defaultValue:'0'
2022-03-17 18:37:05.4|Trace|ConfigService|Using default config value for 'recyclebin' defaultValue:''
2022-03-17 18:37:05.4|Trace|ConfigService|Using default config value for 'recyclebincleanupdays' defaultValue:'7'
2022-03-17 18:37:05.4|Trace|ConfigService|Using default config value for 'rsssyncinterval' defaultValue:'60'
2022-03-17 18:37:05.4|Trace|ConfigService|Using default config value for 'availabilitydelay' defaultValue:'0'
2022-03-17 18:37:05.4|Trace|ConfigService|Using default config value for 'importlistsyncinterval' defaultValue:'24'
2022-03-17 18:37:05.3|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.0.5.5981] FluentValidation.ValidationException: Validation failed: 
 -- MovieFolderFormat: Must contain movie title
   at Radarr.Http.REST.RestController`1.ValidateResource(TResource resource, Boolean skipValidate, Boolean skipSharedValidate) in D:\a\1\s\src\Radarr.Http\REST\RestController.cs:line 113
   at Radarr.Http.REST.RestController`1.OnActionExecuting(ActionExecutingContext context) in D:\a\1\s\src\Radarr.Http\REST\RestController.cs:line 72
   at Microsoft.AspNetCore.Mvc.Controller.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-03-17 18:37:05.4|Trace|ConfigService|Using default config value for 'listsynclevel' defaultValue:'disabled'
2022-03-17 18:37:05.4|Trace|RadarrErrorPipeline|Handling Exception
2022-03-17 18:37:05.4|Trace|ConfigService|Using default config value for 'importexclusions' defaultValue:''
2022-03-17 18:37:05.5|Trace|ConfigService|Using default config value for 'maximumsize' defaultValue:'0'
2022-03-17 18:37:05.4|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- MovieFolderFormat: Must contain movie title
2022-03-17 18:37:05.5|Trace|ConfigService|Using default config value for 'minimumage' defaultValue:'0'
2022-03-17 18:37:05.5|Trace|ConfigService|Using default config value for 'downloadpropersandrepacks' defaultValue:'PreferAndUpgrade'
2022-03-17 18:37:05.5|Trace|Http|Res: 721 [PUT] /api/v3/config/naming: 400.BadRequest (197 ms)
2022-03-17 18:37:05.5|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'
2022-03-17 18:37:05.5|Debug|Api|[PUT] /api/v3/config/naming: 400.BadRequest (197 ms)
2022-03-17 18:37:05.5|Trace|ConfigService|Using default config value for 'preferindexerflags' defaultValue:'False'
2022-03-17 18:37:05.5|Trace|ConfigService|Using default config value for 'allowhardcodedsubs' defaultValue:'False'
2022-03-17 18:37:05.5|Trace|ConfigService|Using default config value for 'whitelistedhardcodedsubs' defaultValue:''
2022-03-17 18:37:05.6|Trace|ConfigService|Using default config value for 'autoredownloadfailed' defaultValue:'True'
2022-03-17 18:37:05.6|Trace|ConfigService|Using default config value for 'createemptymoviefolders' defaultValue:'False'
2022-03-17 18:37:05.6|Trace|ConfigService|Using default config value for 'deleteemptyfolders' defaultValue:'False'
2022-03-17 18:37:05.6|Trace|ConfigService|Using default config value for 'filedate' defaultValue:'None'
2022-03-17 18:37:05.6|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
2022-03-17 18:37:05.6|Trace|ConfigService|Using default config value for 'checkforfinisheddownloadinterval' defaultValue:'1'
2022-03-17 18:37:05.6|Trace|ConfigService|Using default config value for 'downloadclienthistorylimit' defaultValue:'60'
2022-03-17 18:37:05.6|Trace|ConfigService|Using default config value for 'skipfreespacecheckwhenimporting' defaultValue:'False'
2022-03-17 18:37:05.6|Trace|ConfigService|Using default config value for 'minimumfreespacewhenimporting' defaultValue:'100'
2022-03-17 18:37:05.6|Trace|ConfigService|Using default config value for 'copyusinghardlinks' defaultValue:'True'
2022-03-17 18:37:05.6|Trace|ConfigService|Using default config value for 'enablemediainfo' defaultValue:'True'
2022-03-17 18:37:05.6|Trace|ConfigService|Using default config value for 'importextrafiles' defaultValue:'False'
2022-03-17 18:37:05.6|Trace|ConfigService|Using default config value for 'extrafileextensions' defaultValue:'srt'
2022-03-17 18:37:05.6|Trace|ConfigService|Using default config value for 'autorenamefolders' defaultValue:'False'
2022-03-17 18:37:05.6|Trace|ConfigService|Using default config value for 'rescanafterrefresh' defaultValue:'Always'
2022-03-17 18:37:05.7|Trace|ConfigService|Using default config value for 'setpermissionslinux' defaultValue:'False'
2022-03-17 18:37:05.7|Trace|ConfigService|Using default config value for 'chmodfolder' defaultValue:'755'
2022-03-17 18:37:05.7|Trace|ConfigService|Using default config value for 'chowngroup' defaultValue:''
2022-03-17 18:37:05.7|Trace|ConfigService|Using default config value for 'firstdayofweek' defaultValue:'0'
2022-03-17 18:37:05.7|Trace|ConfigService|Using default config value for 'calendarweekcolumnheader' defaultValue:'ddd M/D'
2022-03-17 18:37:05.7|Trace|ConfigService|Using default config value for 'movieruntimeformat' defaultValue:'HoursMinutes'
2022-03-17 18:37:05.7|Trace|ConfigService|Using default config value for 'shortdateformat' defaultValue:'MMM D YYYY'
2022-03-17 18:37:05.7|Trace|ConfigService|Using default config value for 'longdateformat' defaultValue:'dddd, MMMM D YYYY'
2022-03-17 18:37:05.7|Trace|ConfigService|Using default config value for 'timeformat' defaultValue:'h(:mm)a'
2022-03-17 18:37:05.7|Trace|ConfigService|Using default config value for 'showrelativedates' defaultValue:'True'
2022-03-17 18:37:05.7|Trace|ConfigService|Using default config value for 'enablecolorimpairedmode' defaultValue:'False'
2022-03-17 18:37:05.7|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-03-17 18:37:05.7|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2022-03-17 18:37:05.7|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2022-03-17 18:37:05.8|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2022-03-17 18:37:05.8|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2022-03-17 18:37:05.8|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2022-03-17 18:37:05.8|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2022-03-17 18:37:05.8|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2022-03-17 18:37:05.8|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-03-17 18:37:05.8|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2022-03-17 18:37:05.8|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2022-03-17 18:37:05.8|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2022-03-17 18:37:05.8|Trace|EventAggregator|Publishing ConfigSavedEvent
```

[AB#2803](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2803)

**Comment by xlucasfelix** [comment]
Any updates on this?

**Comment by Qstick** [comment]
No
