### ISSUE TITLE
Access was denied from Belarus region by cloudflare. Movie search and other services not working.

### ISSUE THREAD

**Issue by nick-petrovsky** [Radarr/Radarr#7185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Index page from radarr.video (different ISP, white IP addresses):

You do not have access to radarr.video.
The site owner may have set restrictions that prevent you from accessing the site. Contact the site owner for access or try loading the page again.

Please describe which regions are blocked, thank you in advance.

### Expected Behavior

Normal operation

### Steps To Reproduce

`$ curl radarr.video`
error code: 1020%

`$ curl https://radarr.servarr.com/v1/time`
error code: 1020%

### Environment

```markdown
- OS: Ubuntu 20.04
- Radarr: Radarr 3.0.1.4259
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: any
```

### What branch are you running?

Master

### Trace Logs?

2022-04-05 11:28:29.0|Info|RssSyncService|Starting RSS Sync
2022-04-05 11:28:30.1|Info|DownloadDecisionMaker|Processing 189 releases
2022-04-05 11:28:30.7|Info|RssSyncService|RSS Sync Completed. Reports found: 189, Reports grabbed: 0
2022-04-05 11:31:59.7|Warn|HttpClient|HTTP Error - Res: [GET] https://radarr.servarr.com/v1/time: 403.Forbidden
error code: 1020
2022-04-05 11:31:59.8|Error|CommandExecutor|Error occurred while executing task CheckHealth

[v4.0.5.5981] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [GET] at [https://radarr.servarr.com/v1/time]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 101
   at NzbDrone.Core.HealthCheck.Checks.SystemTimeCheck.Check() in D:\a\1\s\src\NzbDrone.Core\HealthCheck\Checks\SystemTimeCheck.cs:line 30
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at NzbDrone.Core.HealthCheck.HealthCheckService.PerformHealthCheck(IProvideHealthCheck[] healthChecks) in D:\a\1\s\src\NzbDrone.Core\HealthCheck\HealthCheckService.cs:line 75
   at NzbDrone.Core.HealthCheck.HealthCheckService.Execute(CheckHealthCommand message) in D:\a\1\s\src\NzbDrone.Core\HealthCheck\HealthCheckService.cs:line 108
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 113
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44
error code: 1020

[AB#2908](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2908)

**Comment by RobinDadswell** [comment]
Due to the current actions of Russia and Belarus access from those regions is denied.
