### ISSUE TITLE
Failed List Sync is treated as a successful sync for Library Clean

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#7194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If a list sync fails - even for a SQL logic error - and a user has clean library enabled. Radarr incorrectly treats the sync as successful and removes every movie from the library.

### Expected Behavior

A failed list sync should not be treated as a successful sync and cause a library cleanup

### Steps To Reproduce

1. Have Radarr connected to a Radarr via list sync
2. Have library clean enabled
3. List sync fails
4. See all movies removed 

### Environment

```markdown
- OS: agnostic
- Radarr: v4.1.0.6144
- Docker Install: agnostic
- Using Reverse Proxy: agnostic
- Browser: agnostic
```

### What branch are you running?

Other (This issue will be closed)

### Trace Logs?

```
2022-04-05 22:47:57.1|Error|FetchAndParseImportListService|Error during Import List Sync for list Radarr

[v4.1.0.6144] code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
no such column: Popularity
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 563
   at NzbDrone.Core.Datastore.BasicRepository`1.UpdateFields(IDbConnection connection, IDbTransaction transaction, IList`1 models, List`1 propertiesToUpdate) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 396
   at NzbDrone.Core.Datastore.BasicRepository`1.UpdateMany(IList`1 models) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 244
   at NzbDrone.Core.Movies.ArtistMetadataRepository.UpsertMany(List`1 data) in D:\a\1\s\src\NzbDrone.Core\Movies\MovieMetadataRepository.cs:line 64
   at NzbDrone.Core.Movies.MovieMetadataService.Upsert(MovieMetadata movie) in D:\a\1\s\src\NzbDrone.Core\Movies\MovieMetadataService.cs:line 34
   at NzbDrone.Core.ImportLists.FetchAndParseImportListService.MapMovieReport(ImportListMovie report) in D:\a\1\s\src\NzbDrone.Core\ImportLists\FetchAndParseImportListService.cs:line 181
   at NzbDrone.Core.ImportLists.FetchAndParseImportListService.<FetchSingleList>b__8_0(ImportListMovie x) in D:\a\1\s\src\NzbDrone.Core\ImportLists\FetchAndParseImportListService.cs:line 155
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at NzbDrone.Core.ImportLists.FetchAndParseImportListService.FetchSingleList(ImportListDefinition definition) in D:\a\1\s\src\NzbDrone.Core\ImportLists\FetchAndParseImportListService.cs:line 153


2022-04-05 22:47:57.2|Debug|FetchAndParseImportListService|Found 0 reports for list Radarr
```

[AB#2924](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2924)

**Comment by pablorodriguezzurro** [comment]
Still happening on Synology NAS 😕

**Comment by bakerboy448** [comment]
Synology NAS is not a valid Radarr version; given SynoComm's frequent delays in updates when the new master lands with this fix, you'll likely have to deal with this bug for many months or a year+ after.

this looks like it was fixed with https://github.com/radarr/Radarr/commit/bd1844030d8af2941af234391cfe5117c194ccc5

which is in develop - 4.7.0.7588
