### ISSUE TITLE
Radarr not updating after update to DSM 7.1, still runs, update fails

### ISSUE THREAD

**Issue by synofan** [Radarr/Radarr#7227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After backup, update is supposed to start, Fail
Log:
 2022-4-15 12:11:35.8|Info|InstallUpdateService|Deleting old update files
2022-4-15 12:11:35.8|Info|InstallUpdateService|Downloading update 4.1.0.6175
2022-4-15 12:11:37.7|Info|InstallUpdateService|Verifying update package
2022-4-15 12:11:38.1|Info|InstallUpdateService|Update package verified successfully
2022-4-15 12:11:38.1|Info|InstallUpdateService|Extracting Update package
2022-4-15 12:11:43.9|Info|InstallUpdateService|Update package extracted successfully
2022-4-15 12:11:43.9|Info|BackupService|Starting Backup
2022-4-15 12:11:43.9|Info|InstallUpdateService|Preparing client
2022-4-15 12:11:44.7|Info|InstallUpdateService|Starting update client /tmp/radarr_update/Radarr.Update
2022-4-15 12:11:44.7|Info|InstallUpdateService|Radarr will restart shortly.
2022-4-15 12:11:44.7|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

[v3.0.2.4552] System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NzbDrone.Common.Processes.ProcessProvider.Start(String path, String args, StringDictionary environmentVariables, Action`1 onOutputDataReceived, Action`1 onErrorDataReceived) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 188
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 160
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 276
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 88
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44

### Expected Behavior

good update

### Environment

```markdown
- OS: DSM 7.1
- Radarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Master

### Trace Logs?

2022-4-15 12:11:35.8|Info|InstallUpdateService|Deleting old update files
2022-4-15 12:11:35.8|Info|InstallUpdateService|Downloading update 4.1.0.6175
2022-4-15 12:11:37.7|Info|InstallUpdateService|Verifying update package
2022-4-15 12:11:38.1|Info|InstallUpdateService|Update package verified successfully
2022-4-15 12:11:38.1|Info|InstallUpdateService|Extracting Update package
2022-4-15 12:11:43.9|Info|InstallUpdateService|Update package extracted successfully
2022-4-15 12:11:43.9|Info|BackupService|Starting Backup
2022-4-15 12:11:43.9|Info|InstallUpdateService|Preparing client
2022-4-15 12:11:44.7|Info|InstallUpdateService|Starting update client /tmp/radarr_update/Radarr.Update
2022-4-15 12:11:44.7|Info|InstallUpdateService|Radarr will restart shortly.
2022-4-15 12:11:44.7|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

[v3.0.2.4552] System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NzbDrone.Common.Processes.ProcessProvider.Start(String path, String args, StringDictionary environmentVariables, Action`1 onOutputDataReceived, Action`1 onErrorDataReceived) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 188
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 160
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 276
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 88
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44

[AB#2997](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2997)

**Comment by GamerGun** [comment]
Same here,

```
System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/tmp/radarr_update/Radarr.Update' with working directory '/'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NzbDrone.Common.Processes.ProcessProvider.Start(String path, String args, StringDictionary environmentVariables, Action`1 onOutputDataReceived, Action`1 onErrorDataReceived) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 185
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 166
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 283
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 113
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44
```

Although i can see the files being unpacked under /tmp/radarr_update so there seems to be no perm issue with /tmp ...

**Comment by synofan** [comment]
Yes Package works fine but updates fail

**Comment by ta264** [comment]
If any of you want to help get to the bottom of this please come by the discord channel

**Comment by synofan** [comment]
Nope its a bug, not a feature, worked fine on DSM 7.01 after upgrade to DSM 7.1 its broken. or am i missing something.

**Comment by bakerboy448** [comment]
It's likely not a bug given nothing would have changed in Radarr to cause permission issues which has nothing to do with the Radarr app itself. No known issues with DSM 7.1.

Given you're on 3.0.2 - your SynoCommunity created, maintained, and supported Radarr package is significantly out of date - I believe they have a 3.2.2 or 3.1 as their base package from Oct 2021 or so. Your native package is missing various bug fixes that fixed their broken package on several NASes due to /tmp being too small.

As Ta said, for further support and debugging, come by discord.

**Comment by synofan** [comment]
Yes, tried to repair under virtual DSM 7.1 with older version via new download after completely erasing package, then reinstall from synocommunity.

Not saying you did anything….Synology did…again.

 

Greets Synofan

 

Van: bakerboy448 ***@***.***> 
Verzonden: vrijdag 15 april 2022 14:44
Aan: Radarr/Radarr ***@***.***>
CC: synofan ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Radarr/Radarr] Radarr not updating after update to DSM 7.1, still runs, update fails (Issue #7227)

 

It's likely not a bug given nothing would have changed in Radarr to cause permission issues which has nothing to do with the Radarr app itself. No known issues with DSM 7.1.

Given you're on 3.0.2 - your SynoCommunity created, maintained, and supported Radarr package is significantly out of date - I believe they have a 3.2.2 or 3.1 as their base package from Oct 2021 or so. Your native package is missing various bug fixes that fixed their broken package on several NASes due to /tmp being too small.

As Ta said, for further support and debugging, come by discord.

**Comment by synofan** [comment]
ofcourse i am not going to break my still running not updating version 4.0.5.5981 on the actual NAS

**Comment by ta264** [comment]
This is resolved in the "official" images we are trialling here: https://github.com/Servarr/spksrc/releases
