### ISSUE TITLE
Database update fails on upgrade

### ISSUE THREAD

**Issue by scphantm** [Radarr/Radarr#7249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the updator fails

### Expected Behavior

i expect it to update the db correctly

### Steps To Reproduce

My system is designed to bring down develop.  It started doing this this morning after an update.  Currently, the service won't start at all.

### Environment

```markdown
- OS: win
- Radarr: dev
- Docker Install: no
- Using Reverse Proxy: no
- Browser: chrome
```

### What branch are you running?

Develop

### Trace Logs?

```
2022-04-25 12:56:43.3|Info|Bootstrap|Starting Radarr - D:\ProgramFiles\Radarr\Radarr.Console.exe - Version 4.2.0.6229
2022-04-25 12:56:46.3|Info|MigrationController|*** Migrating data source=C:\ProgramData\Radarr\radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2022-04-25 12:56:46.7|Info|FluentMigrator.Runner.MigrationRunner|207: movie_metadata migrating
2022-04-25 12:56:46.7|Info|NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor|Beginning Transaction
2022-04-25 12:56:46.7|Info|movie_metadata|Starting migration of Main DB to 207
2022-04-25 12:56:46.7|Info|FluentMigrator.Runner.MigrationRunner|CreateTable MovieMetadata
2022-04-25 12:56:46.7|Info|NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor|CREATE TABLE "MovieMetadata" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "TmdbId" INTEGER NOT NULL, "ImdbId" TEXT, "Images" TEXT NOT NULL, "Genres" TEXT, "Title" TEXT NOT NULL, "SortTitle" TEXT, "CleanTitle" TEXT, "OriginalTitle" TEXT, "CleanOriginalTitle" TEXT, "OriginalLanguage" INTEGER NOT NULL, "Status" INTEGER NOT NULL, "LastInfoSync" DATETIME, "Runtime" INTEGER NOT NULL, "InCinemas" DATETIME, "PhysicalRelease" DATETIME, "DigitalRelease" DATETIME, "Year" INTEGER, "SecondaryYear" INTEGER, "Ratings" TEXT, "Recommendations" TEXT NOT NULL, "Certification" TEXT, "YouTubeTrailerId" TEXT, "Collection" TEXT, "Studio" TEXT, "Overview" TEXT, "Website" TEXT, "Popularity" NUMERIC)
2022-04-25 12:56:46.7|Info|FluentMigrator.Runner.MigrationRunner|=> 0.0489484s
2022-04-25 12:56:46.7|Info|FluentMigrator.Runner.MigrationRunner|CreateIndex MovieMetadata (TmdbId)
2022-04-25 12:56:46.7|Info|NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor|CREATE UNIQUE INDEX "IX_MovieMetadata_TmdbId" ON "MovieMetadata" ("TmdbId" ASC)
2022-04-25 12:56:46.7|Info|FluentMigrator.Runner.MigrationRunner|=> 0.0029041s
2022-04-25 12:56:46.7|Info|FluentMigrator.Runner.MigrationRunner|CreateIndex MovieMetadata (CleanTitle)
2022-04-25 12:56:46.7|Info|NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor|CREATE INDEX "IX_MovieMetadata_CleanTitle" ON "MovieMetadata" ("CleanTitle" ASC)
2022-04-25 12:56:46.7|Info|FluentMigrator.Runner.MigrationRunner|=> 0.0021123s
2022-04-25 12:56:46.8|Info|FluentMigrator.Runner.MigrationRunner|CreateIndex MovieMetadata (CleanOriginalTitle)
2022-04-25 12:56:46.8|Info|NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor|CREATE INDEX "IX_MovieMetadata_CleanOriginalTitle" ON "MovieMetadata" ("CleanOriginalTitle" ASC)
2022-04-25 12:56:46.8|Info|FluentMigrator.Runner.MigrationRunner|=> 0.0019824s
2022-04-25 12:56:46.8|Info|FluentMigrator.Runner.MigrationRunner|ExecuteSqlStatement INSERT INTO "MovieMetadata" ("TmdbId", "ImdbId", "Title", "SortTitle", "CleanTitle", "OriginalTitle", "CleanOriginalTitle", "OriginalLanguage", "Overview", "Status", "LastInfoSync", "Images", "Genres", "Ratings", "Runtime", "InCinemas", "PhysicalRelease", "DigitalRelease", "Year", "SecondaryYear", "Recommendations", "Certification", "YouTubeTrailerId", "Studio", "Collection", "Website")
                          SELECT "TmdbId", "ImdbId", "Title", "SortTitle", "CleanTitle", "OriginalTitle", "CleanTitle", "OriginalLanguage", "Overview", "Status", "LastInfoSync", "Images", "Genres", "Ratings", "Runtime", "InCinemas", "PhysicalRelease", "DigitalRelease", "Year", "SecondaryYear", "Recommendations", "Certification", "YouTubeTrailerId", "Studio", "Collection", "Website"
                          FROM "Movies"
2022-04-25 12:56:46.8|Info|NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor|INSERT INTO "MovieMetadata" ("TmdbId", "ImdbId", "Title", "SortTitle", "CleanTitle", "OriginalTitle", "CleanOriginalTitle", "OriginalLanguage", "Overview", "Status", "LastInfoSync", "Images", "Genres", "Ratings", "Runtime", "InCinemas", "PhysicalRelease", "DigitalRelease", "Year", "SecondaryYear", "Recommendations", "Certification", "YouTubeTrailerId", "Studio", "Collection", "Website")
                          SELECT "TmdbId", "ImdbId", "Title", "SortTitle", "CleanTitle", "OriginalTitle", "CleanTitle", "OriginalLanguage", "Overview", "Status", "LastInfoSync", "Images", "Genres", "Ratings", "Runtime", "InCinemas", "PhysicalRelease", "DigitalRelease", "Year", "SecondaryYear", "Recommendations", "Certification", "YouTubeTrailerId", "Studio", "Collection", "Website"
                          FROM "Movies"
2022-04-25 12:56:46.8|Info|FluentMigrator.Runner.MigrationRunner|=> 0.0516439s
2022-04-25 12:56:46.8|Info|FluentMigrator.Runner.MigrationRunner|ExecuteSqlStatement INSERT INTO "MovieMetadata" ("TmdbId", "ImdbId", "Title", "SortTitle", "CleanTitle", "OriginalTitle", "CleanOriginalTitle", "OriginalLanguage", "Overview", "Status", "LastInfoSync", "Images", "Genres", "Ratings", "Runtime", "InCinemas", "PhysicalRelease", "DigitalRelease", "Year", "Recommendations", "Certification", "YouTubeTrailerId", "Studio", "Collection", "Website")
                          SELECT DISTINCT "TmdbId", "ImdbId", "Title", "SortTitle", "Title", "OriginalTitle", "OriginalTitle", 1, "Overview", "Status", "LastInfoSync", "Images", "Genres", "Ratings", "Runtime", "InCinemas", "PhysicalRelease", "DigitalRelease", "Year", '[]', "Certification", "YouTubeTrailerId", "Studio", "Collection", "Website"
                          FROM "ImportListMovies"
                          WHERE "ImportListMovies"."TmdbId" NOT IN ( SELECT "MovieMetadata"."TmdbId" FROM "MovieMetadata" )
2022-04-25 12:56:46.8|Info|NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor|INSERT INTO "MovieMetadata" ("TmdbId", "ImdbId", "Title", "SortTitle", "CleanTitle", "OriginalTitle", "CleanOriginalTitle", "OriginalLanguage", "Overview", "Status", "LastInfoSync", "Images", "Genres", "Ratings", "Runtime", "InCinemas", "PhysicalRelease", "DigitalRelease", "Year", "Recommendations", "Certification", "YouTubeTrailerId", "Studio", "Collection", "Website")
                          SELECT DISTINCT "TmdbId", "ImdbId", "Title", "SortTitle", "Title", "OriginalTitle", "OriginalTitle", 1, "Overview", "Status", "LastInfoSync", "Images", "Genres", "Ratings", "Runtime", "InCinemas", "PhysicalRelease", "DigitalRelease", "Year", '[]', "Certification", "YouTubeTrailerId", "Studio", "Collection", "Website"
                          FROM "ImportListMovies"
                          WHERE "ImportListMovies"."TmdbId" NOT IN ( SELECT "MovieMetadata"."TmdbId" FROM "MovieMetadata" )
2022-04-25 12:56:47.5|Error|FluentMigrator.Runner.MigrationRunner|constraint failed
UNIQUE constraint failed: MovieMetadata.TmdbId
While Processing:
"INSERT INTO "MovieMetadata" ("TmdbId", "ImdbId", "Title", "SortTitle", "CleanTitle", "OriginalTitle", "CleanOriginalTitle", "OriginalLanguage", "Overview", "Status", "LastInfoSync", "Images", "Genres", "Ratings", "Runtime", "InCinemas", "PhysicalRelease", "DigitalRelease", "Year", "Recommendations", "Certification", "YouTubeTrailerId", "Studio", "Collection", "Website")
                          SELECT DISTINCT "TmdbId", "ImdbId", "Title", "SortTitle", "Title", "OriginalTitle", "OriginalTitle", 1, "Overview", "Status", "LastInfoSync", "Images", "Genres", "Ratings", "Runtime", "InCinemas", "PhysicalRelease", "DigitalRelease", "Year", '[]', "Certification", "YouTubeTrailerId", "Studio", "Collection", "Website"
                          FROM "ImportListMovies"
                          WHERE "ImportListMovies"."TmdbId" NOT IN ( SELECT "MovieMetadata"."TmdbId" FROM "MovieMetadata" )"

[v4.2.0.6229] System.Exception: constraint failed
UNIQUE constraint failed: MovieMetadata.TmdbId
While Processing:
"INSERT INTO "MovieMetadata" ("TmdbId", "ImdbId", "Title", "SortTitle", "CleanTitle", "OriginalTitle", "CleanOriginalTitle", "OriginalLanguage", "Overview", "Status", "LastInfoSync", "Images", "Genres", "Ratings", "Runtime", "InCinemas", "PhysicalRelease", "DigitalRelease", "Year", "Recommendations", "Certification", "YouTubeTrailerId", "Studio", "Collection", "Website")
                          SELECT DISTINCT "TmdbId", "ImdbId", "Title", "SortTitle", "Title", "OriginalTitle", "OriginalTitle", 1, "Overview", "Status", "LastInfoSync", "Images", "Genres", "Ratings", "Runtime", "InCinemas", "PhysicalRelease", "DigitalRelease", "Year", '[]', "Certification", "YouTubeTrailerId", "Studio", "Collection", "Website"
                          FROM "ImportListMovies"
                          WHERE "ImportListMovies"."TmdbId" NOT IN ( SELECT "MovieMetadata"."TmdbId" FROM "MovieMetadata" )"
 ---> code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
UNIQUE constraint failed: MovieMetadata.TmdbId
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   --- End of inner exception stack trace ---
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(String sql)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Execute(String template, Object[] args)
   at FluentMigrator.Runner.Processors.ProcessorBase.Execute(String sql)
   at FluentMigrator.Expressions.ExecuteSqlStatementExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass80_0.<ExecuteExpressions>b__1()
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)


2022-04-25 12:56:48.0|Info|NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor|Rolling back transaction
2022-04-25 12:56:48.4|Fatal|Microsoft.AspNetCore.Hosting.Diagnostics|Application startup exception

[v4.2.0.6229] NzbDrone.Common.Exceptions.RadarrStartupException: Radarr failed to start: Error creating main database
 ---> System.Exception: constraint failed
UNIQUE constraint failed: MovieMetadata.TmdbId
While Processing:
"INSERT INTO "MovieMetadata" ("TmdbId", "ImdbId", "Title", "SortTitle", "CleanTitle", "OriginalTitle", "CleanOriginalTitle", "OriginalLanguage", "Overview", "Status", "LastInfoSync", "Images", "Genres", "Ratings", "Runtime", "InCinemas", "PhysicalRelease", "DigitalRelease", "Year", "Recommendations", "Certification", "YouTubeTrailerId", "Studio", "Collection", "Website")
                          SELECT DISTINCT "TmdbId", "ImdbId", "Title", "SortTitle", "Title", "OriginalTitle", "OriginalTitle", 1, "Overview", "Status", "LastInfoSync", "Images", "Genres", "Ratings", "Runtime", "InCinemas", "PhysicalRelease", "DigitalRelease", "Year", '[]', "Certification", "YouTubeTrailerId", "Studio", "Collection", "Website"
                          FROM "ImportListMovies"
                          WHERE "ImportListMovies"."TmdbId" NOT IN ( SELECT "MovieMetadata"."TmdbId" FROM "MovieMetadata" )"
 ---> code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
UNIQUE constraint failed: MovieMetadata.TmdbId
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   --- End of inner exception stack trace ---
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(String sql)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Execute(String template, Object[] args)
   at FluentMigrator.Runner.Processors.ProcessorBase.Execute(String sql)
   at FluentMigrator.Expressions.ExecuteSqlStatementExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass80_0.<ExecuteExpressions>b__1()
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
   at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions)
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp()
   at NzbDrone.Core.Datastore.Migration.Framework.MigrationController.Migrate(String connectionString, MigrationContext migrationContext) in D:\a\1\s\src\NzbDrone.Core\Datastore\Migration\Framework\MigrationController.cs:line 79
   at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in D:\a\1\s\src\NzbDrone.Core\Datastore\DbFactory.cs:line 114
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in D:\a\1\s\src\NzbDrone.Core\Datastore\DbFactory.cs:line 129
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationContext migrationContext) in D:\a\1\s\src\NzbDrone.Core\Datastore\DbFactory.cs:line 69
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationType migrationType) in D:\a\1\s\src\NzbDrone.Core\Datastore\DbFactory.cs:line 57
   at NzbDrone.Core.Datastore.Extensions.CompositionExtensions.<>c.<AddDatabase>b__0_0(IDbFactory f) in D:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\CompositionExtensions.cs:line 10
   at DryIoc.Interpreter.TryInterpretAndUnwrapContainerException(IResolverContext r, Expression expr, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 2953
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /_/src/DryIoc/Container.cs:line 10633
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 10535
   at DryIoc.Container.ResolveAndCacheKeyed(Int32 serviceTypeHash, Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Object scopeName, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 513
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 441
   at DryIoc.Interpreter.InterpretResolveMethod(IResolverContext resolver, IList`1 callArgs, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3716
   at DryIoc.Interpreter.TryInterpretMethodCall(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3594
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3108
   at DryIoc.Interpreter.TryInterpretNestedLambdaBodyAndUnwrapException(IResolverContext r, Expression bodyExpr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec) in /_/src/DryIoc/Container.cs:line 3412
   at DryIoc.Interpreter.<>c__DisplayClass3_0.<TryInterpretNestedLambda>b__0() in /_/src/DryIoc/Container.cs:line 3301
   at DryIoc.Interpreter.<>c__DisplayClass5_0`1.<ConvertFunc>b__0() in /_/src/DryIoc/Container.cs:line 3422
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at NzbDrone.Host.Startup.Configure(IApplicationBuilder app, IStartupContext startupContext, Lazy`1 mainDatabaseFactory, Lazy`1 logDatabaseFactory, DatabaseTarget dbTarget, ISingleInstancePolicy singleInstancePolicy, InitializeLogger initializeLogger, ReconfigureLogging reconfigureLogging, IAppFolderFactory appFolderFactory, IProvidePidFile pidFileProvider, IConfigFileProvider configFileProvider, IRuntimeInfo runtimeInfo, IFirewallAdapter firewallAdapter, RadarrErrorPipeline errorHandler) in D:\a\1\s\src\NzbDrone.Host\Startup.cs:line 230
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)


2022-04-25 12:56:48.6|Fatal|ConsoleApp|EPIC FAIL!

[v4.2.0.6229] NzbDrone.Common.Exceptions.RadarrStartupException: Radarr failed to start: Error creating main database
 ---> System.Exception: constraint failed
UNIQUE constraint failed: MovieMetadata.TmdbId
While Processing:
"INSERT INTO "MovieMetadata" ("TmdbId", "ImdbId", "Title", "SortTitle", "CleanTitle", "OriginalTitle", "CleanOriginalTitle", "OriginalLanguage", "Overview", "Status", "LastInfoSync", "Images", "Genres", "Ratings", "Runtime", "InCinemas", "PhysicalRelease", "DigitalRelease", "Year", "Recommendations", "Certification", "YouTubeTrailerId", "Studio", "Collection", "Website")
                          SELECT DISTINCT "TmdbId", "ImdbId", "Title", "SortTitle", "Title", "OriginalTitle", "OriginalTitle", 1, "Overview", "Status", "LastInfoSync", "Images", "Genres", "Ratings", "Runtime", "InCinemas", "PhysicalRelease", "DigitalRelease", "Year", '[]', "Certification", "YouTubeTrailerId", "Studio", "Collection", "Website"
                          FROM "ImportListMovies"
                          WHERE "ImportListMovies"."TmdbId" NOT IN ( SELECT "MovieMetadata"."TmdbId" FROM "MovieMetadata" )"
 ---> code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
UNIQUE constraint failed: MovieMetadata.TmdbId
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   --- End of inner exception stack trace ---
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(String sql)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Execute(String template, Object[] args)
   at FluentMigrator.Runner.Processors.ProcessorBase.Execute(String sql)
   at FluentMigrator.Expressions.ExecuteSqlStatementExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass80_0.<ExecuteExpressions>b__1()
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
   at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions)
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp()
   at NzbDrone.Core.Datastore.Migration.Framework.MigrationController.Migrate(String connectionString, MigrationContext migrationContext) in D:\a\1\s\src\NzbDrone.Core\Datastore\Migration\Framework\MigrationController.cs:line 79
   at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in D:\a\1\s\src\NzbDrone.Core\Datastore\DbFactory.cs:line 114
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in D:\a\1\s\src\NzbDrone.Core\Datastore\DbFactory.cs:line 129
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationContext migrationContext) in D:\a\1\s\src\NzbDrone.Core\Datastore\DbFactory.cs:line 69
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationType migrationType) in D:\a\1\s\src\NzbDrone.Core\Datastore\DbFactory.cs:line 57
   at NzbDrone.Core.Datastore.Extensions.CompositionExtensions.<>c.<AddDatabase>b__0_0(IDbFactory f) in D:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\CompositionExtensions.cs:line 10
   at DryIoc.Interpreter.TryInterpretAndUnwrapContainerException(IResolverContext r, Expression expr, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 2953
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /_/src/DryIoc/Container.cs:line 10633
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 10535
   at DryIoc.Container.ResolveAndCacheKeyed(Int32 serviceTypeHash, Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Object scopeName, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 513
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 441
   at DryIoc.Interpreter.InterpretResolveMethod(IResolverContext resolver, IList`1 callArgs, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3716
   at DryIoc.Interpreter.TryInterpretMethodCall(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3594
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3108
   at DryIoc.Interpreter.TryInterpretNestedLambdaBodyAndUnwrapException(IResolverContext r, Expression bodyExpr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec) in /_/src/DryIoc/Container.cs:line 3412
   at DryIoc.Interpreter.<>c__DisplayClass3_0.<TryInterpretNestedLambda>b__0() in /_/src/DryIoc/Container.cs:line 3301
   at DryIoc.Interpreter.<>c__DisplayClass5_0`1.<ConvertFunc>b__0() in /_/src/DryIoc/Container.cs:line 3422
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at NzbDrone.Host.Startup.Configure(IApplicationBuilder app, IStartupContext startupContext, Lazy`1 mainDatabaseFactory, Lazy`1 logDatabaseFactory, DatabaseTarget dbTarget, ISingleInstancePolicy singleInstancePolicy, InitializeLogger initializeLogger, ReconfigureLogging reconfigureLogging, IAppFolderFactory appFolderFactory, IProvidePidFile pidFileProvider, IConfigFileProvider configFileProvider, IRuntimeInfo runtimeInfo, IFirewallAdapter firewallAdapter, RadarrErrorPipeline errorHandler) in D:\a\1\s\src\NzbDrone.Host\Startup.cs:line 230
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Radarr.Host.Bootstrap.Start(String[] args, Action`1 trayCallback) in D:\a\1\s\src\NzbDrone.Host\Bootstrap.cs:line 63
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in D:\a\1\s\src\NzbDrone.Console\ConsoleApp.cs:line 45

```

[AB#3051](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3051)

**Comment by bakerboy448** [comment]
You're on the nightly builds, not develop. 
https://wiki.servarr.com/radarr/faq#how-do-i-update-radarr

"dev" is not a radarr version. 4.2.0.6229 is the version.

this was fixed yesterday; you're out of date, upgrade https://github.com/Radarr/Radarr/commit/e2ae743ee1cba116fc1eb78c6735f49dd72db386

**Comment by scphantm** [comment]
where do i download the binaries?

**Comment by bakerboy448** [comment]
https://radarr.servarr.com/v1/update/nightly/updatefile?os=windows&runtime=netcore&arch=x64&installer=true
