### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by volker-raschek** [Radarr/Radarr#7269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

During an update of the index, Radarr crashes and is restarted by kubernetes. 

According to the logs, the database seems to be locked. 

### Expected Behavior

The application does not crash when updating the index

### Steps To Reproduce

1. Start radarr from the helm chart repository k8s-home/radarr. 
2. Mount as persistentVolumeClaim under /config with NFS as backend.
3. Start updating your index

### Environment

```markdown
- OS: Arch Linux
- Radarr: v4.1.0.6175
- Kubernetes Install: yes
- Using Reverse Proxy: yes - nginx-ingress
- Browser: FireFox
```

### What branch are you running?

Master

### Trace Logs?

[Error] TaskExtensions: Task Error 

[v4.1.0.6175] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1033
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1009
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 184
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 146
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push[TCommand](TCommand command, CommandPriority priority, CommandTrigger trigger) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandQueueManager.cs:line 132
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push(String commandName, Nullable`1 lastExecutionTime, Nullable`1 lastStartTime, CommandPriority priority, CommandTrigger trigger) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandQueueManager.cs:line 146
   at NzbDrone.Core.Jobs.Scheduler.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Jobs\Scheduler.cs:line 42
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

[AB#3111](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3111)

**Comment by RobinDadswell** [comment]
As per SQLite's guidance, databases should not be stored on network storage and is not supported

**Comment by RobinDadswell** [comment]
Postgres on nightly/develop is the way around this limitation

**Comment by volker-raschek** [comment]
Yes, I am aware of that. I would like to use postgres to avoid the error. However, I don't like to start one database per application because radarr wants to use two of its own for backwards compatibility. I am willing to give multiple users or schemas to the application, but certainly not multiple databases. I think the application should allow this without breaking changes.
