### ISSUE TITLE
TaskManager failed while processing [CommandExecutedEvent]

### ISSUE THREAD

**Issue by martimarkov** [Radarr/Radarr#7276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using Postgres as a DB backend the task don't seem to work correctly. The list is empty and history doesn't get updated but get executed.

Error:

`TaskManager failed while processing [CommandExecutedEvent]: Error parsing column 4 (LastStartTime=05/07/2022 15:57:31 - DateTime)`

```
System.Data.DataException: Error parsing column 4 (LastStartTime=05/07/2022 15:57:31 - DateTime)
 ---> System.InvalidCastException: Out of the range of DateTime (year must be between 1 and 9999)
 ---> System.ArgumentOutOfRangeException: Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks. (Parameter 'ticks')
   at System.DateTime.ThrowTicksOutOfRange()
   at Npgsql.Internal.TypeHandlers.DateTimeHandlers.DateTimeUtils.ReadDateTime(NpgsqlReadBuffer buf, DateTimeKind kind)
   --- End of inner exception stack trace ---
   at Npgsql.Internal.TypeHandlers.DateTimeHandlers.DateTimeUtils.ReadDateTime(NpgsqlReadBuffer buf, DateTimeKind kind)
   at Npgsql.Internal.TypeHandling.NpgsqlTypeHandler.Read[TAny](NpgsqlReadBuffer buf, Int32 len, Boolean async, FieldDescription fieldDescription)
   at Npgsql.Internal.TypeHandling.NpgsqlTypeHandler`1.ReadAsObject(NpgsqlReadBuffer buf, Int32 len, Boolean async, FieldDescription fieldDescription)
   at Npgsql.NpgsqlDataReader.GetValue(Int32 ordinal)
   at Deserialize5ce4b41d-52b1-48d4-94b9-67c33980506d(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706
   at Deserialize5ce4b41d-52b1-48d4-94b9-67c33980506d(IDataReader )
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[T](IDatabase db, String sql, Object param)
   at NzbDrone.Core.Datastore.BasicRepository`1.Query(SqlBuilder builder)
   at NzbDrone.Core.Jobs.TaskManager.Handle(CommandExecutedEvent message)
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)
```

### Expected Behavior

Should work like using SQLite

### Environment

```markdown
- OS: Unraid
- Radarr: 4.2.0.6256
- Docker Install: Yes
- Using Reverse Proxy: Both
- Browser:
```

### What branch are you running?

Nightly

### Trace Logs?

<img width="1281" alt="Screenshot 2022-05-09 at 12 24 03" src="https://user-images.githubusercontent.com/1858736/167400275-a844950d-9191-4137-ad55-49328cbeec9e.png">

```


2022-05-09 12:18:16.0|Error|EventAggregator|TaskManager failed while processing [CommandExecutedEvent]

[v4.2.0.6246] System.Data.DataException: Error parsing column 4 (LastStartTime=05/07/2022 15:57:31 - DateTime)
 ---> System.InvalidCastException: Out of the range of DateTime (year must be between 1 and 9999)
 ---> System.ArgumentOutOfRangeException: Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks. (Parameter 'ticks')
   at System.DateTime.ThrowTicksOutOfRange()
   at Npgsql.Internal.TypeHandlers.DateTimeHandlers.DateTimeUtils.ReadDateTime(NpgsqlReadBuffer buf, DateTimeKind kind)
   --- End of inner exception stack trace ---
   at Npgsql.Internal.TypeHandlers.DateTimeHandlers.DateTimeUtils.ReadDateTime(NpgsqlReadBuffer buf, DateTimeKind kind)
   at Npgsql.Internal.TypeHandling.NpgsqlTypeHandler.Read[TAny](NpgsqlReadBuffer buf, Int32 len, Boolean async, FieldDescription fieldDescription)
   at Npgsql.Internal.TypeHandling.NpgsqlTypeHandler`1.ReadAsObject(NpgsqlReadBuffer buf, Int32 len, Boolean async, FieldDescription fieldDescription)
   at Npgsql.NpgsqlDataReader.GetValue(Int32 ordinal)
   at Deserialize5ce4b41d-52b1-48d4-94b9-67c33980506d(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706
   at Deserialize5ce4b41d-52b1-48d4-94b9-67c33980506d(IDataReader )
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[T](IDatabase db, String sql, Object param)
   at NzbDrone.Core.Datastore.BasicRepository`1.Query(SqlBuilder builder)
   at NzbDrone.Core.Jobs.TaskManager.Handle(CommandExecutedEvent message)
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)
SQL: 
==== Begin Query Trace ====

QUERY TEXT:
SELECT "ScheduledTasks".*
 FROM "ScheduledTasks"       

PARAMETERS:

==== End Query Trace ====
```

[AB#3118](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3118)

**Comment by RobinDadswell** [comment]
This should be fixed by #7183
