### ISSUE TITLE
Error occurred while executing task ApplicationUpdate: An error occurred trying to start process '/tmp/radarr_update/Radarr.Update' with working directory '/'. Permission denied

### ISSUE THREAD

**Issue by iamkloudz** [Radarr/Radarr#7285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Can't update Radarr in Synology.

### Expected Behavior

Successful update.

### Steps To Reproduce

I went to Update. Clicked install latest. Failed.

### Environment

```markdown
- OS: Synology DSM 7.1
- Radarr:4.2.0.6237
- Docker Install: Synology
- Using Reverse Proxy:
- Browser: Safari
```

### What branch are you running?

Nightly

### Trace Logs?

System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/tmp/radarr_update/Radarr.Update' with working directory '/'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NzbDrone.Common.Processes.ProcessProvider.Start(String path, String args, StringDictionary environmentVariables, Action`1 onOutputDataReceived, Action`1 onErrorDataReceived) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 196
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 166
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 283
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 81
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44

[AB#3138](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3138)

**Comment by ta264** [comment]
Please search before creating duplicate issues

#7227
