### ISSUE TITLE
Recent changes at custom formats causes exception

### ISSUE THREAD

**Issue by reloxx13** [Radarr/Radarr#7315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Web UI not loading, high CPU usage

And its like a loop now (repeating in logs) causing high cpu usage and web ui not loading.

### Expected Behavior

The opposide of current...

### Steps To Reproduce

Wake up and open web ui.

### Environment

```markdown
- OS: Win10x64
- Radarr: v4.2.0.6316
- Docker Install: -
- Using Reverse Proxy: no
- Browser: any (ff, chrome, edge)
```

### What branch are you running?

Nightly

### Trace Logs?

2022-05-29 11:34:07.9|Error|ImportDecisionMaker|Couldn't evaluate decision on X:\xxx\movies\MOVIENAME.2020.German.DL.1080p.BluRay.x264-LizardSquad\movie.name.2020.german.dl.1080p.bluray.x264-lizardsquad.mkv

```
[v4.2.0.6316] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.CustomFormats.CustomFormatCalculationService.ParseCustomFormat(MovieFile movieFile, List`1 allCustomFormats) in X:\a\1\s\src\NzbDrone.Core\CustomFormats\CustomFormatCalculationService.cs:line 77
   at NzbDrone.Core.MediaFiles.MovieImport.Specifications.UpgradeSpecification.IsSatisfiedBy(LocalMovie localMovie, DownloadClientItem downloadClientItem) in X:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieImport\Specifications\UpgradeSpecification.cs:line 51
   at NzbDrone.Core.MediaFiles.MovieImport.ImportDecisionMaker.EvaluateSpec(IImportDecisionEngineSpecification spec, LocalMovie localMovie, DownloadClientItem downloadClientItem) in X:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieImport\ImportDecisionMaker.cs:line 188
```

And its like a loop now (repeating in logs) causing high cpu usage and web ui not loading.

[AB#3199](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3199)

**Comment by reloxx13** [comment]
Azure CI is broken, too. I got this email:


[Radarr/Radarr]   Sync issue to Azure DevOps work item workflow run

https://github.com/Radarr/Radarr/actions/runs/2403977381

**Comment by reloxx13** [comment]
After waiting around 5min the web ui showed up now.

**Comment by bakerboy448** [comment]
> Azure CI is broken, too. I got this email:
> 
> [Radarr/Radarr] Sync issue to Azure DevOps work item workflow run
> 

not broken. Not an issue. Happens all the time with some race conditions

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/commit/144f5640765c2bc28a28274eeac806c7ab44d929

**Comment by reloxx13** [comment]
Looks like this is fixed, but the web ui still takes multiple minutes while loading. I'm looking through the logs but cannot find any more errors beside    

`2022-05-30 14:48:42.3|Error|LocalizationService|Missing translation/culture resource: X:\Radarr-V3\bin\Localization\Core\de_DE.json`   

While my radarr 4k instance runs fine. I guess it has sth to do with the amount of movies in database.   
In the browser console, I can see the request to `http://192.168.178.12:7873/api/v3/collection` is taking so looooooong.   
`GEThttp://192.168.178.12:7873/api/v3/collection`,  5mins, still running.   

Server completely restarted already.

Tested in Firefox and chrome, private tabs and also cleared cache, sessions and cookies.

**Comment by reloxx13** [comment]
> > Azure CI is broken, too. I got this email:
> > [Radarr/Radarr] Sync issue to Azure DevOps work item workflow run
> 
> not broken. Not an issue. Happens all the time with some race conditions

PS:
I always get the email when creating a new issue (even if i dont edit or answer directly, which would create a race issue). u may still take a look into it.
