### ISSUE TITLE
Cannot save custom formats

### ISSUE THREAD

**Issue by glassbase** [Radarr/Radarr#7319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot save a custom format. Red exclamation point. 

### Expected Behavior

Save a custom format.

### Steps To Reproduce

1. Settings
2. Custom formats
3. Click a current one to edit or add new one
4. Make necessary changes
5. (Actually don't even need to make edit, just open a current)
6. Save, red exclamation point

### Environment

```markdown
- OS: Linux 5.10.21-Unraid x86_64 (Unraid 6.9.1)
- Radarr: 4.2.0.6318
- Docker Install: Y
- Using Reverse Proxy: N
- Browser: Windows, Chrome 101.0.4951.67 (Official Build) (64-bit)
```

### What branch are you running?

Nightly

### Trace Logs?

```
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'autounmonitorpreviouslydownloadedmovies' defaultValue:'False'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'retention' defaultValue:'0'
2022-05-30 09:12:05.1|Trace|EventAggregator|ConfigFileSavedEvent <~ ReconfigureLogging
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'recyclebincleanupdays' defaultValue:'7'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'listsynclevel' defaultValue:'disabled'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'certificationcountry' defaultValue:'US'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'maximumsize' defaultValue:'0'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'minimumage' defaultValue:'0'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'downloadpropersandrepacks' defaultValue:'PreferAndUpgrade'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'allowhardcodedsubs' defaultValue:'False'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'whitelistedhardcodedsubs' defaultValue:''
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'createemptymoviefolders' defaultValue:'False'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'deleteemptyfolders' defaultValue:'False'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'checkforfinisheddownloadinterval' defaultValue:'1'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'downloadclienthistorylimit' defaultValue:'60'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'minimumfreespacewhenimporting' defaultValue:'100'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'enablemediainfo' defaultValue:'True'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'importextrafiles' defaultValue:'False'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'extrafileextensions' defaultValue:'srt'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'rescanafterrefresh' defaultValue:'Always'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'setpermissionslinux' defaultValue:'False'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'chmodfolder' defaultValue:'755'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'chowngroup' defaultValue:''
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'firstdayofweek' defaultValue:'0'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'calendarweekcolumnheader' defaultValue:'ddd M/D'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'movieruntimeformat' defaultValue:'HoursMinutes'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'shortdateformat' defaultValue:'MMM D YYYY'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'longdateformat' defaultValue:'dddd, MMMM D YYYY'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'timeformat' defaultValue:'h(:mm)a'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'showrelativedates' defaultValue:'True'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'enablecolorimpairedmode' defaultValue:'False'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'movieinfolanguage' defaultValue:'1'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-05-30 09:12:05.1|Trace|EventAggregator|Publishing ConfigSavedEvent
2022-05-30 09:12:05.1|Trace|EventAggregator|ConfigSavedEvent ~> LocalizationService
2022-05-30 09:12:05.1|Trace|EventAggregator|ConfigSavedEvent ~> TaskManager
2022-05-30 09:12:05.1|Trace|ServerSideNotificationService|Getting server side health notifications
2022-05-30 09:12:05.1|Trace|EventAggregator|ConfigSavedEvent <~ LocalizationService
2022-05-30 09:12:05.1|Trace|HttpClient|Req: [GET] https://radarr.servarr.com/v1/notification?version=4.2.0.6318&os=linuxmusl&arch=X64&runtime=netcore&branch=nightly
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'checkforfinisheddownloadinterval' defaultValue:'1'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2022-05-30 09:12:05.1|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-05-30 09:12:05.1|Trace|Http|Res: 7620 [PUT] /api/v3/config/host: 202.Accepted (176 ms)
2022-05-30 09:12:05.1|Debug|Api|[PUT] /api/v3/config/host: 202.Accepted (176 ms)
2022-05-30 09:12:05.2|Trace|EventAggregator|ConfigSavedEvent <~ TaskManager
2022-05-30 09:12:05.3|Debug|RootFolderService|3 unmapped folders detected.
2022-05-30 09:12:05.3|Debug|RootFolderService|Generating list of unmapped folders
2022-05-30 09:12:05.3|Debug|RootFolderService|0 unmapped folders detected.
2022-05-30 09:12:05.3|Debug|RootFolderService|Generating list of unmapped folders
2022-05-30 09:12:05.3|Debug|RootFolderService|1 unmapped folders detected.
2022-05-30 09:12:05.3|Trace|Http|Res: 7617 [GET] /api/v3/rootfolder: 200.OK (353 ms)
2022-05-30 09:12:05.3|Debug|Api|[GET] /api/v3/rootfolder: 200.OK (353 ms)
2022-05-30 09:12:05.3|Trace|HttpClient|Res: [GET] https://radarr.servarr.com/v1/notification?version=4.2.0.6318&os=linuxmusl&arch=X64&runtime=netcore&branch=nightly: 200.OK (2 bytes) (288 ms)
2022-05-30 09:12:05.3|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2022-05-30 09:12:05.3|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2022-05-30 09:12:05.3|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2022-05-30 09:12:05.3|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2022-05-30 09:12:05.3|Trace|Http|Req: 7621 [GET] /api/v3/health (from 10.0.0.63 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-30 09:12:05.4|Trace|Http|Res: 7621 [GET] /api/v3/health: 200.OK (2 ms)
2022-05-30 09:12:05.4|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2022-05-30 09:12:05.4|Debug|Api|[GET] /api/v3/health: 200.OK (2 ms)
2022-05-30 09:12:05.4|Trace|HttpClient|Res: [GET] https://radarr.servarr.com/v1/notification?version=4.2.0.6318&os=linuxmusl&arch=X64&runtime=netcore&branch=nightly: 200.OK (2 bytes) (316 ms)
2022-05-30 09:12:05.4|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2022-05-30 09:12:05.4|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2022-05-30 09:12:05.4|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2022-05-30 09:12:05.4|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2022-05-30 09:12:05.5|Trace|Http|Req: 7622 [GET] /api/v3/health (from 10.0.0.63 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-30 09:12:05.5|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2022-05-30 09:12:05.5|Trace|Http|Res: 7622 [GET] /api/v3/health: 200.OK (1 ms)
2022-05-30 09:12:05.5|Debug|Api|[GET] /api/v3/health: 200.OK (1 ms)
2022-05-30 09:12:05.5|Trace|ConfigService|Using default config value for 'movieinfolanguage' defaultValue:'1'
2022-05-30 09:12:05.8|Trace|ConfigService|Using default config value for 'movieinfolanguage' defaultValue:'1'
2022-05-30 09:12:06.2|Trace|ConfigService|Using default config value for 'movieinfolanguage' defaultValue:'1'
2022-05-30 09:12:06.2|Trace|Http|Res: 7618 [GET] /api/v3/calendar?unmonitored=True&start=2022-05-30&end=2022-06-06: 200.OK (1209 ms)
2022-05-30 09:12:06.2|Debug|Api|[GET] /api/v3/calendar?unmonitored=True&start=2022-05-30&end=2022-06-06: 200.OK (1209 ms)
2022-05-30 09:12:06.2|Trace|Http|Req: 7623 [GET] /api/v3/movie (from 10.0.0.8 HomeAssistant/2022.5.5 aiohttp/3.8.1 Python/3.9)
2022-05-30 09:12:06.2|Trace|ConfigService|Using default config value for 'movieinfolanguage' defaultValue:'1'
2022-05-30 09:12:07.5|Trace|Http|Req: 7624 [GET] /api/v3/customformat (from 10.0.0.63 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-30 09:12:07.5|Trace|Http|Res: 7624 [GET] /api/v3/customformat: 200.OK (5 ms)
2022-05-30 09:12:07.5|Debug|Api|[GET] /api/v3/customformat: 200.OK (5 ms)
2022-05-30 09:12:09.6|Trace|Http|Req: 7625 [PUT] /api/v3/customformat/5?forceSave=true (from 10.0.0.63 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-30 09:12:09.6|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.2.0.6318] System.InvalidCastException: Unable to cast object of type 'System.Text.Json.JsonElement' to type 'System.String'.
   at Radarr.Api.V3.CustomFormats.CustomFormatController.<>c.<.ctor>b__2_4(CustomFormatResource customFormat, CustomContext context) in D:\a\1\s\src\Radarr.Api.V3\CustomFormats\CustomFormatController.cs:line 32
   at FluentValidation.Validators.CustomValidator`1.Validate(PropertyValidatorContext context) in /home/(removed)/code/FluentValidation/src/FluentValidation/Validators/CustomValidator.cs:line 41
   at FluentValidation.Internal.PropertyRule.Validate(ValidationContext context)+MoveNext() in /home/(removed)/code/FluentValidation/src/FluentValidation/Internal/PropertyRule.cs:line 282
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in /home/(removed)/code/FluentValidation/src/FluentValidation/AbstractValidator.cs:line 115
   at Radarr.Http.REST.RestController`1.ValidateResource(TResource resource, Boolean skipValidate, Boolean skipSharedValidate) in D:\a\1\s\src\Radarr.Http\REST\RestController.cs:line 99
   at Radarr.Http.REST.RestController`1.OnActionExecuting(ActionExecutingContext context) in D:\a\1\s\src\Radarr.Http\REST\RestController.cs:line 72
   at Microsoft.AspNetCore.Mvc.Controller.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-05-30 09:12:09.8|Trace|RadarrErrorPipeline|Handling Exception
2022-05-30 09:12:09.8|Fatal|RadarrErrorPipeline|Request Failed. PUT /api/v3/customformat/5

[v4.2.0.6318] System.InvalidCastException: Unable to cast object of type 'System.Text.Json.JsonElement' to type 'System.String'.
   at Radarr.Api.V3.CustomFormats.CustomFormatController.<>c.<.ctor>b__2_4(CustomFormatResource customFormat, CustomContext context) in D:\a\1\s\src\Radarr.Api.V3\CustomFormats\CustomFormatController.cs:line 32
   at FluentValidation.Validators.CustomValidator`1.Validate(PropertyValidatorContext context) in /home/(removed)/code/FluentValidation/src/FluentValidation/Validators/CustomValidator.cs:line 41
   at FluentValidation.Internal.PropertyRule.Validate(ValidationContext context)+MoveNext() in /home/(removed)/code/FluentValidation/src/FluentValidation/Internal/PropertyRule.cs:line 282
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in /home/(removed)/code/FluentValidation/src/FluentValidation/AbstractValidator.cs:line 115
   at Radarr.Http.REST.RestController`1.ValidateResource(TResource resource, Boolean skipValidate, Boolean skipSharedValidate) in D:\a\1\s\src\Radarr.Http\REST\RestController.cs:line 99
   at Radarr.Http.REST.RestController`1.OnActionExecuting(ActionExecutingContext context) in D:\a\1\s\src\Radarr.Http\REST\RestController.cs:line 72
   at Microsoft.AspNetCore.Mvc.Controller.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-05-30 09:12:09.9|Trace|Http|Res: 7625 [PUT] /api/v3/customformat/5?forceSave=true: 500.InternalServerError (300 ms)
2022-05-30 09:12:09.9|Debug|Api|[PUT] /api/v3/customformat/5?forceSave=true: 500.InternalServerError (300 ms)
2022-05-30 09:12:10.5|Trace|Scheduler|Pending Tasks: 0
2022-05-30 09:12:12.2|Trace|Http|Res: 7623 [GET] /api/v3/movie: 200.OK (6048 ms)
2022-05-30 09:12:12.2|Debug|Api|[GET] /api/v3/movie: 200.OK (6048 ms)
2022-05-30 09:12:20.3|Trace|Http|Req: 7626 [GET] /api/v3/health (from 10.0.0.63 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-30 09:12:20.3|Trace|Http|Res: 7626 [GET] /api/v3/health: 200.OK (2 ms)
2022-05-30 09:12:20.3|Trace|Http|Req: 7627 [GET] /api/v3/diskspace (from 10.0.0.63 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-30 09:12:20.3|Trace|Http|Req: 7628 [GET] /api/v3/system/status (from 10.0.0.63 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-30 09:12:20.3|Debug|Api|[GET] /api/v3/health: 200.OK (2 ms)
2022-05-30 09:12:20.3|Trace|Http|Res: 7628 [GET] /api/v3/system/status: 200.OK (63 ms)
2022-05-30 09:12:20.3|Debug|Api|[GET] /api/v3/system/status: 200.OK (63 ms)
2022-05-30 09:12:20.6|Trace|Http|Res: 7627 [GET] /api/v3/diskspace: 200.OK (300 ms)
2022-05-30 09:12:20.6|Debug|Api|[GET] /api/v3/diskspace: 200.OK (300 ms)
2022-05-30 09:12:22.0|Trace|Http|Req: 7629 [GET] /api/v3/log/file (from 10.0.0.63 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-30 09:12:22.0|Trace|Http|Res: 7629 [GET] /api/v3/log/file: 200.OK (35 ms)
2022-05-30 09:12:22.0|Debug|Api|[GET] /api/v3/log/file: 200.OK (35 ms)
2022-05-30 09:12:28.1|Trace|Http|Req: 7630 [GET] /logfile/radarr.trace.txt (from 10.0.0.63 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
```

[AB#3211](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3211)

**Comment by reloxx13** [comment]
Try to re-set the default (prefilled) values.

**Comment by reloxx13** [comment]
its fixed already, ull just have to wait for the next version.

**Comment by glassbase** [comment]
Sorry... Did not see it closed. Thanks
