### ISSUE TITLE
StartupFolderValidator does not validate properly | RecycleBin set to Startup Folder

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#7329]
https://github.com/Radarr/Radarr/blob/fd4fb88ce1efa8f673c74f04cd632a3f607565c4/src/NzbDrone.Api/Config/MediaManagementConfigModule.cs#L29 does not work

https://github.com/Radarr/Radarr/commit/fd4fb88ce1efa8f673c74f04cd632a3f607565c4 is not fully functional

https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/Validation/Paths/StartupFolderValidator.cs

doesn't work

abbreviated test
```csharp
            var  folderPath = _appFolderInfo.StartUpFolder;
            var testPath = context.PropertyValue.ToString();
            return !_appFolderInfo.StartUpFolder.IsParentPath(context.PropertyValue.ToString());
```

```none
folderPath
"C:\\Development\\Code\\Radarr\\_output\\net6.0"
testPath
"C:\\Development\\Code\\Radarr\\_output\\net6.0\\"
```

apparently folderPath is not a parent of testPath?

Version 4.2.0.6322
OS agnostic
![image](https://user-images.githubusercontent.com/55419169/171752794-2fbe311f-7f3b-4418-9ef7-6a18220602a1.png)

Logs

```
2022-06-02 18:06:12.6|Trace|ConfigService|Writing Setting to database. Key:'recyclebin' Value:'C:\Development\Code\Radarr\_output\net6.0\'
2022-06-02 18:06:12.6|Trace|Http|Res: 188 [GET] /api/v3/command: 200.OK (17 ms)
2022-06-02 18:06:12.7|Trace|EventAggregator|Publishing ConfigSavedEvent
```

[AB#3222](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3222)

**Comment by bakerboy448** [comment]
Also allows AppData folder to be set as recyclebin

```
2022-06-02 18:12:26.3|Trace|ConfigService|Writing Setting to database. Key:'recyclebin' Value:'C:\ProgramData\Radarr\'
2022-06-02 18:12:26.3|Trace|EventAggregator|Publishing ConfigSavedEvent
```


Correctly blocks setting as a root folder however

```
2022-06-02 18:13:19.4|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v10.0.0.32391] FluentValidation.ValidationException: Validation failed: 
 -- RecycleBin: Path is already configured as a root folder
   at Radarr.Http.REST.RestController`1.ValidateResource(TResource resource, Boolean skipValidate, Boolean skipSharedValidate) in C:\Development\Code\Radarr\src\Radarr.Http\REST\RestController.cs:line 113
   at Radarr.Http.REST.RestController`1.OnActionExecuting(ActionExecutingContext context) in C:\Development\Code\Radarr\src\Radarr.Http\REST\RestController.cs:line 72
   at Microsoft.AspNetCore.Mvc.Controller.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in C:\Development\Code\Radarr\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 27
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in C:\Development\Code\Radarr\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 40
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in C:\Development\Code\Radarr\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 32
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in C:\Development\Code\Radarr\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 26
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in C:\Development\Code\Radarr\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 27
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-06-02 18:13:19.9|Trace|RadarrErrorPipeline|Handling Exception
2022-06-02 18:13:19.9|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- RecycleBin: Path is already configured as a root folder
2022-06-02 18:13:19.9|Trace|Http|Res: 247 [PUT] /api/v3/config/mediamanagement: 400.BadRequest (7956 ms)
2022-06-02 18:13:19.9|Debug|Api|[PUT] /api/v3/config/mediamanagement: 400.BadRequest (7956 ms)
2022-06-02 18:13:21.3|Trace|Http|Res: 246 [GET] /api/v3/filesystem?path=C%3A%5CDevelopment%5CTesting%5CRadarr%5C&allowFoldersWithoutTrailingSlashes=false&includeFiles=false: 200.OK (10248 ms)
2022-06-02 18:13:21.3|Debug|Api|[GET] /api/v3/filesystem?path=C%3A%5CDevelopment%5CTesting%5CRadarr%5C&allowFoldersWithoutTrailingSlashes=false&includeFiles=false: 200.OK (10248 ms)
```
