### ISSUE TITLE
After installation cheking update - SQL logic error no such column: âˆ’1

### ISSUE THREAD

**Issue by tobe76** [Radarr/Radarr#7332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After installation I got error if I go to check updates

Got "Failed to fetch updates" in browser

In Event I got 
23:09 | RadarrErrorPipeline | [GET /api/v3/update]: SQL logic error no such column: −1 
23:09 | Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware | An unhandled exception has occurred while executing the request.: SQL logic error no such column: −1

### Expected Behavior

-

### Environment

```markdown
- OS: Linux Ubuntu server 20.04
- Radarr: 4.1.0.6175
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox/Chrome
```

### What branch are you running?

Master

### Trace Logs?

2022-06-03 23:01:19.6|Debug|Api|[GET] /api/v3/command: 200.OK (21 ms)
2022-06-03 23:01:19.6|Error|CommandExecutor|Error occurred while executing task ApplicationCheckUpdate

[v4.1.0.6175] code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
no such column: âˆ’1
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
   at Dapper.SqlMapper.MultiMapImpl[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn, IDataReader reader, Identity identity, Boolean finalize)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1470
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.MultiMap[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, String sql, Delegate map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1451
   at Dapper.SqlMapper.Query[TFirst,TSecond,TThird,TReturn](IDbConnection cnn, String sql, Func`4 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1327
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[TFirst,TSecond,TThird,TReturn](IDatabase db, String sql, Func`4 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in D:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\SqlMapperExtensions.cs:line 74
   at NzbDrone.Core.Datastore.SqlMapperExtensions.QueryJoined[T,T2,T3](IDatabase db, SqlBuilder builder, Func`4 mapper) in D:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\SqlMapperExtensions.cs:line 164
   at NzbDrone.Core.History.HistoryRepository.PagedQuery(SqlBuilder sql) in D:\a\1\s\src\NzbDrone.Core\History\HistoryRepository.cs:line 84
   at NzbDrone.Core.Datastore.BasicRepository`1.GetPagedRecords(SqlBuilder builder, PagingSpec`1 pagingSpec, Func`2 queryFunc) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 427
   at NzbDrone.Core.Datastore.BasicRepository`1.GetPaged(PagingSpec`1 pagingSpec) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 398
   at NzbDrone.Core.History.HistoryService.Paged(PagingSpec`1 pagingSpec) in D:\a\1\s\src\NzbDrone.Core\History\HistoryService.cs:line 54
   at NzbDrone.Core.Analytics.AnalyticsService.get_InstallIsActive() in D:\a\1\s\src\NzbDrone.Core\Analytics\AnalyticsService.cs:line 33
   at NzbDrone.Core.Update.UpdatePackageProvider.GetLatestUpdate(String branch, Version currentVersion) in D:\a\1\s\src\NzbDrone.Core\Update\UpdatePackageProvider.cs:line 46
   at NzbDrone.Core.Update.CheckUpdateService.AvailableUpdate() in D:\a\1\s\src\NzbDrone.Core\Update\UpdateCheckService.cs:line 25
   at NzbDrone.Core.Update.InstallUpdateService.GetUpdatePackage(CommandTrigger updateTrigger) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 232
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationCheckUpdateCommand message) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 269
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 81
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44
SQL: 
==== Begin Query Trace ====

QUERY TEXT:
SELECT History.*, Movies.*, Profiles.*
 FROM History 
JOIN Movies ON ("History"."MovieId" = "Movies"."Id")
JOIN Profiles ON ("Movies"."ProfileId" = "Profiles"."Id")
      ORDER BY date DESC LIMIT 1 OFFSET âˆ’1

PARAMETERS:

==== End Query Trace ====

[AB#3224](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3224)

**Comment by bakerboy448** [comment]
A single line error spew is not helpful nor the trace logs that are required for bug reports and linked to the wiki.

Please provide the information the bug report requested and follow the 6 steps on the wiki the bug template links.

It also appears whatever you're using to view the logs is mangling their encoding

**Comment by tobe76** [comment]
Found the reason why I got this error.
If you install a linux server with Swedish as the language, you get this error.
When I switched to English as a language, it worked fine without any problems.
So there is a little language bug in the program.
