### ISSUE TITLE
YIFY Movies RSS: Feed contains releases with same guid

### ISSUE THREAD

**Issue by DaeDroug** [Radarr/Radarr#7381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Gets Error When adding any RSS from YIFY Movies (https://yts.mx): Indexer feed is not supported: Feed contains releases with same guid, rejecting malformed rss feed.

### Expected Behavior

Should allow the RSS to be added and treat any later pub dates as repacks.

### Steps To Reproduce

Attempt to add https://yts.mx/rss as an RSS indexer

### Environment

```markdown
- OS: Linux? (running on Synology but linux inside docker container)
- Radarr: 4.0.4.5922
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Opera GX
```

### What branch are you running?

Master

### Trace Logs?

2022-06-21 22:34:44.8|Warn|TorrentRssIndexer|Indexer feed is not supported

[v4.0.4.5922] NzbDrone.Core.Indexers.Exceptions.UnsupportedFeedException: Feed contains releases with same guid, rejecting malformed rss feed.
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.ValidateReleases(TorrentInfo[] releases, TorrentRssIndexerSettings indexerSettings) in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:line 249
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.GetGenericTorrentRssParserSettings(IndexerResponse response, TorrentRssIndexerSettings indexerSettings) in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:line 135
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.GetParserSettings(IndexerResponse response, TorrentRssIndexerSettings indexerSettings) in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:line 68
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.Detect(TorrentRssIndexerSettings indexerSettings) in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:line 57
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssParserFactory.DetectParserSettings(TorrentRssIndexerSettings indexerSettings) in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssParserFactory.cs:line 55
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssParserFactory.<>c__DisplayClass4_0.<GetParser>b__0() in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssParserFactory.cs:line 32
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 104
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssParserFactory.GetParser(TorrentRssIndexerSettings indexerSettings) in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssParserFactory.cs:line 40
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 321

2022-06-21 22:34:46.3|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.0.4.5922] FluentValidation.ValidationException: Validation failed: 
 -- : Indexer feed is not supported: Feed contains releases with same guid, rejecting malformed rss feed.
   at Radarr.Api.V3.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 205
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 191
   at Radarr.Api.V3.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 68
   at lambda_method487(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2022-06-21 22:34:48.0|Trace|RadarrErrorPipeline|Handling Exception
2022-06-21 22:34:48.0|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Indexer feed is not supported: Feed contains releases with same guid, rejecting malformed rss feed.
2022-06-21 22:34:48.1|Trace|Http|Res: 407482 [POST] /api/v3/indexer: 400.BadRequest (5987 ms)
2022-06-21 22:34:48.1|Debug|Api|[POST] /api/v3/indexer: 400.BadRequest (5987 ms)
2022-06-21 22:34:51.6|Trace|Http|Req: 407486 [GET] /api/v3/health (from 172.17.0.1)
2022-06-21 22:34:51.6|Trace|Http|Res: 407486 [GET] /api/v3/health: 200.OK (1 ms)
2022-06-21 22:34:51.6|Debug|Api|[GET] /api/v3/health: 200.OK (1 ms)
2022-06-21 22:34:51.6|Trace|Http|Req: 407487 [GET] /api/v3/diskspace (from 172.17.0.1)
2022-06-21 22:34:51.8|Trace|Http|Req: 407488 [GET] /api/v3/system/status (from 172.17.0.1)
2022-06-21 22:34:51.9|Trace|Http|Res: 407488 [GET] /api/v3/system/status: 200.OK (91 ms)
2022-06-21 22:34:51.9|Debug|Api|[GET] /api/v3/system/status: 200.OK (91 ms)
2022-06-21 22:34:52.9|Trace|Http|Req: 407489 [GET] /api/v3/log/file (from 172.17.0.1)
2022-06-21 22:34:52.9|Trace|Http|Res: 407489 [GET] /api/v3/log/file: 200.OK (4 ms)
2022-06-21 22:34:52.9|Debug|Api|[GET] /api/v3/log/file: 200.OK (4 ms)
2022-06-21 22:34:54.0|Trace|Http|Res: 407487 [GET] /api/v3/diskspace: 200.OK (2357 ms)
2022-06-21 22:34:54.0|Debug|Api|[GET] /api/v3/diskspace: 200.OK (2357 ms)
2022-06-21 22:34:55.9|Trace|Http|Req: 407490 [GET] /logfile/radarr.trace.txt (from 172.17.0.1)

**Comment by bakerboy448** [comment]
The GUID is supposed to be unique; this is something YTS needs to fix.
