### ISSUE TITLE
RSS Parser gives up on empty title

### ISSUE THREAD

**Issue by ohmantics** [Radarr/Radarr#7410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Given an RSS feed with `<item><title><![CDATA[]]></title>` in it, the parser throws an exception. This ruins the whole feed for a single broken item.

https://github.com/Radarr/Radarr/blob/627ab64fd023269c8bedece61e529329600a3419/src/NzbDrone.Core/Indexers/TorrentRss/TorrentRssSettingsDetector.cs#L258

### Expected Behavior

Postel's Law would suggest that when it's possible to recover from issues in input data, we should.

It makes sense to log a warning and allow the feed parsing to continue.

### Environment

```markdown
- OS: FreeBSD 12.2
- Radarr: 4.1.0.6175
- Docker Install: No
- Using Reverse Proxy: No
- Browser: (not UI related)
```

### What branch are you running?

Master

### Trace Logs?

```
2022-07-09 23:10:34.5|Debug|TorrentRssSettingsDetector|Evaluating TorrentRss feed '<REDACTED>'
2022-07-09 23:10:36.0|Warn|TorrentRssIndexer|Indexer feed is not supported

[v4.1.0.6175] NzbDrone.Core.Indexers.Exceptions.UnsupportedFeedException: Feed contains releases without title.
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.ValidateReleases(TorrentInfo[] releases, TorrentRssIndexerSettings indexerSettings) in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:line 273
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.GetGenericTorrentRssParserSettings(IndexerResponse response, TorrentRssIndexerSettings indexerSettings) in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:line 135
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.GetParserSettings(IndexerResponse response, TorrentRssIndexerSettings indexerSettings) in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:line 68
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.Detect(TorrentRssIndexerSettings indexerSettings) in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:line 57
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssParserFactory.DetectParserSettings(TorrentRssIndexerSettings indexerSettings) in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssParserFactory.cs:line 55
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssParserFactory.<>c__DisplayClass4_0.<GetParser>b__0() in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssParserFactory.cs:line 32
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 114
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssParserFactory.GetParser(TorrentRssIndexerSettings indexerSettings) in D:\a\1\s\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssParserFactory.cs:line 40
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 321


2022-07-09 23:10:36.0|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.1.0.6175] FluentValidation.ValidationException: Validation failed: 
 -- : Indexer feed is not supported: Feed contains releases without title.
   at Radarr.Api.V3.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 200
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 191
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 140
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-07-09 23:10:36.0|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Indexer feed is not supported: Feed contains releases without title.
2022-07-09 23:10:36.0|Debug|Api|[POST] /api/v3/indexer/test: 400.BadRequest (1662 ms)
2022-07-09 23:10:48.0|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2022-07-09 23:10:48.0|Debug|Api|[GET] /api/v3/system/status: 200.OK (2 ms)
2022-07-09 23:10:48.0|Debug|Api|[GET] /api/v3/diskspace: 200.OK (14 ms)
2022-07-09 23:10:50.0|Debug|Api|[GET] /api/v3/log/file: 200.OK (125 ms)

```

**Comment by Qstick** [comment]
Based on the error handling and message, I'd say this was intended behavior upstream. @markus101 may be able to add some flavor.

**Comment by ohmantics** [comment]
The parser being strict is a great option to have for those developing feed providers to check their implementation. It's a better user experience to recover from broken feeds in the client.

**Comment by nauip** [comment]
Seems like we're just missing the check box: [   ] Ignore bad titles.
