### ISSUE TITLE
Jackett.Common.IndexerException: Exception (rarbg): The response was not JSON  ---> System.Exception: The response was not JSON

### ISSUE THREAD

**Issue by PN62323424** [Radarr/Radarr#7430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

At regular intervals, radarr and sonarr report the following errors.

If I re-copy the Torznab Feed from rarbg to radarr and sonarr a few times and save it a few times, the error reporting goes away, but comes back after a while.

Indexers unavailable due to failures for more than 6 hours: rarbg 
All rss-capable indexers are temporarily unavailable due to recent indexer errors
 

### Expected Behavior

11

### Environment

```markdown
- OS: openwrt
- Radarr:Radarr 3.0.1.4259
- Docker Install:Yes
- Using Reverse Proxy:No
- Browser:chrome 103.0.5060.134
```

### What branch are you running?

Master

### Trace Logs?

An error occurred while processing indexer feed. http://10.0.0.75:9117/api/v2.0/indexers/rarbg/results/torznab/api?t=movie&cat=2000,100014,100017,100018,100023,100025,100041,100042,100044,100045,100046,100047,100048,100049,100050,100051,100052,100054,5000&extended=1&apikey=(removed)&offset=0&limit=100: Torznab error detected: Jackett.Common.IndexerException: Exception (rarbg): The response was not JSON
 ---> System.Exception: The response was not JSON
   at Jackett.Common.Indexers.RarBG.PerformQueryWithRetry(TorznabQuery query, Boolean retry) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RarBG.cs:line 148
   at Jackett.Common.Indexers.RarBG.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RarBG.cs:line 134
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 324
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 324
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 680
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 440

[AB#3378](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3378)

**Comment by ta264** [comment]
This is RarBG failing / rate limiting you

**Comment by abyssalsmoke** [comment]
I'm having the same issue. Changed url used in jacket and now tests pass in radarr sonar but the error comes back.

**Comment by MrSparklle** [comment]
Same issue here, started a few days ago.

**Comment by jackslapped** [comment]
also having the same issue. rarbg works fine in radarr.

**Comment by jonlbauer** [comment]
Yup. Me too.

**Comment by nssatlantis** [comment]
Same, isn't rarbg not being functional a bug? As it's a standard in the app?
