### ISSUE TITLE
Trakt List import does not handle single quotes or forward slash

### ISSUE THREAD

**Issue by psylenced** [Radarr/Radarr#7432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When importing a trakt list name that has a single quote in the name, it gets replaced with blank string.

The trakt api replaces single quotes with a dash. It also replaces forward slash `/` with dash.

This causes a 404 error.

**List Name:** ```Bob's List```

**Current:**

```https://api.trakt.tv/users/username/lists/bobs-list/items/movies```

```Unable to connect to list: HTTP request failed: [404:NotFound] [GET] at [https://api.trakt.tv/users/username/lists/bobs-list/items/movies]
 at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 101
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchImportListResponse(ImportListRequest request) in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 173
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchPage(ImportListRequest request, IParseImportListResponse parser) in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 157
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 187
```

### Expected Behavior

The Trakt Import should replace single quotes with a dash before calling API.

**Expected URL:**

```https://api.trakt.tv/users/username/lists/bob-s-list/items/movies```

### Environment

```markdown
- OS: Alpine Linux
- Radarr: 4.1.0.6175
- Docker Install: No
```

### What branch are you running?

Master

### Trace Logs?

```Unable to connect to list: HTTP request failed: [404:NotFound] [GET] at [https://api.trakt.tv/users/username/lists/bobs-list/items/movies]
 at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 101
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchImportListResponse(ImportListRequest request) in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 173
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchPage(ImportListRequest request, IParseImportListResponse parser) in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 157
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 187
```

### Workaround

A workaround for this bug is to replace single quote with dash in the UI.

**Changing List Name:** ```Bob's List```

**To List Name:** ```Bob-s List```

**Comment by psylenced** [comment]
But is here:

**Comment by psylenced** [comment]
Bug is here:

https://github.com/Radarr/Radarr/blob/627ab64fd023269c8bedece61e529329600a3419/src/NzbDrone.Core/ImportLists/Trakt/List/TraktListRequestGenerator.cs#L30

It uses generic  ```Parser.Parser.ToUrlSlug();``` so fixing slug parser may break other uses of it.

**Comment by psylenced** [comment]
What would be the best approach for this?

1. Pre-processing special characters in `TraktListRequestGenerator` before calling slug - seems hackish.
2. Passing an optional parameter of some sort (character list) that gets replaced with `-` rather than `string.Empty` in `Parser.ToUrlSlug`.
3. Change the Trakt list search to convert special characters into a Regex wildcard style match to find a matching list regardless of special characters.
