### ISSUE TITLE
indexer hdbits no longer connects

### ISSUE THREAD

**Issue by dedepene** [Radarr/Radarr#7555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to connect to indexer, check the log for more details

### Expected Behavior

2022-08-20 20:05:45.8|Warn|HDBits|Unable to connect to indexer

[v4.2.1.6478] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 309
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 292
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 334

### Environment

```markdown
- OS: windows 10
- Radarr: 4.2.1.6478
- Docker Install:
- Using Reverse Proxy: no
- Browser: chrome
```

### What branch are you running?

Master

### Trace Logs?

as soon as I set logging to "trace" and the radarr became totally unresponsive! no amount of restarting the app or the server seems to fix it. It's so bad, I can't even get to the settings and revert :(((( 

[AB#3655](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3655)

**Comment by dedepene** [comment]
also from the logs now:

`2022-08-20 21:20:44.3|Debug|IndexerFactory|Temporarily ignoring indexer HDBits till 8/21/2022 5:04:25 PM due to recent failures.`

**Comment by dedepene** [comment]
hmm...after another server reboot, the hdbits indexer test passes now
