### ISSUE TITLE
Trakt Anticipated & Popular List - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by delize** [Radarr/Radarr#7576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://discord.com/channels/264387956343570434/264388019585286144/1015001216163532810

1. Add trakt.tv popular list 
2. Select Anticipated from the drop down 
3. Test Connection
4. Get error:
https://gist.github.com/delize/491cbcaaf1c298069c81aeb0fb205bfe

![image](https://user-images.githubusercontent.com/4028612/188013734-0227254a-7500-4f6d-ad46-2228c0ec05d4.png)
![image](https://user-images.githubusercontent.com/4028612/188013749-9623e346-fecf-4d4e-881c-7c52c3de86dc.png)

### Expected Behavior

1. Add trakt.tv popular list 
2. Select Anticipated from the drop down 
3. Test Connection
4. Get that sweet sweet anticipated movie listings

### Steps To Reproduce

See current behavior

### Environment

```markdown
- OS: Ubuntu
- Radarr: 4.2.3.6555
- Docker Install: Yes
- Using Reverse Proxy: Yes, SWAG
- Browser: Google Chrome v105
```

### What branch are you running?

Nightly

### Trace Logs?

https://gist.github.com/delize/491cbcaaf1c298069c81aeb0fb205bfe

```
2022-09-01 15:48:16.6|Trace|Http|Req: 6989 [GET] /radarr/api/v3/importlist/schema (from 10.10.10.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36)
2022-09-01 15:48:16.6|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-09-01 15:48:16.6|Trace|Http|Res: 6989 [GET] /radarr/api/v3/importlist/schema: 200.OK (5 ms)
2022-09-01 15:48:37.3|Trace|Scheduler|Pending Tasks: 0
2022-09-01 15:48:40.4|Trace|Http|Req: 6990 [POST] /radarr/api/v3/importList/action/startOAuth?callbackUrl=https%3A%2F%2Fnet-slum.org%2Fradarr%2Foauth.html (from 10.10.10.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36)
2022-09-01 15:48:40.4|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-09-01 15:48:40.4|Trace|Http|Res: 6990 [POST] /radarr/api/v3/importList/action/startOAuth?callbackUrl=https%3A%2F%2Fnet-slum.org%2Fradarr%2Foauth.html: 200.OK (3 ms)
2022-09-01 15:48:42.3|Trace|Http|Req: 6991 [GET] /radarr/oauth.html?access_token=(removed)&expires_in=7889237&refresh_token=(removed) (from 10.10.10.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36)
2022-09-01 15:48:42.3|Trace|Http|Res: 6991 [GET] /radarr/oauth.html?access_token=(removed)&expires_in=7889237&refresh_token=(removed) 200.OK (1 ms)
2022-09-01 15:48:43.6|Trace|Http|Req: 6992 [POST] /radarr/api/v3/importList/action/getOAuthToken?oauthUrl=https%3A%2F%2Ftrakt.tv%2Foauth%2Fauthorize%3Fclient_id%3D64508a8bf370cee550dde4806469922fd7cd70afb2d5690e3ee7f75ae784b70e%26response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fauth.servarr.com%252Fv1%252Ftrakt%252Fauth%26state%3Dhttps%253A%252F%252Fnet-slum.org%252Fradarr%252Foauth.html&access_token=(removed)&expires_in=7889237&refresh_token=(removed) (from 10.10.10.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36)
2022-09-01 15:48:43.6|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-09-01 15:48:43.6|Trace|HttpClient|Req: [GET] https://api.trakt.tv/users/settings
2022-09-01 15:48:43.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-09-01 15:48:43.9|Trace|HttpClient|Res: [GET] https://api.trakt.tv/users/settings: 200.OK (949 bytes) (302 ms)
2022-09-01 15:48:43.9|Trace|Http|Res: 6992 [POST] /radarr/api/v3/importList/action/getOAuthToken?oauthUrl=https%3A%2F%2Ftrakt.tv%2Foauth%2Fauthorize%3Fclient_id%3D64508a8bf370cee550dde4806469922fd7cd70afb2d5690e3ee7f75ae784b70e%26response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fauth.servarr.com%252Fv1%252Ftrakt%252Fauth%26state%3Dhttps%253A%252F%252Fnet-slum.org%252Fradarr%252Foauth.html&access_token=(removed)&expires_in=7889237&refresh_token=(removed) 200.OK (305 ms)
2022-09-01 15:48:45.1|Trace|Http|Req: 6993 [POST] /radarr/api/v3/importlist/test (from 10.10.10.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36)
2022-09-01 15:48:45.1|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-09-01 15:48:45.1|Warn|TraktPopularImport|Unable to connect to list

[v4.2.3.6555] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.ImportLists.Trakt.Popular.TraktPopularRequestGenerator.GetMoviesRequest()+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 187


2022-09-01 15:48:45.1|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.2.3.6555] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to list, check the log for more details
   at Radarr.Api.V3.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 205
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 191
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 140
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-09-01 15:48:45.4|Trace|RadarrErrorPipeline|Handling Exception
2022-09-01 15:48:45.4|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to list, check the log for more details
```

[AB#3690](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3690)

**Comment by delize** [comment]
Reproducible: https://discord.com/channels/264387956343570434/264388019585286144/1015004356925472891
