### ISSUE TITLE
rarbg indexer is marked as unavailable if movie is not found

### ISSUE THREAD

**Issue by mantas3** [Radarr/Radarr#7625]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Rarbg indexer is marked as not active when movie not found:

> 2022-09-22 21:33:51.4|Info|ReleaseSearchService|Searching indexers for [The Parmesan Thieves]. 1 active indexers
2022-09-22 21:33:51.5|Info|MigrationController|*** Migrating data source=/config/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2022-09-22 21:33:51.5|Warn|Rarbg|https://torrentapi.org/pubapi_v2.php?mode=search&search_themoviedb=1020249&ranked=0&category=14%3B48%3B17%3B45%3B44%3B50%3B54%3B51%3B52%3B46&limit=100&token=(removed)&format=json_extended&app_id=Radarr
[v4.1.0.6175] NzbDrone.Core.Indexers.Exceptions.IndexerException: Indexer API call returned error 14: Cant find themoviedb in database. Are you sure this themoviedb exists?
   at NzbDrone.Core.Indexers.Rarbg.RarbgParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Rarbg\RarbgParser.cs:line 41
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 292
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 123
RequestUri: https://torrentapi.org/pubapi_v2.php?mode=search&search_themoviedb=1020249&ranked=0&category=14%3B48%3B17%3B45%3B44%3B50%3B54%3B51%3B52%3B46&limit=100&token=(removed)&format=json_extended&app_id=Radarr;StatusCode: OK;ContentType: application/json;ContentLength: 98;ContentSample: {"error":"Cant find themoviedb in database. Are you sure this themoviedb exists?","error_code":14}
2022-09-22 21:33:51.6|Info|DownloadDecisionMaker|No results found
2022-09-22 21:33:51.6|Info|MovieSearchService|Movie search completed. 0 reports downloaded.

All further searches will fail, because indexer is not active anymore:

>2022-09-22 21:34:01.3|Info|ReleaseSearchService|Searching indexers for [Avatar: The Way of Water]. 0 active indexers
2022-09-22 21:34:01.3|Info|DownloadDecisionMaker|No results found
2022-09-22 21:34:01.3|Info|MovieSearchService|Movie search completed. 0 reports downloaded.

![image](https://user-images.githubusercontent.com/808053/191827273-8f9a81a7-1ec8-42c2-8a6c-ed1d729fa467.png)

### Expected Behavior

Indexer should not be marked as inactive because move was not found, error code 14 should be handled.

### Steps To Reproduce

1. Search for "The Parmesan Thieves" which doesn't exist in Rarbg database (or any other non existing movie).
2. Rarbg will return API error code 14 with error message that movie is not found.
3. Radarr doesn't handle this error and marks Rarbg indexer as unavailable

### Environment

```markdown
- OS: Unraid Version: 6.10.3
- Radarr: Radarr Version 4.1.0.6175
- Docker Install: Yes. Package Version 4.1.0.6175-ls153 by linuxserver.io
- Using Reverse Proxy: No
- Browser: -
- Database: -
```

### What branch are you running?

Master

### Trace Logs?

2022-09-22 21:33:51.4|Info|ReleaseSearchService|Searching indexers for [The Parmesan Thieves]. 1 active indexers
2022-09-22 21:33:51.5|Info|MigrationController|*** Migrating data source=/config/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2022-09-22 21:33:51.5|Warn|Rarbg|https://torrentapi.org/pubapi_v2.php?mode=search&search_themoviedb=1020249&ranked=0&category=14%3B48%3B17%3B45%3B44%3B50%3B54%3B51%3B52%3B46&limit=100&token=(removed)&format=json_extended&app_id=Radarr
[v4.1.0.6175] NzbDrone.Core.Indexers.Exceptions.IndexerException: Indexer API call returned error 14: Cant find themoviedb in database. Are you sure this themoviedb exists?
   at NzbDrone.Core.Indexers.Rarbg.RarbgParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Rarbg\RarbgParser.cs:line 41
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 292
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 123
RequestUri: https://torrentapi.org/pubapi_v2.php?mode=search&search_themoviedb=1020249&ranked=0&category=14%3B48%3B17%3B45%3B44%3B50%3B54%3B51%3B52%3B46&limit=100&token=(removed)&format=json_extended&app_id=Radarr;StatusCode: OK;ContentType: application/json;ContentLength: 98;ContentSample: {"error":"Cant find themoviedb in database. Are you sure this themoviedb exists?","error_code":14}
2022-09-22 21:33:51.6|Info|DownloadDecisionMaker|No results found
2022-09-22 21:33:51.6|Info|MovieSearchService|Movie search completed. 0 reports downloaded.
2022-09-22 21:34:01.3|Info|ReleaseSearchService|Searching indexers for [Avatar: The Way of Water]. 0 active indexers
2022-09-22 21:34:01.3|Info|DownloadDecisionMaker|No results found
2022-09-22 21:34:01.3|Info|MovieSearchService|Movie search completed. 0 reports downloaded.

[AB#3800](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3800)

**Comment by bakerboy448** [comment]
For future reference info logs are not trace logs.  However, luckily the warning and stacktrace gave enough info
