### ISSUE TITLE
Radarr Telegram connection cannot be saved

### ISSUE THREAD

**Issue by neogamaes** [Radarr/Radarr#7645]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Hi all,

I have already a working telegram notification with Sonarr.

I have set-up the same parameters to Radarr:
- when I hit the "test" button I successfully receive the telegram text from Radarr (everything seems perfect)
- then I hit the "save" button, I receive again the telegram text from Radarr, but it appears then the red exclamation point over the save button... and nothing is indeed saved.

In the debugg log provided it can be seen that the "test" is succesful but that an error appear afterwards...

If you have any idea why this appear on Raddar (while everything is fine with Sonarr).

Thanks for your help,

### Expected Behavior

Click "save" and have a proper telegram notification connection set.

### Steps To Reproduce

1. Add Telegram notification in Radar
2. Give a name, the bot token and Chat ID
3. Test (all OK)
4. Save --> Error

### Environment

```markdown
- OS: DSM Synology V6
- Radarr:3.0.2.4552
- Using Reverse Proxy: No
```

### What branch are you running?

Develop

### Trace Logs?

2022-9-28 11:50:29.5|Debug|Api|[POST] /api/v3/notification/test: 200.OK (395 ms)

2022-9-28 11:50:30.5|Error|RadarrErrorPipeline|[POST /api/v3/notification]

[v3.0.2.4552] code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
table Notifications has no column named OnDelete
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 180
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 143
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.Create(TProviderDefinition definition) in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderFactory.cs:line 101
   at Radarr.Api.V3.ProviderModuleBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Radarr.Api.V3\ProviderModuleBase.cs:line 80
   at Radarr.Http.REST.RestModule`1.<set_CreateResource>b__43_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 206
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)

[AB#3840](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3840)

**Comment by ta264** [comment]
Upgrade radarr. That version is way too old to be reporting bug on.

**Comment by bakerboy448** [comment]
Based on the error you rolled back from a newer radarr version to an ancient radarr version.  That is not supported.
