### ISSUE TITLE
UNIQUE constraint failed: Collections.TmdbId - adding movie from Collection

### ISSUE THREAD

**Issue by Energiz3r** [Radarr/Radarr#7651]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Fresh install - yesterday off website, current release
Browse Movies > Collections or Movies > Discover and add movie from there
Raiders of the Lost Ark is the only movie to encounter this issue.
Torrent is added and finished but Radarr can't process the download. Restarting service hasn't helped

### Expected Behavior

Movie should appear in library

### Steps To Reproduce

1. Install Radarr latest release
2. configure qBittorrent
3. download Raiders of the Lost Ark via Collections / Discover

### Environment

```markdown
- OS: Server 2022 21H2
- Radarr: 4.2.4.6635
- Docker Install: No
- Using Reverse Proxy: NO
- Browser: N/A (Chrome / FF / Safari)
- Database: Sqlite 3.36.0
```

### What branch are you running?

Master

### Trace Logs?

```
code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
UNIQUE constraint failed: Collections.TmdbId
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1058
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 188
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 151
   at NzbDrone.Core.Movies.Collections.MovieCollectionService.AddCollection(MovieCollection newCollection) in D:\a\1\s\src\NzbDrone.Core\Movies\Collections\MovieCollectionService.cs:line 44
   at NzbDrone.Core.Movies.Collections.AddMovieCollectionService.AddMovieCollection(MovieCollection newCollection) in D:\a\1\s\src\NzbDrone.Core\Movies\Collections\AddMovieCollectionService.cs:line 49
   at NzbDrone.Core.Movies.RefreshMovieService.RefreshMovieInfo(Int32 movieId) in D:\a\1\s\src\NzbDrone.Core\Movies\RefreshMovieService.cs:line 135
   at NzbDrone.Core.Movies.RefreshMovieService.Execute(RefreshMovieCommand message) in D:\a\1\s\src\NzbDrone.Core\Movies\RefreshMovieService.cs:line 212
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 81
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44
```

**Comment by Phil57** [comment]
I have the same issue with this movie and version 4.5.2.7388
