### ISSUE TITLE
NzbDroneErrorPipeline

### ISSUE THREAD

**Issue by dhaos21** [Radarr/Radarr#767]
I Have been getting this error, it seems to have started since i have added some jackett indexers and then deleted them, not sure if that the cause.

EDIT: Update on this, i have since donw a fresh install of Radarr and the errors seems to have gone.

System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Download.Pending.PendingReleaseService.GetPendingQueue() in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Pending\PendingReleaseService.cs:line 133
   at NzbDrone.Api.Queue.QueueModule.GetQueueItems() in C:\projects\radarr-usby1\src\NzbDrone.Api\Queue\QueueModule.cs:line 32
   at NzbDrone.Api.Queue.QueueModule.GetQueue() in C:\projects\radarr-usby1\src\NzbDrone.Api\Queue\QueueModule.cs:line 27
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourceAll>b__32_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 111
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by halkeye** [comment]
Is there a trick to getting the stacktrace? I'm using the linuxserver docker image and i'm just getting:
```
17-2-17 10:08:03.1|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.299] System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
  at System.Net.WebConnection.BeginWrite (System.Net.HttpWebRequest request, System.Byte[] buffer, Int32 offset, Int32 size, System.AsyncCallback cb, System.Object state) <0x41d6d7c0 + 0x000a7> in <filename unknown>:0
  at System.Net.WebConnectionStream.BeginWrite (System.Byte[] buffer, Int32 offset, Int32 size, System.AsyncCallback cb, System.Object state) <0x410426e0 + 0x00a9f> in <filename unknown>:0
```

in my logs/rradar.txt

**Comment by halkeye** [comment]
oh sorry, this time its a different error :)
