### ISSUE TITLE
TMDB searches not working and all lists offline

### ISSUE THREAD

**Issue by rustiferch** [Radarr/Radarr#7692]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Radarr v4.2.4.6635. When searching for movies an error is thrown. "Invalid response received from TMDb"
Lists are also not available.

### Expected Behavior

Lists should be working and movies should be searchable.

### Steps To Reproduce

Radarr v4.2.4.6635. When searching for movies an error is thrown. "Invalid response received from TMDb"
Lists are also not available.

### Environment

```markdown
- OS: Windows 10
- Radarr: v4.2.4.6635
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome/Edge
- Database: SQL Lite
```

### What branch are you running?

Master

### Trace Logs?

[v4.2.4.6635] System.Net.Http.HttpRequestException: The request was aborted.
 ---> System.Net.Http.SocksException: SOCKS server failed to connect to the destination.
   at System.Net.Http.SocksHelper.EstablishSocks5TunnelAsync(Stream stream, String host, Int32 port, Uri proxyUri, NetworkCredential credentials, Boolean async)
   at System.Net.Http.SocksHelper.EstablishSocksTunnelAsync(Stream stream, String host, Int32 port, Uri proxyUri, ICredentials proxyCredentials, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishSocksTunnel(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.EstablishSocksTunnel(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 282
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 288
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 483

2022-10-20 21:43:24.9|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.2.4.6635] NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for 'terrifier' failed. Invalid response received from TMDb.
 ---> System.Net.Http.HttpRequestException: The request was aborted.
 ---> System.Net.Http.SocksException: SOCKS server failed to connect to the destination.

[AB#3949](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3949)

**Comment by nunong21** [comment]
I'm having the same issue.... What was the solution?

**Comment by rustiferch** [comment]
Mine was caused by my vpn/proxy provider seemingly ditching support of a socks5 proxy. I haven’t heard from them about it but all the socks5 details have disappeared from their list of provided services. 

Once I disabled the socks5 proxy in radar it works without issue.

**Comment by nunong21** [comment]
Well, I'm not connecting with any VPN...
