### ISSUE TITLE
Library Import Failure

### ISSUE THREAD

**Issue by klingonhighcmd** [Radarr/Radarr#7693]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When adding second library in Radarr for import receive Invalid Signature error. 
Second library is on same drive as first library (a mounted drive) - first library imports with no issue.
Second library has been validated as being compliant with the requirements for import "each movie is in its own folder within the root/library folder, contains release year, etc".

### Expected Behavior

Library should import and add contained movies to Radarr database.

### Steps To Reproduce

In Radarr, go to Movies/Library Import.
Select "Choose Another Folder".
Select Z:'\Movies and press "OK".
Screen turns white!
Click refresh on browser.
Page appears.  Unmapped folders for new path is "-".
Event log shows  multiples errors related to "Invalid Signature. : 'Z:\Movies'"

### Environment

```markdown
- OS: Windows 10 Pro
- Radarr: 4.2.4.6635
- Docker Install: I use docker for Overseer only
- Using Reverse Proxy: I use a reverse proxy for Radarr
- Browser: Same behavior on both latest versions of Chrome and Edge
- Database: Sqlite 3.36.0
```

### What branch are you running?

Master

### Trace Logs?

2022-10-20 23:24:23.9|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-10-20 23:24:23.9|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-10-20 23:24:23.9|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-10-20 23:24:24.4|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-10-20 23:24:24.4|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-10-20 23:24:24.4|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-10-20 23:24:31.4|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-10-20 23:24:31.4|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-10-20 23:24:31.4|Debug|RootFolderService|Generating list of unmapped folders
2022-10-20 23:24:31.5|Debug|RootFolderService|1 unmapped folders detected.
2022-10-20 23:24:31.5|Debug|RootFolderService|Generating list of unmapped folders
2022-10-20 23:24:31.5|Error|RootFolderService|Unable to get free space and unmapped folders for root folder Z:\Movies\

[v4.2.4.6635] System.IO.IOException: Invalid Signature. : 'Z:\Movies'
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.Directory.GetDirectories(String path)
   at NzbDrone.Core.RootFolders.RootFolderService.GetUnmappedFolders(String path, Dictionary`2 moviePaths) in D:\a\1\s\src\NzbDrone.Core\RootFolders\RootFolderService.cs:line 144
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in D:\a\1\s\src\NzbDrone.Core\RootFolders\RootFolderService.cs:line 208
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

2022-10-20 23:24:33.3|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-10-20 23:24:33.3|Debug|RootFolderService|Generating list of unmapped folders
2022-10-20 23:24:33.3|Debug|RootFolderService|1 unmapped folders detected.
2022-10-20 23:24:33.3|Debug|RootFolderService|Generating list of unmapped folders
2022-10-20 23:24:33.3|Error|RootFolderService|Unable to get free space and unmapped folders for root folder Z:\Movies\

[v4.2.4.6635] System.IO.IOException: Invalid Signature. : 'Z:\Movies'
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.Directory.GetDirectories(String path)
   at NzbDrone.Core.RootFolders.RootFolderService.GetUnmappedFolders(String path, Dictionary`2 moviePaths) in D:\a\1\s\src\NzbDrone.Core\RootFolders\RootFolderService.cs:line 144
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in D:\a\1\s\src\NzbDrone.Core\RootFolders\RootFolderService.cs:line 208
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

2022-10-20 23:24:37.5|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-10-20 23:24:42.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-10-20 23:24:42.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-10-20 23:24:42.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-10-20 23:24:45.7|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-10-20 23:24:49.6|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-10-20 23:24:49.6|Info|Database|Vacuuming Log database

**Comment by bakerboy448** [comment]
- debug logs are not trace logs
- What's the existing root folder path?

**Comment by klingonhighcmd** [comment]
Re debug logs are not trace logs; I set the logging level to trace, I
cleared the log, I repeated the steps that cause the issue, I copied and
pasted trace.radarr.txt into the appropriate window in the bug report. Not
sure why it looks like logging at the debug level not trace level. Happy to
try again if that would be helpful.

The existing path that has been working is Z:\MoviesNew (path to new repo
is Z:\Movies).

To provide some more context to this issue, I inherited someone else's Plex
server. I spent a lot of time validating the hygiene of that "new-to-me"
video content folder. I copied the folder to my 32 TB RAID 0 storage array
(Z:\Movies) and associated the folder with my Plex server to validate the
hygiene, etc. Then I attempted to import the content into Radarr and
experienced the issue I reported (after trying to find info about it in the
various blogs and wikis). BTW, I am a developer at Microsoft in Redmond,
Washington. So I try to be very careful about suggesting something is a bug
without digging into it on my own first.

Thank you for your help.

R,
Mark (aka Klingonhighcmd)

**Comment by bakerboy448** [comment]
It's not a Radarr exception or issue that's thrown. It's a dotnet System exception being thrown.

Looks like the below would be the relevant docs.

https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/error-messages-smb-connections

**Comment by klingonhighcmd** [comment]
I saw that article before. However, since I am running Windows 10 pro, not
a Windows Server 2012 or Windows 8 system and the other video repository on
the same mounted drive (Z:\MoviesNew) imported without the issue, I assumed
this issue is related to something else. I have now tried the suggested
test to see if the problem clears, it did not.

I have seen articles suggesting that there is a timeout associated with
mounted drives that contain large repos that can cause issues. Not sure if
that is fact or rumor. I can say that Z:\MoviesNew imported successfully;
it contained slightly over 200 movies. Z:\Movies - that does not import -
contains 2229 movies. I could try breaking that repo into smaller chunks,
but if that is what I have to do, I was hoping you might be able to give
some advice as to what size I should try.

R,
Mark
