### ISSUE TITLE
Collection refresh error handling problem

### ISSUE THREAD

**Issue by santam85** [Radarr/Radarr#7698]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When trying to refresh collections, at the first error returned from the server, Radarr will not try refreshing other collections.
For instance https://api.radarr.video/v1/movie/collection/726871

### Expected Behavior

When a collection refresh fails, Radar should skip it and continue with the others. 500 errors in the API should be resolved.

### Steps To Reproduce

Hit the refresh collection button. Make sure to have a few movies in library, a 500 error is bound to happen (can't understand from the logs what movie triggers it).

### Environment

```markdown
- OS: Ubuntu 2022.04
- Radarr: 
- Docker Install: Yes
- Using Reverse Proxy: Yes 
- Browser: Chrome
- Database: not sure
```

### What branch are you running?

Master

### Trace Logs?

NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://api.radarr.video/v1/movie/collection/726871]
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetCollectionInfo(Int32 tmdbId) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 125
   at NzbDrone.Core.Movies.RefreshCollectionService.RefreshCollectionInfo(Int32 collectionId) in D:\a\1\s\src\NzbDrone.Core\Movies\RefreshCollectionService.cs:line 61
   at NzbDrone.Core.Movies.RefreshCollectionService.Execute(RefreshCollectionsCommand message) in D:\a\1\s\src\NzbDrone.Core\Movies\RefreshCollectionService.cs:line 147
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 113
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44

**Comment by Qstick** [comment]
This is somewhat on purpose (handling of expected errors only) to encourage reporting of upstream issues which are not intentional and to ensure that an issue upstream doesn't result in further issues to a clients db given it could mean data integrity problems. 

In this case a change we pushed this weekend resulted in tossing NullRef errors when setting properties for movies which didn't yet have crew associated with them. This in turn kills a collection call which references said movies. 

This is fixed upstream now.

**Comment by bakerboy448** [comment]
@Qstick resolved?
