### ISSUE TITLE
Error while searching for movies with period (.) in the name (startIndex cannot be larger than length of string)

### ISSUE THREAD

**Issue by fremenfigure** [Radarr/Radarr#771]
**Description:**
Error while searching for [UFC Fight Night 103: Rodríguez vs. Penn]: startIndex cannot be larger than length of string.
Parameter name: startIndex

**Radarr Version:**
0.2.0.299

**Logs:**
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at NzbDrone.Core.Indexers.Newznab.NewznabRequestGenerator.GetSearchRequests(MovieSearchCriteria searchCriteria) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Newznab\NewznabRequestGenerator.cs:line 52
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.Fetch(MovieSearchCriteria searchCriteria) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 123
   at NzbDrone.Core.IndexerSearch.NzbSearchService.<>c__DisplayClass10_0.<MovieSearch>b__0(IIndexer indexer) in C:\projects\radarr-usby1\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:line 72
   at NzbDrone.Core.IndexerSearch.NzbSearchService.<>c__DisplayClass20_1.<Dispatch>b__0() in C:\projects\radarr-usby1\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:line 302

**Comment by Rusk85** [comment]
Whats the status on this? Anyone assigned to this? Still an issue?

**Comment by galli-leo** [comment]
This should be fixed now. If you still experience it let me know and I will reopen this issue.

**Comment by kanylbullen** [comment]
Has anyone been able to snatch UFC? I can't.
