### ISSUE TITLE
UnauthorizedAccessException Config.xml

### ISSUE THREAD

**Issue by SirAce135** [Radarr/Radarr#773]
**Description:**

First let me say THANK YOU!! I am so dang sick and tired of CP.
I am having an issue where I was able to open Radarr one time (downloaded, unzipped to  Radarr folder on desktop then double clicked Radarr.exe to run). Then Bitdefender deleted radarr.exe because it thought it was malicious. 

I killed the process, flagged the folder as an exclusion, unzipped the folder contents in its entirety again just in case. Now I am getting a Unauthorizedaccessexception c:\programdata\radarr\config.xml access denied.
I also saw mention of moving the contents of the radarr folder into a bin folder within programdata so I tried that, and no difference.

**Radarr Version:**
0.2.0.299

**Logs:**
[Info] Bootstrap: Starting Radarr - C:\ProgramData\Radarr\bin\Radarr.Console.exe - Version 0.2.0.299

[Fatal] ConsoleApp: EPIC FAIL!

[v0.2.0.299] System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\Radarr\config.xml' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at NzbDrone.Common.Disk.DiskProviderBase.WriteAllText(String filename, String contents) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 235
   at NzbDrone.Core.Configuration.ConfigFileProvider.SaveConfigFile(XDocument xDoc) in C:\projects\radarr-usby1\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 335
   at NzbDrone.Core.Configuration.ConfigFileProvider.SetValue(String key, Object value) in C:\projects\radarr-usby1\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 258
   at NzbDrone.Core.Configuration.ConfigFileProvider.<>c__DisplayClass45_0.<GetValue>b__0() in C:\projects\radarr-usby1\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 228
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in C:\projects\radarr-usby1\src\NzbDrone.Common\Cache\Cached.cs:line 81
   at NzbDrone.Core.Configuration.ConfigFileProvider.GetValue(String key, Object defaultValue, Boolean persist) in C:\projects\radarr-usby1\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 211
   at NzbDrone.Core.Configuration.ConfigFileProvider.get_LogLevel() in C:\projects\radarr-usby1\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 167
   at NzbDrone.Core.Instrumentation.ReconfigureLogging.Reconfigure() in C:\projects\radarr-usby1\src\NzbDrone.Core\Instrumentation\ReconfigureLogging.cs:line 22
   at Radarr.Host.Bootstrap.Start(ApplicationModes applicationModes, StartupContext startupContext) in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:line 61
   at Radarr.Host.Bootstrap.Start(StartupContext startupContext, IUserAlert userAlert, Action`1 startCallback) in C:\projects\radarr-usby1\src\NzbDrone.Host\Bootstrap.cs:line 40
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in C:\projects\radarr-usby1\src\NzbDrone.Console\ConsoleApp.cs:line 20

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
> I also saw mention of moving the contents of the radarr folder into a bin folder within programdata so I tried that, and no difference.


Don't do this.

Did you try running as admin? Seems like a permissions problem.

**Comment by SirAce135** [comment]
Yes, I tried running as admin. Same results

Thank you for the heads up about not running from radarr/bin/

**Comment by galli-leo** [comment]
Please delete the radarr folder in ProgramData and try the new installation instructions on the wiki.
