### ISSUE TITLE
`-nobrowser` option ignored when instance already running

### ISSUE THREAD

**Issue by alexreg** [Radarr/Radarr#7890]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Attempting to launch a second instance of Radarr (e.g., from the command line) results in a browser window being opened, despite `-nobrowser` being passed to the command line. Note, this also happens when `LaunchBrowser` is set to `False` in `config.xml`.

### Expected Behavior

No browser window should open.

### Steps To Reproduce

1. Launch an instance of Radarr.
2. Launch another instance of Radarr from the command line using `/Applications/Radarr.app/Contents/MacOS/Radarr -nobrowser`
3. Observe that a browser window is opened.

### Environment

```markdown
- OS: macOS 13.1
- Radarr: 4.2.4.6635
- Docker Install: N.A.
- Using Reverse Proxy: No 
- Browser: Safari 16.2
- Database: Sqlite 3.36.0
```

### What branch are you running?

Master

### Trace Logs?

2022-12-15 01:18:34.6|Trace|CommandQueueManager|Updating command status
2022-12-15 01:18:34.6|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-12-15 01:18:34.6|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2022-12-15 01:18:34.6|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2022-12-15 01:18:34.6|Trace|EventAggregator|Publishing CommandExecutedEvent
2022-12-15 01:18:34.6|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2022-12-15 01:18:34.6|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2022-12-15 01:18:34.6|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2022-12-15 01:18:34.6|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2022-12-15 01:18:34.6|Trace|CommandExecutor|DeleteLogFilesCommand <- DeleteLogFilesService [00:00:00.0040390]
2022-12-15 01:18:34.6|Trace|Http|Req: 148 [GET] /api/v3/command (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:34.6|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-12-15 01:18:34.6|Trace|CommandQueueManager|Getting all commands
2022-12-15 01:18:34.6|Trace|Http|Res: 148 [GET] /api/v3/command: 200.OK (2 ms)
2022-12-15 01:18:34.6|Debug|Api|[GET] /api/v3/command: 200.OK (2 ms)
2022-12-15 01:18:34.7|Trace|Http|Req: 149 [GET] /api/v3/log/file (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:34.7|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-12-15 01:18:34.7|Trace|Http|Res: 149 [GET] /api/v3/log/file: 200.OK (2 ms)
2022-12-15 01:18:34.7|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)
2022-12-15 01:18:37.2|Debug|ProcessProvider|Found 0 processes with the name: Radarr.Console
2022-12-15 01:18:37.2|Debug|ProcessProvider|Found 2 processes with the name: Radarr
2022-12-15 01:18:37.2|Debug|ProcessProvider| - [22181] Radarr
2022-12-15 01:18:37.2|Debug|ProcessProvider| - [21435] Radarr
2022-12-15 01:18:37.2|Info|SingleInstancePolicy|1 instance(s) of Radarr are running
2022-12-15 01:18:37.2|Warn|SingleInstancePolicy|Another instance of Radarr is already running.
2022-12-15 01:18:37.2|Info|BrowserService|Starting default browser. http://localhost:7878
2022-12-15 01:18:37.2|Info|ProcessProvider|Opening URL [http://localhost:7878]
2022-12-15 01:18:37.3|Fatal|Microsoft.AspNetCore.Hosting.Diagnostics|Application startup exception

[v4.2.4.6635] Radarr.Host.TerminateApplicationException: Application is being terminated. Reason : Another instance is already running
   at Radarr.Host.SingleInstancePolicy.PreventStartIfAlreadyRunning() in D:\a\1\s\src\NzbDrone.Host\SingleInstancePolicy.cs:line 37
   at NzbDrone.Host.Startup.EnsureSingleInstance(Boolean isService, IStartupContext startupContext, ISingleInstancePolicy instancePolicy) in D:\a\1\s\src\NzbDrone.Host\Startup.cs:line 306
   at NzbDrone.Host.Startup.Configure(IApplicationBuilder app, IStartupContext startupContext, Lazy`1 mainDatabaseFactory, Lazy`1 logDatabaseFactory, DatabaseTarget dbTarget, ISingleInstancePolicy singleInstancePolicy, InitializeLogger initializeLogger, ReconfigureLogging reconfigureLogging, IAppFolderFactory appFolderFactory, IProvidePidFile pidFileProvider, IConfigFileProvider configFileProvider, IRuntimeInfo runtimeInfo, IFirewallAdapter firewallAdapter, RadarrErrorPipeline errorHandler) in D:\a\1\s\src\NzbDrone.Host\Startup.cs:line 227
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)

2022-12-15 01:18:37.4|Info|Bootstrap|Application is being terminated. Reason : Another instance is already running
2022-12-15 01:18:37.5|Trace|Http|Req: 150 [GET] / (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:37.5|Debug|Radarr.Http.Authentication.NoAuthenticationHandler|AuthenticationScheme: None was successfully authenticated.
2022-12-15 01:18:37.5|Trace|Http|Res: 150 [GET] /: 200.OK (6 ms)
2022-12-15 01:18:37.5|Trace|Http|Req: 151 [GET] /initialize.js (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:37.5|Debug|Radarr.Http.Authentication.NoAuthenticationHandler|AuthenticationScheme: None was successfully authenticated.
2022-12-15 01:18:37.5|Trace|Http|Res: 151 [GET] /initialize.js: 200.OK (3 ms)
2022-12-15 01:18:37.7|Trace|Http|Req: 152 [GET] /api/v3/localization (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:37.7|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-12-15 01:18:37.7|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2022-12-15 01:18:37.7|Trace|Http|Res: 152 [GET] /api/v3/localization: 200.OK (16 ms)
2022-12-15 01:18:37.7|Debug|Api|[GET] /api/v3/localization: 200.OK (16 ms)
2022-12-15 01:18:38.0|Trace|Http|Req: 153 [GET] /api/v3/movie (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:38.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-12-15 01:18:38.0|Trace|ConfigService|Using default config value for 'movieinfolanguage' defaultValue:'1'
2022-12-15 01:18:38.0|Trace|ConfigService|Using default config value for 'availabilitydelay' defaultValue:'0'
2022-12-15 01:18:38.0|Trace|Http|Req: 154 [GET] /api/v3/customFilter (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:38.0|Trace|Http|Req: 155 [GET] /api/v3/collection (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:38.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-12-15 01:18:38.0|Trace|Http|Req: 157 [GET] /api/v3/language (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:38.0|Trace|Http|Req: 156 [GET] /api/v3/tag (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:38.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-12-15 01:18:38.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-12-15 01:18:38.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-12-15 01:18:38.0|Trace|Http|Res: 157 [GET] /api/v3/language: 200.OK (1 ms)
2022-12-15 01:18:38.0|Debug|Api|[GET] /api/v3/language: 200.OK (1 ms)
2022-12-15 01:18:38.0|Trace|Http|Res: 155 [GET] /api/v3/collection: 200.OK (4 ms)
2022-12-15 01:18:38.0|Debug|Api|[GET] /api/v3/collection: 200.OK (4 ms)
2022-12-15 01:18:38.0|Trace|Http|Req: 158 [GET] /api/v3/importlist (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:38.0|Trace|Http|Req: 159 [GET] /api/v3/qualityprofile (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:38.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-12-15 01:18:38.0|Trace|Http|Res: 153 [GET] /api/v3/movie: 200.OK (18 ms)
2022-12-15 01:18:38.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-12-15 01:18:38.0|Debug|Api|[GET] /api/v3/movie: 200.OK (18 ms)
2022-12-15 01:18:38.0|Trace|Http|Res: 158 [GET] /api/v3/importlist: 200.OK (1 ms)
2022-12-15 01:18:38.0|Debug|Api|[GET] /api/v3/importlist: 200.OK (1 ms)
2022-12-15 01:18:38.0|Trace|Http|Res: 159 [GET] /api/v3/qualityprofile: 200.OK (1 ms)
2022-12-15 01:18:38.0|Debug|Api|[GET] /api/v3/qualityprofile: 200.OK (1 ms)
2022-12-15 01:18:38.0|Trace|Http|Req: 160 [GET] /api/v3/indexerFlag (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:38.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-12-15 01:18:38.0|Trace|Http|Res: 154 [GET] /api/v3/customFilter: 200.OK (12 ms)
2022-12-15 01:18:38.0|Debug|Api|[GET] /api/v3/customFilter: 200.OK (12 ms)
2022-12-15 01:18:38.0|Trace|Http|Res: 160 [GET] /api/v3/indexerFlag: 200.OK (0 ms)
2022-12-15 01:18:38.0|Trace|Http|Res: 156 [GET] /api/v3/tag: 200.OK (13 ms)
2022-12-15 01:18:38.0|Debug|Api|[GET] /api/v3/indexerFlag: 200.OK (0 ms)
2022-12-15 01:18:38.0|Debug|Api|[GET] /api/v3/tag: 200.OK (13 ms)
2022-12-15 01:18:38.0|Trace|Http|Req: 161 [GET] /api/v3/config/ui (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:38.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-12-15 01:18:38.0|Trace|ConfigService|Using default config value for 'movieruntimeformat' defaultValue:'HoursMinutes'
2022-12-15 01:18:38.0|Trace|ConfigService|Using default config value for 'showrelativedates' defaultValue:'True'
2022-12-15 01:18:38.0|Trace|ConfigService|Using default config value for 'enablecolorimpairedmode' defaultValue:'False'
2022-12-15 01:18:38.0|Trace|ConfigService|Using default config value for 'movieinfolanguage' defaultValue:'1'
2022-12-15 01:18:38.0|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2022-12-15 01:18:38.0|Trace|Http|Res: 161 [GET] /api/v3/config/ui: 200.OK (1 ms)
2022-12-15 01:18:38.0|Debug|Api|[GET] /api/v3/config/ui: 200.OK (1 ms)
2022-12-15 01:18:38.0|Trace|Http|Req: 162 [GET] /api/v3/system/status (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:38.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-12-15 01:18:38.0|Trace|Http|Res: 162 [GET] /api/v3/system/status: 200.OK (1 ms)
2022-12-15 01:18:38.0|Debug|Api|[GET] /api/v3/system/status: 200.OK (1 ms)
2022-12-15 01:18:38.1|Trace|Http|Req: 163 [POST] /signalr/messages/negotiate?access_token=(removed)&negotiateVersion=1 (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:38.1|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: SignalR was successfully authenticated.
2022-12-15 01:18:38.1|Trace|Http|Res: 163 [POST] /signalr/messages/negotiate?access_token=(removed)&negotiateVersion=1: 200.OK (1 ms)
2022-12-15 01:18:38.1|Trace|Http|Req: 164 [GET] /api/v3/queue/status (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:38.1|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-12-15 01:18:38.1|Trace|Http|Res: 164 [GET] /api/v3/queue/status: 200.OK (1 ms)
2022-12-15 01:18:38.1|Debug|Api|[GET] /api/v3/queue/status: 200.OK (1 ms)
2022-12-15 01:18:38.1|Trace|Http|Req: 165 [GET] /api/v3/health (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:38.1|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-12-15 01:18:38.1|Trace|Http|Res: 165 [GET] /api/v3/health: 200.OK (0 ms)
2022-12-15 01:18:38.1|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2022-12-15 01:18:38.1|Trace|Http|Req: 166 [GET] /api/v3/rootFolder (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:38.1|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-12-15 01:18:38.1|Trace|Http|Req: 167 [GET] /api/v3/queue/details (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:38.1|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-12-15 01:18:38.1|Debug|RootFolderService|Generating list of unmapped folders
2022-12-15 01:18:38.1|Trace|ConfigService|Using default config value for 'recyclebin' defaultValue:''
2022-12-15 01:18:38.1|Debug|RootFolderService|1 unmapped folders detected.
2022-12-15 01:18:38.1|Trace|Http|Res: 167 [GET] /api/v3/queue/details: 200.OK (1 ms)
2022-12-15 01:18:38.1|Debug|Api|[GET] /api/v3/queue/details: 200.OK (1 ms)
2022-12-15 01:18:38.1|Trace|Http|Res: 166 [GET] /api/v3/rootFolder: 200.OK (2 ms)
2022-12-15 01:18:38.1|Debug|Api|[GET] /api/v3/rootFolder: 200.OK (2 ms)
2022-12-15 01:18:38.8|Trace|Http|Req: 168 [GET] /signalr/messages?access_token=(removed)&id=CmziXPd8Bed2D7IZUioS4w (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:38.8|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: SignalR was successfully authenticated.
2022-12-15 01:18:39.7|Trace|Http|Res: 168 [GET] /signalr/messages?access_token=(removed)&id=CmziXPd8Bed2D7IZUioS4w: 101.SwitchingProtocols (881 ms)
2022-12-15 01:18:41.7|Trace|Http|Req: 169 [GET] /logfile/radarr.trace.txt (from ::1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15)
2022-12-15 01:18:41.7|Debug|Radarr.Http.Authentication.NoAuthenticationHandler|AuthenticationScheme: None was successfully authenticated.

**Comment by bakerboy448** [comment]
fairly invalid usecase given that you can't run two instances of radarr without both having -data arguments

**Comment by bakerboy448** [comment]
And looking further - looks like you have a specific edge case actually.

the single instance check launches the UI if or some reason if it's already running....presumably to open the already running instance

https://github.com/Radarr/Radarr/blob/5790ebc558ad945d21e4a76c7002425e35900633/src/NzbDrone.Host/SingleInstancePolicy.cs#L36

**Comment by alexreg** [comment]
@bakerboy448 I agree it would be invalid in the case you actually wanted to run two instances, but consider the scenario where you just try to launch an instance without necessarily knowing an instance is already running. It should still respect configuration settings. Also, for the record, Sonarr does the "correct thing" (to me) and doesn't open a browser window in this scenario.
