### ISSUE TITLE
Latest update 4.3.2.6857 broken

### ISSUE THREAD

**Issue by DuvelCorp** [Radarr/Radarr#7969]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I was on version 4.2.4.6635 (25/09/2022) and  I have used the auto updater within Radarr to install the latest release and it somehow broke my installation.

I am on Ubuntu 22.04 (NON DOCKER) and a long time user. I have always used the internal auto updater and never had that kind of issue previously. 

After I launched the upgrade I lost the connection to Radarr

This is what the status said :
![image](https://user-images.githubusercontent.com/33682764/211107821-cef96003-56f8-4cc8-a035-9881f2f0a9f5.png)

I could not find any helpful log to figure it out

Tried to restart the service and no luck.

So I just reinstalled everything from scratch manually using 
`
wget --content-disposition 'http://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64'`

And everything is backup and running on the latest version. So my problem is fixed but I still  report this bug here just in case . 

Prior to reinstall manually, I have backup the old broken install folder so I can dig into it if you want to debug 

### Expected Behavior

Uprading with no issue?

### Environment

```markdown
- OS: Ubuntu 22.04
- Radarr: 4.2.4.6635
- Docker Install: none
- Using Reverse Proxy: none
- Browser: Firefox
- Database: Sqlite3
```

### What branch are you running?

Master

### Trace Logs?

seedbox@dmzseedbox:/media/seedbox/.config/Radarr/logs$ tail radarr.txt
2023-01-06 22:40:16.9|Info|InstallUpdateService|Verifying update package
2023-01-06 22:40:17.1|Info|InstallUpdateService|Update package verified successfully
2023-01-06 22:40:17.1|Info|InstallUpdateService|Extracting Update package
2023-01-06 22:40:20.0|Info|InstallUpdateService|Update package extracted successfully
2023-01-06 22:40:20.0|Info|BackupService|Starting Backup
2023-01-06 22:40:31.2|Info|InstallUpdateService|Preparing client
2023-01-06 22:40:32.0|Info|InstallUpdateService|Starting update client /tmp/radarr_update/Radarr.Update
2023-01-06 22:40:32.0|Info|InstallUpdateService|Radarr will restart shortly.
2023-01-06 22:40:36.7|Info|InstallUpdateService|Deleting old update files
2023-01-06 22:40:36.7|Info|InstallUpdateService|Downloading update 4.3.2.6857
seedbox@dmzseedbox:/media/seedbox/.config/Radarr/logs$ 

[AB#4656](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4656)

**Comment by bakerboy448** [comment]
Most likely your system wiped out the /tmp directory that radarr uses for the update thus removing critical files and both the update and rollback failed.  The [updater logs](https://wiki.servarr.com/en/radarr/troubleshooting#update-logs-location) would confirm this.

for future reference the logs you provided are not the required trace logs for bug reports. please refer to the wiki article the bug report template links for how to get and provide trace logs for future bug reports.

**Comment by DuvelCorp** [comment]
I hate bots.
This is not a support request this is a bug report.
I dont need any support as I solved the issue myself.

**Comment by DuvelCorp** [comment]
Here are the Update logs
```

2023-01-06 22:40:36.7|Debug|DiskTransferService|Copy [/tmp/radarr_update/Radarr/Microsoft.Win32.Primitives.dll] > [/opt/Radarr/Microsoft.Win32.Primitives.dll]
2023-01-06 22:40:36.7|Error|InstallUpdateService|Failed to copy upgrade package to target folder.

[v4.3.2.6857] System.IO.FileNotFoundException: File doesn't exist: /tmp/radarr_update/Radarr/Microsoft.Win32.Primitives.dll
   at NzbDrone.Common.Disk.DiskProviderBase.GetFileSize(String path)
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskTransferService.MirrorFolder(String sourcePath, String targetPath)
   at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start(String installationFolder, Int32 processId)


2023-01-06 22:40:36.8|Info|BackupAndRestore|Attempting to rollback upgrade
2023-01-06 22:40:36.8|Debug|DiskTransferService|Mirror Folder [/tmp/radarr_update/radarr_backup/] > [/opt/Radarr]
2023-01-06 22:40:36.8|Info|TerminateNzbDrone|Killing all running processes
2023-01-06 22:40:36.8|Debug|ProcessProvider|Found 0 processes with the name: Radarr.Console
2023-01-06 22:40:36.8|Debug|ProcessProvider|Found 0 processes to kill
2023-01-06 22:40:36.8|Debug|ProcessProvider|Found 1 processes with the name: Radarr
2023-01-06 22:40:36.8|Debug|ProcessProvider| - [915] Radarr
2023-01-06 22:40:36.8|Debug|ProcessProvider|Found 1 processes to kill
2023-01-06 22:40:36.8|Debug|ProcessProvider|Killing process: 915 [Radarr]
2023-01-06 22:40:36.8|Info|ProcessProvider|[915]: Killing process
2023-01-06 22:40:36.8|Info|ProcessProvider|[915]: Waiting for exit
2023-01-06 22:40:36.8|Info|ProcessProvider|[915]: Process terminated successfully
2023-01-06 22:40:36.9|Warn|ProcessProvider|Cannot find process with id: 915
2023-01-06 22:40:36.9|Info|InstallUpdateService|Waiting for external auto-restart.
2023-01-06 22:40:37.9|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2023-01-06 22:40:38.9|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2023-01-06 22:40:39.9|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2023-01-06 22:40:40.9|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2023-01-06 22:40:41.9|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2023-01-06 22:40:42.9|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2023-01-06 22:40:43.9|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2023-01-06 22:40:44.9|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2023-01-06 22:40:45.9|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2023-01-06 22:40:46.9|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2023-01-06 22:40:46.9|Debug|ProcessProvider|Found 0 processes with the name: Radarr
2023-01-06 22:40:46.9|Info|StartNzbDrone|Starting Radarr
2023-01-06 22:40:46.9|Info|StartNzbDrone|Starting Radarr
2023-01-06 22:40:46.9|Debug|ProcessProvider|Starting /opt/Radarr/Radarr /data=/media/seedbox/.config/Radarr /nobrowser
2023-01-06 22:40:46.9|Fatal|UpdateApp|An error has occurred while applying update package.

[v4.3.2.6857] System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/opt/Radarr/Radarr' with working directory '/'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt>
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NzbDrone.Common.Processes.ProcessProvider.SpawnNewProcess(String path, String args, StringDictionary environmentVariables, Boolean noWindow)
   at NzbDrone.Update.UpdateEngine.StartNzbDrone.Start(String installationFolder, String fileName)
   at NzbDrone.Update.UpdateEngine.StartNzbDrone.StartWinform(String installationFolder)
   at NzbDrone.Update.UpdateEngine.StartNzbDrone.Start(AppType appType, String installationFolder)
   at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start(String installationFolder, Int32 processId)
   at NzbDrone.Update.UpdateApp.Start(String[] args)
   at NzbDrone.Update.UpdateApp.Main(String[] args)
```

My system didn't wipe anything (I have a serious system).
my /tmp dir is still there there and is there for long.
Here's a litlle peak to it 
![image](https://user-images.githubusercontent.com/33682764/211110782-25d73113-33b5-43fb-89ac-7feef5ef3f3b.png)

So the issue is on your side and not mine.

On a side note:  I have no issue and I am only there to help you. But I have the impression of being an annoyance for reporting a bug. I will probably refrain myself to do it next time.

**Comment by bakerboy448** [comment]
> File doesn't exist: /tmp/radarr_update/Radarr/Microsoft.Win32.Primitives.dll

this is due to the file being deleted from the directory by your system. 

> Mirror Folder [/tmp/radarr_update/radarr_backup/] > [/opt/Radarr]

followed by

>[v4.3.2.6857] System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/opt/Radarr/Radarr' with working directory '/'. No such file or directory

indicates that your system deleted at least `/tmp/radarr_update/radarr_backup/Radarr` and likely additional files.

> my /tmp dir is still there there and is there for long.

/tmp itself existing doesn't matter.  the aforementioned files/folders being removed do matter.

>So the BUG is on your side and not mine.

I don't see how that is the case.  The logs clearly confirm it is in fact not a bug.

- the file exists in the tarball zip
- the tarball and file can be assumed to have been extracted to `/tmp/radarr_update/Radarr/` (logs would confirm)
- when Radarr went to copy the file from the tmp extracted update to the binary folder the file was no longer there as it was removed by the system or another application.

There's nothing in Radarr that would result in  a single file being deleted during the update process.  Given the updater works for hundreds of thousands of users and this issue is seen only a handful of times - every single time has indicated that something other than Radarr / the Radarr Updater wiped the critical update files.

> But I have the impression of being an annoyance for reporting a bug. 

It's not a bug.

>  I will probably refrain myself to do it next time.

As the bug report template says **if you are not 100% certain this is a bug please go to our Reddit or Discord first**
The only way you could be 100% certain would be providing trace logs of Radarr deleting the files prior to it trying to copy them for the update.  You'll have no logs of these as it's not something that would occur.
