### ISSUE TITLE
Conenction between SabNZBd and Radarr fails sometimes. Timeout related? error: System.Net.Sockets.SocketException (103): Connection aborted

### ISSUE THREAD

**Issue by jaannnis** [Radarr/Radarr#7972]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Some releases get sent to SabNZBd multiple times. As I interpret it, Radarr thinks the download sent to SabNZBd has failed and sends another release. This gets repeated till Radarr thinks the download got added successful.
Here is the relvant log:
```
2023-01-08 14:16:05.1|Warn|ProcessDownloadDecisions|Couldn't add report to download queue. 1917.2019.MULTi.COMPLETE.UHD.BLURAY-SharpHD DDL - NIMA4K.org

[v4.3.2.6857] System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection aborted.
 ---> System.Net.Sockets.SocketException (103): Connection aborted
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 185
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.DownloadNzb(Byte[] nzbData, String filename, String category, Int32 priority, SabnzbdSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 55
   at NzbDrone.Core.Download.Clients.Sabnzbd.Sabnzbd.AddFromNzbFile(RemoteMovie remoteMovie, String filename, Byte[] fileContent) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Sabnzbd\Sabnzbd.cs:line 45
   at NzbDrone.Core.Download.UsenetClientBase`1.Download(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\UsenetClientBase.cs:line 82
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 73
   at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions(List`1 decisions) in D:\a\1\s\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:line 76


2023-01-08 14:16:05.1|Trace|ProcessDownloadDecisions|Grabbing from Indexer SceneNZBs at priority 40.
```

I know this looks like  network problem but I don't think so, both applications run in docker and in network host-mode on the same host-machine. Sonarr also uses the sabnzbd container and never had this happen even once.

Radarr also adds all (in this case three) downloads to the Activity Tab:
![image](https://user-images.githubusercontent.com/20789461/211199381-8f8a5b9d-ef55-4051-b684-5a3adc999332.png)

If I don't intervene all three releases get downloaded but Radarr will only import one, because as soon as it imports the frst download, all the others are tagged either as "Quality for existing file on disk is of equal or higher preference", "Existing file meets cutoff:" or "Existing file and the Quality profile does not allow upgrades".

Here is the full relevant log (not debug/trace):
```
2023-01-08 14:16:05.1|Warn|ProcessDownloadDecisions|Couldn't add report to download queue. 1917.2019.MULTi.COMPLETE.UHD.BLURAY-SharpHD DDL - NIMA4K.org

[v4.3.2.6857] System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection aborted.
 ---> System.Net.Sockets.SocketException (103): Connection aborted
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 185
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.DownloadNzb(Byte[] nzbData, String filename, String category, Int32 priority, SabnzbdSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 55
   at NzbDrone.Core.Download.Clients.Sabnzbd.Sabnzbd.AddFromNzbFile(RemoteMovie remoteMovie, String filename, Byte[] fileContent) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Sabnzbd\Sabnzbd.cs:line 45
   at NzbDrone.Core.Download.UsenetClientBase`1.Download(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\UsenetClientBase.cs:line 82
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 73
   at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions(List`1 decisions) in D:\a\1\s\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:line 76


2023-01-08 14:16:06.2|Info|Sabnzbd|Adding report [1917.2019.MULTi.COMPLETE.UHD.BLURAY-SharpHD DDL - NIMA4K.org] to the queue.
2023-01-08 14:16:21.5|Info|DownloadService|Report sent to SABnzbd from indexer NZBHydra. Der Herr der Ringe Die Rueckkehr des Koenigs 2003 Extended German DTSHD DL 2160p UHD BluRay HDR x265 - NIMA4K
2023-01-08 14:16:21.5|Info|MovieSearchService|Movie search completed. 1 reports downloaded.
2023-01-08 14:17:46.2|Warn|ProcessDownloadDecisions|Couldn't add report to download queue. 1917.2019.MULTi.COMPLETE.UHD.BLURAY-SharpHD DDL - NIMA4K.org

[v4.3.2.6857] System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection aborted.
 ---> System.Net.Sockets.SocketException (103): Connection aborted
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 185
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.DownloadNzb(Byte[] nzbData, String filename, String category, Int32 priority, SabnzbdSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 55
   at NzbDrone.Core.Download.Clients.Sabnzbd.Sabnzbd.AddFromNzbFile(RemoteMovie remoteMovie, String filename, Byte[] fileContent) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Sabnzbd\Sabnzbd.cs:line 45
   at NzbDrone.Core.Download.UsenetClientBase`1.Download(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\UsenetClientBase.cs:line 82
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 73
   at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions(List`1 decisions) in D:\a\1\s\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:line 76


2023-01-08 14:17:46.8|Info|Sabnzbd|Adding report [1917.2019.German.DL.HDR10Plus.2160p.UHD.BluRay.x265.iNTERNAL-ENDSTATiON] to the queue.
2023-01-08 14:19:03.6|Info|DownloadService|Report sent to SABnzbd from indexer NZBHydra. 1917.2019.German.DL.HDR10Plus.2160p.UHD.BluRay.x265.iNTERNAL-ENDSTATiON
2023-01-08 14:19:03.7|Info|MovieSearchService|Movie search completed. 1 reports downloaded.
```

The SabNZBd Log from that time looks pretty normal, just accepts all three API hits and adds them to the queue.  Do I run into a timeout issue? :
```
2023-01-08 14:14:25,847::INFO::[nzbparser:89] Attempting to add 1917.2019.MULTi.COMPLETE.UHD.BLURAY-SharpHD DDL - NIMA4K.org.nzb
2023-01-08 14:14:25,895::INFO::[filesystem:701] Creating directories: /shared/merged/downloads/sabnzbd/incomplete/1917.2019.MULTi.COMPLETE.UHD.BLURAY-SharpHD DDL - NIMA4K.org
2023-01-08 14:14:26,268::INFO::[filesystem:701] Creating directories: /shared/merged/downloads/sabnzbd/incomplete/1917.2019.MULTi.COMPLETE.UHD.BLURAY-SharpHD DDL - NIMA4K.org/__ADMIN__
2023-01-08 14:14:26,379::INFO::[filesystem:1233] Saving /shared/merged/downloads/sabnzbd/incomplete/1917.2019.MULTi.COMPLETE.UHD.BLURAY-SharpHD DDL - NIMA4K.org/__ADMIN__/1917.2019.MULTi.COMPLETE.UHD.BLURAY-SharpHD DDL - NIMA4K.org.nzb.gz
2023-01-08 14:16:06,894::INFO::[nzbparser:89] Attempting to add 1917.2019.MULTi.COMPLETE.UHD.BLURAY-SharpHD DDL - NIMA4K.org.nzb
2023-01-08 14:16:06,983::INFO::[filesystem:701] Creating directories: /shared/merged/downloads/sabnzbd/incomplete/1917.2019.MULTi.COMPLETE.UHD.BLURAY-SharpHD DDL - NIMA4K.org.1
2023-01-08 14:16:07,613::INFO::[filesystem:701] Creating directories: /shared/merged/downloads/sabnzbd/incomplete/1917.2019.MULTi.COMPLETE.UHD.BLURAY-SharpHD DDL - NIMA4K.org.1/__ADMIN__
2023-01-08 14:16:08,099::INFO::[filesystem:1233] Saving /shared/merged/downloads/sabnzbd/incomplete/1917.2019.MULTi.COMPLETE.UHD.BLURAY-SharpHD DDL - NIMA4K.org.1/__ADMIN__/1917.2019.MULTi.COMPLETE.UHD.BLURAY-SharpHD DDL - NIMA4K.org.nzb.gz
2023-01-08 14:17:47,020::INFO::[nzbparser:89] Attempting to add 1917.2019.German.DL.HDR10Plus.2160p.UHD.BluRay.x265.iNTERNAL-ENDSTATiON.nzb
2023-01-08 14:17:47,305::INFO::[filesystem:701] Creating directories: /shared/merged/downloads/sabnzbd/incomplete/1917.2019.German.DL.HDR10Plus.2160p.UHD.BluRay.x265.iNTERNAL-ENDSTATiON
2023-01-08 14:17:48,269::INFO::[filesystem:701] Creating directories: /shared/merged/downloads/sabnzbd/incomplete/1917.2019.German.DL.HDR10Plus.2160p.UHD.BluRay.x265.iNTERNAL-ENDSTATiON/__ADMIN__
2023-01-08 14:17:48,751::INFO::[filesystem:1233] Saving /shared/merged/downloads/sabnzbd/incomplete/1917.2019.German.DL.HDR10Plus.2160p.UHD.BluRay.x265.iNTERNAL-ENDSTATiON/__ADMIN__/1917.2019.German.DL.HDR10Plus.2160p.UHD.BluRay.x265.iNTERNAL-ENDSTATiON.nzb.gz
2023-01-08 14:19:03,692::INFO::[notifier:123] Sending notification: NZB added to queue - 1917.2019.German.DL.HDR10Plus.2160p.UHD.BluRay.x265.iNTERNAL-ENDSTATiON.nzb (type=download, job_cat=radarr)
2023-01-08 14:20:38,625::INFO::[notifier:123] Sending notification: NZB added to queue - 1917.2019.MULTi.COMPLETE.UHD.BLURAY-SharpHD DDL - NIMA4K.org.nzb (type=download, job_cat=radarr)
2023-01-08 14:21:36,595::INFO::[notifier:123] Sending notification: NZB added to queue - 1917.2019.MULTi.COMPLETE.UHD.BLURAY-SharpHD DDL - NIMA4K.org.nzb (type=download, job_cat=radarr)
```

Only thing that sticks to my eye is that SabNZBd takes over 4 minutes between the ``Attempting to add foo.nzb`` and ``Sending notification: NZB added to queue - foo`` the first two times, the succesfull attempt takes less than 4 minutes. But this in it self doesn't make much sense as Radarr isn't even waiting 2 minutes to send a new file. 

I don't have any other ideas, just to be clear and have a few facts:

- upgrades are disabled in the profile
- the server runs on beefy hardware and doesn't have any high load
- Sonarr works as expected, even when adding 20 releases at once. (Queue of SabNZBd was pretty empty in the example above)
- no SSL/proxy between these two, not even docker proxy, just a direct https request
- not having any problems with any other application that uses this SabNZBd (API).

### Expected Behavior

One release gets processed, not multiple with the same specs.

### Steps To Reproduce

unsure, sorry. I'll play around a bit more and edit if I find out.

### Environment

```markdown
- OS: Ubuntu 22.04.1
- Radarr: 4.3.2.6857
- Docker Install: Yes (linuxserver/radarr:latest)
- Using Reverse Proxy: not between Radarr and Download Client
- Browser: /
- Database: default (Sqlite 3.36.0)
```

### What branch are you running?

Master

### Trace Logs?

unfortunately really long and containing other releases in between, but every log mentioned above is in there:
[trace.log](https://github.com/Radarr/Radarr/files/10368641/trace.log)

[AB#4663](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4663)

**Comment by bakerboy448** [comment]
> The operation was canceled.

sab failed to respond in 100s or less
