### ISSUE TITLE
downloaded movie not picked up due to ffprobe failing with error: Picture size 0x0 is invalid

### ISSUE THREAD

**Issue by Pierric82** [Radarr/Radarr#7979]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

A series of movies downloaded on Sunday have been downloaded successfully by Transmission, but have not been picked up by Radarr. They are stuck as Downloading in Radarr. Looking at the logs, Radarr repeatedly attempt to process them via ffprobe, but ffprobe fails.

Here is the _tail_ of the ffprobe output when manually run on one of the files in question, from inside the container (proving the file can be accessed, is partially processed, but fails, possibly due to subtitles stream):
```
Stream #0:3(eng): Subtitle: dvd_subtitle
    Metadata:
      BPS             : 6020
      BPS-eng         : 6020
      DURATION        : 01:20:22.209000000
      DURATION-eng    : 01:20:22.209000000
      NUMBER_OF_FRAMES: 2500
      NUMBER_OF_FRAMES-eng: 2500
      NUMBER_OF_BYTES : 3628936
      NUMBER_OF_BYTES-eng: 3628936
      _STATISTICS_WRITING_APP: mkvmerge v7.7.0 ('Six Voices') 64bit built on Feb 28 2015 23:39:33
      _STATISTICS_WRITING_APP-eng: mkvmerge v7.7.0 ('Six Voices') 64bit built on Feb 28 2015 23:39:33
      _STATISTICS_WRITING_DATE_UTC: 2021-01-14 19:15:12
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-01-14 19:15:12
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[dvdsub @ 0x3aa3980] [IMGUTILS @ 0x7ffeb933f300] Picture size 0x0 is invalid
Could not open codec for input stream 3
```

I have posted the full ffprobe output (edited for movie title) at https://pastebin.com/AsfD9tRu

This is what Docker logs, for each file (the main movie file as well as the included Sample MKV):
```
2023-01-09T17:58:30.740146030Z [Error] VideoFileInfoReader: Unable to parse media info from file: /data/torrents/movie/movie.mkv 
2023-01-09T17:58:30.740220599Z 
2023-01-09T17:58:30.740236160Z [v4.3.2.6857] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - [matroska,webm @ 0x2ae86c0] Unsupported encoding typePicture size 0x0 is invalid
2023-01-09T17:58:30.740250818Z [dvdsub @ 0x2afb700] [IMGUTILS @ 0x7ffe611ac100] Picture size 0x0 is invalid
2023-01-09T17:58:30.740264494Z [dvdsub @ 0x2bef840] [IMGUTILS @ 0x7ffe611ac420] Picture size 0x0 is invalid)
2023-01-09T17:58:30.740277965Z    at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
2023-01-09T17:58:30.740291646Z    at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MediaInfo\VideoFileInfoReader.cs:line 129
2023-01-09T17:58:30.740306061Z 
2023-01-09T17:58:30.740319013Z 
2023-01-09T17:58:30.741177671Z [Error] DetectSample: Failed to get runtime from the file, make sure ffprobe is available 
```

Sometimes the line with `[dvdsub ...` at the beginning appears twice like here, sometimes only once, but the rest is always the same.

### Expected Behavior

The movie should be picked up and moved to the media folder as other movies do.
As it happens, manual import does work.

### Steps To Reproduce

This happens with Radarr running on Docker with the following config (Ansible format, sorry):

docker_container:
    image: 	lscr.io/linuxserver/radarr:latest
    name: ms_radarr
    volumes:
      - "{{ arrpath }}/radarr:/config"
      - "{{ mediapath }}/data:/data"
    state: started
    restart_policy: unless-stopped
    network_mode: moviestack
    ports:
      - "7878:7878"
    env:
      PUID: "1000"
      PGID: "1000"

The container was updated to the latest version of the image on the 6th of Jan (amd64 architecture).

As to further reproducibility, apologies, I'm not sure how to further help without referring specifically to the movie in question, which may not be welcome on a public forum like this.

### Environment

```markdown
- OS: Debian 11 running Docker
- Radarr: 4.3.2.6857-ls159 by linuxserver.io
- Docker Install: see above
- Using Reverse Proxy: nginx (Swag container by linuxserver.io)
- Browser: Vivaldi 4.6
- Database: nothing special, running out of the box via the container (SQLite?)
```

### What branch are you running?

Master

### Trace Logs?

See above for an edited extract. I can provide longer logs on demand, but I'm unsure about editing all the titles out in a full log...

[AB#4680](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4680)

**Comment by tandy626** [comment]
Thanks for your issue report. I am having the same issue. I’ve tried consoling into the container and updating ffmpeg and updating to the nightly release with no change when retrying.
One thing I did notice, if I leave the container running long enough, it seems to strike luck in some cases. 

I started experiencing this behavior on a clean install, the only thing I did was attempt to import an existing library. On import the container was only able to import 64 of 1208.  Leaving the container running and left alone for 24 hours, it came to its senses with 272 additional. Total of 296. Hope this info is useful, and maybe the activity will value priority towards a resolution.

**Comment by Zindaar** [comment]
on a somewhat related note, a succesfully imported movie also keeps throwing the "ffprobe exited with non-zero exit-code" when there is no or invalid metadata

2024-03-01 04:01:57.8|Error|VideoFileInfoReader|Unable to parse media info from file: G:\[redacted](1994)\[redacted](1994).avi

[v5.4.0.8636] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - G:\[redacted] (1994)\[redacted](1994).avi: Invalid data found when processing input)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in ./Radarr.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs:line 140
