### ISSUE TITLE
Can't connect to NZBhydra:  "The request was aborted: Could not create SSL/TLS secure channel"

### ISSUE THREAD

**Issue by seanvree** [Radarr/Radarr#802]
Radarr Version 0.2.0.299
NZBHydra Version: Current version: 0.2.206

**Description:**

Can't connect to NZBHydra from Radarr/sonarr. 

I can hit the NZBHydra from the webUI.  

No reverse proxy currently, all three tools on the same box. 

Reference issue from /NZBHYDRA:

https://github.com/theotherp/nzbhydra/issues/560

**Logs:**

Unable to connect to indexer: The request was aborted: Could not create SSL/TLS secure channel

System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 74
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 58
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 63
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 311
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 295
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 3

**Comment by galli-leo** [comment]
Which mono version are you using?

**Comment by seanvree** [comment]
Mono JIT compiler version 4.6.2 (Visual Studio built mono)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           normal
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  x86
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

**Comment by galli-leo** [comment]
Can you try and install libcurl3? And restar radarr.

**Comment by seanvree** [comment]
@Galli-leo  

Yup, that did it. Wasn't easy install that on Windows BTW.

What changed?

**Comment by galli-leo** [comment]
Wait how are you using mono on windows?

**Comment by seanvree** [comment]
@galli-leo  - Cygwin

**Comment by galli-leo** [comment]
@seanvree Why are you not using the normal windows version? Much easier to handle.

**Comment by seanvree** [comment]
@galli-leo I have a bunch of other applications that I'm running that require it. 

What caused the original error?  Do you know?

**Comment by galli-leo** [comment]
@seanvree Well a not up to date curl version in mono causes the SSL handshake to fail, probably because the server does not accept that version of SSL/TLS anymore since it's insecure.

**Comment by seanvree** [comment]
@galli-leo got it.  Thx.

**Comment by seanvree** [comment]
@galli-leo  - Does radarr work with mono 64bit?  Do you know?

**Comment by seanvree** [comment]
Hey guys, these errors are back. It's only happening in Radarr and NOT sonarr.   And it also seems to be intermittent which is weird.  There's a bug somewhere. 


17-2-23 17:41:45.4|Debug|NewznabCapabilitiesProvider|Failed to get capabilities from https://192.168.1.20:5075: The request was aborted: Could not create SSL/TLS secure channel.

[v0.2.0.375] System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 74
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 58
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 63
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 186
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 54

17-2-23 17:41:45.4|Debug|NewznabCapabilitiesProvider|Failed to get capabilities from https://192.168.1.20:5075: The request was aborted: Could not create SSL/TLS secure channel.

[v0.2.0.375] System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 74
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 58
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 63
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 186
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 54

17-2-23 17:41:45.4|Debug|Newznab|Downloading Feed https://192.168.1.20:5075/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100
17-2-23 17:41:45.4|Warn|Newznab|Unable to connect to indexer

[v0.2.0.375] System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 74
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 58
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 63
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 311
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 295
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324

17-2-23 17:41:45.4|Debug|NewznabCapabilitiesProvider|Failed to get capabilities from https://192.168.1.20:5075: The request was aborted: Could not create SSL/TLS secure channel.

[v0.2.0.375] System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 74
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 58
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 63
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 186
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 54

**Comment by onedr0p** [comment]
Simple: don't use cardigann

**Comment by seanvree** [comment]
@onedr0p  - I'm not. NZBhydra
