### ISSUE TITLE
The string can't be left empty, null or consist of only whitespaces.

### ISSUE THREAD

**Issue by randallc79** [Radarr/Radarr#8053]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I enter or edit an existing connection (example plex media server) and click "Test" or "Save".  I get a red "!" and it will not save.

### Expected Behavior

When I click "test", it should show "ok" or I click save, it should save and close.

### Steps To Reproduce

From the [RADARR Web GUI] -> Settings -> Connect -> [Connections] ->

edit or create a new connect.

### Environment

```markdown
- OS: "Debian GNU/Linux 11 (bullseye)"
- Radarr: 4.3.2.6857 / 4.3.2.6857-ls160 by linuxserver.io
- Docker Install: Docker Engine - Community / 20.10.23
- Using Reverse Proxy: no
- Browser: Chrome & Firefox
- Database:
```

### What branch are you running?

Master

### Trace Logs?

System.ArgumentException: The string can't be left empty, null or consist of only whitespaces. (Parameter 'key')
   at NzbDrone.Common.EnsureThat.EnsureStringExtensions.IsNotNullOrWhiteSpace(Param`1 param) in D:\a\1\s\src\NzbDrone.Common\EnsureThat\EnsureStringExtensions.cs:line 17
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 104
   at NzbDrone.Core.Notifications.Plex.PlexTv.PlexTvService.Ping(String authToken) in D:\a\1\s\src\NzbDrone.Core\Notifications\Plex\PlexTv\PlexTvService.cs:line 95
   at NzbDrone.Core.Notifications.Plex.Server.PlexServer.Test() in D:\a\1\s\src\NzbDrone.Core\Notifications\Plex\Server\PlexServer.cs:line 142
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.Test(TProviderDefinition definition) in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderFactory.cs:line 81
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 191
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 142
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

[AB#4830](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4830)

**Comment by bakerboy448** [comment]
- Please provide the required trace logs the template notes is bug reports; not just the error saying an error occurred. For more information see the bug report template link's to the wiki.
- Screenshot would likely be helpful to understand what's up - with any token/creds replace with generic

**Comment by randallc79** [comment]
![Capture0](https://user-images.githubusercontent.com/7954932/215955110-5a5f4f5a-53c2-4bd0-a9b6-bdfa4e61df97.PNG)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/10553458/radarr.debug.txt)
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/10553460/radarr.trace.txt)
[radarr.txt](https://github.com/Radarr/Radarr/files/10553461/radarr.txt)

**Comment by bakerboy448** [comment]
Pretty sure the issue is going to be you didn't  `Authenticate with Plex.tv` and thus the auth token is blank & the error is valid.

Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

can reopen later if it turns out to be a bug

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/commit/8fe81b428a4d22478da41dae1791c3368be26379

To keep the connection to plex alive and authorized is when ping was added and thus when the auth token is now required.

same thing in sonarr v4

**Comment by randallc79** [comment]
Appreciate the help!   Also, nice to get a good answer to why.  But for people like me who don't have plex.tv accounts (and never needed them).  This is gonna be a good reason to switch from plex.
