### ISSUE TITLE
System.IO.FileNotFoundException for srt files on DownloadedMoviesScan API v3 call

### ISSUE THREAD

**Issue by Rouzax** [Radarr/Radarr#8057]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I'm importing using the v3 API in Radarr but during import I see some weird stuff happening in the log
The movie and subtitles import successful 

The first weird thing I see is:
```
2023-02-03 16:35:48.7|Debug|MediaFileAttributeService|Unable to apply folder permissions to: 
```

and then on the srt files:
```
2023-02-03 16:35:48.7|Debug|MediaFileAttributeService|C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.5.en.srt

[v4.4.0.6882] System.IO.FileNotFoundException: C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.5.en.srt
   at System.Security.AccessControl.NativeObjectSecurity.CreateInternal(ResourceType resourceType, Boolean isContainer, String name, SafeHandle handle, AccessControlSections includeSections, Boolean createByName, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   at System.Security.AccessControl.NativeObjectSecurity..ctor(Boolean isContainer, ResourceType resourceType, String name, AccessControlSections includeSections, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   at System.Security.AccessControl.FileSystemSecurity..ctor(Boolean isContainer, String name, AccessControlSections includeSections, Boolean isDirectory)
   at System.IO.FileSystemAclExtensions.GetAccessControl(FileInfo fileInfo, AccessControlSections includeSections)
   at NzbDrone.Windows.Disk.DiskProvider.InheritFolderPermissions(String filename) in D:\a\1\s\src\NzbDrone.Windows\Disk\DiskProvider.cs:line 48
   at NzbDrone.Core.MediaFiles.MediaFileAttributeService.SetFilePermissions(String path) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MediaFileAttributeService.cs:line 39


2023-02-03 16:35:48.7|Debug|DiskTransferService|Move [C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.en.srt] > [\\hyperv\data\movies\National Treasure Book of Secrets (2007)\National Treasure Book of Secrets (2007) - [Bluray-1080p][X264][AC3 5.1][ENG][CtrlHD].2.en.srt]
```

In the end the files are copied with the import so not sure what is happening here

Radarr is running as a user that has Admin Privileges on the file share and OS.
Both the source and destination have these effective permissions
![image](https://user-images.githubusercontent.com/4103090/216648179-4785aa71-04bd-4812-8ad4-5659a8f05324.png)

### Expected Behavior

To not through those file system errors

### Environment

```markdown
- OS: Server 2019
- Radarr: Version 4.4.0.6882
- Docker Install: -
- Using Reverse Proxy: -
- Browser: -
- Database: Sqlite 3.36.0
```

### What branch are you running?

Develop

### Trace Logs?

```
2023-02-03 16:35:18.7|Debug|DownloadedMovieCommandService|External directory scan request for known download ED6567F9E80EF97F2803842D83C1BF474BC2D413. [C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD]
2023-02-03 16:35:18.7|Debug|DownloadedMovieImportService|Processing path: C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD
2023-02-03 16:35:18.7|Debug|Parser|Parsing string 'National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD'
2023-02-03 16:35:18.7|Debug|Parser|Movie Parsed. National Treasure - 2004 
2023-02-03 16:35:18.7|Debug|Parser|Release Group parsed: CtrlHD
2023-02-03 16:35:18.7|Debug|Parser|Languages parsed: Unknown
2023-02-03 16:35:18.7|Debug|QualityParser|Trying to parse quality for National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD
2023-02-03 16:35:18.7|Debug|Parser|Quality parsed: Bluray-1080p v1
2023-02-03 16:35:18.7|Debug|Parser|Edition parsed: 
2023-02-03 16:35:18.7|Debug|DownloadedMovieImportService|National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD folder quality: Bluray-1080p v1
2023-02-03 16:35:18.7|Debug|DiskScanService|Scanning 'C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD' for video files
2023-02-03 16:35:18.7|Debug|DiskScanService|1 video files were found in C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD
2023-02-03 16:35:18.7|Debug|ImportDecisionMaker|Analyzing 1/1 files.
2023-02-03 16:35:18.7|Debug|Parser|Parsing string 'National.Treasure.Book.Of.Secrets.2007.1080p.BluRay.DD5.1.x264-CtrlHD'
2023-02-03 16:35:18.7|Debug|Parser|Movie Parsed. National Treasure Book Of Secrets - 2007 
2023-02-03 16:35:18.7|Debug|Parser|Release Group parsed: CtrlHD
2023-02-03 16:35:18.7|Debug|Parser|Languages parsed: Unknown
2023-02-03 16:35:18.7|Debug|QualityParser|Trying to parse quality for National.Treasure.Book.Of.Secrets.2007.1080p.BluRay.DD5.1.x264-CtrlHD
2023-02-03 16:35:18.7|Debug|Parser|Quality parsed: Bluray-1080p v1
2023-02-03 16:35:18.7|Debug|Parser|Edition parsed: 
2023-02-03 16:35:18.7|Debug|VideoFileInfoReader|Getting media info from C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.mkv
2023-02-03 16:35:18.7|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-02-03 16:35:18.7|Debug|Api|[GET] /api/v3/command/909908: 200.OK (1 ms)
2023-02-03 16:35:18.9|Debug|DetectSample|Runtime of 7886,816 is more than 600 seconds, Not Sample
2023-02-03 16:35:18.9|Debug|Parser|Parsing string 'National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.mkv'
2023-02-03 16:35:18.9|Debug|Parser|Movie Parsed. National Treasure - 2004 
2023-02-03 16:35:18.9|Debug|Parser|Release Group parsed: CtrlHD
2023-02-03 16:35:18.9|Debug|Parser|Languages parsed: Unknown
2023-02-03 16:35:18.9|Debug|QualityParser|Trying to parse quality for National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.mkv
2023-02-03 16:35:18.9|Debug|Parser|Quality parsed: Bluray-1080p v1
2023-02-03 16:35:18.9|Debug|Parser|Edition parsed: 
2023-02-03 16:35:18.9|Debug|VideoFileInfoReader|Getting media info from C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.mkv
2023-02-03 16:35:19.0|Debug|AggregateLanguage|Selected languages: English
2023-02-03 16:35:19.0|Debug|AggregateQuality|Using quality: Bluray-1080p v1
2023-02-03 16:35:19.0|Debug|AlreadyImportedSpecification|Skipping already imported check for movie without file
2023-02-03 16:35:19.0|Debug|GrabbedReleaseQualitySpecification|No grabbed history for this download client item
2023-02-03 16:35:19.0|Debug|VideoFileInfoReader|Getting media info from C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.mkv
2023-02-03 16:35:19.1|Debug|DetectSample|Runtime of 7886,816 is more than 600 seconds, Not Sample
2023-02-03 16:35:19.1|Debug|ImportDecisionMaker|File accepted
2023-02-03 16:35:19.1|Debug|ImportApprovedMovie|Decisions: 1
2023-02-03 16:35:19.1|Debug|MovieFileMovingService|Moving movie file: C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.mkv to \\hyperv\data\movies\National Treasure Book of Secrets (2007)\National Treasure Book of Secrets (2007) - [Bluray-1080p][X264][AC3 5.1][ENG][CtrlHD].mkv
2023-02-03 16:35:19.1|Debug|DiskTransferService|Move [C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.mkv] > [\\hyperv\data\movies\National Treasure Book of Secrets (2007)\National Treasure Book of Secrets (2007) - [Bluray-1080p][X264][AC3 5.1][ENG][CtrlHD].mkv]
2023-02-03 16:35:19.7|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-02-03 16:35:48.2|Debug|MediaFileAttributeService|Setting last write time on movie folder: \\hyperv\data\movies\National Treasure Book of Secrets (2007)
2023-02-03 16:35:48.6|Info|MovieService|Assigning file [National Treasure Book of Secrets (2007) - [Bluray-1080p][X264][AC3 5.1][ENG][CtrlHD].mkv] to movie [[National Treasure: Book of Secrets (2007)][tt0465234, 6637]]
2023-02-03 16:35:48.6|Debug|LanguageParser|Parsing language from subtitle file: C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.5.en.srt
2023-02-03 16:35:48.6|Debug|LanguageParser|Parsing language from subtitle file: C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.en.srt
2023-02-03 16:35:48.6|Debug|LanguageParser|Parsing language from subtitle file: C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.nl.srt
2023-02-03 16:35:48.6|Debug|DiskTransferService|Move [C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.5.en.srt] > [\\hyperv\data\movies\National Treasure Book of Secrets (2007)\National Treasure Book of Secrets (2007) - [Bluray-1080p][X264][AC3 5.1][ENG][CtrlHD].1.en.srt]
2023-02-03 16:35:48.7|Debug|MediaFileAttributeService|Unable to apply folder permissions to: 
2023-02-03 16:35:48.7|Debug|MediaFileAttributeService|C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.5.en.srt

[v4.4.0.6882] System.IO.FileNotFoundException: C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.5.en.srt
   at System.Security.AccessControl.NativeObjectSecurity.CreateInternal(ResourceType resourceType, Boolean isContainer, String name, SafeHandle handle, AccessControlSections includeSections, Boolean createByName, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   at System.Security.AccessControl.NativeObjectSecurity..ctor(Boolean isContainer, ResourceType resourceType, String name, AccessControlSections includeSections, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   at System.Security.AccessControl.FileSystemSecurity..ctor(Boolean isContainer, String name, AccessControlSections includeSections, Boolean isDirectory)
   at System.IO.FileSystemAclExtensions.GetAccessControl(FileInfo fileInfo, AccessControlSections includeSections)
   at NzbDrone.Windows.Disk.DiskProvider.InheritFolderPermissions(String filename) in D:\a\1\s\src\NzbDrone.Windows\Disk\DiskProvider.cs:line 48
   at NzbDrone.Core.MediaFiles.MediaFileAttributeService.SetFilePermissions(String path) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MediaFileAttributeService.cs:line 39


2023-02-03 16:35:48.7|Debug|DiskTransferService|Move [C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.en.srt] > [\\hyperv\data\movies\National Treasure Book of Secrets (2007)\National Treasure Book of Secrets (2007) - [Bluray-1080p][X264][AC3 5.1][ENG][CtrlHD].2.en.srt]
2023-02-03 16:35:48.7|Debug|MediaFileAttributeService|Unable to apply folder permissions to: 
2023-02-03 16:35:48.7|Debug|MediaFileAttributeService|C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.en.srt

[v4.4.0.6882] System.IO.FileNotFoundException: C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.en.srt
   at System.Security.AccessControl.NativeObjectSecurity.CreateInternal(ResourceType resourceType, Boolean isContainer, String name, SafeHandle handle, AccessControlSections includeSections, Boolean createByName, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   at System.Security.AccessControl.NativeObjectSecurity..ctor(Boolean isContainer, ResourceType resourceType, String name, AccessControlSections includeSections, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   at System.Security.AccessControl.FileSystemSecurity..ctor(Boolean isContainer, String name, AccessControlSections includeSections, Boolean isDirectory)
   at System.IO.FileSystemAclExtensions.GetAccessControl(FileInfo fileInfo, AccessControlSections includeSections)
   at NzbDrone.Windows.Disk.DiskProvider.InheritFolderPermissions(String filename) in D:\a\1\s\src\NzbDrone.Windows\Disk\DiskProvider.cs:line 48
   at NzbDrone.Core.MediaFiles.MediaFileAttributeService.SetFilePermissions(String path) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MediaFileAttributeService.cs:line 39


2023-02-03 16:35:48.7|Debug|DiskTransferService|Move [C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.nl.srt] > [\\hyperv\data\movies\National Treasure Book of Secrets (2007)\National Treasure Book of Secrets (2007) - [Bluray-1080p][X264][AC3 5.1][ENG][CtrlHD].nl.srt]
2023-02-03 16:35:48.8|Debug|MediaFileAttributeService|Unable to apply folder permissions to: 
2023-02-03 16:35:48.8|Debug|MediaFileAttributeService|C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.nl.srt

[v4.4.0.6882] System.IO.FileNotFoundException: C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD.nl.srt
   at System.Security.AccessControl.NativeObjectSecurity.CreateInternal(ResourceType resourceType, Boolean isContainer, String name, SafeHandle handle, AccessControlSections includeSections, Boolean createByName, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   at System.Security.AccessControl.NativeObjectSecurity..ctor(Boolean isContainer, ResourceType resourceType, String name, AccessControlSections includeSections, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   at System.Security.AccessControl.FileSystemSecurity..ctor(Boolean isContainer, String name, AccessControlSections includeSections, Boolean isDirectory)
   at System.IO.FileSystemAclExtensions.GetAccessControl(FileInfo fileInfo, AccessControlSections includeSections)
   at NzbDrone.Windows.Disk.DiskProvider.InheritFolderPermissions(String filename) in D:\a\1\s\src\NzbDrone.Windows\Disk\DiskProvider.cs:line 48
   at NzbDrone.Core.MediaFiles.MediaFileAttributeService.SetFilePermissions(String path) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MediaFileAttributeService.cs:line 39


2023-02-03 16:35:48.8|Debug|NotificationService|No tags set for this notification.
2023-02-03 16:35:49.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-02-03 16:35:49.0|Debug|Api|[GET] /api/v3/command/909908: 200.OK (1 ms)
2023-02-03 16:35:49.3|Debug|XbmcService|Movie [National Treasure: Book of Secrets (2007)][tt0465234, 6637] doesn't exist on XBMC host: htpc1.home.lan:80, Updating Entire Library
2023-02-03 16:35:49.3|Debug|NotificationService|No tags set for this notification.
2023-02-03 16:35:49.3|Debug|PlexServer|Scheduling library update for movie 2892 National Treasure: Book of Secrets
2023-02-03 16:35:49.3|Debug|NotificationService|No tags set for this notification.
2023-02-03 16:35:50.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-02-03 16:35:50.0|Debug|Api|[GET] /api/v3/command/909908: 200.OK (1 ms)
2023-02-03 16:35:50.1|Debug|NotificationService|No tags set for this notification.
2023-02-03 16:35:50.5|Debug|DiskScanService|Scanning 'C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD' for video files
2023-02-03 16:35:50.5|Debug|DiskScanService|0 video files were found in C:\TEMP\Torrent\PROCD\Movie\National.Treasure.2004.1080p.BluRay.DD5.1.x264-CtrlHD
2023-02-03 16:35:50.5|Debug|DownloadedMovieImportService|Deleting folder after importing valid files
2023-02-03 16:35:50.6|Debug|CompletedDownloadService|All movies were imported for National.Treasure.Book.Of.Secrets.2007.1080p.BluRay.DD5.1.x264-CtrlHD
```
[AB#4837](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4837)

**Comment by bakerboy448** [comment]
this appears to be an issue with your network drive reporting the file as not existing ` System.IO.FileNotFoundException`

**Comment by Rouzax** [comment]
Blast from the past 😁
To be honest I've also not seen these messages anymore in a while.
