### ISSUE TITLE
Cannot remove path from poster view

### ISSUE THREAD

**Issue by pbarone** [Radarr/Radarr#8093]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I enabled path in the table view. When switching back to poster view I still see the path. Switch back to table view and remove path, it disappears from the table view but when I switch to poster view again the path is still there. Path is indeed not selected in the View Options

### Expected Behavior

I would expect path not to be visible in poster view if it is disabled in the View settings

### Environment

```markdown
- OS: Ubuntu 22.04.1 LTS
- Radarr: 4.3.2.6857-ls160 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox
- Database: Sqlite 3.40.1
```

### What branch are you running?

Master

### Trace Logs?

There is nothing in the logs about this as far as I can tell

2023-02-12 09:17:03.3|Info|RssSyncService|Starting RSS Sync
2023-02-12 09:17:08.7|Info|DownloadDecisionMaker|Processing 142 releases
2023-02-12 09:17:09.5|Info|RssSyncService|RSS Sync Completed. Reports found: 142, Reports grabbed: 0
2023-02-12 10:17:34.2|Info|RssSyncService|Starting RSS Sync
2023-02-12 10:17:39.9|Info|DownloadDecisionMaker|Processing 142 releases
2023-02-12 10:17:40.5|Info|RssSyncService|RSS Sync Completed. Reports found: 142, Reports grabbed: 0
2023-02-12 10:48:34.7|Info|BackupService|Starting Backup
2023-02-12 11:18:05.0|Info|RssSyncService|Starting RSS Sync
2023-02-12 11:18:10.5|Info|DownloadDecisionMaker|Processing 142 releases
2023-02-12 11:18:11.2|Info|RssSyncService|RSS Sync Completed. Reports found: 142, Reports grabbed: 0
2023-02-12 11:39:35.5|Info|RecycleBinProvider|Recycle Bin has not been configured, cannot cleanup.
2023-02-12 11:40:05.5|Info|HousekeepingService|Running housecleaning tasks
2023-02-12 11:40:05.6|Info|Database|Vacuuming Log database
2023-02-12 11:40:05.7|Info|Database|Log database compressed
2023-02-12 11:40:05.7|Info|Database|Vacuuming Main database
2023-02-12 11:40:06.2|Info|Database|Main database compressed
2023-02-12 12:05:05.9|Info|FetchAndParseImportListService|Syncing Movies for List: IMDb Lists
2023-02-12 12:05:05.9|Info|FetchAndParseImportListService|Syncing Movies for List: IMDb Lists
2023-02-12 12:05:08.4|Warn|SkyHookProxy|Couldn't map movie  to a movie on The Movie DB. It will not be added :(

[v4.3.2.6857] NzbDrone.Core.Exceptions.MovieNotFoundException: Movie with IMDBId tt4121026 was not found, it may have been removed from TMDb.
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieByImdbId(String imdbId) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 182
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie(MovieMetadata movie) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 372

2023-02-12 12:05:08.8|Warn|SkyHookProxy|Couldn't map movie  to a movie on The Movie DB. It will not be added :(

[v4.3.2.6857] NzbDrone.Core.Exceptions.MovieNotFoundException: Movie with IMDBId tt5996672 was not found, it may have been removed from TMDb.
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieByImdbId(String imdbId) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 182
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie(MovieMetadata movie) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 372

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

Only way I can reproduce this would be if you're sorting by path. The table option is correctly not carrying over.

**Comment by pbarone** [comment]
Thank you, I was actually sorting by path and changing sort fixed it
