### ISSUE TITLE
Custom Formats & Blocklist - Object reference not set to an instance of an object - /blocklist/movie fails

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#8136]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

blocklist/movie fails due to custom format calculations and the blocklist

```none
2023-02-19 12:46:03.8|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/blocklist/movie

[v4.4.3.6966] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.CustomFormats.CustomFormatCalculationService.ParseCustomFormat(Blocklist blocklist, Movie movie) in D:\a\1\s\src\NzbDrone.Core\CustomFormats\CustomFormatCalculationService.cs:line 61
```

Regression from https://github.com/Radarr/Radarr/commit/cbcf3d1058f47a87c43658084eafac13e7e0889

### Expected Behavior

should not fail 

### Steps To Reproduce

1. Mark as Failed a release from Movie's History
2. Search is triggered
3. Object reference not set to an instance of an object is thrown

### Environment

```markdown
- OS: Ubuntu 20.04
- Radarr: v4.4.3.6966
- Docker Install: No
- Using Reverse Proxy: N/A
- Browser: N/A
- Database: Sqlite 3.31.1 - DB 217
```

### What branch are you running?

Nightly

### Trace Logs?

```
2023-02-19 12:46:03.8|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/blocklist/movie

[v4.4.3.6966] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.CustomFormats.CustomFormatCalculationService.ParseCustomFormat(Blocklist blocklist, Movie movie) in D:\a\1\s\src\NzbDrone.Core\CustomFormats\CustomFormatCalculationService.cs:line 61
   at Radarr.Api.V3.Blocklist.BlocklistResourceMapper.MapToResource(Blocklist model, ICustomFormatCalculationService formatCalculator) in D:\a\1\s\src\Radarr.Api.V3\Blocklist\BlocklistResource.cs:line 37
   at Radarr.Api.V3.Blocklist.BlocklistController.<GetMovieBlocklist>b__4_0(Blocklist h) in D:\a\1\s\src\Radarr.Api.V3\Blocklist\BlocklistController.cs:line 39
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Radarr.Api.V3.Blocklist.BlocklistController.GetMovieBlocklist(Int32 movieId) in D:\a\1\s\src\Radarr.Api.V3\Blocklist\BlocklistController.cs:line 39
   at lambda_method1247(Closure , Object , Object[] )
```

https://gist.github.com/bakerboy448/7d775a9fc0927298d47d4ae46d5f0180

**Comment by bakerboy448** [comment]
RCA - Appears `movie` is null

![image](https://user-images.githubusercontent.com/55419169/230163714-b286c4d1-75b4-4f3e-8efa-05549b749d61.png)
https://github.com/Radarr/Radarr/blob/b48eda95dd61389458462a7bdd03030df8057c90/src/NzbDrone.Core/CustomFormats/CustomFormatCalculationService.cs#L62-L71
