### ISSUE TITLE
Radarr fails to get list of torrents from Transmission - Could not convert to integer

### ISSUE THREAD

**Issue by Millio345** [Radarr/Radarr#8166]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Since a few days ago, the integration with "Transmission" download client has completely stopped working with the error:
"Failed to get the list of torrents: Could not convert to integer: 21212200149. Path '[39].eta'."

Both the "21212200149" value and the "39" value regularly change.

I have 270 torrents in Transmission, 268 are seeding, 2 are 'downloading' (actually idle, waiting for a seeder to come online). I have tried pausing the 2 downloading ones but that does not seem to change anything.

I do remember occasionally seeing this error in the past but it always went away after a minute but now it's always there. The issue persists after restarting radarr and transmission.

### Expected Behavior

Radarr connects to Transmission and monitors torrents

### Steps To Reproduce

1. Add and configure Transmission download client
2. Click "Test" on the download client
Result: Error "Failed to get the list of torrents: Could not convert to integer: 21212200149. Path '[39].eta'."

### Environment

```markdown
- OS: Arch Linux
- Radarr: 4.3.2.6857
- Docker Install: Yes, Linuxserver image (4.3.2.6857-ls163 by linuxserver.io)
- Using Reverse Proxy: Yes, Traefik
- Browser: Firefox
- Database: Sqlite 3.40.1
- Transmission: 4.0.1 (Through docker container linuxserver/transmission)
```

### What branch are you running?

Master

### Trace Logs?

```
``2023-03-01 09:17:31.3|Error|Transmission|Failed to get torrents

[v4.3.2.6857] Newtonsoft.Json.JsonReaderException: Could not convert to integer: 25255342375. Path '[39].eta'.
 ---> System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ThrowInt32OverflowException()
   at System.Convert.ToInt32(Int64 value)
   at Newtonsoft.Json.JsonReader.ReadAsInt32()
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.JsonReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.GetTorrents(TransmissionSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Transmission\TransmissionProxy.cs:line 45
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionBase.TestGetTorrents() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Transmission\TransmissionBase.cs:line 295

```

**Comment by Millio345** [comment]
I've actually done a little more research on this and this seems to be related to seeding torrents. When seeding, the "eta" value returned by transmission is the time left until seed ratio is reached. I've set the seed ratio to 5 so for slow uploads on large files this actually returns values that are more than hunderd thousand days.

**Comment by bakerboy448** [comment]
Please provide the trace logs the bug report template asks for and requires not just the error.

xref https://github.com/Sonarr/Sonarr/issues/5444
