### ISSUE TITLE
Built-in updater fails on macOS arm64 (Apple Silicon / M1 / M2)

### ISSUE THREAD

**Issue by aniqueta** [Radarr/Radarr#8181]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Using the built in updater progresses through download, unpacking, backup, etc. It does not progress further. This issue seems to be unique to macOS ARM machines. The logs are normal but show nothing after:

```
Info|InstallUpdateService|Starting update client /var/folders/.../radarr_update/Radarr.Update
```

It appears that Radarr.Update is not code signed, as running Radarr.Update manually has it automatically killed. Executing the following command resolves that:

```
codesign --force --deep -s - Radarr.Update 
```

However, running Radarr.Update manually dose not seem to complete the update. And, starting the built-in update again from Radarr, means a new executable is downloaded and extracted, and the issue repeats. 

### Expected Behavior

The built-in updater works automatically on macOS arm64, as it does on macOS x64.

### Environment

```markdown
- OS: macOS 13
- Radarr: 4.4.2.6956
- Docker Install: n/a
- Using Reverse Proxy: nginx
- Browser: n/a
- Database: n/a
```

### What branch are you running?

Develop

### Trace Logs?

Please see above.

**Comment by Camwise1** [comment]
I'm having the same issue on my mac mini m1. Running Radarr.  Since trying to run the upgrade I am also now unable to search for additional/new movies.  Getting the below errors now: 

`System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 282
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 288
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 483

**Comment by aniqueta** [comment]
I don't have that issue, but to upgrade, I manually downloaded and reinstalled.

**Comment by Qstick** [comment]
Essentially same root cause as #4535, we need to sign them.
