### ISSUE TITLE
Radarr does not display unmatched queue items when using a language Custom Format

### ISSUE THREAD

**Issue by yammes08** [Radarr/Radarr#8193]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When a release is downloaded, if the release name does not match the movie name and a language custom format is in use then the unknown movie item is not displayed in the Radarr queue. `Show Unknown Movie Items` is selected. 

Here's the json for the lamguage custom format I'm using:

```json
{
  "name": "Not Original Language",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "Not Original",
      "implementation": "LanguageSpecification",
      "negate": true,
      "required": false,
      "fields": {
        "value": -2
      }
    }
  ]
}
```

### Expected Behavior

The unknown movie would be displayed in the queue.

### Steps To Reproduce

1. Setup a language custom format (eg, the example above)
2. Ensure `Show Unknown Movie Items` is checked in the queue options
3. Download a release of a movie where the movie name does not match any known name for that movie
4. Wait for the download to finish
5. Observe that the unknown movie does not show in the queue
6. Delete the language custom format
7. Refresh the queue
8. Observe that the unknown movie now appears

### Environment

```markdown
- OS: Unraid
- Radarr: 4.4.2.6956
- Docker Install: Yes, hotio
- Using Reverse Proxy: No
- Browser: Firefox
- Database: Sqlite 3.38.5
```

### What branch are you running?

Develop

### Trace Logs?

```
[v4.4.2.6956] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.CustomFormats.LanguageSpecification.IsSatisfiedByWithoutNegate(CustomFormatInput input) in D:\a\1\s\src\NzbDrone.Core\CustomFormats\Specifications\LanguageSpecification.cs:line 37
   at NzbDrone.Core.CustomFormats.CustomFormatSpecificationBase.IsSatisfiedBy(CustomFormatInput input) in D:\a\1\s\src\NzbDrone.Core\CustomFormats\Specifications\CustomFormatSpecificationBase.cs:line 32
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at NzbDrone.Core.CustomFormats.CustomFormatCalculationService.<>c__DisplayClass9_0.<ParseCustomFormat>b__1(IGrouping`2 g) in D:\a\1\s\src\NzbDrone.Core\CustomFormats\CustomFormatCalculationService.cs:line 151
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at NzbDrone.Core.CustomFormats.CustomFormatCalculationService.ParseCustomFormat(CustomFormatInput input, List`1 allCustomFormats)
   at NzbDrone.Core.Download.TrackedDownloads.TrackedDownloadService.TrackDownload(DownloadClientDefinition downloadClient, DownloadClientItem downloadItem) in D:\a\1\s\src\NzbDrone.Core\Download\TrackedDownloads\TrackedDownloadService.cs:line 179
```

**Comment by bakerboy448** [comment]
more logs for context
https://gist.github.com/bakerboy448/f4288bfd0225507bee1e34d9bc8a2bf8

appears to be a regression from cbcf3d1058f47a87c43658084eafac13e7e0889f

**Comment by Qstick** [comment]
7d9183ef12
