### ISSUE TITLE
unable to search any films

### ISSUE THREAD

**Issue by Toinoutoine** [Radarr/Radarr#8245]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Hy,

Sinces few days, when i try to search new film with search field (on top left), i have always cthe same message : 
`Failed to load search results, please try again.
Search for 'dune' failed. Invalid response received from TMDb.`
Moreover 3 events appears : 
![image](https://user-images.githubusercontent.com/128632514/226998468-55151dea-2593-460e-ae4f-b628e8f243bd.png)

### Expected Behavior

When i use the search field on top left, radarr show me corresponding films.

### Steps To Reproduce

Use search field on top left.

### Environment

```markdown
- OS: linux (DSM 7.1.1-42962 Update 4)
- Radarr: 4.3.2.6857
- Docker Install: no
- Using Reverse Proxy: yes 
- Browser: all
```

### What branch are you running?

Master

### Trace Logs?

2023-03-22 19:20:59.6|Trace|Http|Req: 774 [GET] /api/v3/command (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)
2023-03-22 19:20:59.6|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-03-22 19:20:59.6|Trace|CommandQueueManager|Getting all commands
2023-03-22 19:20:59.6|Trace|Http|Res: 774 [GET] /api/v3/command: 200.OK (3 ms)
2023-03-22 19:20:59.6|Trace|Http|Req: 775 [GET] /api/v3/command (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)
2023-03-22 19:20:59.6|Debug|Api|[GET] /api/v3/command: 200.OK (3 ms)
2023-03-22 19:20:59.6|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-03-22 19:20:59.6|Trace|Http|Req: 776 [GET] /api/v3/log/file (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)
2023-03-22 19:20:59.6|Trace|CommandQueueManager|Getting all commands
2023-03-22 19:20:59.7|Trace|Http|Res: 775 [GET] /api/v3/command: 200.OK (5 ms)
2023-03-22 19:20:59.7|Debug|Api|[GET] /api/v3/command: 200.OK (5 ms)
2023-03-22 19:20:59.7|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-03-22 19:20:59.7|Trace|Http|Res: 776 [GET] /api/v3/log/file: 200.OK (7 ms)
2023-03-22 19:20:59.7|Debug|Api|[GET] /api/v3/log/file: 200.OK (7 ms)
2023-03-22 19:20:59.7|Trace|Http|Req: 777 [GET] /api/v3/command (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36)
2023-03-22 19:20:59.7|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-03-22 19:20:59.7|Trace|CommandQueueManager|Getting all commands
2023-03-22 19:20:59.7|Trace|Http|Res: 777 [GET] /api/v3/command: 200.OK (3 ms)
2023-03-22 19:20:59.7|Debug|Api|[GET] /api/v3/command: 200.OK (3 ms)
2023-03-22 19:21:00.6|Trace|Http|Req: 778 [POST] /signalr/messages?access_token=(removed)&id=nNb0b_CM2KsCLG4MYFQ3_A (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36)
2023-03-22 19:21:00.6|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: SignalR was successfully authenticated.
2023-03-22 19:21:00.6|Trace|Http|Res: 778 [POST] /signalr/messages?access_token=(removed)&id=nNb0b_CM2KsCLG4MYFQ3_A: 200.OK (2 ms)
2023-03-22 19:21:02.4|Trace|Http|Req: 780 [GET] /MediaCover/741/poster-250.jpg?lastWrite=638132038534324398 (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)
2023-03-22 19:21:02.4|Trace|Http|Req: 779 [GET] /MediaCover/560/poster-250.jpg?lastWrite=638092267955022455 (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)
2023-03-22 19:21:02.4|Trace|Http|Res: 779 [GET] /MediaCover/560/poster-250.jpg?lastWrite=638092267955022455: 200.OK (3 ms)
2023-03-22 19:21:02.4|Trace|Http|Res: 780 [GET] /MediaCover/741/poster-250.jpg?lastWrite=638132038534324398: 200.OK (15 ms)
2023-03-22 19:21:02.5|Trace|Http|Req: 781 [POST] /signalr/messages?access_token=(removed)&id=yq8veOX5OeZZ7KyX8CVX2Q (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)
2023-03-22 19:21:02.5|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: SignalR was successfully authenticated.
2023-03-22 19:21:02.5|Trace|Http|Res: 781 [POST] /signalr/messages?access_token=(removed)&id=yq8veOX5OeZZ7KyX8CVX2Q: 200.OK (1 ms)
2023-03-22 19:21:03.1|Trace|Http|Req: 782 [GET] /MediaCover/1082/poster-250.jpg?lastWrite=637884028794840091 (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)
2023-03-22 19:21:03.1|Trace|Http|Req: 783 [GET] /MediaCover/1104/poster-250.jpg?lastWrite=638092267916793097 (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)
2023-03-22 19:21:03.1|Trace|Http|Res: 782 [GET] /MediaCover/1082/poster-250.jpg?lastWrite=637884028794840091: 200.OK (8 ms)
2023-03-22 19:21:03.1|Trace|Http|Res: 783 [GET] /MediaCover/1104/poster-250.jpg?lastWrite=638092267916793097: 200.OK (11 ms)
2023-03-22 19:21:04.5|Trace|Http|Req: 784 [GET] /api/v3/rootFolder (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)
2023-03-22 19:21:04.5|Trace|Http|Req: 785 [GET] /api/v3/exclusions (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)
2023-03-22 19:21:04.5|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-03-22 19:21:04.5|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-03-22 19:21:04.5|Trace|Http|Res: 785 [GET] /api/v3/exclusions: 200.OK (5 ms)
2023-03-22 19:21:04.5|Trace|Http|Req: 786 [GET] /api/v3/queue/details (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)
2023-03-22 19:21:04.5|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-03-22 19:21:04.5|Trace|Http|Res: 786 [GET] /api/v3/queue/details: 200.OK (3 ms)
2023-03-22 19:21:04.5|Debug|Api|[GET] /api/v3/queue/details: 200.OK (3 ms)
2023-03-22 19:21:04.5|Debug|Api|[GET] /api/v3/exclusions: 200.OK (5 ms)
2023-03-22 19:21:04.5|Debug|RootFolderService|Generating list of unmapped folders
2023-03-22 19:21:04.5|Trace|ConfigService|Using default config value for 'recyclebin' defaultValue:''
2023-03-22 19:21:04.5|Debug|RootFolderService|755 unmapped folders detected.
2023-03-22 19:21:04.5|Debug|RootFolderService|Generating list of unmapped folders
2023-03-22 19:21:04.5|Trace|ConfigService|Using default config value for 'recyclebin' defaultValue:''
2023-03-22 19:21:04.5|Debug|RootFolderService|31 unmapped folders detected.
2023-03-22 19:21:04.5|Debug|RootFolderService|Generating list of unmapped folders
2023-03-22 19:21:04.5|Trace|ConfigService|Using default config value for 'recyclebin' defaultValue:''
2023-03-22 19:21:04.5|Debug|RootFolderService|155 unmapped folders detected.
2023-03-22 19:21:04.6|Debug|RootFolderService|Generating list of unmapped folders
2023-03-22 19:21:04.6|Trace|ConfigService|Using default config value for 'recyclebin' defaultValue:''
2023-03-22 19:21:04.6|Debug|RootFolderService|11 unmapped folders detected.
2023-03-22 19:21:04.6|Trace|Http|Res: 784 [GET] /api/v3/rootFolder: 200.OK (86 ms)
2023-03-22 19:21:04.6|Debug|Api|[GET] /api/v3/rootFolder: 200.OK (86 ms)
2023-03-22 19:21:04.8|Trace|Http|Req: 787 [GET] /api/v3/movie/lookup?term=dune (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)
2023-03-22 19:21:04.8|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-03-22 19:21:04.8|Debug|Parser|Parsing string 'dune'
2023-03-22 19:21:04.8|Debug|Parser|Unable to parse dune
2023-03-22 19:21:04.8|Trace|HttpClient|Req: [GET] https://api.radarr.video/v1/search?q=dune&year=
2023-03-22 19:21:04.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-03-22 19:21:04.8|Error|X509CertificateValidationService|Certificate validation for api.radarr.video failed. RemoteCertificateNameMismatch
2023-03-22 19:21:04.8|Warn|SkyHookProxy|System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

[v4.3.2.6857] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 282
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 288
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 483

2023-03-22 19:21:04.9|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.3.2.6857] NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for 'dune' failed. Invalid response received from TMDb.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 282
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 288
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 483
   --- End of inner exception stack trace ---
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 500
   at lambda_method130(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2023-03-22 19:21:04.9|Trace|RadarrErrorPipeline|Handling Exception
2023-03-22 19:21:04.9|Trace|Http|Res: 787 [GET] /api/v3/movie/lookup?term=dune: 503.ServiceUnavailable (167 ms)
2023-03-22 19:21:04.9|Debug|Api|[GET] /api/v3/movie/lookup?term=dune: 503.ServiceUnavailable (167 ms)
2023-03-22 19:21:05.5|Trace|Http|Req: 788 [POST] /signalr/messages?access_token=(removed)&id=xuxkjRtdwb2bqPC9754UOA (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)
2023-03-22 19:21:05.5|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: SignalR was successfully authenticated.
2023-03-22 19:21:05.5|Trace|Http|Res: 788 [POST] /signalr/messages?access_token=(removed)&id=xuxkjRtdwb2bqPC9754UOA: 200.OK (2 ms)
2023-03-22 19:21:06.3|Trace|Scheduler|Pending Tasks: 0
2023-03-22 19:21:08.9|Trace|Http|Req: 789 [GET] /api/v3/health (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)
2023-03-22 19:21:08.9|Trace|Http|Req: 790 [GET] /api/v3/system/status (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)
2023-03-22 19:21:08.9|Trace|Http|Req: 791 [GET] /api/v3/diskspace (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)
2023-03-22 19:21:08.9|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-03-22 19:21:09.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-03-22 19:21:09.0|Trace|Http|Res: 789 [GET] /api/v3/health: 200.OK (8 ms)
2023-03-22 19:21:09.0|Debug|Api|[GET] /api/v3/health: 200.OK (8 ms)
2023-03-22 19:21:09.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-03-22 19:21:09.0|Trace|Http|Res: 791 [GET] /api/v3/diskspace: 200.OK (41 ms)
2023-03-22 19:21:09.0|Debug|Api|[GET] /api/v3/diskspace: 200.OK (41 ms)
2023-03-22 19:21:09.1|Trace|Http|Res: 790 [GET] /api/v3/system/status: 200.OK (182 ms)
2023-03-22 19:21:09.1|Debug|Api|[GET] /api/v3/system/status: 200.OK (182 ms)
2023-03-22 19:21:11.4|Trace|Http|Req: 792 [GET] /api/v3/log/file (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)
2023-03-22 19:21:11.4|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-03-22 19:21:11.4|Trace|Http|Res: 792 [GET] /api/v3/log/file: 200.OK (2 ms)
2023-03-22 19:21:11.4|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)
2023-03-22 19:21:15.6|Trace|Http|Req: 793 [GET] /logfile/radarr.trace.txt (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)
2023-03-22 19:21:15.6|Trace|Http|Req: 794 [POST] /signalr/messages?access_token=(removed)&id=nNb0b_CM2KsCLG4MYFQ3_A (from 127.0.0.1 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36)

**Comment by bakerboy448** [comment]
SSL issues will likely be something due to your system rejecting the certs / having outdated root certs or your networking interfering with the certs or some other local to your environment issue

Not a radarr application issue/bug

**Comment by Toinoutoine** [comment]
Hey @bakerboy448. I think it's more complicated because if i try a 
`curl https://api.radarr.video/v1/search?q=someone` on ssh from my NAS it work correctly.

**Comment by Jackeldk** [comment]
of you have a unifi router , Turn off ad blocking on your Unifi router.

**Comment by apetresc** [comment]
@Jackeldk Thank you, this was exactly the issue, and I likely would have *never* connected those dots.

But it still leaves a lot of unanswered questions. Why is the call to TMDB being rejected by Unifi's adblocker, but only when coming from Radarr? Sonarr can still query TMDB, and I can still query api.radarr.video from curl on the same network, as @Toinoutoine described.

**Comment by bakerboy448** [comment]
Sonarr does not use TMDb at all....it uses TVDb proxied via Skyhook.  Same concept as Radarr.

You'd have to ask UniFi why they have decided to block the Radarr and Servarr domains.

you'd have to contact your Syno support or the SynoCommunity who create, maintain, and support the third party packages and/or UniFi for further help.

it's an ssl error, so curl would not show that - OpenSSL would. https://wiki.servarr.com/permissions-and-networking#ssl-issues

If you do some DNS lookups for the domain with ad blocking enabled, it will presumably not be the Servarr servers.

good luck!

Regardless, not a radarr issue at all. GitHub is not for support / support discussions

**Comment by asic79** [comment]
Apologies for resurrecting this...

Indeed the problem is with Unifi AD Blocker.
You can leave the ad blocker on and configure a route rule:

What to route: Specific Traffic
Category: Domain Name
Domain Name: radarr.video
Target: {your radarr}
Interface: {your broadband IF}

**Comment by richjdsmith** [comment]
> If you have a unifi router , Turn off ad blocking on your Unifi router.

I would kiss you straight on the lips over this response. I have reinstalled Unraid and still couldn't figure it out. I was blaming my ISP. I phoned them. It has been the bane of my existence. Thanks for your help, I greatly appreciate it.

**Comment by g4defender-oz** [comment]
great job asic79

**Comment by gebb79** [comment]
Thanks for the Unifi workaround!! works a treat for my UDM Pro
