### ISSUE TITLE
Some Prowlarr indexers not being available

### ISSUE THREAD

**Issue by fede843** [Radarr/Radarr#8247]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Some indexers added in Prowlarr not being available in Radarr. For instance BitSearch and Solid Torrents.

### Expected Behavior

Since those indexers include movie category, should be available.

### Steps To Reproduce

Have added those 2 in Prowlarr, let them sync and they never came up.

### Environment

```markdown
- OS: Linux raspberrypi 5.15.84-v8+ #1613
- Radarr: Docker, image linuxserver/radarr:latest 1.3.1.2796-ls94 by linuxserver.io
- Docker Docker 23.0.1: 
- Using Reverse Proxy: No
- Browser: Chrome 110.0.5481.100 (Build oficial) (x86_64)
- Database: Sqlite 3.40.1
```

### What branch are you running?

Master

### Trace Logs?

When adding Solidtorrent index in prowlarr I get:

In Radarr:

```
Invalid request Validation failed: 
 -- : Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.

An unhandled exception has occurred while executing the request.: Validation failed: 
 -- : Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.
FluentValidation.ValidationException: Validation failed: 
 -- : Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.
   at Radarr.Api.V3.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 205
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 191
   at Radarr.Api.V3.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 68
   at lambda_method232(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
Close

```

In Prowlarr:

```
NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://192.168.254.70:7878/api/v3/indexer]

HTTP Error - Res: [POST] http://192.168.254.70:7878/api/v3/indexer: 400.BadRequest (274 bytes)
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]

```

Sonarr takes it jut fine.

**Comment by fede843** [comment]
Just to add, movie seems present in prowlarr indexer categories:

```
Indexer Details
Id
11
Description
Solid Torrents is a Public torrent meta-search engine
Encoding
Unicode (UTF-8)
Language
en-US
Indexer Site
https://solidtorrents.to/
Torznab Url
http://192.168.254.70:9696/11/api
Search Capabilities
Raw Search Supported
No
Search Types
q
TV Search Types
q, season, ep
Movie Search Types
q
Book Search Types
q
Music Search Types
q
```

**Comment by fede843** [comment]
I am not sure if this is a Radarr issue or a Prowlarr one. Just decided to start out from here.

**Comment by fede843** [comment]
Hi!
Just did it.
Thanks!
