### ISSUE TITLE
Request Failed: Instance property 'this' is not defined for type 'NzbDrone.Core.Tv.Movie'

### ISSUE THREAD

**Issue by CBers** [Radarr/Radarr#825]
**Description:**

Error in logs.

I believe this is related to loading the WANTED page, as that was what I was viewing when, after taking a long time to load, I checked the logs.

EDIT: I can confirm this. It occurs on load of the WANTED page.

**Radarr Version:**

0.2.0.373

**Logs:**

System.ArgumentException: Instance property 'this' is not defined for type 'NzbDrone.Core.Tv.Movie'
   at System.Linq.Expressions.Expression.Property(Expression expression, String propertyName)
   at NzbDrone.Core.Datastore.Extensions.PagingSpecExtensions.CreateExpression[TModel](String propertyName) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Extensions\PagingSpecExtensions.cs:line 36
   at NzbDrone.Core.Tv.MovieRepository.GetMoviesWithoutFilesQuery(PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieRepository.cs:line 197
   at NzbDrone.Core.Tv.MovieRepository.MoviesWithoutFiles(PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieRepository.cs:line 189
   at NzbDrone.Core.Tv.MovieService.MoviesWithoutFiles(PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:line 277
   at NzbDrone.Api.NzbDroneRestModule`1.ApplyToPage[TModel](Func`2 function, PagingSpec`1 pagingSpec, Converter`2 mapper) in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModule.cs:line 27
   at NzbDrone.Api.Wanted.MovieMissingModule.GetMissingMovies(PagingResource`1 pagingResource) in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieMissingModule.cs:line 42
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourcePaged>b__35_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 126
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
Close

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by CBers** [comment]
The WANTED page will not load due to this error.

**Comment by onedr0p** [comment]
Try Clear your cookies, and try in incognito window.

**Comment by crafty35a** [comment]
FYI, I also had this issue, and clearing cookies did resolve it.
