### ISSUE TITLE
SQL error - no such column: t0.Minimumavailability  (nightly build)

### ISSUE THREAD

**Issue by drafie** [Radarr/Radarr#827]
I upgraded on Windows from nightly build 0.357 to 0.369 and 0.374.   Neither of those builds (369 / 374) would run, instead they spam System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database no such column: t0.Minimumavailability  

I assume this is related to #816 and the database migration hasn't been run on my database.  

They spammed these errors:

[v0.2.0.374] System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
no such column: t0.Minimumavailability
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Marr.Data.DataMapper.Query[T](String sql, ICollection`1 entityList, Boolean useAltName) in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:line 566
   at Marr.Data.QGen.QueryBuilder`1.ToList() in C:\projects\radarr-usby1\src\Marr.Data\QGen\QueryBuilder.cs:line 279
   at Marr.Data.QGen.SortBuilder`1.ToList() in C:\projects\radarr-usby1\src\Marr.Data\QGen\SortBuilder.cs:line 176
   at Marr.Data.QGen.SortBuilder`1.GetEnumerator() in C:\projects\radarr-usby1\src\Marr.Data\QGen\SortBuilder.cs:line 247
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Tv.MovieRepository.FindByTitle(String cleanTitle, Int32 year) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieRepository.cs:line 144
   at NzbDrone.Core.Tv.MovieService.FindByTitle(String title, Int32 year) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:line 179
   at NzbDrone.Core.Parser.ParsingService.GetMovie(ParsedMovieInfo parsedEpisodeInfo, String imdbId, SearchCriteriaBase searchCriteria) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 409
   at NzbDrone.Core.Parser.ParsingService.Map(ParsedMovieInfo parsedEpisodeInfo, String imdbId, SearchCriteriaBase searchCriteria) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\ParsingService.cs:line 230
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.<GetMovieDecisions>d__6.MoveNext() in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 73

**Comment by galli-leo** [comment]
How the hell did you get that in the nightly? That isn't merged yet.

**Comment by drafie** [comment]
I have been downloading, what I assumed was nightly, off the continuous build link at the bottom of the readme.   <hoping not to hang head in shame>

**Comment by galli-leo** [comment]
@drafie Ah gotcha. You can update to the latest nightly by just changing the branch in settings.

**Comment by drafie** [comment]
@galli-leo my fault.  <hangs head in shame> 

But, I don't see a "nightly" branch on Github?

**Comment by galli-leo** [comment]
No problem. I should probably put a warning there or change the url to the develop branch. And yeah the nightly branch is only created by our API.

**Comment by drafie** [comment]
Got it - updated to nightly branch through UI.    Working great.

**Comment by drafie** [comment]
@galli-leo sorry to raise a closed issue.   But, I am still getting this error despite going to nightly builds, see below.   I can fix this if I manually deploy the latest pre-release.   But as soon as it updates to nightly build it begins to pop this error and the GUI is inaccessible. 

Any ideas on why this this hanging around?   

[v0.2.0.405] System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
no such column: t0.MinimumAvailability
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Marr.Data.DataMapper.Query[T](String sql, ICollection`1 entityList, Boolean useAltName) in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:line 566
   at Marr.Data.QGen.QueryBuilder`1.ToList() in C:\projects\radarr-usby1\src\Marr.Data\QGen\QueryBuilder.cs:line 279
   at Marr.Data.QGen.SortBuilder`1.ToList() in C:\projects\radarr-usby1\src\Marr.Data\QGen\SortBuilder.cs:line 176
   at NzbDrone.Core.Datastore.BasicRepository`1.GetPaged(PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 249
   at NzbDrone.Core.Tv.MovieRepository.GetPaged(PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieRepository.cs:line 216
   at NzbDrone.Core.Tv.MovieService.Paged(PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:line 122
   at NzbDrone.Api.NzbDroneRestModule`1.ApplyToPage[TModel](Func`2 function, PagingSpec`1 pagingSpec, Converter`2 mapper) in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModule.cs:line 27
   at NzbDrone.Api.Movie.MovieModule.GetMoviePaged(PagingResource`1 pagingResource) in C:\projects\radarr-usby1\src\NzbDrone.Api\Series\MovieModule.cs:line 143
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourcePaged>b__35_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 126
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by galli-leo** [comment]
Seems like you messed up your db. Can you edit the db file and change the Minimumavailability column to MinimumAvailabilty or if Minimumavailabilty is not there add it yourself. Hit one of the devs up on discord if you need more help.

**Comment by galli-leo** [comment]
You can also just nuke the db

**Comment by drafie** [comment]
@galli-leo thanks!  I edited the DB and added the columns, per the commit from a couple of days ago. 

NetImport
Movies 

Added MinimumAvailability as 32 int, with "4" as default.

Looks like its working.
