### ISSUE TITLE
Looking for some Radarr help ~> Error occurred while executing task RefreshCollections: The SSL connection could not be established...

### ISSUE THREAD

**Issue by wallsofjoeco** [Radarr/Radarr#8427]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have been experiencing an issue with Radarr, which is mounted in Docker on my Synology NAS (using Watchtower to update the containers). This is only happening on Radarr and not Sonarr nor Lidarr containers. Since a week ago it started showing this in the in the event logs:

    Apr 25 2023 CommandExecutor	Error occurred while executing task RefreshMovie: The SSL connection could not be established, see inner exception.	
    Apr 25 2023	X509CertificateValidationService	Certificate validation for api.radarr.video failed. RemoteCertificateNameMismatch

### Expected Behavior

The problem, I can't add movies: Invalid response received from TMDb or able to refresh data.  I am not sure how to resolve this. I don't code, so not much into knowledge on Linux/Ubuntu.  I have SSH here and their based on You Tube vids, that about it.  Here is the log on error.  I did notice an update on April 14th.  Would that might be the issue?  Does anyone have and idea'rs how to fix?

### Environment

```markdown
- OS: Synology OS
- Radarr: 4.4.4.7068
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox 112.0.2 (64-bit)
- Database: ...
```

### What branch are you running?

Master

### Trace Logs?

    System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
     ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
       at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
       at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
       at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
       at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
       --- End of inner exception stack trace ---
       at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
       at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
       at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
       at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
       at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
       at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
       at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 101
       at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
       at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
       at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 282
       at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 288
       at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetChangedMovies(DateTime startTime) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 67
       at NzbDrone.Core.Movies.RefreshMovieService.Execute(RefreshMovieCommand message) in D:\a\1\s\src\NzbDrone.Core\Movies\RefreshMovieService.cs:line 203
       at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 113
       at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
       at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44

**Comment by bakerboy448** [comment]
Based on the incomplete partial logs - crystal ball says you have UniFi running their adblocker or your DNS or ISP is otherwise interfering accessing radarr's metadata servers.

```bash
 nslookup api.radarr.video
```
```none
Server:         127.0.0.53
Address:        127.0.0.53#53
Non-authoritative answer:
Name:   api.radarr.video
Address: 172.64.101.3
Name:   api.radarr.video
Address: 172.64.100.3
Name:   api.radarr.video
Address: 2606:4700:e0::ac40:6503
Name:   api.radarr.video
Address: 2606:4700:e0::ac40:6403
```

**Comment by wallsofjoeco** [comment]
Got a new Unifi Dream Router w/ UniFi running adblocker is the issue.  Thanks bakerboy448!
