### ISSUE TITLE
Unable to search for movies from movie list and "Search" tab of movie crashing

### ISSUE THREAD

**Issue by PartTheSeas** [Radarr/Radarr#8434]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

If you click on the little magnifying glass of a movie, search fails. So does the search tab from a movie view

### Expected Behavior

Search, search, search 

### Steps To Reproduce

Not sure if it's Linux and/or docker specific, but I presume it's related to the latest version

### Environment

```markdown
- OS: 23.04
- Radarr: 4.5.1.7175
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Any
- Database: Sqlite 3.40.1
```

### What branch are you running?

Nightly

### Trace Logs?

https://gist.github.com/PartTheSeas/496089c345d7b854dc6716f2b8fc3e84

**Comment by bakerboy448** [comment]
Confirmed 4.5.1.7175

- Cannot reproduce this from the `Search` tab for an interactive search
- Cannot reproduce this with `Search Movie` on a movie details page
- Confirmed and reproduced when clicking the magnifying glass from the movie index

```none
2023-05-02 16:55:46.1|Trace|Http|Res: 1081 [POST] /radarr4k/api/v3/command: 201.Created (18 ms)
2023-05-02 16:55:46.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
2023-05-02 16:55:46.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2023-05-02 16:55:46.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2023-05-02 16:55:46.1|Trace|CommandQueueManager|Updating command status
2023-05-02 16:55:46.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
2023-05-02 16:55:46.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2023-05-02 16:55:46.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2023-05-02 16:55:46.1|Trace|EventAggregator|Publishing CommandExecutedEvent
2023-05-02 16:55:46.1|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2023-05-02 16:55:46.1|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2023-05-02 16:55:46.1|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2023-05-02 16:55:46.1|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2023-05-02 16:55:46.1|Trace|EventAggregator|CommandExecutedEvent -> QualityDefinitionController
2023-05-02 16:55:46.1|Trace|EventAggregator|CommandExecutedEvent <- QualityDefinitionController
2023-05-02 16:55:46.1|Trace|CommandExecutor|MoviesSearchCommand <- MovieSearchService [00:00:00.0123445]
2023-05-02 16:55:46.1|Error|CommandExecutor|Error occurred while executing task MoviesSearch

[v4.5.1.7175] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.IndexerSearch.MovieSearchService.Execute(MoviesSearchCommand message) in D:\a\1\s\src\NzbDrone.Core\IndexerSearch\MoviesSearchService.cs:line 41
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 113
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44


2023-05-02 16:55:46.2|Trace|Http|Req: 1082 [GET] /radarr4k/api/v3/command (from 73.*.*.12 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36)
```

Payload from magnifying glass:
```json
{"name":"MoviesSearch","movieId":1701}
```
Response
```json
 {
    "name": "MoviesSearch",
    "commandName": "Movies Search",
    "message": "Failed",
    "body": {
      "sendUpdatesToClient": true,
      "updateScheduledTask": true,
      "completionMessage": "Completed",
      "requiresDiskAccess": false,
      "isExclusive": false,
      "isTypeExclusive": false,
      "isLongRunning": false,
      "name": "MoviesSearch",
      "trigger": "manual",
      "suppressMessages": false
    },
    "priority": "normal",
    "status": "failed",
    "queued": "2023-05-02T21:56:07Z",
    "started": "2023-05-02T21:56:07Z",
    "ended": "2023-05-02T21:56:07Z",
    "duration": "00:00:00.0096084",
    "exception": "System.NullReferenceException: Object reference not set to an instance of an object.\n   at NzbDrone.Core.IndexerSearch.MovieSearchService.Execute(MoviesSearchCommand message) in D:\\a\\1\\s\\src\\NzbDrone.Core\\IndexerSearch\\MoviesSearchService.cs:line 41\n   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\\a\\1\\s\\src\\NzbDrone.Core\\Messaging\\Commands\\CommandExecutor.cs:line 113",
    "trigger": "manual",
    "stateChangeTime": "2023-05-02T21:56:07Z",
    "sendUpdatesToClient": true,
    "updateScheduledTask": true,
    "id": 2501765
  }
```
