### ISSUE TITLE
Cannot add movie

### ISSUE THREAD

**Issue by shomilsaini** [Radarr/Radarr#8515]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Trying to add a movie, clicking on add button does nothing.
searching the movie shows it in result list, tmdb page exists. it shows the link to tmdb page as well

this issue started when randomly radarr started saying the movie doesnt exist on tmdb and should be deleted and re-added as per https://wiki.servarr.com/radarr/system#movie-was-removed-from-tmdb

I was able to delete the movie but cannot add it back.

Thanks!

### Expected Behavior

movie should add to list

### Steps To Reproduce

go to search
search for movie name
movie shows up in results
click to add

### Environment

```markdown
- OS: UnRAID
- Radarr: 4.4.4.7068
- Docker Install: bihex-radarr
- Using Reverse Proxy: no
- Browser: chrome
- Database: Sqlite 3.41.2
```

### What branch are you running?

Master

### Trace Logs?

2023-05-14 13:10:08.4|Error|AddMovieService|TmdbId 109907 was not found, it may have been removed from TMDb. Path: 
2023-05-14 13:10:08.4|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.4.4.7068] FluentValidation.ValidationException: Validation failed: 
 -- TmdbId: A movie with this ID was not found. Path: 
   at NzbDrone.Core.Movies.AddMovieService.AddSkyhookData(Movie newMovie) in D:\a\1\s\src\NzbDrone.Core\Movies\AddMovieService.cs:line 112
   at NzbDrone.Core.Movies.AddMovieService.AddMovie(Movie newMovie) in D:\a\1\s\src\NzbDrone.Core\Movies\AddMovieService.cs:line 52
   at Radarr.Api.V3.Movies.MovieController.AddMovie(MovieResource moviesResource) in D:\a\1\s\src\Radarr.Api.V3\Movies\MovieController.cs:line 209
   at lambda_method236(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\StartingUpMiddleware.cs:line 41
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2023-05-14 13:10:08.4|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- TmdbId: A movie with this ID was not found. Path: 

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by shomilsaini** [comment]
I don't think this is tech support if the movie exists and Radarr is not able to add it.
I don't use other platforms so 🤷‍♂️

Cheers!

**Comment by austinwbest** [comment]
> I don't think this is tech support if the movie exists and Radarr is not able to add it.
> I don't use other platforms so 🤷‍♂️
> 
> Cheers!

That's because it is not a movie, it's a TV show. This is not a bug as radarr will not add things that are not listed as a movie on tmdb and GH is used for bug reports. 

https://www.themoviedb.org/tv/109907-first-ladies?language=en-US

If you need further assistance you'll need to use one of the before mentioned platforms.

**Comment by shomilsaini** [comment]
> > I don't think this is tech support if the movie exists and Radarr is not able to add it.
> > I don't use other platforms so 🤷‍♂️
> > Cheers!
> 
> That's because it is not a movie, it's a TV show. This is not a bug as radarr will not add things that are not listed as a movie on tmdb and GH is used for bug reports.
> 
> https://www.themoviedb.org/tv/109907-first-ladies?language=en-US
> 
> If you need further assistance you'll need to use one of the before mentioned platforms.

It is not a TV Show, here is the proof. See the link on bottom left. Clicking on TMDb link on 1st movie takes me takes me directly to the movie [https://www.themoviedb.org/movie/109907-hate-story](https://www.themoviedb.org/movie/109907-hate-story)

Also, Side note - this movie was already in Radarr until I recieved a notification that the movie has been deleted...... so needs to be deleted from Radarr or something. This has happened before and usually I just delete and add again and this fixes it. NOt this time.

![image](https://github.com/Radarr/Radarr/assets/46788173/fdc1fef5-2fc0-4afe-917d-9baa7743442a)


Let me know if you need further information.

Thanks!
