### ISSUE TITLE
Exceptions being thrown for failed parsing.

### ISSUE THREAD

**Issue by austinwbest** [Radarr/Radarr#8593]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

```2023-05-25 15:30:58.3|Trace|Http|Req: 3065 [POST] /api/v3/release/push (from ::1 autobrr)
2023-05-25 15:30:58.3|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-05-25 15:30:58.3|Info|ReleasePushController|Release pushed: Team Rubicon S01E01 1080p WEB H264-SPAMnEGGS - https://www.torrentleech.org/rss/download/241055500/(removed)/Team+Rubicon+S01E01+1080p+WEB+H264-SPAMnEGGS.torrent
2023-05-25 15:30:58.4|Debug|ReleasePushController|Push Release Team Rubicon S01E01 1080p WEB H264-SPAMnEGGS associated with indexer 6 - torrentleech.
2023-05-25 15:30:58.4|Info|DownloadDecisionMaker|Processing 1 releases
2023-05-25 15:30:58.4|Trace|DownloadDecisionMaker|Processing release 1/1
2023-05-25 15:30:58.4|Debug|DownloadDecisionMaker|Processing release 'Team Rubicon S01E01 1080p WEB H264-SPAMnEGGS' from 'torrentleech'
2023-05-25 15:30:58.4|Debug|Parser|Parsing string 'Team Rubicon S01E01 1080p WEB H264-SPAMnEGGS'
2023-05-25 15:30:58.4|Debug|Parser|Unable to parse Team Rubicon S01E01 1080p WEB H264-SPAMnEGGS
2023-05-25 15:30:58.4|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.5.2.7363] FluentValidation.ValidationException: Validation failed: 
 -- Title: Unable to parse
   at Radarr.Api.V3.Indexers.ReleasePushController.Create(ReleaseResource release) in ./Radarr.Api.V3/Indexers/ReleasePushController.cs:line 74
   at lambda_method102(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2023-05-25 15:30:58.4|Trace|RadarrErrorPipeline|Handling Exception
2023-05-25 15:30:58.4|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Title: Unable to parse
2023-05-25 15:30:58.4|Trace|Http|Res: 3065 [POST] /api/v3/release/push: 400.BadRequest (54 ms)
2023-05-25 15:30:58.4|Debug|Api|[POST] /api/v3/release/push: 400.BadRequest (54 ms)
```

### Expected Behavior

Log the failure without the exception stack (upstream does this) as this floods the logs non stop with un-necessary text.

When watching log files for critical errors, this one flags hundreds of times per day sending notifications that are not relevant.

Upstream looks like

```2023-05-25 15:30:58.3|Trace|Http|Req: 3065 [POST] /api/v3/release/push (from ::1 autobrr)
2023-05-25 15:30:58.3|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-05-25 15:30:58.3|Info|ReleasePushController|Release pushed: Team Rubicon S01E01 1080p WEB H264-SPAMnEGGS - https://www.torrentleech.org/rss/download/241055500/(removed)/Team+Rubicon+S01E01+1080p+WEB+H264-SPAMnEGGS.torrent
2023-05-25 15:30:58.4|Debug|ReleasePushController|Push Release Team Rubicon S01E01 1080p WEB H264-SPAMnEGGS associated with indexer 6 - torrentleech.
2023-05-25 15:30:58.4|Info|DownloadDecisionMaker|Processing 1 releases
2023-05-25 15:30:58.4|Trace|DownloadDecisionMaker|Processing release 1/1
2023-05-25 15:30:58.4|Debug|DownloadDecisionMaker|Processing release 'Team Rubicon S01E01 1080p WEB H264-SPAMnEGGS' from 'torrentleech'
2023-05-25 15:30:58.4|Debug|Parser|Parsing string 'Team Rubicon S01E01 1080p WEB H264-SPAMnEGGS'
2023-05-25 15:30:58.4|Debug|Parser|Unable to parse Team Rubicon S01E01 1080p WEB H264-SPAMnEGGS
2023-05-25 15:30:58.4|Trace|RadarrErrorPipeline|Handling Exception
2023-05-25 15:30:58.4|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Title: Unable to parse
2023-05-25 15:30:58.4|Trace|Http|Res: 3065 [POST] /api/v3/release/push: 400.BadRequest (54 ms)
2023-05-25 15:30:58.4|Debug|Api|[POST] /api/v3/release/push: 400.BadRequest (54 ms)
```

### Steps To Reproduce

Push something to the endpoint that wont be able to parse

### Environment

```markdown
- OS: Windows
- Radarr: 4.5.2.7363
- Docker Install: N/A
- Using Reverse Proxy: No
- Browser: Not relevant
- Database: sqlite
```

### What branch are you running?

Nightly

### Trace Logs?

Log exception provided above

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by austinwbest** [comment]
> Sonarr V4 is doing the same for me.

Ah, i'm still on v3. So different behavior then from 3 to 4
