### ISSUE TITLE
Unable to add new movie - duplicate key value violates unique constraint "PK_MovieMetadata"

### ISSUE THREAD

**Issue by zebernst** [Radarr/Radarr#8652]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

As of a couple of hours ago, I'm no longer able to add new movies to my Radarr library. When I click the add button, it spins briefly and then stops - nothing happens. According to the logs, there's a primary key clash on the `MovieMetadata` table, but I don't know enough about the internal workings of Radarr to know why that clash is happening. It also doesn't look like I can add `Include Error Detail` in the connection string from the user config level.

### Expected Behavior

The movie is added to the library successfully.

### Environment

```markdown
- OS: Kubernetes (Talos Linux)
- Radarr: 4.5.2.7388
- Docker Install: Yes
- Using Reverse Proxy: Yes (Ingress-Nginx Controller)
- Browser: Firefox
- Database: PostgresQL 15.2
```

### What branch are you running?

Develop

### Trace Logs?

```
2023-06-02 20:36:12.2|Trace|Http|Req: 265 [POST] /api/v3/movie (from 192.168.4.42 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/113.0)
2023-06-02 20:36:12.2|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-06-02 20:36:12.2|Trace|HttpClient|Req: [GET] https://api.radarr.video/v1/movie/49530
2023-06-02 20:36:12.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-06-02 20:36:12.3|Trace|HttpClient|Res: [GET] https://api.radarr.video/v1/movie/49530: 200.OK (71919 bytes) (75 ms)
2023-06-02 20:36:12.3|Trace|ConfigService|Using default config value for 'certificationcountry' defaultValue:'US'
2023-06-02 20:36:12.3|Trace|ConfigService|Using default config value for 'recyclebin' defaultValue:''
2023-06-02 20:36:12.3|Info|AddMovieService|Adding Movie [In Time (2011)][tt1637688, 49530] Path: [/media/plex/Movies/Source/In Time (2011)]
2023-06-02 20:36:12.3|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.5.2.7388] Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "PK_MovieMetadata"

DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.<ReadMessage>g__ReadMessageSequential|44_0(NpgsqlConnector connector, Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1033
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1009
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in ./Radarr.Core/Datastore/BasicRepository.cs:line 189
   at NzbDrone.Core.Datastore.BasicRepository`1.InsertMany(IList`1 models) in ./Radarr.Core/Datastore/BasicRepository.cs:line 210
   at NzbDrone.Core.Movies.MovieMetadataRepository.UpsertMany(List`1 data) in ./Radarr.Core/Movies/MovieMetadataRepository.cs:line 117
   at NzbDrone.Core.Movies.MovieMetadataService.Upsert(MovieMetadata movie) in ./Radarr.Core/Movies/MovieMetadataService.cs:line 58
   at NzbDrone.Core.Movies.AddMovieService.AddMovie(Movie newMovie) in ./Radarr.Core/Movies/AddMovieService.cs:line 55
   at Radarr.Api.V3.Movies.MovieController.AddMovie(MovieResource moviesResource) in ./Radarr.Api.V3/Movies/MovieController.cs:line 218
   at lambda_method228(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
  Exception data:
    Severity: ERROR
    SqlState: 23505
    MessageText: duplicate key value violates unique constraint "PK_MovieMetadata"
    Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
    SchemaName: public
    TableName: MovieMetadata
    ConstraintName: PK_MovieMetadata
    File: nbtinsert.c
    Line: 664
    Routine: _bt_check_unique
Severity: ERROR;InvariantSeverity: ERROR;SqlState: 23505;MessageText: duplicate key value violates unique constraint "PK_MovieMetadata";Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.;SchemaName: public;TableName: MovieMetadata;ConstraintName: PK_MovieMetadata;File: nbtinsert.c;Line: 664;Routine: _bt_check_unique

2023-06-02 20:36:12.3|Trace|RadarrErrorPipeline|Handling Exception
2023-06-02 20:36:12.3|Fatal|RadarrErrorPipeline|Request Failed. POST /api/v3/movie
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by zebernst** [comment]
Oh, good catch. Let me see if I can recreate this with v14

**Comment by zebernst** [comment]
Exact same error when run against a Postgres v14 database. For what it's worth, it's been running just fine on PG v15 for the past few weeks, only ran into this error today.

**Comment by zebernst** [comment]
I also re-ran a [Recyclarr](https://recyclarr.dev/wiki/) job a few minutes ago, and got PK violations on the `CustomFormats` table as well. It seems like my database is more or less in read-only state at the moment 🥲  Is it possible that Radarr is not allowing the DB to auto-generate table PKs via a `sequence`, and its own record counter got out of sync with the database?

**Comment by theinterestingstory** [comment]
Did you find out what was happening? I'm running into the same problem.

**Comment by mikepflu** [comment]
@theinterestingstory how did you get the additional detail?  Did you enable something in the logs to get it, or are these postgresql logs?

I'm having the same problem, running v4.5.2.7388 agains Postgresql v14 as of just recently.  I'd like to try to help by gathering more information, but I'm not sure what I would need to do on my side to do that.

**Comment by bakerboy448** [comment]
#8708 was SQLite appears not isolated to PG

**Comment by volschin** [comment]
Probably an issue of the same kind with a broken migration to postgres in version 4.5.2.7388. Deletes done as described and used the the ghcr.io/roxedus/pgloader in docker as written.

For me it seems that something with resetting the sequences is missing in the documentation or in the used queries.

```
2023-06-26T22:03:49.076030Z ERROR Database error 23505: duplicate key value violates unique constraint "PK_ScheduledTasks"
DETAIL: Key ("Id")=(1) already exists.
CONTEXT: COPY ScheduledTasks, line 1
2023-06-26T22:03:49.148031Z ERROR Database error 23505: duplicate key value violates unique constraint "UC_Version"
DETAIL: Key ("Version")=(1) already exists.
CONTEXT: COPY VersionInfo, line 1
KABOOM!
UNDEFINED-COLUMN: Database error 42703: column ""Id"" of relation "CustomFilters" does not exist
CONTEXT: PL/pgSQL function inline_code_block line 6 at FOR over SELECT rows
QUERY:
DO $$
DECLARE
  n integer := 0;
  r record;
BEGIN
  FOR r in
       SELECT 'select '
               || trim(trailing ')'
                  from replace(pg_get_expr(d.adbin, d.adrelid),
                               'nextval', 'setval'))
               || ', (select greatest(max(' || quote_ident(a.attname) || '), (select seqmin from pg_sequence where seqrelid = ('''
               || pg_get_serial_sequence(quote_ident(nspname) || '.' || quote_ident(relname), quote_ident(a.attname)) || ''')::regclass limit 1), 1) from only '
               || quote_ident(nspname) || '.' || quote_ident(relname) || '));' as sql
         FROM pg_class c
              JOIN pg_namespace n on n.oid = c.relnamespace
              JOIN pg_attribute a on a.attrelid = c.oid
              JOIN pg_attrdef d on d.adrelid = a.attrelid
                                 and d.adnum = a.attnum
                                 and a.atthasdef
        WHERE relkind = 'r' and a.attnum > 0
              and pg_get_expr(d.adbin, d.adrelid) ~ '^nextval'
              and c.oid in (select oid from reloids)
  LOOP
    n := n + 1;
    EXECUTE r.sql;
  END LOOP;

  PERFORM pg_notify('seqs', n::text);
END;
$$;
An unhandled error condition has been signalled:
   Database error 42703: column ""Id"" of relation "CustomFilters" does not exist
CONTEXT: PL/pgSQL function inline_code_block line 6 at FOR over SELECT rows
QUERY:
DO $$
DECLARE
  n integer := 0;
  r record;
BEGIN
  FOR r in
       SELECT 'select '
               || trim(trailing ')'
                  from replace(pg_get_expr(d.adbin, d.adrelid),
                               'nextval', 'setval'))
               || ', (select greatest(max(' || quote_ident(a.attname) || '), (select seqmin from pg_sequence where seqrelid = ('''
               || pg_get_serial_sequence(quote_ident(nspname) || '.' || quote_ident(relname), quote_ident(a.attname)) || ''')::regclass limit 1), 1) from only '
               || quote_ident(nspname) || '.' || quote_ident(relname) || '));' as sql
         FROM pg_class c
              JOIN pg_namespace n on n.oid = c.relnamespace
              JOIN pg_attribute a on a.attrelid = c.oid
              JOIN pg_attrdef d on d.adrelid = a.attrelid
                                 and d.adnum = a.attnum
                                 and a.atthasdef
        WHERE relkind = 'r' and a.attnum > 0
              and pg_get_expr(d.adbin, d.adrelid) ~ '^nextval'
              and c.oid in (select oid from reloids)
  LOOP
    n := n + 1;
    EXECUTE r.sql;
  END LOOP;

  PERFORM pg_notify('seqs', n::text);
END;
$$;



2023-06-26T22:03:49.684038Z ERROR Database error 42703: column ""Id"" of relation "CustomFilters" does not exist
CONTEXT: PL/pgSQL function inline_code_block line 6 at FOR over SELECT rows
QUERY:
DO $$
DECLARE
  n integer := 0;
  r record;
BEGIN
  FOR r in
       SELECT 'select '
               || trim(trailing ')'
                  from replace(pg_get_expr(d.adbin, d.adrelid),
                               'nextval', 'setval'))
               || ', (select greatest(max(' || quote_ident(a.attname) || '), (select seqmin from pg_sequence where seqrelid = ('''
               || pg_get_serial_sequence(quote_ident(nspname) || '.' || quote_ident(relname), quote_ident(a.attname)) || ''')::regclass limit 1), 1) from only '
               || quote_ident(nspname) || '.' || quote_ident(relname) || '));' as sql
         FROM pg_class c
              JOIN pg_namespace n on n.oid = c.relnamespace
              JOIN pg_attribute a on a.attrelid = c.oid
              JOIN pg_attrdef d on d.adrelid = a.attrelid
                                 and d.adnum = a.attnum
                                 and a.atthasdef
        WHERE relkind = 'r' and a.attnum > 0
              and pg_get_expr(d.adbin, d.adrelid) ~ '^nextval'
              and c.oid in (select oid from reloids)
  LOOP
    n := n + 1;
    EXECUTE r.sql;
  END LOOP;

  PERFORM pg_notify('seqs', n::text);
END;
$$;

What I am doing here?

Database error 42703: column ""Id"" of relation "CustomFilters" does not exist
CONTEXT: PL/pgSQL function inline_code_block line 6 at FOR over SELECT rows
QUERY:
DO $$
DECLARE
  n integer := 0;
  r record;
BEGIN
  FOR r in
       SELECT 'select '
               || trim(trailing ')'
                  from replace(pg_get_expr(d.adbin, d.adrelid),
                               'nextval', 'setval'))
               || ', (select greatest(max(' || quote_ident(a.attname) || '), (select seqmin from pg_sequence where seqrelid = ('''
               || pg_get_serial_sequence(quote_ident(nspname) || '.' || quote_ident(relname), quote_ident(a.attname)) || ''')::regclass limit 1), 1) from only '
               || quote_ident(nspname) || '.' || quote_ident(relname) || '));' as sql
         FROM pg_class c
              JOIN pg_namespace n on n.oid = c.relnamespace
              JOIN pg_attribute a on a.attrelid = c.oid
              JOIN pg_attrdef d on d.adrelid = a.attrelid
                                 and d.adnum = a.attnum
                                 and a.atthasdef
        WHERE relkind = 'r' and a.attnum > 0
              and pg_get_expr(d.adbin, d.adrelid) ~ '^nextval'
              and c.oid in (select oid from reloids)
  LOOP
    n := n + 1;
    EXECUTE r.sql;
  END LOOP;

  PERFORM pg_notify('seqs', n::text);
END;
$$;

**Comment by LilDrunkenSmurf** [comment]
I'm having this issue as well, post-migration to postgres. I followed the documented migration steps, including the delete commands, and Radarr comes back up healthy, but I'm unable to add any movies.

**Comment by LilDrunkenSmurf** [comment]
Can confirm that @larivierec workaround worked for me. Tested before and after the fix.

**Comment by catduckgnaf** [comment]
Thank you for this! Since we are not the only ones, and it is not really a radarr issue, I submitted a PR to the wiki.

**Comment by JourneyOver** [comment]
Seems that it's not only affecting being unable to add movies but also history as well and probably various other things, as I came across this issue somewhat today with it causing an issue in `PK_History` and `PK_DownloadHistory` where it kept downloading the same torrent over and over again every time it ran a RSS sync due to the fact that it wasn't able to add that it grabbed the file or even fully downloaded it and all that.

I recently migrated to postgres as well myself, and I can at least confirm that @larivierec workaround worked for me as well and fixed the issue I was facing right away.

the errors I was getting was these two:

```
Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "PK_History"

DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.<ReadMessage>g__ReadMessageSequential|44_0(NpgsqlConnector connector, Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1058
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in ./Radarr.Core/Datastore/BasicRepository.cs:line 188
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in ./Radarr.Core/Datastore/BasicRepository.cs:line 151
   at NzbDrone.Core.History.HistoryService.Handle(MovieGrabbedEvent message) in ./Radarr.Core/History/HistoryService.cs:line 173
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)
  Exception data:
    Severity: ERROR
    SqlState: 23505
    MessageText: duplicate key value violates unique constraint "PK_History"
    Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
    SchemaName: public
    TableName: History
    ConstraintName: PK_History
    File: nbtinsert.c
    Line: 664
    Routine: _bt_check_unique
```

and 

```
Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "PK_DownloadHistory"

DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.<ReadMessage>g__ReadMessageSequential|44_0(NpgsqlConnector connector, Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1058
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in ./Radarr.Core/Datastore/BasicRepository.cs:line 188
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in ./Radarr.Core/Datastore/BasicRepository.cs:line 151
   at NzbDrone.Core.Download.History.DownloadHistoryService.Handle(MovieGrabbedEvent message) in ./Radarr.Core/Download/History/DownloadHistoryService.cs:line 120
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)
  Exception data:
    Severity: ERROR
    SqlState: 23505
    MessageText: duplicate key value violates unique constraint "PK_DownloadHistory"
    Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
    SchemaName: public
    TableName: DownloadHistory
    ConstraintName: PK_DownloadHistory
    File: nbtinsert.c
    Line: 664
    Routine: _bt_check_unique
```

**Comment by catduckgnaf** [comment]
I've migrated all to Postgres. Radarr only one with issues. 
This issue should probably be closed, as the PR to add the solution to the documentation was merged.

**Comment by larivierec** [comment]
> it makes me wonder if something will need to be done for prowlarr as well?

All the *arr stack should have this issue post-migration, i could be wrong.
I'm not sure sonarr allows the use of Postgres yet, but yeah at least for radarr this was the solution, something similar might be the case for Prowlarr

**Comment by LilDrunkenSmurf** [comment]
> > it makes me wonder if something will need to be done for prowlarr as well?
> 
> All the *arr stack should have this issue post-migration, i could be wrong.
> I'm not sure sonarr allows the use of Postgres yet, but yeah at least for radarr this was the solution, something similar might be the case for Prowlarr
> 
> EDIT: i had to do a similar workaround for Lidarr migration

I had to do a similar workaround for prowlarr, but it was only a single table

**Comment by LilDrunkenSmurf** [comment]
> > I had to do a similar workaround for prowlarr, but it was only a single table
> 
> What table?

```Error occurred while executing task ApplicationIndexerSync: 23505: duplicate key value violates unique constraint "PK_ApplicationStatus"```

**Comment by JourneyOver** [comment]
> I'm not sure sonarr allows the use of Postgres yet

it sadly does not yet, hoping it comes eventually though.

but going by what others are saying, it does sound like we should just include this as an extra step for all the *arr apps post-migration.

**Comment by volschin** [comment]
It seems sonarr Postgres support is in work for V4. So also there.

**Comment by bakerboy448** [comment]
Closing; migration fixed with docs updates

PRs or edits to other Starr postgres docs welcomed and encouraged

**Comment by JakeShirley** [comment]
Hitting this with Readarr still using a sqlite db.  Any tips? All of these fixes seem to be for PG dbs.
