### ISSUE TITLE
Email Notification Doesn't work

### ISSUE THREAD

**Issue by sugarfunk** [Radarr/Radarr#866]
**Description:**

Tried to setup email notification, doesnt seem to work. 
I used Gmail with the correct settings (Yes i have 2fa, but used app password.(
smtp.gmail.com (also tried http/https)/465/SSL/full Email Username
also checked firewall

Pretty sure it might have something to do with this, not on my machine "C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Email\EmailService.cs"

**Radarr Version:2.0.375**

```
[v0.2.0.375] System.Net.Mail.SmtpException: Failure sending mail. ---> System.Net.WebException: The remote name could not be resolved: 'smtp.google.com'
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- End of inner exception stack trace ---
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at NzbDrone.Core.Notifications.Email.EmailService.Send(MailMessage email, String server, Int32 port, Boolean ssl, NetworkCredential credentials) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Email\EmailService.cs:line 58
   at NzbDrone.Core.Notifications.Email.EmailService.SendEmail(EmailSettings settings, String subject, String body, Boolean htmlBody) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Email\EmailService.cs:line 48
   at NzbDrone.Core.Notifications.Email.EmailService.Test(EmailSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Email\EmailService.cs:line 67

17-2-23 22:35:09.2|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to send test email
17-2-23 22:35:09.4|Error|EmailService|Error sending email. Subject: Radarr - Test Notification
17-2-23 22:35:09.4|Error|EmailService|Unable to send test email: Failure sending mail.
```

**Comment by ersan** [comment]
It says in the error that it can't resolve smtp.google.com - it should be smtp.gmail.com or smtp.googlemail.com, are you sure you typed the address correctly?

**Comment by sugarfunk** [comment]
@ersan Thanks for coming back, yes, that was one of many combinations I tried.

Below is smtp.gmail.com and smtp.googlemail.com "System IO IOExceptions" error

```
[v0.2.0.375] System.Net.Mail.SmtpException: Failure sending mail. ---> System.IO.IOException: Unable to read data from the transport connection: net_io_connectionclosed.
   at System.Net.Mail.SmtpReplyReaderFactory.ProcessRead(Byte[] buffer, Int32 offset, Int32 read, Boolean readLine)
   at System.Net.Mail.SmtpReplyReaderFactory.ReadLines(SmtpReplyReader caller, Boolean oneLine)
   at System.Net.Mail.SmtpReplyReaderFactory.ReadLine(SmtpReplyReader caller)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- End of inner exception stack trace ---
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at NzbDrone.Core.Notifications.Email.EmailService.Send(MailMessage email, String server, Int32 port, Boolean ssl, NetworkCredential credentials) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Email\EmailService.cs:line 58
   at NzbDrone.Core.Notifications.Email.EmailService.SendEmail(EmailSettings settings, String subject, String body, Boolean htmlBody) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Email\EmailService.cs:line 48
   at NzbDrone.Core.Notifications.Email.EmailService.Test(EmailSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Email\EmailService.cs:line 67

17-2-24 10:23:41.1|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to send test email
17-2-24 10:24:18.9|Error|EmailService|Error sending email. Subject: Radarr - Test Notification
17-2-24 10:24:18.9|Error|EmailService|Unable to send test email: Failure sending mail.

[v0.2.0.375] System.Net.Mail.SmtpException: Failure sending mail. ---> System.IO.IOException: Unable to read data from the transport connection: net_io_connectionclosed.
   at System.Net.Mail.SmtpReplyReaderFactory.ProcessRead(Byte[] buffer, Int32 offset, Int32 read, Boolean readLine)
   at System.Net.Mail.SmtpReplyReaderFactory.ReadLines(SmtpReplyReader caller, Boolean oneLine)
   at System.Net.Mail.SmtpReplyReaderFactory.ReadLine(SmtpReplyReader caller)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- End of inner exception stack trace ---
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at NzbDrone.Core.Notifications.Email.EmailService.Send(MailMessage email, String server, Int32 port, Boolean ssl, NetworkCredential credentials) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Email\EmailService.cs:line 58
   at NzbDrone.Core.Notifications.Email.EmailService.SendEmail(EmailSettings settings, String subject, String body, Boolean htmlBody) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Email\EmailService.cs:line 48
   at NzbDrone.Core.Notifications.Email.EmailService.Test(EmailSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Email\EmailService.cs:line 67

17-2-24 10:24:18.9|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to send test email
```

**Comment by madyoda** [comment]
Email notification working fine here.  
![image](https://cloud.githubusercontent.com/assets/5332144/23331452/388f4880-fb5e-11e6-9196-9cf5f31021e5.png)

**Comment by bartolomesoriano** [comment]
E-mail notifications are not working for me either.  Trying with gmail, ssl, port 465, correct host smtp.gmail.com, correct user and password.  It says the operation timed out in the log:

17-2-25 10:15:31.1|Error|EmailService|Error sending email. Subject: Radarr - Test Notification
17-2-25 10:15:31.1|Error|EmailService|Unable to send test email: The operation has timed out.

[v0.2.0.375] System.Net.Mail.SmtpException: The operation has timed out.
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at NzbDrone.Core.Notifications.Email.EmailService.Send(MailMessage email, String server, Int32 port, Boolean ssl, NetworkCredential credentials) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Email\EmailService.cs:line 58
   at NzbDrone.Core.Notifications.Email.EmailService.SendEmail(EmailSettings settings, String subject, String body, Boolean htmlBody) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Email\EmailService.cs:line 48
   at NzbDrone.Core.Notifications.Email.EmailService.Test(EmailSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Email\EmailService.cs:line 67

17-2-25 10:15:31.1|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to send test email

**Comment by sugarfunk** [comment]
So I tried the TLS port, on a whim (587), and it works. Cant get my head around that yet. But the email fired correctly.
![image](https://cloud.githubusercontent.com/assets/1361962/23436949/50889b98-fdda-11e6-87e2-cc295ad4d78b.png)

**Comment by onedr0p** [comment]
We might just need to update the port, maybe google changed ports?

**Comment by onedr0p** [comment]
I updated the code to default to 587 and SSL to true. Fixed in next release.
