### ISSUE TITLE
Service wont start on machine with other *arr apps

### ISSUE THREAD

**Issue by hypercube33** [Radarr/Radarr#8856]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Service starts and stops immediately. Running in a console:

PS C:\WINDOWS\system32> C:\ProgramData\Readarr\bin\Readarr.Console.exe
[Info] Bootstrap: Starting Readarr - C:\ProgramData\Readarr\bin\Readarr.Console.exe - Version 0.2.3.1955
[Debug] Bootstrap: Getting windows service status
[Debug] Bootstrap: Console selected
[Trace] EventAggregator: Publishing ApplicationStartingEvent
[Info] MigrationController: *** Migrating data source=C:\ProgramData\Readarr\readarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Debug] MigrationController: Took: 00:00:00.2102056
[Info] MigrationController: *** Migrating data source=C:\ProgramData\Readarr\cache.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Debug] MigrationController: Took: 00:00:00.0118038
[Trace] EventAggregator: ApplicationStartingEvent -> InstallUpdateService
[Trace] EventAggregator: ApplicationStartingEvent <- InstallUpdateService
[Info] SingleInstancePolicy: 1 instance(s) of Readarr are running
[Warn] SingleInstancePolicy: Another instance of Readarr is already running.
[Info] BrowserService: Starting default browser. http://localhost:8787
[Info] ProcessProvider: Opening URL [http://localhost:8787]
[Fatal] Microsoft.AspNetCore.Hosting.Diagnostics: Application startup exception

[v0.2.3.1955] NzbDrone.Host.TerminateApplicationException: Application is being terminated. Reason : Another instance is already running
   at NzbDrone.Host.SingleInstancePolicy.PreventStartIfAlreadyRunning() in ./Readarr.Host/SingleInstancePolicy.cs:line 37
   at NzbDrone.Host.Startup.EnsureSingleInstance(Boolean isService, IStartupContext startupContext, ISingleInstancePolicy instancePolicy) in ./Readarr.Host/Startup.cs:line 299
   at NzbDrone.Host.Startup.Configure(IApplicationBuilder app, IStartupContext startupContext, Lazy`1 mainDatabaseFactory, Lazy`1 logDatabaseFactory, Lazy`1 cacheDatabaseFactory, DatabaseTarget dbTarget, ISingleInstancePolicy singleInstancePolicy, InitializeLogger initializeLogger, ReconfigureLogging reconfigureLogging, IAppFolderFactory appFolderFactory, IProvidePidFile pidFileProvider, IConfigFileProvider configFileProvider, IRuntimeInfo runtimeInfo, IFirewallAdapter firewallAdapter, IEventAggregator eventAggregator, ReadarrErrorPipeline errorHandler) in ./Readarr.Host/Startup.cs:line 216
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)

[Info] Bootstrap: Application is being terminated. Reason : Another instance is already running

### Expected Behavior

Service starts and stops immediately.

### Environment

```markdown
- OS: Windows 10 Pro 21H2
- Radarr: Current release as of 7/21
- Docker Install: No
- Using Reverse Proxy: No
- Browser: N/A
- Database: Deleted it, still doesnt launch.
```

### What branch are you running?

Master

### Trace Logs?

[Readarr.txt](https://github.com/Radarr/Radarr/files/12134772/Readarr.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Also Radarr != Readarr
