### ISSUE TITLE
Only allow manual import once errors have been corrected (e.g. missing quality or movie)

### ISSUE THREAD

**Issue by schmittyd** [Radarr/Radarr#896]
r**Description:**

Can not perform a Manual Import of a Blu-Ray rip. It throws an error saying "Can't parse file"

**Radarr Version:** 0.2.0.375 develop

**Logs:**

Error occurred while executing task ManualImport: Object reference not set to an instance of an object.

System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Qualities.QualityModelComparer.Compare(QualityModel left, QualityModel right) in C:\projects\radarr-usby1\src\NzbDrone.Core\Qualities\QualityModelComparer.cs:line 29
   at System.Linq.EnumerableSorter`2.CompareKeys(Int32 index1, Int32 index2)
   at System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:line 52
   at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.Execute(ManualImportCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\Manual\ManualImportService.cs:line 299
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41

**Comment by onedr0p** [comment]
@fedoranimus you might want to take a look into this.

**Comment by fedoranimus** [comment]
Sure thing - I need to spend some time with the manual import system.

**Comment by onedr0p** [comment]
Crap I thought this was related to bulk import, don't mind me @fedoranimus ;)

**Comment by fedoranimus** [comment]
Nah, I have a few other issues with manual import as well. It seems to run fine manually, but isn't automatically running. I can take a look at this.

**Comment by Rsslone** [comment]
I have the same problem when trying to import a item that didnt get caught but the auto matching service. 


System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Qualities.QualityModelComparer.Compare(QualityModel left, QualityModel right) in C:\projects\radarr-usby1\src\NzbDrone.Core\Qualities\QualityModelComparer.cs:line 29
   at System.Linq.EnumerableSorter`2.CompareKeys(Int32 index1, Int32 index2)
   at System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:line 52
   at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.Execute(ManualImportCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\Manual\ManualImportService.cs:line 305
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41

**Comment by janipewter** [comment]
Me too.

Message
Error occurred while executing task ManualImport: Object reference not set to an instance of an object

Exception
System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.Qualities.QualityModelComparer.Compare (NzbDrone.Core.Qualities.QualityModel left, NzbDrone.Core.Qualities.QualityModel right) [0x00000] in <a65e619312484e57bf6a607be1e6496a>:0 
  at System.Linq.EnumerableSorter`2[TElement,TKey].CompareKeys (System.Int32 index1, System.Int32 index2) [0x00000] in <2392cff65f724abaaed9de072f62bc4a>:0 
  at System.Linq.EnumerableSorter`1[TElement].QuickSort (System.Int32[] map, System.Int32 left, System.Int32 right) [0x00020] in <2392cff65f724abaaed9de072f62bc4a>:0 
  at System.Linq.EnumerableSorter`1[TElement].Sort (TElement[] elements, System.Int32 count) [0x00025] in <2392cff65f724abaaed9de072f62bc4a>:0 
  at System.Linq.OrderedEnumerable`1+<GetEnumerator>c__Iterator0[TElement].MoveNext () [0x0005a] in <2392cff65f724abaaed9de072f62bc4a>:0 
  at System.Linq.Enumerable+<SelectManyIterator>c__Iterator2`2[TSource,TResult].MoveNext () [0x000bc] in <2392cff65f724abaaed9de072f62bc4a>:0 
  at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x0008b] in <f712f98eb8e445c8918edaf595bbe465>:0 
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00011] in <2392cff65f724abaaed9de072f62bc4a>:0 
  at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import (System.Collections.Generic.List`1[T] decisions, System.Boolean newDownload, NzbDrone.Core.Download.DownloadClientItem downloadClientItem, NzbDrone.Core.MediaFiles.EpisodeImport.ImportMode importMode) [0x000a2] in <a65e619312484e57bf6a607be1e6496a>:0 
  at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.Execute (NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportCommand message) [0x00199] in <a65e619312484e57bf6a607be1e6496a>:0 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x00081] in <a65e619312484e57bf6a607be1e6496a>:0 
Close
Radarr Ver. 0.2.0.375

**Comment by onedr0p** [comment]
What do your movie file names look like for these movies

**Comment by janipewter** [comment]
00001.m2ts

**Comment by onedr0p** [comment]
Radarr is supposed to know what movie that is?

**Comment by janipewter** [comment]
No, that's why you tell it which movie it is on the manual import screen.

http://imgur.com/a/UKvYU

**Comment by onedr0p** [comment]
@galilieo maybe we need to have quality a selectbox

**Comment by Rsslone** [comment]
The directory is D:\qBittorrent\Completed\REQ-Radarr\The.Men.Who.Stare.at.Goats.2009.1080p.BluRay.x264-SECTOR7\s7-men.who.stare.at.goats.x264

Movie name: The Men Who Stare at Goats
File name: s7-men.who.stare.at.goats.x264.mkv

This happens pretty often for me and im not sure whats going on.
```
`System.NullReferenceException:` Object reference not set to an instance of an object.
   at NzbDrone.Core.Qualities.QualityModelComparer.Compare(QualityModel left, QualityModel right) in C:\projects\radarr-usby1\src\NzbDrone.Core\Qualities\QualityModelComparer.cs:line 29
   at System.Linq.EnumerableSorter`2.CompareKeys(Int32 index1, Int32 index2)
   at System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:line 52
   at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.Execute(ManualImportCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\Manual\ManualImportService.cs:line 302
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41
```

**Comment by galli-leo** [comment]
@RSSLone This happens when no profile is set for the movie

**Comment by Rsslone** [comment]
@galli-leo The profile is set to 1080p. idk.

**Comment by krin-san** [comment]
A lot of russian movies fails to be imported with the same error.

Movie: https://www.themoviedb.org/movie/807-se7en
Also known as: **Se7en, Seven - Se7en and The Seven Deadly Sins.**
Profile: **HD - 720p/7080p**
Downloaded file path: `/media/downloads/_MOVIES/Se7en_1080p_EuReKA.mkv`
Destination filder: `/media/movies/Se7en (1995)/`

Failed to be imported automatically with the error:
```
Se7en_1080p_EuReKA.mkv
Unable to parse file
```
Manual import failed too with the following record in the logs:
```
Message
Error occurred while executing task ManualImport: Object reference not set to an instance of an object

Exception
System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.Qualities.QualityModelComparer.Compare (NzbDrone.Core.Qualities.QualityModel left, NzbDrone.Core.Qualities.QualityModel right) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Qualities\QualityModelComparer.cs:29 
  at System.Linq.EnumerableSorter`2[TElement,TKey].CompareKeys (System.Int32 index1, System.Int32 index2) [0x00000] in /wrkdirs/usr/ports/lang/mono/work/mono-mono-4.8.1.0/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:2558 
  at System.Linq.EnumerableSorter`1[TElement].QuickSort (System.Int32[] map, System.Int32 left, System.Int32 right) [0x00017] in /wrkdirs/usr/ports/lang/mono/work/mono-mono-4.8.1.0/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:2513 
  at System.Linq.EnumerableSorter`1[TElement].Sort (TElement[] elements, System.Int32 count) [0x00025] in /wrkdirs/usr/ports/lang/mono/work/mono-mono-4.8.1.0/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:2503 
  at System.Linq.OrderedEnumerable`1+<GetEnumerator>c__Iterator0[TElement].MoveNext () [0x0005a] in /wrkdirs/usr/ports/lang/mono/work/mono-mono-4.8.1.0/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:2450 
  at System.Linq.Enumerable+<SelectManyIterator>c__Iterator2`2[TSource,TResult].MoveNext () [0x0009a] in /wrkdirs/usr/ports/lang/mono/work/mono-mono-4.8.1.0/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:424 
  at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x0008b] in /wrkdirs/usr/ports/lang/mono/work/mono-mono-4.8.1.0/mcs/class/referencesource/mscorlib/system/collections/generic/list.cs:99 
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00011] in /wrkdirs/usr/ports/lang/mono/work/mono-mono-4.8.1.0/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:861 
  at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import (System.Collections.Generic.List`1[T] decisions, System.Boolean newDownload, NzbDrone.Core.Download.DownloadClientItem downloadClientItem, NzbDrone.Core.MediaFiles.EpisodeImport.ImportMode importMode) [0x00016] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:52 
  at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.Execute (NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportCommand message) [0x00186] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\Manual\ManualImportService.cs:316 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x00081] in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:77 
```
Any ideas on what could be wrong in `QualityModelComparer`? I could take a look but knows nothing about implementation for now.

**Comment by galli-leo** [comment]
@krin-san Probably, because it can't parse the quality of the file. Submitted a fix for that today though, should be on nightly by now.

**Comment by krin-san** [comment]
@galli-leo, import succeded on nightly version but led me to another issue #2349
