### ISSUE TITLE
tmpfs causing repeated warnings from DiskProvider

### ISSUE THREAD

**Issue by pn-taylor** [Radarr/Radarr#9013]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Logs for Radarr are full of the following warning:

Unable to get drive mounts: Failed to fetch drive info for mount point: /run/user/1000/doc: Failed to fetch drive info for mount point: /run/user/1000/doc

From running df -h this shows up as tmpfs which has immutable permissions.

Event log reads:
System.Exception: Failed to fetch drive info for mount point: /run/user/1000/doc
 ---> System.UnauthorizedAccessException: Access to the path is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
   at System.IO.DriveInfo.get_DriveFormat()
   at NzbDrone.Mono.Disk.DiskProvider.<>c.<GetAllMounts>b__16_0(DriveInfo d) in ./Radarr.Mono/Disk/DiskProvider.cs:line 193
   --- End of inner exception stack trace ---
   at NzbDrone.Mono.Disk.DiskProvider.<>c.<GetAllMounts>b__16_0(DriveInfo d) in ./Radarr.Mono/Disk/DiskProvider.cs:line 193
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at NzbDrone.Mono.Disk.DiskProvider.GetAllMounts() in ./Radarr.Mono/Disk/DiskProvider.cs:line 203

### Expected Behavior

Ignore tmpfs entirely when fetching drive info

### Steps To Reproduce

1. Go to 'System'
2. Click on 'Events'
3. Observe many entries

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS
- Radarr: 4.6.4.7568
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Edge
- Database: Sqlite 3.37.2
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

https://pastebin.ubuntu.com/p/ywS7gD2vrq/

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
> Radarr: 4.6.4.7568

https://github.com/Radarr/Radarr/releases/tag/v4.7.5.7809

You're out of date; update

**Comment by pn-taylor** [comment]
> > Radarr: 4.6.4.7568
> 
> https://github.com/Radarr/Radarr/releases/tag/v4.7.5.7809
> 
> You're out of date; update

I did see that but didn't see that in the fixes/notes, will update and see if it persists.

**Comment by Qstick** [comment]
Nothing will change on update. It's failing during getting drive format due to permissions while getting mounts to analyze before it even tries to get freespace or other

**Comment by pn-taylor** [comment]
> Nothing will change on update. It's failing during getting drive format due to permissions while getting mounts to analyze before it even tries to get freespace or other

That's what I thought, I haven't had chance to update yet but from what I've noted, you can't change the permissions to this so, realistically, Radarr (and potentially other *arr apps) need to ignore these.

**Comment by Qstick** [comment]
Sure this is difficult when it fails while we are getting mount drive format info. I'd venture to say we would see more cases of this if it wasn't fixable given how large our Linux install base is. Care to stop by the discord to dig in further with some of the team?

**Comment by pn-taylor** [comment]
> > Radarr: 4.6.4.7568
> 
> https://github.com/Radarr/Radarr/releases/tag/v4.7.5.7809
> 
> You're out of date; update

I have updated now, the issue still persists in the events log.

**Comment by Rio-D** [comment]
Just noticed the same issue on a new system I setup:
```

System.Exception: Failed to fetch drive info for mount point: /run/user/1000/doc
 ---> System.UnauthorizedAccessException: Access to the path is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
   at System.IO.DriveInfo.get_DriveFormat()
   at NzbDrone.Mono.Disk.DiskProvider.<>c.<GetAllMounts>b__16_0(DriveInfo d) in ./Radarr.Mono/Disk/DiskProvider.cs:line 193
   --- End of inner exception stack trace ---
   at NzbDrone.Mono.Disk.DiskProvider.<>c.<GetAllMounts>b__16_0(DriveInfo d) in ./Radarr.Mono/Disk/DiskProvider.cs:line 193
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at NzbDrone.Mono.Disk.DiskProvider.GetAllMounts() in ./Radarr.Mono/Disk/DiskProvider.cs:line 203
```

```
- OS: Ubuntu 22.04.3 LTS
- Radarr: 4.7.5.7809
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox
- Database: Sqlite 3.37.2
```

**Comment by pn-taylor** [comment]
> Sure this is difficult when it fails while we are getting mount drive format info. I'd venture to say we would see more cases of this if it wasn't fixable given how large our Linux install base is. Care to stop by the discord to dig in further with some of the team?

I'm around on Discord so feel free to mention me if someone's around to take a deeper look.

**Comment by Danzig67** [comment]
> Just noticed the same issue on a new system I setup:
> 
> ```
> 
> System.Exception: Failed to fetch drive info for mount point: /run/user/1000/doc
>  ---> System.UnauthorizedAccessException: Access to the path is denied.
>  ---> System.IO.IOException: Operation not permitted
>    --- End of inner exception stack trace ---
>    at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
>    at System.IO.DriveInfo.get_DriveFormat()
>    at NzbDrone.Mono.Disk.DiskProvider.<>c.<GetAllMounts>b__16_0(DriveInfo d) in ./Radarr.Mono/Disk/DiskProvider.cs:line 193
>    --- End of inner exception stack trace ---
>    at NzbDrone.Mono.Disk.DiskProvider.<>c.<GetAllMounts>b__16_0(DriveInfo d) in ./Radarr.Mono/Disk/DiskProvider.cs:line 193
>    at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
>    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
>    at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
>    at NzbDrone.Mono.Disk.DiskProvider.GetAllMounts() in ./Radarr.Mono/Disk/DiskProvider.cs:line 203
> ```
> 
> ```
> - OS: Ubuntu 22.04.3 LTS
> - Radarr: 4.7.5.7809
> - Docker Install: No
> - Using Reverse Proxy: No
> - Browser: Firefox
> - Database: Sqlite 3.37.2
> ```

I'm getting Radarr constantly throw these errors in the event log too. Not sure what to do about it or if it is just safe to ignore. Have a pretty much identical set up on Sonarr and not getting the same issue.
