### ISSUE TITLE
Magnet errors should be handled properly

### ISSUE THREAD

**Issue by jl1990** [Radarr/Radarr#9125]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When a magnet URL is invalid, Radarr correctly displays the exception in the event log, but it doesn't mark the download as failed.
As a result, the file download is not retried.

### Expected Behavior

After trying to download and realize that the magnet URL is invalid, the download should be marked as failed, so Radarr can try to find another suitable release

### Environment

```markdown
- OS: linux/amd64
- Radarr: 4.7.5.7809
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: 
- Database:
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

Log:

`Failed to parse magnetlink for movie **MOVIE LINK REMOVED BY ME**: Magnet links must start with 'magnet:'.
`

Exception:

`System.FormatException: Magnet links must start with 'magnet:'.
   at MonoTorrent.MagnetLink.FromUri(Uri uri)
   at MonoTorrent.MagnetLink.Parse(String uri)
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromMagnetUrl(RemoteMovie remoteMovie, String magnetUrl) in ./Radarr.Core/Download/TorrentClientBase.cs:line 214`

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by jl1990** [comment]
As I understand, instead of returning null here: https://github.com/Radarr/Radarr/blob/d6749a0c8e4c38407a51ba483ada76fe2b9840f5/src/NzbDrone.Core/Download/TorrentClientBase.cs#L220
an exception should be raised...
