### ISSUE TITLE
Default Root Folder for Adding Movies via API

### ISSUE THREAD

**Issue by apply3387** [Radarr/Radarr#9127]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Not sure if this is a Radarr issue or Overseerr issue, but I have not had the same issue with Sonarr after upgrading my hard drive and migrating my data.

Requests via Overseerr that do not specify a root folder default to old root folder. After deleting old root folder and adding new one, requesting a movie via Overseerr adds movie to Radarr, but sets root directory for new movie to old directory path and import fails with RootFolderNotFoundException

### Expected Behavior

Movie adds via API with unspecified root folder should default to first/only configured root folder for import (or user-specified if multiple root folders configured).

### Steps To Reproduce

1. Integrate Overseerr for requests, without specified root folder
2. Add new root folder
3. Delete old root folder
4. Request movie via Overseerr
5. Movie is added to Radarr with old root folder

### Environment

```markdown
- OS: Win10
- Radarr: 4.7.5.7809
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome 116.0.5845.141
- Database: Sqlite 3.36.0

- "Old" root folder: Y:\Movies (Deleted via Media Management Settings page, confirmed via DB Browser)
- "New" root folder: X:\Movies
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

2023-09-04 10:03:31.4|Info|AddMovieService|Adding Movie [Elemental (2023)][tt15789038, 976573] Path: [Y:\Movies\Elemental (2023)]
2023-09-04 10:03:31.5|Info|RefreshMovieService|Updating info for Elemental
2023-09-04 10:03:32.3|Info|MediaCoverService|Downloading Poster for [Elemental (2023)][tt15789038, 976573] https://image.tmdb.org/t/p/original/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg
2023-09-04 10:03:32.3|Warn|DiskScanService|Movie's root folder (Y:\Movies) doesn't exist.
2023-09-04 10:03:32.3|Info|MovieScannedHandler|[Elemental] was recently added, performing post-add actions
2023-09-04 10:03:32.3|Info|ReleaseSearchService|Searching indexers for [Elemental]. 1 active indexers
2023-09-04 10:03:32.6|Info|MediaCoverService|Downloading Fanart for [Elemental (2023)][tt15789038, 976573] https://image.tmdb.org/t/p/original/5luaIi1lLzLfgl8oywifeUtPN6W.jpg
2023-09-04 10:03:33.4|Info|MetadataService|Movie folder does not exist, skipping metadata image creation
2023-09-04 10:03:37.4|Info|DownloadDecisionMaker|Processing 43 releases
2023-09-04 10:03:41.2|Info|DownloadService|Report for Elemental (2023) sent to qBittorrent from indexer 1337x (Prowlarr). Elemental.2023.1080p.WEBRip.1400MB.DD5.1.x264-GalaxyRG
2023-09-04 10:03:41.3|Info|MovieSearchService|Movie search completed. 1 reports downloaded.
2023-09-04 10:04:14.9|Info|ImportListSyncService|No auto enabled lists, skipping sync and cleaning
2023-09-04 10:09:15.1|Info|ImportListSyncService|No auto enabled lists, skipping sync and cleaning
2023-09-04 10:10:15.2|Error|TaskExtensions|Task Error

2023-09-04 10:10:45.5|Warn|ImportApprovedMovie|Couldn't import movie \\seedbox\downloads\Elemental.2023.1080p.WEBRip.1400MB.DD5.1.x264-GalaxyRG[TGx]\Elemental.2023.1080p.WEBRip.1400MB.DD5.1.x264-GalaxyRG.mkv

[v4.7.5.7809] NzbDrone.Core.MediaFiles.MovieImport.RootFolderNotFoundException: Root folder 'Y:\Movies' was not found.
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.EnsureMovieFolder(MovieFile movieFile, Movie movie, String filePath) in ./Radarr.Core/MediaFiles/MovieFileMovingService.cs:line 177
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.EnsureMovieFolder(MovieFile movieFile, LocalMovie localMovie, String filePath) in ./Radarr.Core/MediaFiles/MovieFileMovingService.cs:line 165
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in ./Radarr.Core/MediaFiles/MovieFileMovingService.cs:line 78
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in ./Radarr.Core/MediaFiles/UpgradeMediaFileService.cs:line 77
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in ./Radarr.Core/MediaFiles/MovieImport/ImportApprovedMovie.cs:line 129

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Radarr does not have any default root folder for the api. The UI remembers the last one selected on that device and third party apps provide them in the api call
