### ISSUE TITLE
Failing to Import Custom List

### ISSUE THREAD

**Issue by andregdias** [Radarr/Radarr#9139]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When importing a custom list that has this structure
```
[{"id":365620,"imdb_id":"tt3758542","title":"Ferrari","release_year":"2023","clean_title":"/film/ferrari-2023/","adult":false}
,{"id":346698,"imdb_id":"tt1517268","title":"Barbie","release_year":"2023","clean_title":"/film/barbie/","adult":false}
,{"id":1107940,"imdb_id":"tt24634274","title":"Sunset: The Mystery of the Necklace of São Cajó","release_year":"2023","clean_title":"/film/sunset-the-mystery-of-the-necklace-of-sao-cajo/","adult":false}
,{"id":980489,"imdb_id":"tt4495098","title":"Gran Turismo","release_year":"2023","clean_title":"/film/gran-turismo/","adult":false}
,{"id":951491,"imdb_id":"tt21807222","title":"Saw X","release_year":"2023","clean_title":"/film/saw-x/","adult":false}
,{"id":976573,"imdb_id":"tt15789038","title":"Elemental","release_year":"2023","clean_title":"/film/elemental-2023/","adult":false}
,{"id":335977,"imdb_id":"tt1462764","title":"Indiana Jones and the Dial of Destiny","release_year":"2023","clean_title":"/film/indiana-jones-and-the-dial-of-destiny/","adult":false}
,{"id":299054,"imdb_id":"tt3291150","title":"Expend4bles","release_year":"2023","clean_title":"/film/expend4bles/","adult":false}
,{"id":385687,"imdb_id":"tt5433140","title":"Fast X","release_year":"2023","clean_title":"/film/fast-x/","adult":false}
,{"id":986056,"imdb_id":"tt20969586","title":"Thunderbolts","release_year":"2024","clean_title":"/film/thunderbolts/","adult":false}
,{"id":911916,"imdb_id":"tt16360004","title":"Spider-Man: Beyond the Spider-Verse","release_year":"","clean_title":"/film/spider-man-beyond-the-spider-verse/","adult":false}]
```

the application throws an error and does not conclude.

### Expected Behavior

List to be properly processed, this was working before.

### Environment

```markdown
- OS: Windows
- Radarr: v5.0.1.7993
- Docker Install: No
- Using Reverse Proxy: No
- Browser: 
- Database:
```

### What branch are you running?

Develop

### Trace Logs? **Not Optional**

```
[v5.0.1.7993] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.ImportLists.ImportListMovies.ImportListMovie.get_TmdbId() in ./Radarr.Core/ImportLists/ImportListMovies/ImportListMovie.cs:line 25
   at NzbDrone.Core.ImportLists.ImportListMovies.ImportListMovieService.<>c__DisplayClass5_1.<SyncMoviesForList>b__4(ImportListMovie e) in ./Radarr.Core/ImportLists/ImportListMovies/ImportListMovieService.cs:line 49
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at NzbDrone.Core.ImportLists.ImportListMovies.ImportListMovieService.<>c__DisplayClass5_0.<SyncMoviesForList>b__0(ImportListMovie l) in ./Radarr.Core/ImportLists/ImportListMovies/ImportListMovieService.cs:line 49
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at NzbDrone.Core.ImportLists.ImportListMovies.ImportListMovieService.SyncMoviesForList(List`1 listMovies, Int32 listId) in ./Radarr.Core/ImportLists/ImportListMovies/ImportListMovieService.cs:line 0
   at NzbDrone.Core.ImportLists.FetchAndParseImportListService.<>c__DisplayClass8_2.<Fetch>b__3() in ./Radarr.Core/ImportLists/FetchAndParseImportListService.cs:line 125
```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by andregdias** [comment]
From my digging into the code, I think the `TmdbId` should be correctly fetched from the `id` field on the json.

**Comment by andregdias** [comment]
If it helps, I'm serving the list via [letterboxd-list-radarr](https://github.com/screeny05/letterboxd-list-radarr).
[Here](https://letterboxd-list-radarr.onrender.com/screeny05/list/jackie-chan-the-definitive-list/)'s an example list provided by it.

**Comment by andregdias** [comment]
```
2023-09-07 13:41:13.2|Trace|CommandQueueManager|Publishing ImportListSync
2023-09-07 13:41:13.2|Trace|CommandQueueManager|Checking if command is queued or started: ImportListSync
2023-09-07 13:41:13.2|Trace|CommandQueueManager|Inserting new command: ImportListSync
2023-09-07 13:41:13.2|Trace|CommandExecutor|ImportListSyncCommand -> ImportListSyncService
2023-09-07 13:41:13.2|Trace|CommandQueueManager|Marking command as started: ImportListSync
2023-09-07 13:41:13.2|Trace|Http|Res: 625 [POST] /api/v3/command: 201.Created (5 ms)
2023-09-07 13:41:13.2|Debug|Api|[POST] /api/v3/command: 201.Created (5 ms)
2023-09-07 13:41:13.2|Trace|EventAggregator|Publishing CommandUpdatedEvent
2023-09-07 13:41:13.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2023-09-07 13:41:13.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2023-09-07 13:41:13.2|Debug|FetchAndParseImportListService|Available import lists 1
2023-09-07 13:41:13.2|Info|FetchAndParseImportListService|Syncing Movies for Import List Custom Lists (Letterboxd)
2023-09-07 13:41:13.2|Trace|EventAggregator|Publishing CommandUpdatedEvent
2023-09-07 13:41:13.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2023-09-07 13:41:13.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2023-09-07 13:41:13.2|Debug|RadarrListImport|Downloading List https://letterboxd-list-radarr.onrender.com/andredias/watchlist/
2023-09-07 13:41:13.2|Trace|HttpClient|Req: [GET] https://letterboxd-list-radarr.onrender.com/andredias/watchlist/
2023-09-07 13:41:13.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-09-07 13:41:13.4|Trace|HttpClient|Res: HTTP/2.0 [GET] https://letterboxd-list-radarr.onrender.com/andredias/watchlist/: 200.OK (12379 bytes) (130 ms)
2023-09-07 13:41:13.4|Debug|FetchAndParseImportListService|Found 84 from Import List Custom Lists (Letterboxd)
2023-09-07 13:41:13.5|Debug|MovieMetadataRepository|0 movie metadata up to date; Updating 84, Adding 0 movie metadata entries.
2023-09-07 13:41:13.6|Error|FetchAndParseImportListService|Error during Import List Sync of Custom Lists (Letterboxd)

[v5.0.1.7993] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.ImportLists.ImportListMovies.ImportListMovie.get_TmdbId() in ./Radarr.Core/ImportLists/ImportListMovies/ImportListMovie.cs:line 25
   at NzbDrone.Core.ImportLists.ImportListMovies.ImportListMovieService.<>c__DisplayClass5_1.<SyncMoviesForList>b__4(ImportListMovie e) in ./Radarr.Core/ImportLists/ImportListMovies/ImportListMovieService.cs:line 49
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at NzbDrone.Core.ImportLists.ImportListMovies.ImportListMovieService.<>c__DisplayClass5_0.<SyncMoviesForList>b__0(ImportListMovie l) in ./Radarr.Core/ImportLists/ImportListMovies/ImportListMovieService.cs:line 49
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at NzbDrone.Core.ImportLists.ImportListMovies.ImportListMovieService.SyncMoviesForList(List`1 listMovies, Int32 listId) in ./Radarr.Core/ImportLists/ImportListMovies/ImportListMovieService.cs:line 0
   at NzbDrone.Core.ImportLists.FetchAndParseImportListService.<>c__DisplayClass8_2.<Fetch>b__3() in ./Radarr.Core/ImportLists/FetchAndParseImportListService.cs:line 125


2023-09-07 13:41:13.6|Debug|FetchAndParseImportListService|Found 84 total reports from 0 lists
2023-09-07 13:41:13.6|Trace|CommandQueueManager|Updating command status
2023-09-07 13:41:13.6|Trace|EventAggregator|Publishing CommandUpdatedEvent
2023-09-07 13:41:13.6|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2023-09-07 13:41:13.6|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2023-09-07 13:41:13.6|Trace|EventAggregator|Publishing CommandExecutedEvent
2023-09-07 13:41:13.6|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2023-09-07 13:41:13.6|Trace|TaskManager|Updating last run time for: NzbDrone.Core.ImportLists.ImportListSyncCommand
2023-09-07 13:41:13.6|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2023-09-07 13:41:13.6|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2023-09-07 13:41:13.6|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2023-09-07 13:41:13.6|Trace|EventAggregator|CommandExecutedEvent -> QualityDefinitionController
2023-09-07 13:41:13.6|Trace|EventAggregator|CommandExecutedEvent <- QualityDefinitionController
2023-09-07 13:41:13.6|Trace|CommandExecutor|ImportListSyncCommand <- ImportListSyncService [00:00:00.3492170]
```

**Comment by andregdias** [comment]
@bakerboy448, would these be enough?

**Comment by nasssssss2363** [comment]
> @bakerboy448, would these be enough?

Have you solved this problem? I am also looking for a solution.

**Comment by bakerboy448** [comment]
When there is an update this issue will be commented on or closed when a PR fixing it is landed.

Radarr has ~ no active developers and no one from the community has decided to work on this issue

**Comment by adenwuts** [comment]
After trying and failing to reproduce this issue it appears to now be resolved.
