### ISSUE TITLE
… is an invalid escapable character within a JSON string

### ISSUE THREAD

**Issue by paulirish** [Radarr/Radarr#9172]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

User-facing-wise... I see "unable to load movies".

![image](https://github.com/Radarr/Radarr/assets/39191/a9fe46fc-b2cb-4157-8293-fbf4dbf43e5f)

### Expected Behavior

It works. 
I'd expect that even with an invalid character in JSON read from the movie metadata in the DB, the home view of viewing all movies wouldn't be completely unavailable.

### Steps To Reproduce

1. Seemingly have something odd in your Princess Mononoke metadata

### Environment

```markdown
- OS: synology dsm 7.2
0 Version: 4.7.5.7809
- Package Version: 4.7.5.7809-ls187 by linuxserver.io
- .NET: Yes (6.0.16)
- Docker Yes
- Using Reverse Proxy: no
- Browser: chrome 
- Database: migration 227. Sqlite 3.41.2
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

```

2023-09-11 13:24:30.9|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/movie

[v4.7.5.7809] System.Data.DataException: Error parsing column 16 (MediaInfo={
  "rawStreamData": "{    \u0022streams\u0022: [        {            \u0022index\u0022: 0,            \u0022codec_name\u0022: \u0022hevc\u0022,            \u0022codec_long_name\u0022: \u0022H.265 / HEVC (High Efficiency Video Coding)\u0022,            \u0022profile\u0022: \u0022Main 10\u0022,            \u0022codec_type\u0022: \u0022video\u0022,            \u0022codec_tag_string\u0022: \u0022x265\u0022,            \u0022codec_tag\u0022: \u00220x35363278\u0022,            \u0022width\u0022: 1920,            \u0022height\u0022: 1040,            \u0022coded_width\u0022: 1920,            \u0022coded_height\u0022: 1040,            \u0022closed_captions\u0022: 0,            \u0022film_grain\u0022: 0,            \u0022has_b_frames\u0022: 2,            \u0022sample_aspect_ratio\u0022: \u00221:1\u0022,            \u0022display_aspect_ratio\u0022: \u002224:13\u0022,            \u0022pix_fmt\u0022: \u0022yuv420p10le\u0022,            \u0022level\u0022: 120,            \u0022color_range\u0022: \u0022tv\u0022,            \u0022chroma_location\u0022: \u0022left\u0022,            \u0022refs\u0022: 1,            \u0022r_frame_rate\u0022: \u002224000/1001\u0022,            \u0022avg_frame_rate\u0022: \u002224000/1001\u0022,            \u0022time_base\u0022: \u00221/1000\u0022,            \u0022start_pts\u0022: 0,            \u0022start_time\u0022: \u00220:00:00.000000\u0022,            \u0022extradata_size\u0022: 2649,            \u0022disposition\u0022: {                \u0022default\u0022: 1,                \u0022dub\u0022: 0,                \u0022original\u0022: 0,                \u0022comment\u0022: 0,                \u0022lyrics\u0022: 0,                \u0022karaoke\u0022: 0,                \u0022forced\u0022: 1,                \u0022hearing_impaired\u0022: 0,                \u0022visual_impaired\u0022: 0,                \u0022clean_effects\u0022: 0,                \u0022attached_pic\u0022: 0,                \u0022timed_thumbnails\u0022: 0,                \u0022captions\u0022: 0,                \u0022descriptions\u0022: 0,                \u0022metadata\u0022: 0,                \u0022dependent\u0022: 0,                \u0022still_image\u0022: 0            },            \u0022tags\u0022: {                \u0022BPS\u0022: \u00225249390\u0022,                \u0022DURATION\u0022: \u002202:14:06.622000000\u0022,                \u0022NUMBER_OF_FRAMES\u0022: \u0022192926\u0022,                \u0022NUMBER_OF_BYTES\u0022: \u00225279982576\u0022,                \u0022_STATISTICS_WRITING_APP\u0022: \u0022mkvmerge v76.0 (\u0027Celebration\u0027) 64-bit\u0022,                \u0022_STATISTICS_WRITING_DATE_UTC\u0022: \u00222023-05-08 11:48:42\u0022,                \u0022_STATISTICS_TAGS\u0022: \u0022BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\u0022            }        },        {            \u0022index\u0022: 1,            \u0022codec_name\u0022: \u0022eac3\u0022,            \u0022codec_long_name\u0022: \u0022ATSC A/52B (AC-3, E-AC-3)\u0022,            \u0022codec_type\u0022: \u0022audio\u0022,            \u0022codec_tag_string\u0022: \u0022[0][0][0][0]\u0022,            \u0022codec_tag\u0022: \u00220x0000\u0022,            \u0022sample_fmt\u0022: \u0022fltp\u0022,            \u0022sample_rate\u0022: \u002248000\u0022,            \u0022channels\u0022: 6,            \u0022channel_layout\u0022: \u00225.1(side)\u0022,            \u0022bits_per_sample\u0022: 0,            \u0022r_frame_rate\u0022: \u00220/0\u0022,            \u0022avg_frame_rate\u0022: \u00220/0\u0022,            \u0022time_base\u0022: \u00221/1000\u0022,            \u0022start_pts\u0022: 0,            \u0022start_time\u0022: \u00220:00:00.000000\u0022,            \u0022bit_rate\u0022: \u0022768000\u0022,            \u0022disposition\u0022: {                \u0022default\u0022: 1,                \u0022dub\u0022: 0,                \u0022original\u0022: 0,                \u0022comment\u0022: 0,                \u0022lyrics\u0022: 0,                \u0022karaoke\u0022: 0,                \u0022forced\u0022: 0,                \u0022hearing_impaired\u0022: 0,                \u0022visual_impaired\u0022: 0,                \u0022clean_effects\u0022: 0,                \u0022attached_pic\u0022: 0,                \u0022timed_thumbnails\u0022: 0,                \u0022captions\u0022: 0,                \u0022descriptions\u0022: 0,                \u0022metadata\u0022: 0,                \u0022dependent\u0022: 0,                \u0022still_image\u0022: 0            },            \u0022tags\u0022: {                \u0022language\u0022: \u0022jpn\u0022,                \u0022BPS\u0022: \u0022768000\u0022,                \u0022DURATION\u0022: \u002202:14:06.592000000\u0022,                \u0022NUMBER_OF_FRAMES\u0022: \u0022251456\u0022,                \u0022NUMBER_OF_BYTES\u0022: \u0022772472832\u0022,                \u0022_STATISTICS_WRITING_APP\u0022: \u0022mkvmerge v76.0 (\u0027Celebration\u0027) 64-bit\u0022,                \u0022_STATISTICS_WRITING_DATE_UTC\u0022: \u00222023-05-08 11:48:42\u0022,                \u0022_STATISTICS_TAGS\u0022: \u0022BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\u0022            }        },        {            \u0022index\u0022: 2,            \u0022codec_name\u0022: \u0022eac3\u0022,            \u0022codec_long_name\u0022: \u0022ATSC A/52B (AC-3, E-AC-3)\u0022,            \u0022codec_type\u0022: \u0022audio\u0022,            \u0022codec_tag_string\u0022: \u0022[0][0][0][0]\u0022,            \u0022codec_tag\u0022: \u00220x0000\u0022,            \u0022sample_fmt\u0022: \u0022fltp\u0022,            \u0022sample_rate\u0022: \u002248000\u0022,            \u0022channels\u0022: 6,            \u0022channel_layout\u0022: \u00225.1(side)\u0022,            \u0022bits_per_sample\u0022: 0,            \u0022r_frame_rate\u0022: \u00220/0\u0022,            \u0022avg_frame_rate\u0022: \u00220/0\u0022,            \u0022time_base\u0022: \u00221/1000\u0022,            \u0022start_pts\u0022: 0,            \u0022start_time\u0022: \u00220:00:00.000000\u0022,            \u0022bit_rate\u0022: \u0022768000\u0022,            \u0022disposition\u0022: {                \u0022default\u0022: 0,                \u0022dub\u0022: 0,                \u0022original\u0022: 0,                \u0022comment\u0022: 0,                \u0022lyrics\u0022: 0,                \u0022karaoke\u0022: 0,                \u0022forced\u0022: 0,                \u0022hearing_impaired\u0022: 0,                \u0022visual_impaired\u0022: 0,                \u0022clean_effects\u0022: 0,                \u0022attached_pic\u0022: 0,                \u0022timed_thumbnails\ 0022: 0,                \u0022captions\u0022: 0,               h\u0022descriptions\u0022: 0,                \u0022metadata\u0022: 0,                \u0022dependent\u0022: 0,                \u0022still_image\u0022: 0            },            \u0022tags\u0022: {                \u0022language\u0022: \u0022eng\u0022,                \u0022BPS\u0022: \u0022768000\u0022,                \u0022DURATION\u0022: \u002202:14:06.592000000\u0022,                \u0022NUMBER_OF_FRAMES\u0022: \u0022251456\u0022,                \u0022NUMBER_OF_BYTES\u0022: \u0022772472832\u0022,                \u0022_STATISTICS_WRITING_APP\u0022: \u0022mkvmerge v76.0 (\u0027Celebration\u0027) 64-bit\u0022,                \u0022_STATISTICS_WRITING_DATE_UTC\u0022: \u00222023-05-08 11:48:42\u0022,                \u0022_STATISTICS_TAGS\u0022: \u0022BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\u0022            }        },        {            \u0022index\u0022: 3,            \u0022codec_name\u0022: \u0022dvd_subtitle\u0022,            \u0022codec_long_name\u0022: \u0022DVD subtitles\u0022,            \u0022codec_type\u0022: \u0022subtitle\u0022,            \u0022codec_tag_string\u0022: \u0022[0][0][0][0]\u0022,            \u0022codec_tag\u0022: \u00220x0000\u0022,            \u0022width\u0022: 1920,            \u0022height\u0022: 1080,            \u0022r_frame_rate\u0022: \u00220/0\u0022,            \u0022avg_frame_rate\u0022: \u00220/0\u0022,            \u0022time_base\u0022: \u00221/1000\u0022,            \u0022start_pts\u0022: 0,            \u0022start_time\u0022: \u00220:00:00.000000\u0022,            \u0022duration_ts\u0022: 8046622,            \u0022duration\u0022: \u00222:14:06.622000\u0022,            \u0022extradata_size\u0022: 344,            \u0022disposition\u0022: {                \u0022default\u0022: 0,                \u0022dub\u0022: 0,                \u0022original\u0022: 0,                \u0022comment\u0022: 0,                \u0022lyrics\u0022: 0,                \u0022karaoke\u0022: 0,                \u0022forced\u0022: 0,                \u0022hearing_impaired\u0022: 0,                \u0022visual_impaired\u0022: 0,                \u0022clean_effects\u0022: 0,                \u0022attached_pic\u0022: 0,                \u0022timed_thumbnails\u0022: 0,                \u0022captions\u0022: 0,                \u0022descriptions\u0022: 0,                \u0022metadata\u0022: 0,                \u0022dependent\u0022: 0,                \u0022still_image\u0022: 0            },            \u0022tags\u0022: {                \u0022language\u0022: \u0022eng\u0022,                \u0022BPS\u0022: \u00227553\u0022,                \u0022DURATION\u0022: \u002202:07:52.951000000\u0022,                \u0022NUMBER_OF_FRAMES\u0022: \u00221200\u0022,                \u0022NUMBER_OF_BYTES\u0022: \u00227244878\u0022,                \u0022_STATISTICS_WRITING_APP\u0022: \u0022mkvmerge v76.0 (\u0027Celebration\u0027) 64-bit\u0022,                \u0022_STATISTICS_WRITING_DATE_UTC\u0022: \u00222023-05-08 11:48:42\u0022,                \u0022_STATISTICS_TAGS\u0022: \u0022BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\u0022            }        },        {            \u0022index\u0022: 4,            \u0022codec_name\u0022: \u0022dvd_subtitle\u0022,            \u0022codec_long_name\u0022: \u0022DVD subtitles\u0022,            \u0022codec_type\u0022: \u0022subtitle\u0022,            \u0022codec_tag_string\u0022: \u0022[0][0][0][0]\u0022,            \u0022codec_tag\u0022: \u00220x0000\u0022,            \u0022width\u0022: 1920,            \u0022height\u0022: 1080,            \u0022r_frame_rate\u0022: \u00220/0\u0022,            \u0022avg_frame_rate\u0022: \u00220/0\u0022,            \u0022time_base\u0022: \u00221/1000\u0022,            \u0022start_pts\u0022: 0,            \u0022start_time\u0022: \u00220:00:00.000000\u0022,            \u0022duration_ts\u0022: 8046622,            \u0022duration\u0022: \u00222:14:06.622000\u0022,            \u0022extradata_size\u0022: 344,            \u0022disposition\u0022: {                \u0022default\u0022: 0,                \u0022dub\u0022: 0,                \u0022original\u0022: 0,                \u0022comment\u0022: 0,                \u0022lyrics\u0022: 0,                \u0022karaoke\u0022: 0,                \u0022forced\u0022: 0,                \u0022hearing_impaired\u0022: 0,                \u0022visual_impaired\u0022: 0,                \u0022clean_effects\u0022: 0,                \u0022attached_pic\u0022: 0,                \u0022timed_thumbnails\u0022: 0,                \u0022captions\u0022: 0,                \u0022descriptions\u0022: 0,                \u0022metadata\u0022: 0,                \u0022dependent\u0022: 0,                \u0022still_image\u0022: 0            },            \u0022tags\u0022: {                \u0022language\u0022: \u0022eng\u0022,                \u0022BPS\u0022: \u00229412\u0022,                \u0022DURATION\u0022: \u002202:09:35.887000000\u0022,                \u0022NUMBER_OF_FRAMES\u0022: \u00221587\u0022,                \u0022NUMBER_OF_BYTES\u0022: \u00229149201\u0022,                \u0022_STATISTICS_WRITING_APP\u0022: \u0022mkvmerge v76.0 (\u0027Celebration\u0027) 64-bit\u0022,                \u0022_STATISTICS_WRITING_DATE_UTC\u0022: \u00222023-05-08 11:48:42\u0022,                \u0022_STATISTICS_TAGS\u0022: \u0022BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\u0022            }        },        {            \u0022index\u0022: 5,            \u0022codec_name\u0022: \u0022dvd_subtitle\u0022,            \u0022codec_long_name\u0022: \u0022DVD subtitles\u0022,            \u0022codec_type\u0022: \u0022subtitle\u0022,            \u0022codec_tag_string\u0022: \u0022[0][0][0][0]\u0022,            \u0022codec_tag\u0022: \u00220x0000\u0022,            \u0022width\u0022: 1920,            \u0022height\u0022: 1080,            \u0022r_frame_rate\u0022: \u00220/0\u0022,            \u0022avg_frame_rate\u0022: \u00220/0\u0022,            \u0022time_base\u0022: \u00221/1000\u0022,            \u0022start_pts\u0022: 0,            \u0022start_time\u0022: \u00220:00:00.000000\u0022,            \u0022duration_ts\u0022: 8046622,            \u0022duration\u0022: \u00222:14:06.622000\u0022,            \u0022extradata_size\u0022: 344,            \u0022disposition\u0022: {                \u0022default\u0022: 0,                \u0022dub\u0022: 0,                \u0022original\u0022: 0,                \u0022comment\u0022: 0,                \u0022lyrics\u0022: 0,                \u0022karaoke\u0022: 0,                \u0022forced\u0022: 0,                \u0022hearing_impaired\u0022: 0,                \u0022visual_impaired\u0022: 0,                \u0022clean_effects\u0022: 0,                \u0022attached_pic\u0022: 0,                \u0022timed_thumbnails\u0022: 0,                \u0022captions\u0022: 0,                \u0022descriptions\u0022: 0,                \u0022metadata\u0022: 0,                \u0022dependent\u0022: 0,                \u0022still_image\u0022: 0            },            \u0022tags\u0022: {                \u0022language\u0022: \u0022fre\u0022,                \u0022BPS\u0022: \u00227820\u0022,                \u0022DURATION\u0022: \u002202:07:53.074000000\u0022,                \u0022NUMBER_OF_FRAMES\u0022: \u00221206\u0022,                \u0022NUMBER_OF_BYTES\u0022: \u00227500734\u0022,                \u0022_STATISTICS_WRITING_APP\u0022: \u0022mkvmerge v76.0 (\u0027Celebration\u0027) 64-bit\u0022,                \u0022_STATISTICS_WRITING_DATE_UTC\u0022: \u00222023-05-08 11:48:42\u0022,                \u0022_STATISTICS_TAGS\u0022: \u0022BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\u0022            }        }    ],    \u0022format\u0022: {        \u0022filename\u0022: \u0022/data/Downloads/Movies/Princess Mononoke (1997) (1080p BluRay x265 HEVC 10bit EAC3 5.1 Japanese Garshasp)/Princess Mononoke (1997) (1080p BluRay x265 Garshasp).mkv\u0022,        \u0022nb_streams\u0022: 6,        \u0022nb_programs\u0022: 0,        \u0022format_name\u0022: \u0022matroska,webm\u0022,        \u0022format_long_name\u0022: \u0022Matroska / WebM\u0022,        \u0022start_time\u0022: \u00220:00:00.000000\u0022,        \u0022duration\u0022: \u00222:14:06.622000\u0022,        \u0022size\u0022: \u00226840983924\u0022,        \u0022bit_rate\u0022: \u00226801347\u0022,        \u0022probe_score\u0022: 100,        \u0022tags\u0022: {            \u0022encoder\u0022: \u0022libebml v1.4.4 \u002B libmatroska v1.7.1\u0022,            \u0022creation_time\u0022: \u00222023-05-08T11:48:42.000000Z\u0022        }    }}",
  "schemaRevision": 10,
  "containerFormat": "matroska,webm",
  "videoFormat": "hevc",
  "videoCodecID": "x265",
  "videoProfile": "Main 10",
  "videoBitrate": 0,
  "videoBitDepth": 10,
  "videoMultiViewCount": 1,
  "videoHdrFormat": "none",
  "height": 1040,
  "width": 1920,
  "audioFormat": "eac3",
  "audioCodecID": "[0][0][0][0]",
  "audioBitrate": 768000,
  "runTime": "02:14:06.6220000",
  "audioStreamCount": 2,
  "audioChannels": 6,
  "audioChannelPositions": "5.1(side)",
  "videoFps": 23.976023976023976023976023976,
  "audioLanguages": [
    "jpn",
    "eng"
  ],
  "subtitles": [
    "eng",
    "eng",
    "fre"
  ],
  "scanType": "Progressive"
} - String)
 ---> System.Text.Json.JsonException: ' ' is an invalid escapable character within a JSON string. The string should be correctly escaped. Path: $.rawStreamData | LineNumber: 1 | BytePositionInLine: 6583.
 ---> System.Text.Json.JsonReaderException: ' ' is an invalid escapable character within a JSON string. The string should be correctly escaped. LineNumber: 1 | BytePositionInLine: 6583.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(ReadOnlySpan`1 data, Int32 idx)
   at System.Text.Json.Utf8JsonReader.ConsumeString()
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Dapper.SqlMapper.TypeHandler`1.Dapper.SqlMapper.ITypeHandler.Parse(Type destinationType, Object value) in /_/Dapper/SqlMapper.TypeHandler.cs:line 42
   at Dapper.SqlMapper.TypeHandlerCache`1.Parse(Object value) in /_/Dapper/SqlMapper.TypeHandlerCache.cs:line 23
   at Deserialize1eaaa8b2-b1f9-4f33-b462-240d4ff6fa52(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706
   at Deserialize1eaaa8b2-b1f9-4f33-b462-240d4ff6fa52(IDataReader )
   at Dapper.SqlMapper.<>c__DisplayClass160_0`8.<GenerateMapper>b__1(IDataReader r)
   at Dapper.SqlMapper.MultiMapImpl[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn, IDataReader reader, Identity identity, Boolean finalize)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.MultiMap[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, String sql, Delegate map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType)
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[TFirst,TSecond,TThird,TReturn](IDatabase db, String sql, Func`4 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType)
   at NzbDrone.Core.Datastore.SqlMapperExtensions.QueryJoined[T,T2,T3](IDatabase db, SqlBuilder builder, Func`4 mapper)
   at NzbDrone.Core.Movies.MovieRepository.All()
   at NzbDrone.Core.Movies.MovieService.GetAllMovies()
   at Radarr.Api.V3.Movies.MovieController.<AllMovie>b__10_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Radarr.Api.V3.Movies.MovieController.AllMovie(Nullable`1 tmdbId)
   at lambda_method143(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context)
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context)
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context)
   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context)
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context)
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
SQL: 
==== Begin Query Trace ====

QUERY TEXT:
SELECT "Movies".*, "MovieFiles".*, "MovieMetadata".*
 FROM "Movies"   
LEFT JOIN "MovieFiles" ON ("Movies"."MovieFileId" = "MovieFiles"."Id")
LEFT JOIN "MovieMetadata" ON ("Movies"."MovieMetadataId" = "MovieMetadata"."Id")
    

PARAMETERS:

==== End Query Trace ====



2023-09-11 13:24:31.0|Trace|Http|Res: 285 [GET] /api/v3/movie: 500.InternalServerError (196 ms)
2023-09-11 13:24:31.0|Debug|Api|[GET] /api/v3/movie: 500.InternalServerError (196 ms)```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/radarr/faq#i-am-getting-an-error-database-disk-image-is-malformed   Corruot DB entry

**Comment by paulirish** [comment]
> [wiki.servarr.com/radarr/faq#i-am-getting-an-error-database-disk-image-is-malformed](https://wiki.servarr.com/radarr/faq#i-am-getting-an-error-database-disk-image-is-malformed) Corruot DB entry

This FAQ entry is about a corrupt database. That's not my problem.

The problem is that the `MediaInfo` column in `MovieFiles` table has invalid JSON.

Radarr could gracefully recover from this error instead of falling back to a "Unable to load movies" case.

But ok.

**Comment by bakerboy448** [comment]
the json is invalid, thus the database is corrupt.

Please use [Discord](https://radarr.video/discord) for support/questions.
