### ISSUE TITLE
Can't import existing library. DiskProvider: Unable to get drive mounts

### ISSUE THREAD

**Issue by ryanmilley** [Radarr/Radarr#9176]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I'm getting this error when trying to import my existing Library. Please note I am running Sonarr perfectly using the exact same settings and installation method. Some notes:  
I installed this using the tar.gz method. I did change the user/group in my radarr.service to my local user. I double checked permissions in /opt/radarr etc.  A copy of my file is below. 

[Unit]
Description=Radarr Daemon
After=syslog.target network.target
[Service]
User=ryan
Group=ryan
Type=simple

ExecStart=/opt/Radarr/Radarr -nobrowser
TimeoutStopSec=20
KillMode=process
Restart=on-failure
[Install]
WantedBy=multi-user.target

### Expected Behavior

Movies should import

### Environment

```markdown
- OS: Linux Mint 21.2
- Radarr:     5.0.2.8054 I tried main and nightly, no difference
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox
- Database: Sqlite3
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

2023-09-12 18:41:23.7|Warn|DiskProvider|Unable to get drive mounts: Failed to fetch drive info for mount point: /run/user/1000/doc

[v5.0.2.8054] System.Exception: Failed to fetch drive info for mount point: /run/user/1000/doc
 ---> System.UnauthorizedAccessException: Access to the path is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
   at System.IO.DriveInfo.get_DriveFormat()
   at NzbDrone.Mono.Disk.DiskProvider.<>c.<GetAllMounts>b__16_0(DriveInfo d) in ./Radarr.Mono/Disk/DiskProvider.cs:line 193
   --- End of inner exception stack trace ---
   at NzbDrone.Mono.Disk.DiskProvider.<>c.<GetAllMounts>b__16_0(DriveInfo d) in ./Radarr.Mono/Disk/DiskProvider.cs:line 193
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at NzbDrone.Mono.Disk.DiskProvider.GetAllMounts() in ./Radarr.Mono/Disk/DiskProvider.cs:line 203

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by StevenAFC** [comment]
I also have this issue, although I am using a fresh install on Ubuntu using the ArrInstall.sh script. I also setup using my Ubuntu user and group. Sonarr with same setup is working as expected.

**Comment by ryanmilley** [comment]
> I also have this issue, although I am using a fresh install on Ubuntu using the ArrInstall.sh script. I also setup using my Ubuntu user and group. Sonarr with same setup is working as expected.

Do your movies actually import or no?

**Comment by StevenAFC** [comment]
> > I also have this issue, although I am using a fresh install on Ubuntu using the ArrInstall.sh script. I also setup using my Ubuntu user and group. Sonarr with same setup is working as expected.
> 
> Do your movies actually import or no?

Other than getting the error in the event log my movies import fine.
