### ISSUE TITLE
Issue going from 4.7.5 -> 5.X

### ISSUE THREAD

**Issue by phyzical** [Radarr/Radarr#9240]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Going from v4 to v5 (this db would be around from v2 days incase that matters)

This also happened to me a few weeks ago, i must have pinned to 4.X and forgot to raise a bug report

Also tried removing the db and attempting to restore multiple dbs without success (4.7.5 and 4.7.4) 

it is linuxserver's "latest" image tag which is currently serving [v5.0.3.8127](https://github.com/Radarr/Radarr/releases/tag/v5.0.3.8127)

sqlite lite

I asked in discord and atleast one user confirmed that they could go from 4 -> 5 without issues so im sure it relates to my db in some way shape or form.

### Expected Behavior

should migrate without issue

### Environment

```markdown
- OS: unraid
- Radarr: 4.7.5 -> 5.X
- Docker Install: https://hub.docker.com/layers/linuxserver/radarr/latest/images/sha256-ba539d5ea0c4c0230e28b2ad0c4861d8a1c1c03c4444d6c9f6bca8bab85e063f
- Using Reverse Proxy: yes
- Browser: 
- Database: sqlite
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

```
2023-10-08T15:25:58+08:00	Non-recoverable failure, waiting for user intervention...
2023-10-08T15:25:57+08:00	Press enter to exit...
2023-10-08T15:25:57+08:00	
2023-10-08T15:25:57+08:00	
2023-10-08T15:25:57+08:00	   at NzbDrone.Console.ConsoleApp.Main(String[] args) in ./Radarr.Console/ConsoleApp.cs:line 43
2023-10-08T15:25:57+08:00	   at NzbDrone.Host.Bootstrap.Start(String[] args, Action`1 trayCallback) in ./Radarr.Host/Bootstrap.cs:line 78
2023-10-08T15:25:57+08:00	   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
2023-10-08T15:25:57+08:00	   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2023-10-08T15:25:57+08:00	   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2023-10-08T15:25:57+08:00	   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
2023-10-08T15:25:57+08:00	   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
2023-10-08T15:25:57+08:00	   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
2023-10-08T15:25:57+08:00	   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
2023-10-08T15:25:57+08:00	   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
2023-10-08T15:25:57+08:00	   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
2023-10-08T15:25:57+08:00	   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2023-10-08T15:25:57+08:00	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2023-10-08T15:25:57+08:00	   at NzbDrone.Host.Startup.Configure(IApplicationBuilder app, IStartupContext startupContext, Lazy`1 mainDatabaseFactory, Lazy`1 logDatabaseFactory, DatabaseTarget dbTarget, ISingleInstancePolicy singleInstancePolicy, InitializeLogger initializeLogger, ReconfigureLogging reconfigureLogging, IAppFolderFactory appFolderFactory, IProvidePidFile pidFileProvider, IConfigFileProvider configFileProvider, IRuntimeInfo runtimeInfo, IFirewallAdapter firewallAdapter, IEventAggregator eventAggregator, RadarrErrorPipeline errorHandler) in ./Radarr.Host/Startup.cs:line 236
2023-10-08T15:25:57+08:00	   at System.Lazy`1.get_Value()
2023-10-08T15:25:57+08:00	   at System.Lazy`1.CreateValue()
2023-10-08T15:25:57+08:00	   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2023-10-08T15:25:57+08:00	   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2023-10-08T15:25:57+08:00	   at DryIoc.Interpreter.<>c__DisplayClass9_0`1.<ConvertFunc>b__0() in /_/src/DryIoc/Container.cs:line 3460
2023-10-08T15:25:57+08:00	   at DryIoc.Interpreter.<>c__DisplayClass5_0.<TryInterpretNestedLambda>b__0() in /_/src/DryIoc/Container.cs:line 3349
2023-10-08T15:25:57+08:00	   at DryIoc.Interpreter.TryInterpretNestedLambdaBodyAndUnwrapException(IResolverContext r, Expression bodyExpr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs) in /_/src/DryIoc/Container.cs:line 3450
2023-10-08T15:25:57+08:00	   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3167
2023-10-08T15:25:57+08:00	   at DryIoc.Interpreter.TryInterpretMethodCall(IResolverContext r, MethodCallExpression callExpr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3640
2023-10-08T15:25:57+08:00	   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 466
2023-10-08T15:25:57+08:00	   at DryIoc.Container.ResolveAndCacheKeyed(Int32 serviceTypeHash, Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Object scopeName, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 538
2023-10-08T15:25:57+08:00	   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11029
2023-10-08T15:25:57+08:00	   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /_/src/DryIoc/Container.cs:line 11110
2023-10-08T15:25:57+08:00	   at DryIoc.Interpreter.TryInterpretSingletonAndUnwrapContainerException(IResolverContext r, Expression expr, ImMapEntry`1 itemRef, Object& result) in /_/src/DryIoc/Container.cs:line 3084
2023-10-08T15:25:57+08:00	   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3155
2023-10-08T15:25:57+08:00	   at DryIoc.Interpreter.TryInterpretMethodCall(IResolverContext r, MethodCallExpression callExpr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3504
2023-10-08T15:25:57+08:00	   at DryIoc.Interpreter.TryInterpretFuncInvoke(IResolverContext r, MethodCallExpression e, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3706
2023-10-08T15:25:57+08:00	   at DryIoc.Registrator.ToFuncWithObjParams[D1,TService](Func`2 f, Object d1) in /_/src/DryIoc/Container.cs:line 8046
2023-10-08T15:25:57+08:00	   at NzbDrone.Core.Datastore.Extensions.CompositionExtensions.<>c.<AddDatabase>b__0_0(IDbFactory f) in ./Radarr.Core/Datastore/Extensions/CompositionExtensions.cs:line 10
2023-10-08T15:25:57+08:00	   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationType migrationType) in ./Radarr.Core/Datastore/DbFactory.cs:line 58
2023-10-08T15:25:57+08:00	   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationContext migrationContext) in ./Radarr.Core/Datastore/DbFactory.cs:line 70
2023-10-08T15:25:57+08:00	   at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in ./Radarr.Core/Datastore/DbFactory.cs:line 161
2023-10-08T15:25:57+08:00	   --- End of inner exception stack trace ---
2023-10-08T15:25:57+08:00	   at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in ./Radarr.Core/Datastore/DbFactory.cs:line 115
2023-10-08T15:25:57+08:00	   at NzbDrone.Core.Datastore.Migration.Framework.MigrationController.Migrate(String connectionString, MigrationContext migrationContext) in ./Radarr.Core/Datastore/Migration/Framework/MigrationController.cs:line 79
2023-10-08T15:25:57+08:00	   at FluentMigrator.Runner.MigrationRunner.MigrateUp()
2023-10-08T15:25:57+08:00	   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement)
2023-10-08T15:25:57+08:00	   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement)
2023-10-08T15:25:57+08:00	   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction)
2023-10-08T15:25:57+08:00	   at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions)
2023-10-08T15:25:57+08:00	   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
2023-10-08T15:25:57+08:00	   at FluentMigrator.Runner.StopWatch.Time(Action action)
2023-10-08T15:25:57+08:00	   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass80_0.<ExecuteExpressions>b__1()
2023-10-08T15:25:57+08:00	   at FluentMigrator.Expressions.ExecuteSqlStatementExpression.ExecuteWith(IMigrationProcessor processor)
2023-10-08T15:25:57+08:00	   at FluentMigrator.Runner.Processors.ProcessorBase.Execute(String sql)
2023-10-08T15:25:57+08:00	   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Execute(String template, Object[] args)
2023-10-08T15:25:57+08:00	   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(String sql)
2023-10-08T15:25:57+08:00	   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
2023-10-08T15:25:57+08:00	   --- End of inner exception stack trace ---
2023-10-08T15:25:57+08:00	   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
2023-10-08T15:25:57+08:00	   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
2023-10-08T15:25:57+08:00	   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
2023-10-08T15:25:57+08:00	   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
2023-10-08T15:25:57+08:00	   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
2023-10-08T15:25:57+08:00	   at System.Data.SQLite.SQLiteDataReader.NextResult()
2023-10-08T15:25:57+08:00	   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
2023-10-08T15:25:57+08:00	database disk image is malformed
2023-10-08T15:25:57+08:00	 ---> code = Corrupt (11), message = System.Data.SQLite.SQLiteException (0x87AF054E): database disk image is malformed
2023-10-08T15:25:57+08:00	"UPDATE "Credits" SET "Images" = REPLACE("Images", '"url"', '"remoteUrl"')"
2023-10-08T15:25:57+08:00	While Processing:
2023-10-08T15:25:57+08:00	database disk image is malformed
2023-10-08T15:25:57+08:00	 ---> System.Exception: database disk image is malformed
2023-10-08T15:25:57+08:00	[v5.0.3.8127] NzbDrone.Common.Exceptions.RadarrStartupException: Radarr failed to start: Error creating main database
2023-10-08T15:25:57+08:00	
2023-10-08T15:25:57+08:00	[Fatal] ConsoleApp: EPIC FAIL! 
2023-10-08T15:25:57+08:00	Non-recoverable failure, waiting for user intervention...
```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by phyzical** [comment]
One user indicated that even though it wasnt affecting my install before, i could just have had this corruption for quite a while. 

i will try these commands and report back https://wiki.servarr.com/radarr/faq#i-am-getting-an-error-database-disk-image-is-malformed

**Comment by KaHooli** [comment]
I had the same issue.
I had tried restoring the most recent backup, no change.
I then followed the instructions on the *Arr Wiki [Recovering a Corrupt DB](https://wiki.servarr.com/useful-tools#recovering-a-corrupt-db), by running the following commands under the directory where the radarr.db file is located...
```
sqlite3 ./radarr.db .recover | sqlite3 ./recovered.db
rm radarr.db
mv recovered.db radarr.db
```
I then started radarr and output the logs...
```
docker start radarr; docker logs -tf radarr
```
so I could monitor the logs as Radarr started, and all was fine 👍

**Comment by phyzical** [comment]
@KaHooli thanks for the confirmation. i just had a chance to get back to this and can confirm that the simple repair worked perfectly.
