### ISSUE TITLE
Radarr thinks it's running in docker when it isn't, and disables updates

### ISSUE THREAD

**Issue by xdpirate** [Radarr/Radarr#9247]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Radarr has stopped letting me update it from the web UI:

![image](https://github.com/Radarr/Radarr/assets/1757462/490b7dde-5586-4275-a159-3f6acaeaa4f4)

...yet the update mechanism is set to builtin:

![image](https://github.com/Radarr/Radarr/assets/1757462/d351a919-ccb9-445b-b68c-8c7c763d22b2)

Looking at the "About" section reveals that Radarr thinks it's running in Docker:

![image](https://github.com/Radarr/Radarr/assets/1757462/97ee8df3-b3d6-4104-8c2c-9981cb7e67dd)

...yet Radarr is running as a systemd service:

```
$ sudo docker ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED         STATUS                    PORTS                                       NAMES
60e7d35ffb32   fallenbagel/jellyseerr:latest   "/sbin/tini -- yarn …"   3 months ago    Up 11 minutes             0.0.0.0:5055->5055/tcp, :::5055->5055/tcp   jellyseerr
7d9c47e68aed   lissy93/dashy:latest            "docker-entrypoint.s…"   4 months ago    Up 11 minutes (healthy)   0.0.0.0:81->80/tcp, :::81->80/tcp           dashy
0c6696fa00b8   jellyfin/jellyfin:latest        "/jellyfin/jellyfin"     5 months ago    Up 11 minutes (healthy)                                               jellyfin
70ab9d8294c2   a21638c50ef1                    "/init"                  17 months ago   Up 11 minutes             0.0.0.0:7998->8080/tcp, :::7998->8080/tcp   scrutiny

$ sudo service radarr status
● radarr.service - Radarr Daemon
     Loaded: loaded (/etc/systemd/system/radarr.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-10-10 03:57:20 CEST; 11min ago
   Main PID: 528356 (Radarr)
      Tasks: 22 (limit: 9282)
     Memory: 275.4M
        CPU: 13.378s
     CGroup: /system.slice/radarr.service
             └─528356 /opt/Radarr/Radarr -nobrowser -data=/var/lib/radarr/

Oct 10 04:06:34 BanaNAS Radarr[528356]:    at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
Oct 10 04:06:34 BanaNAS Radarr[528356]:    at System.IO.DriveInfo.get_DriveFormat()
Oct 10 04:06:34 BanaNAS Radarr[528356]:    at NzbDrone.Mono.Disk.DiskProvider.<>c.<GetAllMounts>b__16_0(DriveInfo d) in ./Radarr.Mono/Disk/DiskProvider.>
Oct 10 04:06:34 BanaNAS Radarr[528356]:    --- End of inner exception stack trace ---
Oct 10 04:06:34 BanaNAS Radarr[528356]:    at NzbDrone.Mono.Disk.DiskProvider.<>c.<GetAllMounts>b__16_0(DriveInfo d) in ./Radarr.Mono/Disk/DiskProvider.>
Oct 10 04:06:34 BanaNAS Radarr[528356]:    at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
Oct 10 04:06:34 BanaNAS Radarr[528356]:    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
Oct 10 04:06:34 BanaNAS Radarr[528356]:    at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
Oct 10 04:06:34 BanaNAS Radarr[528356]:    at NzbDrone.Mono.Disk.DiskProvider.GetAllMounts() in ./Radarr.Mono/Disk/DiskProvider.cs:line 203
Oct 10 04:07:53 BanaNAS Radarr[528356]: [Info] ImportListSyncService: No auto enabled lists, skipping sync and cleaning
```

### Expected Behavior

Expected to be able to continue updating via the web UI, like I've done for about two years now. Installing the current version seems to have broken it.

### Environment

```markdown
- OS: Ubuntu Server 22.04 LTS
- Radarr: 4.7.5.7809
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox 118.0.1 (64-bit)
- Database: Sqlite 3.37.2
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/12852103/radarr.trace.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by Qstick** [comment]
Update Radarr

**Comment by xdpirate** [comment]
Thanks for the swift resolution. I used the "easy script" when installing the first time so I had no clue how to update manually. Appropriating the install guide helped, I'll leave this here if anyone comes across this in the future:

Stop Radarr service
```
sudo service radarr stop
```

Backup old directory

```
cd /opt
tar czf Radarr-old.tar.gz Radarr/
```

Download latest release
```
wget --content-disposition 'http://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64'
```

Unpack new release over old one
```
tar xvf Radarr.master.*.linux-core-x64.tar.gz
```

Start Radarr service
```
sudo service radarr start
```

Reload the web UI. Finally, remove the two archives
```
rm Radarr*.tar.gz
```
