### ISSUE TITLE
Failed to load Radarr

### ISSUE THREAD

**Issue by G4Zz0L1** [Radarr/Radarr#9286]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

On opening Radarr on the browser, the following message appears.

![image](https://github.com/Radarr/Radarr/assets/13220636/f972d965-f020-4049-974e-7e0bfdd3b625)

From what I understand an API is failing to load with the following message.

![image](https://github.com/Radarr/Radarr/assets/13220636/48fd726b-3ceb-4d1e-ad86-bf7154be0a20)

```
{
    "message": "Object reference not set to an instance of an object.",
    "description": "System.NullReferenceException: Object reference not set to an instance of an object.\n   at Radarr.Api.V3.Collections.CollectionController.MapToResource(List\u00601 collections)\u002BMoveNext() in ./Radarr.Api.V3/Collections/CollectionController.cs:line 162\n   at System.Collections.Generic.List\u00601..ctor(IEnumerable\u00601 collection)\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable\u00601 source)\n   at Radarr.Api.V3.Collections.CollectionController.GetCollections(Nullable\u00601 tmdbId) in ./Radarr.Api.V3/Collections/CollectionController.cs:line 80\n   at lambda_method138(Closure , Object , Object[] )\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/BufferingMiddleware.cs:line 28\n   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/IfModifiedMiddleware.cs:line 41\n   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33\n   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/StartingUpMiddleware.cs:line 38\n   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/UrlBaseMiddleware.cs:line 27\n   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/VersionMiddleware.cs:line 29\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"
}
```

### Expected Behavior

I expect it to load as usual.

### Environment

```markdown
- OS: Arch Linux
- Radarr: 5.0.3.8127
- Docker Install: no
- Using Reverse Proxy: yes
- Browser: Chrome 118.0.5993.70
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

```
2023-10-14 18:45:57.000000 radarr[1909]: [Fatal] RadarrErrorPipeline: Request Failed. GET /api/v3/collection
2023-10-14 18:45:57.000000 radarr[1909]: [v5.0.3.8127] System.NullReferenceException: Object reference not set to an instance of an object.
2023-10-14 18:45:57.000000 radarr[1909]:    at Radarr.Api.V3.Collections.CollectionController.MapToResource(List`1 collections)+MoveNext() in ./Radarr.Api.V3/Collections/CollectionController.cs:line 162
2023-10-14 18:45:57.000000 radarr[1909]:    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
2023-10-14 18:45:57.000000 radarr[1909]:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2023-10-14 18:45:57.000000 radarr[1909]:    at Radarr.Api.V3.Collections.CollectionController.GetCollections(Nullable`1 tmdbId) in ./Radarr.Api.V3/Collections/CollectionController.cs:line 80
2023-10-14 18:45:57.000000 radarr[1909]:    at lambda_method138(Closure , Object , Object[] )
2023-10-14 18:45:57.000000 radarr[1909]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2023-10-14 18:45:57.000000 radarr[1909]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
2023-10-14 18:45:57.000000 radarr[1909]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2023-10-14 18:45:57.000000 radarr[1909]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
2023-10-14 18:45:57.000000 radarr[1909]: --- End of stack trace from previous location ---
2023-10-14 18:45:57.000000 radarr[1909]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2023-10-14 18:45:57.000000 radarr[1909]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2023-10-14 18:45:57.000000 radarr[1909]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
2023-10-14 18:45:57.000000 radarr[1909]: --- End of stack trace from previous location ---
2023-10-14 18:45:57.000000 radarr[1909]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-10-14 18:45:57.000000 radarr[1909]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2023-10-14 18:45:57.000000 radarr[1909]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2023-10-14 18:45:57.000000 radarr[1909]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2023-10-14 18:45:57.000000 radarr[1909]:    at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/BufferingMiddleware.cs:line 28
2023-10-14 18:45:57.000000 radarr[1909]:    at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
2023-10-14 18:45:57.000000 radarr[1909]:    at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
2023-10-14 18:45:57.000000 radarr[1909]:    at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/StartingUpMiddleware.cs:line 38
2023-10-14 18:45:57.000000 radarr[1909]:    at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
2023-10-14 18:45:57.000000 radarr[1909]:    at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/VersionMiddleware.cs:line 29
2023-10-14 18:45:57.000000 radarr[1909]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
2023-10-14 18:45:57.000000 radarr[1909]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2023-10-14 18:45:57.000000 radarr[1909]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2023-10-14 18:45:57.000000 radarr[1909]:    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
pursuant to

> Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

Closing due to invalid report; can reopen if it's an issue and if/when proper logs are provided and the wiki is followed rather than merely checking the box

**Comment by G4Zz0L1** [comment]
Sorry, I thought the logs put above were enough.
If it's already fixed with the commit https://github.com/Radarr/Radarr/commit/9b3640407180871439774c52835d7f2d4c578b77 it will be ok when it's published, so I don't think I'll have to reopen this. right?

**Comment by jjbrunton** [comment]
Is there any way to force an update if using Linuxserver docker image?

**Comment by bakerboy448** [comment]
Please use [Discord](https://radarr.video/discord) for support/questions.
