### ISSUE TITLE
Error 500 on blocklist, field missing in table

### ISSUE THREAD

**Issue by reloxx13** [Radarr/Radarr#9314]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

If i open Blocklist, the page does not load and browser console shows error 500

```
09:37:02.381 XHRGET
http://192.168.178.12:7873/api/v3/blocklist?page=1&pageSize=20&sortDirection=ascending&sortKey=movies.sortTitle
[HTTP/1.1 500 Internal Server Error 10ms]

 
1

{

2

  "message": "SQL logic error\r\nno such column: Movies.SortTitle",

3

  "description": "code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error\r\nno such column: Movies.SortTitle\r\n   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String\u0026 strRemain)\r\n   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()\r\n   at System.Data.SQLite.SQLiteDataReader.NextResult()\r\n   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)\r\n   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)\r\n   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1142\r\n   at Dapper.SqlMapper.MultiMapImpl[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn, DbDataReader reader, Identity identity, Boolean finalize)\u002BMoveNext() in /_/Dapper/SqlMapper.cs:line 1537\r\n   at System.Collections.Generic.List\u00601..ctor(IEnumerable\u00601 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable\u00601 source)\r\n   at Dapper.SqlMapper.MultiMap[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, String sql, Delegate map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable\u00601 commandTimeout, Nullable\u00601 commandType) in /_/Dapper/SqlMapper.cs:line 1518\r\n   at Dapper.SqlMapper.Query[TFirst,TSecond,TReturn](IDbConnection cnn, String sql, Func\u00603 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable\u00601 commandTimeout, Nullable\u00601 commandType) in /_/Dapper/SqlMapper.cs:line 1373\r\n   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[TFirst,TSecond,TReturn](IDatabase db, String sql, Func\u00603 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable\u00601 commandTimeout, Nullable\u00601 commandType) in ./Radarr.Core/Datastore/Extensions/SqlMapperExtensions.cs:line 50\r\n   at NzbDrone.Core.Datastore.SqlMapperExtensions.QueryJoined[T,T2](IDatabase db, SqlBuilder builder, Func\u00603 mapper) in ./Radarr.Core/Datastore/Extensions/SqlMapperExtensions.cs:line 156\r\n   at NzbDrone.Core.Blocklisting.BlocklistRepository.PagedQuery(SqlBuilder sql) in ./Radarr.Core/Blocklisting/BlocklistRepository.cs:line 55\r\n   at NzbDrone.Core.Datastore.BasicRepository\u00601.GetPagedRecords(SqlBuilder builder, PagingSpec\u00601 pagingSpec, Func\u00602 queryFunc) in ./Radarr.Core/Datastore/BasicRepository.cs:line 434\r\n   at NzbDrone.Core.Datastore.BasicRepository\u00601.GetPaged(PagingSpec\u00601 pagingSpec) in ./Radarr.Core/Datastore/BasicRepository.cs:line 404\r\n   at NzbDrone.Core.Blocklisting.BlocklistService.Paged(PagingSpec\u00601 pagingSpec) in ./Radarr.Core/Blocklisting/BlocklistService.cs:line 68\r\n   at Radarr.Http.Extensions.RequestExtensions.ApplyToPage[TResource,TModel](PagingSpec\u00601 pagingSpec, Func\u00602 function, Converter\u00602 mapper) in ./Radarr.Http/Extensions/RequestExtensions.cs:line 56\r\n   at Radarr.Api.V3.Blocklist.BlocklistController.GetBlocklist(PagingRequestResource paging) in ./Radarr.Api.V3/Blocklist/BlocklistController.cs:line 33\r\n   at lambda_method198(Closure , Object , Object[] )\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/BufferingMiddleware.cs:line 28\r\n   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/IfModifiedMiddleware.cs:line 41\r\n   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33\r\n   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/StartingUpMiddleware.cs:line 38\r\n   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/UrlBaseMiddleware.cs:line 27\r\n   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/VersionMiddleware.cs:line 29\r\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)\r\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"

4

}
```

### Expected Behavior

Showing blocklist

### Environment

```markdown
- OS: win10
- Radarr: 5.1.1.8195
- Docker Install: no
- Using Reverse Proxy: no 
- Browser: all
- Database: DB Migration
    233
Datenbank
    Sqlite 3.36.0
```

### What branch are you running?

Nightly

### Trace Logs? **Not Optional**

```
2023-10-22 09:36:16.4|Error|RadarrErrorPipeline|[GET /api/v3/blocklist]

[v5.1.1.8195] code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
no such column: Movies.SortTitle
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1142
   at Dapper.SqlMapper.MultiMapImpl[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn, DbDataReader reader, Identity identity, Boolean finalize)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1537
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.MultiMap[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, String sql, Delegate map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1518
   at Dapper.SqlMapper.Query[TFirst,TSecond,TReturn](IDbConnection cnn, String sql, Func`3 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1373
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[TFirst,TSecond,TReturn](IDatabase db, String sql, Func`3 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in ./Radarr.Core/Datastore/Extensions/SqlMapperExtensions.cs:line 50
   at NzbDrone.Core.Datastore.SqlMapperExtensions.QueryJoined[T,T2](IDatabase db, SqlBuilder builder, Func`3 mapper) in ./Radarr.Core/Datastore/Extensions/SqlMapperExtensions.cs:line 156
   at NzbDrone.Core.Blocklisting.BlocklistRepository.PagedQuery(SqlBuilder sql) in ./Radarr.Core/Blocklisting/BlocklistRepository.cs:line 55
   at NzbDrone.Core.Datastore.BasicRepository`1.GetPagedRecords(SqlBuilder builder, PagingSpec`1 pagingSpec, Func`2 queryFunc) in ./Radarr.Core/Datastore/BasicRepository.cs:line 434
   at NzbDrone.Core.Datastore.BasicRepository`1.GetPaged(PagingSpec`1 pagingSpec) in ./Radarr.Core/Datastore/BasicRepository.cs:line 404
   at NzbDrone.Core.Blocklisting.BlocklistService.Paged(PagingSpec`1 pagingSpec) in ./Radarr.Core/Blocklisting/BlocklistService.cs:line 68
   at Radarr.Http.Extensions.RequestExtensions.ApplyToPage[TResource,TModel](PagingSpec`1 pagingSpec, Func`2 function, Converter`2 mapper) in ./Radarr.Http/Extensions/RequestExtensions.cs:line 56
   at Radarr.Api.V3.Blocklist.BlocklistController.GetBlocklist(PagingRequestResource paging) in ./Radarr.Api.V3/Blocklist/BlocklistController.cs:line 33
   at lambda_method198(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
SQL: 
==== Begin Query Trace ====

QUERY TEXT:
SELECT "Blocklist".*, "Movies".*
 FROM "Blocklist" 
JOIN "Movies" ON ("Blocklist"."MovieId" = "Movies"."Id")
  
LEFT JOIN "MovieMetadata" ON ("Movies"."MovieMetadataId" = "MovieMetadata"."Id")
    ORDER BY "Movies"."SortTitle" ASC LIMIT 20 OFFSET 0


PARAMETERS:

==== End Query Trace ====
```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by reloxx13** [comment]
Happened on nightly i guess :p <3

**Comment by reloxx13** [comment]
ahh okay, i didnt see the other issue https://github.com/Radarr/Radarr/issues/9234 cause i searched for blocklist. i resetted local storage and its working fine now, thank you.
