### ISSUE TITLE
New downloads stuck with a queue entry with "Failed to import movie, Destination already exists."

### ISSUE THREAD

**Issue by avillev** [Radarr/Radarr#9358]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When adding new movies, some of them will end up with an orange icon in the Activity / queue tab with this message: "Failed to import movie, Destination already exists."

 - The movie was well downloaded.
 - The movie was properly renamed and moved to the target folder.
 - There was no conflict with any other download and the folder was empty before Radarr created it itself for this download.
 - This entry remains in the queue with that message... Everything else is ok.

### Expected Behavior

THe movie is download, renamed, moved and has no error entry in the Queue tab.

### Steps To Reproduce

1. In the environement described downthere
2. WIth Radarr's image linked to various volumes including a source (torrent download folder) and a destination (Root Folders)
3. Custom formats, transmission and the HD - 720p/1080p profile is used
4. Add any movie
5. There is a chance of occurance

### Environment

```markdown
- OS: Synology DSM 7.2.1-69057 Update 1
- Radarr: Radarr 5.0.3.8127
- Docker Install: Yes, Docker version 20.10.23, build 876964a
- Using Reverse Proxy: No
- Browser: Version 118.0.5993.118 (Official Build) (64-bit)
- Database: Whatever is in 5.0.3.8127-ls192 by linuxserver.io
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

2023-10-31 21:51:08.8|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-10-31 21:51:09.5|Debug|Api|[GET] /api/v3/queue/details?all=true: 200.OK (690 ms)
2023-10-31 21:51:10.8|Debug|DownloadedMovieImportService|Processing path: /downloads/video/radarr/Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT
2023-10-31 21:51:10.8|Debug|Parser|Parsing string 'Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT'
2023-10-31 21:51:10.8|Debug|Parser|Movie Parsed. Couleurs de l. incendie - 2022 
2023-10-31 21:51:10.8|Debug|Parser|Release Group parsed: ROMKENT
2023-10-31 21:51:10.8|Debug|Parser|Languages parsed: Unknown
2023-10-31 21:51:10.8|Debug|QualityParser|Trying to parse quality for 'Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT'
2023-10-31 21:51:10.8|Debug|Parser|Quality parsed: Bluray-1080p v1
2023-10-31 21:51:10.8|Debug|Parser|Edition parsed: 
2023-10-31 21:51:10.8|Debug|DownloadedMovieImportService|Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT folder quality: Bluray-1080p v1
2023-10-31 21:51:10.8|Debug|DiskScanService|Scanning '/downloads/video/radarr/Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT' for video files
2023-10-31 21:51:10.8|Debug|DiskScanService|1 video files were found in /downloads/video/radarr/Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT
2023-10-31 21:51:10.9|Debug|ImportDecisionMaker|Analyzing 1/1 files.
2023-10-31 21:51:10.9|Debug|Parser|Parsing string 'Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT'
2023-10-31 21:51:10.9|Debug|Parser|Movie Parsed. Couleurs de l. incendie - 2022 
2023-10-31 21:51:10.9|Debug|Parser|Release Group parsed: ROMKENT
2023-10-31 21:51:10.9|Debug|Parser|Languages parsed: Unknown
2023-10-31 21:51:10.9|Debug|QualityParser|Trying to parse quality for 'Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT'
2023-10-31 21:51:10.9|Debug|Parser|Quality parsed: Bluray-1080p v1
2023-10-31 21:51:10.9|Debug|Parser|Edition parsed: 
2023-10-31 21:51:10.9|Debug|VideoFileInfoReader|Getting media info from /downloads/video/radarr/Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT/Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT.mkv
2023-10-31 21:51:11.1|Debug|DetectSample|Runtime of 8040.736 is more than 600 seconds, Not Sample
2023-10-31 21:51:11.1|Debug|Parser|Parsing string 'Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT.mkv'
2023-10-31 21:51:11.1|Debug|Parser|Movie Parsed. Couleurs de l. incendie - 2022 
2023-10-31 21:51:11.1|Debug|Parser|Release Group parsed: ROMKENT
2023-10-31 21:51:11.1|Debug|Parser|Languages parsed: Unknown
2023-10-31 21:51:11.1|Debug|QualityParser|Trying to parse quality for 'Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT.mkv'
2023-10-31 21:51:11.1|Debug|Parser|Quality parsed: Bluray-1080p v1
2023-10-31 21:51:11.1|Debug|Parser|Edition parsed: 
2023-10-31 21:51:11.1|Debug|VideoFileInfoReader|Getting media info from /downloads/video/radarr/Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT/Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT.mkv
2023-10-31 21:51:11.1|Debug|AggregateLanguage|Selected languages: French
2023-10-31 21:51:11.1|Debug|QualityParser|Trying to parse quality for 'Couleurs de l incendie 2022 VOF 1080p BluRay mHD x264 AC3-ROMKENT'
2023-10-31 21:51:11.1|Debug|AggregateQuality|Using quality: Bluray-1080p v1
2023-10-31 21:51:11.1|Debug|AlreadyImportedSpecification|Skipping already imported check for movie without file
2023-10-31 21:51:11.1|Debug|VideoFileInfoReader|Getting media info from /downloads/video/radarr/Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT/Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT.mkv
2023-10-31 21:51:11.1|Debug|DetectSample|Runtime of 8040.736 is more than 600 seconds, Not Sample
2023-10-31 21:51:11.1|Debug|ImportDecisionMaker|File accepted
2023-10-31 21:51:11.1|Debug|ImportApprovedMovie|Decisions: 1
2023-10-31 21:51:11.5|Debug|MovieFileMovingService|Copying movie file: /downloads/video/radarr/Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT/Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT.mkv to /videos/movies/Couleurs de l'incendie (2022)/Couleurs de l'incendie (2022) Bluray-1080p.mkv
2023-10-31 21:51:11.5|Debug|DiskTransferService|Copy [/downloads/video/radarr/Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT/Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT.mkv] > [/videos/movies/Couleurs de l'incendie (2022)/Couleurs de l'incendie (2022) Bluray-1080p.mkv]
2023-10-31 21:51:11.5|Warn|ImportApprovedMovie|Couldn't import movie /downloads/video/radarr/Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT/Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT.mkv

[v5.0.3.8127] NzbDrone.Common.Disk.DestinationAlreadyExistsException: Destination /videos/movies/Couleurs de l'incendie (2022)/Couleurs de l'incendie (2022) Bluray-1080p.mkv already exists.
   at NzbDrone.Common.Disk.DiskTransferService.ClearTargetPath(String sourcePath, String targetPath, Boolean overwrite) in ./Radarr.Common/Disk/DiskTransferService.cs:line 403
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in ./Radarr.Common/Disk/DiskTransferService.cs:line 296
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode, LocalMovie localMovie) in ./Radarr.Core/MediaFiles/MovieFileMovingService.cs:line 154
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in ./Radarr.Core/MediaFiles/UpgradeMediaFileService.cs:line 41
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in ./Radarr.Core/MediaFiles/MovieImport/ImportApprovedMovie.cs:line 129

2023-10-31 21:51:11.6|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-10-31 21:51:11.6|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
2023-10-31 21:51:11.6|Debug|CompletedDownloadService|Not all movies have been imported for Couleurs.de.l.incendie.2022.VOF.1080p.BluRay.mHD.x264.AC3-ROMKENT
2023-10-31 21:51:11.7|Debug|DownloadedMovieImportService|Processing path: /downloads/video/radarr/Les.Miens.2022.FRENCH.1080p.BluRay.REMUX.AVC.DTS-HDMA.5.1-SMV.mkv
2023-10-31 21:51:11.7|Debug|ImportDecisionMaker|Analyzing 1/1 files.
2023-10-31 21:51:11.7|Debug|Parser|Parsing string 'Les.Miens.2022.FRENCH.1080p.BluRay.REMUX.AVC.DTS-HDMA.5.1-SMV.mkv'
2023-10-31 21:51:11.7|Debug|Parser|Movie Parsed. Les Miens - 2022 
2023-10-31 21:51:11.7|Debug|Parser|Release Group parsed: SMV
2023-10-31 21:51:11.7|Debug|Parser|Languages parsed: French
2023-10-31 21:51:11.7|Debug|QualityParser|Trying to parse quality for 'Les.Miens.2022.FRENCH.1080p.BluRay.REMUX.AVC.DTS-HDMA.5.1-SMV.mkv'
2023-10-31 21:51:11.7|Debug|Parser|Quality parsed: Remux-1080p v1
2023-10-31 21:51:11.7|Debug|Parser|Edition parsed: 
2023-10-31 21:51:11.7|Debug|VideoFileInfoReader|Getting media info from /downloads/video/radarr/Les.Miens.2022.FRENCH.1080p.BluRay.REMUX.AVC.DTS-HDMA.5.1-SMV.mkv
2023-10-31 21:51:11.7|Debug|DetectSample|Runtime of 5159.509 is more than 600 seconds, Not Sample
2023-10-31 21:51:11.7|Debug|Parser|Parsing string 'Les.Miens.2022.FRENCH.1080p.BluRay.REMUX.AVC.DTS-HDMA.5.1-SMV.mkv'
2023-10-31 21:51:11.7|Debug|Parser|Movie Parsed. Les Miens - 2022 
2023-10-31 21:51:11.7|Debug|Parser|Release Group parsed: SMV
2023-10-31 21:51:11.7|Debug|Parser|Languages parsed: French
2023-10-31 21:51:11.7|Debug|QualityParser|Trying to parse quality for 'Les.Miens.2022.FRENCH.1080p.BluRay.REMUX.AVC.DTS-HDMA.5.1-SMV.mkv'
2023-10-31 21:51:11.7|Debug|Parser|Quality parsed: Remux-1080p v1
2023-10-31 21:51:11.7|Debug|Parser|Edition parsed: 
2023-10-31 21:51:11.7|Debug|VideoFileInfoReader|Getting media info from /downloads/video/radarr/Les.Miens.2022.FRENCH.1080p.BluRay.REMUX.AVC.DTS-HDMA.5.1-SMV.mkv
2023-10-31 21:51:11.7|Debug|AggregateLanguage|Selected languages: French
2023-10-31 21:51:11.7|Debug|QualityParser|Trying to parse quality for 'Les.Miens.2022.FRENCH.1080p.BluRay.REMUX.AVC.DTS-HDMA.5.1-SMV'
2023-10-31 21:51:11.7|Debug|AggregateQuality|Using quality: Remux-1080p v1
2023-10-31 21:51:11.7|Debug|AlreadyImportedSpecification|Skipping already imported check for movie without file
2023-10-31 21:51:11.7|Debug|VideoFileInfoReader|Getting media info from /downloads/video/radarr/Les.Miens.2022.FRENCH.1080p.BluRay.REMUX.AVC.DTS-HDMA.5.1-SMV.mkv
2023-10-31 21:51:11.7|Debug|DetectSample|Runtime of 5159.509 is more than 600 seconds, Not Sample
2023-10-31 21:51:11.7|Debug|ImportDecisionMaker|File accepted
2023-10-31 21:51:11.7|Debug|ImportApprovedMovie|Decisions: 1
2023-10-31 21:51:11.7|Debug|MovieFileMovingService|Copying movie file: /downloads/video/radarr/Les.Miens.2022.FRENCH.1080p.BluRay.REMUX.AVC.DTS-HDMA.5.1-SMV.mkv to /videos/movies/Our Ties (2022)/Les Miens (2022) Remux-1080p.mkv
2023-10-31 21:51:11.7|Debug|DiskTransferService|Copy [/downloads/video/radarr/Les.Miens.2022.FRENCH.1080p.BluRay.REMUX.AVC.DTS-HDMA.5.1-SMV.mkv] > [/videos/movies/Our Ties (2022)/Les Miens (2022) Remux-1080p.mkv]
2023-10-31 21:51:11.7|Warn|ImportApprovedMovie|Couldn't import movie /downloads/video/radarr/Les.Miens.2022.FRENCH.1080p.BluRay.REMUX.AVC.DTS-HDMA.5.1-SMV.mkv

[v5.0.3.8127] NzbDrone.Common.Disk.DestinationAlreadyExistsException: Destination /videos/movies/Our Ties (2022)/Les Miens (2022) Remux-1080p.mkv already exists.
   at NzbDrone.Common.Disk.DiskTransferService.ClearTargetPath(String sourcePath, String targetPath, Boolean overwrite) in ./Radarr.Common/Disk/DiskTransferService.cs:line 403
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in ./Radarr.Common/Disk/DiskTransferService.cs:line 296
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode, LocalMovie localMovie) in ./Radarr.Core/MediaFiles/MovieFileMovingService.cs:line 154
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in ./Radarr.Core/MediaFiles/UpgradeMediaFileService.cs:line 41
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in ./Radarr.Core/MediaFiles/MovieImport/ImportApprovedMovie.cs:line 129

2023-10-31 21:51:12.1|Info|DiskScanService|Scanning disk for The Colors of Fire
2023-10-31 21:51:12.1|Debug|DiskScanService|Scanning '/videos/movies/Couleurs de l'incendie (2022)' for video files
2023-10-31 21:51:12.1|Debug|DiskScanService|1 video files were found in /videos/movies/Couleurs de l'incendie (2022)
2023-10-31 21:51:12.1|Debug|DiskScanService|[The Colors of Fire (2022)][tt13217988, 785980] Cleaning up media files in DB
2023-10-31 21:51:12.1|Debug|ImportDecisionMaker|Analyzing 0/0 files.
2023-10-31 21:51:12.1|Debug|ImportApprovedMovie|Decisions: 0
2023-10-31 21:51:12.1|Info|DiskScanService|Completed scanning disk for The Colors of Fire
2023-10-31 21:51:12.1|Debug|ExistingExtraFileService|Looking for existing extra files in /videos/movies/Couleurs de l'incendie (2022)
2023-10-31 21:51:12.1|Debug|DiskScanService|Scanning '/videos/movies/Couleurs de l'incendie (2022)' for non-video files
2023-10-31 21:51:12.1|Debug|DiskScanService|1 non-video files were found in /videos/movies/Couleurs de l'incendie (2022)
2023-10-31 21:51:12.1|Debug|ExistingMetadataImporter|Looking for existing metadata in /videos/movies/Couleurs de l'incendie (2022)
2023-10-31 21:51:12.1|Info|ExistingMetadataImporter|Found 0 existing metadata files
2023-10-31 21:51:12.1|Debug|ExistingSubtitleImporter|Looking for existing subtitle files in /videos/movies/Couleurs de l'incendie (2022)
2023-10-31 21:51:12.1|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
2023-10-31 21:51:12.1|Debug|ExistingOtherExtraImporter|Looking for existing extra files in /videos/movies/Couleurs de l'incendie (2022)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by avillev** [comment]
Hum... @bakerboy448 
I am pretty sure this is a bug :)

**Comment by bakerboy448** [comment]
- Support issues are not bugs
- invalid bug report, debug logs are not the trace logs you claimed to and lied about providing
- logs should not just be spammed in the GHI as per the wiki that was not read
- the file system - not radarr - having issues with correctly reporting the copy is not a radarr issue
- Everytime this issue has been seen it is 100% an issue with the user's environmental setup and file system. For network mounts that is missing the required flags noted in the FAQ and QuickStart. For other systems it is often do to an extremely slow file system or other file system issues that ultimately result in the file not appearing to be relocated on disk 


PS your paths are suboptimal and result in slow IO intensive copies and duplicate space for all torrents. Refer to the Docker install docs, the docker guide, trash's guide, or LSIO's own read me for further details.

**Comment by avillev** [comment]
Thx @mynameisbogdan 

There is a file in the target folder with the same name indeed but I am pretty sure that this job is the one which put it there. It looks like it's competing with itself. I would have absolutly no idea why such a file and folder would end up in this folder otherwise.

To answer your question, all of the movies with such error have a file in the "Files" tab.

**Comment by avillev** [comment]
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/13217919/radarr.trace.txt)
![Files](https://github.com/Radarr/Radarr/assets/30140326/0c7c1d16-7b83-4ce7-adc3-dd7d05b1259e)
![Queues](https://github.com/Radarr/Radarr/assets/30140326/8e310c3a-f4d0-4039-be01-e2d680c2e876)

I finaly understood how to upload a file, sorry for pasting things violently before. I admit that my setup is what it is. But I still don't understand why it'd end up like that :'(

Hardlinks are deactivated.

I just repeated the issue right now with the movie "Air (2023)".
I added a couple of screenshots as well.

**Comment by avillev** [comment]
Ha, i guess that something was fixed on syno at some point on develop. Let me try tonight. A little dangerous though :)

As for the complex naming, i don't mind but my plex has been recognizing things very well so far.

**Comment by cbarbara** [comment]
> `[v5.0.3.8127] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x87AF00AA): database is locked`
> 
> @avillev Using a synology? if true, please try switching to the develop branch.

@mynameisbogdan - i'm also seeing this SQLiteException in a docker container on synology. before I switch to a dev branch, which commit(s) do you think have helped with this error?

**Comment by avillev** [comment]
And apparently we are not the only ones :)

https://www.reddit.com/r/radarr/comments/17ei43n/having_issue_importing_movies_i_get_an_error/

**Comment by avillev** [comment]
And can we assume that something like that is happening to me?

1: the download works
2: the file is renamed and copied properly
3: Somehow that information is not saved to SQLite and Radarr thinks he did not copy things
4: WHen he tries to do it again, he sees the file and says there is a conflict

**Comment by avillev** [comment]
I upgraded to develop, let me see if it continues :)

**Comment by avillev** [comment]
I confirm that it's not really happening anymore. Though I still have a few System.Data.SQLite.SQLiteException (0x800007AF): database is locked flying around. I guess it wasn't connected.
