### ISSUE TITLE
Not detecting movie on disk even with manual scan

### ISSUE THREAD

**Issue by ajkis** [Radarr/Radarr#944]
**Description:**
Movie is not being detected by radarr.
![Image](https://puu.sh/unQ5c/04957469d5.png)
![image2](https://puu.sh/unRTd/207829a0ff.png)
**Radarr Version:**
Radarr Ver. 0.2.0.375 develop

**Logs:**
17-2-28 17:28:30.8|Info|RefreshMovieService|Updating Info for Alien
17-2-28 17:28:31.4|Debug|RefreshMovieService|Finished movie refresh for Alien
17-2-28 17:28:31.8|Info|DiskScanService|Scanning disk for Alien
17-2-28 17:28:31.8|Debug|DiskScanService|Scanning '/mnt/unionfs/movies/Alien (1979)' for video files
17-2-28 17:28:31.8|Debug|DiskScanService|1 video files were found in /mnt/unionfs/movies/Alien (1979)
17-2-28 17:28:31.8|Debug|DiskScanService|[tt0078748][Alien] Cleaning up media files in DB
17-2-28 17:28:31.8|Debug|ImportDecisionMaker|Analyzing 0/1 files.
17-2-28 17:28:31.8|Debug|ImportApprovedMovie|Decisions: 0

**Comment by ajkis** [comment]
I tried changing file modification date but its still not being added.

**Comment by Oz0n3** [comment]
I have a similar issue.
![Uploading Screen Shot 2017-02-28 at 10.25.50 AM.png…]()
![Uploading Screen Shot 2017-02-28 at 10.26.32 AM.png…]()
![Uploading Screen Shot 2017-02-28 at 10.34.10 AM.png…]()
![Uploading Screen Shot 2017-02-28 at 10.37.45 AM.png…]()

**Comment by zaphod0** [comment]
I've just noticed the same issue after adding my existing library. I have add a portion of the logs below. The movies are marked as missing despite being detected originally when adding using "Bulk Import Movies"

**Logs:**

```
17-2-28 21:05:09.4|Info|DiskScanService|Scanning disk for Apocalypse Now
17-2-28 21:05:09.5|Warn|ArgumentValidator|Value can not be null.
17-2-28 21:05:09.5|Error|EventAggregator|DiskScanService failed while processing [MovieUpdatedEvent]

[v0.2.0.375] System.ArgumentNullException: Value can not be null.
Parameter name: profile
   at NzbDrone.Common.EnsureThat.EnsureObjectExtensions.IsNotNull[T](Param`1 param) in C:\projects\radarr-usby1\src\NzbDrone.Common\EnsureThat\EnsureObjectExtensions.cs:line 12
   at NzbDrone.Core.Qualities.QualityModelComparer..ctor(Profile profile) in C:\projects\radarr-usby1\src\NzbDrone.Core\Qualities\QualityModelComparer.cs:line 13
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.<>c.<Import>b__7_2(Int32 i, IEnumerable`1 s) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:line 53
   at System.Linq.Lookup`2.<ApplyResultSelector>d__3`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:line 52
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(Movie movie) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 186
   at NzbDrone.Core.MediaFiles.DiskScanService.Handle(MovieUpdatedEvent message) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 262
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56
```

**Comment by onedr0p** [comment]
@zaphod0 you did not select a profile.

**Comment by zaphod0** [comment]
@onedr0p Sorry I thought I selected "Any" when adding. Obviously I missed this. Selecting a profile has resolved my issue.

**Comment by galli-leo** [comment]
@ajkis Can you enable trace logging and scan again?

**Comment by onedr0p** [comment]
@ajkis accidentally deleted your second post when cleaning up other posts here. Sorry.

**Comment by ajkis** [comment]
I update to nightly and will let you know if it happens again.
Iam redownloading the whole movie to see if it will work.

**Comment by Sparticuz** [comment]
I'm having this problem as well
````
17-3-2 10:48:56.0|Trace|CommandQueueManager|Publishing RefreshMovie
17-3-2 10:48:56.0|Trace|CommandQueueManager|Checking if command is queued or started: RefreshMovie
17-3-2 10:48:56.0|Trace|CommandQueueManager|Inserting new command: RefreshMovie
17-3-2 10:48:56.0|Trace|CommandExecutor|RefreshMovieCommand -> RefreshMovieService
17-3-2 10:48:56.0|Trace|CommandQueueManager|Marking command as started: RefreshMovie
17-3-2 10:48:56.0|Trace|Http|Res: 153 [POST] /api/command: 201.Created (10 ms)
17-3-2 10:48:56.0|Debug|Api|[POST] /api/command: 201.Created (10 ms)
17-3-2 10:48:56.0|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-3-2 10:48:56.0|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-3-2 10:48:56.0|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-3-2 10:48:56.0|Trace|EventAggregator|Publishing MovieRefreshStartingEvent
17-3-2 10:48:56.0|Info|RefreshMovieService|Updating Info for Anchorman 2: The Legend Continues
17-3-2 10:48:56.0|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-3-2 10:48:56.0|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-3-2 10:48:56.0|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-3-2 10:48:56.0|Trace|HttpClient|Req: [GET] https://api.themoviedb.org/3/movie/109443?api_key=1a7373301961d03f97f853a876dd1212&append_to_response=alternative_titles%2Crelease_dates%2Cvideos&language=EN
17-3-2 10:48:56.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-3-2 10:48:56.4|Trace|HttpClient|Res: [GET] https://api.themoviedb.org/3/movie/109443?api_key=1a7373301961d03f97f853a876dd1212&append_to_response=alternative_titles%2Crelease_dates%2Cvideos&language=EN: 200.OK (456 ms)
17-3-2 10:48:56.5|Trace|EventAggregator|Publishing MovieEditedEvent
17-3-2 10:48:56.5|Trace|EventAggregator|MovieEditedEvent -> MovieEditedService
17-3-2 10:48:56.5|Trace|EventAggregator|MovieEditedEvent <- MovieEditedService
17-3-2 10:48:56.5|Trace|EventAggregator|MovieEditedEvent -> MovieModule
17-3-2 10:48:56.5|Trace|EventAggregator|MovieEditedEvent <- MovieModule
17-3-2 10:48:56.5|Trace|EventAggregator|MovieEditedEvent -> CalendarModule
17-3-2 10:48:56.5|Trace|EventAggregator|MovieEditedEvent <- CalendarModule
17-3-2 10:48:56.5|Debug|RefreshMovieService|Finished movie refresh for Anchorman 2: The Legend Continues
17-3-2 10:48:56.5|Trace|EventAggregator|Publishing MovieUpdatedEvent
17-3-2 10:48:56.5|Trace|EventAggregator|MovieUpdatedEvent -> DiskScanService
17-3-2 10:48:56.5|Info|DiskScanService|Scanning disk for Anchorman 2: The Legend Continues
17-3-2 10:48:56.5|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-3-2 10:48:56.5|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-3-2 10:48:56.5|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-3-2 10:48:56.5|Debug|DiskScanService|Scanning '/mnt/samba/Movies/Anchorman 2 - The Legend Continues (2013)' for video files
17-3-2 10:48:56.5|Debug|DiskScanService|1 video files were found in /mnt/samba/Movies/Anchorman 2 - The Legend Continues (2013)
17-3-2 10:48:56.5|Trace|DiskScanService|Finished getting episode files for: [tt1229340][Anchorman 2: The Legend Continues] [00:00:00.0025080]
17-3-2 10:48:56.5|Debug|DiskScanService|[tt1229340][Anchorman 2: The Legend Continues] Cleaning up media files in DB
17-3-2 10:48:56.5|Debug|ImportDecisionMaker|Analyzing 0/1 files.
17-3-2 10:48:56.5|Trace|DiskScanService|Import decisions complete for: [tt1229340][Anchorman 2: The Legend Continues] [00:00:00.0029457]
17-3-2 10:48:56.5|Debug|ImportApprovedMovie|Decisions: 0
17-3-2 10:48:56.5|Info|DiskScanService|Completed scanning disk for Anchorman 2: The Legend Continues
17-3-2 10:48:56.5|Trace|EventAggregator|Publishing MovieScannedEvent
17-3-2 10:48:56.5|Trace|EventAggregator|MovieScannedEvent -> MovieScannedHandler
17-3-2 10:48:56.5|Trace|EventAggregator|MovieScannedEvent <- MovieScannedHandler
17-3-2 10:48:56.5|Trace|EventAggregator|MovieScannedEvent -> UpdateMovieFileService
17-3-2 10:48:56.5|Trace|ConfigService|Using default config value for 'filedate' defaultValue:'None'
17-3-2 10:48:56.5|Trace|EventAggregator|MovieScannedEvent <- UpdateMovieFileService
17-3-2 10:48:56.5|Trace|EventAggregator|MovieUpdatedEvent <- DiskScanService
17-3-2 10:48:56.5|Trace|EventAggregator|MovieUpdatedEvent -> MovieModule
17-3-2 10:48:56.5|Trace|EventAggregator|MovieUpdatedEvent <- MovieModule
17-3-2 10:48:56.5|Trace|EventAggregator|MovieUpdatedEvent -> CalendarModule
17-3-2 10:48:56.5|Trace|EventAggregator|MovieUpdatedEvent <- CalendarModule
17-3-2 10:48:56.5|Trace|CommandQueueManager|Updating command status
17-3-2 10:48:56.5|Trace|EventAggregator|MovieUpdatedEvent ~> MediaCoverService
17-3-2 10:48:56.5|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-3-2 10:48:56.5|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-3-2 10:48:56.5|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-3-2 10:48:56.5|Trace|EventAggregator|Publishing CommandExecutedEvent
17-3-2 10:48:56.5|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
17-3-2 10:48:56.5|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
17-3-2 10:48:56.5|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
17-3-2 10:48:56.5|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
17-3-2 10:48:56.5|Trace|CommandExecutor|RefreshMovieCommand <- RefreshMovieService [00:00:00.5391160]
17-3-2 10:48:56.6|Trace|HttpClient|Req: [HEAD] http://image.tmdb.org/t/p/original/66HbvNKmfxYoOHAp1IVIYQsFoeA.jpg
17-3-2 10:48:56.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-3-2 10:48:56.7|Trace|HttpClient|Res: [HEAD] http://image.tmdb.org/t/p/original/66HbvNKmfxYoOHAp1IVIYQsFoeA.jpg: 200.OK (102 ms)
17-3-2 10:48:56.8|Trace|HttpClient|Req: [HEAD] http://image.tmdb.org/t/p/original/mTMnfiWuvhbCdez9LAzbYy0vLSG.jpg
17-3-2 10:48:56.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-3-2 10:48:56.9|Trace|HttpClient|Res: [HEAD] http://image.tmdb.org/t/p/original/mTMnfiWuvhbCdez9LAzbYy0vLSG.jpg: 200.OK (117 ms)
17-3-2 10:48:56.9|Trace|EventAggregator|Publishing MediaCoversUpdatedEvent
17-3-2 10:48:56.9|Trace|EventAggregator|MediaCoversUpdatedEvent -> ExtraService
17-3-2 10:48:56.9|Trace|EventAggregator|MediaCoversUpdatedEvent <- ExtraService
17-3-2 10:48:56.9|Trace|EventAggregator|MediaCoversUpdatedEvent -> SeriesModule
17-3-2 10:48:56.9|Trace|EventAggregator|MediaCoversUpdatedEvent <- SeriesModule
17-3-2 10:48:56.9|Trace|EventAggregator|MediaCoversUpdatedEvent -> MovieModule
17-3-2 10:48:56.9|Trace|EventAggregator|MediaCoversUpdatedEvent <- MovieModule
17-3-2 10:48:56.9|Trace|EventAggregator|MediaCoversUpdatedEvent -> CalendarModule
17-3-2 10:48:56.9|Trace|EventAggregator|MediaCoversUpdatedEvent <- CalendarModule
17-3-2 10:48:56.9|Trace|EventAggregator|MovieUpdatedEvent <~ MediaCoverService

**Comment by galli-leo** [comment]
This is fixed on the latest release.

**Comment by Sparticuz** [comment]
This is still not working for me (running 0.2.0.535)

````
17-3-16 11:33:12.1|Trace|CommandQueueManager|Publishing RefreshMovie
17-3-16 11:33:12.1|Trace|CommandQueueManager|Checking if command is queued or started: RefreshMovie
17-3-16 11:33:12.1|Trace|CommandQueueManager|Inserting new command: RefreshMovie
17-3-16 11:33:12.1|Trace|CommandExecutor|RefreshMovieCommand -> RefreshMovieService
17-3-16 11:33:12.1|Trace|CommandQueueManager|Marking command as started: RefreshMovie
17-3-16 11:33:12.1|Trace|Http|Res: 63 [POST] /api/command: 201.Created (84 ms)
17-3-16 11:33:12.1|Debug|Api|[POST] /api/command: 201.Created (84 ms)
17-3-16 11:33:12.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-3-16 11:33:12.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-3-16 11:33:12.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-3-16 11:33:12.1|Trace|EventAggregator|Publishing MovieRefreshStartingEvent
17-3-16 11:33:12.1|Info|RefreshMovieService|Updating Info for Anchorman 2: The Legend Continues
17-3-16 11:33:12.2|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-3-16 11:33:12.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-3-16 11:33:12.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-3-16 11:33:12.2|Trace|HttpClient|Req: [GET] https://api.themoviedb.org/3/movie/109443?api_key=1a7373301961d03f97f853a876dd1212&append_to_response=alternative_titles%2Crelease_dates%2Cvideos&language=EN
17-3-16 11:33:12.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-3-16 11:33:12.5|Trace|HttpClient|Res: [GET] https://api.themoviedb.org/3/movie/109443?api_key=1a7373301961d03f97f853a876dd1212&append_to_response=alternative_titles%2Crelease_dates%2Cvideos&language=EN: 200.OK (279 ms)
17-3-16 11:33:12.7|Trace|HttpClient|Req: [GET] https://api.themoviedb.org/3/configuration?api_key=1a7373301961d03f97f853a876dd1212
17-3-16 11:33:12.7|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-3-16 11:33:12.9|Trace|HttpClient|Res: [GET] https://api.themoviedb.org/3/configuration?api_key=1a7373301961d03f97f853a876dd1212: 200.OK (239 ms)
17-3-16 11:33:12.9|Trace|HttpClient|Req: [GET] http://predb.me?rss=1&cats=movies&search=Anchorman%202%3A%20The%20Legend%20Continues
17-3-16 11:33:12.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-3-16 11:33:13.0|Trace|HttpClient|Res: [GET] http://predb.me?rss=1&cats=movies&search=Anchorman%202%3A%20The%20Legend%20Continues: 403.Forbidden (125 ms)
17-3-16 11:33:13.0|Warn|PreDBService|Non 200 StatusCode Forbidden encountered while searching PreDB.
17-3-16 11:33:13.1|Trace|EventAggregator|Publishing MovieEditedEvent
17-3-16 11:33:13.1|Trace|EventAggregator|MovieEditedEvent -> MovieEditedService
17-3-16 11:33:13.1|Trace|EventAggregator|MovieEditedEvent <- MovieEditedService
17-3-16 11:33:13.1|Trace|EventAggregator|MovieEditedEvent -> MovieModule
17-3-16 11:33:13.1|Trace|EventAggregator|MovieEditedEvent <- MovieModule
17-3-16 11:33:13.1|Trace|EventAggregator|MovieEditedEvent -> CalendarModule
17-3-16 11:33:13.1|Trace|EventAggregator|MovieEditedEvent <- CalendarModule
17-3-16 11:33:13.1|Debug|RefreshMovieService|Finished movie refresh for Anchorman 2: The Legend Continues
17-3-16 11:33:13.1|Trace|EventAggregator|Publishing MovieUpdatedEvent
17-3-16 11:33:13.1|Trace|EventAggregator|MovieUpdatedEvent -> DiskScanService
17-3-16 11:33:13.2|Trace|Http|Req: 64 [GET] /MediaCover/28/banner.jpg?lastWrite=636226769490000000
17-3-16 11:33:13.2|Trace|Http|Res: 64 [GET] /MediaCover/28/banner.jpg?lastWrite=636226769490000000: 200.OK (5 ms)
17-3-16 11:33:13.2|Info|DiskScanService|Scanning disk for Anchorman 2: The Legend Continues
17-3-16 11:33:13.2|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-3-16 11:33:13.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-3-16 11:33:13.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-3-16 11:33:13.2|Debug|DiskScanService|Scanning '/mnt/samba/Rented Movies/Anchorman 2 - The Legend Continues (2013)' for video files
17-3-16 11:33:13.3|Debug|DiskScanService|1 video files were found in /mnt/samba/Rented Movies/Anchorman 2 - The Legend Continues (2013)
17-3-16 11:33:13.3|Trace|DiskScanService|Finished getting episode files for: [tt1229340][Anchorman 2: The Legend Continues] [00:00:00.0562064]
17-3-16 11:33:13.3|Debug|DiskScanService|[tt1229340][Anchorman 2: The Legend Continues] Cleaning up media files in DB
17-3-16 11:33:13.3|Debug|ImportDecisionMaker|Analyzing 0/1 files.
17-3-16 11:33:13.3|Trace|DiskScanService|Import decisions complete for: [tt1229340][Anchorman 2: The Legend Continues] [00:00:00.0066630]
17-3-16 11:33:13.3|Debug|ImportApprovedMovie|Decisions: 0
17-3-16 11:33:13.3|Info|DiskScanService|Completed scanning disk for Anchorman 2: The Legend Continues
17-3-16 11:33:13.3|Trace|EventAggregator|Publishing MovieScannedEvent
17-3-16 11:33:13.3|Trace|EventAggregator|MovieScannedEvent -> MovieScannedHandler
17-3-16 11:33:13.3|Trace|EventAggregator|MovieScannedEvent <- MovieScannedHandler
17-3-16 11:33:13.3|Trace|EventAggregator|MovieScannedEvent -> UpdateMovieFileService
17-3-16 11:33:13.3|Trace|ConfigService|Using default config value for 'filedate' defaultValue:'None'
17-3-16 11:33:13.3|Trace|EventAggregator|MovieScannedEvent <- UpdateMovieFileService
17-3-16 11:33:13.3|Trace|EventAggregator|MovieScannedEvent -> UpdateMediaInfoService
17-3-16 11:33:13.3|Trace|ConfigService|Using default config value for 'enablemediainfo' defaultValue:'True'
17-3-16 11:33:13.3|Trace|EventAggregator|MovieScannedEvent <- UpdateMediaInfoService
17-3-16 11:33:13.3|Trace|EventAggregator|MovieUpdatedEvent <- DiskScanService
17-3-16 11:33:13.3|Trace|EventAggregator|MovieUpdatedEvent -> MovieModule
17-3-16 11:33:13.3|Trace|EventAggregator|MovieUpdatedEvent <- MovieModule
17-3-16 11:33:13.3|Trace|EventAggregator|MovieUpdatedEvent -> CalendarModule
17-3-16 11:33:13.3|Trace|EventAggregator|MovieUpdatedEvent <- CalendarModule
17-3-16 11:33:13.3|Trace|EventAggregator|MovieUpdatedEvent ~> MediaCoverService
17-3-16 11:33:13.3|Trace|CommandQueueManager|Updating command status
17-3-16 11:33:13.3|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-3-16 11:33:13.4|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-3-16 11:33:13.4|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-3-16 11:33:13.4|Trace|EventAggregator|Publishing CommandExecutedEvent
17-3-16 11:33:13.4|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
17-3-16 11:33:13.4|Trace|Owin|SQLite error (5): database is locked

17-3-16 11:33:13.4|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
17-3-16 11:33:13.4|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
17-3-16 11:33:13.4|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
17-3-16 11:33:13.4|Trace|CommandExecutor|RefreshMovieCommand <- RefreshMovieService [00:00:01.1998890]
17-3-16 11:33:13.5|Trace|HttpClient|Req: [HEAD] http://image.tmdb.org/t/p/original/66HbvNKmfxYoOHAp1IVIYQsFoeA.jpg
17-3-16 11:33:13.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-3-16 11:33:14.4|Trace|HttpClient|Res: [HEAD] http://image.tmdb.org/t/p/original/66HbvNKmfxYoOHAp1IVIYQsFoeA.jpg: 200.OK (878 ms)
17-3-16 11:33:14.5|Trace|HttpClient|Req: [HEAD] http://image.tmdb.org/t/p/original/mTMnfiWuvhbCdez9LAzbYy0vLSG.jpg
17-3-16 11:33:14.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-3-16 11:33:14.7|Trace|HttpClient|Res: [HEAD] http://image.tmdb.org/t/p/original/mTMnfiWuvhbCdez9LAzbYy0vLSG.jpg: 200.OK (192 ms)
17-3-16 11:33:14.7|Trace|EventAggregator|Publishing MediaCoversUpdatedEvent
17-3-16 11:33:14.7|Trace|EventAggregator|MediaCoversUpdatedEvent -> ExtraService
17-3-16 11:33:14.7|Trace|EventAggregator|MediaCoversUpdatedEvent <- ExtraService
17-3-16 11:33:14.7|Trace|EventAggregator|MediaCoversUpdatedEvent -> SeriesModule
17-3-16 11:33:14.7|Trace|EventAggregator|MediaCoversUpdatedEvent <- SeriesModule
17-3-16 11:33:14.7|Trace|EventAggregator|MediaCoversUpdatedEvent -> MovieModule
17-3-16 11:33:14.7|Trace|EventAggregator|MediaCoversUpdatedEvent <- MovieModule
17-3-16 11:33:14.7|Trace|EventAggregator|MediaCoversUpdatedEvent -> CalendarModule
17-3-16 11:33:14.7|Trace|EventAggregator|MediaCoversUpdatedEvent <- CalendarModule
17-3-16 11:33:14.7|Trace|EventAggregator|MovieUpdatedEvent <~ MediaCoverService
````

**Comment by galli-leo** [comment]
@Sparticuz Try removing and re-adding the movie.

**Comment by Sparticuz** [comment]
I moved the file into the drone factory, then did a manual import, matched it up to the correct item and imported. it worked.
