### ISSUE TITLE
Couldn't import movie \\DISKSTATION\My Book\Movies\blah\blah.mp4: The network connection was aborted by the local system.

### ISSUE THREAD

**Issue by Lasikie** [Radarr/Radarr#947]
**Description:**

I'm getting the below error when NZBget sends the file back to radarr

**Radarr Version:**
0.2.0.375

**Message**
Couldn't import movie \\DISKSTATION\My Book\Movies\blah\blah.mp4: The network connection was aborted by the local system.

**Logs:**
System.IO.IOException: The network connection was aborted by the local system.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile(String source, String destination, Boolean overwrite) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 209
   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified(String sourcePath, String targetPath, Int64 originalSize) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 564
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 308
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 183
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 117
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 77
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile episodeFile, LocalMovie localEpisode, Boolean copyOnly) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 74
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:line 103

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Do you get this for every file?

**Comment by galli-leo** [comment]
If this is still an issue, let me know and I will reopen.
