### ISSUE TITLE
Cannot search any movie result 503.ServiceUnavailable

### ISSUE THREAD

**Issue by BramFr** [Radarr/Radarr#9504]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

After a search of a movie i`ll get a result of: "Failed to load search results, please try again." within the logs i recieve a 503 message.

### Expected Behavior

Finding a movie to add to radarr list.

### Steps To Reproduce

Just try to search any movie. 
![image](https://github.com/Radarr/Radarr/assets/16082279/f8e08ae4-013f-4cde-88e5-498e36a8ed42)

### Environment

```markdown
- OS: Debian 12
- Radarr: 5.1.3.8246
- Docker Install: Yes Kubernetes
- Using Reverse Proxy: No
- Browser: Chrome latest version
- Database: Sqlite 3.41.2
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

2023-12-21 07:06:08.2|Trace|RadarrErrorPipeline|Handling Exception
2023-12-21 07:06:08.2|Trace|Http|Res: 60430 [GET] /api/v3/movie/lookup?term=the%20color%20pu: 503.ServiceUnavailable (100016 ms)
2023-12-21 07:06:08.2|Debug|Api|[GET] /api/v3/movie/lookup?term=the%20color%20pu: 503.ServiceUnavailable (100016 ms)
2023-12-21 07:06:08.9|Warn|SkyHookProxy|System.Threading.Tasks.TaskCanceledException: A task was canceled.

[v5.1.3.8246] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Radarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 105
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Radarr.Common/Http/HttpClient.cs:line 157
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Radarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.GetAsync[T](HttpRequest request) in ./Radarr.Common/Http/HttpClient.cs:line 336
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 502

2023-12-21 07:06:09.0|Trace|RadarrErrorPipeline|Handling Exception
2023-12-21 07:06:09.0|Trace|Http|Res: 60431 [GET] /api/v3/movie/lookup?term=the%20color%20purple: 503.ServiceUnavailable (100014 ms)
2023-12-21 07:06:09.0|Debug|Api|[GET] /api/v3/movie/lookup?term=the%20color%20purple: 503.ServiceUnavailable (100014 ms)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by BramFr** [comment]
after rollout command within kubernetess reload the container. After this action everythings works fine again.
