### ISSUE TITLE
Indexer flag parsing failure on removed flags

### ISSUE THREAD

**Issue by ossimoi** [Radarr/Radarr#9557]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues

### Current Behavior

Task 'Process Monitored Downloads' fails if download has broken indexer flags.

The actual flags are:
  
`"indexerFlags": "g_Freeleech, HDB_Internal",`

I suspect these are set on earlier version and should have been removed by migration scripts?

Fixed by manually editing the database and removing HDB_Internal from flags of affected releases. Had this happen for 3 out of ~3000 releases. The task dying caused automatic importing to break completely.

### Expected Behavior

Process Monitored Downloads should ignore and warn about the problematic release and process the ones it can.

### Environment

```markdown
- OS: Debian 12
- Radarr: 5.2.6.8376
- Docker Install: Yes
- Database: Sqlite 3.41.2
```

### What branch are you running?

Develop

### Trace Logs? **Not Optional**

```
 ---> System.Text.Json.JsonException: The JSON value could not be converted to NzbDrone.Core.Parser.Model.IndexerFlags. Path: $.indexerFlags | LineNumber: 19 | BytePositionInLine: 45.
   at System.Text.Json.ThrowHelper.ThrowJsonException(String message)
   at System.Text.Json.Serialization.Converters.EnumConverter`1.ReadAsPropertyNameCore(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.EnumConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Dapper.SqlMapper.TypeHandler`1.Dapper.SqlMapper.ITypeHandler.Parse(Type destinationType, Object value) in /_/Dapper/SqlMapper.TypeHandler.cs:line 42
   at Dapper.SqlMapper.TypeHandlerCache`1.Parse(Object value) in /_/Dapper/SqlMapper.TypeHandlerCache.cs:line 23
   at Deserialize12f56440-de82-496f-9470-838a012d9baa(DbDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3878
   at Deserialize12f56440-de82-496f-9470-838a012d9baa(DbDataReader )
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[T](IDatabase db, String sql, Object param)
   at NzbDrone.Core.Datastore.BasicRepository`1.Query(SqlBuilder builder)
   at NzbDrone.Core.Download.History.DownloadHistoryRepository.FindByDownloadId(String downloadId)
   at NzbDrone.Core.Download.History.DownloadHistoryService.GetLatestGrab(String downloadId)
   at NzbDrone.Core.Download.DownloadSeedConfigProvider.FetchIndexer(String infoHash)
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime)
   at NzbDrone.Core.Download.DownloadSeedConfigProvider.GetSeedConfiguration(String infoHash)
   at NzbDrone.Core.Download.Clients.RTorrent.RTorrent.GetItems()
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient)
```
### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
For future reference a partial stack trace are neither trace logs nor what one would get following the steps on the wiki as you appear to have erroneously checked as having been completed

**Comment by ossimoi** [comment]
> [e5963c9](https://github.com/Radarr/Radarr/commit/e5963c9ee1ea5c043eb94890fc0ab822a18b63cc)
> 
> This was fixed 4 months ago.
> 
> You logs have anything related to migration 233 in them?

Bunch of entries by MigrationController, nothing of this particular migration.

**Comment by ossimoi** [comment]
> For future reference a partial stack trace are neither trace logs nor what one would get following the steps on the wiki as you appear to have erroneously checked as having been completed

True, this is not the full trace log, but literally the only relevant snippet related to the issue.

**Comment by ossimoi** [comment]
> Unless you can provide some logs related to migration 233 or to provide information in which tables you had to remove that aren't in the migration, there's nothing much to do here.

I'll dig through the logs once more.

Did not delete any tables. IndexerFlags are stored in Release field, in DownloadHistory table, stored as raw JSON, which was easy to update in place.

**Comment by ossimoi** [comment]
Hmm, seems like https://github.com/Radarr/Radarr/commit/e5963c9ee1ea5c043eb94890fc0ab822a18b63cc fixes 'hdB_Internal' for DownloadHistory but not 'HDB_Internal'.

**Comment by ossimoi** [comment]
> The enum `HDB_Internal` is saved as `hdB_Internal` so it's not that unless you changed something manually directly in the database.
> 
> Same goes for `PTP_Golden` as `ptP_Golden`, `PTP_Approved` as `ptP_Approved`, etc.

After running the migrations manually, 'HDB_Internal' still persists in IndexerFlags. The replace query will only work for 'hdB_Internal' flag. From where the HDB_Internal origins from I have no idea, never touched the database manually before.

Interestingly enough only 3 releases were affected by this, while;
```
sqlite> select count(*) from DownloadHistory where Release regexp 'Internal';
227
```

**Comment by ossimoi** [comment]
> Like I already said,`HDB_Internal` should not be saved there if the application set the indexer flags.
Well, it clearly was.

> It's not that surprising, there's also `g_Internal` in use.
But out of all Internal releases only 3 had broken flag 'HDB_Internal' set.

**Comment by ossimoi** [comment]
What do you mean? I've probably had this going on for a while. Radarr has been working fine except automatic imports have not. Been importing manually and just now bothered to actually check what's going on.

**Comment by ossimoi** [comment]
Just to clarify;

Running radarr:develop since 2020. Instance barely touched at all during that time.

Automatic imports stop working somewhere during fall 2023. Everything else works 100%. Import manually until now.

Find out automatic importing broken because 3 out of 3000 releases have broken IndexerFlag set.

**Comment by ossimoi** [comment]
```
sqlite> select Date from DownloadHistory where Release regexp 'HDB_Internal';
2021-02-20 20:28:34.3535013Z
2021-05-23 19:29:18.743794Z
2021-05-26 17:36:53.8754323Z
```

**Comment by Qstick** [comment]
There were a lot of odd things happening with flags (and other stuff) in the beginning of this project, it wouldn't surprise me if there were different cases being saved to DB for these enums.

**Comment by Qstick** [comment]
Can't we do another migration that is case insensitive to get these out of the DB?
