### ISSUE TITLE
Link Crew/Cast to TMDB

### ISSUE THREAD

**Issue by ZacWarham** [Radarr/Radarr#9667]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It would be nice to be able to click on one of the Crew/Cast Sliders and be taken to the TMDB profile of that person

### Describe the solution you'd like

Use the existing tmdbId to link to the person page when looking at a movie in your library

### Describe alternatives you've considered

NA

### Anything else?

From what I can tell you just need to add `tmdbId` to the _frontend/src/Movie/Details/Credits/Cast/MovieCastPoster.js_  (and crew equivalent) const as well as update `<div className={styles.title}>
          {character}
        </div>` to be a URL but I presume that is just my lack of knowledge of React/C#/this code base making it seem simpler than it is

**Comment by ZacWarham** [comment]
> You're on the right track with what needs to be done. Do you want to take a try at it?
> 
> We're always in search of an extra hand. 😋
> 
> https://github.com/Radarr/Radarr/blob/develop/CONTRIBUTING.md

I did try but I kept getting stuck trying to run the Radarr file through wsl 2 on Windows 11 🙃

![image](https://github.com/Radarr/Radarr/assets/48937711/cc053c7b-afd5-4db1-b389-6a253e22a63f)

**Comment by ZacWarham** [comment]
> Try to set `LaunchBrowser` to `false` in your config.xml to disable that.

I can give that a try when I'm back home but if I navigate to localhost directly it gives me a response saying it can't find the resource. I think it's related to the last two lines there where my content path is correct but it's looking within the Linux folder for that directory as if it's appending it?

**Comment by ZacWarham** [comment]
> No, based on the last line in your screenshot you just forgot to build the assets.
> 
> ```shell
> yarn install # to install frontend packages
> yarn watch # to build the assets in watch mode, CTRL+C to quit watch mode
> ```

I had already done that and can see index.html in my _output/UI directory

**Comment by ZacWarham** [comment]
> Are you sure you build the project Radarr.Console in Debug + Posix and not Release? But I don't use VS to be sure...

I ran Radarr not Radarr.Console because I am doing this from the Ubuntu terminal, not in Windows (from what I can see Radarr.Console is an exe for Windows?)

> [Terminal]
sudo snap install dotnet-sdk --classic
conda activate radarr
[Conda Env]
~/projects/radarr$ corepack enable
~/projects/radarr$ yarn
~/projects/radarr$ git clone https://github.com/ZacWarham/Radarr.git
~/projects/radarr$ cd Radarr/
~/projects/radarr/Radarr$ yarn install
~/projects/radarr/Radarr$ yarn start
[Terminal]
dotnet msbuild -restore src/Radarr.sln -p:Configuration=Debug -p:Platform=Posix -t:PublishAllRids
[Conda Env]
~/projects/radarr/Radarr$ dotnet msbuild -restore src/Radarr.sln -p:Configuration=Debug -p:Platform=Posix -t:PublishAllRids
~/projects/radarr/Radarr/_output$ ./net6.0/linux-x64/Radarr
~/projects/radarr/Radarr/_output/UI$ ./../net6.0/linux-x64/Radarr
~/projects/radarr/Radarr$ ./_output/net6.0/linux-x64/Radarr

Is this what you are referring to?

**Comment by ZacWarham** [comment]
> Ah, you're using Visual Studio.
> 
> `dotnet --version` what's showing?

8.0.100

**Comment by ZacWarham** [comment]
> Try to install dotnet 6.x, we don't have support for 8.x yet.

I downgraded to 6 and then did a rebuild and am getting a different error. Trying to install what it is suggesting (so far with no luck) but will put here in case you recognize it

> Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CachedCulturesByName()
   at System.Globalization.CultureInfo.GetCultureInfo(System.String)
   at System.Reflection.RuntimeAssembly.GetLocale()
   at System.Reflection.RuntimeAssembly.GetName(Boolean)
   at System.Reflection.Assembly.GetName()
   at System.AppDomain.get_FriendlyName()
   at NLog.Internal.Fakeables.AppDomainWrapper..ctor(System.AppDomain)
   at NLog.LogFactory.get_DefaultAppEnvironment()
   at NLog.LogFactory..cctor()
   at NLog.LogFactory..ctor()
   at NLog.LogManager..cctor()
   at NLog.LogManager.get_LogFactory()
   at NLog.Config.LoggingConfiguration..ctor()
   at NzbDrone.Common.Instrumentation.NzbDroneLogger..cctor()
   at NzbDrone.Common.Instrumentation.NzbDroneLogger.Register(NzbDrone.Common.EnvironmentInfo.IStartupContext, Boolean, Boolean)
   at NzbDrone.Console.ConsoleApp.Main(System.String[])
Aborted

**Comment by ZacWarham** [comment]
> Try to do a clean before, or try again from scratch if it fails.

Ah, I mistakenly assumed the Restore and Build cleaned as well. Cleaning first fails

> ~/projects/radarr/Radarr$ dotnet clean $slnFile -c Debug
MSBuild version 17.3.2+561848881 for .NET
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.




Side note; I tried setting the Invariant to true like the error message suggested and I get back to where I was before with the service running but unable to find index.html

**Comment by ZacWarham** [comment]
> Try
> 
> ```shell
> dotnet clean src/Radarr.sln -c Release
> dotnet clean src/Radarr.sln -c Debug
> ```

Just realised that the .sln file was in src as I posted that sorry 🙃

Trying both of these Debug basically removed nothing but Release removed a whole lot. Is this what you were asking before about building in wrong location?

> Are you sure you build the project Radarr.Console in Debug + Posix and not Release? But I don't use VS to be sure...

**Comment by ZacWarham** [comment]
> Try again with the updated commands. Tested them myself and it's surely working.

I tried this and I was still having the same issue. I decided to spin up an Ubuntu VM on my NAS and try a fresh install of the instructions from there. Success in the VM. What I noticed in the VM was that my `_output/net6.0` folder looked different. Instead of being a bunch of folders for each platform (linux-arm, osx-x64, win-x86 etc), it was just the contents of one of those folders.

I went back to my desktop and noticed in the process of all this troubleshooting the contents of the linux folder was in the net6.0 alongside all the platform folders. Running `~/projects/radarr/Radarr$ ./_output/net6.0/linux-x64/Radarr` failed but if I removed the `linux-x64` then it worked on my desktop.

My hypothesis is when running the instructions from the wiki, `dotnet msbuild -restore src/Radarr.sln -p:Configuration=Debug -p:Platform=Posix -t:PublishAllRids` built the _output for every platform in their respective folder and then `dotnet msbuild -restore src/Radarr.sln -p:Configuration=Debug -p:Platform=Posix -p:RuntimeIdentifiers=linux-x64` just builds the specific version. The issue then is that the `Radarr.dll` is using a relative path, hence the .. that shows in my path mismatch screenshot. The code is built to only go up one directory but because mine was built inside a subfolder it could not find the UI folder. Which would explain why I could load Radarr but not see the UI.

I am not sure where to go to confirm this hypothesis but perhaps you know if this sounds likely? I guess I could try in a fresh Windows VM but re-installing one OS in a night is enough for me 😅

**Comment by ZacWarham** [comment]
> You're right, that's why I removed `-t:PublishAllRids` and added `-p:RuntimeIdentifiers=linux-x64` to build directly in `_output/net6.0`.
> 
> `-p:Configuration=Debug` is needed because of
> 
> https://github.com/Radarr/Radarr/blob/c717989034192d717bdc1ecbd54187147dc376ac/src/NzbDrone.Core/Configuration/ConfigFileProvider.cs#L232

So it was appending all along 😅 glad we got there in the end. Perhaps it is worth updating the contributing wiki to explain this?

I have been able to create this feature now and had put in a PR for it. Probably buggered up that process somehow though 🙃
