### ISSUE TITLE
[v5.3.1.8438] System.ArgumentException: value [M:]  is not a valid Windows path. paths must be a full path e.g. C:\Windows (Parameter 'path')

### ISSUE THREAD

**Issue by redglory** [Radarr/Radarr#9709]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I'm getting the following error while starting Radarr after 14/01 upgrade to v5.3.1.8432:
`2024-01-14 06:36:09.6|Warn|ArgumentValidator|value [M:]  is not a valid Windows path. paths must be a full path e.g. C:\Windows
2024-01-14 06:36:09.6|Error|CommandExecutor|Error occurred while executing task CheckHealth

[v5.3.1.8432] System.ArgumentException: value [M:]  is not a valid Windows path. paths must be a full path e.g. C:\Windows (Parameter 'path')
   at NzbDrone.Common.EnsureThat.EnsureStringExtensions.IsValidPath(Param`1 param, PathValidationType validationType) in ./Radarr.Common/EnsureThat/EnsureStringExtensions.cs:line 119
   at NzbDrone.Common.Disk.DiskProviderBase.FolderExists(String path) in ./Radarr.Common/Disk/DiskProviderBase.cs:line 97
   at NzbDrone.Core.HealthCheck.Checks.MovieCollectionRootFolderCheck.Check() in ./Radarr.Core/HealthCheck/Checks/MovieCollectionRootFolderCheck.cs:line 41
   at NzbDrone.Core.HealthCheck.HealthCheckService.<ProcessHealthChecks>b__15_0(IProvideHealthCheck c) in ./Radarr.Core/HealthCheck/HealthCheckService.cs:line 97
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at NzbDrone.Core.HealthCheck.HealthCheckService.ProcessHealthChecks() in ./Radarr.Core/HealthCheck/HealthCheckService.cs:line 85
   at NzbDrone.Core.HealthCheck.HealthCheckService.Execute(CheckHealthCommand message) in ./Radarr.Core/HealthCheck/HealthCheckService.cs:line 149
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in ./Radarr.Core/Messaging/Commands/CommandExecutor.cs:line 113
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in ./Radarr.Core/Messaging/Commands/CommandExecutor.cs:line 44`

ROOT FOLDERS:
3	M:\
4	G:\Animation\Movies\

### Expected Behavior

Radarr starts wihout any issue (haven't changed anything on my config).

### Steps To Reproduce

Start Radarr console as a service

### Environment

```markdown
- OS: Windows 10
- Radarr: v5.3.1.8432
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Brave
- Database:
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

`2024-01-14 06:36:09.6|Warn|ArgumentValidator|value [M:]  is not a valid Windows path. paths must be a full path e.g. C:\Windows
2024-01-14 06:36:09.6|Error|CommandExecutor|Error occurred while executing task CheckHealth

[v5.3.1.8432] System.ArgumentException: value [M:]  is not a valid Windows path. paths must be a full path e.g. C:\Windows (Parameter 'path')
   at NzbDrone.Common.EnsureThat.EnsureStringExtensions.IsValidPath(Param`1 param, PathValidationType validationType) in ./Radarr.Common/EnsureThat/EnsureStringExtensions.cs:line 119
   at NzbDrone.Common.Disk.DiskProviderBase.FolderExists(String path) in ./Radarr.Common/Disk/DiskProviderBase.cs:line 97
   at NzbDrone.Core.HealthCheck.Checks.MovieCollectionRootFolderCheck.Check() in ./Radarr.Core/HealthCheck/Checks/MovieCollectionRootFolderCheck.cs:line 41
   at NzbDrone.Core.HealthCheck.HealthCheckService.<ProcessHealthChecks>b__15_0(IProvideHealthCheck c) in ./Radarr.Core/HealthCheck/HealthCheckService.cs:line 97
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at NzbDrone.Core.HealthCheck.HealthCheckService.ProcessHealthChecks() in ./Radarr.Core/HealthCheck/HealthCheckService.cs:line 85
   at NzbDrone.Core.HealthCheck.HealthCheckService.Execute(CheckHealthCommand message) in ./Radarr.Core/HealthCheck/HealthCheckService.cs:line 149
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in ./Radarr.Core/Messaging/Commands/CommandExecutor.cs:line 113
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in ./Radarr.Core/Messaging/Commands/CommandExecutor.cs:line 44

2024-01-14 06:36:10.1|Info|InstallUpdateService|Downloading update 5.3.1.8438
2024-01-14 06:36:31.0|Info|InstallUpdateService|Verifying update package
2024-01-14 06:36:31.2|Info|InstallUpdateService|Update package verified successfully
2024-01-14 06:36:31.2|Info|InstallUpdateService|Extracting Update package
2024-01-14 06:36:39.4|Info|InstallUpdateService|Update package extracted successfully
2024-01-14 06:36:39.4|Info|BackupService|Starting Backup
2024-01-14 06:36:55.4|Info|InstallUpdateService|Preparing client
2024-01-14 06:36:56.5|Info|InstallUpdateService|Starting update client C:\WINDOWS\TEMP\radarr_update\Radarr.Update.exe
2024-01-14 06:36:56.5|Info|InstallUpdateService|Radarr will restart shortly.
2024-01-14 06:36:57.3|Info|Microsoft.Hosting.Lifetime|Application is shutting down...
2024-01-14 06:36:57.3|Info|ConsoleApp|Exiting main.
2024-01-14 06:37:08.2|Info|Bootstrap|Starting Radarr - C:\ProgramData\Radarr\bin\radarr.console.exe - Version 5.3.1.8438
2024-01-14 06:37:12.3|Info|MigrationController|*** Migrating data source=C:\ProgramData\Radarr\radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 ***
2024-01-14 06:37:13.3|Info|MigrationController|*** Migrating data source=C:\ProgramData\Radarr\logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 ***
2024-01-14 06:37:14.4|Info|Microsoft.Hosting.Lifetime|Now listening on: http://[::]:8083
2024-01-14 06:37:14.7|Info|CommandExecutor|Starting 2 threads for tasks.
2024-01-14 06:37:14.8|Info|Microsoft.Hosting.Lifetime|Application started. Hosting environment: Production; Content root path: C:\ProgramData\Radarr\bin\
2024-01-14 06:37:16.6|Warn|ArgumentValidator|value [M:]  is not a valid Windows path. paths must be a full path e.g. C:\Windows
2024-01-14 06:37:16.6|Error|TaskExtensions|Task Error

[v5.3.1.8438] System.ArgumentException: value [M:]  is not a valid Windows path. paths must be a full path e.g. C:\Windows (Parameter 'path')
   at NzbDrone.Common.EnsureThat.EnsureStringExtensions.IsValidPath(Param`1 param, PathValidationType validationType) in ./Radarr.Common/EnsureThat/EnsureStringExtensions.cs:line 129
   at NzbDrone.Common.Disk.DiskProviderBase.FolderExists(String path) in ./Radarr.Common/Disk/DiskProviderBase.cs:line 96
   at NzbDrone.Core.HealthCheck.Checks.MovieCollectionRootFolderCheck.Check() in ./Radarr.Core/HealthCheck/Checks/MovieCollectionRootFolderCheck.cs:line 41
   at NzbDrone.Core.HealthCheck.HealthCheckService.<ProcessHealthChecks>b__15_0(IProvideHealthCheck c) in ./Radarr.Core/HealthCheck/HealthCheckService.cs:line 98
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.HealthCheck.HealthCheckService.ProcessHealthChecks() in ./Radarr.Core/HealthCheck/HealthCheckService.cs:line 85
   at NzbDrone.Core.HealthCheck.HealthCheckService.HandleAsync(ApplicationStartedEvent message) in ./Radarr.Core/HealthCheck/HealthCheckService.cs:line 162
   at NzbDrone.Core.Messaging.Events.EventAggregator.<>c__DisplayClass6_2`1.<PublishEvent>b__2() in ./Radarr.Core/Messaging/Events/EventAggregator.cs:line 120
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

2024-01-14 06:41:44.9|Info|RssSyncService|Starting RSS Sync
2024-01-14 06:41:45.8|Info|DownloadDecisionMaker|Processing 100 releases
2024-01-14 06:41:46.7|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 0
2024-01-14 06:52:15.9|Warn|ArgumentValidator|value [M:]  is not a valid Windows path. paths must be a full path e.g. C:\Windows
2024-01-14 06:52:15.9|Error|TaskExtensions|Task Error

[v5.3.1.8438] System.ArgumentException: value [M:]  is not a valid Windows path. paths must be a full path e.g. C:\Windows (Parameter 'path')
   at NzbDrone.Common.EnsureThat.EnsureStringExtensions.IsValidPath(Param`1 param, PathValidationType validationType) in ./Radarr.Common/EnsureThat/EnsureStringExtensions.cs:line 119
   at NzbDrone.Common.Disk.DiskProviderBase.FolderExists(String path) in ./Radarr.Common/Disk/DiskProviderBase.cs:line 97
   at NzbDrone.Core.HealthCheck.Checks.MovieCollectionRootFolderCheck.Check() in ./Radarr.Core/HealthCheck/Checks/MovieCollectionRootFolderCheck.cs:line 41
   at NzbDrone.Core.HealthCheck.HealthCheckService.<ProcessHealthChecks>b__15_0(IProvideHealthCheck c) in ./Radarr.Core/HealthCheck/HealthCheckService.cs:line 98
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at NzbDrone.Core.HealthCheck.HealthCheckService.ProcessHealthChecks() in ./Radarr.Core/HealthCheck/HealthCheckService.cs:line 85
   at NzbDrone.Core.HealthCheck.HealthCheckService.HandleAsync(IEvent message) in ./Radarr.Core/HealthCheck/HealthCheckService.cs:line 187
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)`

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by redglory** [comment]
Hi @mynameisbogdan 

I've traced back to version 5.3.1.8415 the first time I've got this problem:

`2024-01-08 06:31:20.6|Error|CommandExecutor|Error occurred while executing task CheckHealth

[v5.3.1.8415] System.ArgumentException: value [M:]  is not a valid Windows path. paths must be a full path e.g. C:\Windows (Parameter 'path')
   at NzbDrone.Common.EnsureThat.EnsureStringExtensions.IsValidPath(Param`1 param, PathValidationType validationType) in ./Radarr.Common/EnsureThat/EnsureStringExtensions.cs:line 119
   at NzbDrone.Common.Disk.DiskProviderBase.FolderExists(String path) in ./Radarr.Common/Disk/DiskProviderBase.cs:line 97
   at NzbDrone.Core.HealthCheck.Checks.MovieCollectionRootFolderCheck.Check() in ./Radarr.Core/HealthCheck/Checks/MovieCollectionRootFolderCheck.cs:line 41
   at NzbDrone.Core.HealthCheck.HealthCheckService.<ProcessHealthChecks>b__15_0(IProvideHealthCheck c) in ./Radarr.Core/HealthCheck/HealthCheckService.cs:line 97
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at NzbDrone.Core.HealthCheck.HealthCheckService.ProcessHealthChecks() in ./Radarr.Core/HealthCheck/HealthCheckService.cs:line 85
   at NzbDrone.Core.HealthCheck.HealthCheckService.Execute(CheckHealthCommand message) in ./Radarr.Core/HealthCheck/HealthCheckService.cs:line 149
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in ./Radarr.Core/Messaging/Commands/CommandExecutor.cs:line 113
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in ./Radarr.Core/Messaging/Commands/CommandExecutor.cs:line 44`

So I believe it was on this upgraded version:
`Updating Radarr from version 5.3.0.8410 to version 5.3.1.8415`

**Comment by redglory** [comment]
I've just installed latest 5.3.3.8535 version and all went ok, Radarr as just started without an issue with my configs.

Thanks
