### ISSUE TITLE
When error occurs in file importing due to ffprobe, user isn't informed

### ISSUE THREAD

**Issue by Lagicrus** [Radarr/Radarr#9814]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When I was manually importing a file with a `.arj` extension, Sonarr told me it was importing then stopped, didn't tell me if it failed or succeeded.
Going by the logs this is because ffprobe failed on the file, this being because `arj` is a archive format.

### Describe the solution you'd like

When manually importing a file where ffprobe fails, inform the user that this occurred perhaps along with why i.e. not a media type file (not mkv, ts, mp4, etc)

### Describe alternatives you've considered

Just checking the logs is possible yes, but it would be nice if shown to the user easily without needing to dig through logs.

### Anything else?

Here are the censored logs that show where what error appears in the logs when this happens.
```
2024-03-01 08:52:18.2|Error|VideoFileInfoReader|Unable to parse media info from file: /files/removed.arj

[v5.2.6.8376] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - /files/removed.arj: Invalid data found when processing input)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in ./Radarr.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs:line 140


2024-03-01 08:52:18.3|Error|DetectSample|Failed to get runtime from the file, make sure ffprobe is available
2024-03-01 08:52:18.4|Error|VideoFileInfoReader|Unable to parse media info from file: /files/removed.arj

[v5.2.6.8376] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - /files/removed.arj: Invalid data found when processing input)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in ./Radarr.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs:line 140


2024-03-01 08:52:18.4|Error|DetectSample|Failed to get runtime from the file, make sure ffprobe is available
2024-03-01 08:52:24.6|Warn|ImportApprovedMovie|Couldn't import movie /files/removed.arj

[v5.2.6.8376] System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at NzbDrone.Core.MediaFiles.MediaInfo.UpdateMediaInfoService.UpdateMediaInfo(MovieFile movieFile, Movie movie) in ./Radarr.Core/MediaFiles/MediaInfo/UpdateMediaInfoService.cs:line 71
   at NzbDrone.Core.Organizer.FileNameBuilder.UpdateMediaInfoIfNeeded(String pattern, MovieFile movieFile, Movie movie) in ./Radarr.Core/Organizer/FileNameBuilder.cs:line 504
   at NzbDrone.Core.Organizer.FileNameBuilder.BuildFileName(Movie movie, MovieFile movieFile, NamingConfig namingConfig, List`1 customFormats) in ./Radarr.Core/Organizer/FileNameBuilder.cs:line 115
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in ./Radarr.Core/MediaFiles/MovieFileMovingService.cs:line 75
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in ./Radarr.Core/MediaFiles/UpgradeMediaFileService.cs:line 41
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in ./Radarr.Core/MediaFiles/MovieImport/ImportApprovedMovie.cs:line 129


2024-03-01 08:53:30.8|Error|VideoFileInfoReader|Unable to parse media info from file: /files/removed.arj

[v5.2.6.8376] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - /files/removed.arj: Invalid data found when processing input)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in ./Radarr.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs:line 140


2024-03-01 08:53:30.8|Error|DetectSample|Failed to get runtime from the file, make sure ffprobe is available
```

**Comment by bakerboy448** [comment]
Believe this is already done in develop https://github.com/Radarr/Radarr/commit/e73015010e7d73fa01c44b8e49b75bbf5bd99061
