### ISSUE TITLE
Couldn't process tracked download... Expected one movie, but found 2 (mergerfs)

### ISSUE THREAD

**Issue by Markomas** [Radarr/Radarr#9891]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Movie import fail when using mergerfs, it looks that radarr sees two files instead of one.

### Expected Behavior

Movie import successful, or have the ability to force import.

### Steps To Reproduce

I suspect that's incompatibility with mergerfs, for example mc sees duplicate files (this is known issue). 

Under the hood there is only one file:
ls /data/data/*/data/torrent/ | grep Princess
The.Princess.2022.WEB-DL.2160p.x265.HDR.LT.RU.EN.mkv

Merging two filesystems should produce this issue

A year old version of radarr worked fine (don't know exact version when this issue started to happen)

### Environment

```markdown
- OS: Debian bullseye
- Radarr: 5.3.6.8612-ls211 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: 115.9.0esr (64-bit)
- Database: Sqlite 3.44.2
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

```
2024-04-06 03:25:23.4|Debug|Parser|Parsing string 'The.Princess.2022.WEB-DL.2160p.x265.HDR.LT.RU.EN.mkv'
2024-04-06 03:25:23.4|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2024-04-06 03:25:23.4|Debug|Parser|Movie Parsed. The Princess - 2022 
2024-04-06 03:25:23.4|Debug|Parser|Release Group parsed: 
2024-04-06 03:25:23.4|Debug|Parser|Languages parsed: Lithuanian, Russian
2024-04-06 03:25:23.4|Debug|QualityParser|Trying to parse quality for 'The.Princess.2022.WEB-DL.2160p.x265.HDR.LT.RU.EN.mkv'
2024-04-06 03:25:23.4|Debug|Parser|Quality parsed: WEBDL-2160p v1
2024-04-06 03:25:23.4|Debug|Parser|Edition parsed: 
2024-04-06 03:25:23.4|Debug|TrackedDownloadService|Found multiple movies for The.Princess.2022.WEB-DL.2160p.x265.HDR.LT.RU.EN.mkv

[v5.3.6.8612] NzbDrone.Core.Movies.MultipleMoviesFoundException: Expected one movie, but found 2. Matching movies: [The Princess (2022)][tt15738214, 1008779],[The Princess (2022)][tt13406136, 759175]
   at NzbDrone.Core.Movies.MovieService.ReturnSingleMovieOrThrow(List`1 movies) in ./Radarr.Core/Movies/MovieService.cs:line 384
   at NzbDrone.Core.Parser.ParsingService.TryGetMovieByTitleAndOrYear(ParsedMovieInfo parsedMovieInfo) in ./Radarr.Core/Parser/ParsingService.cs:line 204
   at NzbDrone.Core.Parser.ParsingService.FindMovie(ParsedMovieInfo parsedMovieInfo, String imdbId, Int32 tmdbId, SearchCriteriaBase searchCriteria) in ./Radarr.Core/Parser/ParsingService.cs:line 150
   at NzbDrone.Core.Parser.ParsingService.Map(ParsedMovieInfo parsedMovieInfo, String imdbId, Int32 tmdbId, SearchCriteriaBase searchCriteria) in ./Radarr.Core/Parser/ParsingService.cs:line 82
   at NzbDrone.Core.Download.TrackedDownloads.TrackedDownloadService.TrackDownload(DownloadClientDefinition downloadClient, DownloadClientItem downloadItem) in ./Radarr.Core/Download/TrackedDownloads/TrackedDownloadService.cs:line 195


2024-04-06 03:25:23.4|Debug|Parser|Parsing string 'The.Princess.2022.WEB-DL.2160p.x265.HDR.LT.RU.EN.mkv'
2024-04-06 03:25:23.4|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2024-04-06 03:25:23.4|Debug|Parser|Movie Parsed. The Princess - 2022 
2024-04-06 03:25:23.4|Debug|Parser|Release Group parsed: 
2024-04-06 03:25:23.4|Debug|Parser|Languages parsed: Lithuanian, Russian
2024-04-06 03:25:23.4|Debug|QualityParser|Trying to parse quality for 'The.Princess.2022.WEB-DL.2160p.x265.HDR.LT.RU.EN.mkv'
2024-04-06 03:25:23.4|Debug|Parser|Quality parsed: WEBDL-2160p v1
2024-04-06 03:25:23.4|Debug|Parser|Edition parsed: 
2024-04-06 03:25:23.4|Error|DownloadMonitoringService|Couldn't process tracked download The.Princess.2022.WEB-DL.2160p.x265.HDR.LT.RU.EN.mkv

[v5.3.6.8612] NzbDrone.Core.Movies.MultipleMoviesFoundException: Expected one movie, but found 2. Matching movies: [The Princess (2022)][tt15738214, 1008779],[The Princess (2022)][tt13406136, 759175]
   at NzbDrone.Core.Movies.MovieService.ReturnSingleMovieOrThrow(List`1 movies) in ./Radarr.Core/Movies/MovieService.cs:line 384
   at NzbDrone.Core.Parser.ParsingService.TryGetMovieByTitleAndOrYear(ParsedMovieInfo parsedMovieInfo) in ./Radarr.Core/Parser/ParsingService.cs:line 204
   at NzbDrone.Core.Parser.ParsingService.GetMovie(String title) in ./Radarr.Core/Parser/ParsingService.cs:line 77
   at NzbDrone.Core.Download.CompletedDownloadService.Check(TrackedDownload trackedDownload) in ./Radarr.Core/Download/CompletedDownloadService.cs:line 116
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientItem(IDownloadClient downloadClient, DownloadClientItem downloadItem) in ./Radarr.Core/Download/TrackedDownloads/DownloadMonitoringService.cs:line 135

```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Nothing to do with mergerfs. You have two movies with the same name in the same year in radarr thus you must tell radarr which movie it's for
